= Lisk Core Upgrade with Lisk Commander
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Commander Upgrade page describes how to upgrade Lisk Core to the latest version via Lisk Commander.
:toc:
:v_core: 2.1.3

NOTE: The `core:upgrade` command is only supported for Lisk Core versions greater than 2.0.0.

== Upgrade

[tabs]
=====
Mainnet::
+
--
To upgrade Lisk Core, run the following command in your terminal:

[source,bash]
----
lisk core:upgrade lisk-mainnet <1>
----
<1> Exchange `INSTANCE` with the name of your Lisk Core instance, which you chose during the xref:setup/commander.adoc[Installation of Lisk Core].
--
Testnet::
+
--
To upgrade Lisk Core, run the following command in your terminal:

[source,bash]
----
lisk core:upgrade lisk-testnet <1>
----
<1> Exchange `INSTANCE` with the name of your Lisk Core instance, which you chose during the xref:setup/commander.adoc[Installation of Lisk Core].
--
=====

[TIP]
====
If you forgot the name of the Lisk instance, have a look into the `instances` directory:

[source,bash]
----
ls ~/.lisk/instances/ <1>
----
<1> Lists all available Lisk Core instances
====

== Available options

Add one or multiple of the options below to the `core:upgrade` command. Multiple options are seperated by spaces.

|===
| Full Name | Short Name | Examples | Description

| `--release-url` | `-r`
| `--release-url=https://my-custom.url/testnet/2.1.0-rc.0/lisk-2.1.0-rc.0-Linux-x86_64.tar.gz`
| Define a custom URL for downloading the new Lisk Core binary script.
You also need to have the checksum for the TAR file with the format 2.0.0-Linux-x86_64.tar.gz.SHA256 for the Commander to check the integrity of the binary.
You can refer to our https://downloads.lisk.io/lisk/mainnet/{v_core}/[binary release] for the file naming convention.

| `--lisk-version`
| N/A
a|
* `--lisk-version=2.0.0`
* `--lisk-version=2.1.3`
| Define the concrete version, Lisk Core should be upgraded to.
|===
