= Managing accounts
Mona Bärenfänger <mona@lightcurve.io>
:description: How to create and manage accounts including creating and sending transactions, transferring tokens & voting.
// Settings
:toc:
// Project URLs
:url_core_cli: v4@lisk-core::core-cli.adoc
:url_sdk_cli: v6@lisk-sdk::client-cli.adoc
:url_sdk_keyscreate: {url_sdk_cli}#keyscreate

The most convenient way to manage your account is to employ a user interface, such as Lisk Desktop.
However, it is possible to manage your account directly from the command-line with the CLI of a Lisk node.

The most important interactions are described below.

TIP: For more information about the available Lisk Core commands, check the CLI references for xref:{url_core_cli}[Lisk Core] and xref:{url_sdk_cli}[Lisk SDK].

== How account related data is stored on the blockchain

== Creating new account credentials

=== Creating the passphrase

A 12 word mnemonic passphrase is required as an input to generate all corresponding account credentials for an account.

You may choose the passphrase for yourself, or generate a new random passphrase.
If you wish to generate the the passphrase, the Lisk SDK provides simple commands for this, as described below.

To generate the passphrase quickly from the command-line, start the console:

[tabs]
=====
Lisk Core::
+
--
[source,bash]
----
lisk-core console
----
--
Lisk app::
+
--
[source,bash]
----
./bin/run console
----
--
=====

Generate a new mnemonic passphrase using the Lisk passphrase library:

----
 > lisk.passphrase.Mnemonic.generateMnemonic()
----

This will return a randomly generated 12 word mnemonic passphrase.

----
'anger system news one finger rifle kiss expect arena swift spirit decline'
----

=== Creating the other credentials

Next, use the xref:{url_sdk_keyscreate}[keys:create] command to generate all relevant account credentials:

[tabs]
=====
Lisk Core::
+
--
[source,bash]
----
lisk-core keys:create
----
--
Lisk app::
+
--
[source,bash]
----
./bin/run keys:create
----
--
=====

When asked for the passphrase, enter the passphrase created in step <<creating-the-passphrase>>.

----
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
----

Next, you will be also asked for a password.
This password will be used to encrypt your account credentials symmetrically.

The encrypted credentials are used for example in the config, when the node needs account information to generate new blocks for a validator.

TIP: If you don't wish to encrypt your credentials, it is possible to skip this step by adding the `--no-encryption` flag to the `keys:create` command.

The password will be required everytime the credentials need to be decrypted, for example when enabling block generation on a node.
Therefore, the password should be saved and kept at a secure place, similar to the passphrase of the account.

----
? Please enter password:  [hidden]
? Please re-enter password:  [hidden]
----

This will then return the credentials for the account:

.Example output
[%collapsible]
====
[source,json]
----
{
  "keys": [
    {
      "address": "lsk7dqp2w7447pqhuzmhxsxr65qeoq7nbfox28wxc",
      "keyPath": "m/44'/134'/0'",
      "publicKey": "0ca6a5d44cc366de186a2589e3e51849272fa0ae9c52646766ddb7820dfe770c",
      "privateKey": "bd7e42529df375cb9133ddf299641d38975fa4d0930eff6e7c072d4d3ff190830ca6a5d44cc366de186a2589e3e51849272fa0ae9c52646766ddb7820dfe770c",
      "plain": {
        "generatorKeyPath": "m/25519'/134'/0'/0'",
        "generatorKey": "e59f2f603b84b9c491e267240a3425a09adaad348b984cc6e21c14fd02f28e7e",
        "generatorPrivateKey": "398a04e2a001dc4580bb1fab2c6e71dbbbd81c9f22170e1073cd4084d81588f4e59f2f603b84b9c491e267240a3425a09adaad348b984cc6e21c14fd02f28e7e",
        "blsKeyPath": "m/12381/134/0/0",
        "blsKey": "95c7a571ecf569f91f6995f9a8d8a2e70904cb079350372b66d8a2b6986788f6d4589c79fffefd952debc96a17317e18",
        "blsProofOfPossession": "a02f2672621b3adcd25079c6646e751517c514c70d11ec4ec4846310f5f7cddedd598ade849496bcfe15d3baa554d06b148a2e9f2d349e2010df2a17d7a3d57f13ab9bf290042c552d47d925c0877596ca8865b96ba2972eea5ce7831b014cca",
        "blsPrivateKey": "4ce94d4439152ec5e0ae88a5c77c12cf0b5d9304111359c5f42b490503429c26"
      },
      "encrypted": {
        "ciphertext": "5cc26d74c2b6ed7d56a1268eb04cd3878190695bd2546bca82885cc5d7171d71e397cab265544436d9feadd143e17deeeb5f32a00e6d6cf8d0e64afc5475067875a6836a5c7f78d3e0b4937c464817f40359c869bd0b01762a18169296774d1c76821a752e53dc96390c27a15ba8b1b3eef7016335dabcef424ed0dd3bf972f89451d2ea8db113b310e9ecda7ea3a044c68e4dc57f8c992e84729c62f952c7c24688f375b39311ef069d8a2ccde6c272ce65645839da3dfb",
        "mac": "ebdb87bb0be482ea6ec867bb3355d3c9aece28520d56d7b1c17463dc06e1eb97",
        "kdf": "argon2id",
        "kdfparams": {
          "parallelism": 4,
          "iterations": 1,
          "memorySize": 2024,
          "salt": "63092ee970b05d28017a606c39ff799b"
        },
        "cipher": "aes-256-gcm",
        "cipherparams": {
          "iv": "1a188eb0d5eab9eca50b7b3c",
          "tag": "2578354b532bec4485eeb7123c27f855"
        },
        "version": "1"
      }
    }
  ]
}
----
====

=== Managing multiple accounts with a single passphrase

Key derivation allows multiple key pairs to be derived from the same secret passphrase as a tree of keys.

This means, a user can manage multiple different accounts, while they only need to remember a single passphrase.

To generate multiple accounts from the same passphrase, use the `--count` flag of the `keys:create` command, and set it to the number of accounts that you wish to create.

The key path for the new accounts will always start with the default key-derivation path and increment by +1 onwards.
If you wish to start from a different key path, you can specify an `--offset`.

[tabs]
=====
Lisk Core::
+
--
[source,bash]
----
lisk-core keys:create --passphrase your-passphrase --no-encrypt --count 2 --offset 1
----
--
Lisk app::
+
--
[source,bash]
----
./bin/run keys:create --passphrase your-passphrase --no-encrypt --count 2 --offset 1
----
--
=====

They can use the same passphrase for every account, the only thing that will change is the key-derivation path.
The *key derivation path* allows to derive a specific key from within a tree of keys.

[NOTE]
====
If a user uses the default key-derivation path `m/44'/134'/0`, it is not necessary to mention it as a parameter when the account credentials are requested.
If you are using a custom key-derivation path, make sure to always specify the key derivation path when providing the passphrase.
For example, for the `transaction:create` command, you can specify the key derivation path like so:

 % ./bin/run transaction:create hello createHello 10000000 --key-derivation-path="m/44'/134'/1'" --params='{"message":"Hello world!"}'

====

== Overview of the account credentials

.Account credentials
[cols="1,1,2",options="header",stripes="hover"]
|===
|Type
|Name
|Description

|General credentials
|`address`
|description

|General credentials
|`keyPath`
|description

|General credentials
|`publicKey`
|description

|General credentials
|`privateKey`
|description

|Credentials required for block generation
|`generatorKeyPath`
|description

|Credentials required for block generation
|`generatorKey`
|description

|Credentials required for block generation
|`generatorPrivateKey`
|description

|Credentials required for block generation
|`blsKeyPath`
|description

|Credentials required for block generation
|`blsKey`
|description

|Credentials required for block generation
|`blsProofOfPossession`
|description

|Credentials required for block generation
|`blsPrivateKey`
|description

|===

=== Formats for account addresses

Format examples and explanations for what it is used

== Initializing a new account

How to initialize a new account in the network

