= How to enable/disable block generation
:toc: preamble
:idprefix:
:idseparator: -
:docs_sdk: v6@lisk-sdk::
// URLs
:url_sdk_cli_generatorenable: {docs_sdk}application-cli.adoc#generatorenable
:url_sdk_cli_generatordisable: {docs_sdk}application-cli.adoc#generatordisable
:url_run_validator: run-blockchain/become-a-validator.adoc
:url_run_validator_set_hashonion: run-blockchain/become-a-validator.adoc#set-the-hash-onion
:url_run_validator_get_hashonion: run-blockchain/become-a-validator.adoc#get-the-hash-onion
:url_run_validator_import: run-blockchain/become-a-validator.adoc#import-the-validator-keys
:url_run_validator_validator_keys: run-blockchain/become-a-validator.adoc#creating-the-validator-keys
:url_run_validator_data: run-blockchain/become-a-validator.adoc#validator-info-data
:url_staking: run-blockchain/staking.adoc

====
On this page, you'll learn how to enable and disable block generation on anode for a validator.

This includes how to:

* [x] Enable block generation
* [x] Safely re-enable block generation on another node
* [x] Safely re-enable block generation when the xref:{url_run_validator_data}[validator info data] is lost.
* [x] Disable block generation
====

== How to enable block generation on a node

IMPORTANT: The blockchain application needs to be running to successfully enable block generation on the node.

[CAUTION]
====
. Ensure the node is **fully synchronized** with the network, before enabling block generation on this node.
. If block generation is enabled for a validator for the **first time**, check out the dedicated guide xref:{url_run_validator}[].
. Ensure to adhere to the following points to avoid being punished by the network:
.. Never use outdated xref:{url_run_validator_data}[validator info data].
.. Never activate block generation for the same validator on two or more nodes at the same time.
====

=== Get the validator info data

WARNING: Don't trust xref:{url_run_validator_data}[validator info data] from public APIs or explorers, make sure to always use your local data!

[tabs]
=====
Lisk Core::
+
--
//TODO: Verify Lisk Core command
[source,bash]
----
lisk-core generator status --pretty
----
--
Sidechain node::
+
--
[source,bash]
----
./bin/run generator status --pretty
----
--
=====

This will return the following information for a validator who imported her/his keys to the node:

* `address`: The Lisk32 address of the validator.
* `enabled`: `true`, if the delegate has block generation enabled, `false` if not.
* The xref:{url_run_validator_data}[validator info data].

//TODO: Update with real example
.Example output
[source,json]
----
{
  "info": {
    "status":
    [{
        "address": "lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3",
        "height": 0,
        "maxHeightPrevoted": 0,
        "maxHeightGenerated": 0,
        "enabled": false
      }
  ]}
}
----

NOTE: If the command returns an empty array, you probably haven't imported your validators keys to the node.
In that case, follow the guide xref:{url_run_validator}[] to prepare the node for block generation.

=== Enable block generation

[tabs]
=====
Lisk Core::
+
--
//TODO: Add link to Core CLI reference, once the page is available
//Use the xref:{url_sdk_cli_generatorenable}[generator enable] command to enable block generation on your node.

//TODO: Verify Lisk Core command
.Enable block generation
[source,bash]
----
lisk-core generator enable lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3 --height=123 --max-height-generated=101 --max-height-prevoted=101
----
--
Sidechain node::
+
--
Use the xref:{url_sdk_cli_generatorenable}[generator enable] command to enable block generation on your node.

.Enable block generation
[source,bash]
----
./bin/run generator enable lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3 --height=123 --max-height-generated=101 --max-height-prevoted=101
----
--
=====

Replace `lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3` with your validator address.

Verify the correctness of the values `height`, `maxHeightPrevoted`, and `maxHeightPreviouslyForged` by answering `yes`, and use your password created in step xref:{url_run_validator_validator_keys}[Creating the validator keys] to decrypt the passphrase for block generation.

[TIP]
====
To prefill the validator info data automatically, add the flag `--use-status-values` to the `generator enable` command.

[source,bash]
----
lisk-core generator enable lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3 --use-status-values
----

//TODO: Update example snippet
[source,bash]
----
 Current block generation status for validator account lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3 is:
{"height":14814092,"maxHeightPrevoted":14814017,"maxHeightPreviouslyForged":14814025}
? Do you want to use the above values to enable block generation? yes
? Enter password to decrypt the encrypted passphrase:  **********
Updated block generation status:
{"address":"lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3","enabled":true}
----
====

== How to disable block generation on a node

If you wish to disable block generation on the node, follow the steps as described below.

[WARNING]
====
If you would like to *completely stop block generation* without being punished by the network, make sure to xref:{url_staking}[unstake] all self-stakes for a validator, before you disable block generation on the node.
====

[tabs]
=====
Lisk Core::
+
--
//TODO: Add link to Core CLI reference, once the page is available
//Use the xref:{url_sdk_cli_generatordisable}[generator disable] command to disable block generation on your node.

//TODO: Verify Lisk Core command
.Disable block generation
[source,bash]
----
lisk-core generator disable lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3
----
--
Sidechain node::
+
--
Use the xref:{url_sdk_cli_generatordisable}[generator disable] command to disable block generation on your node.

.Disable block generation
[source,bash]
----
./bin/run generator disable lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3
----
--
=====

Replace `lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3` with the address of your validator.

When prompted for a password, use the password that you defined while xref:{url_run_validator_validator_keys}[creating the validator keys].

== Safely enabling block generation on another node

To safely enable block generation on another node, please ensure to follow the steps below:

. Install a new node on another server.
. Start the node and let it synchronize with the network.
If available, it is recommended to synchronize from a snapshot, to speed up the synchronization process.
. Login to the server with the old node.
. <<how-to-disable-block-generation-on-a-node,Disable block generation>> on the old node.
. xref:{url_run_validator_get_hashonion}[Export the hash onion seed] used by the validator.
. Stop the old node.
. Export the validator info data from the old node.
+
[source,bash]
----
lisk-core generator export --output genInfo.json
----
. Login to the server with the new node.
. Restore the `forger_info` table.
+
[source,bash]
----
lisk-core generator import ./genInfo.json
----
. xref:{url_run_validator_import}[Import the validator keys].
. xref:{url_run_validator_set_hashonion}[Import the hash onion seed] used by the validator.
. Ensure the node is fully synchronized with the network.
The height of your node should be equal to the current network height.
+
[source,bash]
----
lisk-core node info
----
. <<get-the-validator-info-data>> to fetch the validator info data.
. <<how-to-enable-block-generation-on-a-node,Enable block generation>>.

//TODO: Review and update this paragraph if necessary as part of this issue: https://github.com/LiskHQ/lisk-docs/issues/1216
////
== Safely enabling forging without forger_info data

Configurable Constants::

* `BLOCK_TIME = 10`: The block time of the considered blockchain in seconds, i.e., 10 for Lisk Mainnet.
* `MAX_FORK_DEPTH = 8640`: An upper boundary on the largest chain of off-chain blocks for which the validator generated a block, i.e., for every block at height `h` generated by the validator, the parent block at height `h - MAX_FORK_DEPTH` must be contained in the canonical chain that is eventually finalized.
It is recommended to use `MAX_FORK_DEPTH` = 8640 = 24*60 *6 (number of blocks generated in 24 h).

Required Delegate Input::

* `lastHeightActive`: Unix timestamp of the last height when the validator node could have possibly been active and forging, (over estimate with a larger number when uncertain about the exact time).

Instructions::
. Start a new node with forging deactivated and synchronize with the Lisk blockchain until there is a block `finalizedBlock` that is
finalized, and that the finalized block header timestamp is greater than the last active height: `finalizedBlock.header.timestamp > lastHeightActive`
. Obtain a block `parentBlock` which is a parent block of `finalizedBlock` at height `finalizedBlock.header.height - MAX_FORK_DEPTH`.

 parentBlock.header.height = finalizedBlock.header.height - MAX_FORK_DEPTH

. Compute the number of missed blocks in the current chain between the `finalizedBlock` and the `parentBlock`, i.e., as shown below:

 missedBlocks = ceil((finalizedBlock.header.timestamp - parentBlock.header.timestamp)/BLOCK_TIME) - (finalizedBlock.header.height - parentBlock.header.height)

. Use the following forging configuration and activate forging:

 height = finalizedBlock.header.height
 maxHeightPreviouslyForged = finalizedBlock.header.height + missedBlocks
 heightPrevoted = finalizedBlock.header.height
////