= Monitoring a node
Muhammad Talha <muhammad.talha@lightcurve.io>
// Settings
:toc: preamble
:toclevels: 5
:page-toclevels: 3
:idprefix:
:idseparator: -
:sectnums:
:experimental:

// External URLs
:url_plugin_monitor: {site-url}/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_framework_monitor_plugin.html
:url_plugin_monitor_config: {site-url}/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_framework_monitor_plugin.html#$config-options
:url_cors_intro: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
:url_prometheus: https://prometheus.io/docs/introduction/overview/

// Project URLs
:url_guides_config: build-blockchain/configuration.adoc
:url_guides_config_hello: {url_guides_config}#example-configuration-for-the-hello-world-client
:url_core_index: v4@lisk-core::index.adoc

The {url_plugin_monitor}[Monitor plugin^] provides insights about a running node, for example, if a node is down or node is missing blocks, etc.
Monitor plugin takes the data reported by the {url_prometheus}[Prometheus (an open-source systems monitoring and alerting toolkit)^] and exposes the data into a standard format using the available endpoints.

//  automatic detection of a validator's misbehavior and sends the `reportMisbehavior` transaction to the running node.
// This transaction contains two xref:{url_blocks_header}[block headers] that are necessary to prove that the validator who generated the blocks has violated the {url_consensus_bft}[Lisk-BFT consensus protocol^] and is deemed to be punished{fn_lip24} once proven guilty.
//TODO: Replace the BFT LIP reference with Docs BFT consensus page, when ready.

====
On this page, you'll learn:

* [x] Registration of the Monitor plugin to a blockchain client.
* [x] Configuring the Monitor plugin
* [x] Discussing the Endpoints
====

Using this guide, the Monitor plugin can be registered to a xref:{url_core_index}[Lisk Core] node or any Lisk-based blockchain client.

== Plugin registration
With the latest version of Lisk Core v4 and Lisk SDK v6, the default plugins come pre-installed after a client is installed or initiated, respectively.
 
You can check the `package.json` file of the blockchain client to ensure the installation.

.hello_client/package.json
[source,json]
----
"dependencies": {
  //[...]
	"@liskhq/lisk-framework-monitor-plugin": "0.4.1",
	//[...]
},
----

Otherwise, you can install the Monitor plugin like this:
 
[source,bash]
----
npm install --save @liskhq/lisk-framework-monitor-plugin
----

There are various ways to enable the Monitor plugin.
You can opt for any of the below-mentioned to register the plugin to the blockchain client.

[IMPORTANT]
====
It is essential to enable WS API and configure the `allowedMethods` property before registering the `MonitorPlugin`.
For more information, see the configurations described in the xref:{url_guides_config_hello}[configuration guide].
====

=== Registering via source
For blockchain clients that were initialized with Lisk Commander, it is possible to register the plugin through the `plugins.ts` file.
Open the `plugins.ts` file, import the Report Misbehavior plugin, and register it with the application as shown below:

.src/app/plugins.ts
[source,typescript]
----
/* eslint-disable @typescript-eslint/no-empty-function */
import { MonitorPlugin } from '@liskhq/lisk-framework-monitor-plugin';
import { Application } from 'lisk-sdk';

export const registerPlugins = (app: Application): void => {
    app.registerPlugin(new MonitorPlugin ());
};

----

Save and close the `plugins.ts` file.

After updating the *plugins.ts* file, build the blockchain client again:

[source,bash]
----
npm run build
----

== Starting the node
Depending on how you chose to register the plugin, start the blockchain client, accordingly.

[tabs]
=====
Registered via built-in flag::
+
--
It is also possible to enable the Monitor plugin without updating the configuration, the `plugins.ts` file, or using PM2.
This can be done simply by adding the `--enable-monitor-plugin` flag to the `start` command.

.*Mainchain*
* Start the blockchain client with designated flags on a `mainchain` node.
+
[source,bash]
----
lisk-core start --network testnet --enable-monitor-plugin
----

.*Sidechain*
* *Or*, start the blockchain client with designated flags on a `sidechain` node.
+
[source,bash]
----
./bin/run start --config=config/custom_config.json --enable-monitor-plugin
----
--
Registered via Source::
+
--

.Start the blockchain client with custom_config.json
[source,bash]
----
./bin/run start --config=config/custom_config.json 
----
--
=====


== Configuring the Monitor Plugin
The Monitor plugin comes with a set of pre-defined configurations, which can be tweaked as per the node operator's needs.

[tabs]
=====
Available Configurations::
+
--
[cols="1,1,2,2",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`port`
|string
|Port where the monitor plugin runs.
|`4003`

|`host`
|string
|Hosts where the 
|`127.0.0.1`

|`whiteList`
|string
|Hosts that are 
|`['127.0.0.1']`

|`cors`
|string
|Defines the {url_cors_intro}[CORS^] properties such as `origin` and allowed `methods` which should be entertained by the Monitor plugin.
a|
[source,json]
----
cors: {
			origin: '*',
			methods: ['GET', 'POST', 'PUT'],
		},
----

|`limits`
|string
|Defines various types of limits for example: `max`, `delayMs`, `delayeAfter`, `windowMs`, `headersTimeout`, and `serverSetTimeout` for the monitor plugin.
a|
[source,json]
----
limits: {
    max: 0,
    delayMs: 0,
    delayAfter: 0,
    windowMs: 60000,
    headersTimeout: 5000,
    serverSetTimeout: 20000,
},
----
|===
--
Usage::
+
--
.config.json
[source,json]
----
"plugins": {
    "monitor": {
        "port": "9000"
    }
}
----
--
=====


== Retrieving data
The monitor plugin exposes four endpoints which return important data about a validator's node.
