= Process management with pm2
Muhammad Talha <muhammad.talha@lightcurve.io>
//Settings
:toc:
:toc: preamble

// External URLs
:url_pm2_docs: https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/
:url_global_cli: build-blockchain/create-blockchain-app.adoc#using-the-application-cli-globally

It is recommended to set up additional process management with a sidechain client.
Any process management tool can be used to manage the sidechain client.
We recommend using PM2 to manage the instance.

== Setup

Install pm2 globally:

[source,bash]
----
npm i -g pm2
----

== PM2 config
Create a pm2 config, for example as shown below:

.pm2.conf.json
[source,json]
----
{
  "name": "hello_client",
  "script": "hello_client start --config=config/custom_config.json",
  "env": {
    "LISK_NETWORK": "testnet",
    "LISK_CONFIG_FILE": "/home/.lisk/hello_client/custom_config.json"
  }
}
----

TIP: All available options for `scripts` and `env` can be found in `hello_client --help`.

To add the process to PM2 and start it directly, execute the following command:

[source,bash]
----
pm2 start pm2.conf.json
----

== Show status

View the status of the sidechain client in the list of running PM2 processes:

[source,bash]
----
pm2 ls
----

----
┌────┬──────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name         │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼──────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ hello_client │ fork     │ 0    │ online    │ 0%       │ 3.1mb    │
└────┴──────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
----

== Starting a Client Lisk Core with PM2

Execute the following command to start a Sidechain client node:
[source,bash]
----
pm2 start hello_client
----


== Saving the app list to be restored at reboot

Once a sidechain client has started, it is convenient to save the app list so it will respawn after rebooting:

[source,bash]
----
pm2 save
----

For more information, please refer to {url_pm2_docs}[^]

== Stopping a sidechain client
Execute the following command to stop a Sidechain client node:
[source,bash]
----
pm2 stop hello_client
----

== Refreshing a node
To refresh a node after changing the configuration, delete the existing process with pm2, and then use the pm2 config file to restart the process.

Execute the following command to restart a sidechain client:
[source,bash]
----
pm2 delete hello_client
pm2 start pm2.conf.json
----

== Restarting a node
Execute the following command to restart a sidechain client:
[source,bash]
----
pm2 restart hello_client
----
