= How share block Rewards
Muhammad Talha <muhammad.talha@lightcurve.io>
:toc: preamble
:toclevels: 5
:page-toclevels: 3
:idprefix:
:idseparator: -
:sectnums:
:experimental:

:url_staking_guide: run-blockchain/staking.adoc
:url_getStaker: api/module-rpc-api/pos-endpoints.adoc#pos_getstaker


:url_lip_70: https://github.com/LiskHQ/lips/blob/350d08a90bdbedb3485363a40dd34f3ccadf0b7d/proposals/lip-0070.md

On this page, we'll talk about how a registered validator can enable reward sharing with its stakers and how such rewards can be later claimed.

== What is reward sharing?

In Lisk protocol, validators receive rewards for generating blocks. The set of validators that generate blocks is chosen based on the total stake of each validator (self-stake and sum of staked amounts from stakers).

Rewards are shared between validators and stakers as follows: a certain part of the rewards is awarded to the validator as a commission (the precise percentage of the commission is chosen by each validator); then, the remaining rewards are shared by the validator and the stakers proportionally to their staked amounts.

The reward sharing mechanism is part of the PoS module. To learn more about how reward sharing works in Lisk Protocol, see Lip {url_lip_70}[LIP 70^].

The values of all constants related to commissions are between *0* and *10000*, corresponding to percentages with two decimal places, which can be obtained by dividing the value by *100*. For example, a commission value of *1000*, corresponds to a *10%* commission.

Initially, after validator's registration the commission of a validator is initialized with 100%. Afterwards, it can be decreased by submitting a commission change transaction.

== Prerequisites and Background

* To earn rewards, stake LSKs for an actively block generating validator. To learn more about staking, see xref:{url_staking_guide}[].

Once you successfully stake for a validator, you can see your stakes by invoking the xref:{url_getStaker}[pos_getStaker] endpoint:
Each time a validator becomes part of the block generation round, there are chances that they will be selected to generate an upcoming block. 
To check the if the validator is in the list of active validators, see the response of consensus_getBFTParameters.
If the validator is in the returned list then, soon your validator will be generating a block in a round and as a result will earn rewards.

Block rewards are distributed after the `offset` height is reached. By default, the value of offset is `2160`.
After reaching the offset height, rewards for each validator are credited to their account.
The estimated rewards of a validator can be checked via the `dynamicReward_getExpectedValidatorRewards` endpoint.

Once the validator generated a block, Lisk Protocol automatically, increments the `lockedBalance` and `availableBalance` of the validators account.