= Enable forging
Mona Bärenfänger <mona@lightcurve.io>
:description: The forging guide explains how to enable, disable and check forging on the respective user's node.
:toc:
:v_protocol: master
:sectnums:
:sectnumlevels: 1
:url_guides_api_access: guides/node-management/api-access.adoc
:url_commander_commands: references/lisk-commander/commands.adoc
:url_elements_crytpography: references/lisk-elements/cryptography.adoc
:url_explanations_consensus: explanations/consensus.adoc#forging
:url_explanations_consensus_register: explanations/consensus.adoc#delegate_registration
:url_guides_config: guides/app-development/configuration.adoc

:url_protocol_block_forgers: {v_protocol}@lisk-protocol::blocks.adoc#forgers
:url_protocol_dpos: {v_protocol}@lisk-protocol::consensus-algorithm.adoc
:url_protocol_delegate_selection: {v_protocol}@lisk-protocol::consensus-algorithm.adoc#delegate_selection
:url_protocol_blocks_punishment: {v_protocol}@lisk-protocol::consensus-algorithm.adoc#punishment

The enable forging guide describes how to enable forging on a node as a delegate.

How to register as delegate is explained in xref:{url_explanations_consensus_register}[Consensus in Lisk - Registering as delegate]

For more information about forging, please check the explanations in xref:{url_explanations_consensus}[Consensus in Lisk - Forging].

[[config_forging_data]]
== Add forging data to config

To enable your node to forge for a particular delegate, firstly it is required to insert some data into the config file under the `forging.delegates` array:

* `publicKey`: The publicKey of the delegate.
* `encryptedPassphrase`: The symmetrically enrypted 12 word mnemonic passphrase of the delegate account.

To encrypt your passphrase, it is recommended to use one of the following alternatives listed below:

* xref:{url_commander_commands}[Lisk Commander] via `encrypt passphrase` command.
* xref:{url_elements_crytpography}[Cryptography package of Lisk Elements]

The first alternative with the Lisk Commander is described in detail below.
Please ensure the Lisk Commander is installed in a secure environment.
Upon completion, please follow these commands to generate the encrypted passphrase:

[source,bash]
----
$ lisk
lisk passphrase:encrypt --outputPublicKey
Please enter your secret passphrase: ***** <1>
Please re-enter your secret passphrase: *****
Please enter your password: *** <2>
Please re-enter your password: ***
{
        "encryptedPassphrase": "iterations=1000000&cipherText=30a3c8&iv=b0d7322bf24e0dfe08462f4f&salt=aa7e26c9f4317b61b4f45b5c6909f941&tag=a2e0eadaf1f11a10b342965bc3bafc68&version=1",
        "publicKey": "a4465fd76c16fcc458448076372abf1912cc5b150663a64dffefe550f96feadd"
}
----

<1> Enter the secret passphrase here that needs to be encrypted.
<2> Enter the password here that will be required to decrypt the passphrase again.

* Type in the passphrase followed by the password required for encryption.
* This will result in the creation of an `encryptedPassphrase` key-value pair.
* Add the JSON object to the config under `forging.delegates` as can be seen below:

[source,js]
----
{
  forging: {
    force: false,
    delegates: [ <1>
        {
            encryptedPassphrase: "iterations=1&salt=476d4299531718af8c88156aab0bb7d6&cipherText=663dde611776d87029ec188dc616d96d813ecabcef62ed0ad05ffe30528f5462c8d499db943ba2ded55c3b7c506815d8db1c2d4c35121e1d27e740dc41f6c405ce8ab8e3120b23f546d8b35823a30639&iv=1a83940b72adc57ec060a648&tag=b5b1e6c6e225c428a4473735bc8f1fc9&version=1",
            publicKey: "9d3058175acab969f41ad9b86f7a2926c74258670fe56b37c429c01fca9f2f0f"
        }
    ],
  },
  modules: {
    http_api: {
      access: {
        whiteList: ["127.0.0.1", "REPLACE_ME"], <2>
      }
    }
  }
}
----

<1>  The list of delegates who are allowed to forge on this node.
<2> Replace with the IP address which will be used to access the node.

Now restart the node to apply the changes in the config.

For more information about the configuration of the Lisk SDK check out the xref:{url_guides_config}[configuration guide].

[[forging_enable_disable]]
== Enable/Disable Forging

[CAUTION]
====
Do not activate forging for the same delegate on multiple nodes.
This behaviour will be xref:{url_protocol_blocks_punishment}[punished] by the network.

In case you want to change the node you are forging on, check the section <<safely_activating_forging,Enabling forging on another node>>.

'''

Make sure your node is **fully synchronized** with the network, before you enable forging.
====

If the node is running on your local machine, it is possible to enable forging via the API, without any further interruption.
If you want to enable forging from remote, ensure to whitelist the remote IP like described in the xref:{url_guides_api_access}[API access guide].

Use the following curl command to *enable the forging* for your delegate:

.Enable forging
[source,bash]
----
curl -X PUT \
  http://127.0.0.1:4000/api/node/status/forging \ <1>
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
          "publicKey": "YYYYYYYYY", <2>
          "password": "XXX", <3>
          "forging": true <4>
      }'
----

<1> Replace `127.0.0.1` with the IP of your Lisk node, if you run the command from remote.
<2> `publicKey` is the key for the delegate which is required to be enabled/disabled.
<3> `password` is the password used to encrypt your passphrase in the config.
<4> `forging` is the boolean value to enable or disable the forging.

Use the following curl command to *disable the forging* for your delegate:

[[disable]]
.Disable forging
[source,bash]
----
curl -X PUT \
  http://127.0.0.1:4000/api/node/status/forging \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
          "publicKey": "YYYYYYYYY",
          "password": "XXX",
          "forging": false <1>
      }'
----

<1> Change forging to `false` to disable forging for a delegate on the node.

[NOTE]
====
The endpoints to enable and disable forging are *idempotent*.

This means that the results are identical, regardless of how many times the query is executed.
====

[[safely_activating_forging]]
=== Safely enabling forging on another node

To safely enable forging on another node, make sure to follow the steps below:

. Setup a new node on another server.
. Start the node and let it synchronize with the network.
If available, it is recommended to synchronize from snapshots, to speed up the synchronisation process.
. Login to the server with the old node.
. <<disable,Disable forging>> on the old node.
. Stop the old node.
. Dump the data in the `forger_info` table of the db of your node.
+
[source,bash]
----
pg_dump -d lisk_dev -t forger_info > forger_info.sql
----
. Login to the server with the new node.
. Restore the `forger_info` table.
+
[source,bash]
----
pg_restore -d lisk_dev -t forger_info forger_info.sql
----
. <<config_forging_data,Add the forging data to the config>>.
. Ensure node is fully synchronized with network.
The height of your node should be equal to the current network height.
+
[source,bash]
----
curl http://127.0.0.1:4000/api/node/status
----
. Ensure once again, that forging for this delegate is not enabled on other nodes. See the section <<check_forging, check forging>>
. <<forging_enable_disable,Enable forging>>.

//TODO
//==== Migrating to another forging node without access to the `forger_info` data
//
//In some edge cases, it is not possible to retrieve the latest `forger_info` data from the old node, e.g. if the database was destroyed or is not accessible anymore.
//
//In this cases, it is important to restore the `maxHeightPreviouslyForged` manually.

[[check_forging]]
== Check forging

Use the following `curl` command to verify the forging status of your delegate:

[source,bash]
----
curl \
  http://127.0.0.1:4000/api/node/status/forging \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json'
----

The result should appear as shown below in the following code snippet:

[source,json,linenums]
----
{
  "meta": {},
  "data": [
    {
      "forging": true,
      "publicKey": "9bc945f92141d5e11e97274c275d127dc7656dda5c8fcbf1df7d44827a732664"
    }
  ],
  "links": {}
}
----
