= Protecting a non-forging node
// Settings
:toc:
// External URLs
:url_haproxy: http://www.haproxy.org/
:url_haproxy_blog: https://www.haproxy.com/blog/the-four-essential-sections-of-an-haproxy-configuration/
// Project URLs
:url_plugin_http_api: references/lisk-framework/http-api-plugin.adoc

== Setting up a blockchain application behind a reverse proxy
This guide explains in a step-by-step process how to set up a blockchain application behind a reverse proxy.
The reasoning behind this is that it can sometimes be advantageous to run a blockchain application behind a reverse proxy for SSL termination, rate limiting, and other beneficial reasons.

*We highly recommended running a reverse proxy for a public web service*

{url_haproxy}[HAProxy^] is one such reverse proxy.

An HAProxy configuration has 4 sections, which are {url_haproxy_blog}[explained here^].
Firstly, the relevant sections that we are concerned with initially are the `frontend` and `backend`.
This is followed by starting out with a very basic config snippet and then building up from there.

[NOTE]
====
For this example to work, it is assumed that the application uses the default configuration for the WebSocket port, which is `8080`.

In the case whereby you have configured a different port, then replace `8080` with your alternative port in the example below.
====

[source,bash]
----
frontend f_lisk
        mode http
        bind :80 <1>
        use_backend b_lisk_ws <2>
backend b_lisk_ws
        server lisk_ws 127.0.0.1:8080 <3>
----

<1> A new `bind` line is added, which creates a listener on port 80.
<2> `use_backend` defines the backend which responds to incoming requests.
<3> `server` sets the backend server and expects a name as the first argument, and the IP and port as the second argument.

This does nothing more than proxy requests coming in at port 80 to your blockchain application WebSocket port.

=== SSL Termination
We can add SSL termination by telling it to listen on port 443 and specifying the certificate in the frontend section:

[source,bash]
----
frontend f_lisk
        mode http
        bind [::]:443 ssl crt /etc/haproxy/ssl/cert.pem alpn h2,http/1.1 <1>
        bind [::]:80 <2>
        http-response set-header Strict-Transport-Security max-age=15768000 <3>
        redirect scheme https code 301 <4>
        use_backend b_lisk_ws
----

<1> A new `bind` line is added, which performs the following:
* Listens on port 443.
* Specifies the SSL certificate.
* Enables the TLS ALPN extension, as described in the HAProxy documentation https://www.haproxy.com/documentation/aloha/12-5/traffic-management/lb-layer7/tls/
<2> The `bind` lines were changed so that HAProxy will also listen on IPv6.
<3> The `Strict-Transport-Security` response header is set to inform web browsers to only access this site via HTTPS.
<4> A permanent redirect is created for anyone connecting over HTTP to connect via HTTPS.

=== Rate Limiting
HAProxy is easily configurable when it comes to rate limiting and a specific example is provided here.

[TIP]
====
Recommended additional reading:

* https://www.haproxy.com/blog/four-examples-of-haproxy-rate-limiting/ is a good starting point for further investigation.
* https://www.haproxy.com/blog/use-haproxy-response-policies-to-stop-threats/
* https://www.haproxy.com/blog/bot-protection-with-haproxy/
====

[source,bash]
----
frontend f_lisk
        mode http
        bind [::]:443 ssl crt /etc/haproxy/ssl/cert.pem alpn h2,http/1.1
        bind [::]:80
        http-response set-header Strict-Transport-Security max-age=15768000
        redirect scheme https code 301
        rate-limit sessions 500 <1>
        stick-table type ipv6 size 200k expire 10m store gpc0 <2>
        acl repeat_abuses src_get_gpc0(f_lisk) gt 2 <3>
        tcp-request content track-sc0 src <4>
        tcp-request content reject if repeat_abuses <5>
        use_backend b_lisk_ws
backend b_lisk_ws
        stick-table type ipv6 size 200k expire 2m store conn_rate(10s) <6>
        tcp-request content track-sc1 src <7>
        acl exceeds_conn_rate sc1_conn_rate gt 50 <8>
        acl mark_repeat_abuses sc0_inc_gpc0 gt 0 <9>
        http-request deny deny_status 429 if exceeds_conn_rate mark_repeat_abuses <10>
        server lisk_ws 127.0.0.1:8080
----

This can be thought of as somewhat of a 3-pronged approach to rate limiting.
`rate-limit sessions 500` limits the number of new sessions per second.
New sessions are queued and accepted in line with the set value, which can be adjusted as required.

The rest of the changes here instruct the HAProxy to track the connection rate (over a rolling time period of 10 seconds), of up to 200k connecting IP addresses, whereby the entries of these will expire after 2 minutes.
If the connection rate of an IP exceeds 50 connections per 10 seconds, a 429 response gets returned and a global counter for that IP gets incremented, to track repeat abuses.
If an IP exceeds this threshold more than twice in a 10 minute period, new connections from that IP will be silently dropped.

=== Multiple Backends
So far, the examples provided have just been for proxying the Lisk WebSocket RPC endpoint.
The example below will proxy both the WebSocket RPC endpoint and the HTTP API endpoint by the hostname (`http.lisk.example` is a placeholder for whatever your domain is).

[NOTE]
====
For this example to work, it is assumed that the application has the xref:{url_plugin_http_api}[HTTP API plugin] enabled with the HTTP port set to 4000 (which is the default value).

In the case whereby you have configured a different port, then replace `4000` with your alternative port in the example below.
====

It is possible to have multiple backends that are served using all kinds of different criteria.
Commonly, this is by the `Host` header in order to serve more than one site.
This can be achieved by the following example below:

[source,bash]
----
frontend f_lisk
        mode http
        bind [::]:443 ssl crt /etc/haproxy/ssl/cert.pem alpn h2,http/1.1
        bind [::]:80
        http-response set-header Strict-Transport-Security max-age=15768000
        redirect scheme https code 301
        rate-limit sessions 500
        stick-table type ipv6 size 200k expire 10m store gpc0
        acl repeat_abuses src_get_gpc0(f_lisk) gt 2
        tcp-request content track-sc0 src
        tcp-request content reject if repeat_abuses
        acl host_http hdr(host) http.lisk.example
        use_backend b_lisk_http if host_http
    default_backend b_lisk_ws
backend b_lisk_ws
        stick-table type ipv6 size 200k expire 2m store conn_rate(10s)
        tcp-request content track-sc1 src
        acl exceeds_conn_rate sc1_conn_rate gt 50
        acl mark_repeat_abuses sc0_inc_gpc0 gt 0
        http-request deny deny_status 429 if exceeds_conn_rate mark_repeat_abuses
        server lisk_ws 127.0.0.1:8080
backend b_lisk_http
        stick-table type ipv6 size 200k expire 2m store conn_rate(10s)
        tcp-request content track-sc2 src
        acl exceeds_conn_rate sc2_conn_rate gt 50
        acl mark_repeat_abuses sc0_inc_gpc0 gt 0
        http-request deny deny_status 429 if exceeds_conn_rate mark_repeat_abuses
        server lisk_http 127.0.0.1:4000
----

TIP: If you use multiple domains with SSL termination, your certificate will either have to be for those multiple domains or it will be necessary to have multiple certificates, which can be specified with `crt-list` instead of `crt` (https://www.haproxy.com/documentation/aloh).
