= Protecting a non-forging node
// Settings
:toc:
// External URLs
:url_haproxy: http://www.haproxy.org/
:url_haproxy_blog: https://www.haproxy.com/blog/the-four-essential-sections-of-an-haproxy-configuration/

Sometimes, it's desirable to run a blockchain application behind a reverse proxy for SSL termination, rate limiting and other reasons.

*We highly recommended running a reverse proxy for a public web service*

== Setting up Lisk Core behind a reverse proxy

{url_haproxy}[HAProxy^] is one such reverse proxy.

An HAProxy configuration has 4 sections, {url_haproxy_blog}[explained here ^].
The sections that we are concerned with here are `frontend` and `backend`.
We'll start out with a very basic config snippet and then build up.

[source]
----
frontend f_lisk
        mode http
        bind :80
        use_backend b_lisk_ws
backend b_lisk_ws
        server lisk_ws 127.0.0.1:5052
----

This does nothing more than proxy requests coming in at port 80 to your Lisk Core websocket port.

==== SSL Termination
We can add ssl termination by telling it to listen on port 443 and specifying the certificate in the frontend section

[source]
----
frontend f_lisk
        mode http
        bind [::]:443 ssl crt /etc/haproxy/ssl/cert.pem alpn h2,http/1.1
        bind [::]:80
        http-response set-header Strict-Transport-Security max-age=15768000
        redirect scheme https code 301
        use_backend b_lisk_ws
----

which was done in the new `bind` line.
You'll notice that there were a few other changes here.

* The bind lines were changed so that HAProxy will also listen on ipv6.
* The TLS ALPN extension is enabled, as described in the HAProxy documentation https://www.haproxy.com/documentation/aloha/12-5/traffic-management/lb-layer7/tls/
* The `Strict-Transport-Security` response header is set to tell web browsers to only access this site over HTTPS
* a permanent redirect is created for anyone connecting over http to connect via https

==== Rate Limiting
HAProxy is very configurable when it comes to rate limiting.
We'll provide a specific example here.

Recommended additional reading:

* https://www.haproxy.com/blog/four-examples-of-haproxy-rate-limiting/ is a good starting point for further investigation.
* https://www.haproxy.com/blog/use-haproxy-response-policies-to-stop-threats/
* https://www.haproxy.com/blog/bot-protection-with-haproxy/

[source]
----
frontend f_lisk
        mode http
        bind [::]:443 ssl crt /etc/haproxy/ssl/cert.pem alpn h2,http/1.1
        bind [::]:80
        http-response set-header Strict-Transport-Security max-age=15768000
        redirect scheme https code 301
        rate-limit sessions 500
        stick-table type ipv6 size 200k expire 10m store gpc0
        acl repeat_abuses src_get_gpc0(f_lisk) gt 2
        tcp-request content track-sc0 src
        tcp-request content reject if repeat_abuses
        use_backend b_lisk_ws
backend b_lisk_ws
        stick-table type ipv6 size 200k expire 2m store conn_rate(10s)
        tcp-request content track-sc1 src
        acl exceeds_conn_rate sc1_conn_rate gt 50
        acl mark_repeat_abuses sc0_inc_gpc0 gt 0
        http-request deny deny_status 429 if exceeds_conn_rate mark_repeat_abuses
        server lisk_ws 127.0.0.1:5052
----

This is a bit of a 3-pronged approach to rate limiting.
`rate-limit sessions 500` limits the number of new sessions per second.
New sessions are queued and accepted in line with the set value, which can be adjusted as needed.

The rest of the changes here tell HAProxy to track the connection rate (over a rolling 10 seconds) of up 200k connecting IP addresses, the entries of which will expire after 2 minutes.
If the connection rate of an IP exceeds 50 connections per 10 seconds, a 429 response gets returned and a global counter for that IP gets incremented, to track repeat abuses.
If an IP exceeds this threshold more than twice in a 10 minute period, new connections from that IP will get silently dropped.

==== Multiple Backends
You can have multiple backends that get served using all kinds of different criteria.
Commonly, this is by `Host` header to serve more than one site.
We'll do this here

[source]
----
frontend f_lisk
        mode http
        bind [::]:443 ssl crt /etc/haproxy/ssl/cert.pem alpn h2,http/1.1
        bind [::]:80
        http-response set-header Strict-Transport-Security max-age=15768000
        redirect scheme https code 301
        rate-limit sessions 500
        stick-table type ipv6 size 200k expire 10m store gpc0
        acl repeat_abuses src_get_gpc0(f_lisk) gt 2
        tcp-request content track-sc0 src
        tcp-request content reject if repeat_abuses
        acl host_http hdr(host) http.lisk.example
        use_backend b_lisk_http if host_http
    default_backend b_lisk_ws
backend b_lisk_ws
        stick-table type ipv6 size 200k expire 2m store conn_rate(10s)
        tcp-request content track-sc1 src
        acl exceeds_conn_rate sc1_conn_rate gt 50
        acl mark_repeat_abuses sc0_inc_gpc0 gt 0
        http-request deny deny_status 429 if exceeds_conn_rate mark_repeat_abuses
        server lisk_ws 127.0.0.1:5052
backend b_lisk_http
        stick-table type ipv6 size 200k expire 2m store conn_rate(10s)
        tcp-request content track-sc2 src
        acl exceeds_conn_rate sc2_conn_rate gt 50
        acl mark_repeat_abuses sc0_inc_gpc0 gt 0
        http-request deny deny_status 429 if exceeds_conn_rate mark_repeat_abuses
        server lisk_http 127.0.0.1:5050
----

So far, the examples have been just for proxying the Lisk Websocket RPC endpoint.
This latest one will proxy both the Websocket RPC endpoint and the http RPC endpoint by hostname (http.lisk.example is a placeholder for whatever your domain is).

If you use multiple domains with SSL termination, your certificate will either have to be for those multiple domains or you will have to have multiple certificates, which can be specified with `crt-list` instead of `crt` (https://www.haproxy.com/documentation/aloh
