= Template Customization

The default UI bundle can be customized using AsciiDoc attributes.
xref:templates.adoc[] explained how to access such attributes.
But what are the attributes that actually affect this particular template?
If you're going to use the default UI bundle for your project, you'll want to know.

== page-pagination attribute

The `page-pagination` attribute is set in your xref:antora:playbook:asciidoc-attributes.adoc[playbook] in order to enable pagination, if your UI bundle supports it.
The default UI bundle supports this and you'll get the links to previous and next pages at the bottom of every page, based your navigation.

.Enable pagination
[,yaml]
----
asciidoc:
  attributes:
    page-pagination: ''
----

Antora automatically calculates the appropriate URLs and inserts the correct links.

Since you most likely want this enabled for every page in your site, there's no point setting this attribute per page.
However, if you do want to be able to override it per page, such as to turn it off, then you need to soft set the value in the playbook.

.Enable pagination, but make it overriddable
[,yaml]
----
asciidoc:
  attributes:
    page-pagination: '@'
----

You can now turn page pagination off by unsetting the `page-pagination` attribute in the document header.
