= Introduction

_This documentation only describes the general features of the Lisk protocol version *XXX*: for a detailed technical explanation go [here]._

== What is a Blockchain?

At its core, a [#index-blockchain-1]#*blockchain*# is a database shared across multiple computers.
Operations on the database are called *transactions*.
The data contained in a transaction specifies the operation to be performed.
In an [#index-account_based-1]#*account-based*# blockchain (such as Ethereum, see https://en.wikipedia.org/wiki/Ethereum[Wikipedia page]), the validity of a new transaction is checked against a database of user accounts. An account is a portion of the database identified by the account [#index-address-1]#*address*#.
This is opposed to [#index-UTXO_based-1]#*UTXO-based*# blockchains (such as Bitcoin, see https://en.wikipedia.org/wiki/Bitcoin[Wikipedia page]), where there is no concept of account and the validity of a transaction is based on referenced past transactions.
The cost of processing the transaction and updating the blockchain is specified in the transaction fee and paid using [#index-tokens-1]#*tokens*#.
Transactions are shared among users connected in a [#index-P2P_network-1]#*P2P network*# and are grouped together into [#index-blocks-1]#*blocks*#.
The validity of a block (and all transactions within it) is determined against the accounts state.
The [#index-consensus_protocol-1]#*consensus protocol*# specifies who has the right to [#index-forge-1]#*forge*# a new block and how agreement on the validity of a block is reached.
After the block has been forged, it is added to the blockchain, and all state changes induced by the block transactions are applied.

Starting from the initial [#index-genesis_block-1]#*genesis block*# (the initial state of the database), the current [#index-state_of_the_blockchain-1]#*state of the blockchain*# can be calculated by successively applying all transactions contained in the blocks.
In this sense, _defining the blockchain to be the history of the underlying database or the ordered collection of blocks, is equivalent_.

insert big diagram from https://projects.invisionapp.com/share/SRVCPRZ7F83#/screens/398517617_Infographic_-_Contracted[here]

== Overview of the Lisk Protocol

The Lisk protocol is the formal set of rules that defines a blockchain created with the Lisk SDK.
The Lisk protocol defines an account-based blockchain with a fixed set of [#index-transaction_types-1]#*default transaction types*# that are used to modify the accounts state.
The fees for those transactions are paid with the chain native token.
Transactions are gathered in blocks by [#index-delegates-1]#*delegates*#, which are selected using a [#index-delegated_proof_of_stake-1]#*delegated proof-of-stake*# mechanism.
Delegates agree on blocks using the [#index-lisk_bft-1]#*Lisk-BFT*# consensus algorithm.

This documentation is structured as follows:

. link:1-accounts.adoc[*Accounts*]: In this section, user accounts forming the underlying database are covered.
. link:2-transactions.adoc[*Transactions*]: This section outlines the default transactions present in the Lisk protocol.
. link:3-blocks.adoc[*Blocks*]: This section describes the actual data stored in a block and how new blocks are created.
. link:4-consensus-algorithm.adoc[*Consensus Algorithm*]: This section illustrates how the delegates eligible to create blocks are selected and how they reach agreement on new blocks.
. link:5-network.adoc[*Network*]: This section describes the Lisk P2P network used to exchange information such as blocks or transactions between nodes.
