== 0. Introduction

_This documentation only describes the general features of the Lisk protocol: for a detailed technical explanation go [here]._

=== What is a Blockchain?

At its core, a *blockchain* is a database shared across multiple computers. Operations on the database are called *transactions*. The data contained in a transaction specifies the operation to be performed. Generally speaking, users are allowed to perform operations on their *accounts*, corresponding to a portion of the database identified by their account *address*. The cost of processing the transaction and updating the blockchain is specified in the transaction fee and paid using *tokens*. Transactions are shared among users connected in a *P2P network* and are grouped together into *blocks*. The validity of a block (and therefore of all transactions within it) is determined following a *consensus protocol*. The consensus protocol also specifies who has the right to *forge* a new block. After the block has been forged, the block is added to the blockchain, and all state changes induced by the block transactions are applied.

Starting from the initial *genesis block* (the initial state of the database), the current *state of the blockchain* can be calculated by successively applying all transactions contained in the blocks. In this sense, _defining the blockchain to be __the history of the underlying database__ or the ordered collection of blocks, is equivalent._

=== Overview of the Lisk Protocol

The Lisk Protocol is the formal set of rules that defines the Lisk blockchain. Lisk is an *account-based* blockchain, where the validity of a new transaction is checked against a database of user accounts. This is opposed to *UTXO-based* blockchains (like Bitcoin [https://en.wikipedia.org/wiki/Bitcoin[1]]), where there is no concept of account and the validity of a transaction is based on referenced past transactions. The Lisk protocol defines a fixed set of *transaction types* that are used to modify the account state. The fees for those transactions are paid with the native token *LSK*. Each LSK is further subdivided into 10^8^ *Beddows*. Transactions are gathered in blocks by *delegates*, which are selected using a *delegated proof-of-stake* mechanism. Delegates agree on blocks using the *Lisk-BFT* consensus algorithm.

This documentation is structured as follows:

.  link:1-accounts.adoc[*Accounts*]: In this section, we describe user accounts forming the underlying database.
. https://docs.google.com/document/d/1sCGxXm2HTaXjiezThr_LqAdpls6wPgh9R4YoLrFGas8/edit#[*Transactions]*: This section describes the transactions present in the Lisk protocol.
. https://docs.google.com/document/d/1Eidrm7AMvp2Hq6SEXkZhuYiw9LimMUQmYDyZZ-LFZak/edit#heading=h.9z7jcxlc9ksz[*Blocks]*: This section describes what data is stored in a block and how new blocks are created.
. https://docs.google.com/document/d/1MCIQVFWD9DXqIq4vt0u2ct8l5cEHtYy9bntvLpFnnho/edit#[*Consensus Algorithm]*: In this section, we explain how the delegates eligible to create blocks are selected and how they reach agreement on new blocks.
. https://docs.google.com/document/d/1_4agJKD6ssXkDSVq3LJ8OGv6ATyK2X8p2fJDNovEz7k/edit#[*Network]*: This section describes the Lisk P2P network used to exchange information such as blocks or transactions between nodes.


=== Index

* Blockchain
* Transactions
* Account
* Address
* LSK tokens
* Blocks
* Genesis block
* State of the blockchain
* P2P network

