= Best practices
Mona Bärenfänger <mona@lightcurve.io>
:description: The Best practices section describes how to avoid double forging and extend custom transaction types from the base transaction.
:toc:
:page-previous: /lisk-sdk/guides.html
:page-previous-title: Guides

Conventions and recommendations for the optimal experience when working with the Lisk SDK can be found on this page below.

== Avoid double forging

Double forging means that a delegate has forging enabled on more than 1 node at once.

This behaviour can create instabilities in the network and therefore will be punished.

== Always extend a custom transaction type from the `BaseTransaction`

It is also possible to extend from one of the default or from another custom transaction types, in order to extend or modify them.

In most cases though, this is not recommended because updates in the logic of the inherited transaction can break the logic of the custom transaction.

To avoid the possibility of incompatibilities, always extend from the `BaseTransaction`:

.Extending from the `BaseTransaction`
[source,js]
----
const {
    BaseTransaction,
    TransactionError
} = require('@liskhq/lisk-transactions');

class HelloTransaction extends BaseTransaction {
[...]
----
