= Client configuration
Mona Bärenfänger <mona@lightcurve.io> Muhammad Talha <muhammad.talha@lightcurve.io>
:description: The configuration reference covers the config object, the default values, and also a description of each value.
// Settings
:toc: preamble
:toclevels: 3
:page-toclevels: 3
:idprefix:
:idseparator: -
:v_sdk: development
// URLs
:url_github_sdk_configschema: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/framework/src/schema/application_config_schema.ts
:url_github_config_example: https://github.com/LiskHQ/lisk-sdk/blob/development/commander/src/utils/config.ts
:lisk_ID_system: https://lisk.com/blog/research/new-lisk-id-system
:url_plain_object_schema: https://github.com/LiskHQ/lisk-sdk/blob/238ed3166fe04856e855ff8d2dd328ae414666f7/framework/src/engine/generator/schemas.ts#L429
:url_encrypted_object_schema: https://github.com/LiskHQ/lisk-sdk/blob/238ed3166fe04856e855ff8d2dd328ae414666f7/framework/src/engine/generator/schemas.ts#L376
:url_key_derivation_lip66: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0066.md
:keys_fixture: https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/testing/fixtures/keys_fixture.json
:url_mozilla_acao: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
// Project URLs
:url_configure_app_guide: ROOT::build-blockchain/configuration.adoc
:url_run_keys_create: ROOT::run-blockchain/become-a-validator.adoc#creating-the-validator-keys
:url_run_key_path: ROOT::run-blockchain/account-management.adoc#key-derivation-path

A complete reference of the client configurations is described on this page.

TIP: For more information on how to create and use a *custom configuration* for the client, please check out the guide xref:{url_configure_app_guide}[].

== Default Configuration
The default configuration used to initialize new blockchain clients with Lisk Commander can be found here: {url_github_config_example}[config.ts^]

The configuration schema can be found at {url_github_sdk_configschema}[client config schema^]

== Client config reference
The following sections describe all configuration categories and their available options.

=== genesis
The `genesis` configuration holds the settings for the blockchain protocol.

WARNING: The `genesis` configurations should only be changed by the blockchain developer, and not by the node operator!
If a node operator changes any of the genesis configurations, it might cause the node to fork.

[tabs]
=====
Properties::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| block
| object
| optional
| This is the first block of a chain.
a|[source,js]
----
"block": {
	"fromFile": "./config/genesis_block.blob'",
	"blob": "<<Hex of encoded genesis block>>",
},
----

| chainID
| string
| mandatory
| Represents a 4-byte hex string that identifies each chain in the Lisk ecosystem. The length of the hex string should be 8 characters.
| 00000000

| maxTransactionsSize
| number
| mandatory
| The maximum transaction size (kilobytes) allowed in a block.
| 15 * 1024

| blockTime
| number
| mandatory
| The frequency of blocks to be created.
| 10

| bftBatchSize
| number
| mandatory
| The length of a round for block generation.
| 103

|===

--
Sample::
+
--
[source,js]
----
const customConfig =
{
	// Other types of configurations.
	"genesis": {
		"block": {
			"fromFile": "./config/genesis_block.blob",
			"blob": "<<Hex of encoded genesis block>>",
		},
		"chainID": "00000000",
		"maxTransactionsSize": 15 * 1024, // Kilo Bytes
		"blockTime": 10,
		"bftBatchSize": 103,
	},
	// Other types of configurations.
}
----
--
=====

=== network 
The `network` category contains the following configuration options:

[tabs]
=====
Properties::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| version
| string
| optional
| The version of network protocol.
| 1.0
 
| port
| number
| optional
| The port defines an open port for P2P incoming connections.
| 7667
 
| seedPeers
| object[]
| mandatory
| SeedPeers defines an entry point of the network.
a|[source,js]
----
"seedPeers": [{
	"ip": "127.0.0.1",
	"port": 5000
}]
----
 
| host
| string
| optional
| Address of the server to connect to.
| 127.0.0.1
 
| blacklistedIPs
| string[]
| optional
| A list of IP addresses for which the node will reject the connection for both outbound and inbound connections.
| 192.168.178.23
 
| fixedPeers
| object[]
| optional
| A set of peers to which a node will always try to connect, for outbound connections.
a|[source,js]
----
"fixedPeers": [{
	"ip": "192.110.01.12",
	"port": 5000
}]
----
 
| whitelistedPeers
| object[]
| optional
| Set of peers that are always allowed to connect to the node through inbound connections.
a|[source,js]
----
"whitelistedPeers": [{
	"ip": "192.110.01.12",
	"port": 5000
}]
----
 
| maxOutboundConnections
| number
| optional
| The maximum number of outbound connections allowed.
| 20footnote:disclaimer[This is the default value.]
 
| maxInboundConnections
| number
| optional
| The maximum number of inbound connections allowed.
| 100footnote:disclaimer[This is the default value.]
 
| wsMaxPayload
| number
| optional
| The maximum size of the payload allowed per communication.
| 3048576footnote:disclaimer[This is the default value.]
 
| advertiseAddress
| boolean
| optional
| Defines whether to announce the IP/Port to other peers.
| truefootnote:disclaimer[This is the default value.]

|===

--
Sample::
+
--
[source,js]
----
const customConfig = 
{
	// Other types of configurations.
	"network": {
		"version": "1.0",  
		"seedPeers": [
			{
				"ip": "127.0.0.1",
				"port": 5000
			}
		],
		"port": 7667,
		"host": "127.0.0.1",  
		"blacklistedIPs": [
			"172.112,31.0",
			"172.112,31.2"
		],                                    
		"fixedPeers": [
			{
				"ip": "192.110.01.12",
				"port": 5000
			},
		],
		"whitelistedPeers": [
			{
				"ip": "192.110.01.12",
				"port": 5000
			},
		],                  
		"maxOutboundConnections": 20,                                   
		"maxInboundConnections": 100,                             
		"wsMaxPayload": 3048576,             
		"advertiseAddress": true,                           
		},
	// Other types of configurations.
}
----
--
=====

WARNING: The connectivity of the node might be negatively impacted if the `*fixedPeers*` configuration is used.
Beware of declaring only trustworthy peers in `*whitelistedPeers*` as these could attack a node with a denial-of-service attack because the banning mechanism is deactivated.

=== rpc
Apps on Lisk can communicate with a node via the `rpc` communication protocol.

[tabs]
=====
Properties::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| modes
| array
| mandatory
| Modes of communication between lisk node and external services.
| IPC, WS, HTTP

| port
| number
| mandatory
| Port to be used for a 'WS' connection.
| 7887

| host
| string
| mandatory
| Address of the server to connect.
| 127.0.0.1

| allowedMethods
| array
| optional
| Allowed methods for the node to use.
Add the `namespace`, to allow all endpoints of namespace, or `namespace_endpointName` to allow a specific endpoint.
`[*]` allows all methods, `[]` none.
| ["generator", "system", "random"]

| accessControlAllowOrigin
| string
| optional
| Defines the {url_mozilla_acao}[Access Control Allow Origin] for RPC requests.
| "*"

|===
--
Sample::
+
--
[source,js]
----
const customConfig =
{
	// Other types of configurations.
	"rpc": {
		"modes": ["IPC"],
		"port": 7887,
		"host": "127.0.0.1",
	},
	// Other types of configurations.
}
----
--
=====

=== system
The `system` configuration holds settings for the node.

[tabs]
=====
Properties::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| version
| string
| mandatory
| The version of the system.
| 1.0
 
| dataPath
| string
| mandatory
| DataPath defines the folder path for the client application data.
| ~/.lisk/beta-sdk-app

| keepEventsForHeights
| number
| mandatory
| Defines the number of blocks for which the events should be maintained by the system.
Usually, the events are based on the latest, given number of blocks.
| 300footnote:disclaimer[This is the default value.]

| logLevel
| string
| mandatory
| Level of the log to be maintained.
| info

| enableMetrics
| boolean
| optional
| Tracks certain events in the system.
//TODO: Update RPC API reference with system_getMetricReport endpoint and add link here
If enabled, metrics can be queried via the `system_getMetricReport` endpoint.
For development purposes.
| false

|===
--
Sample::
+
--
[source,js]
----
const customConfig = 
{
	// Other types of configurations.
	"system": {
		"version": "1.0",
		"dataPath": "~/.lisk/beta-sdk-app",
		"keepEventsForHeights": 300,
		"logLevel": "info",
	},
	// Other types of configurations.
}
----
--
=====

=== modules
`modules` contains the module-specific configuration options for the blockchain client.

WARNING: The `module` configurations should only be changed by the blockchain developer, and not by the node operator!
If a node operator changes any of the module-specific configurations, it might cause the node to fork.

Please check the available documentation for the respective module to learn about the available configuration options.

=== plugins
`plugins` contains the plugin-specific configuration options for the blockchain client.

Please check the available documentation for the respective plugin to learn about the available configuration options.

=== Optional configurations

==== generator
The `generator` configuration is used to read xref:{url_run_keys_create}[validator keys] from a file, which are then stored in the database.

[tabs]
=====
Properties::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| keys
| object
| optional
| Contains a path to the "keys" file of a generator/validator.
a|
[source,json]
----
{"fromFile": "keys.json"}
----

|===
--


Sample::
+
--
[source,js]
----
const customConfig =
{
	// Other types of configurations.
	"generator": {
		"keys": {
			"fromFile": "keys.json",
		},
	},
	// Other types of configurations.
}
----
--
=====

==== legacy
The `legacy` category contains the following configuration options:

[tabs]
=====
Properties::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| sync
| boolean
| optional
| Boolean if it will sync the legacy blocks or not.
| true

| brackets
| array
| mandatory
| Brackets specify the blocks of previous legacy blockchains.
For example, in Lisk Core v4, it will store the height from Core v3 where it starts from, and where it ended.
a|
[source,json]
----
[
    {
       "startHeight":1,
       "snapshotHeight":123,
       "snapshotBlockID":
	   "0f4ea1c3cfb61b99d38
	   7b26aaadf57936a528e
	   5c713c6e55aa06f4d62
	   1b7e6f0"
    }
]
----

|===

--
Sample::
+
--
[source,js]
----
const customConfig =
{
	// Other types of configurations.
	"legacy": {
		"sync": true,
		"brackets": [{"startHeight": 1,"snapshotHeight": 123,"snapshotBlockID": "0f4ea1c3cfb61b99d387b26aaadf57936a528e5c713c6e55aa06f4d621b7e6f0"}]
	},
	// Other types of configurations.
}
----
--
=====

==== transactionPool
This type of configuration holds the settings for the transaction pool.

[tabs]
=====
Properties::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| maxTransactions
| number
| optional
| The maximum number of transactions in the pool.
| 4096

| maxTransactionsPerAccount
| number
| optional
| The maximum number of transactions in the pool per sender account.
| 64

| transactionExpiryTime
| number
| optional
| Defines the timeout (milliseconds) of the transaction in the pool.
| 3 * 60 * 60 * 1000

| minEntranceFeePriority
| string
| optional
| The minimum fee required for a transaction to be added to the transaction pool.
| 0

| minReplacementFeeDifference
| string
| optional
| The difference of minimum fee required to replace a transaction with the same nonce
| 10

|===

--
Sample::
+
--
[source,js]
----
const customConfig =
{
	// Other types of configurations.
	"transactionPool": {
		"maxTransactions": 4096,
		"maxTransactionsPerAccount": 64,
		"transactionExpiryTime": 3 * 60 * 60 * 1000,
		"minEntranceFeePriority": "0",
		"minReplacementFeeDifference": "10",
	},
	// Other types of configurations.
}
----
--
=====







