= Lisk SDK Configuration
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:imagesdir: assets/images

== Pass and modify default values

[source,js]
----
const { Application, genesisBlockDevnet, configDevnet} = require('lisk-sdk'); <1>

const app = new Application(genesisBlockDevnet, configDevnet); <2>
----

<1> Require the lisk-sdk package
<2> Passes the config json `configDevnet` as config object for the new application instance. Will start the node with a fully functioning Devnet.

[source,js]
----
const { Application, genesisBlockDevnet, configDevnet} = require('lisk-sdk'); <1>

const app = new Application(genesisBlockDevnet, { <2>
    app: {
        label: 'my-label',
        minVersion: '0.0.2',
        version: '2.3.4',
        protocolVersion: '4.1'
        },
    components: {
        logger: {
            consoleLogLevel: "info"
        }
    }});
----

<1> Require the lisk-sdk package
<2> Sets the required values for label, protocol and version, overrides consoleLogLevel, uses default values for everything else

The configuration object `configDevnet` has the structure like shown in the xref:#_list_of_configuration_options[list of configuration options].
It can be modified accordingly, before passing the config to the `Application` instance:

[source,js]
----
const { Application, genesisBlockDevnet, configDevnet} = require('lisk-sdk'); <1>

configDevnet.components.storage.database = 'my-custom-db' <2>
configDevnet.modules.http_api.access.public = true; <3>


const app = new Application(genesisBlockDevnet, configDevnet);
----

<1> require the lisk-sdk package
<2> change the db name to my-custom-db
<3> make the API accessible from everywhere

== List of configuration options

Here is a complete list of all the available configuration options of the Lisk SDK.

The values below are the *default values*.
They will be used automatically when starting the application as described in xref:#_pass_and_modify_default_values[Pass and modify default values].
To change them, override the specific default values with custom ones, when initializing the application.

=== Constants

Inside `app.genesisConfig` specific constants for the blockchain application are set.

In the alpha version of the Lisk SDK, not all available constants are configurable by the user.
Only the configurable constants are listed above.
In future versions of the Lisk SDK, more constants will become configurable.

TIP: To see a full list of all constants and their predefined values, check out https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/controller/schema/constants_schema.js[framework/src/controller/schema/constants_schema.js].

include::partial$config-object.adoc[]

== The Genesis block

The genesis block describes the very first block in the blockchain.
It defines the initial state of the blockchain on start of the network.

The genesis block is not forged by a delegate, like all other blocks, which come after the genesis block.
Instead, it is defined by the blockchain application developer, when creating the `Application` instance of the blockchain app (see section link:#pass-and-modify-default-values[pass and modify default config values]).

TIP: Go to Github, to see the full file https://github.com/LiskHQ/lisk-sdk/blob/development/sdk/src/samples/genesis_block_devnet.json[genesis_block_devnet.json]

A genesis block generator to create genesis blocks conveniently will be included in the Lisk SDK eventually.
For Lisk Alpha SDK, you can use the exposed `genesisBlockDevnet` as a template, and customize it to your needs.

It’s possible and recommended to customize the genesis block to suit the use case of your blockchain application.
The following template describes all available options for the genesis block.

[source,js]
----
{
    "version": 0, <1>
    "totalAmount": "10000000000000000", <2>
    "totalFee": "0", <3>
    "reward": "0", <4>
    "payloadHash": "198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d", <5>
    "timestamp": 0, <6>
    "numberOfTransactions": 103, <7>
    "payloadLength": 19619, <8>
    "previousBlock": null, <9>
    "generatorPublicKey": "c96dec3595ff6041c3bd28b76b8cf75dce8225173d1bd00241624ee89b50f2a8", <10>
    "transactions": [], <11>
    "height": 1, <12>
    "blockSignature": "c81204bf67474827fd98584e7787084957f42ce8041e713843dd2bb352b73e81143f68bd74b06da8372c43f5e26406c4e7250bbd790396d85dea50d448d62606", <13>
    "id": "6524861224470851795" <14>
}
----

<1> block version
<2> the total amount of tokens that are transferred in this block
<3> the total amount of fees associated with the block
<4> reward for forging the block
<5> hashes of the combined transactional data blocks
<6> epoch timestamp of when the block was created
<7> number of transactions processed in the block
<8> sum of data blocks of all transaction in this block in bytes
<9> null, because the genesis block has no previous block by definition
<10> public key of the delegate who forged the block
<11> list of transactions in the genesis block
<12> current height of the blockchain, always equals 1 for the genesis block
<13> signature of the block, signed by the delegate
<14> block id
