= Application Configuration
Mona Bärenfänger <mona@lightcurve.io> Muhammad Talha <muhammad.talha@lightcurve.io>
:description: The configuration reference covers the config object, the default values, and also a description of each value.
// Settings
:toc: preamble
:v_sdk: development
// URLs
:url_github_sdk_configschema: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/framework/src/schema/application_config_schema.ts
// Project URLs

A complete reference of the *default* and *custom* application configurations is described on this page.

TIP: For more information about the configuration schema, see the {url_github_sdk_configschema}[application config schema file] at GitHub.

== Default Configuration

The application `config` object is passed to the `Application` instance and must follow the configuration schema.
By default, each blockchain application has a set of configrations that enable it to run properly.
The application uses the default configuration options in case a custom config is not specified.

An `Application` instance can have various configuration schemas within a configuration object, as listed below:

* network
* genesis
* transactionPool
* system
* rpc
* generator
* delegate

By default a configuration looks like this:

.Default config options
[source,js]
----
export const defaultConfig = {
	// Contains configuration for the blockchain application.
	"system": {
		"dataPath": "~/.lisk/beta-sdk-app",
		"keepEventsForHeights": 300,
		"logLevel": "info",
	},

	// The rpc protocol defines communication behavior.
	"rpc": {
		"modes": ["ipc"],
		"port": 7887,
		"host": "127.0.0.1",
	},

	//The network configuration holds the network information of the node.
	"network": {
		"version": "1.0",
		"seedPeers": [],
		"port": 7667,
	},

	// Contains configuration about a transaction pool.
	"transactionPool": {
		"maxTransactions": 4096,
		"maxTransactionsPerAccount": 64,
		"transactionExpiryTime": 3 * 60 * 60 * 1000,
		"minEntranceFeePriority": "0",
		"minReplacementFeeDifference": "10",
	},

	// The genesis configuration holds the blockchain protocol configurations.
	"genesis": {
		"block": {
			"fromFile": "./config/genesis_block.blob",
		},
		"blockTime": 10,
		"bftBatchSize": 103,

		"maxTransactionsSize": 15 * 1024, // Kilo Bytes
		"minFeePerByte": 1000,
		"chainID": "yaE12vt6",
	},
	"generator": {
		"keys": {},
	},

	// (Optional) modules hold a group of module-specific configs which is passed to a particular module.
	"modules": {},

	// (Optional) plugins hold a group of plugin-specific configs which is passed to a particular plugin.
	"plugins": {},
};

export const DEFAULT_KEY_DERIVATION_PATH = "m/25519'/134'/0'/0'";
----

All the aforementioned configurations can be tweaked as per necessity and then can be passed as a `customConfig` to the `Application` instance. 
The following sections describe various configuration schemas and their available properties.

=== network 
An application's `network` can be configured by passing a specific network configuration object to the Application config.

WARNING: The connectivity of the node might be negatively impacted if the `*fixedPeers*` configuration is used.
 Beware of declaring only trustworthy peers in `*whitelistedPeers*` as these could attack a node with a denial-of-service attack because the banning mechanism is deactivated.

[tabs]
=====
network Configurations::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| version
| string
| mandatory
| The version of network protocol.
| 1.0
 
| port
| number
| mandatory
| Port defines an open port for P2P incoming connections.
| 7667
 
| seedPeers
| object[]
| mandatory
| SeedPeers defines an entry point of the network.
a|[source,js]
----
"seedPeers": [{
	"ip": "127.0.0.1",
	"port": 5000
}]
----
 
| host
| string
| optional
| Address of the server to connect to.
| 127.0.0.1
 
| blacklistedIPs
| string[]
| optional
| A list of IP addresses for which the node will reject the connection for both outbound and inbound connections.
| 192.168.178.23
 
| fixedPeers
| object[]
| optional
| Set of peers that will always try to connect for outbound connections.
a|[source,js]
----
"fixedPeers": [{
	"ip": "192.110.01.12",
	"port": 5000
}]
----
 
| whitelistedPeers
| object[]
| optional
| Set of peers that are always allowed to connect to the node through inbound connections.
a|[source,js]
----
"whitelistedPeers": [{
	"ip": "192.110.01.12",
	"port": 5000
}]
----
 
| maxOutboundConnections
| number
| optional
| The maximum number of outbound connections allowed.
| 20footnote:disclaimer[This is the default value.]
 
| maxInboundConnections
| number
| optional
| The maximum number of inbound connections allowed.
| 100footnote:disclaimer[This is the default value.]
 
| wsMaxPayload
| number
| optional
| The maximum size of the payload allowed per communication.
| 3048576footnote:disclaimer[This is the default value.]
 
| advertiseAddress
| boolean
| optional
| Defines whether to announce the IP/Port to other peers.
| truefootnote:disclaimer[This is the default value.]

|===

--
Sample Configuration::
+
--
[source,js]
----
const customConfig = 
{
	// Other types of configurations.
	"network": {
		"version": "1.0",  
		"seedPeers": [
			{
				"ip": "127.0.0.1",
				"port": 5000
			}
		],
		"port": 7667,
		"host": "127.0.0.1",  
		"blacklistedIPs": [
			"172.112,31.0",
			"172.112,31.2"
		],                                    
		"fixedPeers": [
			{
				"ip": "192.110.01.12",
				"port": 5000
			},
		]            
		"whitelistedPeers": [
			{
				"ip": "192.110.01.12",
				"port": 5000
			},
		],                  
		"maxOutboundConnections": 20,                                   
		"maxInboundConnections": 100,                             
		"wsMaxPayload": 3048576,             
		"advertiseAddress": true,                           
		},
	// Other types of configurations.
}
----
--
=====

=== genesis
The `genesis` configuration holds the settings for the blockchain protocol.

[tabs]
=====
genesis Configurations::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| block
| object
| optional
| This is the first block of a chain.
a|[source,js]
----
"block": {
	"fromFile": "./config/genesis_block.blob'",
	"blob": "<<Hex of encoded genesis block>>",
},
----
 
| chainID
| string
| mandatory
| A hexadecimal string which identifies each chain. 
| ae1rF4gb
 
| maxTransactionsSize
| number
| mandatory
| The maximum transaction size (kilobytes) allowed in a block.
| 15 * 1024

| minFeePerByte
| number
| mandatory
| The minimum fee per byte for a transaction.
| 1000
 
| blockTime
| number
| mandatory
| The frequency of blocks to be created.
| 10
 
| bftBatchSize
| number
| mandatory
| The length of a round for block generation.
| 103

|===

--
Sample Configuration::
+
--
[source,js]
----
const customConfig = 
{
	// Other types of configurations.
	"genesis": {
		"block": {
			"fromFile": "./config/genesis_block.blob",
			"blob": "<<Hex of encoded genesis block>>",
		},
		"chainID": "ae1rF4gb",
		"maxTransactionsSize": 15 * 1024, // Kilo Bytes
		"minFeePerByte": 1000,
		"blockTime": 10,
		"bftBatchSize": 103,
	},
	// Other types of configurations.
}
----
--
=====





=== transactionPool
This type of configuration holds the settings for the `transactionPool`.

[tabs]
=====
transactionPool Configurations::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| maxTransactions
| number
| optional
| The maximum number of transactions in the pool.
| 4096
 
| maxTransactionsPerAccount
| number
| optional
| The maximum number of transactions in the pool per sender account.
| 64
 
| transactionExpiryTime
| number
| optional
| Defines the timeout (milliseconds) of the transaction in the pool.
| 3 * 60 * 60 * 1000
 
| minEntranceFeePriority
| string
| optional
| The minimum fee required for a transaction to be added into the transaction pool.
| 0
 
| minReplacementFeeDifference
| string
| optional
| The difference of minimum fee required to replace a transaction with the same nonce
| 10

|===

--
Sample Configuration::
+
--
[source,js]
----
const customConfig = 
{
	// Other types of configurations.
	"transactionPool": {
		"maxTransactions": 4096,
		"maxTransactionsPerAccount": 64,
		"transactionExpiryTime": 3 * 60 * 60 * 1000,
		"minEntranceFeePriority": "0",
		"minReplacementFeeDifference": "10",
	},
	// Other types of configurations.
}
----
--
=====



=== system
The `system` configuration holds settings for the lisk application.

[tabs]
=====
system Configurations::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| version
| string
| mandatory
| Version of the system.
| 1.0
 
| dataPath
| string
| mandatory
| DataPath defines the blockchain application's name and folder within the root path.
| ~/.lisk/beta-sdk-app

| keepEventsForHeights
| number
| mandatory
| Defines the number of blocks for which the events should be maintained by the system. Usually the events are based on the latest, given number of blocks.
| 300footnote:disclaimer[This is the default value.]

| logLevel
| string
| mandatory
| Level of the log to be maintained.
| info

|===
--
Sample Configuration::
+
--
[source,js]
----
const customConfig = 
{
	// Other types of configurations.
	"system": {
		"version": "1.0"
		"dataPath": "~/.lisk/beta-sdk-app",
		"keepEventsForHeights": 300,
		"logLevel": "info",
	},
	// Other types of configurations.
}
----
--
=====


=== rpc
Lisk based blockchain applications can communicate with a node via the `rpc` communication protocol. 

[tabs]
=====
rpc Properties::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| modes
| enum
| mandatory
| Modes of communication between lisk node and the blockchain application.
| IPC, WS, HTTP
 
| port
| number
| mandatory
| Port to be used for a 'WS' connection.
| 7887

| host
| string
| mandatory
| Address of the server to connect.
| 127.0.0.1

|===
--
Sample Configuration::
+
--
[source,js]
----
const customConfig = 
{
	// Other types of configurations.
	"rpc": {
		"modes": ["IPC"],
		"port": 7887,
		"host": "127.0.0.1",
	},
	// Other types of configurations.
}
----
--
=====



=== generator
The `generator` configuration is used to read keys from a file, which are then stored in the database.

[tabs]
=====
generator Configurations::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| keys
| object
| optional
| Contains keys for the generator.
a| 
[source,js]
----
"generator": {
	"keys": {},
},
----

|===

--
Sample Configuration::
+
--
[source,js]
----
const customConfig = 
{
	// Other types of configurations.
	"generator": {
		"keys": {
			"fromFile": "<<path/filename>>",
		},
	},
	// Other types of configurations.
}
----
--
=====


=== delegate 
This configuration holds the `delegate` information about block generation.

[tabs]
=====
delegate Configurations::
+
--
[cols="2,1,1,2,4",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Optionality
|Description
|Sample

| address
| string
| mandatory
| Defines the address of the delegate.
| 68d6b039567ebbfc714176d87cdd6906cf526cc7

| encryptedPassphrase
| string
| mandatory
| Defines the encrypted passphrase.
| iterations=1000000&cipherText=5c53db41ec94b46049- 
ca5a5b8312e6b38c7bbad775153a8091baf-ade3f78ac855b55d- 5d33318e13f22ec961510061c8a07726aeb4d2d2b30fbcc6ddfa- bc82dd6f233891a06ae54b2&iv=8c0419422b6e81c32c10ac6a&-
salt=1f2308d0d12480d0c788a4c60a8f272dtag=23cf9840cb9-
85550a96b463f878de99d&version=1
 
| hashOnion
| object
| mandatory
| Holds the seed reveal to put in the block header. A hashOnion object contains count, distance and a hashes[string].
a| 
[source,js]
----
"hashOnion": {
	"count": 100000,
	"distance": 1000,
	"hashes": ["34ecc432170c0812e7ca69d73485ca57"]
},
----
|===

--
Sample Configuration::
+
--
[source,js]
----
const customConfig = 
{
	// Other types of configurations.
	"delegate": [
		{		
			// Defines the address of the delegate.
			"address": "68d6b039567ebbfc714176d87cdd6906cf526cc7",

			// Defines the encrypted passphrase.
			"encryptedPassphrase": "iterations=1000000&cipherText=5c53db41ec94b46049ca5a5b8312e6b38c7bbad775153a8091bafade3f78ac855b55d5d33318e13f22ec961510061c8a07726aeb4d2d2b30fbcc6ddfabc82dd6f233891a06ae54b2&iv=8c0419422b6e81c32c10ac6a&salt=1f2308d0d12480d0c788a4c60a8f272d&tag=23cf9840cb985550a96b463f878de99d&version=1",
			
			// The hashOnion holds the seed reveal to put in the block header.
			"hashOnion": {
				//The count property holds the total number of hash onions.
				"count": 100000,
				// Defines distance between each hash onion.
				"distance": 1000,
				// The hashes holds the seed reveal for every distance.
				"hashes": [
					"34ecc432170c0812e7ca69d73485ca57",
					"1bf9423f594619f7d14e6f742c0631a1",
					// ...
					"fa51b75c7920894019b43378af621e2d",
					"bd4ea06be86fb6d850023be7ad1d9558",
					"da23c5a34d19bbd57ebb159da170dfb5"
				]
			},
		}
	],
		// Other types of configurations.
}
----
--
=====

