= Configuration
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes how to configure Lisk Service.
:toc:
:imagesdir: ../assets/images
:page-previous: /lisk-service/setup/index.html
:page-previous-title: Setup

How to configure Lisk Service.

[[default_configs]]
== Default configurations

Lisk Service provides different ready-to-use configuration files, which are located in the `env/` folder in the root directory of Lisk Service.

.lisk-service/env/
----
├── betanet.env
├── export_env
├── local.env
├── mainnet.env
└── testnet.env
----

To connect to any of the networks displayed in the snippet above, simply copy all its contents and paste them into the `.env` file in the `docker/` folder.

=== Mainnet

.lisk-service/env/mainnet.env
[source,bash]
----
## Lisk Service configuration
# Service broker
SERVICE_BROKER=redis://localhost:6379/0

# Lisk Service Gateway
PORT=9901
HOST=0.0.0.0
SERVICE_GATEWAY_REDIS=redis://localhost:6379/2

# Lisk Service Core
SERVICE_CORE_REDIS=redis://localhost:6379/1
SERVICE_CORE_POSTGRES=postgres://lisk:password@localhost:5432/lisk
ENV_LISK_DB_DATABASE=lisk
ENV_LISK_DB_USER=lisk
ENV_LISK_DB_PASSWORD=password

# Lisk Service log config
SERVICE_LOG_CONSOLE=false
SERVICE_LOG_FILE=false
SERVICE_LOG_GELF=false
SERVICE_LOG_LEVEL=debug
SERVICE_LOG_STDOUT=true

## External services
# Lisk ecosystem configuration
LISK_CORE_HTTP=https://mainnet.lisk.io
LISK_CORE_WS=wss://mainnet.lisk.io
LISK_STATIC=https://static-data.lisk.io

# Lisk Service geolocation backend
GEOIP_JSON=https://geoip.lisk.io/json
----

=== Testnet

.lisk-service/env/testnet.env
[source,bash]
----
LISK_CORE_HTTP=https://testnet.lisk.io
LISK_CORE_WS=wss://testnet.lisk.io
LISK_STATIC=https://static-data.lisk.io

SERVICE_BROKER=redis://localhost:6379/0
SERVICE_CORE_POSTGRES=postgres://lisk:password@localhost:5432/lisk
SERVICE_CORE_REDIS=redis://localhost:6379/1
SERVICE_GATEWAY_REDIS=redis://localhost:6379/2

SERVICE_LOG_CONSOLE=false
SERVICE_LOG_FILE=./logs/app.log
SERVICE_LOG_GELF=localhost:12201/udp
SERVICE_LOG_LEVEL=info
SERVICE_LOG_STDOUT=true

GEOIP_JSON=https://geoip.lisk.io/json

----

=== Betanet

.lisk-service/env/betanet.env
[source,bash]
----
LISK_CORE_HTTP=https://betanet.lisk.io
LISK_CORE_WS=wss://betanet.lisk.io
LISK_STATIC=https://static-data.lisk.io

SERVICE_BROKER=redis://localhost:6379/0
SERVICE_CORE_POSTGRES=postgres://lisk:password@localhost:5432/lisk
SERVICE_CORE_REDIS=redis://localhost:6379/1
SERVICE_GATEWAY_REDIS=redis://localhost:6379/2

SERVICE_LOG_CONSOLE=false
SERVICE_LOG_FILE=./logs/app.log
SERVICE_LOG_GELF=localhost:12201/udp
SERVICE_LOG_LEVEL=info
SERVICE_LOG_STDOUT=true

GEOIP_JSON=https://geoip.lisk.io/json
----

=== Devnet

.lisk-service/env/local.env
[source,bash]
----
LISK_CORE_HTTP=http://localhost:4000
LISK_CORE_WS=ws://localhost:4000
LISK_STATIC=https://static-data.lisk.io

SERVICE_BROKER=redis://localhost:6379/0
SERVICE_CORE_POSTGRES=postgres://lisk:password@localhost:5432/lisk
SERVICE_CORE_REDIS=redis://localhost:6379/1
SERVICE_GATEWAY_REDIS=redis://localhost:6379/2

SERVICE_LOG_CONSOLE=false
SERVICE_LOG_FILE=./logs/app.log
SERVICE_LOG_GELF=localhost:12201/udp
SERVICE_LOG_LEVEL=info
SERVICE_LOG_STDOUT=true

GEOIP_JSON=https://geoip.lisk.io/json
----

== Custom configuration

To manually change certain config options in Lisk Service, it is possible to either define them in the `.env` file, or alternatively, to export them on the command-line.

=== .env file

Beside just copy-pasting the <<default_configs,preconfigured configuration files>>, it is of course also possible to adjust the `.env` file to your needs.

See a reference of <<config_options, all available config options>> below.

=== Set environment variables

Another option to configure Lisk Service is to export the environment variables directly in the command-line.

.Example: Update the database password
[source,bash]
----
export ENV_LISK_DB_PASSWORD=myCustomPassword
----

[[config_options]]
== List of configuration options

[cols="1,2,2,3", options="header"]
.List of configuration options
|===
|Category |Option |Example |Description

|Service broker
|SERVICE_BROKER
|redis://localhost:6379/0
|description

|Gateway
|PORT
|9901
|API (HTTP) port

|Gateway
|HOST
|0.0.0.0
|API (HTTP) host name or IP

|Gateway
|SERVICE_GATEWAY_REDIS
|redis://localhost:6379/2
|description

|Core
|SERVICE_CORE_POSTGRES
|redis://localhost:6379/1
|description

|Core
|SERVICE_CORE_REDIS
|postgres://lisk:password@localhost:5432/lisk
|description

|Core
|ENV_LISK_DB_DATABASE
|lisk
|Lisk Service database name

|Core
|ENV_LISK_DB_USER
|lisk
|Database user

|Core
|ENV_LISK_DB_PASSWORD
|password
|Database password

|Log config
|SERVICE_LOG_CONSOLE
|false
|Toggle logging in the console

|Log config
|SERVICE_LOG_FILE
|false
|Toggle logging in a file

|Log config
|SERVICE_LOG_GELF
|false
|description

|Log config
|SERVICE_LOG_LEVEL
|debug
|Log level

|Log config
|SERVICE_LOG_STDOUT
|true
|Toggle logging in `stdout`

|External services
|LISK_CORE_HTTP
|https://mainnet.lisk.io
|description

|External services
|LISK_CORE_WS
|wss://mainnet.lisk.io
|description

|External services
|LISK_STATIC
|https://static-data.lisk.io
|description

|Geolocation
|GEOIP_JSON
|https://geoip.lisk.io/json
|description
|===
