= The DPoS module

The DPoS module handles all logic related to balance.
Specifically:

* Validating and subtracting fees for all transactions
* Checking the minimum remaining balance requirement
* Giving block rewards to the block generator
* Transferring account balances

[cols=",",options="header",stripes="hover"]
|===
|Name
|Property

|Name
|`dpos`

|ID
|`5`

|Assets
a|
* `RegisterTransactionAsset`
** `AssetID: 0`
* `VoteTransactionAsset`
** `AssetID: 1`
* `UnlockTransactionAsset`
** `AssetID: 2`
* `PomTransactionAsset`
** `AssetID: 3`

|Reducers
a| none

|Actions
a|
* `getAllDelegates()`
* `getUnlockings()`

|Events
| none

|===

== Account schema

The token module adds a new property `balance` under the key `token` to every account in the network as follows:

[source,typescript]
----
{
    type: 'object',
    properties: {
        delegate: {
            type: 'object',
            fieldNumber: 1,
            properties: {
                username: { dataType: 'string', fieldNumber: 1 },
                pomHeights: {
                    type: 'array',
                    items: { dataType: 'uint32' },
                    fieldNumber: 2,
                },
                consecutiveMissedBlocks: { dataType: 'uint32', fieldNumber: 3 },
                lastForgedHeight: { dataType: 'uint32', fieldNumber: 4 },
                isBanned: { dataType: 'boolean', fieldNumber: 5 },
                totalVotesReceived: { dataType: 'uint64', fieldNumber: 6 },
            },
            required: [
                'username',
                'pomHeights',
                'consecutiveMissedBlocks',
                'lastForgedHeight',
                'isBanned',
                'totalVotesReceived',
            ],
        },
        sentVotes: {
            type: 'array',
            fieldNumber: 2,
            items: {
                type: 'object',
                properties: {
                    delegateAddress: {
                        dataType: 'bytes',
                        fieldNumber: 1,
                    },
                    amount: {
                        dataType: 'uint64',
                        fieldNumber: 2,
                    },
                },
                required: ['delegateAddress', 'amount'],
            },
        },
        unlocking: {
            type: 'array',
            fieldNumber: 3,
            items: {
                type: 'object',
                properties: {
                    delegateAddress: {
                        dataType: 'bytes',
                        fieldNumber: 1,
                    },
                    amount: {
                        dataType: 'uint64',
                        fieldNumber: 2,
                    },
                    unvoteHeight: {
                        dataType: 'uint32',
                        fieldNumber: 3,
                    },
                },
                required: ['delegateAddress', 'amount', 'unvoteHeight'],
            },
        },
    },
	default: {
		delegate: {
			username: '',
			pomHeights: [],
			consecutiveMissedBlocks: 0,
			lastForgedHeight: 0,
			isBanned: false,
			totalVotesReceived: BigInt(0),
		},
		sentVotes: [],
		unlocking: [],
	},
};
----

== Transactions

The following transaction assets are provided by the token module.

=== RegisterTransactionAsset

Allows to send a register delegate transaction, which registers a delegate for the sender account with a given username.

Name::
registerDelegate
ID::
1

.Schema
[source,typescript]
----
{
    $id: 'lisk/dpos/register',
    type: 'object',
    required: ['username'],
    properties: {
        username: {
            dataType: 'string',
            fieldNumber: 1,
            minLength: 1,
            maxLength: 20,
        },
    },
}
----

=== VoteTransactionAsset

Allows to send a vote transaction, which casts votes and unvotes for delegates.

Each token can only be used once for voting, therefore the sender locks a certain amount of tokens for each vote.
After unvoting a delegate, the user is able to unlock the token again with the <<unlocktransactionasset, unlock transaction>>.

Name::
voteDelegate
ID::
1

.Schema
[source,typescript]
----
{
    $id: 'lisk/dpos/vote',
    type: 'object',
    required: ['votes'],
    properties: {
        votes: {
            type: 'array',
            minItems: 1,
            maxItems: 20,
            items: {
                type: 'object',
                required: ['delegateAddress', 'amount'],
                properties: {
                    delegateAddress: {
                        dataType: 'bytes',
                        fieldNumber: 1,
                        minLength: 20,
                        maxLength: 20,
                    },
                    amount: {
                        dataType: 'sint64',
                        fieldNumber: 2,
                    },
                },
            },
            fieldNumber: 1,
        },
    },
}
----

=== UnlockTransactionAsset

Allows to send an unlock transaction, which unlocks token that have been locked after voting for a delegate, after unvoting this delegate.

Name::
unlockToken
ID::
2

.Schema
[source,typescript]
----
{
    $id: 'lisk/dpos/unlock',
    type: 'object',
    required: ['unlockObjects'],
    properties: {
        unlockObjects: {
            type: 'array',
            minItems: 1,
            maxItems: 20,
            items: {
                type: 'object',
                required: ['delegateAddress', 'amount', 'unvoteHeight'],
                properties: {
                    delegateAddress: {
                        dataType: 'bytes',
                        fieldNumber: 1,
                        minLength: 20,
                        maxLength: 20,
                    },
                    amount: {
                        dataType: 'uint64',
                        fieldNumber: 2,
                    },
                    unvoteHeight: {
                        dataType: 'uint32',
                        fieldNumber: 3,
                    },
                },
            },
            fieldNumber: 1,
        },
    },
}
----

=== PomTransactionAsset

Allows to send a proof-of-misbehavior transaction, reports violations of the BFT protocol by a particular delegate.

Name::
reportDelegateMisbehavior
ID::
3

.Schema
[source,typescript]
----
{
    $id: 'lisk/dpos/pom',
    type: 'object',
    required: ['header1', 'header2'],
    properties: {
        header1: {
            ...blockHeaderSchema,
            fieldNumber: 1,
        },
        header2: {
            ...blockHeaderSchema,
            fieldNumber: 2,
        },
    },
}
----


== Actions

=== getAllDelegates

Returns a list of all registered delegates, including their username and address.
The address is returned as hex string.

==== Input
none


==== Returns
[source,json]
----
{
    username: string, <1>
    address: string, <2>
}[]
----

<1> Username of the delegate
<2> Address of the delegate as hex string.

=== getUnlockings
Returns a list of delegate unvotes of a certain account, the height of the unvote, and the minimum height for unlocking the tokens again.

==== Input

[source,json]
----
{
  address: string; <1>
}
----

<1> Address of the account as hex string.


==== Returns
[source,js]
----
{
    delegateAddress: string, <1>
    amount: string, <2>
    unvoteHeight: number, <3>
    minUnlockHeight: number, <4>
}[]
----

