= How to maintain a node
Mona Bärenfänger <mona@lightcurve.io>
:description: Learn how to maintain a Lisk node and also when it is recommended to run a specific node.
:toc:


== How to set up a node?

Simply follow the node setup guide for your desired distribution.
This is described on the xref:index.adoc#_distributions[Lisk Core Overview] page.

There are three available distributions of Lisk Core which can be seen below:

=== Binary

The *default* way to setup Lisk Core.
The xref:setup/binary.adoc[Binary installation] is an easy and automated way to set up Lisk Core, which includes almost completed automated update scripts; together with a selection of tools to assist with seamlessly maintaining a Lisk Node.

=== Commander

Use xref:setup/commander.adoc[Lisk Commander] to conveniently install and manage Lisk Core.

=== Docker

xref:setup/docker.adoc[Docker] adds support for additional platforms upon which to run a Lisk node.
For example, running a Lisk node inside of a Docker on Windows and connecting it via a custom Node on Lisk Desktop to Lisk Core, without the necessity to rent an additional server.

=== Source

This is designed for anyone wishing to develop on the Lisk Core codebase.
It also comes with an extensive test-suite, detailed in the following `README.md`.
An installation performed from xref:setup/source.adoc[Source] enables a developer to work on the newest codebase for Lisk Core, which may not have been tagged for a release yet.
