== The Lisk Protocol

=== Table of contents

[cols=",",options="header",]
|===
|Blockchain |Network
|link:blocks.md[Blocks] |link:p2p-communication.md[Peers Communication]
|link:security.md[Security] |link:transactions.md[Transactions]
| |link:consensus.md[Consensus]
|===

=== What is Lisk?

Lisk is a blockchain application platform created to bring blockchain
technology to the world through an SDK (Sidechain Development Kit)
written in JavaScript, the most commonly used programming language in
the world.

By utilizing sidechain technology, Lisk’s SDK enables developers to
build powerful and scalable blockchain applications, which include
custom tokens. With special focus on usability and accessibility, Lisk
aims to become the foremost platform for blockchain application
development in the world.

Headquartered in Zug, Switzerland, Lisk raised over 14,000 Bitcoins
during its ICO in Q1 2016.

=== Lisk Tokens

The utility token used in the Lisk ecosystem is known as Lisk (LSK).

This token is used to pay the fees associated with sending transactions
on the network. Each token also allows the holder to vote for delegates
that secure the network within the Lisk DPoS (Delegated Proof of Stake)
consensus protocol.

LSK tokens can be acquired through a number of ways, such as purchasing
them from an exchange or from another individual using Fiat or Bitcoin
(BTC).
