== The Lisk Protocol

* link:blocks.md[Blocks]
* link:transactions.md[Transactions]
* link:consensus.md[Consensus]
* link:security.md[Security]
* link:p2p-communication.md[Peers Communication]

=== What is Lisk?

Lisk is a blockchain application platform created to bring blockchain
technology to the world through an SDK (Sidechain Development Kit)
written in JavaScript, the most commonly used programming language in
the world.

By utilizing sidechain technology, Lisk’s SDK enables developers to
build powerful and scalable blockchain applications, which include
custom tokens. With special focus on usability and accessibility, Lisk
aims to become the foremost platform for blockchain application
development in the world.

Headquartered in Zug, Switzerland, Lisk raised over 14,000 Bitcoins
during its ICO in Q1 2016.

=== Lisk Tokens

The utility token used in the Lisk ecosystem is known as Lisk (LSK).

This token is used to pay the fees associated with sending transactions
on the network. Each token also allows the holder to vote for delegates
that secure the network within the Lisk DPoS (Delegated Proof of Stake)
consensus protocol.

LSK tokens can be acquired through a number of ways, such as purchasing
them from an exchange or from another individual using Fiat or Bitcoin
(BTC).

=== The Lisk Protocol

The Lisk Protocol is the formal set of rules of the Lisk blockchain.

It defines rules for the link:p2p-communication.md[peer-to-peer
communication], link:blocks.md[block] and
link:transactions.md[transaction] formats, the
link:consensus.md[consensus algorithm], and how
https://lisk.io/academy/blockchain-basics/how-does-blockchain-work/digital-signatures[signatures]
and link:security.md[IDs] are computed and verified.

The Lisk protocol is evolving following the objectives outlined by the
https://lisk.io/roadmap[Lisk roadmap]. Changes of the Lisk protocol are
formally specified as Lisk Improvement Proposals (LIPs) and published in
the https://github.com/LiskHQ/lips[LIPs Github repository]. The process
regarding LIPs is described in detail in the
https://github.com/LiskHQ/lips/blob/master/proposals/lip-0001.md[LIP
purpose and guidelines] and discussions about possible LIPs take place
openly and transparently at https://research.lisk.io[Lisk Research].
After a LIP comes into effect, i.e., the protocol changes have been
adopted by the Lisk blockchain, the official Lisk documentation will be
updated accordingly.

The protocol defines these rules without a focus on concrete
implementation, and it is, therefore, possible to implement it in any
common programming language.

Currently, the official implementations of the Lisk protocol are
link:../lisk-core/introduction.md[Lisk Core],
link:../lisk-sdk/lisk-framework/introduction.md[Lisk Framework] and
link:../lisk-sdk/lisk-elements/introduction.md[Lisk Elements], which are
written in Javascript and Typescript.
