= Lisk Core Migration
Mona Bärenfänger <mona@lightcurve.io>
:toc:

[IMPORTANT]
====
Migration of a Lisk Node is only necessary during a hard fork.
For standard software updates that do not invoke a hard fork, please perform a normal upgrade.
For more information please see xref:index.adoc#_upgrade_vs_migration[Upgrade vs Migration].
====

== What happens during migration

The migration is regarded as a special case for the upgrade of your Lisk Core node.
A migration is required if the new version of the software is incompatible with the older Lisk Core versions.

As a consequence here, the majority of the network needs to perform this software update simultaneously.
This is required in order to stabilize the forked chain and as a result, ensure it grows faster than the previous outdated version of the chain.

To achieve this, a height is picked to proceed with a simultaneous global upgrade.
When the block height of the network reaches the pre-defined height, it will invoke the update on all nodes in the network simultaneously.
Hence, the probabilities of creating forks are lower.

Apart from the normal update script that is used, the *Lisk Bridge* script may include additional scripts.
For example, if the new update includes changes in the structure of the configuration file, the script will attempt to reorganize your existing config to the new structure, which would then be followed by running the normal update script.
If it is not required to use the automated script, a detailed explanation of <<_migrate_manually, how to migrate manually>> can be found in the following section below.

This section describes how to use both automated and manual migration scripts for binary distributions of Lisk Core, in order to ensure that both methods of migration can be performed in a seamless manner.

== Automated Migration

=== Prepare your workspace

At this point it is assumed that Lisk Core has been succesfully installed and the user is now familiar with the application.
However, at this stage it is recommended to double check the points listed below:

* Revisit the xref:index.adoc#_distributions[setup] steps before continuing.
* Verify that the following ports are open, depending on the network in use:

[options="header"]
|===
|Network |HTTP |WebSocket
|Mainnet |8000 |8001
|Testnet |7000 |7001
|===

* Create a backup of `config.json`.
It is worth noting that although this process does perform a backup automatically in a `backup/` directory, it is recommended to create an additional back up, just for peace of mind.
At the end of this tutorial, some advanced cases are shown in order to provide the user with further helpful guidance.
* In the following section below, a useful tool is introduced which enables the user to perform a gapless migration.

=== Lisk Bridge: Automated Lisk Core Migration

This tool used to perform the migration is called *Lisk Bridge*, and can be found by accessing the following URL: https://downloads.lisk.io/lisk/[downloads.lisk.io].
Depending on which network your node is using, it is possible to directly download the applicable *Lisk Bridge* tool by accessing the appropriate link below:

* https://downloads.lisk.io/lisk/test/lisk_bridge.sh[Lisk Bridge for Testnet]
* https://downloads.lisk.io/lisk/main/lisk_bridge.sh[Lisk Bridge for Mainnet]

Basically this is actually a wrapper script that invokes `installLisk.sh upgrade` at a specific block height.
Therefore, it is intended for users employing the xref:setup/binary.adoc[Binary installation].

To upgrade the node on a specific network height, it is necessary to download `lisk_bridge.sh` . This should be downloaded into the same directory used for the download and execution of `installLisk.sh`.
In other words, it should be 1 directory up from where the lisk application is stored.
For example, if you are currently running `Lisk Core 0.9.16` as a user called `lisk`, `Lisk Core 0.9.16` is most likely to be installed in `/home/lisk/lisk-main` and `installLisk.sh` is stored in `/home/lisk`, the lisk user’s home directory.
Therefore as the lisk user, it will then be possible to execute the following:

[source,bash]
----
su - lisk <1>
rm -f lisk_bridge.sh <2>
wget https://downloads.lisk.io/lisk/<network>/lisk_bridge.sh <3>
----

<1> Change to lisk user.
<2> Remove old versions of `lisk_bridge.sh`.
<3> The `<network>` can either be `main` for Mainnet or `test` for Testnet.

This can be followed by executing the script with the desired parameters as shown below:

[source,bash]
----
bash lisk_bridge.sh -n <network> -h <blockheight>
----

Where `<network>` can either be `main` for Mainnet or `test` for Testnet.
The `<blockheight>` is before the announced blockheight when the hard fork is due to occur.

The bridge script will then execute and wait for the specified height of the network.
Upon reaching the specified height, it will invoke `installLisk.sh` to update the code, migrate the database to the new model, and finally update the config files.

If a fully automated migration is being performed, it would be possible to execute the `lisk_bridge.sh` inside of tmux, screen, byobu or another terminal multiplexer, and detach your session days ahead of time if required.
However it is recommended to minmize this lead time if the `LISK_MASTER_PASSWORD` is being exported.

[IMPORTANT]
====
*Important note for delegates:* After an automated upgrade has been performed, it will be necessary to manually enable forging again, as described in the following xref:configuration.adoc#_enabledisable_forging[configuration section].
====

A short video clip showing the expected output from the script execution can be seen below.
It is recommended to view this as it shows the expected output from the script execution, thus assisting the user to verify that the migration was completed successfully:

video::Zy9gyH-toBM[youtube,width=66%,height=100%]

=== Lisk Bridge Command Reference

For reference purposes, the lisk_bridge.sh usage help menu can be seen below:

[source,bash]
----
Usage: bash lisk_bridge.sh <-h <BLOCKHEIGHT>> [-s <DIRECTORY>] [-n <NETWORK>]
-h <BLOCKHEIGHT> -- specify blockheight at which bridging will be initiated
-f <TARBALL>     -- specify path to local tarball containing the target release
-s <DIRECTORY>   -- Lisk home directory
-n <NETWORK>     -- choose main or test

Example: bash lisk_bridge.sh -h 50000000 -n test -s /home/lisk/lisk-test
Set the LISK_MASTER_PASSWORD environment variable if it is required to perform secrets migration in non-interactive mode
----

=== What if I miss the block height or if Lisk Bridge script fails?

In this case, counting from the migration height there are 2 full forging rounds of time available, in order to perform a manual upgrade.
This can be completed by following the steps described in this link: <<_migrate-manually, Migrate manually>>.
If 2 full forging rounds have already passed since the migration occurred, then it is likely that your Node may be on a fork after the upgrade.
In order to resolve this, please rebuild your version of the blockchain xref:index.adoc#_snapshots[from snaphot] or xref:administration/binary.adoc#_rebuild_from_the_genesis_block[from genesis block].

=== Migration Notes Lisk Core 0.9 to 1.0

==== Neccessary utility scripts

The following utility scripts can be run by executing `lisk_bridge.sh` :

* <<_update_config,update_config.js>>: This migrates the config to new structure.

During the execution of `lisk_bridge.sh`, a password prompt will appear in the case whereby it finds a passphrase.
It will encrypt and migrate that passphrase to the new format.
If you wish to avoid this prompt and perform a full-automated migration, then add the next environment variable to your system:

[source,bash]
----
export LISK_MASTER_PASSWORD=XXXXXXXX
----

== Migrate manually

To perform a manual Lisk node migration, please follow the steps listed below:

. Backup your data.
. Run the necessary <<_utility_scripts, utility scripts>>.
These scripts prepare the Lisk node for the migration and are required before the upgrade script can run successfully.
The utility scripts that need to be run can vary depending on the migration.
. Perform the default xref:index.adoc#_upgrade_vs_migration[upgrade process].

=== Utility Scripts

It is not necessary to execute these scripts if the `lisk_bridge.sh` has already been run, as it is automatically executed there.

There are 2 useful command line scripts which the user may find helpful described below:

All scripts are located under the `./scripts/` directory and can be executed directly by the `node scripts/<file_name>`.

==== Generate Config

This script will assist in generating a unified version of the configuration file for any network.
The usage information can be seen below:

[source,bash]
----
Usage: node scripts/generate_config.js [options]

Options:

-h, --help               output usage information
-V, --version            output the version number
-c, --config [config]    custom config file
-n, --network [network]  specify the network or use LISK_NETWORK
----

The argument `network` is required and can be either `devnet`, `testnet`, `mainnet` or any other network folder available under `./config` directory.

==== Update Config

This script keeps track of all changes introduced in Lisk over time in different versions.
If one config file exists in any specific version, then the function of this script will make it compatible with other versions of Lisk.

[source,bash]
----
Usage: node scripts/update_config.js [options] <input_file> <from_version> [to_version]

Options:

-h, --help               output usage information
-V, --version            output the version number
-n, --network [network]  specify the network or use LISK_NETWORK
-o, --output [output]    output file path
----

As can be seen from the usage guide, `input_file` and `from_version` are required.
If you skip `to_version`, argument changes in the config.json will be applied up to the latest version of Lisk Core.
If the `--output` path is not specified, then the final config.json will be printed to stdout.
If the `--network` argument is not specified, then it will have to be loaded from `LISK_NETWORK` env variable.
