= Monitoring
Mona Bärenfänger <mona@lightcurve.io>
:description: The Monitoring page for Lisk Core describes different strategies how to monitor Lisk Core. Both log and performance monitoring with New Relic are also explained.
:toc:
:url_apache_bench: https://httpd.apache.org/docs/2.4/programs/ab.html
:url_github_core_tests: https://github.com/LiskHQ/lisk-core#tests
:url_grafana: https://grafana.com/
:url_graylog: https://www.graylog.org/
:url_kibana: https://www.elastic.co/products/kibana/
:url_newrelic: http://newrelic.com/
:url-newrelic-apm-intro: https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/introduction-new-relic-apm
:url_newrelic_rpm: https://rpm.newrelic.com
:url_siege: https://www.joedog.org/siege-manual
:url_logs_stream: configuration.adoc#file_log_stream

[[log_monitoring]]
== Log Monitoring

The xref:{url_logs_stream}[log files] provide a chronological list of activities that happened on a node.
These activities can be analyzed further to provide monitoring for a particular node or the network in general.
As the logs are created in JSON format, it is possible to pipe the log messages to additional monitoring software.
With monitoring software, the node operator can filter automatically for certain events and visualize them through a frontend application.
Also, it could be used to send notifications to the operator, in case of an emergency.

Various types of monitoring software packages currently exist that support log analysis.
For example: {url_kibana}[Kibana], {url_grafana}[Grafana] or {url_graylog}[Graylog].
