= Monitoring
Mona Bärenfänger <mona@lightcurve.io>
:description: The monitoring page for Lisk Core describes different strategies how to monitor Lisk Core.
:toc:

:url_grafana: https://grafana.com/
:url_graylog: https://www.graylog.org/
:url_kibana: https://www.elastic.co/products/kibana/

:url_logs_stream: management/logs.adoc#file_log_stream

[[log_monitoring]]
== Log monitoring

The xref:{url_logs_stream}[log files] provide a chronological list of activities that occurred on a node.
These activities can be analyzed further to provide monitoring for a particular node or the network in general.
As the logs are created in JSON format, it is possible to pipe the log messages to additional monitoring software.
With monitoring software, the node operator can filter automatically for certain events and visualize them through a front-end application.
In addition, it could also be used to send notifications to the operator in case of an emergency.

Various types of monitoring software packages currently exist that support log analysis.
For example: {url_kibana}[Kibana^], {url_grafana}[Grafana^] or {url_graylog}[Graylog^].
