= Quickstart

The quickest way to bootstrap a blockchain application with the Lisk SDK is explained here step-by-step.

== Installation

Create a `package.json` file.

[source,bash]
----
npm init --yes
----

Install the `lisk-sdk` package.

[source,bash]
----
npm i lisk-sdk
----

== Start the application

[NOTE]
====
The `lisk-sdk` package contains the sample objects `genesisBlockDevnet` and `configDevnet` which enable the user to quickly spin up a development blockchain network.
`genesisBlockDevnet` includes a set of preconfigured genesis delegates, that will immediately start forging on a single node to stabilize the network.
`configDevnet` includes the configuration for the Devnet.

Both objects can be customized before passing them to the `Application` instance, if desired.
====

Create a new file `index.js` and paste the following snippet.

[source,js]
----
const { Application, genesisBlockDevnet, configDevnet } = require('lisk-sdk'); <1>

const app = Application.defaultApplication(genesisBlockDevnet, configDevnet); <2>

app <3>
	.run()
	.then(() => app.logger.info('App started...'))
	.catch(error => {
		console.error('Faced error in application', error);
		process.exit(1);
	});
----

<1> Import the `Application`, `genesisBlockDevnet` and `configDevnet` from the `lisk-sdk` package.
<2> Creates a default application, which comes with all default modules.
<3> Starts the application.

After saving the file with the above contents, start the application as shown below:

[source,bash]
----
node index.js
----

To verify the application start, check the log messages in the terminal.
If the start was successful, the application will enable forging for all genesis delegates and will start to add new blocks to the blockchain every 10 seconds.

[NOTE]
====
After completing these steps, the default blockchain application of the Lisk SDK will now be running.

It will now be possible to start to customize your application by registering new modules and plugins, and also adjusting the genesis block and config to suit your specific use case.
====
