= RPC endpoints
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc:
// Project URLs
:url_guides_config: guides/app-development/configuration.adoc
:url_references_elements_apiclient: references/lisk-elements/api-client.adoc

The Lisk SDK offers two different API modes: `ipc` (Inter-process communication) and `ws` (WebSocket).

TIP: To conveniently communicate with the API from a client application, use the xref:{url_references_elements_apiclient}[]

If the node and the client are running on the same machine, it is recommended to use the `ipc` mode.

To enable the API to be reachable from remote, use the `ws` option.

[WARNING]
====
Allowing arbitrary machines to access the rpc port (ws) is dangerous and strongly discouraged -- access should be strictly limited to trusted machines.

To achieve this, configure a firewall that only allows access from whitelisted IPs
====

.API access options in the configuration
[source,js]
----
{
  //[...]
  rpc: {
    // Default: false
    // enabled creates IPC socket if true
    enabled: boolean,
    // Default: ipc
    // enabled communication through 'ipc' or 'ws'
    mode:'ipc',
    // Default: 8080
    // In case of WS, this port used
    port: 8080
  },
  //[...]
}
----

//@TODO: Uncomment, once dev guides are back
//For more information about the configuration of the Lisk SDK check out the xref:{url_guides_config}[configuration guide].

== Application actions

=== `app:getSchema`
Get the app schema.

==== Input
none

==== Returns

=== `app:getRegisteredModules`
Get a list of all modules that are registered in the application.

==== Input
none

==== Returns

=== `app:getNodeInfo`
Gets information about the node.

==== Input
none

==== Returns

=== `app:getConnectedPeers`
Returns all connected peers.

==== Input
none

==== Returns

=== `app:getDisconnectedPeers`
Returns all disconnected peers

==== Input
none

==== Returns

=== `app:getForgers`
Returns the status of all registered forgers information for the current round.

==== Input
none

==== Returns

=== `app:getForgingStatus`
Gets information about the forging status of the node.

==== Input
none

==== Returns

=== `app:updateForgingStatus`
Enable or disable forging for a registered forger in config.

==== Input

[source,typescript]
----
{
  address: string; <1>
  password: string; <2>
  forging: boolean; <3>
}
----
<1> binary address in hex string
<2> password to decrypt the passphrase
<3> when enabling forging, the value should be `true`

==== Returns

=== `app:getAccount`
Gets information about an account based on its address.

==== Input
[source,typescript]
----
{
  address: string; <1>
}
----
<1> address in hex string

==== Returns

=== `app:getAccounts`
Gets information about multiple accounts based on their address.

==== Input
[source,typescript]
----
{
  address: string[]; <1>
}
----
<1> address in hex string

==== Returns

=== `app:getLastBlock`
Gets the last forged block of the blockchain.

==== Input
none

==== Returns

=== `app:getBlockByID`
Get information about a block based on its ID.

==== Input
[source,typescript]
----
{
  id: string; <1>
}
----
<1> block ID in hex string

==== Returns

=== `app:getBlocksByIDs`
Get information about multiple blocks based on their IDs.

==== Input
[source,typescript]
----
{
  ids: string[]; <1>
}
----
<1> block ID in hex string

==== Returns

=== `app:getBlockByHeight`
Get information about a block based on its height.

==== Input
[source,typescript]
----
{
  height: number; <1>
}
----
<1> block height

==== Returns

=== `app:getBlocksByHeightBetween`
Get all blocks starting from height `from`, until height `to`.

==== Input
[source,typescript]
----
{
  from: number; <1>
  to: number; <2>
}
----
<1> block height to fetch from
<2> block height to fetch to

==== Returns

=== `app:getTransactionByID`
Gets information about a single transaction based on its ID.

==== Input
[source,typescript]
----
{
  ids: string; <1>
}
----
<1> transaction ID in hex string

==== Returns

=== `app:getTransactionsByIDs`
Gets information about multiple transactions based on their IDs.

==== Input
[source,typescript]
----
{
  ids: string[]; <1>
}
----
<1> transaction ID in hex string

==== Returns

=== `app:getTransactionsFromPool`
Gets information about all transactions that are currently in the transaction pool of the application.

==== Input
none

==== Returns

=== `app:postTransaction`
Posts a transaction to the node.

==== Input
[source,typescript]
----
{
  transaction: string; <1>
}
----
<1> encoded transaction in hex string

==== Returns

== Application events

=== `app:ready`
Fired when the application starts.

==== Returns

=== `app:shutdown`
Fired when the application stops.

==== Returns

=== `app:network:ready`
Fired when the network has at least one outbound connection.

==== Returns

=== `app:network:event`
Fired when the application receives P2P event from the network.

==== Returns

=== `app:transaction:new`
Fired when the node receives a new transaction.

==== Returns

=== `app:chain:fork`
Fired when the node received a block from the forked chain.

==== Returns

=== `app:chain:validators:change`
Fired when the node updates the validator set.

==== Returns

=== `app:block:new`
Fired when a new block is added to the blockchain.

==== Returns

=== `app:block:delete`
Emitted when a block is deleted from the blockchain.

==== Returns


== Module- and plugin-specific actions & events

Modules and plugins often expose own action events to the application.
All actions and events of modules and plugins that are registered with the application are available as RPC endpoints.

Events and actions are addressed in the following way:

.How action and event labels are constructed
----
"moduleOrPluginAlias:eventOrActionAlias"
----

//@TODO Add references to the events and actions references of the module pages
