= SDK Setup
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:imagesdir: assets/images

== Dependencies

The following dependencies need to be installed in order to run applications created with the Lisk SDK:

[cols=",",options="header",]
|===
|Dependencies |Version
|Node.js |10.17.0
|PostgreSQL |10+
|Redis (optional) |5+
|Python |2
|===

== Ports

[IMPORTANT]
====
*Mandatory:* Always open the *WebSocket* port of your desired network, to enable communication with other peer nodes.

*Optional:* Open the corresponding HTTP port for your network, to make your node’s https://lisk.io/documentation/lisk-core/api[API] reachable.
For more info, see the diagram on the xref:getting-started/interact-with-network.adoc[Interact with network] page.
====

To connect to the desired network with Lisk Core, please ensure that the corresponding ports are open:

[options="header",]
|===
|Network |HTTP |WebSocket
|Devnet |4000 |5000
|===

The ports can be xref:configuration.adoc[altered] later in the xref:configuration.adoc#_structure[`configuration`] file.

== Pre-Installation

=== Create a new user

[NOTE]
====
To install the required prerequisites, it is necessary to have a user with sudo rights on the server.
The `lisk` user itself *does not need* any `sudo` rights to run the node.
====

To run and manage a node in the future, please create a separate `lisk` user.
E.g. execute:

[tabs]
=====
Ubuntu::
+
--
[source,bash]
----
sudo adduser lisk
----
--
MacOS::
+
--
It is not essentially needed to set up a `lisk` user, especially when you are running a local instance for development purposes.
If you still want to do it, we recommend to create the user using the macOS GUI: https://support.apple.com/en-gb/guide/mac-help/mtusr001/mac
--
=====

=== Toolchain components

Used for compiling dependencies.

[tabs]
=====
Ubuntu::
+
--
[source,bash]
----
sudo apt install -y libtool automake autoconf curl python-minimal build-essential
----
--
MacOS::
+
--
Ensure that both https://developer.apple.com/xcode/[XCode] and https://brew.sh/[Homebrew] are installed.

[source,bash]
----
brew install autoconf automake libtool
----
--
=====

include::partial$install-postgres.adoc[]

include::partial$install-node.adoc[]

=== PM2 (optional)

Install https://github.com/Unitech/pm2[PM2] for managing start/stop of the app process in the background:

[source,bash]
----
npm install pm2 -g
----

== Installation

To install the NPM package https://www.npmjs.com/package/lisk-sdk[lisk-sdk], run:

[source,bash]
----
npm install lisk-sdk
----
