= Lisk Core Troubleshooting
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Troubleshooting page provides solutions for the most common problems that can occur while installing or managing Lisk Core.
:toc:
:url_lisk_discord: https://lisk.chat/
:url_config: configuration.adoc
:url_config_forging: configuration.adoc#forging
:url_forging_enable_disable: configuration.adoc#forging_enable_disable

== Setup

=== A process is already listening on port 5432 (Binary)

==== Problem:

After running `+installLisk.sh+`, the installation script is aborted with the following output:

....
Error: A process is already listening on port 5432
PostgreSQL by default listens on 127.0.0.1:5432 and attempting to run two instances at the same time will result in this installation failing
To proceed anyway, use the -i flag to ignore the warning.
....

PostgreSQL is already installed on your system and listening to the PostgreSQL default port 5432. For example, this can happen when a second Lisk Core node is installed on the same server.

[tabs]
====
Solution 1::
+
--
If postgreSQL has been installed globally on the system, disable it using the following commands:

[source,bash]
----
sudo systemctl stop postgresql
sudo systemctl disable postgresql
----

Possible data inside of databases remains stored in this case.
--
Solution 2::
+
--
If postgreSQL has been installed globally on the system and the data in it is not needed anymore, simply remove the already installed postgreSQL by running the following command:

[source,bash]
----
sudo apt-get --purge remove postgresql postgresql-doc postgresql-common
----
--
====

=== Role lisk does not exist (Source)

==== Problem:

Starting the Lisk node fails with the following error:

....
error: role "lisk" does not exist
....

Lisk Core expects a Postgres user called `lisk` exists on the system and has the rights to create a database.
This user is specified in `config.json`.
If the user is not present on the system, the above error will be thrown.

[tabs]
====
Solution 1 - create lisk user::
+
--
Create a Postgres user with name `lisk` and grant it the right to create databases.

[source,bash]
----
  sudo -u postgres createuser --createdb lisk
----
--
Solution 2 - change db.user from lisk to custom username::
+
--
Edit xref:{url_config}[`config.json`] and replace the value `lisk` in `db.user` with an alternative Postgres username on the system that has the right to create databases.
--
====

=== Nothing is visible in the console after starting Lisk Core (Source)

==== Problem:

After installing from Source and starting Lisk Core with `node dist/index.js`, no are logs visible in the console.
This is an expected response, as the default console logging value in the config is `none`, which means no logs are shown in the console after starting the process.

===== Solution:

To rectify this and verify that your installation works as expected, it is recommended to change the`+consoleLogLevel+` to `error`, `info` or `debug`.
Alternatively, check the log files located in `logs/`, which are on `info` logging level by default.

== Administration

=== Enable forging: Delegate not found

==== Problem:

When trying to activate forging on your node, the following response was received:
`Delegate with publicKey: xyz not found`

[tabs]
====
Solution 1 - Node still syncing::
+
--
Check the current height of your Node and compare it with the Height in Explorer.
If your Nodes’ height is significantly lower than the height shown in the Explorer, it means your Node is still syncing/downloading the Lisk Blockchain.
At this time enabling forging might fail, due to the fact that the Delegate registration has not been downloaded yet.
To solve this issue, wait until your Node is fully synced.
--
Solution 2 - Missing data in config ::
+
--
Check your `config.json` in section `forging.delegates`.
If it is required to enable forging for a particular delegate on your node, an object with the delegates’ public key and encrypted passphrase in that section needs to be stored, as described in the xref:{url_config_forging}[configuration:forging] section.
--
====

=== Enable forging: Invalid password and public key combination

==== Problem:

When trying to activate forging on a node like described in section xref:{url_forging_enable_disable}[Enable/Disable forging], it responds with: `{"message":"\"Invalid password and public key combination\""}`.

==== Solution:

As the message states, the provided combination of your delegates publicKey and the password is invalid.
Please ensure both properties are set to the correct values, and that the original passphrase of your account is not used with that command.

[NOTE]
====
The naming convention is explained below:

* *Passphrase* is always referring to the 12-word long mnemonic passphrase that was created at the same time as your Lisk ID.
This should always be kept secure and private.
For communication with the API the passphrase is not sent in plaintext.
However, the password is sent in plaintext so it can be used to encrypt the passphrase which is stored in your xref:{url_config}[config].
* *Password* is always referring to the secret word(s) used to encrypt the passphrase symmetrically, as described in the xref:{url_config_forging}[Forging section].
====

For any further queries please reach out to one of the team the Lisk community on {url_lisk_discord}[Lisk Discord]