= SDK Tutorials
Mona Bärenfänger <mona@lightcurve.io>
:toc:

Get onboarded to the Lisk SDK with step-by-step walkthroughs that simplify the process of developing a proof of concept blockchain application.

== What do the tutorials cover?

* How to initially set up the Lisk SDK and get the network started.
* How to develop a new transaction type and how to register it with the application.
* How to create a sendable transaction object of the new type, and broadcast it to the network.

== Hello World

Built using the Alpha SDK, our Hello World application explains how to create a new transaction type from scratch.

Hello World is a simple example to showcase how to create a new transaction type by implementing the xref:2.3.2@lisk-sdk::customize.adoc[BaseTransaction interface].

* xref:tutorials/hello-world.adoc[Hello World Tutorial]
* https://github.com/LiskHQ/lisk-sdk-examples/tree/development/hello_world[Full code example of Hello World application on GitHub]

== Cashback

The Cashback application shows you how to create a new custom transaction inherited from a pre-existing transaction type.

Built by extending the balance transfer transaction, in addition to the regular transfer functionality, the cashback transaction also applies an inflationary 10% to the senders account.

This tutorial is an example of a simple but valid use case - a cashback transaction.

* xref:tutorials/cashback.adoc[Cashback Tutorial]
* https://github.com/LiskHQ/lisk-sdk-examples/tree/development/cashback[Full code example of Cashback application on GitHub]
