= Managing Lisk Core
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:v_core: master

Install and manage an instance of Lisk Core.

[IMPORTANT]
====
The commands for Lisk Core are not compatible with other distributions or with installations from the xref:{v_core}@lisk-core::setup/binary.adoc#_option_b_the_bash_script[bash script].
To manage Lisk Core with Lisk Commander, first uninstall the old version and perform a fresh <<_lisk_coreinstall_name,installation>>.
====

== lisk core:install NAME

Install an instance of Lisk Core.

[source,bash]
----
USAGE
  $ lisk core:install NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

OPTIONS
  -n, --network=mainnet|testnet|betanet|alphanet|devnet  [default: mainnet] Lisk Core network name.
  -r, --release-url=release-url                          Lisk Core download URL.

  -s, --snapshot-url=snapshot-url                        [default:
                                                         https://downloads.lisk.io/lisk/mainnet/blockchain.db.gz] Lisk
                                                         Core blockchain snapshot URL.

  --lisk-version=lisk-version                            Lisk Core version.

  --no-snapshot                                          Install Lisk Core without a blockchain snapshot.

  --no-start                                             Install Lisk Core without starting.

EXAMPLES
  core:install lisk-mainnet
  core:install --no-start lisk-mainnet
  core:install --no-snapshot lisk-mainnet
  core:install --lisk-version=2.0.0 lisk-mainnet
  core:install --network=testnet --release-url=https://downloads.lisk.io/lisk/testnet/2.0.0-rc.0/lisk-2.0.0-rc.0-Linux-x86_64.tar.gz lisk-testnet
  core:install --network=mainnet --snapshot-url=https://downloads.lisk.io/lisk/mainnet/blockchain.db.gz custom-mainnet
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/install.ts[dist/commands/core/install.ts]_

== lisk core:logs NAME

Stream logs of a Lisk Core instance.

[source,bash]
----
USAGE
  $ lisk core:logs NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

EXAMPLE
  core:logs mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/logs.ts[dist/commands/core/logs.ts]_

== lisk core:restart NAME

Restart Lisk Core instance.

[source,bash]
----
USAGE
  $ lisk core:restart NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

EXAMPLE
  core:restart mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/restart.ts[dist/commands/core/restart.ts]_

== lisk core:start NAME

Start Lisk Core instance.

[source,bash]
----
USAGE
  $ lisk core:start NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

EXAMPLE
  core:start mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/start/index.ts[dist/commands/core/start/index.ts]_

== lisk core:start:cache NAME

Start the cache server.

[source,bash]
----
USAGE
  $ lisk core:start:cache NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

EXAMPLE
  core:start:cache mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/start/cache.ts[dist/commands/core/start/cache.ts]_

== lisk core:start:database NAME

Start the database server.

[source,bash]
----
USAGE
  $ lisk core:start:database NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

EXAMPLE
  core:start:database mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/start/database.ts[dist/commands/core/start/database.ts]_

== lisk core:status NAME

Show the status of a Lisk Core instances.

[source,bash]
----
USAGE
  $ lisk core:status [NAME]

ARGUMENTS
  NAME  Lisk Core installation directory name.

OPTIONS
  -j, --[no-]json  Prints output in JSON format. You can change the default behaviour in your config.json file.

  --[no-]pretty    Prints JSON in pretty format rather than condensed. Has no effect if the output is set to table. You
                   can change the default behaviour in your config.json file.

EXAMPLES
  core:status
  core:status mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/status.ts[dist/commands/core/status.ts]_

== lisk core:stop NAME

Stop Lisk Core instance.

[source,bash]
----
USAGE
  $ lisk core:stop NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

EXAMPLE
  core:stop mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/stop/index.ts[dist/commands/core/stop/index.ts]_

== lisk core:stop:cache NAME

Stop the cache server.

[source,bash]
----
USAGE
  $ lisk core:stop:cache NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

EXAMPLE
  core:stop:cache mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/stop/cache.ts[dist/commands/core/stop/cache.ts]_

== lisk core:stop:database NAME

Stop the database server.

[source,bash]
----
USAGE
  $ lisk core:stop:database NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

EXAMPLE
  core:stop:database mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/stop/database.ts[dist/commands/core/stop/database.ts]_

== lisk core:uninstall NAME

Uninstall an instance of Lisk Core.

[source,bash]
----
USAGE
  $ lisk core:uninstall NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

EXAMPLE
  core:uninstall mainnet-latest
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/uninstall.ts[dist/commands/core/uninstall.ts]_

== lisk core:upgrade NAME

Upgrade an instance of Lisk Core (Binary) to a specified or latest
version.

NOTE: The `core:upgrade` command is only supported for Lisk Core versions > `2.0.0`.

[source,bash]
----
USAGE
  $ lisk core:upgrade NAME

ARGUMENTS
  NAME  Lisk Core installation directory name.

OPTIONS
  -r, --release-url=release-url  Lisk Core download URL.
  --lisk-version=lisk-version    Lisk Core version.

EXAMPLES
  core:upgrade lisk-mainnet
  core:upgrade --lisk-version=2.0.0 lisk-mainnet
  core:upgrade --release-url=https://downloads.lisk.io/lisk/testnet/2.1.0-rc.0/lisk-2.1.0-rc.0-Linux-x86_64.tar.gz
  lisk-mainnet
----

_See code: https://github.com/LiskHQ/lisk-sdk/blob/master/commander/src/commands/core/upgrade.ts[dist/commands/core/upgrade.ts]_
