= Connecting Lisk Service to a blockchain node
Muhammad Talha <muhammad.talha@lightcurve.io>
:toc: preamble
:toclevels: 3
:page-toclevels: 3
:sectnums:
:idprefix:
:idseparator: -

:docs_core: v4@lisk-core::
:docs_service: 0.7@lisk-service::
:url_service_index: {docs_service}index.adoc
:url_npm_core_setup: {docs_core}setup/npm.adoc
:url_blockchain_client: build-blockchain/create-blockchain-client.adoc
:url_service_docker_setup: {docs_service}setup/docker.adoc
:url_service_source_setup: {docs_service}setup/source.adoc
:url_connect_node: {docs_service}/setup/docker.adoc#connecting-lisk-service-to-a-blockchain-node
:url_sidechain: understand-blockchain/interoperability/index.adoc#sidechain
:rpc_api: api/lisk-service-rpc.adoc
:http_api: api/lisk-service-http.adoc
:pm2_sidechain: run-blockchain/process-management.adoc#using-a-json-config-file

//footnotes

:fn_node_config: footnote:config[Events are necessary to determine the transaction execution status and the actual block generation rewards. Without this information, Lisk Service wouldn’t be able index the all the transactions. Thus, the indexing will be incomplete. Setting "system.keepEventsForHeights: -1" will ensure that the events are not deleted and are maintained on the node for all the block heights. By default the node only maintains the events for the last 300 blocks.]

xref:{url_service_index}[Lisk Service] is a web application middleware that allows interaction with various blockchain networks based on the Lisk protocol.
In this guide, you'll learn to connect Lisk Service to a blockchain node.
Lisk Service is installed in addition to a Lisk blockchain application such as Lisk Core or a sidechain client, to provide enriched network data for third-party services.

[NOTE]
====
*Pre-requisite*

1. It is required to set up a blockchain node.

* Make sure that you have set up a blockchain node e.g. Lisk Core node. 
Please refer to the dedicated setup guides, such as the xref:{url_npm_core_setup}[].
* Alternatively, you can setup up a xref:{url_sidechain}[sidechain] node to connect with Lisk Service.
* Please make sure to set `system.keepEventsForHeights: -1` in the node config{fn_node_config} before synchronizing the node with the network.

2. It is required to set up Lisk Service.

* Lisk Service must be set up via either the recommended xref:{url_service_docker_setup}[] or the xref:{url_service_source_setup}[] guide.
====

== Configuring a node



Use the client CLI to start the node with the desired configurations.

* `--api-ws` enables the WebSocket API of the node, if not already enabled within the *config.json* file.
* `--api-ws-host=0.0.0.0` allows remote servers to connect to the blockchain node via WS API.
If this option is not set, it defaults to `127.0.0.1`.
* `--api-ws-port=7887` is the port for the WebSocket API.
* `--api-http` allows remote servers to connect with the blockchain node via HTTP.

[tabs]
=====
Sidechain node::
+
--
We recommend using xref:{pm2_sidechain}[PM2 for running a node], the starting script of the *pm2.conf.json* file can look like the following:

.pm2.conf.json
[source,json]
----
{
  "apps": [
    {
      "name": "hello_client",
      "script": "./bin/run start --api-ws --api-ws-host=0.0.0.0 --api-ws-port=7887 --api-http"
    }
  ]
}
----

To start the node with your desired configurations mentioned above, execute the following command:

[source,bash]
----
pm2 start pm2.conf.json
----
--
Lisk Core node::
+
--
The `--network` flag determines the blockchain network Lisk Core connects to.

[source,bash]
----
lisk-core start --network mainnet --api-ws --api-ws-host=0.0.0.0 --api-ws-port=7887 --api-http
----
To connect to a different network, replace `mainnet` with either `testnet` or `devnet`.
--
=====

Once the node starts, follow the steps mentioned in the xref:{url_connect_node}[Connecting Lisk Service to a blockchain node] section to connect Lisk Service with a node.

== Running Lisk Service
Run the docker container for `lisk-service`, `redis`, and `mysql` or `mariadb`. It is recommended to use `mariadb` instead of `mysql` when running on Darwin.

[tabs]
=====
lisk-service::
+
--
.Run "lisk-service" container: ./lisk-service/
[source,bash]
----
make up
----
--
redis::
+
--
.Run "redis" container: ./lisk-service/jenkins/redis
[source,bash]
----
make up
----
--
mariadb::
+
--
.Run "mariadb" container: ./lisk-service/jenkins/mariadb
[source,bash]
----
make up
----
--
=====

== Checking established connection 

After both the blockchain client and the Lisk Service are running, you'll see a similar message to the following on your node CLI.

[source,bash]
----
2023-06-27T11:03:39.085Z INFO XYZ.local engine 35439 New web socket client connected
----

Another hint that Lisk Service is now connected to your node is the occurrence of the following entry in the logs from the `blockchain-connector` service.

[source,bash]
----
2023-06-26T16:09:28.435 INFO [app] Found a node, starting service LISK-SERVICE-BLOCKCHAIN-CONNECTOR...
----

You can also invoke an endpoint of the blockchain node via Lisk service API like the following, to verify that the connection was established successfully.

[source,bash]
----
curl --location 'http://localhost:9901/api/v3/invoke' --header 'Content-Type: application/json' --data '{"endpoint": "chain_getLastBlock","params": {}}' | json_pp
----

For more information about Lisk Service APIs, see xref:{rpc_api}[] or xref:{http_api}[] reference pages.
