= Configuration with Docker
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes how to configure Lisk Service with Docker.
:toc:
:imagesdir: ../assets/images
:page-previous: /lisk-service/setup/docker.html
:page-previous-title: Installation with Docker
:page-next: /lisk-service/management/docker.html
:page-next-title: Docker commands

:url_references_config: references/configuration.adoc

How to configure Lisk Service.

== Show current configuration

To show the current configuration of Lisk Service, execute the following command:

[source,bash]
----
make print-config
----

.Result for the default config, which will connect Lisk Service to the Lisk Mainnet
[source,yaml]
----
networks:
  core_network: {}
  services_network: {}
services:
  core:
    depends_on:
      mysql_core:
        condition: service_started
      redis_common:
        condition: service_started
      redis_core:
        condition: service_started
    environment:
      ENABLE_FEE_ESTIMATOR_FULL: "false"
      ENABLE_FEE_ESTIMATOR_QUICK: "true"
      ENABLE_JOB_MISSING_BLOCKS: "true"
      ENABLE_TRANSACTION_STATS: "true"
      FEE_EST_DEFAULT_START_BLOCK_HEIGHT: ''
      GENESIS_BLOCK_URL: ''
      GENESIS_HEIGHT: ''
      GEOIP_JSON: https://geoip.lisk.io/json
      INDEX_MISSING_BLOCKS_RANGE: '1080'
      INDEX_N_BLOCKS: '0'
      LISK_CORE_HTTP: ''
      LISK_CORE_WS: ws://localhost:8080
      LISK_STATIC: https://static-data.lisk.io
      SERVICE_BROKER: redis://redis_common:6379/0
      SERVICE_CORE_MYSQL: mysql://lisk:password@mysql_core:3306/lisk
      SERVICE_CORE_REDIS: redis://redis_core:6379/0
      SERVICE_LOG_CONSOLE: "false"
      SERVICE_LOG_FILE: "false"
      SERVICE_LOG_GELF: "false"
      SERVICE_LOG_LEVEL: debug
      SERVICE_LOG_STDOUT: "true"
      TRANSACTION_STATS_HISTORY_LENGTH_DAYS: ''
    extra_hosts:
      host.docker.internal: host-gateway
    image: lisk/service_core
    networks:
      core_network: {}
      services_network: {}
    restart: always
  gateway:
    depends_on:
      core:
        condition: service_started
    environment:
      ENABLE_HTTP_API: http-status,http-version
      ENABLE_HTTP_CACHE_CONTROL: "false"
      ENABLE_WS_API: ''
      HOST: 0.0.0.0
      HTTP_CACHE_CONTROL_DIRECTIVES: public,max-age=10
      PORT: '9901'
      SERVICE_BROKER: redis://redis_common:6379/0
      SERVICE_LOG_CONSOLE: "false"
      SERVICE_LOG_FILE: "false"
      SERVICE_LOG_GELF: "false"
      SERVICE_LOG_LEVEL: debug
      SERVICE_LOG_STDOUT: "true"
    healthcheck:
      test: curl --fail http://gateway:9901/api/v1/transactions
    image: lisk/service_gateway
    networks:
      services_network: {}
    ports:
    - 127.0.0.1:9901:9901/tcp
    restart: always
  market:
    depends_on:
      redis_common:
        condition: service_started
      redis_market:
        condition: service_started
    environment:
      SERVICE_BROKER: redis://redis_common:6379/0
      SERVICE_LOG_CONSOLE: "false"
      SERVICE_LOG_FILE: "false"
      SERVICE_LOG_GELF: "false"
      SERVICE_LOG_LEVEL: debug
      SERVICE_LOG_STDOUT: "true"
      SERVICE_MARKET_REDIS: redis://redis_market:6379/0
    image: lisk/service_market
    networks:
      services_network: {}
    restart: always
  mysql_core:
    environment:
      MYSQL_DATABASE: lisk
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: lisk
    healthcheck:
      retries: 10
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - localhost
      timeout: 20s
    image: mysql:5.7
    networks:
      core_network: {}
    restart: always
    volumes:
    - mysql-data:/var/lib/mysql:rw
  redis_common:
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
    image: redis:5-alpine
    networks:
      services_network: {}
    restart: always
    volumes:
    - /home/lisk/lisk-service/docker/redis/redis.volatile.conf:/etc/redis/redis.conf:ro
  redis_core:
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
    image: redis:5-alpine
    networks:
      core_network: {}
    restart: always
    volumes:
    - /home/lisk/lisk-service/docker/redis/redis.persistent.conf:/etc/redis/redis.conf:ro
  redis_market:
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
    image: redis:5-alpine
    networks:
      services_network: {}
    restart: always
    volumes:
    - /home/lisk/lisk-service/docker/redis/redis.persistent.conf:/etc/redis/redis.conf:ro
version: '3'
volumes:
  mysql-data: {}
----


////
[[default_configs]]
== Default configurations

Lisk Service provides different ready-to-use configuration files, which are located in the `docker/` folder of Lisk Service.

.lisk-service/docker/
----
├── custom.env
├── docker-compose.betanet.yml
├── docker-compose.custom.yml
├── docker-compose.devnet.yml
├── docker-compose.mainnet.yml
└── docker-compose.testnet.yml
----

To connect to any of the networks displayed in the snippet above, simply change line 9 in the `Makefile` file:

.Example: How to update the `Makefile`, to connect to the Betanet with Lisk Service
[source,bash]
----

.PHONY: clean coldstart mrproper up
all: up

compose := docker-compose \
	-f docker-compose.yml \
	-f lisk_service/docker-compose.core.yml \
	-f lisk_service/docker-compose.gateway.yml \
	-f lisk_service/docker-compose.gateway-ports.yml \
	-f docker-compose.betanet.yml <1>
----

<1> Update this line from `-f docker-compose.mainnet.yml` to `-f docker-compose.NETWORK.yml`, where `NETWORK` can be either:
* `betanet`
* `custom`
* `devnet`
* `mainnet`
* `testnet`

After updating the `Makefile` as described above, start Lisk Service again:

[source,bash]
----
make up
----

Lisk Service should now be connected to the desired network.

== Custom configuration
:sectnums:

=== The custom.env file

First, open the file `docker/custom.env` .

The following contents below will be displayed:

[source,bash]
----
## Lisk Service custom configuration

# Lisk Core node
LISK_CORE_HTTP=https://mainnet.lisk.io
LISK_CORE_WS=wss://mainnet.lisk.io
----

The two existing options `LISK_CORE_HTTP` and `LISK_CORE_WS` are examples of how to set config options in this file.

To see a list of the most important options, check out the preconfigured `env` files in the `docker/lisk-service/env/network` folder.

To check and view the complete list of all available config options of Lisk Service, go to the xref:{url_references_config}[configuration reference].

=== Update the Makefile

.How to update the `Makefile` to use a custom configuration
[source,bash]
----

.PHONY: clean coldstart mrproper up
all: up

compose := docker-compose \
	-f docker-compose.yml \
	-f lisk_service/docker-compose.core.yml \
	-f lisk_service/docker-compose.gateway.yml \
	-f lisk_service/docker-compose.gateway-ports.yml \
	-f docker-compose.custom.yml <1>
----

<1> Update this line from `-f docker-compose.mainnet.yml` to `-f docker-compose.custom.yml`.

=== Start Lisk Service

All that is now remaining is to start Lisk Service again:

.In the `lisk-service` root folder
[source,bash]
----
make up
----

:!sectnums:
////
