= Configuring a Plugin
Muhammad Talha <muhammad.talha@lightcurve.io>

Our plugin will sync on-chain event's data with the off-chain database after a certain time interval. So, On this page, you will learn:

====
* [x] Defining a sync interval.
* [x] Overwrite default sync interval.
====


== Defining a sync interval
A plugin can have its own set of configurations, and as we want our plugin to sync with the on-chain data after a specific interval, a config will help.

Open the `schemas.ts` file and define `configSchema` there. It will have an integer type property: `syncInterval`. It's essential to define a default value to the `syncInterval` in milliseconds as well.

.hello_client/src/app/plugins/hello_info/schemas.ts
[source,typescript]
----
export const configSchema = {
    $id: '#/plugins/helloInfo/config',
    type: 'object',
    properties: {
        syncInterval: {
            type: 'integer',
        },
    },
    required: ['syncInterval'],
    default: {
        syncInterval: 120000, // milliseconds
    },
};
----

We will use a `syncInterval` variable in our HelloInfo plugin class as well so let's define that in the `types.ts` file.

.hello_client/src/app/plugins/hello_info/types.ts
[source,typescript]
----
// [...]

export interface HelloInfoPluginConfig {
    syncInterval: number;
}
----

== Overwrite default sync interval

The aforementioned schema and type is enough for our plugin to function, however, there may be an optional case where a node operator wants to increase or decrease the time of sync interval so, for that they can add it in the `custom_config.json` file under the `plugins` property.

If a value is available in the `custom_config.json` for the syncInterval, the plugin will automatically take that value in consideration and overwrite the default value for interval synchronization.

.hello_client/config/custom_config.json
[source,json]
----
// [...]
"plugins": {
    "helloInfo": {
        "syncInterval": 60000 
    }
}
----
