= Configuring a Plugin
Muhammad Talha <muhammad.talha@lightcurve.io>
:toc: preamble
:idprefix:
:idseparator: -
:sectnums:
// URLs
:url_github_schemas: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/hello_client/src/app/plugins/hello_info/schemas.ts
:url_github_types: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/hello_client/src/app/plugins/hello_info/types.ts
:url_github_custom_config: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/hello_client/config/custom_config.json



The HelloInfoPlugin should sync on-chain events data with the off-chain database after a configured time interval. 

====
On this page, you'll learn:

* [x] Defining configuration for a plugin.
* [x] Overwriting default configuration.
====

TIP: The relevant files discussed in this guide are {url_github_schemas}[schemas.ts^], {url_github_types}[types.ts^], and {url_github_custom_config}[custom_config.json^].

== Defining a sync interval configuration
A plugin is capable of having its own set of configurations, and since we aim for our plugin to sync with on-chain data at specific intervals, having a config will be beneficial.

We will use a `syncInterval` variable in our `HelloInfoPlugin` class so, let's define that in the `types.ts` file.

.hello_client/src/app/plugins/hello_info/types.ts
[source,typescript]
----
// [...]

export interface HelloInfoPluginConfig {
    syncInterval: number;
}
----

After that, Open the `schemas.ts` file and define `configSchema` there. 
It will have an integer-type property: `syncInterval`. 
It's essential to define a default value to the `syncInterval` in milliseconds as well.

.hello_client/src/app/plugins/hello_info/schemas.ts
[source,typescript]
----
export const configSchema = {
	$id: '/plugins/helloInfo/config',
	type: 'object',
	properties: {
		syncInterval: {
			type: 'integer',
		},
	},
	required: ['syncInterval'],
	default: {
		syncInterval: 120000, // milliseconds
	},
};
----

== Overwrite default sync interval

The aforementioned type and schema definition are enough for our plugin to function, however, there may be an optional case where a node operator wants to increase or decrease the time of sync interval so, for that, they can add it in the `custom_config.json` file under the `plugins` property.

If a value is available in the `custom_config.json` for the `syncInterval`, the plugin will automatically consider that value and overwrite the default value for interval synchronization.

.hello_client/config/custom_config.json
[source,json]
----
// [...]
"plugins": {
    "helloInfo": {
        "syncInterval": 60000 
    }
}
----

Now that we have added Plugin's configuration, it's time to update the `HelloInfoPlugin` class as described in the next guide.