= Defining off-chain data structures
Muhammad Talha <muhammad.talha@lightcurve.io>

:toc: preamble
:idprefix:
:idseparator: -
// :sectnums:
:docs_sdk: lisk-sdk::
// URLs
:url_github_guides_plugin: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/hello_client/src/app/plugins/hello_info
:url_github_schemas: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/hello_client/src/app/plugins/hello_info/schemas.ts
:url_github_types: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/hello_client/src/app/plugins/hello_info/types.ts

// Project URLS
:url_block_height: glossary.adoc#block-height

The `HelloInfoPlugin` will need to store data of events emitted by the `HelloModule`. So, On this page, you will learn:

====
* [x] Defining Schemas for events, counter, and height.
* [x] Defining Types for events, counter, and height.
* [x] Defining Constants for unique key generation.
====

TIP: The relevant files discussed in this guide are {url_github_schemas}[schemas.ts] and {url_github_types}[types.ts].

== Defining Schemas
Create a new file called `schemas.ts` inside the `hello_info` directory. 
Inside the `schemas.ts`, we want to define schemas of various data that will be stored by the plugin's database.

These schemas will be used by Lisk Framework for validating, encoding, and decoding data. 
The `HelloInfoPlugin` needs to store three kinds of data.

. On-chain NewHelloEvent's data, which contains
.. The sender address
.. The hello message
.. The xref:{url_block_height}[block height] where the event was found by HelloInfoPlugin.
. A counter for the number of NewHelloEvents stored off-chain.
It is also used for unique key generation.
. The last block height checked by the plugin.

[#NewHelloEvent]
*On-chain NewHelloEvent's data*: The NewHelloEvent's data will be fetched from the sidechain by the plugin and will be stored in the plugin's database.
The `newHelloEventSchema` will be used for encoding, decoding, and storing the sender address, hello message, and block height in the database.

.hello_client/src/app/plugins/hello_info/schemas.ts
[source,typescript]
----
export const newHelloEventSchema = {
    $id: '/helloInfo/new_hello',
    type: 'object',
    required: ['senderAddress', 'message', 'height'],
    properties: {
        senderAddress: {
            dataType: 'bytes',
            fieldNumber: 1,
        },
        message: {
            dataType: 'string',
            fieldNumber: 2,
        },
        height: {
            dataType: 'uint32',
            fieldNumber: 3,
        },
    },
};
----


*A Counter for NewHelloEvents stored off-chain:* The HelloInfoPlugin will store a counter for the number of NewHelloEvent stored in the off-chain database. 
Each counter's value will also be used for key generation for our off-chain database. So, let's define the `counterSchema` in the `schemas.ts` file.

.hello_client/src/app/plugins/hello_info/schemas.ts
[source,typescript]
----
export const counterSchema = {
    $id: '/helloInfo/counter',
    type: 'object',
    required: ['counter'],
    properties: {
        counter: {
            dataType: 'uint32',
            fieldNumber: 1,
        },
    },
};
----

*Height of the last block checked*: As the name suggests, we want to store the last block height checked by the plugin for NewHelloEvent retrieval.
This will enable the plugin to only check newer blocks of the sidechain for any new hello event.

.hello_client/src/app/plugins/hello_info/schemas.ts
[source,typescript]
----
export const heightSchema = {
    $id: '/helloInfo/height',
    type: 'object',
    required: ['height'],
    properties: {
        height: {
            dataType: 'uint32',
            fieldNumber: 1,
        },
    },
};
----


== Defining Types
Schemas will fulfill the needs of lisk SDK and plugin database, however, we need to define interfaces that will be used in the implementation of HelloInfoPlugin. 
So let's do that, create a new file `types.ts` in the root directory of your plugin `hello_info`.

The idea behind creating the following types remains the same, we want interfaces to interact with various types of data such as event data, counter, and height. 
Add the following interfaces to your `types.ts` file:

.hello_client/src/app/plugins/hello_info/types.ts
[source,typescript]
----
export interface Event {
    senderAddress: Buffer;
    message: string;
    height: number;
}

export interface Counter {
    counter: number;
}

export interface Height {
    height: number;
}
----

== Defining Constants
We plan to use a key-value-based off-chain database for our plugin, which needs a set of unique key values. 
Part of our unique keys will come from constants that we define in a `constants.ts` file.

Create a `constants.ts` file inside the `hello_info` folder and add the following constants to it.

.hello_client/src/app/plugins/hello_info/constants.ts
[source,typescript]
----
export const DB_KEY_ADDRESS_INFO = Buffer.from('helloInfo:address', 'utf8');
export const DB_LAST_COUNTER_INFO = Buffer.from('helloInfo:counter', 'utf8');
export const DB_LAST_HEIGHT_INFO = Buffer.from('helloInfo:height', 'utf8');
----

Now that we have defined the relevant schemas, types, and constants, our plugin is ready to have the database logic, as described in the next guide.