= Defining off-chain data structures
Muhammad Talha <muhammad.talha@lightcurve.io>

:toc: preamble
:idprefix:
:idseparator: -
// :sectnums:
:docs_sdk: lisk-sdk::
// URLs
:url_github_guides_plugin: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/hello_client/src/app/plugins/hello_info
// Project URLS
:url_architecture_config: understand-blockchain/sdk/architecture.adoc#configuration
:url_guides_module: build-blockchain/module/index.adoc
:url_guides_module_configuration: build-blockchain/module/configuration.adoc
:url_guides_module_stores: build-blockchain/module/stores.adoc
:url_guides_module_command: build-blockchain/command.adoc
:url_guides_module_endpoints: build-blockchain/module/endpoints-methods.adoc
:url_guides_module_events: build-blockchain/module/blockchain-event.adoc
:url_guides_setup: build-blockchain/create-blockchain-app.adoc
:url_guides_setup_helloapp: {url_guides_setup}#the-hello-world-application
:url_intro_plugins: understand-blockchain/sdk/plugins.adoc
:url_references_commander_commands_plugin: {docs_sdk}references/lisk-commander/

Our plugin will need to store data of events generated by the `HelloModule`. So, On this page, you will learn:

====
* [x] Defining Schemas
* [x] Defining Types
* [x] Defining Constants
====

== Defining Schemas
Create a new file called `schemas.ts` inside the `hello_info` directory. Inside the `schemas.ts`, we want to define schema of data that will be produced and consumed by our plugin. These schemas will be used by Lisk Framework for validating, encoding and decoding data. The `HelloInfoPlugin` needs to store or consume five kinds of data.


. On-chain NewHelloEvent's data.
. Off-chain NewHelloEvent's data.
. A Counter for NewHelloEvents stored off-chain.
. Height of the last block where a NewHelloEvent was emitted.


[#NewHelloEvent]
*Off-chain NewHelloEvent's data*: Next up is the schema for off-chain NewHelloEvent's data. Here we define properties such as `senderAddress`, `message` and `height` of the block. The `newHelloEventSchema` will be used for encoding, decoding and storing said data in the database.

.newHelloEventSchema
[source,typescript]
----
export const newHelloEventSchema = {
    $id: '/helloInfo/new_hello',
    type: 'object',
    required: ['senderAddress', 'message', 'height'],
    properties: {
        senderAddress: {
            dataType: 'bytes',
            fieldNumber: 1,
        },
        message: {
            dataType: 'string',
            fieldNumber: 2,
        },
        height: {
            dataType: 'uint32',
            fieldNumber: 3,
        },
    },
};
----


*A Counter for NewHelloEvents stored off-chain:* We want to store a counter of how many Hello Events have been stored in our off-chain database. A counter will also be used for key generation for our off-chain database. So, let's define the `counterSchema` in your `schemas.ts` file.

.counterSchema
[source,typescript]
----
export const counterSchema = {
    $id: '/helloInfo/counter',
    type: 'object',
    required: ['counter'],
    properties: {
        counter: {
            dataType: 'uint32',
            fieldNumber: 1,
        },
    },
};
----


*Height of the last block where a NewHelloEvent was emitted*: As the name suggests, we want to store the height of last block where our plugin found a NewHelloEvent. This will help us avoid storing redundant data in our off-chain database.

.heightSchema
[source,typescript]
----
export const heightSchema = {
    $id: '/helloInfo/height',
    type: 'object',
    required: ['height'],
    properties: {
        height: {
            dataType: 'uint32',
            fieldNumber: 1,
        },
    },
};
----

After you define all the aforementioned schemas, your `schemas.ts` file should look like this:

.Schemas for HelloInfoPlugin
[%collapsible]
====
.hello_client/src/app/plugins/hello_info/schemas.ts
[source,typescript]
----
export const configSchema = {
    $id: '#/plugins/helloInfo/config',
    type: 'object',
    properties: {
        enablePlugin: {
            type: 'boolean',
        },
    },
    required: ['enablePlugin'],
    default: {
        enablePlugin: true,
    },
};


export const chainEventSchema = {
    $id: '/helloInfo/new_hello/chainEvent',
    type: 'object',
    required: ['senderAddress', 'message'],
    properties: {
        senderAddress: {
            dataType: 'bytes',
            fieldNumber: 1,
        },
        message: {
            dataType: 'string',
            fieldNumber: 2,
        },
    },
};

export const newHelloEventSchema = {
    $id: '/helloInfo/new_hello',
    type: 'object',
    required: ['senderAddress', 'message', 'height'],
    properties: {
        senderAddress: {
            dataType: 'bytes',
            fieldNumber: 1,
        },
        message: {
            dataType: 'string',
            fieldNumber: 2,
        },
        height: {
            dataType: 'uint32',
            fieldNumber: 3,
        },
    },
};

export const counterSchema = {
    $id: '/helloInfo/counter',
    type: 'object',
    required: ['counter'],
    properties: {
        counter: {
            dataType: 'uint32',
            fieldNumber: 1,
        },
    },
};

export const heightSchema = {
    $id: '/helloInfo/height',
    type: 'object',
    required: ['height'],
    properties: {
        height: {
            dataType: 'uint32',
            fieldNumber: 1,
        },
    },
};
----
====


== Defining Types
Schemas will fullfill the needs of lisk SDK and databases, however, we need to define interfaces that we will be used in our `.ts` files for implementing our plugin. So let's do that, create a new file `types.ts` in the root directory of your plugin `hello_info`.

The idea behind creating the following types still remains the same, we want interfaces to interact with various types of data from such as configuration, event's data, counter and height. So, add the following interfaces to your types.ts file:


.hello_client/src/app/plugins/hello_info/types.ts
[source,typescript]
----
export interface Event {
    senderAddress: Buffer;
    message: string;
    height: number;
}

export interface Counter {
    counter: number;
}

export interface Height {
    height: number;
}
----


== Defining Constants
We plan to use a key-value based offchain database for our plugin, which needs a set of unique key values. Part of our unique keys will come from constants that we define in a `constants.ts` file.

So, create a `constants.ts` file inside the `hello_info` folder and add the following constants in it.


.hello_client/src/app/plugins/hello_info/constants.ts
[source,typescript]
----
export const DB_KEY_ADDRESS_INFO = Buffer.from('helloInfo:address', 'utf8');
export const DB_LAST_COUNTER_INFO = Buffer.from('helloInfo:counter', 'utf8');
export const DB_LAST_HEIGHT_INFO = Buffer.from('helloInfo:height', 'utf8');
----

Now that we have defined our schemas, types and constants, our plugin is ready to have the database logic, as described in the next guide.