{empty}[@liskhq/lisk-api-client](../README.md) ›
link:delegatesresource.md[DelegatesResource]

== Class: DelegatesResource

=== Hierarchy

* APIResource
+
↳ *DelegatesResource*

=== Index

==== Constructors

* link:delegatesresource.md#constructor[constructor]

==== Properties

* link:delegatesresource.md#apiclient[apiClient]
* link:delegatesresource.md#get[get]
* link:delegatesresource.md#getforgers[getForgers]
* link:delegatesresource.md#getforgingstatistics[getForgingStatistics]
* link:delegatesresource.md#getstandby[getStandby]
* link:delegatesresource.md#path[path]

==== Accessors

* link:delegatesresource.md#headers[headers]
* link:delegatesresource.md#resourcepath[resourcePath]

==== Methods

* link:delegatesresource.md#handleretry[handleRetry]
* link:delegatesresource.md#request[request]

=== Constructors

==== constructor

+ *new DelegatesResource*(`+apiClient+`: link:apiclient.md[APIClient]):
_link:delegatesresource.md[DelegatesResource]_

_Overrides void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/delegates.ts#L26[resources/delegates.ts:26]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+apiClient+` |link:apiclient.md[APIClient]
|===

*Returns:* _link:delegatesresource.md[DelegatesResource]_

=== Properties

==== apiClient

• *apiClient*: _link:apiclient.md[APIClient]_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L26[api_resource.ts:26]_

'''''

==== get

• *get*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/delegates.ts#L22[resources/delegates.ts:22]_

'''''

==== getForgers

• *getForgers*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/delegates.ts#L23[resources/delegates.ts:23]_

'''''

==== getForgingStatistics

• *getForgingStatistics*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/delegates.ts#L24[resources/delegates.ts:24]_

'''''

==== getStandby

• *getStandby*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/delegates.ts#L25[resources/delegates.ts:25]_

'''''

==== path

• *path*: _string_

_Overrides void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/delegates.ts#L26[resources/delegates.ts:26]_

=== Accessors

==== headers

• *get headers*(): _HashMap_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L34[api_resource.ts:34]_

*Returns:* _HashMap_

'''''

==== resourcePath

• *get resourcePath*(): _string_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L38[api_resource.ts:38]_

*Returns:* _string_

=== Methods

==== handleRetry

▸ *handleRetry*(`+error+`: Error, `+req+`: AxiosRequestConfig,
`+retryCount+`: number): _Promise‹APIResponse›_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L42[api_resource.ts:42]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+error+` |Error
|`+req+` |AxiosRequestConfig
|`+retryCount+` |number
|===

*Returns:* _Promise‹APIResponse›_

'''''

==== request

▸ *request*(`+req+`: AxiosRequestConfig, `+retry+`: boolean,
`+retryCount+`: number): _Promise‹APIResponse›_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L67[api_resource.ts:67]_

*Parameters:*

[cols=",,",options="header",]
|===
|Name |Type |Default
|`+req+` |AxiosRequestConfig |-
|`+retry+` |boolean |-
|`+retryCount+` |number |1
|===

*Returns:* _Promise‹APIResponse›_
