= Registering plugins
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc:
:url_guides_setup: guides/app-development/setup.adoc
:url_guides_setup_init: guides/app-development/setup.adoc#initializing-a-new-blockchain-application
:url_register_dashboard_plugin: guides/app-development/registration/dashboard-plugin.adoc

How to register a new plugin or module to the blockchain application.

.Prerequisites
[NOTE]
====
To follow this guide, the following criteria is assumed:

* A basic blockchain application is already initiated with Lisk Commander as explained in the previous guide xref:{url_guides_setup}[].
====

== Registering plugins

=== Enabling default plugins of the Lisk SDK

The default plugins are shipped with the Lisk SDK and can be imported directly from the `lisk-sdk` package.

If the blockchain application was xref:{url_guides_setup_init}[initialized with Lisk Commander], it is possible to enable the default plugins by setting environment variables or by setting the correct flags when starting the application.

==== Option 1: Enable plugins via command flags

[source,bash]
----
./bin/run start --enable-faucet-plugin --enable-forger-plugin --enable-http-api-plugin --enable-dashboard-plugin
----

==== Option 2: Enable plugins with environment variables

[source,bash]
----
export LISK_ENABLE_REPORT_MISBEHAVIOR_PLUGIN
export LISK_ENABLE_MONITOR_PLUGIN
./bin/run start
----

=== Adding plugins to the application

.Adding a specific plugin
****
Go to the dedicated guides to learn how to use the different official plugins for the Lisk SDK in your blockchain application.

* xref:{url_register_dashboard_plugin}[]
****


[source,typescript]
----
import { Application } from 'lisk-sdk';
import { DashboardPlugin } from "@liskhq/lisk-framework-dashboard-plugin";
import { FaucetPlugin } from "@liskhq/lisk-framework-faucet-plugin";

export const registerPlugins = (app: Application): void => {
    app.registerPlugin(DashboardPlugin);
    app.registerPlugin(FaucetPlugin);
};
----

=== Configuring plugins
