= Lisk Docs

This is the build branch for rendering the Lisk Documentation using Antora

== README

=== Prerequisites

The following software packages are required:

- make
- node.js
- antora (npm install --global @antora/cli@2.1 @antora/site-generator-default@2.1)
- gulp (npm install --global gulp-cli)

It's also required to have the `antora` and `master` directories setup as working trees to their respective branches.
This can be done like so:

```
git worktree add master master
git worktree add antora antora
```

Note: if you're making a pull request against either the master or antora branches, you might want to temporarily use different branches instead. Refer to `man git worktree` for further details

You'll notice that if you do a `git branch` now that you have 3 branches checked out.

=== Build Steps

Building at this point should be as simple as running `make`

Once this is complete, the changes will be in the master directory/branch and ready for committing and pushing

=== Build Details

It's a 2 step process where the UI bundle is built first followed by the static site which uses the UI bundle.

This can be done manually by going into the antora directory and running:
`git pull origin antora && npm ci && gulp bundle`

More details on this can be found in antora/README.adoc

And then, from the root directory, running `antora site.yml`.


