= Lisk Documentation
:hide-uri-scheme:
:idprefix:
:toc: preamble
// External URLs:
:url_antora_ui: https://gitlab.com/antora/antora-ui-default
:url_antora_ui_docs: https://docs.antora.org/antora-ui-default/
:url_antora: https://antora.org/
:url_antora_directories: https://docs.antora.org/antora/latest/standard-directories/
:url_docs: https://lisk.com/documentation
:url_docs_gitpage: https://liskhq.github.io/lisk-docs
:url_github_sdk: https://github.com/LiskHQ/lisk-sdk/tree/development/docs/antora
:url_github_core: https://github.com/LiskHQ/lisk-core/tree/development/docs/antora
:url_github_service: https://github.com/LiskHQ/lisk-service/tree/development/docs/antora
:url_github_lips: https://github.com/LiskHQ/lips

The {url_docs}[Lisk documentation^] includes explanations, guides, tutorials, and references about

* the {url_github_sdk}[Lisk SDK^],
* {url_github_core}[Lisk Core^],
* {url_github_service}[Lisk Service^],
* and the {url_github_lips}[Lisk protocol^] in general

The Lisk documentation uses {url_antora}[Antora^] as a documentation generator.

== Repository structure

The internal structure of `development` and `main` branch.

=== The `docs/` folder

The source content for the general Lisk documentation is located in the `docs/` folder.

The file structure follows the expected structure for Antora documentation, see: {url_antora_directories}[^].

All content is written in AsciiDoc.

=== The `ui/` folder

The presentation of the documentation is stored completely separate from the actual content.

The UI is based on the {url_antora_ui}[Antora default UI^] (see also {url_antora_ui_docs}[^]).

It is customized as listed in the following points below:

* Updated the CSS to improve the UX and follow the Lisk brand styleguide.
* Added additional features, such as:
** Algolia site search
** Dark theme
** Zoom for images
** Additional layout for swagger UI
** Tab-blocks
** ...

=== The `build/` folder
The `build` folder contains the following:

* ...the `site.yml` file, which is used to generate the Lisk documentation using Antora.
* ...the `searchdocs-scraper` folder, for creating the search index.
* ...the `lib` folder which stores the Asciidoc extensions that are used in the Lisk documentation.

----
.
├── lib/ <1>
├── searchdocs-scraper/ <2>
├── live-site.yml <3>
└── site.yml <4>
----

<1> The `lib/` folder contains extensions for Antora.
<2> The `searchdocs-scraper/` folder contains the file required to update the Algolia search index of the documentation.
<3> The playbook used to compile the live documentation on {url_docs}[^] with Antora.
Results are pushed to the `live` branch.
<4> The playbook used to compile the documentation at {url_docs_gitpage}[^] with Antora.
Results are pushed to the `git-page` branch.

== Contributors

https://github.com/LiskHQ/lisk-docs/graphs/contributors

== License

Copyright 2016-2023 Lisk Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.