site:
  title: Lisk documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://lisk.com/documentation
  start_page: lisk::index.adoc
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    imagesdir: ~
#    description: ~
    idprefix: ''
    idseparator: '-'
  extensions:
#  - asciidoctor-emoji
#  - asciidoctor-plantuml
#  - asciidoctor-chart
  - ./lib/tabs-block/extension.js
  - "@djencks/asciidoctor-glossary"
content:
  sources:
  - url: https://github.com/LiskHQ/lisk-docs.git
    branches: [docs-lisk,  1255-calc-min-fee, docs-service, docs-core, docs-sdk-4.0.0, docs-sdk-3.0.2,  docs-core-v2, docs-manual]
#    start_path: docs
ui:
  bundle:
#    url: https://github.com/LiskHQ/lisk-docs/raw/dev-antora/build/ui-bundle.zip
   url: ./dev-antora/build/ui-bundle.zip
   snapshot: true
output:
  dir: ./main
