= Blockchain Scalability
Chris Braithwaite <christopher.braithwaite@lightcurve.io> Mona Bärenfänger <mona@lightcurve.io>

:description: Scalability in the blockchain industry and how it is managed in the Lisk ecosystem

:toc: preamble
:idprefix:
:idseparator: -
:imagesdir: ../../assets/images
//:experimental::toc:
:page-previous: /root/intro/lisk-products.html
:page-previous-title: Lisk Products
:page-next:
:page-next-title:


=== Overview


The advent of Blockchain technology has resulted in a wide array of many positive benefits on a global scale, whereby numerous blockchain applications are found in a variety of different industry sectors worldwide.
Blockchain growth continues to march forward exponentially offering more and more innovative and limitless solutions, from revolutionizing and boosting security, to digital property rights, and many more.
However, this does not come without its challenges, as the many blockchains continue to grow and expand, coupled with the enormous growth in users, this subsequently results in scalability issues, which in turn result in transaction latency problems.
In this section, we will explore scalability and cover the solutions available to address this with a view to reducing and eliminating blockchain latency.


