= Blockchain Scalability
Chris Braithwaite <christopher.braithwaite@lightcurve.io> Mona Bärenfänger <mona@lightcurve.io>
:description: Scalability in the blockchain industry and how it is managed in the Lisk ecosystem
:toc: preamble
:idprefix:
:idseparator: -
:imagesdir: ../../assets/images
:page-previous: /root/intro/lisk-products.html
:page-previous-title: Lisk Products
:page-next:
:page-next-title:

//scalability trilemma diagram built
== Overview


The advent of Blockchain technology has resulted in a wide array of many positive benefits on a global scale, whereby numerous blockchain applications are found in a variety of different industry sectors worldwide.
Blockchain growth continues to march forward exponentially offering more and more innovative and limitless solutions, from revolutionizing and boosting security, to digital property rights, and many more.
However, this does not come without its challenges, as the many blockchains continue to grow and expand, coupled with the enormous growth in users, this subsequently results in scalability issues, which in turn result in transaction latency problems.
In this section, we will explore scalability and cover the solutions available to address this with a view to reducing and eliminating blockchain latency.


== What is blockchain scalability?

Scalability in this context can be defined as the platform or system's ability to manage and support an increasing amount or quantity of tasks, namely an increasing amount of transactions together with an increasing amount of nodes in the network.
Generally, blockchain networks suffer from low scalability.
In the blockchain world, this mostly refers to the transaction throughput, bootstrap time, latency, and even the cost of the actual transaction.
A blockchain network can be classed as scalable when it is able to adequately handle a high volume of transactions per second (TPS), usually by the adjustment of certain system characteristics such as its consensus mechanism.

== Defining blockchain scalability

As growth in blockchain networks continues to increase exponentially, this naturally results in an ever-increasing number of nodes within the blockchain networks. This in turn raises the issue of scalability.
Probably one of the best comparisons to make here to highlight the scalability issues would be to consider the number of transactions processed in the Bitcoin network, which currently runs to around 7 transactions per second. If we compare this to the well-known Visa card processing system, the number of transactions processed every second is around 17,000. To compound this further issues with its practical applications and the difficulties when an increased number of users wish to use the network occur, as this causes the transaction process to slow down, and often increases the transaction costs, whilst restricting further users from joining the network.
There are various factors that define blockchain scalability, and generally speaking these consist of networking, capacity, and throughput.

As growth in blockchain networks continues to increase exponentially, this naturally results in an ever-increasing number of nodes within the blockchain networks.
This in turn raises the issue of scalability.
Probably one of the best comparisons to make here to highlight the scalability issues would be to consider the number of transactions processed in the Bitcoin network, which currently runs to around 7 transactions per second.
If we compare this to the well-known Visa card processing system, the number of transactions processed every second is around 17,000.
To compound this further issues with its practical applications and the difficulties when an increased number of users wish to use the network occur, as this causes the transaction process to slow down, and often increases the transaction costs, whilst restricting further users from joining the network.
There are various factors that define blockchain scalability, and generally speaking these consist of networking, capacity, and throughput.
With regard to networking, every type of transaction that occurs is transmitted to all nodes residing in the network.
This can consume a vast amount of network resources coupled with increasing propagation delays.
Secondly, the capacity and cost also factor into this equation, as storing large quantities of data is a requirement.
Starting from the genesis block to the latest block and transactions consists of a large quantity of data, so it has to be taken into consideration that each network node does not possess adequate resources for the storage of such high volumes of data.



== Scalability bottlenecks