= What is blockchain?
Chris Braithwaite <christopher.braithwaite@lightcurve.io>
:description: The What is blockchain page starts the into section and provides a high-level overview and summary of what blockchain and its use cases.
:toc:

// :url_hello: build-blockchain/create-blockchain-app.adoc


At its core, a blockchain is a database shared across multiple computers.

Triggers for the database operations are called transactions The data contained in a transaction specifies the operation to be performed.

In an account-based blockchain, the validity of a new transaction is checked against a database of user accounts. An account is a portion of the database identified by the account address. This is opposed to UTXO-based blockchains (such as Bitcoin, see Wikipedia page), where there is no concept of account and the validity of a transaction is based on a database of referenced past transactions.

The cost of processing the transaction and updating the blockchain is specified in the transaction fee and paid using tokens.

Transactions are shared among nodes connected in a P2P network and are grouped together into blocks.

The validity of a block (and all transactions within it) is determined against the accounts state.

The consensus protocol specifies who has the right to forge a new block and how agreement on blocks is reached. After the block has been forged, it is added to the blockchain, and all state changes induced by the block transactions are applied.

