= Sidechain client configuration
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:page-aliases: configuration.adoc
:toc: preamble
:idprefix:
:idseparator: -
:docs-sdk: lisk-sdk::
// URLs
// Project URLs
:url_build_module_config: build-blockchain/module/configuration.adoc
:url_build_plugin: build-blockchain/create-plugin.adoc
:url_references_config: {docs-sdk}config.adoc
:url_references_config_system: {docs-sdk}config.adoc#system
:url_references_config_rpc: {docs-sdk}config.adoc#rpc
:url_references_config_network: {docs-sdk}config.adoc#network
:url_references_config_transactionpool: {docs-sdk}config.adoc#transactionpool
:url_references_config_network: {docs-sdk}config.adoc#network
:url_references_config_genesis: {docs-sdk}config.adoc#genesis
:url_references_config_generator: {docs-sdk}config.adoc#generator
:url_references_config_modules: {docs-sdk}config.adoc#modules
:url_references_config_plugins: {docs-sdk}config.adoc#plugins
:url_references_cli_start: {docs-sdk}application-cli.adoc#start

How to configure a sidechain client.

== Node config reference

To get a complete overview of all configuration options for the Lisk SDK, please refer to the xref:{url_references_config}[].

=== Configurations for the sidechain developer

These configuration are set by the sidechain developer, and *the node operator should not change them.*

* xref:{url_references_config_genesis}[`genesis`]
* xref:{url_references_config_modules}[`modules`]

=== Configs for the node operator

The following configurations can be changed by the node operator:

* xref:{url_references_config_system}[`system`]
* xref:{url_references_config_rpc}[`rpc`]
* xref:{url_references_config_network}[`network`]
* xref:{url_references_config_transactionpool}[`transactionpPool`]
* xref:{url_references_config_generator}[`generator`]
* xref:{url_references_config_plugins}[`plugins`]

== Default configuration

The default node configuration is used, if no other config is specified when starting the node.

=== After initialization

When a new client is initialized with `lisk init`, a default config template for the client is generated under `config/default/`.

IMPORTANT: This config is only a template, which is used to generate a default configuration on the initial start of the node.
After the node was started, it will use the config in the <<node-data,node data folder>>.

.Path of the node config template
 <SIDECHAIN_CLIENT>/config/default/config.json

=== After the first start

When the app was started at least once, the config is copied from the template to the folder for the node data, which is located under `~/.lisk/<CLIENT_NAME>/`.

The sidechain node will always use the config in the *node data folder* by default, if no custom config is specified.

[#node-data]
.Node config path
 ~/.lisk/<SIDECHAIN_CLIENT>/config/config.json

== How to use a custom configuration

A best practise to create a custom configuration for a sidechain client, is to copy an existing `config.json` and adjust it to suit your requirements.

.In the root directory of the sidechain client
[source,bash]
----
cp config/default/config.json config/custom_config.json
----

To use the custom config in the sidechain client, add the `--config` flag to the xref:{url_references_cli_start}[start command] and specify the path to the configuration file.

The flag `--overwrite-config` overwrites the existing config, in case a different config was used before.

[source,bash]
----
bin/run start --config config/custom_config.json --overwrite-config
----

== Example: Configuration for the Hello World sidechain

For the Hello World sidechain, create a `custm_config.json`, like explained in the previous stepp <<how-to-use-a-custom-configuration>>.

Then, adjust the RPC configuration as follows:

.config/custom_config.json
[source,js]
----
{

  // ...

    "rpc": {
		"modes": ["ipc", "http"],
		"port": 7887,
		"host": "127.0.0.1"
	},

   // ...

}
----

This will start the node with enabled API for IPC and HTTP.
That allows to send transactions and other RPC API requests to the node with tools like Postman or cURL, which use the HTTP protocol.

Restart the app to apply the new configuration.

The Hello World custom config is adjusted further in the following guides:

* xref:{url_build_module_config}[]
* xref:{url_build_plugin}[]
