= Blockchain client configuration
Mona Bärenfänger <mona@lightcurve.io> Muhammad Talha <muhammad.talha@lightcurve.io>
// Settings
:page-aliases: configuration.adoc
:toc: preamble
:idprefix:
:idseparator: -
:docs-sdk: lisk-sdk::
// URLs
// Project URLs
:url_build_module_config: build-blockchain/module/configuration.adoc
:url_build_plugin: build-blockchain/plugin/configuring-plugin.adoc
:url_references_config: {docs-sdk}config.adoc
:url_references_config_system: {docs-sdk}config.adoc#system
:url_references_config_rpc: {docs-sdk}config.adoc#rpc
:url_references_config_network: {docs-sdk}config.adoc#network
:url_references_config_transactionpool: {docs-sdk}config.adoc#transactionpool
:url_references_config_network: {docs-sdk}config.adoc#network
:url_references_config_genesis: {docs-sdk}config.adoc#genesis
:url_references_config_generator: {docs-sdk}config.adoc#generator
:url_references_config_modules: {docs-sdk}config.adoc#modules
:url_references_config_plugins: {docs-sdk}config.adoc#plugins
:url_references_cli_start: {docs-sdk}client-cli.adoc#start

How to configure a blockchain client.

====
On this page, you'll learn:

* [x] Which config options can be changed by node operators?
* [x] Which config options can only be changed by blockchain developers?
* [x] What is the default configuration of a client, and where to find it?
* [x] How to create and use a custom configuration for the client?
====

== Node config reference

To get a complete overview of all configuration options for the Lisk SDK, please refer to the xref:{url_references_config}[].

=== Configurations for the blockchain developer

A *blockchain developer* sets the following configurations. *A node operator should not change them.*

* xref:{url_references_config_genesis}[genesis]
* xref:{url_references_config_modules}[modules]

=== Configurations for the node operator

The following configurations can be changed by the node operator:

* xref:{url_references_config_system}[system]
* xref:{url_references_config_rpc}[rpc]
* xref:{url_references_config_network}[network]
* xref:{url_references_config_transactionpool}[transactionPool]
* xref:{url_references_config_generator}[generator]
* xref:{url_references_config_plugins}[plugins]

== Default configuration

The default node configuration is used, if no other config is specified when starting the node.

=== After initialization

When a new client is initialized with `lisk init`, a default config template for the client is generated under `config/default/`.

IMPORTANT: This config is only a template, which is used to generate a default configuration on the initial start of the node.
After the node is started, it will use the config in the <<client-data,client data folder>>.

.Path of the node config template
 <BLOCKCHAIN_CLIENT>/config/default/config.json

=== After the first start

When the blockchain client is started for the first time, the config is copied from the template to the folder for the node data, which is located under `~/.lisk/<CLIENT_NAME>/`.

The blockchain client will always use the config in the *client data folder* by default, if no custom config is specified.

[#client-data]
.Client config path
 ~/.lisk/<CLIENT_NAME>/config/config.json

== How to use a custom configuration

A best practice to create a custom configuration for a blockchain client is to copy an existing `config.json`, and then adjust it to suit your requirements.

.In the root directory of the blockchain client
[source,bash]
----
cp config/default/config.json config/custom_config.json
----

To use the custom config in the blockchain client, add the `--config` flag to the xref:{url_references_cli_start}[start command] and specify the path to the configuration file.

The flag `--overwrite-config` overwrites the existing config, in case a different config was previously used before.

[source,bash]
----
./bin/run start --config config/custom_config.json --overwrite-config
----

== Example: Configuration for the Hello World client

For the Hello World client, create a `custom_config.json`, as explained in the previous step <<how-to-use-a-custom-configuration>>.

Then, adjust the RPC configuration as follows:

.config/custom_config.json
[source,js]
----
{
	// [...]

	"rpc": {
		"modes": [
			"ipc",
			"ws",
			"http"
		],
		"port": 7887,
		"host": "127.0.0.1",
		"allowedMethods": [
			"*"
		]
	},

	// [...]
}
----

This will start the node with the enabled API for IPC, WS, and HTTP.

Such configuration allows sending transactions and other RPC API requests to the node with tools such as Postman or cURL, which use the HTTP protocol.

Whereas the IPC and WS modes can entertain RPC requests made to the node.

The `allowedMethods:[*]` configuration will allow the node to access all the endpoints offered by various Lisk modules.

After updating the `custom_config.json` file, restart the client with the `--overwrite-config` flag to apply the new configuration.

.hello_client/
[source,bash]
----
./bin/run start --config config/custom_config.json --overwrite-config
----

The configuration for the Hello World client is adjusted further in the following guides:

* xref:{url_build_module_config}[]
* xref:{url_build_plugin}[]
