= Creating a new blockchain application
Mona Bärenfänger <mona@lightcurve.io> Muhammad Talha <muhammad.talha@lightcurve.io>
// Settings
:toc: preamble
:idprefix:
:idseparator: -
:experimental:
:docs_sdk: lisk-sdk::
// URLs
:url_github_guides_bootstrap: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello
:url_homebrew: https://brew.sh/
:url_nvm: https://github.com/nvm-sh/nvm
// Project URLs
:url_modules_registration: understand-blockchain/sdk/modules-commands.adoc#adding-a-module-to-the-application
:url_guide_config: build-blockchain/configure-app.adoc
:url_guide_module: build-blockchain/create-module.adoc
:url_guide_asset: build-blockchain/create-asset.adoc
:url_guide_plugin: build-blockchain/create-plugin.adoc
:url_references_cli: {docs_sdk}application-cli.adoc#help
:url_references_cli_start: {docs_sdk}application-cli.adoc#start
:url_lisk_commander: {docs_sdk}references/lisk-commander/index.adoc 
:url_lisk_default_modules: {docs_sdk}modules/index.adoc


On this page, you will learn how to create a new blockchain application with the Lisk SDK.
To get started with the development of a blockchain application simply and efficiently, it is *recommended* to follow the guide <<bootstrapping-a-new-blockchain-application-with-lisk-commander>>.

== Bootstrapping a new blockchain application with Lisk Commander

xref:{url_lisk_commander}[Lisk Commander] offers various commands related to <<initializing-a-new-blockchain-application>> which can be used to conveniently get started with developing a blockchain application.

.Sample code
[NOTE]
====
View the complete sample code of this guide on GitHub in the {url_github_guides_bootstrap}[Lisk SDK examples repository^].
====

=== Supported Operating Systems

The Lisk SDK runs on both Ubuntu and macOS operating systems and supports the following versions, as described below:

[tabs]

=====
Ubuntu::
+
--
* 18.04 (LTS)
* 20.04 (LTS)
* 22.04 (LTS)
--
macOS::
+
--
* 10.13 (High Sierra)
* 10.14 (Mojave)
* 10.15 (Catalina)
* 11.04 (Big Sur)
* 12.6.1 (Monterey)
* 13.0 (Ventura)
--
=====

NOTE: Please note that the SDK does not come with any official support for Windows.

=== Dependencies

[options="header",]
|===
|Dependencies |Version 
|Git | v2 (latest) 
|Node.js | v16.18.0 (latest LTS) 
|Lisk Commander | v6.0.0 (latest) 
|Homebrew (macOS) | v3.6.7 (latest)
|automake | 1.16.5 (latest)
|autoconf | 2.71 (latest)
|curl (Ubuntu)| 7.68.0 (latest)
|build-essential (Ubuntu) | 12.8 (latest)
|python2 | 2.7 (latest)
|===

==== Node.js

If you are using NVM ({url_nvm}[Node.js Version Manager]), install the correct version as shown below:

[source,bash]
----
nvm install v16.18.0
----
// NOTE: The correct version for NPM(6) is installed automatically with version 12 of Node.js.

==== Lisk Commander

It is recommended to install Lisk Commander globally with NPM (Node Packet Manager), to facilitate the convenient usage of the Lisk Commander CLI.

[source,bash]
----
npm install --global lisk-commander
----

To check the successful installation of Lisk Commander, run the following command:

[source,bash]
----
$ lisk --version
lisk-commander/6.0.0 darwin-arm64 node-v16.18.0
----

==== Toolchain dependencies

Once Lisk Commander is installed, install the following compiler dependencies as well.

[tabs]
====
Ubuntu::
+
--
[source,bash]
----
sudo apt update
sudo apt install -y libtool automake autoconf curl build-essential python2-minimal
----
--
macOS::
+
--
Ensure that {url_homebrew}[Homebrew] is installed.

[source,bash]
----
brew install autoconf automake libtool python2
----
--
====

=== Initializing a new blockchain application

In this example, we want to create a new blockchain application with the name `hello`.
Our blockchain application is divided into two tiers such as a frontend and a blockchain application. 

Create a dedicated folder `hello/`, which will contain the files for the entire application.

[source,bash]
----
mkdir hello
cd hello
----

Once you're in the dedicated `hello` folder, create another folder named `hello_app` which will house the logic for our blockchain application.

[source,bash]
----
mkdir hello_app
cd hello_app
----

Inside the `hello_app`, execute the `init` command of Lisk Commander as shown below:

[source,bash]
----
lisk init
----

NOTE: The `init` command can be executed anywhere on the disk to bootstrap a blockchain application, however, to accommodate both *frontend* and the *blockchain application*, we have to create the aforementioned folders.

As a result of executing the `init` command, you will be asked for the *Application name*, *ChainID*, *Application description*, *Author*, and *License*.

----
Using template "lisk-ts"
Initializing git repository
Updating .liskrc.json file
Creating project structure
? Application name hello_app
? Chain ID in hex representation. ChainID must be 4 bytes (8 characters) 12345678
? Application description A simple blockchain application that saves hello messages in user accounts.
? Author XYZ
? License ISC
----

Next, all the required files are created by Lisk Commander.

=== Using the application CLI globally

To use the application commands globally, create an alias in the `.bashrc` or `.zshrc` file depending on the operating system that you are using.


[tabs]
====
bashrc::
+
--
.~/.bashrc/
[source,bash]
----
alias hello_app="$HOME/hello_app/bin/run"
----
Add the path to where your `hello_app` is located.

After updating the `.bashrc` file, make it directly available in the terminal by executing the following:

[source,bash]
----
. ~/.bashrc
----
--
zshrc::
+
--
.~/.zshrc/
[source,bash]
----
alias hello_app="$HOME/hello_app/bin/run" 
----
Add the path to where your `hello_app` is located.

After updating the `.zshrc` file, make it directly available in the terminal by executing the following:

[source,bash]
----
. ~/.zshrc
----
--
====


Now it is possible to conveniently run these application CLI commands from anywhere by referring to the alias.

[source,bash]
----
hello_app --help
----

The above command will display the general xref:{url_references_cli}[CLI command reference]:

.Available commands
----
Lisk-SDK Application

VERSION
  hello_app/0.1.0 darwin-arm64 node-v16.18.0

USAGE
  $ hello_app [COMMAND]

TOPICS
  block          Commands relating to hello_app blocks.
  blockchain     Commands relating to hello_app blockchain data.
  config         Commands relating to hello_app node configuration.
  endpoint       Commands relating to hello_app endpoint.
  generator      Commands relating to hello_app block generator.
  genesis-block  Creates a genesis block file.
  keys           Commands relating to hello_app key generation.
  node           Commands relating to hello_app node.
  passphrase     Commands relating to hello_app passphrases.
  transaction    Commands relating to hello_app transactions.

COMMANDS
  autocomplete  Displays autocomplete installation instructions
  console       Lisk interactive REPL session to run commands.
  hash-onion    Creates hash onions to be used by the forger.
  help          Displays help for hello_app.
  start         Starts Blockchain Node.
  version
----

=== File & folder structure

The blockchain application will have the following file structure after the first initialization:

----
.
├── bin/ <1>
│   ├── run
│   └── run.cmd
├── config/ <2>
│   └── default/
│   │   ├── config.json
│   │   ├── dev-validators.json
│   │   ├── genesis_assets.json
│   │   ├── genesis_block.blob
│   │   └── passphrase.json
├── src/
│   ├── app/ <3>
│   │   ├── app.ts <4>
│   │   ├── index.ts
│   │   ├── modules/ <5>
│   │   ├── modules.ts <6>
│   │   ├── plugins/ <7>
│   │   └── plugins.ts <8>
│   └── commands/ <9>
├── test/ <10>
├── jest.config.js
├── package-lock.json
├── package.json
├── readme.md
└── tsconfig.json
----

<1> `bin/`: Contains the script to run the CLI of the application.
<2> `config/`: Contains the configuration, dev-validators, genesis assets, genesis block, and passphrase files that are used by the application.
<3> `app/`: Contains the files of the blockchain application.
<4> `app.ts`: Creates the `Application` instance.
<5> `modules/`: Contains modules of the application.
This folder is empty after the first initialization with the `lisk init`.
The command `lisk generate:module` creates a new module in this folder.
<6> `modules.ts` Registers the modules with the application.
<7> `plugins/`: Contains plugins of the application.
This folder is empty after the first initialization with `lisk init`.
The command `lisk generate:plugin` creates a new plugin in this folder.
<8> `plugins.ts` Registers the plugins with the application.
<9> `commands/`: Contains the logic for the CLI commands of the application.
The files for the different commands can be adjusted and extended as desired, for example, to include new flags and commands.
<10> `test/`: Contains the test files for the unit, functional, and integration tests.

These files create a ready-to-start blockchain application configured for a local devnet, which uses only the default modules of the Lisk SDK.

TIP: Lisk provides a range of default modules out of the box. These modules are created automatically whenever a blockchain application is bootstrapped via Lisk Commander. For more information, see the xref:{url_lisk_default_modules}[].

=== Starting the application
The application is created in the file `app.ts`:

.src/app/app.ts
[source,typescript]
----
import { Application, PartialApplicationConfig } from 'lisk-sdk';
import { registerModules } from './modules';
import { registerPlugins } from './plugins';

export const getApplication = (config: PartialApplicationConfig): Application => {
	const { app } = Application.defaultApplication(config); //Creates a blockchain application with the default modules.
  
  // Will register additional modules to the application. 
  // Currently, no additional modules are available for the application.
  // To add new modules update the `modules.ts` file.
	registerModules(app);

  // Will register additional plugins to the application. 
  // Currently, no plugins are available for the application.
  // To add new plugins update the `plugins.ts` file.
	registerPlugins(app);

	return app;
};

----

In most cases, the <<default-modules,default modules>> don't need to be changed, as they provide the basic functionality that most sidechain clients need.
But in case you want to replace the default modules with other modules, you can also run the application without the default modules by replacing 

[source,typescript]
----
const { app } = Application.defaultApplication(config);
----
with

[source,typescript]
----
const app = new Application(config);
----

Please be aware that if you create the app with `const app = new Application(config);`, then you need to register all modules manually in the `modules.ts` file.

This way it is also possible to include some, but not all of the default modules in the client application.

To verify the successful bootstrap of the blockchain application, start it with the following command:

[source,bash]
----
hello_app start
----

The `start` command offers various options, allowing further configuration of the application.
For example, it is possible to define ports or to enable plugins that will be used by the application.
For a complete list of all available start options, visit the relevant xref:{url_references_cli_start}[application CLI reference].

Executing the `start` command should kick-off the blockchain application, which is currently running with a local single-node development network.

Observe the displayed log messages in the console.
If no errors are thrown, the application will start to add new logs every 10 seconds after the initial startup.

Once it is verified that the application is functioning correctly, stop the node again with kbd:[Ctrl] + kbd:[C].

Once the application starts successfully for the first time, the corresponding application data can be found under the path `~/.lisk/hello_app/`

.~/.lisk/hello_app/
----
.
├── config
│   └── default
│   │   ├── config.json <1>
│   │   ├── dev-validators.json <2>
│   │   ├── genesis_assets.json <3>
│   │   ├── genesis_block.blob <4>
│   │   └── passphrase.json <5>
├── data  <6>
│   ├── blockchain.db
│   ├── generator.db
│   ├── module.db
│   ├── node.db
│   └── state.db
├── logs  <7>
├── plugins <8>
└── tmp <9>
----


<1> `config.json` is the configuration file of the blockchain application.
<2> `dev-validators.json` contains the details of all the validators that generate a block.
<3> `genesis_assets.json` contains all the accounts and asset details for the blockchain.
<4> `genesis_block.blob` is the genesis block of the blockchain application.
<5> `passpharase.json` contains the passphrase used in various blockchain-related operations.
<6> `data` contains the on-chain and off-chain data of the blockchain, data is stored in key-value stores.
<7> `logs` contain the file logs of the application and its plugins.
<8> `plugins` contain all the off-chain data relating to the plugins of the application, data is stored in key-value stores.
<9> `tmp` contains temporary application data.

==== How to reset the database of an application

Once the application starts for the first time, it saves the application-specific data under the path `~/.lisk/hello_app/`.

To reset the database of the application, simply delete the folder with the application data:

[source,bash]
----
rm -r ~/.lisk/hello_app/data/
----

NOTE: Once removed, the *`hello_app/data`* folder is recreated automatically after the blockchain application starts again.

=== Next steps

By installing Lisk Commander and running `lisk init`, a working blockchain application now exists with the default configurations for running in a local devnet.

To extend the application further, you need to register additional modules and/or plugins to the application.

For the next step, proceed with the guide xref:{url_guide_module}[].





//*****The following is not relevant anymore.*****


// == Manual Setup (alternative without Lisk Commander)

// How to create a new blockchain application manually without using the Lisk Commander.

// === Dependencies

// * Node.js v16.15.0

// If you are using NVM, install the latest version as shown below:

// [source,bash]
// ----
// nvm install v16.15.0
// ----

// === Project setup

// Create a new folder for the blockchain application and navigate into it.

// [source,bash]
// ----
// mkdir my_blockchain_app
// cd my_blockchain_app
// ----

// Create a `package.json` file.

// [source,bash]
// ----
// npm init --yes
// ----

// Install the `lisk-sdk` package.

// [source,bash]
// ----
// npm i lisk-sdk
// ----

// === Creating a blockchain application

// Create a new file `index.js`.
// We want to use this file to store the code that will start the blockchain application by using the Lisk SDK.

// In `index.js`, import the `Application`, `genesisBlockDevnet`, and `configDevnet` from the the `lisk-sdk` package.

// [source,js]
// ----
// const { Application, genesisBlockDevnet, configDevnet } = require('lisk-sdk');
// ----

// Now use the objects to create a blockchain application:

// [source,js]
// ----
// const app = Application.defaultApplication(genesisBlockDevnet, configDevnet);
// ----

// This will create a new blockchain application that uses `genesisBlockDevnet` as the genesis block for the blockchain, and `configDevnet` to configure the application with common default options to run a node in a development network.

// [NOTE]
// ====
// The `lisk-sdk` package contains the sample objects `genesisBlockDevnet` and `configDevnet` which enable the user to quickly spin up a development blockchain network.
// The `genesisBlockDevnet` includes a set of preconfigured genesis delegates, that will immediately start forging on a single node to stabilize the network.
// The `configDevnet` includes the configuration for the Devnet.

// Both objects can be customized before passing them to the `Application` instance if desired.

// More information can be found in the guide xref:{url_guide_config}[].
// ====

// Use `app.run()` to start the application:

// [source,js]
// ----
// app
// 	.run()
// 	.then(() => app.logger.info('App started...'))
// 	.catch(error => {
// 		console.error('Faced error in application', error);
// 		process.exit(1);
// 	});
// ----

// After adding all of the above contents, save the file.
// Now it is possible to start a blockchain application with a default configuration, that will connect to a local devnet.

// === Starting the application

// Start the application as shown below:

// [source,bash]
// ----
// node index.js
// ----

// To verify the application start, check the log messages in the terminal.
// If the start was successful, the application will enable forging for all genesis delegates and will start to add new blocks to the blockchain every 10 seconds.

// [NOTE]
// ====
// After completing these steps, the default blockchain application of the Lisk SDK will now be running.

// It is now possible to customize your application by registering new modules and plugins, and also adjusting the genesis block and config to suit your specific use case.
// ====
