= How to create a new genesis block
Mona Bärenfänger <mona@lightcurve.io> Muhammad Talha <muhammad.talha@lightcurve.io>
// Settings
:toc:
:idprefix:
:idseparator: -
:docs_sdk: lisk-sdk::
// Project URLs
:url_default_modules: understand-blockchain/index.adoc#default-modules
:url_genesis_block: understand-blockchain/blocks-txs.adoc#genesis-block-execution
:url_guides_setup: build-blockchain/create-blockchain-app.adoc
:url_guides_module: build-blockchain/module/index.adoc
:url_modules_dpos: {docs_sdk}modules/dpos-module.adoc
:url_modules_token: {docs_sdk}modules/token-module.adoc
:url_references_cli_genesis: {docs_sdk}application-cli.adoc#genesis-blockcreate
:url_guides_module_skeleton: build-blockchain/module/index.adoc#module-skeleton

How to generate a genesis block for a sidechain client.

.Prerequisites
[NOTE]
====
To use this guide, ensure the the following criteria below has been fulfilled:

* a basic blockchain application is already initiated, as explained in the guide xref:{url_guides_setup}[].
* a custom module `HelloModule` is created, as explained in the previous guide xref:{url_guides_module}[].
====

TIP: The recommended and most convenient method to generate a new genesis block is <<using-the-cli-to-generate-a-new-genesis-block>>.

Each blockchain application needs a xref:{url_genesis_block}[genesis block], which is the very first block of the blockchain.

During the init process of a sidechain client, lisk-sdk bootstraps the first genesis block required for each sidechain and the relevant assets in the `config/default` directory of each client.

.Default genesis block and configuration files
----
├── bin/
├── config/
│    └── default/
│         ├── config.json <1>
│         ├── dev-validators.json <2>
│         ├── genesis_assets.json <3>
│         ├── genesis_block.blob <4>
│         └── passphrase.json <5>
├── src/
└── test/
----

<1> The default configuration of the sidechain client exist in the `config.json` file.
<2> `dev-validators.json`: Contains the plain & encrypted keys, addresses, and other properties of 102 validators.
<3> `genesis_assets.json`: Contains details about the initial state of a sidechain such as account details for `token` and `pos` modules. Also contains list of validators, etc.
<4> `genesis_block.blob`: A blob file of the genesis block.
<5> `passphrase.json`: Contains the passphrase used in various sidechain client operations.


== Why create a new genesis block?
For every new sidechain a unique genesis block is required. As mentioned earlier, A default genesis block becomes available right after the client's `init` process. However, whilst running a public network, you may want to assign different tokens to specific addresses of your choice.

Recreating genesis block based on the needs of modules is also relevant here, for example, setting up the initial constraints required for a staking module, etc.

// different tokens allocated to certain addresses of your choice as well as whatever you want to fill up for other modules. For example to set initial validators in PoS. The users will use it to fill up the initial state of their custom module

// If a module includes an account schema, it is necessary to update the genesis block after registering the module with the application, to update the accounts in the genesis block with the new properties.

NOTE: If a module wants to process genesis block asset, the module need to implement `initGenesisState` or `finalizeGenesisState` hook available in each xref:{url_guides_module_skeleton} [Module Class]

// If a new module that includes an account schema is then registered with the application, it will fail and an error similar to this example shown below will be displayed:

// ----
// $ ./bin/run start
// Starting Lisk hello_app at /Users/xyz/.lisk/hello_app.
// 12:31:44 INFO lisk-framework: Starting the app - hello_app (module=lisk:app)
// 12:31:44 INFO lisk-framework: If you experience any type of error, please open an issue on Lisk GitHub: https://github.com/LiskHQ/lisk-sdk/issues (module=lisk:app)
// 12:31:44 INFO lisk-framework: Contribution guidelines can be found at Lisk-sdk: https://github.com/LiskHQ/lisk-sdk/blob/development/docs/CONTRIBUTING.md (module=lisk:app)
// 12:31:44 INFO lisk-framework: Booting the application with Lisk Framework(0.1.0) (module=lisk:app)
// 12:31:44 INFO lisk-framework: Initializing controller (module=lisk:app)
// 12:31:44 INFO lisk-framework: Loading controller (module=lisk:app)
// 12:31:44 INFO lisk-framework: Event * was subscribed but not registered to the bus yet. (module=lisk:app)
//     TypeError: Cannot read property 'helloMessage' of undefined
// 12:31:45 INFO lisk-framework: Application shutdown started (module=lisk:app)
// {
//  "errorCode": 2,
//  "message": "process.exit"
// }
// ----

// To fix this error, it is required to update the genesis block of the application to include the newly created account schema.

== Using the CLI to generate a new genesis block

The genesis block can be updated with the application CLI.
By executing the following command in the root directory of the sidechain client, you can create a new genesis-block.

[source,bash]
----
./bin/run genesis-block:create --output config/default --assets-file ./config/default/genesis_assets.json
----
As a result, the new genesis block files will be created in the directory mentioned with the `--output` flag.

[source,bash]
----
2022-12-02T12:59:33.104Z INFO XYZ application 30245 Registered and initialized auth module
2022-12-02T12:59:33.105Z INFO XYZ application 30245 Registered auth module has command registerMultisignature
2022-12-02T12:59:33.106Z INFO XYZ application 30245 Registered and initialized validators module
2022-12-02T12:59:33.107Z INFO XYZ application 30245 Registered and initialized token module
2022-12-02T12:59:33.107Z INFO XYZ application 30245 Registered token module has command transfer
2022-12-02T12:59:33.107Z INFO XYZ application 30245 Registered token module has command crossChaintransfer
2022-12-02T12:59:33.108Z INFO XYZ application 30245 Registered and initialized fee module
2022-12-02T12:59:33.110Z INFO XYZ application 30245 Registered and initialized reward module
2022-12-02T12:59:33.111Z INFO XYZ application 30245 Registered and initialized random module
2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered and initialized dpos module
2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered dpos module has command registerDelegate
2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered dpos module has command reportDelegateMisbehavior
2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered dpos module has command unlock
2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered dpos module has command updateGeneratorKey
2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered dpos module has command voteDelegate
2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered and initialized interoperability module
2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered interoperability module has command mainchainRegistration
Genesis block files saved at: /Users/xyz/lisk/hello_app/config/default
----


NOTE: For more information about the `genesis-block:create` command, check the xref:{url_references_cli_genesis}[CLI command reference].

// Once the above command is executed, wait until the new genesis block is generated.

//  Creating genesis block [===========         ] 55% 44.6s

// When asked to overwrite the existing genesis block, reply with `yes`.

//  ? A genesis_block file already exists at the given location. Do you want to overwrite it? Yes

After the genesis block creation is complete, the `passphares.json` and `genesis_block.blob` re-generate under `config/default/`.



// * `genesis-block.blob`: The new genesis block.
// * `forging_info.json`: The prepared information about the genesis delegates for the config.
// * `password.json`: The default password to decrypt the passphrases of the genesis delegates.
// * `accounts.json`: The passphrases of each genesis delegate as plain text.
// Store this file somewhere secure and safe.

// The `config.json` is required to be updated as well, with the forging information of the new genesis delegates:

// Assuming no custom config is used, the following commands can be used to update the configuration (please update `<YOUR_APP>` to the corresponding application name).

//  tmp=$(mktemp)
//  jq '.forging.delegates = input' config/default/config.json config/default/forging_info.json > "$tmp" && mv "$tmp" config/default/config.json
//  jq '.forging += input' config/default/config.json config/default/password.json > "$tmp" && mv "$tmp" config/default/config.json

// Remove the old application data:

//  rm -r ~/.lisk/<YOUR_APP>

// Now start the node again:

//  ./bin/run start

// IMPORTANT: Ensure the file `accounts.json` is securely stored somewhere safe, as it contains the passphrases of all the genesis delegates.

// .Example config with forging enabled for the genesis delegates
// [source,js]
// ----
// {
//   // ...
//   "forging": {
//     "force": true,
//     "waitThreshold": 2,
//     "delegates": [
//         {
//             "encryptedPassphrase": "iterations=1000000&cipherText=e340e06389f55bacb4043a60b9135aa905c3fd543fcab7e9f309577abf5631bec801626c67e87b47b6e9b674a65a1d15ec5176ace21fb5c0f0f1c1f1950b38abe5b06c8fc54fd511c0109f83dc&iv=37abcda2bf1a254563f49e36&salt=1a3b09594d04096d250e74850d3c7508&tag=a836539af32622c10536dacecd12320d&version=1",
//             "hashOnion": {
//                 "count": 100000,
//                 "distance": 1000,
//                 "hashes": [
//                     "34ecc432170c0812e7ca69d73485ca57",
//                     "1bf9423f594619f7d14e6f742c0631a1",
//                     "4732e2bc540f8ab1e51e8a5d7b5b8f7e",
//                     // ...
//                     "fa51b75c7920894019b43378af621e2d",
//                     "bd4ea06be86fb6d850023be7ad1d9558",
//                     "da23c5a34d19bbd57ebb159da170dfb5"
//                 ]
//             },
//             "address": "8baec1286a12488825f3b6a8c84a7a72bf6591d9"
//         },
//         // ....
//         {
//             "encryptedPassphrase": "iterations=1000000&cipherText=5c53db41ec94b46049ca5a5b8312e6b38c7bbad775153a8091bafade3f78ac855b55d5d33318e13f22ec961510061c8a07726aeb4d2d2b30fbcc6ddfabc82dd6f233891a06ae54b2&iv=8c0419422b6e81c32c10ac6a&salt=1f2308d0d12480d0c788a4c60a8f272d&tag=23cf9840cb985550a96b463f878de99d&version=1",
//             "hashOnion": {
//                 "count": 100000,
//                 "distance": 1000,
//                 "hashes": [
//                     "34ecc432170c0812e7ca69d73485ca57",
//                     "1bf9423f594619f7d14e6f742c0631a1",
//                     "4732e2bc540f8ab1e51e8a5d7b5b8f7e",
//                     // ...
//                     "bd4ea06be86fb6d850023be7ad1d9558",
//                     "da23c5a34d19bbd57ebb159da170dfb5"
//                 ]
//             },
//             "address": "68d6b039567ebbfc714176d87cdd6906cf526cc7"
//         }
//     ],
//     "defaultPassword": "state dawn marriage honey cinnamon sadness crumble someone file caution sell oxygen"
//     },
// 	// ...
// }
// ----

