= How to register a sidechain
Chris Braithwaite <christopher.braithwaite@lightcurve.io> Mona Bärenfänger <mona@lightcurve.io>
:description: How to register a sidechain to the mainchain and vice versa.
// Settings
:toc: preamble
:idprefix:
:idseparator: -
:docs_sdk: v6@lisk-sdk::
// URLs
:url_lisk_wallet: https://lisk.com/wallet
:url_bls_key: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0038.md#public-key-registration-and-proof-of-possession
:url_lip56: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0056.md
:url_update_cross_chain_lip53: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0053.md#outboxrootwitness
// Project URLs
:url_understand_interop_chainid: understand-blockchain/interoperability/index.adoc#chain-identifiers
:url_ccm: understand-blockchain/interoperability/communication.adoc#sending-cross-chain-transactions-to-generate-ccms
:url_ccu: understand-blockchain/interoperability/communication.adoc#creating-and-posting-ccus
:url_sidechain_reg_recovery: understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
:url_sidechain_chain_store: {url_sidechain_reg_recovery}#chain-substore
:url_sidechain_reg_command: {url_sidechain_reg_recovery}#register-sidechain-command
:url_mainchain_reg: {url_sidechain_reg_recovery}#register-mainchain-command
// Footnotes
:fn_lip53: footnote:witness[Due to the increasing size of the {url_update_cross_chain_lip53}[outboxRootWitness^] property of the command.]

====
On this page, you'll learn how to:

* [x] Register a sidechain on the mainchain
* [x] Register the mainchain on a sidechain
====

== Registration overview

To complete the sidechain registration process, perform the following steps:

. <<how-to-register-a-sidechain-on-the-mainchain,Sidechain registration on the mainchain>>
. <<how-to-register-the-mainchain-on-the-sidechain,Mainchain registration on the sidechain>>

NOTE: Please read xref:{url_sidechain_reg_recovery}[] to get more information about the lifecycle of a sidechain.

:sectnums:
== How to register a sidechain on the mainchain

A sidechain is registered on the mainchain by posting a xref:{url_sidechain_reg_command}[Register Sidechain transaction].

A Register Sidechain transaction *can be sent by any user account* in the Lisk Mainchain that has adequate funds to pay the required <<sidechain-registration-fee,fee>>.

NOTE: The Lisk Core node CLI is used in this example to post the transaction.
Alternatively, users can use the {url_lisk_wallet}[Lisk Wallet^], where the transaction can be created conveniently as well.

To create a *Register Sidechain* transaction, the following information is required:

. <<chainid>>
. <<name>>
. <<sidechaincertificatethreshold>>
. <<sidechainvalidators>>

=== Sidechain registration fee
When the "Register Sidechain" command is processed, it creates a sidechain account in the mainchain state which is associated with a unique chain identifier and a name.
Hence, every new sidechain occupies a certain namespace within the ecosystem.
Additionally, every newly registered sidechain can increase the size of every cross-chain update command posted on the mainchain.

For these two reasons, the minimum fee for this command has an added constant similar to the extra fee in a Register Validator transaction.

NOTE: The extra registration fee for a sidechain registration is *10 LSK* tokens.

=== Prepare the required parameters

==== chainID
The xref:{url_understand_interop_chainid}[chainID] of the sidechain.
Has to be *unique* within the Lisk ecosystem.
If the given value is already taken by another sidechain, the sidechain registration command fails.
In this case, the sidechain has to change the chain ID with a hardfork, and resubmit the "Register Sidechain" command with a new value.
The first byte should be set to the correct value depending on the network on which the chain is running.

.registerSidechain.json
[source,json]
----
{
  "chainID": "00000001"
}
----

==== Name
The name of the sidechain as a string.
Has to be *unique* within the Lisk ecosystem  and contain only characters from the set `[a-z0-9!@$&_.]`.

.registerSidechain.json
[source,json]
----
{
  "chainID": "00000001",
  "name": "sidechain1"
}
----

==== sidechainCertificateThreshold
An integer setting the minimum signatures weight required for the first sidechain certificate to be valid.

.registerSidechain.json
[source,json]
----
{
  "chainID": "00000001",
  "name": "sidechain1",
  "sidechainCertificateThreshold": "2"
}
----

==== sidechainValidators
Defines the set of sidechain validators expected to sign the first certificate from the mainchain.
Each item contains the following properties:

. `blsKey`: The {url_bls_key}[public BLS key] of the validator.
. `bftWeight`: The {url_lip56}[BFT weight^] is the weight attributed to the pre-votes and pre-commits cast by a validator, and therefore determines to what extent the validator contributes to finalizing blocks.

To retrieve the BFT parameters of the sidechain validators, simply invoke the `consensus_getBFTParameters` endpoint on the *sidechain node*.

Set the `height` to the *latest block height on the sidechain* in the request parameters:

[tabs]
=====
Sidechain node CLI::
+
--
[source,bash]
----
./bin/run  endpoint:invoke consensus_getBFTParameters '{"height": 200}'
----
--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "consensus_getBFTParameters",
    "params": {
         "height": 200
    }
}'
----
--
=====

This will return a complete list of all active sidechain validators at the specified block height.

Now, paste the *complete list* that was returned by the `consensus_getBFTParameters` endpoint under the `"sidechainValidators"` key:

.registerSidechain.json
[source,json]
----
{
  "chainID": "00000001",
  "name": "sidechain1",
  "sidechainCertificateThreshold": "2",
  "sidechainValidators": [
	{
	  "blsKey": "92f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31",
	  "bftWeight": "2"
	}
  ]
}
----

=== Post the transaction on the mainchain

Send the transaction to a node that is connected to the mainchain.

[source,bash]
----
lisk-core transaction:create interoperability registerSidechain 2000000000 --pretty -f ./registerSidechain.json
----

[source,json]
----
{
  "transaction": "0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a0404000001120a73696465636861696e311a340a3092f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31100220023a408261e374405af4ec1143dfc0ae82a38e385d0edce870f698385749112064b374ac0de67354210aa27280db82121ec0bce195e5630c56a568a8b99dbbcb3a3d0b"
}
----

[source,bash]
----
./bin/run transaction:send 0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a0404000001120a73696465636861696e311a340a3092f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31100220023a408261e374405af4ec1143dfc0ae82a38e385d0edce870f698385749112064b374ac0de67354210aa27280db82121ec0bce195e5630c56a568a8b99dbbcb3a3d0b
----

----
Transaction with id: '1d944f3fb46714978ad7bedd1b788919c3b37e92d893088fd056f8217f20ed8a' received by node.
----

=== Get the sidechain account
Once the Register Sidechain command is processed, the sidechain account `status` is set to `registered`.

To verify that the account was created successfully, request the `interoperability_getChainAccount` endpoint from a mainchain node.

Parameters:

* `chainID`: The chain ID of the registered sidechain.

[tabs]
=====
Mainchain node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke interoperability_getChainAccount '{"chainID": "00000001"}'
----
--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getChainAccount",
    "params": {
         "chainID": "00000001"
    }
}'

----
--
=====



This will return the respective sidechain account stored in the xref:{url_sidechain_chain_store}[Chain substore] of the mainchain.

//TODO: Add example output

== How to register the mainchain on the sidechain

The mainchain is registered on a sidechain by posting a xref:{url_mainchain_reg}[Register Mainchain transaction].
A "Register Mainchain" transaction can be sent by any user account in the sidechain that has adequate funds to pay the required fee.

[IMPORTANT]
====
* The mainchain registration process always has to occur *after* the sidechain registration on the mainchain, since the sidechain has no prior knowledge of its name and must be certain that the correct chain ID has been registered.
* It is of key importance that the sidechain validators ensure that they are signing the registration command with the correct information, otherwise the sidechain interoperable functionality may be unusable.
====

To create a *Register Mainchain* transaction, the following information is required:

. <<ownchainid>>
. <<ownname>>
. <<mainchainvalidators>>
. <<mainchaincertificatethreshold>>
. <<signature>>
. <<aggregationbits>>

=== Prepare the required parameters

==== ownChainID
The chain ID of the sidechain.

==== ownName
Sets the name of the sidechain in its own state according to the name given in the mainchain.

==== mainchainValidators
Defines the set of mainchain validators expected to sign the first certificate from the mainchain.
Each item contains the following properties:

. `blsKey`: The {url_bls_key}[public BLS key] of the validator.
. `bftWeight`: The {url_lip56}[BFT weight^] is the weight attributed to the pre-votes and pre-commits cast by a validator.

==== mainchainCertificateThreshold
An integer setting the minimum signatures weight required for the first mainchain certificate to be valid.

==== signature
The `signature` property is an aggregate signature of the sidechain validators.
It ensures that the sidechain validators agree on registering the mainchain in the sidechain.

==== aggregationBits
The `aggregationBits` property is a bit vector used to validate the aggregate signature.

=== Posting a Register Mainchain transaction

.registerMainchain.json
[source,json]
----
{
  "ownChainID": "00000001",
  "ownName": "sidechain1",
  "mainchainValidators": [
	{
	  "blsKey": "92f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31",
	  "bftWeight": "2"
	}
  ],
  "mainchainCertificateThreshold": "2",
  "signature": "",
  "aggregationBits": ""
}
----

[source,bash]
----
./bin/run transaction:create interoperability registerMainchain 2000000000 --pretty -f ./registerMainchain.json
----

[source,json]
----
{
  "transaction": "0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a0404000001120a73696465636861696e311a340a3092f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31100220023a408261e374405af4ec1143dfc0ae82a38e385d0edce870f698385749112064b374ac0de67354210aa27280db82121ec0bce195e5630c56a568a8b99dbbcb3a3d0b"
}
----

[source,bash]
----
./bin/run transaction:send 0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a0404000001120a73696465636861696e311a340a3092f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31100220023a408261e374405af4ec1143dfc0ae82a38e385d0edce870f698385749112064b374ac0de67354210aa27280db82121ec0bce195e5630c56a568a8b99dbbcb3a3d0b
----

----
Transaction with id: '1d944f3fb46714978ad7bedd1b788919c3b37e92d893088fd056f8217f20ed8a' received by node.
----

=== Get mainchain account
Once the Register Mainchain command is processed, the mainchain account is initialized and its `status` is set to `registered`.

To verify that the account was created successfully, request the `interoperability_getChainAccount` endpoint from a sidechain node.

Parameters:

* `chainID`: The chain ID of the registered mainchain.

[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getChainAccount",
    "params": {
         "chainID": "00000000"
    }
}'

----

This will return the mainchain account stored in the xref:{url_sidechain_chain_store}[Chain substore] of the sidechain.

//TODO: Add example output
