= How to register a sidechain
Chris Braithwaite <christopher.braithwaite@lightcurve.io> Mona Bärenfänger <mona@lightcurve.io>
:description: How to register a sidechain to the mainchain and vice versa.
// Settings
:toc: preamble
:idprefix:
:idseparator: -
:docs_sdk: v6@lisk-sdk::
// URLs
:url_lisk_wallet: https://lisk.com/wallet
:url_bls_key: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0038.md#public-key-registration-and-proof-of-possession
:url_lip56: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0056.md
:url_update_cross_chain_lip53: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0053.md#outboxrootwitness
// Project URLs
:url_understand_interop_chainid: understand-blockchain/interoperability/index.adoc#chain-identifiers
:url_ccm: understand-blockchain/interoperability/communication.adoc#sending-cross-chain-transactions-to-generate-ccms
:url_ccu: understand-blockchain/interoperability/communication.adoc#creating-and-posting-ccus
:url_nonce: understand-blockchain/lisk-protocol/transactions.adoc#nonce
:url_sidechain_reg_recovery: understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
:url_sidechain_lifecycle: {url_sidechain_reg_recovery}#life-cycle-of-a-sidechain
:url_sidechain_liveness: {url_sidechain_reg_recovery}#liveness-condition
:url_sidechain_chain_store: {url_sidechain_reg_recovery}#chain-substore
:url_sidechain_reg_command: {url_sidechain_reg_recovery}#sidechain-registration-command
:url_mainchain_reg: {url_sidechain_reg_recovery}#mainchain-registration-command
:url_mainchain_reg_commands: {url_sidechain_reg_recovery}#mainchain-registration-on-a-sidechain
// Footnotes
:fn_lip53: footnote:witness[Due to the increasing size of the {url_update_cross_chain_lip53}[outboxRootWitness^] property of the command.]

====
On this page, you'll learn how to:

* [x] Register a sidechain on the mainchain
* [x] Register the mainchain on a sidechain
====

== Registration overview

This guide explains how to register a sidechain on the Lisk mainchain.
A registration is performed by creating the required chain accounts for sidechain and mainchain.

:sectnums:
== How to register a sidechain on the mainchain

A Register Sidechain transaction can be sent by any user account in the Lisk Mainchain that has adequate funds to pay the required fee.

=== Sidechain registration fee
When the Register Sidechain command is processed, it creates a sidechain account in the mainchain state associated with a unique chain identifier and a name.
Hence, every new sidechain occupies a certain namespace within the ecosystem.

Additionally, every newly registered sidechain can increase the size of every cross-chain update command posted on the mainchain{}

For these two reasons, the minimum fee for this command has an added constant similar to the extra fee in a delegate registration command.

The value of this extra registration fee is *10 LSK* tokens.

=== Posting a Register Sidechain transaction

NOTE: The Lisk Core node CLI is used in this example to post the transaction.
Alternatively, users can use the {url_lisk_wallet}[Lisk Wallet^], where the transaction can be created conveniently as well.

To create a xref:{url_sidechain_reg_recovery}[Sidechain Registration command], the following information is required:

. `name` -  The name of the sidechain as a string of characters.
Has to be *unique* within the Lisk ecosystem.
. `chainID` - The xref:{url_understand_interop_chainid}[chainID] of the sidechain.
Has to be *unique* within the Lisk ecosystem.
. `sidechainValidators` - This property defines the set of eligible keys with their respective weights and the certificate threshold required to sign the first certificate from the sidechain.
It is an object containing the following properties:
.. `keys`: An array of {url_bls_key}[BLS public keys].
The set of public keys that are eligible to sign the next certificate.
.. `bftWeight`: The {url_lip56}[BFT weight^] is the weight attributed to the prevotes and precommits cast by a validator, and therefore determines to what extent the validator contributes to finalizing blocks.
An array of integers of the same size as the keys property, where each element is the weight of the corresponding key.
For PoS chains it corresponds to the stake of the validator.
. `certificateThreshold`: An integer setting the minimum signatures weight required for the first sidechain certificate to be valid.

.registerSidechain.json
[source,json]
----
{
  "chainID": "00100000",
  "name": "sidechain1",
  "sidechainValidators": [
	{
	  "blsKey": "92f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31",
	  "bftWeight": "2"
	}
  ],
  "sidechainCertificateThreshold": "2"
}
----

[NOTE]
====
The node CLI of a sidechain client can be used to create the transaction as well.

Just make sure to send the transaction to a node that is connected to the mainchain, and not a sidechain node.
====

[source,bash]
----
lisk-core transaction:create interoperability registerSidechain 2000000000 --pretty -f ./registerSidechain.json
----

[source,json]
----
{
  "transaction": "0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a0404000001120a73696465636861696e311a340a3092f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31100220023a408261e374405af4ec1143dfc0ae82a38e385d0edce870f698385749112064b374ac0de67354210aa27280db82121ec0bce195e5630c56a568a8b99dbbcb3a3d0b"
}
----

[source,bash]
----
./bin/run transaction:send 0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a0404000001120a73696465636861696e311a340a3092f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31100220023a408261e374405af4ec1143dfc0ae82a38e385d0edce870f698385749112064b374ac0de67354210aa27280db82121ec0bce195e5630c56a568a8b99dbbcb3a3d0b
----

----
Transaction with id: '1d944f3fb46714978ad7bedd1b788919c3b37e92d893088fd056f8217f20ed8a' received by node.
----

=== Get the sidechain account
Once the Register Sidechain command is processed, the sidechain account `status` is set to `registered`.

To verify that the account was created successfully, request the `interoperability_getChainAccount` endpoint from a mainchain node.

Parameters:

* `chainID`: The chain ID of the registered sidechain.

[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getChainAccount",
    "params": {
         "chainID": "00100000"
    }
}'

----

This will return the respective sidechain account stored in the xref:{url_sidechain_chain_store}[Chain substore] of the mainchain.

//TODO: Add example output

== How to register the mainchain on the sidechain

WARNING: This registration process always has to occur after the sidechain registration on the mainchain, since the sidechain has no prior knowledge of its name and must be certain that the correct chain ID has been registered.

=== Posting a register mainchain transaction

It is of key importance that the sidechain validators ensure that they are signing the registration command with the correct information, otherwise the sidechain interoperable functionality may be unusable.

The command has the following parameters:

* *ownChainID*: The chain ID is set on the mainchain after processing the corresponding sidechain registration command.
* *ownName*: The `ownName` property sets the name of the sidechain in its own state according to the name given in the mainchain.
* *mainchainValidators*: This is similar to the `initValidators` property in the sidechain registration command, it defines the set of mainchain validators with their respective xref:{url_bft_weights}[BFT weight] expected to sign the first certificate from the mainchain.
* *signature*: The `signature` property is an aggregate signature of the sidechain validators.
It ensures that the sidechain validators agree on registering the mainchain in the sidechain.
* *aggregationBits*: The `aggregationBits` property is a bit vector used to validate the aggregate signature.


.registerMainchain.json
[source,json]
----
{
  "ownChainID": "04000001",
  "ownName": "sidechain1",
  "mainchainValidators": [
	{
	  "blsKey": "92f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31",
	  "bftWeight": "2"
	}
  ],
  "mainchainCertificateThreshold": "2",
  "signature": "",
  "aggregationBits": ""
}
----

[source,bash]
----
./bin/run transaction:create interoperability registerMainchain 2000000000 --pretty -f ./registerMainchain.json
----

[source,json]
----
{
  "transaction": "0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a0404000001120a73696465636861696e311a340a3092f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31100220023a408261e374405af4ec1143dfc0ae82a38e385d0edce870f698385749112064b374ac0de67354210aa27280db82121ec0bce195e5630c56a568a8b99dbbcb3a3d0b"
}
----

[source,bash]
----
./bin/run transaction:send 0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a0404000001120a73696465636861696e311a340a3092f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31100220023a408261e374405af4ec1143dfc0ae82a38e385d0edce870f698385749112064b374ac0de67354210aa27280db82121ec0bce195e5630c56a568a8b99dbbcb3a3d0b
----

----
Transaction with id: '1d944f3fb46714978ad7bedd1b788919c3b37e92d893088fd056f8217f20ed8a' received by node.
----

=== Get mainchain account
Once the Register Mainchain command is processed, the mainchain account is initialized and its `status` is set to `registered`.

To verify that the account was created successfully, request the `interoperability_getChainAccount` endpoint from a sidechain node.

Parameters:

* `chainID`: The chain ID of the registered mainchain.

[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getChainAccount",
    "params": {
         "chainID": "00000000"
    }
}'

----

This will return the mainchain account stored in the xref:{url_sidechain_chain_store}[Chain substore] of the sidechain.

//TODO: Add example output
