= Creating a new transaction asset
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:page-aliases: customize.adoc
:toc: preamble

// Project URLs
:url_guides_setup: guides/app-development/setup.adoc
:url_guides_module: guides/app-development/module.adoc
:url_guides_module_nft_utils: guides/app-development/module.adoc#nft-utility-functions
:url_guides_module_statestore: guides/app-development/module.adoc#statestore
:url_references_schemas: references/schemas.adoc
:url_tutorials: tutorials/index.adoc

How to create a new asset for a module of a blockchain application.

.Prerequisites
[NOTE]
====
To follow this guide, the following is assumed:

* Lisk Commander is installed, and a basic blockchain application is already initialized, as explained in the guide xref:{url_guides_setup}[].
* a custom module `NftModule` is created, as explained in the previous guide xref:{url_guides_module}[].
====

== Generating the asset skeleton

Use Lisk Commander to generate the skeleton for the new asset:

[source,bash]
----
$ lisk generate:asset --help
Creates an asset skeleton for the given module name, name, and id.

USAGE
  $ lisk generate:asset MODULENAME ASSETNAME ASSETID

ARGUMENTS
  MODULENAME  Module name.
  ASSETNAME   Asset name.
  ASSETID     Asset Id.

OPTIONS
  -t, --template=template  Template to bootstrap the application. It will read from `.liskrc.json` or use `lisk-ts` if not found.

EXAMPLES
  generate:asset nft transfer 1
----

The command `generate:asset` expects 3 arguments:

. *Module name*: The name of the module the asset belongs to.
. *Asset name*: The name of the new asset.
Needs to be a string that only consists of lower case and upper case letters [a-z, A-Z].
No numbers, hyphens, etc., are allowed.
. *Asset ID*: The ID of the asset.
Needs to be unique within the module.
Minimum value is 0.

As an example, we will add a new asset `createNFT` to the `nft` module:

[[generate-asset]]
[source,bash]
----
lisk generate:asset nft createNFT 0
----

This will generate the following files:

----
Creating asset skeleton with asset name "createNFT" and asset ID "0" for module "nft"
Using template "lisk-ts"
Generating asset skeleton.
Registering asset...
identical .liskrc.json
   create src/app/modules/nft/assets/create_n_f_t_asset.ts
   create test/unit/modules/nft/assets/create_n_f_t_asset.spec.ts

No change to package.json was detected. No package manager install will be executed.

Your asset is created and ready to use.
----

The file `create_n_f_t_asset.ts` contains the asset skeleton and the file `create_n_f_t_asset.spec.ts` contains the related unit tests for the new asset.

Firstly, view the module skeleton in `create_n_f_t_asset.ts`:

.src/app/modules/nft/assets/create_n_f_t_asset.ts
[source,typescript]
----
import { BaseAsset, ApplyAssetContext, ValidateAssetContext } from 'lisk-sdk';

export class CreateNFTAsset extends BaseAsset {
  public name = 'createNFT';
  public id = 0;

  // Define schema for asset
	public schema = {
    $id: 'nft/createNFT-asset',
		title: 'CreateNFTAsset transaction asset for nft module',
		type: 'object',
		required: [],
		properties: {},
  };

  public validate({ asset }: ValidateAssetContext<{}>): void {
    // Validate your asset
  }

  // eslint-disable-next-line @typescript-eslint/require-await
  public async apply({ asset, transaction, stateStore }: ApplyAssetContext<{}>): Promise<void> {
      throw new Error('Asset "createNFT" apply hook is not implemented.');
  }
}
----

The command `generate:asset` previously created the asset `createNFT` which already contains skeletons of all important components of an asset.
The only properties which are set at this point are the asset ID and the asset name, which were defined when generating the asset.


If the application is started at this point, it is already possible to create a basic `createNFT` transaction with an empty transaction asset, sign it, and send it to the node.
The node will then throw the following error:

 Asset "createNFT" apply hook is not implemented.

This is due to the fact that the `apply()` function of the asset is not implemented yet.
To give the asset a purpose, it is necessary to implement certain logic inside of the asset.

The following sections describe the different components of a transaction asset in detail.

== The asset class

The asset class always extends from the `BaseAsset`, which is imported from the `lisk-sdk` package.

The properties `name` and `id` are prefilled by the values used when <<generate-asset,generating the asset skeleton>> was completed in the previous step.

.src/app/modules/nft/assets/create_n_f_t_asset.ts
[source,typescript]
----
import { BaseAsset, ApplyAssetContext, ValidateAssetContext } from 'lisk-sdk';

export class CreateNFTAsset extends BaseAsset {
  public name = 'createNFT';
  public id = 0;

  // ...
}
----

== The asset schema

The asset schema defines in which format data is sent in the transaction asset.

TIP: For more information about schemas and how they are used in the Lisk SDK, check out the xref:{url_references_schemas}[].

We expect the following data in a transaction, to be able to create a new NFT:

* minPurchaseMargin: The % value of the initial value, that is added to the initial value when purchasing the NFT.
* initValue: The inital value of the NFT.
* name: The name of the NFT.

Therefore, the asset schema is adjusted accordingly as shown below:

.src/app/modules/nft/assets/create_n_f_t_asset.ts
[source,typescript]
----
public schema = {
    $id: "nft/createNFT-asset",
    title: 'CreateNFTAsset transaction asset for nft module',
    type: "object",
    required: ["minPurchaseMargin", "initValue", "name"], <1>
    properties: {
        minPurchaseMargin: {
            dataType: "uint32", <2>
            minimum: 0, <3>
            maximum: 100, <4>
            fieldNumber: 1, <5>
        },
        initValue: {
            dataType: "uint64", <6>
            exclusiveMinimum: 0, <7>
            fieldNumber: 2,
        },
        name: {
            dataType: "string",
            minLength: 3, <8>
            maxLength: 64, <9>
            fieldNumber: 3,
        },
    },
};
----

<1> All 3 properties are required to create a new NFT.
<2> `uin32` is used as a data type, because the `minPurchaseMargin` is a minimal number between 0 and 100.
<3> The minimum value is set to 0.
<4> The maximum value is set to 100.
<5> The `fieldNumber` increments by +1 for each property in the transaction asset.
<6> `uint64` is used as a data type, because the `initValue` can have very high values.
<7> The exclusive minimum value is set to 0, signifying that the `initValue` needs to be higher than 0 to be valid.
<8> The minimum length of the NFT name is set to 3.
<9> The maximum length of the NFT name is set to 64.

== Validating the asset data

The optional function `validate()` validates the data of a transaction asset, before it is passed to the `apply()` function.

If one of these conditions is not fulfilled, then the transaction will not be processed, and an error should be thrown.

TIP: The min and max values for the different properties of the schema do not need to get validated again in the `validate()` function.

In this example, we want to validate, that no NFT can be created with the name "Mewtwo".
Of course, what to validate here exaclty is up to the developer.
The name "Mewtwo" is choosen randomly for the example.

If some account sends a `createNFT` transaction, with `asset.name` equal to `Mewtwo`, it will throw the error `Illegal NFT name: Mewtwo`

.src/app/modules/nft/assets/create_n_f_t_asset.ts
[source,typescript]
----
validate({asset}) {
    if (asset.name === "Mewtwo") {
        throw new Error("Illegal NFT name: Mewtwo");
    }
};
----

If the validation does not throw any errors, that signifies they been successful and the data will be applied as defined in the `apply()` function.

== Defining the asset logic

The most important part of the transaction asset is the `apply()` function.
It contains the logic of how the data in the transaction asset should be applied on the blockchain.

In this example, we use the transaction data to create a new NFT token, which is added to the senders account.

To get and set the blockchain state, the `stateStore` is used again, which we know already from the lifecycle hooks of the xref:{url_guides_module_statestore}[module guide].

.src/app/modules/nft/assets/create_n_f_t_asset.ts
[source,typescript]
----
public async apply({ asset, transaction, stateStore }: ApplyAssetContext<{}>): Promise<void> {
    // 4.verify if sender has enough balance
    const senderAddress = transaction.senderAddress;
    const senderAccount = await stateStore.account.get(senderAddress);

    // 5.create nft
    const nftToken = createNFTToken({
      name: asset.name,
      ownerAddress: senderAddress,
      nonce: transaction.nonce,
      value: asset.initValue,
      minPurchaseMargin: asset.minPurchaseMargin,
    });

    // 6.update sender account with unique nft id
    senderAccount.nft.ownNFTs.push(nftToken.id);
    await stateStore.account.set(senderAddress, senderAccount);

    // 7.debit tokens from sender account to create nft
    await reducerHandler.invoke("token:debit", {
      address: senderAddress,
      amount: asset.initValue,
    });

    // 8.save nfts
    const allTokens = await getAllNFTTokens(stateStore);
    allTokens.push(nftToken);
    await setAllNFTTokens(stateStore, allTokens);
  }
}
----

=== NFT utility functions

The NFT utility functions that we use inside the `apply()` function are imported from the file `../nft.js`.

.src/app/modules/nft/assets/create_n_f_t_asset.ts
[source,typescript]
----
import { BaseAsset, ApplyAssetContext, ValidateAssetContext } from 'lisk-sdk';
import {
    getAllNFTTokens,
    setAllNFTTokens,
    createNFTToken,
}  from "../nft";
----

The file `nft.js` was already used in the guide xref:{url_guides_module_nft_utils}[Creating a new module], the functions `getAllNFTTokens()`, `setAllNFTTokens()`, `createNFTToken()` can simply be added, if not present yet:

.src/app/modules/nft/nft.js
[source,js]
----
const { codec, cryptography } = require("lisk-sdk");

const createNFTToken = ({ name, ownerAddress, nonce, value, minPurchaseMargin }) => {
  const nonceBuffer = Buffer.alloc(8);
  nonceBuffer.writeBigInt64LE(nonce);
  const seed = Buffer.concat([ownerAddress, nonceBuffer]);
  const id = cryptography.hash(seed);

  return {
    id,
    minPurchaseMargin,
    name,
    ownerAddress,
    value,
  };
};

const getAllNFTTokens = async (stateStore) => {
  const registeredTokensBuffer = await stateStore.chain.get(
    CHAIN_STATE_NFT_TOKENS
  );
  if (!registeredTokensBuffer) {
    return [];
  }

  const registeredTokens = codec.decode(
    registeredNFTTokensSchema,
    registeredTokensBuffer
  );

  return registeredTokens.registeredNFTTokens;
};

const setAllNFTTokens = async (stateStore, NFTTokens) => {
  const registeredTokens = {
    registeredNFTTokens: NFTTokens.sort((a, b) => a.id.compare(b.id)),
  };

  await stateStore.chain.set(
    CHAIN_STATE_NFT_TOKENS,
    codec.encode(registeredNFTTokensSchema, registeredTokens)
  );
};

module.exports = {
  registeredNFTTokensSchema,
  CHAIN_STATE_NFT_TOKENS,
  getAllNFTTokens,
  setAllNFTTokens,
  getAllNFTTokensAsJSON,
  createNFTToken,
};
----

