= Creating a custom asset
Mona Bärenfänger <mona@lightcurve.io>
:page-aliases: customize.adoc
:toc:
:v_sdk: v5.0.1

:url_guides_setup: guides/app-development/setup.adoc
:url_guides_module: guides/app-development/module.adoc
:url_tutorials: tutorials/index.adoc

This guide explains step-by-step, how to create a custom asset for a module of a blockchain application built with the Lisk SDK.

.Prerequisites
[NOTE]
====
To follow this guide, the following is assumed:

* a basic blockchain application is already initiated, like explained in the guide xref:{url_guides_setup}[].
* a custom module is created, like explained in the previous guide xref:{url_guides_module}[].
====

First, create a new file named after the new asset, for example `my-asset.js`.

----
├── blockchain_app
│   ├── index.js
│   ├── my-asset.js
│   ├── my-module.js
│   └── package.json
----

== Creating the asset class

Now open `my-asset.js` and import the `BaseAsset` from the `lisk-sdk` package:

[source,js]
----
const { BaseAsset } = require('lisk-sdk');
----

Next, define a new class `MyAsset`, which extends from the `BaseAsset`:

[source,js]
----
const { BaseAsset } = require('lisk-sdk');

class MyAsset extends BaseAsset {

}

module.exports = MyAsset;
----

== Setting name and ID of the module

Inside of the `MyAsset` class, define the different properties of the transaction asset:

`id`(number)::
The ID of the asset.
Must be unique within the module.
The ID is used for example to for creation of transactions of the module.
`name`(string)::
The name of the asset.
Must be unique within the module.

[source,js]
----
const { BaseAsset } = require('lisk-sdk');

class MyAsset extends BaseAsset {
  id = 0; <1>
  name = 'my-asset';
}

module.exports = MyAsset;
----

<1> The transaction asset `MyAsset` is the first asset of the module `MyModule`, therefore we set the `id` to the lowest possible value, which is `0`.

== Defining the asset schema

The asset schema defines in which format data is sent in the transaction asset.

DataType must be one of `string`, `bytes`, `boolean`, `uint32`, `sint32`, `uint64` or `sint64`.

[cols=",,",options="header",stripes="hover"]
|===
|Database
|JavaScript object
|JSON

|string
|string
|string

|uint32
|number
|number

|sint32
|number
|number

|uint64
|BigInt
|string

|sint64
|BigInt
|string

|bytes
|Buffer
|string in hex format

|boolean
|boolean
|boolean

|===

The schema must be defined like the example below, which is a modified JSON schema.

If the property is either an object or an array, the `type` property must be used to identify it, instead of `dataType`.

For better overview, let's add the schema to the file `schemas.js`, which was created in the previous guide xref:{url_guides_module}[].

.schemas.js
[source,js]
----
export const myAssetSchema = {
  // Unique identifier of the schema throughout the system
  $id: "/unique-id",
  // Root type must be type object
  type: "object",
  // Required properties
  required: ["key1","key2"],
  // Properties for the object
  properties: {
    key1: {
      dataType: "string",
      fieldNumber: 1,
    },
    key2: {
      dataType: "boolean",
      fieldNumber: 2,
    },
    key3: {
      dataType: "uint64",
      fieldNumber: 3,
    },
    key4: {
      type: "object",
      fieldNumber: 4,
      properties: {
        nestedKey1: {
          dataType: "sint32",
          fieldNumber: 1,
        },
        nestedKey2: {
          dataType: "string",
          fieldNumber: 2,
        },
      },
    },
    key5: {
      type: "array",
      fieldNumber: 5,
      items: {
        type: "object",
        properties: {
          nestedArrayKey1: {
            dataType: "string",
            fieldNumber: 1,
          },
          nestedArrayKey2: {
            dataType: "boolean",
            fieldNumber: 2,
          },
        },
      },
    },
    key6: {
      type: "array",
      fieldNumber: 6,
      items: {
        dataType: "bytes",
      },
    },
  },
  // Default values for the different properties
  default: {
    key1 : "",
    key2 : false,
    key3 : 0,
    key4 : {},
    key5 : [],
    key6 : [],
  }
}
----

Now include the schema in the module:

[source,js]
----
const { BaseModule } = require('lisk-sdk');
const { myAssetSchema } = require('./schemas.js'); <1>

class MyModule extends BaseModule {
  id = 1024;
  name = 'my-module';
  schema = myAssetSchema; <2>
}

module.exports = MyModule;
----

<1> Require the schema.
<2> Set the `schema` of the asset to the imported schema.
