= Configuring a blockchain application
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:page-aliases: configuration.adoc
:toc:
:idprefix:
:idseparator: -
:v_sdk: v5.1.1
// URLs
:url_github_config_devnet: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/sdk/src/samples/config_devnet.json
:url_github_constants_schema: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/framework/src/schema/application_config_schema.ts#L61
:url_github_genesis_block: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/sdk/src/samples/genesis_block_devnet.json
:url_github_sdk: https://github.com/LiskHQ/lisk-sdk/tree/{v_sdk}
// Project URLs
:url_architecture_config: advanced-explanations/architecture.adoc#configuration
:url_architecture_communication: advanced-explanations/communication.adoc
:url_architecture_genesis_block: advanced-explanations/architecture.adoc#genesis-block
:url_rpc_endpoints: advanced-explanations/rpc-endpoints.adoc
:url_guides_setup: guides/app-development/setup.adoc

This guide explains step-by-step, how to configure a blockchain application.

.Prerequisites
[NOTE]
====
To follow this guide, the following criteria is assumed:

* Lisk Commander is installed, and a basic blockchain application is already initialized, as explained in the previous guide xref:{url_guides_setup}[].
====

== Configuration options

[TIP]

It is not necessary to include all options that are included in the schema.
The application will use the default configuration options in case a config option is not specified.

=== List of all available config options

To get a complete overview of all configuration options for the Lisk SDK, please refer to the xref:{url_architecture_config}[configuration schema].

=== Important configuration options

==== `label`

Change the name of the blockchain application by updating the `label` option.

.Starting the app with a custom label
[source,js]
----
const { Application, configDevnet, genesisBlockDevnet, utils } = require('lisk-sdk'); <1>

// Create a custom config based on the configDevnet
const appConfig = utils.objects.mergeDeep({}, configDevnet, { <2>
    label: 'hello-app'
});

// Create the application instance
const app = Application.defaultApplication(genesisBlockDevnet, appConfig); <3>
----

==== `genesisConfig`

Specific constants for the blockchain application are set inside `configDevnet.genesisConfig`.
These constants allow the basic properties of the blockchain to be easily adjusted.
For example, the time that elapses until a new block is forged, the network epoch time, and the block rewards.

TIP: To see a full list of all constants and their predefined values, please see the file {url_github_constants_schema}[application_config_schema.js^].

.Starting the app with a custom genesisConfig
[source,js]
----
const { Application, configDevnet, genesisBlockDevnet, utils } = require('lisk-sdk');

// Create a custom config based on the configDevnet
const appConfig = utils.objects.mergeDeep({}, configDevnet, {
    genesisConfig: {
      bftThreshold: 78,
      communityIdentifier: 'hello',
      blockTime: 5,
      maxPayloadLength: 19000,
      rewards:{
        milestones: ['1000000000','700000000','500000000','200000000','100000000'],
        offset: 100,
        distance: 100000
      },
      minFeePerByte: 500,
      baseFees: [{
        moduleID: 2,
        assetID: 0,
        baseFee: 1000000,
      }]
    },
    activeDelegates: 31
    standbyDelegates: 5
});

// Create the application instance
const app = Application.defaultApplication(genesisBlockDevnet, appConfig);
----

===== Custom properties in the genesisConfig

Since all genesis config options will be passed, it is possible to add custom config options to the `genesisConfig`.
These options can then be used in a specific custom module.

.Adding a custom config option to the genesis config
[source,js]
----
const { Application, configDevnet, genesisBlockDevnet, utils } = require('lisk-sdk');

// Create a custom config based on the configDevnet
const appConfig = utils.objects.mergeDeep({}, configDevnet, {
    genesisConfig: {
      myCustomOption: 'Some data'
    },
});

// Create the application instance
const app = Application.defaultApplication(genesisBlockDevnet, appConfig);
----

==== `rpc`

The `rpc` key holds all configuration options related to the API access of the blockchain application.

[WARNING]
====
Allowing arbitrary machines to access the rpc port (ws) is dangerous and strongly discouraged -- access should be strictly limited to trusted machines.

To achieve this, configure a firewall that only allows access from whitelisted IPs
====

Please see the xref:{url_rpc_endpoints}[] and xref:{url_architecture_communication}[] pages for more information about the API access options.

.Starting the app with a custom API access
[source,js]
----
const { Application, configDevnet, genesisBlockDevnet, utils } = require('lisk-sdk');

// Create a custom config based on the configDevnet
const appConfig = utils.objects.mergeDeep({}, configDevnet, {
    rpc: {
        enable: true, //true or false
        mode: 'ws', //'ws' or 'ipc'
        port: 8888, //websocket port
    },
});

// Create the application instance
const app = Application.defaultApplication(genesisBlockDevnet, appConfig);
----
