= Configuring a blockchain application
Mona Bärenfänger <mona@lightcurve.io>
:description: How to configure a blockchain application together with the most important config options and the genesis block.
:page-aliases: configuration.adoc
:toc:
:v_sdk: v5.0.1
:v_protocol: master

:url_github_config_devnet: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/sdk/src/samples/config_devnet.json
:url_github_constants_schema: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/framework/src/schema/application_config_schema.ts#L61
:url_github_genesis_block: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/sdk/src/samples/genesis_block_devnet.json
:url_github_sdk: https://github.com/LiskHQ/lisk-sdk/tree/{v_sdk}

:url_architecture_config: architecture.adoc#configuration
:url_architecture_communication: communication.adoc
:url_architecture_genesis_block: architecture.adoc#genesis-block
:url_rpc_endpoints: rpc-endpoints.adoc
:url_guides_setup: guides/app-development/setup.adoc

This guide explains step-by-step, how to configure a blockchain application built with the Lisk SDK.

.Prerequisites
[NOTE]
====
To follow this guide, the following criteria is assumed:

* A basic blockchain application is already initiated as explained in the previous guide xref:{url_guides_setup}[starting a blockchain application].
====

When the application instance is created, the `Application` expects a configuration JSON object as the second argument, (the first one is the genesis block).

During development of a blockchain application it is recommended to import and use the {url_github_config_devnet}[configDevnet^] object from the Lisk SDK.
Together with `genesisBlockDevnet`, which defines the <<genesis_block, genesis block>>, it sets up a local development environment with 101 forging genesis delegates.

.index.js of the Hello World app
[source,js]
----
const { Application, configDevnet, genesisBlockDevnet, utils } = require('lisk-sdk'); <1>

// Create a custom config based on the configDevnet
const appConfig = utils.objects.mergeDeep({}, configDevnet, { <2>
    label: 'hello-app',
    genesisConfig: { communityIdentifier: 'hello' },
    rpc: {
        enable: true,
        mode: 'ws',
        port: 8888,
    },
    network: {
        port: 8887,
    },
    logger: {
        consoleLogLevel: 'info',
    },
});

// Create the application instance
const app = Application.defaultApplication(genesisBlockDevnet, appConfig); <3>
----

<1> Imports `Application`, `configDevnet`, `genesisBlockDevnet` and `utils` from the `lisk-sdk` package.
<2> Optionally it is possible to override certain options in `configDevnet` before creating the application instance.
<3> Creates the application instance and passes the `genesisBlockDevnet` as genesis block and `configDevnet` as config.

== The genesis block

When the application instance is created, the `Application` expects a xref:{url_architecture_genesis_block}[genesis block] as the first argument.

=== The devnet genesis block

The Lisk SDK exposes an object `genesisBlockDevnet` that holds all of the required configurations to spin up a local development network.

This genesis block can be used together with the `configDevnet` to quickstart your application with a preconfigured devnet.

TIP: Go to Github, to see the full file {url_github_genesis_block}[genesis_block_devnet.json^]

////
@TODO: Add link when the guide is created
[NOTE]
====
To learn how to create a custom genesis block, please refer to the guide xref:{}[]
====
////

== Configuration options

// suppress inspection "AsciiDocHeadingStyle"
[TIP]
====
It is not necessary to include all options that are included in the schema. The application will use the default configuration options in case a config option is not specified.
====

=== List of all available config options

To get a complete overview of all configuration options for the Lisk SDK, please refer to the xref:{url_architecture_config}[configuration schema].


=== Important configuration options

==== `label`

Change the name of the blockchain application by updating the `label` option.

.Starting the app with a custom label
[source,js]
----
const { Application, configDevnet, genesisBlockDevnet, utils } = require('lisk-sdk'); <1>

// Create a custom config based on the configDevnet
const appConfig = utils.objects.mergeDeep({}, configDevnet, { <2>
    label: 'hello-app'
});

// Create the application instance
const app = Application.defaultApplication(genesisBlockDevnet, appConfig); <3>
----

==== `genesisConfig`

Specific constants for the blockchain application are set inside `configDevnet.genesisConfig`.
These constants allow the basic properties of the blockchain to be easily adjusted.
For example, the time that elapses until a new block is forged, the network epoch time, and the block rewards.

TIP: To see a full list of all constants and their predefined values, please see the file {url_github_constants_schema}[application_config_schema.js^].

.Starting the app with a custom genesisConfig
[source,js]
----
const { Application, configDevnet, genesisBlockDevnet, utils } = require('lisk-sdk');

// Create a custom config based on the configDevnet
const appConfig = utils.objects.mergeDeep({}, configDevnet, {
    genesisConfig: {
      bftThreshold: 78,
      communityIdentifier: 'hello',
      blockTime: 5,
      maxPayloadLength: 19000,
      rewards:{
        milestones: ['1000000000','700000000','500000000','200000000','100000000'],
        offset: 100,
        distance: 100000
      },
      minFeePerByte: 500,
      baseFees: [{
        moduleID: 2,
        assetID: 0,
        baseFee: 1000000,
      }]
    },
    activeDelegates: 31
    standbyDelegates: 5
});

// Create the application instance
const app = Application.defaultApplication(genesisBlockDevnet, appConfig);
----

===== Custom properties in the genesisConfig

Since all genesis config options will be passed, it is possible to add custom config options to the `genesisConfig`.
These options can then be used in a specific custom module.

.Adding a custom config option to the genesis config
[source,js]
----
const { Application, configDevnet, genesisBlockDevnet, utils } = require('lisk-sdk');

// Create a custom config based on the configDevnet
const appConfig = utils.objects.mergeDeep({}, configDevnet, {
    genesisConfig: {
      myCustomOption: 'Some data'
    },
});

// Create the application instance
const app = Application.defaultApplication(genesisBlockDevnet, appConfig);
----

==== `rpc`

The `rpc` key holds all configuration options related to the API access of the blockchain application.

Please see the xref:{url_rpc_endpoints}[] and xref:{url_architecture_communication}[] pages for more information about the API access options.

.Starting the app with a custom API access
[source,js]
----
const { Application, configDevnet, genesisBlockDevnet, utils } = require('lisk-sdk');

// Create a custom config based on the configDevnet
const appConfig = utils.objects.mergeDeep({}, configDevnet, {
    rpc: {
        enable: true, //true or false
        mode: 'ws', //'ws' or 'ipc'
        port: 8888, //websocket port
    },
});

// Create the application instance
const app = Application.defaultApplication(genesisBlockDevnet, appConfig);
----
