= Creating a custom module
:sectnums:
// Project URLS
:url_guides_setup: guides/app-development/setup.adoc

This guide explains step-byb-step, how to create a custom module for a blockchain application bbuilt with the Lisk SDK.

.Prerequisites
[NOTE]
====
To follow this guide, the following is assumed:

* a basic blockchain application is already initiated, like explained in the previous guide xref:{url_guides_setup}[].
====

First, create a new file named after the new module, for example `my-module.js`.

//tree with standard app files + the new module
----
----

== Creating the module class

Now open `my-module.js` and import the `BaseModule` from the `lisk-sdk` package:

[source,js]
----
const { BaseModule } = require('lisk-sdk');
----

Next, define a new class `MyModule`, which extends from the `BaseModule`:

[source,js]
----
const { BaseModule } = require('lisk-sdk');

class MyModule extends BaseModule {

}

module.exports = MyModule;
----

== Setting name and ID of the module

Inside of the `myModule` class, define the different properties of the module:

`id`::
The ID of the module.
Must be unique in the application.
The ID is used for example to for creation of transactions of the module.
* Number
* Minimum value is `1024`
`name`::
The name of the module.
Must be unique in the application.
The name is used for example to subscribe to events, or to invoke actions of the module.
* String

== Defining the account schema

The account schema defines which propeties are added to user accounts by the module.

The new properties will be added under a key that is named after the module name.
Inside this new key, the module-specific properties for every account are saved.

== Adding transaction assets to the module

== Adding an interface by providing reducers, actions and events

== Defining the lifecycle hooks
