= Creating a custom module
:sectnums:
// Project URLS
:url_guides_setup: guides/app-development/setup.adoc

This guide explains step-byb-step, how to create a custom module for a blockchain application bbuilt with the Lisk SDK.

.Prerequisites
[NOTE]
====
To follow this guide, the following is assumed:

* a basic blockchain application is already initiated, like explained in the previous guide xref:{url_guides_setup}[].
====

== Creating the module class
First, create a new file named after the new module, for example `my-module.js`.

//tree with standard app files + the new module
----
----

Now open `my-module.js` and import the `BaseModule` from the `lisk-sdk` package:

[source,js]
----
const { BaseModule } = require('lisk-sdk');
----

Next, define a new class `MyModule`, which extends from the `BaseModule`:

[source,js]
----
const { BaseModule } = require('lisk-sdk');

class MyModule extends BaseModule {

}

module.exports = MyModule;
----

== Setting name and ID of the module

Inside of the `myModule` class, it is possible now to define the different properties and the behavior of the module.

== Defining the account schema

== Adding transaction assets to the module

== Adding an interface by providing reducers, actions and events

== Defining the lifecycle hooks
