= Decoding transactions and blocks with the API Client
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc: preamble
:imagesdir: ../../../assets/images
:idprefix:
:idseparator: -
:experimental:
// URLs
// Project URLS
:url_references_client: references/lisk-elements/client.adoc

Blocks and transactions can be decoded conveniently with the `apiClient` library of the Lisk SDK.

TIP: The `apiClient` is also included in the NPM package xref:{url_references_client}[`@liskhq/lisk-client`]

== Decoding a block

.Simple script for decoding a block by a given ID
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');
let clientCache;

const getClient = async () => {
	if (!clientCache) {
		clientCache = await apiClient.createWSClient('ws://localhost:8080/ws');
	}
	return clientCache;
};

if (process.argv.length < 3) {
	console.error("Please provide the block ID to be decoded.")
	process.exit(1);
}
const blockId = process.argv[2];


getClient().then((client) => {
	client.invoke("app:getBlockByID", {
		id: blockId
	}).then(res => {
		const block = client.block.decode(res);
		console.log(block);
		if (block.payload && block.payload.length > 0) {
			console.log(block.payload[0].asset);
		}
		process.exit(0);
	});
});
----

== Decoding a transaction

The transaction ID is returned evey time a transaction is sent to the node.

Write a simple script that decodes the transaction by providing the respective transaction ID as parameter. Create a new file `getTxById.js`:

.Example for decoding a transaction by a given ID
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');
let clientCache;

const getClient = async () => {
	if (!clientCache) {
		clientCache = await apiClient.createWSClient('ws://localhost:8080/ws');
	}
	return clientCache;
};

if (process.argv.length < 3) {
	console.error("Please provide the transaction ID to be decoded.")
	process.exit(1);
}
const txId = process.argv[2];

getClient().then((client) => {
	client.invoke("app:getTransactionByID", {
		id: txId
	}).then(res => {
		console.log(res);
		console.log(client.transaction.decode(res));
		process.exit(0);
	});
});
----

Assuming you want to decode a transaction with the ID `130227fa63ac60edbbacb6dae709cf9304ab0181ef7ea28105764f6240d012f2`, then execute the following:

[source,bash]
----
node getTxById.js 130227fa63ac60edbbacb6dae709cf9304ab0181ef7ea28105764f6240d012f2
----

The decoded transaction object is then returned in the terminal:

----
{
  moduleID: 1000,
  assetID: 0,
  nonce: 6n,
  fee: 100000000n,
  senderPublicKey: <Buffer ba d9 83 c7 2b ed 43 fd 27 4f 85 26 58 c2 98 b7 4c 71 ab 6f c5 05 08 87 9f ef 30 9e 38 36 38 4b>,
  asset: { helloString: 'Greetings! :-)' },
  signatures: [
    <Buffer 26 c7 24 8a 01 e1 ff 60 4d 93 28 0b 52 0b 13 d7 81 4d ff b4 ae 3f 28 ca 66 d3 0f 6d ca d7 de 89 1c 22 e6 8f f2 b5 3b c9 18 6c e8 07 d1 2e 96 f5 31 96 ... 14 more bytes>
  ],
  id: <Buffer 13 02 27 fa 63 ac 60 ed bb ac b6 da e7 09 cf 93 04 ab 01 81 ef 7e a2 81 05 76 4f 62 40 d0 12 f2>
}
----