= Communicating with a frontend
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:sectnums:
// External URLs
:url_reactjs: https://reactjs.org/
// Project URLS
:url_guides_asset: guides/app-development/asset.adoc
:url_guides_module: guides/app-development/module.adoc
:url_guides_setup: guides/app-development/setup.adoc

This guide explains step-by-step, how to build a simple frontend that communicates with a blockchain application built with the Lisk SDK.

.Prerequisites
[NOTE]
====
To follow this guide, the following criteria is assumed:

* a basic blockchain application is already initiated, as explained in the previous guide xref:{url_guides_setup}[].
====

To interact with the blockchain application conveniently through a browser, we want to build a simple frontend application.
This frontend can be build with any technology stack you feel most comfortable with.
In this example, we will use {url_reactjs}[React.js].

We will use the `@liskhq/lisk-client` package in the frontend application to communicate with the blockchain application.

== Create a new React app

First let's take a look at the current file structure of the project:

----
├── blockchain-app
│   ├── index.js
│   └── package.json
----

Create a new folder for the frontend on the root level of your project:

[source,bash]
----
npx create-react-app frontend-app
----

This will automatically set up a React project for you with default configurations in a newly created `frontend-app` folder.

----
├── blockchain-app
│   ├── index.js
│   └── package.json
├── frontend-app
│   ├── public/
│   ├── src/
│   ├── README.md
│   └── package.json
----

It is already possible to start the frontend at this point:

[source,bash]
----
cd frontend-app
npm start
----

== Create basic components

Now, let's customize this simple app by creating different components for the first basic functions of the frontend:

* New account: Generates new account credentials.
* Faucet: A component that sends funds to a specified account from the genesis account.
* Send transfer transaction: A component that allows to send token from one account to another.
* Account details: Returns details of a user account by address.

=== New account

[source,jsx]
----
import { passphrase, cryptography } from '@liskhq/lisk-client';

const newCredentials = () => {
    const pass = passphrase.Mnemonic.generateMnemonic();
    const keys = cryptography.getPrivateAndPublicKeyFromPassphrase(pass);
    const credentials = {
        address: cryptography.getBase32AddressFromPassphrase(pass),
        binaryAddress: cryptography.getAddressFromPassphrase(pass).toString("hex"),
        passphrase: pass,
        publicKey: keys.publicKey.toString("hex"),
        privateKey: keys.privateKey.toString("hex")
    };
    return credentials;
};

const NewAccount = () => {
    const credentials = newCredentials();
    return (
        <div>
            <h2>Create new account</h2>
            <p>Refresh page to get new credentials.</p>
            <pre>{JSON.stringify(credentials, null, 2)}</pre>
        </div>
    );
}
export default NewAccount;
----

=== Faucet

.api.js
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');
const RPC_ENDPOINT = 'ws://localhost:8888/ws';

let clientCache;

export const getClient = async () => {
    if (!clientCache) {
        clientCache = await apiClient.createWSClient(RPC_ENDPOINT);
    }
    return clientCache;
};
----

.Faucet.js
[source,jsx]
----
import React, { useState } from 'react';
import { cryptography, transactions } from '@liskhq/lisk-client';
import * as api from './api.js';

const accounts = {
  "genesis": {
    "passphrase": "peanut hundred pen hawk invite exclude brain chunk gadget wait wrong ready"
  }
};

const Faucet = () => {
    const [state, updateState] = useState({
        address: '',
        amount: '',
        transaction: {},
        response: {}
    });

    const handleChange = (event) => {
        const { name, value } = event.target;
        updateState({
            ...state,
            [name]: value,
        });
    };

    const handleSubmit = async (event) => {
        event.preventDefault();

        const client = await api.getClient();
        const address = cryptography.getAddressFromBase32Address(state.address);
        const tx = await client.transaction.create({
            moduleID: 2,
            assetID: 0,
            fee: BigInt(transactions.convertLSKToBeddows('0.01')),
            asset: {
                amount: BigInt(transactions.convertLSKToBeddows(state.amount)),
                recipientAddress: address,
                data: '',
            },
        }, accounts.genesis.passphrase);
        const response = await client.transaction.send(tx);
        updateState({
            transaction: client.transaction.toJSON(tx),
            address: '',
            amount: '',
            response:response
        });
    }

    return (
        <div>
            <h2>Faucet</h2>
            <p>The faucet transfers tokens from the genesis account to another.</p>
            <form onSubmit={handleSubmit}>
                <label>
                    Address:
                        <input type="text" id="address" name="address" onChange={handleChange} value={state.address} />
                </label>
                <label>
                    Amount (1 = 10^8 tokens):
                        <input type="text" id="amount" name="amount" onChange={handleChange} value={state.amount} />
                </label>
                <input type="submit" value="Submit" />
            </form>
            {state.transaction &&
                <div>
                    <pre>Transaction: {JSON.stringify(state.transaction, null, 2)}</pre>
                    <pre>Response: {JSON.stringify(state.response, null, 2)}</pre>
                </div>
            }
        </div>
    );
};

export default Faucet;
----

=== Send transaction

.Transfer.js
[source,jsx]
----
import React, { useState } from 'react';
import { cryptography, transactions } from '@liskhq/lisk-client';
import * as api from './api.js';

const Transfer = () => {
    const [state, updateState] = useState({
        address: '',
        amount: '',
        fee: '',
        passphrase: '',
        transaction: {},
        response: {}
    });

    const handleChange = (event) => {
        const { name, value } = event.target;
        updateState({
            ...state,
            [name]: value,
        });
    };

    const handleSubmit = async (event) => {
        event.preventDefault();

        const client = await api.getClient();
        const address = cryptography.getAddressFromBase32Address(state.address);
        const tx = await client.transaction.create({
            moduleID: 2,
            assetID: 0,
            fee: BigInt(transactions.convertLSKToBeddows(state.fee)),
            asset: {
                amount: BigInt(transactions.convertLSKToBeddows(state.amount)),
                recipientAddress: address,
                data: '',
            },
        }, state.passphrase);
        let res;
        try {
            res = await client.transaction.send(tx);
        } catch (error) {
            res = error;
        }

        updateState({
            transaction: client.transaction.toJSON(tx),
            response: res,
            address: '',
            amount: '',
            fee: '',
            passphrase: '',
        });
    };

    return (
        <div>
            <h2>Transfer</h2>
            <p>Send tokens from one account to another.</p>
            <form onSubmit={handleSubmit}>
                <label>
                    Recipient:
                        <input type="text" id="address" name="address" onChange={handleChange} value={state.address} />
                </label>
                <label>
                    Amount (1 = 10^8 tokens):
                        <input type="text" id="amount" name="amount" onChange={handleChange} value={state.amount} />
                </label>
                <label>
                    Fee:
                        <input type="text" id="fee" name="fee" onChange={handleChange}  value={state.fee} />
                </label>
                <label>
                    Passphrase:
                        <input type="text" id="passphrase" name="passphrase" onChange={handleChange}  value={state.passphrase} />
                </label>
                <input type="submit" value="Submit" />
            </form>
            {state.transaction &&
                <div>
                    <pre>Transaction: {JSON.stringify(state.transaction, null, 2)}</pre>
                    <pre>Response: {JSON.stringify(state.response, null, 2)}</pre>
                </div>
            }
        </div>
    );
}
export default Transfer;
----

=== Account details

.Account.js
[source,jsx]
----
import { cryptography } from '@liskhq/lisk-client';
import React, { useState } from 'react';
import * as api from './api.js';

const Account = () => {
    const [state, updateState] = useState({
        address: '',
        account: {},
    });

    const handleChange = (event) => {
        const { name, value } = event.target;
        updateState({
            ...state,
            [name]: value,
        });
    };

    const handleSubmit = async (event) => {
        event.preventDefault();
        const client = await api.getClient();
        const account = await client.account.get(cryptography.getAddressFromBase32Address(state.address));
        updateState({
            ...state,
            account: client.account.toJSON(account),
        });
    };

    return (
        <div>
            <h2>Account</h2>
            <p>Get account details by address.</p>
            <form onSubmit={handleSubmit}>
                <label>
                    Address:
                        <input type="text" id="address" name="address" onChange={handleChange} value={state.address} />
                </label>
                <input type="submit" value="Submit" />
            </form>
            <div>
                <pre>Account: {JSON.stringify(state.account, null, 2)}</pre>
            </div>
        </div>
    );
}
export default Account;
----

=== Index and navigation

.Home.js
[source,jsx]
----
import React from "react";

const Home = () => {
  return (
    <div>
      <h2>Hello Lisk!</h2>
      <p>A simple frontend for blockchain applications built with the Lisk SDK.</p>
    </div>
  );
};

export default Home;
----

.App.js
[source,jsx]
----
import React from "react";
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link
} from "react-router-dom";
import Home from './Home';
import NewAccount from './NewAccount';
import Faucet from './Faucet';
import Account from './Account';
import Transfer from './Transfer';

export const app = () => {
  return (
    <Router>
      <div>
        <Route>
          <ul>
            <li><Link to="/">Home</Link></li>
            <hr />
            <h3> Interact </h3>
            <li><Link to="/new-account">New Account</Link></li>
            <li><Link to="/faucet">Faucet</Link></li>
            <li><Link to="/send-transfer">Send Transfer</Link></li>
            <hr />
            <h3> Explore </h3>
            <li><Link to="/account">Account</Link></li>
          </ul>
        </Route>

        <Switch>
          <Route exact path="/">
            <Home />
          </Route>
          <Route path="/new-account">
            <NewAccount />
          </Route>
          <Route path="/faucet">
            <Faucet />
          </Route>
          <Route path="/send-transfer">
            <Transfer />
          </Route>
          <Route path="/account">
            <Account />
          </Route>
        </Switch>
      </div>
    </Router>
  );
}

export default app;
----

.index.js
[source,jsx]
----
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
----

== View in the browser
