= Communicating with a frontend
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:sectnums:
// External URLs
:url_reactjs: https://reactjs.org/
// Project URLS
:url_guides_asset: guides/app-development/asset.adoc
:url_guides_module: guides/app-development/module.adoc
:url_guides_setup: guides/app-development/setup.adoc

This guide explains step-by-step, how to build a simple frontend that communicates with a blockchain application built with the Lisk SDK.

.Prerequisites
[NOTE]
====
To follow this guide, the following criteria is assumed:

* a basic blockchain application is already initiated, as explained in the previous guide xref:{url_guides_setup}[].
* a custom module has been registered with the application, as explained in the previous guide xref:{url_guides_module}[].
* a custom asset is created, as explained in the previous guide xref:{url_guides_asset}[].
====

To interact with the blockchain application conveniently through a browser, we want to build a simple frontend application.
This frontend can be build with any technology stack you feel most comfortable with.
In this example, we will use {url_reactjs}[React.js].

== Create a new React app

First let's take a look at the current file structure of the project:

----
├── blockchain-app
│   ├── index.js
│   ├── my-asset.js
│   ├── my-module.js
│   ├── my-plugin.js
│   └── package.json
----

Create a new folder for the frontend on the root level of your project:

[source,bash]
----
npx create-react-app frontend-app
----

This will automatically set up a React project for you with default configurations in a newly created `frontend-app` folder.

----
├── blockchain-app
│   ├── defaults.js
│   ├── index.js
│   ├── my-asset.js
│   ├── my-module.js
│   ├── my-plugin.js
│   ├── schemas.js
│   └── package.json
├── frontend-app
│   ├── public/
│   ├── src/
│   ├── README.md
│   └── package.json
----

It is already possible to start the frontend at this point:

[source,bash]
----
cd frontend-app
npm start
----

== Create basic components

Now, let's customize this simple app by creating different components for the first basic functions of the frontend:

* New account: Generates new account credentials.
* Faucet: A component that sends funds to a specified account from the genesis account.
* Send transaction: A component that allows to send a specific transaction to the network.
* Account details: Returns details of a user account by address.

To communicate with the blockchain application, we will use the `@liskhq/lisk-client` package.

=== New account
=== Faucet
=== Send transaction
=== Account details
=== Index

== View in the browser
