= Generating a genesis block
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc:
// Project URLs
:url_default_modules: architecture/on-chain-architecture.adoc#sdk-default-modules
:url_guides_setup: guides/app-development/setup.adoc
:url_guides_module: guides/app-development/module.adoc
:url_modules_dpos: dpos-module.adoc
:url_modules_token: token-module.adoc

How to use `lisk-genesis` to generate a genesis block for a blockchain application.

.Prerequisites
[NOTE]
====
To follow this guide, the following is assumed:

* a basic blockchain application is already initiated, like explained in the guide xref:{url_guides_setup}[].
* a custom module `MyModule` is created, like explained in the previous guide xref:{url_guides_module}[].
====

Each blockchain application needs a genesis block, which is the very first block of the blockchain.

During development, the `genesisBlockDevnet` was used as genesis block.
Once the application will be released, it is important to exchange that genesis block with a cusomized one for your application.

Inside of the genesis block, it is possible to define the following parameters:

`accountAssetSchemas`(object)::
Required. The genesis block needs to contain all account asset schemas for all modules which are registered with the respective blockchain application.
The different account asset schemas are all grouped together in one big object and added as `accountAssetSchemas` to the genesis block params.
`accountAssetSchemas` is one of the most important parameters for generating a valid genesis block, so make sure it includes all required account asset schemas.

`initDelegates`(array)::
Required. List of initial delegate addresses used during the bootstrap period to forge blocks.
Addresses are expected to be in `Buffer` format.

`accounts`(array)::
Required. List of initial accounts in the network.
Minimum required is `address`, but can have other properties like `balance`.
Addresses are expected to be in `Buffer` format.

`initRounds?`(number)::
Optional. Number of rounds for bootstrap period, default is 3.

`height?`(number)::
Optional. Height of the genesis block.

`timestamp?`(number)::
Optional. Timestamp of the genesis block.

`previousBlockID?`(Buffer)::
Optional. Previous block ID.
Can be used for example in case of regenesis.

The genesis library can be used to generate a valid genesis block based on the above parameters.
It can be imported directly from the `lisk-sdk` package, or alternatively it can be installed as separate package `@liskhq/lisk-genesis`.

[source,bash]
----
npm install lisk-sdk
# or
npm install @liskhq/lisk-genesis
----

== Including the account asset schemas

The genesis block needs to include the account schemas of all modules that are registered with the application.
This also includes all account schemas of the xref:{url_default_modules}[default modules] which are registered with the application by default.

To achieve this, first import all relevant modules to get their account schemas:

[source,js]
----
const { TokenModule, DPoSModule, KeysModule, SequenceModule, genesis, passphrase, cryptography, configDevnet } = require('lisk-sdk');
const { MyModule } = require('./my-module');

// Create the accountAssetSchemas
const token = new TokenModule(configDevnet.genesisConfig).accountSchema;
const dpos = new DPoSModule(configDevnet.genesisConfig).accountSchema;
const keys = new KeysModule(configDevnet.genesisConfig).accountSchema;
const sequence = new SequenceModule(configDevnet.genesisConfig).accountSchema;
const myModule = new MyModule().accountSchema;

// Add fieldNumber starting from 2. Field number 1 is assigned to address of the account
token.fieldNumber = 2;
dpos.fieldNumber = 3;
keys.fieldNumber = 4;
sequence.fieldNumber = 5;
myModule.fieldNumber = 6;

const accountAssetSchemas = {
  token,
  dpos,
  keys,
  sequence,
  myModule
};
----

NOTE: The key of each account schema should equal the `name` property of the respective module.

[IMPORTANT]

====
The xref:{url_default_modules}[default modules] are always required to be included in the application for it to work properly.

If they are not included in the application, other modules need to be included, which replace their functionalities.
====

== Generating a list of genesis delegates

The genesis block includes a list of genesis delegates under the `initDelegates` key.

These delegates will forge during the bootstrap period of the blockchain, which is lasting 3 forging rounds (`3 * 103 blocks = 309 blocks`) by default.

TIP: The default length of the bootstrap period can be altered with the `initRounds` property.

=== Generation a fresh list of genesis delegates

If you don't have a list of already existing account details, it is needed to generate the accounts newly.

The three minimum properties for a delegate are the following:

* `address`(`Buffer`): Address of the delegate account.
* `token.balance`(`BigInt`): Balance of the delegate.
* `dpos.delegate.username`(`string`): Unique username of the delegate.

[source,js]
----
// Generating the genesis delegates

const newCredentials = () => {
    const pass = passphrase.Mnemonic.generateMnemonic();
    const keys = cryptography.getPrivateAndPublicKeyFromPassphrase(pass);
    const credentials = {
        address: cryptography.getBase32AddressFromPassphrase(pass),
        binaryAddress: cryptography.getAddressFromPassphrase(pass).toString("hex"),
        passphrase: pass,
        publicKey: keys.publicKey.toString("hex"),
        privateKey: keys.privateKey.toString("hex")
    };
    return credentials;
};

const credentials = [];


const newDelegate = (name) => {
  const cred = newCredentials();
  credentials.push(cred);
    const delegate = {
        address: Buffer.from(cred.binaryAddress, 'hex'),
        token: { balance: BigInt(100000000) },
        dpos: { delegate: { username: name } }
    };
    return delegate;
};

const generateDelegates = (amount) => {
  const delegates = [];
  const name = 'genesisDelegate';
  for (let i = 1; i <= amount; i++) {
    let nameNumber = name + i;
    delegates.push(newDelegate(nameNumber))
  }
  return delegates;
};

const delegates = generateDelegates(5);
----

== Generating the list of genesis accounts

All accounts that exist already in the beginning of the network are listed under the property `accounts` of the genesis block.

The `accounts` property is a list of accounts that always needs to include the accounts for the genesis delegates, that were created in the previous step.

Beside this, any other accounts can be added here, and account properties like `balance` can be configured as desired.

[source,js]
----
// Creating the genesis account list

const newAccount = () => {
  const cred = newCredentials();
  credentials.push(cred);
  const account = {
    address: Buffer.from(cred.binaryAddress, 'hex'),
    token: { balance: BigInt(25000000000) }
  };
  return account;
};

const generateAccounts = (amount) => {
  const accounts = [];
  for (let i = 1; i <= amount; i++) {
    accounts.push(newAccount())
  }
  return accounts;
};

const genesisAccounts = generateAccounts(3);

const accounts = [...delegates, ...genesisAccounts];
----

== Creating the genesis block

As final step, use the function `createGenesisBlock()` of the genesis library to generate the genesis block.

The parameters for the genesis block are all packed into one object.

* `initDelegates`(Array): List of addresses of the genesis delegates in `Buffer` format.
* `accounts`(Array): List of genesis accounts.
* `accountAssetSchemas`(Array): The account schemas of all modules which are registered with thee application.

This object is provided as parameter for the `createGenesisBlock()` function, which will then use them to generate the dedicated genesis block.

[source,js]
----
const genesisBlockParams = {
	initDelegates: delegates.map(a => a.address),
	accounts,
	accountAssetSchemas,
};

const genesisBlock = genesis.createGenesisBlock(genesisBlockParams);

console.log(genesisBlock);
----

== Complete example

.Full example: How to generate a genesis block
[source,js]
----
const { TokenModule, DPoSModule, KeysModule, SequenceModule, genesis, passphrase, cryptography, configDevnet } = require('lisk-sdk');
const { MyModule } = require('./my-module');

// Create the accountAssetSchemas
const token = new TokenModule(configDevnet.genesisConfig).accountSchema;
const dpos = new DPoSModule(configDevnet.genesisConfig).accountSchema;
const keys = new KeysModule(configDevnet.genesisConfig).accountSchema;
const sequence = new SequenceModule(configDevnet.genesisConfig).accountSchema;
const myModule = new MyModule().accountSchema;

// Add fieldNumber starting from 2. Field number 1 is assigned to address of the account
token.fieldNumber = 2;
dpos.fieldNumber = 3;
keys.fieldNumber = 4;
sequence.fieldNumber = 5;
myModule.fieldNumber = 6;

const accountAssetSchemas = {
  token,
  dpos,
  keys,
  sequence,
  myModule
};

// Generating the genesis delegates

const newCredentials = () => {
  const pass = passphrase.Mnemonic.generateMnemonic();
  const keys = cryptography.getPrivateAndPublicKeyFromPassphrase(pass);
  const credentials = {
    address: cryptography.getBase32AddressFromPassphrase(pass),
    binaryAddress: cryptography.getAddressFromPassphrase(pass).toString("hex"),
    passphrase: pass,
    publicKey: keys.publicKey.toString("hex"),
    privateKey: keys.privateKey.toString("hex")
  };
  return credentials;
};

const credentials = [];


const newDelegate = (name) => {
  const cred = newCredentials();
  credentials.push(cred);
  const delegate = {
    address: Buffer.from(cred.binaryAddress, 'hex'),
    token: { balance: BigInt(100000000) },
    dpos: { delegate: { username: name } }
  };
  return delegate;
};

const generateDelegates = (amount) => {
  const delegates = [];
  const name = 'genesisDelegate';
  for (let i = 1; i <= amount; i++) {
    let nameNumber = name + i;
    delegates.push(newDelegate(nameNumber))
  }
  return delegates;
};

const delegates = generateDelegates(5);

// Creating the genesis account list

const newAccount = () => {
  const cred = newCredentials();
  credentials.push(cred);
  const account = {
    address: Buffer.from(cred.binaryAddress, 'hex'),
    token: { balance: BigInt(25000000000) }
  };
  return account;
};

const generateAccounts = (amount) => {
  const accounts = [];
  for (let i = 1; i <= amount; i++) {
    accounts.push(newAccount())
  }
  return accounts;
};

const genesisAccounts = generateAccounts(3);

const accounts = [...delegates, ...genesisAccounts];

// Creating the genesis block

const genesisBlockParams = {
  initDelegates: delegates.map(a => a.address),
  accounts,
  accountAssetSchemas,
};

const genesisBlock = genesis.createGenesisBlock(genesisBlockParams);

console.log(genesisBlock);

----

.Example output
[source,js]
----
{
  header: {
    generatorPublicKey: <Buffer >,
    height: 0,
    previousBlockID: <Buffer >,
    reward: 0n,
    signature: <Buffer >,
    timestamp: 1620398241,
    transactionRoot: <Buffer e3 b0 c4 42 98 fc 1c 14 9a fb f4 c8 99 6f b9 24 27 ae 41 e4 64 9b 93 4c a4 95 99 1b 78 52 b8 55>,
    version: 0,
    asset: { initRounds: 3, initDelegates: [Array], accounts: [Array] },
    id: <Buffer a8 eb 2c da 7b 2a 8f 0e 84 24 1e 78 af 78 4e c9 0b ce d0 39 d0 b4 98 87 95 a8 5d 63 83 be c5 a0>
  },
  payload: []
}
----

== Optional parameters for the genesis block

Beside the three required properties `initDelegates`, `accounts`, and `accountAssetSchemas`, it is possible to set the following optional propeerties for the genesis block:

* `initRounds`(number): Number of rounds for bootstrap period, default is 3.
* `height`(number): Height of the genesis block.
* `timestamp`(number): Timestamp of the genesis block.
* `previousBlockID`(Buffer): Previous block ID.
Can be used for example in case of regenesis.

.Example: Generating a genesis block with all optional properties included
[source,js]
----
const genesisBlockParams = {
	initDelegates: delegates.map(a => a.address),
	accounts,
	accountAssetSchemas,
	initRounds: 200,
	height: 123,
	timestamp: 1520668243,
	previousBlockID: Buffer.from(
		'454690a1c37838326007519a7ce1c8a6a495df50898f1ebd69d22fbcedf9689a',
		'hex',
	)
};

const genesisBlock = genesis.createGenesisBlock(genesisBlockParams);

console.log(genesisBlock);
----
