= Generating a genesis block
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc:
// Project URLs
:url_guides_setup: guides/app-development/setup.adoc
:url_guides_module: guides/app-development/module.adoc

How to use `lisk-genesis` to generate a genesis block for a blockchain application.

.Prerequisites
[NOTE]
====
To follow this guide, the following is assumed:

* a basic blockchain application is already initiated, like explained in the guide xref:{url_guides_setup}[].
* a custom module `MyModule` is created, like explained in the previous guide xref:{url_guides_module}[].
====

Each blockchain application needs a genesis block, which is the very first block of the blockchain.

During development, the `genesisBlockDevnet` was used as genesis block.
Once the application will be released, it is important to exchange that genesis block with a cusomized one for your application.

Inside of the genesis block, it is possible to define the following parameters:

`accountAssetSchemas`(object)::
Required. The genesis block needs to contain all account asset schemas for all modules which are registered with the respective blockchain application.
The different account asset schemas are all grouped together in one big object and added as `accountAssetSchemas` to the genesis block params.
`accountAssetSchemas` is one of the most important parameters for generating a valid genesis block, so make sure it includes all required account asset schemas.

`accounts`(array)::
Required. List of initial accounts in the network.
Minimum required is `address`, but can have other properties like `balance`.
Addresses are expected to be in `Buffer` format.

`initDelegates`(array)::
Required. List of initial delegate addresses used during the bootstrap period to forge blocks.
Addresses are expected to be in `Buffer` format.

`initRounds?`(number)::
Optional. Number of rounds for bootstrap period, default is 3.

`height?`(number)::
Optional. Height of the genesis block.

`timestamp?`(number)::
Optional. Timestamp of the genesis block.

`previousBlockID?`(Buffer)::
Optional. Previous block ID.
Can be used for example in case of regenesis.


The genesis library can bbe used to generate a valid genesis block based on the above parameters.
It can be imported directly from the `lisk-sdk` package, or alternatively it can be installed as separate package `@liskhq/lisk-genesis`.

[source,bash]
----
npm install @liskhq/lisk-genesis
----

[source,js]
----
import * as genesis from '@liskhq/lisk-genesis
// or
// const { genesis } = require("lisk-sdk");
----

== Including the account asset schemas

== Generating a list of genesis delegates

== Generating the list of genesis accounts

== Optional parameters for the genesis block
