= Creating a module
Mona Bärenfänger <mona@lightcurve.io>
:toc: preamble
:sectnums:
:idprefix:
:idseparator: -
// URLs
//TODO: Add links to the code examples on lisk-sdk-examples repo
:url_github_hello_module: https://github.com/LiskHQ/lisk-sdk-examples/blob/development/tutorials/hello-world/blockchain_app/hello_module/hello_module.js
:url_github_nft_module: https://github.com/LiskHQ/lisk-sdk-examples/blob/development/tutorials/nft/blockchain_app/nft_module/index.js
:url_github_srs_module: https://github.com/LiskHQ/lisk-sdk-examples/blob/development/tutorials/social-recovery/blockchain_app/srs_module/index.js

// Project URLS
:url_guides_setup: guides/app-development/setup.adoc
:url_guides_setup_helloapp: guides/app-development/setup.adoc#the-hello-world-application
:url_guides_asset: guides/app-development/asset.adoc
:url_guides_genesis: guides/app-development/genesis-block.adoc
:url_guides_genesis_cli: guides/app-development/genesis-block.adoc#using-the-cli-to-generate-a-new-genesis-block
:url_guides_testing: guides/app-development/testing.adoc
:url_intro_modules: introduction/modules.adoc
:url_intro_modules_accountschema: introduction/modules.adoc#account-schema
:url_intro_modules_actions: introduction/modules.adoc#actions
:url_intro_modules_events: introduction/modules.adoc#events
:url_intro_modules_id: introduction/modules.adoc#module-id
:url_intro_modules_lifecyclehooks: introduction/modules.adoc#lifecycle-hooks
:url_intro_modules_name: introduction/modules.adoc#module-name
:url_modules_dpos: references/lisk-framework/dpos-module.adoc
:url_advanced_communication: advanced-explanations/communication.adoc
:url_advanced_communication_aliases: advanced-explanations/communication.adoc#aliases
:url_rpc_endpoints: advanced-explanations/rpc-endpoints.adoc
:url_references_schemas: advanced-explanations/schemas.adoc
:url_references_commander_commands_module: references/lisk-commander/commands.adoc#generate-module
:url_tutorials_nft: tutorials/nft.adoc
:url_tutorials_srs: tutorials/srs.adoc

How to create a new xref:{url_intro_modules}[module] for a blockchain application.

[TIP]

====
If you wish to view an example of a module in a more complex blockchain application, check out the following examples:

* the {url_github_nft_module}[NFT module] from the xref:{url_tutorials_nft}[] tutorial
* the {url_github_srs_module}[SRS module] from the xref:{url_tutorials_srs}[] tutorial
====

As defined in the xref:{url_guides_setup_helloapp}[Hello World application overview], the module shall provide the following functionality:

* A hello message shall be stored in the user accounts
** The hello message has to be of type `string`.
** The hello message has a maximum length of 64 characters.
* A counter, counting the total number of sent hello messages.
Anyone can request the current value of the hello counter.
* Anyone can be notified immediately, if a new hello message was sent.
The notification includes information about the sender andress and the sent hello message.

.Prerequisites
[NOTE]
====
To follow this guide, the following criteria is assumed:

* Lisk Commander is installed, and a basic blockchain application is already initialized, as explained in the previous guide xref:{url_guides_setup}[].
====

== Generating the module skeleton

While in the root folder of your blockchain application, generate a skeleton for the new module with Lisk Commander.

The command `lisk generate:module` expects 2 arguments:

. The xref:{url_intro_modules_name}[module name].
. The xref:{url_intro_modules_id}[module ID].
Needs to be unique within the application.
Minimum value is `1000`.

For a complete overview of all available options of the `generate:module` command, visit the xref:{url_references_commander_commands_module}[Lisk Commander command reference].

As an example, we use the module name `hello` and the module ID `1000`:

[[generate-module]]
[source,bash]
----
lisk generate:module hello 1000
----

This will generate the following files:

----
Creating module skeleton with module name "hello" and module ID "1000"
Using template "lisk-ts"
Generating module skeleton.
Registering module...
identical .liskrc.json
   create src/app/modules/hello/hello_module.ts
   create test/unit/modules/hello/hello_module.spec.ts

No change to package.json was detected. No package manager install will be executed.

Your module is created and ready to use.
----

It will also automatically register the module with the application, by adding it to `src/app/modules.ts`.

.src/app/modules.ts
[source,typescript]
----
import { Application } from 'lisk-sdk';
import { HelloModule } from "./modules/hello/hello_module";

export const registerModules = (app: Application): void => {

    app.registerModule(HelloModule);
};
----

Though you will notice, once the <<defining-an-account-schema,account schema>> is implemented into the module, that the application wont start successfully anymore.
That is, because the accounts in the genesis block are not including the account schema for the new module yet.

To solve this, simply generate a new genesis block by using the application CLI, like explained in the next guide xref:{url_guides_genesis}[].

The file `hello_module.ts` contains the module skeleton and the file `hello_module.spec.ts` contains the related unit tests for the new module.

TIP: For more information on how to write a unit test for the blockchain application, check out the xref:{url_guides_testing}[] guide.

The module skeleton can be viewed in `hello_module.ts`:

.src/app/modules/hello/hello_module.ts
[source,typescript]
----
import {
    BaseModule,
    AfterBlockApplyContext,
    TransactionApplyContext,
    BeforeBlockApplyContext,
    AfterGenesisBlockApplyContext,
    // GenesisConfig
} from 'lisk-sdk';

export class HelloModule extends BaseModule {
    public actions = {
        // Example below
        // getBalance: async (params) => this._dataAccess.account.get(params.address).token.balance,
        // getBlockByID: async (params) => this._dataAccess.blocks.get(params.id),
    };
    public reducers = {
        // Example below
        // getBalance: async (
		// 	params: Record<string, unknown>,
		// 	stateStore: StateStore,
		// ): Promise<bigint> => {
		// 	const { address } = params;
		// 	if (!Buffer.isBuffer(address)) {
		// 		throw new Error('Address must be a buffer');
		// 	}
		// 	const account = await stateStore.account.getOrDefault<TokenAccount>(address);
		// 	return account.token.balance;
		// },
    };
    public name = 'hello';
    public transactionAssets = [];
    public events = [
        // Example below
        // 'hello:newBlock',
    ];
    public id = 1000;

    // public constructor(genesisConfig: GenesisConfig) {
    //     super(genesisConfig);
    // }

    // Lifecycle hooks
    public async beforeBlockApply(_input: BeforeBlockApplyContext) {
        // Get any data from stateStore using block info, below is an example getting a generator
        // const generatorAddress = getAddressFromPublicKey(_input.block.header.generatorPublicKey);
		// const generator = await _input.stateStore.account.get<TokenAccount>(generatorAddress);
    }

    public async afterBlockApply(_input: AfterBlockApplyContext) {
        // Get any data from stateStore using block info, below is an example getting a generator
        // const generatorAddress = getAddressFromPublicKey(_input.block.header.generatorPublicKey);
		// const generator = await _input.stateStore.account.get<TokenAccount>(generatorAddress);
    }

    public async beforeTransactionApply(_input: TransactionApplyContext) {
        // Get any data from stateStore using transaction info, below is an example
        // const sender = await _input.stateStore.account.getOrDefault<TokenAccount>(_input.transaction.senderAddress);
    }

    public async afterTransactionApply(_input: TransactionApplyContext) {
        // Get any data from stateStore using transaction info, below is an example
        // const sender = await _input.stateStore.account.getOrDefault<TokenAccount>(_input.transaction.senderAddress);
    }

    public async afterGenesisBlockApply(_input: AfterGenesisBlockApplyContext) {
        // Get any data from genesis block, for example get all genesis accounts
        // const genesisAccoounts = genesisBlock.header.asset.accounts;
    }
}
----

The command `generate:module` already created the class `HelloModule` which contains skeletons for the most important components of a module.
The only properties which are set at this point are the module ID and the module name, which were defined previously while <<generate-module,generating the module skeleton>>.

In fact, with these 2 properties, it is already a complete module that can be registered with the application.
However, this module is not performing any functions yet.
To give the module a purpose, it is necessary to implement certain logic inside of the module.

The following sections explain, how the different components of a module can be used to implement the desired logic for the module.

== The module class

The module class always extends from the `BaseModule`, which is imported from the `lisk-sdk` package.

The properties `name` and `id` are prefilled by the values we used when <<generate-module,generating the module skeleton>> in the previous step.

.src/app/modules/hello/hello_module.ts
[source,typescript]
----
export class HelloModule extends BaseModule {

    // ...

    public name = 'hello';
    public id = 1000;

    // ...
}
----

== Defining an account schema

In some cases, the new module will require storing some new data in the user accounts.
If that is the case, it is required to define the corresponding account schema in the module.

TIP: For more information about the account schema in modules, check out the section about account schemas on the xref:{url_intro_modules_accountschema}[Modules] introduction page.

For the Hello application, we want to store a hello message in each user account, as defined in the application overview of the guide xref:{url_guides_setup_helloapp}[Creating a new blockchain application].
The hello message should be of type `string` and it should have a minium length of 3, and a maximum length of 64 characters.
All of this can be defined in the account schema.

The account schema for the Hello module is defined as follows:

[source,typescript]
----
export class HelloModule extends BaseModule {

    // ...

    public accountSchema = {
        type: 'object',
        properties: {
            helloMessage: {
                fieldNumber: 1,
                dataType: 'string',
                minLength: 3,
                maxLength: 64,
            },
        },
        default: {
            helloMessage: '',
        },
    };

    // ...
}
----

[IMPORTANT]

====
If a module includes an account schema, it is necessary to <<updating-the-genesis-block,update the genesis block>> after registering the module to the application.
====

== Assets

A module can include various assets, each allowing the module to handle a new transaction type.

Before a new asset can be added, it is first required to create the custom asset as described in the xref:{url_guides_asset}[] guide.

Assuming an asset `HelloAsset` has been created for the module, then it will be included in the module as shown below:

.src/app/modules/hello/hello_module.ts
[source,typescript]
----
import { BaseModule } from 'lisk-sdk';
const { HelloAsset } = require('./assets/hello_asset');

export class HelloModule extends BaseModule {

    // ...

    public transactionAssets = [
       new HelloAsset()
    ];

    // ...
}
----

== Events

A list of events that this module is able to emit.

Modules, plugins, and external services can subscribe to these events.

TIP: See the xref:{url_intro_modules_events}[Events] section of the "Modules" introduction page and the xref:{url_advanced_communication_aliases}[Aliases] section of the "Communication" page for more information.

Add a new event `newHello`.
This event shall be published, every time someone is updating their hello message.
The under `events` defined events can be published to the application in the <<lifecycle-hooks>> of the module.

[source,typescript]
----
export class HelloModule extends BaseModule {

    // ...
    public events = ['newHello'];

    // ...
}
----

== Lifecycle Hooks

Lifecycle hooks allow a module to execute certain logic, before or after blocks or transactions are applied to the blockchain.

Inside of the lifecycle hooks, it's possible to *publish* the above defined events to the application and to filter for certain transactions and blocks, before applying the logic.

TIP: See the "Lifecycle Hooks" section of the xref:{url_intro_modules_lifecyclehooks}[Modules] introduction page for more information.

In the hello module, two different lifecycle hooks are defined.

afterTransactionApply::
Publishes for every applied `hello` transaction asset a new event `hello:newHello`, and adds information about the sender of the transaction, and the corresponding hello message.

afterGenesisBlockApply::
If the genesis block is applied, it will set the counter for posted hello transactions to zero.

[source,typescript]
----
export class HelloModule extends BaseModule {

    // ...

    public async afterTransactionApply({transaction, stateStore, reducerHandler}) {
        // Publish a `newHello` event for every received hello transaction
        if (_input.transaction.moduleID === this.id && _input.transaction.assetID === HelloAssetID) {

          const helloAsset = codec.decode(
            helloAssetSchema,
            _input.transaction.asset
          );

          this._channel.publish('hello:newHello', {
            sender: _input.transaction._senderAddress.toString('hex'),
            hello: helloAsset.helloString
          });
        }
    }

    public async afterGenesisBlockApply({genesisBlock, stateStore, reducerHandler}) {
        // Set the hello counter to zero after the genesis block is applied
        await stateStore.chain.set(
            CHAIN_STATE_HELLO_COUNTER,
            codec.encode(helloCounterSchema, { helloCounter: 0 })
        );
    }

    // ...
}
----

It is recommended to store the different schemas in a separate file, e.g. `schemas.js`, and import them in the module and asset where needed.

TIP: For more information about schemas, check out the xref:{url_references_schemas}[] page.

The following schemas are used in the lifecycle hooks:

.Schemas
[source,js]
----
// This key is used to save the data for the hello counter in the database
const CHAIN_STATE_HELLO_COUNTER = "hello:helloCounter";

// This schema is used to decode/encode the data of the hello counter from/for the database
const helloCounterSchema = {
    $id: "lisk/hello/counter",
    type: "object",
    required: ["helloCounter"],
    properties: {
        helloCounter: {
            dataType: "uint32",
            fieldNumber: 1,
        },
    },
};

// This schema is used to decode/encode the data of the asset of the hello transaction from/for the database
const helloAssetSchema = {
  $id: "lisk/hello/asset",
  type: "object",
  required: ["helloString"],
  properties: {
    helloString: {
      dataType: "string",
      fieldNumber: 1,
    },
  },
};
----

== Actions

A list of actions that plugins and external services can invoke.

TIP: See the "Actions" section of the xref:{url_intro_modules_actions}[Modules] introduction page for more information.

Add a new action `amountOfHellos`.

If the action is invoked, it will return the total amount of sent hello messages in the network.
The hello counter is set to zero after applying the genesis block in the <<lifecycle-hooks>>, and incremented in the <<transaction-assets,asset>>.
The action simply returns the current value of the hello counter, which is retrieved from the database.

.src/app/modules/hello/hello_module.ts
[source,typescript]
----
export class HelloModule extends BaseModule {

    // ...

    public actions = {
        amountOfHellos: async () => {
            const res = await this._dataAccess.getChainState(CHAIN_STATE_HELLO_COUNTER);
            const count = codec.decode(
                helloCounterSchema,
                res
            );
            return count;
        },
    };

    // ...
}
----
