= Creating a new module
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:sectnums:
// URLs
:url_github_hello_module: https://github.com/LiskHQ/lisk-sdk-examples/blob/development/tutorials/hello-world/blockchain_app/hello_module/hello_module.js
:url_github_nft_module: https://github.com/LiskHQ/lisk-sdk-examples/blob/development/tutorials/nft/blockchain_app/nft_module/index.js
:url_github_srs_module: https://github.com/LiskHQ/lisk-sdk-examples/blob/development/tutorials/social-recovery/blockchain_app/srs_module/index.js

// Project URLS
:url_guides_setup: guides/app-development/setup.adoc
:url_guides_asset: guides/app-development/asset.adoc
:url_guides_genesis: guides/app-development/genesis-block.adoc
:url_guides_testing: guides/app-development/testing.adoc
:url_modules_dpos: references/lisk-framework/dpos-module.adoc
:url_rpc_endpoints: advanced-explanations/rpc-endpoints.adoc
:url_references_schemas: advanced-explanations/schemas.adoc
:url_tutorials_hello: tutorials/hello-world.adoc
:url_tutorials_nft: tutorials/nft.adoc
:url_tutorials_srs: tutorials/srs.adoc

How to create a new module for a blockchain application.

.Prerequisites
[NOTE]
====
To follow this guide, the following criteria is assumed:

* Lisk Commander is installed, and a basic blockchain application is already initialized, as explained in the previous guide xref:{url_guides_setup}[].
====


[TIP]

====
This guide describes the components of a module in general.
If you wish to view an example of a fully implemented module, check out the following examples:

* the {url_github_hello_module}[Hello module] from the xref:{url_tutorials_hello}[] tutorial
* the {url_github_nft_module}[NFT module] from the xref:{url_tutorials_nft}[] tutorial
* the {url_github_srs_module}[SRS module] from the xref:{url_tutorials_srs}[] tutorial
====

== Generating the module skeleton

Use Lisk Commander to generate the skeleton for the new module:

[source,bash]
----
$ lisk generate:module --help
Creates a module skeleton for the given name and id.

USAGE
  $ lisk generate:module MODULENAME MODULEID

ARGUMENTS
  MODULENAME  Module name.
  MODULEID    Module Id, should be at least 1000 or more

OPTIONS
  -t, --template=template  Template to bootstrap the application. It will read from `.liskrc.json` or use `lisk-ts` if not found.

EXAMPLE
  generate:module nft 5000
----

The command `lisk generate:module` expects 2 arguments:

. *Module name*: The name of the module.
The name is used for example to subscribe to events, or to invoke actions of the module.
Needs to be a string that only consists of upper and lower case letters [a-z, A-Z].
No numbers, hyphens, etc., are allowed.
. *Module ID*: The ID of the module.
Needs to be unique within the application.
Minimum value is `1000`.

As an example, we use the module name `nft` and the module ID `1000`:

[[generate-module]]
[source,bash]
----
lisk generate:module nft 1000
----

This will generate the following files:

----
Creating module skeleton with module name "nft" and module ID "1000"
Using template "lisk-ts"
Generating module skeleton.
Registering module...
identical .liskrc.json
   create src/app/modules/nft/nft_module.ts
   create test/unit/modules/nft/nft_module.spec.ts

No change to package.json was detected. No package manager install will be executed.


Your module is created and ready to use.
----

It will also automatically register the module with the application, by adding it to `src/app/modules.ts`.

.src/app/modules.ts
[source,typescript]
----
import { Application } from 'lisk-sdk';
import { NftModule } from "./modules/nft/nft_module";

export const registerModules = (app: Application): void => {
    app.registerModule(NftModule);
};

----

The file `nft_module.ts` contains the module skeleton and the file `nft_module.spec.ts` contains the related unit tests for the new module.

TIP: For more information on how to write a unit test for the blockchain application, check out the xref:{url_guides_testing}[] guide.

The module skeleton can be viewed in `nft_module.ts`:

[source,typescript]
----
import {
    BaseModule,
    AfterBlockApplyContext,
    TransactionApplyContext,
    BeforeBlockApplyContext,
    AfterGenesisBlockApplyContext,
    // GenesisConfig
} from 'lisk-sdk';

export class NftModule extends BaseModule {
    public actions = {
        // Example below
        // getBalance: async (params) => this._dataAccess.account.get(params.address).token.balance,
        // getBlockByID: async (params) => this._dataAccess.blocks.get(params.id),
    };
    public reducers = {
        // Example below
        // getBalance: async (
		// 	params: Record<string, unknown>,
		// 	stateStore: StateStore,
		// ): Promise<bigint> => {
		// 	const { address } = params;
		// 	if (!Buffer.isBuffer(address)) {
		// 		throw new Error('Address must be a buffer');
		// 	}
		// 	const account = await stateStore.account.getOrDefault<TokenAccount>(address);
		// 	return account.token.balance;
		// },
    };
    public name = 'nft';
    public transactionAssets = [];
    public events = [
        // Example below
        // 'nft:newBlock',
    ];
    public id = 1000;

    // public constructor(genesisConfig: GenesisConfig) {
    //     super(genesisConfig);
    // }

    // Lifecycle hooks
    public async beforeBlockApply(_input: BeforeBlockApplyContext) {
        // Get any data from stateStore using block info, below is an example getting a generator
        // const generatorAddress = getAddressFromPublicKey(_input.block.header.generatorPublicKey);
		// const generator = await _input.stateStore.account.get<TokenAccount>(generatorAddress);
    }

    public async afterBlockApply(_input: AfterBlockApplyContext) {
        // Get any data from stateStore using block info, below is an example getting a generator
        // const generatorAddress = getAddressFromPublicKey(_input.block.header.generatorPublicKey);
		// const generator = await _input.stateStore.account.get<TokenAccount>(generatorAddress);
    }

    public async beforeTransactionApply(_input: TransactionApplyContext) {
        // Get any data from stateStore using transaction info, below is an example
        // const sender = await _input.stateStore.account.getOrDefault<TokenAccount>(_input.transaction.senderAddress);
    }

    public async afterTransactionApply(_input: TransactionApplyContext) {
        // Get any data from stateStore using transaction info, below is an example
        // const sender = await _input.stateStore.account.getOrDefault<TokenAccount>(_input.transaction.senderAddress);
    }

    public async afterGenesisBlockApply(_input: AfterGenesisBlockApplyContext) {
        // Get any data from genesis block, for example get all genesis accounts
        // const genesisAccoounts = genesisBlock.header.asset.accounts;
    }
}
----

The command `generate:module` already created the class `NftModule` which contains skeletons for the most important components of a module.
The only properties which are set at this point are the module ID and the module name, which were defined previously.

In fact, with these 2 properties, it is already a complete module that can be registered with the application.
However, this module is not performing any functions yet.
To give the module a purpose, it is necessary to implement certain logic inside of the module.

The following sections explain, how the different components of a module can be used to implement the desired logic for the module.

== The module class

The module class always extends from the `BaseModule`, which is imported from the `lisk-sdk` package.

The properties `name` and `id` are prefilled by the values we used when <<generate-module,generating the module skeleton>> in the previous step.

[source,typescript]
----
import {
    BaseModule,
    AfterBlockApplyContext,
    TransactionApplyContext,
    BeforeBlockApplyContext,
    AfterGenesisBlockApplyContext,
    // GenesisConfig
} from 'lisk-sdk';

export class NftModule extends BaseModule {

    // ...

    public name = 'nft';
    public id = 1000;

    // ...
}
----

== Transaction assets

A module can include various custom transaction assets, that provide new transaction types to the application.

Before a new asset can be added, it is first required to create the custom asset as described in the xref:{url_guides_asset}[] guide.

Assuming an asset `CreateNFT` has been created for the module, then it will be included in the module as shown below:

[source,typescript]
----
import { BaseModule,AfterBlockApplyContext,TransactionApplyContext,BeforeBlockApplyContext,AfterGenesisBlockApplyContext } from 'lisk-sdk';
const { CreateNFT } = require('./assets/create_nft_asset');

export class NftModule extends BaseModule {

    // ...

    public transactionAssets = [new CreateNFT()];

    // ...
}
----

== Actions

A list of actions that plugins and external services can invoke via the API client.

TIP: See the xref:{url_rpc_endpoints}[] page for more information.

[source,typescript]
----
import { BaseModule, AfterBlockApplyContext, TransactionApplyContext, BeforeBlockApplyContext, AfterGenesisBlockApplyContext } from 'lisk-sdk';
import { CreateNFT } from './assets/create_nft_asset';
import { getAllNFTTokensAsJSON } from './nft';

export class NftModule extends BaseModule {

    // ...

    public actions = {
        getAllNFTTokens: async () => getAllNFTTokensAsJSON(this._dataAccess),
    };

    // ...
}
----

=== Data access for actions

Blockchain data can be accessed in a module via `this._dataAccess`.

The data access is only used in the implementation of the actions to retrieve certain information from the blockchain.

.Interface of `dataAccess`
----
interface dataAccess {
    getChainState: async (key: string) => Buffer,
    getAccountByAddress: async <T = AccountDefaultProps>(address: Buffer) => Account,
    getLastBlockHeader: async () => BlockHeader
}
----

=== NFT utility functions

The function `getAllNFTTokensAsJSON()` gets called, every time the action `nft:getAllNFTTokens` is invoked.
It will return a list of all registered NFTs as JSON.

`getAllNFTTokensAsJSON()` is imported from a new file `nft.js`, which is created manually to store the utility functions for the NFT module.
The implementation of the function is shown below:

.nft.js
[source,js]
----
const { codec } = require("lisk-sdk");

const registeredNFTTokensSchema = {
  $id: "lisk/nft/registeredTokens",
  type: "object",
  required: ["registeredNFTTokens"],
  properties: {
    registeredNFTTokens: {
      type: "array",
      fieldNumber: 1,
      items: {
        type: "object",
        required: ["id", "value", "ownerAddress", "minPurchaseMargin", "name"],
        properties: {
          id: {
            dataType: "bytes",
            fieldNumber: 1,
          },
          value: {
            dataType: "uint64",
            fieldNumber: 2,
          },
          ownerAddress: {
            dataType: "bytes",
            fieldNumber: 3,
          },
          minPurchaseMargin: {
            dataType: "uint32",
            fieldNumber: 4,
          },
          name: {
            dataType: "string",
            fieldNumber: 5,
          },
        },
      },
    },
  },
};

const CHAIN_STATE_NFT_TOKENS = "nft:registeredNFTTokens";

const getAllNFTTokensAsJSON = async (dataAccess) => {
  const registeredTokensBuffer = await dataAccess.getChainState(
    CHAIN_STATE_NFT_TOKENS
  );

  if (!registeredTokensBuffer) {
    return [];
  }

  const registeredTokens = codec.decode(
    registeredNFTTokensSchema,
    registeredTokensBuffer
  );

  return codec.toJSON(registeredNFTTokensSchema, registeredTokens).registeredNFTTokens;
};

module.exports = {
  registeredNFTTokensSchema,
  CHAIN_STATE_NFT_TOKENS,
  getAllNFTTokensAsJSON,
};
----

== Reducers

A list of actions that other modules of the application can invoke.

NOTE: Reducers can only be invoked by other modules, *not* by plugins.

[source,typescript]
----
public reducers = {
    // Example below
    // getBalance: async (
    // 	params: Record<string, unknown>,
    // 	stateStore: StateStore,
    // ): Promise<bigint> => {
    // 	const { address } = params;
    // 	if (!Buffer.isBuffer(address)) {
    // 		throw new Error('Address must be a buffer');
    // 	}
    // 	const account = await stateStore.account.getOrDefault<TokenAccount>(address);
    // 	return account.token.balance;
    // },
};
----

== Events

A list of events that this module is able to emit.

Modules, plugins, and external services can subscribe to these events.

TIP: See the xref:{url_rpc_endpoints}[] page for more information.

[source,typescript]
----
public events = [
    // Example below
    // 'nft:newBlock',
];
----

Which events, actions, and reducers are used within a module, or if these interfaces are actually required at all, will be a specific individual requirement for every module; as it is heavily dependant on which functionality the module intends to provide to the application.

In this example, no events for the NFT module will be implemented.

[TIP]

====
A list of modules with events:

* The {url_github_hello_module}[Hello Module^] from the xref:{url_tutorials_hello}[] tutorial
* The {url_github_srs_module}[SRS Module^] from the xref:{url_tutorials_srs}[] tutorial
====

== Lifecycle Hooks

Lifecycle hooks allow a module to execute certain logic, before or after blocks or transactions are applied to the blockchain.

Inside of the lifecycle hooks, it's possible to *publish* the above defined events to the application and to filter for certain transactions and blocks, before applying the logic.

The following lifecycle hooks are available for each module:

`beforeTransactionApply()`::
The code here is applied before each transaction is applied.
`afterTransactionApply()`::
The code here is applied after each transaction is applied.
`afterGenesisBlockApply()`::
The code here is applied after the genesis block is applied.
`beforeBlockApply()`::
The code here is applied before each block is applied.
`afterBlockApply()`::
The code here is applied after each block is applied.

[source,typescript]
----
public async beforeBlockApply({block, stateStore, reducerHandler}) {
    // Get any data from stateStore using block info, below is an example getting a generator
    // const generatorAddress = getAddressFromPublicKey(_input.block.header.generatorPublicKey);
    // const generator = await _input.stateStore.account.get<TokenAccount>(generatorAddress);
}

public async afterBlockApply({block, consensus, stateStore, reducerHandler}) {
    // Get any data from stateStore using block info, below is an example getting a generator
    // const generatorAddress = getAddressFromPublicKey(_input.block.header.generatorPublicKey);
    // const generator = await _input.stateStore.account.get<TokenAccount>(generatorAddress);
}

public async beforeTransactionApply({transaction, stateStore, reducerHandler}) {
    // Get any data from stateStore using transaction info, below is an example
    // const sender = await _input.stateStore.account.getOrDefault<TokenAccount>(_input.transaction.senderAddress);
}

public async afterTransactionApply({transaction, stateStore, reducerHandler}) {
    // Get any data from stateStore using transaction info, below is an example
    // const sender = await _input.stateStore.account.getOrDefault<TokenAccount>(_input.transaction.senderAddress);
}

public async afterGenesisBlockApply({genesisBlock, stateStore, reducerHandler}) {
    // Get any data from genesis block, for example get all genesis accounts
    // const genesisAccoounts = genesisBlock.header.asset.accounts;
}
----

In this example, no lifecycle hooks for the NFT module will be implemented.

[TIP]

====
A list of modules with implemented lifecycle hooks:

* The {url_github_hello_module}[Hello Module^] from the xref:{url_tutorials_hello}[] tutorial
* The {url_github_srs_module}[SRS Module^] from the xref:{url_tutorials_srs}[] tutorial
====

=== stateStore

The `stateStore` is used to mutate the state of the blockchain data, or to retrieve data from the blockchain.

Inside of a module, the `stateStore` is available for reducers and all lifecycle hooks.

.Interface of `stateStore`
----
interface StateStore {
	readonly account: {
		get<T = AccountDefaultProps>(address: Buffer): Promise<Account<T>>;
		getOrDefault<T = AccountDefaultProps>(address: Buffer): Promise<Account<T>>;
		set<T = AccountDefaultProps>(address: Buffer, updatedElement: Account<T>): Promise<void>;
		del(address: Buffer): Promise<void>;
	};
	readonly chain: {
		lastBlockHeaders: ReadonlyArray<BlockHeader>;
		lastBlockReward: bigint;
		networkIdentifier: Buffer;
		get(key: string): Promise<Buffer | undefined>;
		set(key: string, value: Buffer): Promise<void>;
	};
}
----

=== reducerHandler

Reducers of other modules can be *invoked* inside of the lifecycle hooks via the `reducerHandler`.

.Interface of `reducerHandler`
----
interface ReducerHandler {
	invoke: <T = unknown>(name: string, params?: Record<string, unknown>) => Promise<T>;
}
----

== Defining an account schema

In some cases, the new module will require storing some new data in the user accounts.
If that is the case, it is required to define the corresponding account schema in the module.

The account schema defines which properties are added to user accounts by the module.

TIP: For more information about schemas and how they are used in the Lisk SDK, check out the xref:{url_references_schemas}[].

The module-specific properties will be added under a key that is named after the module name.
So for example, in case the module name is `nft`, the data will be stored under the key "nft" in each user account.

The account schema for the NFT module is defined as follows:

[source,typescript]
----
export class NftModule extends BaseModule {

  // ...

  public accountSchema = {
    type: "object",
    required: ["ownNFTs"],
    properties: {
      ownNFTs: {
        type: "array",
        fieldNumber: 1,
        items: {
          dataType: "bytes",
        },
      },
    },
    default: {
      ownNFTs: [],
    },
  };

  // ...
}
----

[IMPORTANT]

====
If a module includes an account schema, it is necessary to update the genesis block after registering the module with the application.

For more information, see the xref:{url_guides_genesis}[] guide.
====
