= Creating a plugin
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc: preamble
:idprefix:
:idseparator: -
:sectnums:
// Project URLS
:url_architecture_config: advanced-explanations/architecture.adoc#configuration
:url_guides_module: guides/app-development/module.adoc
:url_guides_asset: guides/app-development/asset.adoc
:url_guides_setup: guides/app-development/setup.adoc
:url_intro_plugins: introduction/plugins.adoc

How to create a new xfef:{url_intro_plugins}[plugin] for a blockchain application.

.Prerequisites
[NOTE]
====
To use this guide, it is assumed that the following criteria have been met:

* Lisk Commander is installed, and a basic blockchain application is already initialized, as explained in the guide xref:{url_guides_setup}[].
* a new module `HelloModule` is created, as explained in the guide xref:{url_guides_module}[].
* a new asset `HelloAsset` is created, as explained in the previous guide xref:{url_guides_asset}[].
====

== Generating the plugin skeleton

Use Lisk Commander to generate the skeleton for the new asset:

[source,bash]
----
$ lisk generate:plugin --help
Creates custom plugin.

USAGE
  $ lisk generate:plugin ALIAS

ARGUMENTS
  ALIAS  Alias of the plugin.

OPTIONS
  -o, --output=output      Path to create the plugin.
  -t, --template=template  Template to bootstrap the application. It will read from `.liskrc.json` or use `lisk-ts` if not found.
  --registry=registry      URL of a registry to download dependencies from.
  --standalone             Create a standalone plugin package.

EXAMPLES
  generate:plugin my-plugin
  generate:plugin my-plugin --standalone --output ./myplugin
----

The command `generate:plugin` expects 1 argument:

* Plugin alias: The name of the plugin.
Needs to be a string that only consists of both lower case and upper case letters [a-z, A-Z].
No numbers, hyphens, etc., are allowed.

[[generate-plugin]]
[source,bash]
----
lisk generate:plugin latestHello
----

This will generate the following files:

----
Using template "lisk-ts"
Generating plugin skeleton
Registering plugin...
 conflict .liskrc.json
? Overwrite .liskrc.json? overwrite
    force .liskrc.json
   create src/app/plugins/latest_hello/latest_hello_plugin.ts
   create test/unit/plugins/latest_hello/latest_hello_plugin.spec.ts

No change to package.json was detected. No package manager install will be executed.

Finished creating plugin
----

It will also automatically register the plugin with the application by adding it to `src/app/plugins.ts`.

.src/app/plugins.ts
[source,typescript]
----
/* eslint-disable @typescript-eslint/no-empty-function */
import { Application } from 'lisk-sdk';
import { LatestHelloPlugin } from "./plugins/latest_hello/latest_hello_plugin";

// @ts-expect-error Unused variable error happens here until at least one module is registered
export const registerPlugins = (app: Application): void => {

    app.registerPlugin(LatestHelloPlugin);
};
----

The file `latest_hello_plugin.ts` contains the plugin skeleton and the file `latest_hello_plugin.spec.ts` contains the related unit tests for the new plugin.

The plugin skeleton can be viewed in `latest_hello_plugin.ts`:

[source,typescript]
----
import { BasePlugin, PluginInfo } from 'lisk-sdk';
import type { BaseChannel, EventsDefinition, ActionsDefinition, SchemaWithDefault } from 'lisk-sdk';

 /* eslint-disable class-methods-use-this */
 /* eslint-disable  @typescript-eslint/no-empty-function */
 export class LatestHelloPlugin extends BasePlugin {
	// private _channel!: BaseChannel;

	public static get alias(): string {
		return 'latestHello';
	}

	// eslint-disable-next-line @typescript-eslint/class-literal-property-style
	public static get info(): PluginInfo {
		return {
			author: 'mona',
			version: '0.1.0',
			name: 'latestHello',
		};
	}

	// eslint-disable-next-line @typescript-eslint/explicit-member-accessibility
	public get defaults(): SchemaWithDefault {
		return {
			$id: '/plugins/plugin-latestHello/config',
			type: 'object',
			properties: {},
			required: [],
			default: {},
		}
	}

	public get events(): EventsDefinition {
		return [
			// 'block:created',
			// 'block:missed'
		];
	}

	public get actions(): ActionsDefinition {
		return {
		// 	hello: async () => { hello: 'world' },
		};
	}

		public async load(_: BaseChannel): Promise<void> {
		// this._channel = channel;
		// this._channel.once('app:ready', () => {});
	}

	public async unload(): Promise<void> {}
}
----

The command `generate:plugin` already created the plugin `LatestHelloPlugin` which contains skeletons of all the important components of a plugin.
The only properties currently set at this point are the auto-generated plugin info, and the plugin alias which was defined when generating the plugin.

The plugin can already be used like this with the application, however, it is not performing any functions yet.
To give the plugin a purpose, it is necessary to implement certain logic inside of the plugin.

The following sections explain, how the different components of a plugin can be used to implement the desired logic.

== The plugin class

The plugin class always extends from the `BasePlugin`, which is imported from the `lisk-sdk` package.

The properties `alias` and `info` are pre-filled when <<generate-plugin,generating the plugin skeleton>> in the previous step.

[source,typescript]
----
import { BasePlugin, PluginInfo } from 'lisk-sdk';
import type { BaseChannel, EventsDefinition, ActionsDefinition, SchemaWithDefault } from 'lisk-sdk';

 export class LatestHelloPlugin extends BasePlugin {

	public static get alias(): string {
		return 'latestHello';
	}

	public static get info(): PluginInfo {
		return {
			author: 'mona',
			version: '0.1.0',
			name: 'latestHello',
		};
	}

	// ...

 }
----

== Actions & events

Similar to modules, plugins expose `actions` and `events`, which are interfaces that allow other plugins or external services to interact with the plugin.

In this example, one actions is added:

* If `latestHello:getLatestHello` is invoked, it returns the last hello message that was posted in the network.

[source,typescript]
----
public get actions(): ActionsDefinition {
    return {
      getLatestHello: () => this._hello,
    };
}
----

== Defining the plugin logic

The plugin subscribes to the event `hello:newHello`.
If a new event `latestHello:newHello` is published, it saves the latest hello message to `this._hello`.

[source,typescript]
----
public async load(channel): Promise<void> {
  channel.subscribe('hello:newHello', (info) => {
      this._hello = info;
    });
}

public async unload(): Promise<void> {}
----

== Defining the plugin configuration

A plugin can be configured by setting the related properties in the application configuration.

The `defaults()` getter defines which properties are available in the xref:{url_architecture_config}[application configuration] for the plugin.

The config options shown below are not really required in this example, however, they provide a good example of how to structure the configuration of a plugin.

[source,js]
----
public get defaults(): SchemaWithDefault {
    return {
        $id: '/plugins/plugin-latestHello/config',
        type: 'object',
        properties: {
            enable: {
                type: 'boolean',
            },
            port: {
                type: 'integer',
                minimum: 1,
                maximum: 65535,
            },
            host: {
                type: 'string',
                format: 'ip',
            },
            whiteList: {
                type: 'array',
                items: {
                    type: 'string',
                },
            },
            cors: {
                type: 'object',
                properties: {
                    origin: {
                        anyOf: [{ type: 'string' }, { type: 'boolean' }],
                    },
                    methods: {
                        type: 'array',
                    },
                },
                required: ['origin'],
            },
        },
        required: ['port', 'whiteList', 'cors', 'enable'],
        default: {
            enable: true,
            port: 5000,
            whitelist: ['127.0.0.1'],
            cors: {
                origin: '*',
                methods: ['GET', 'POST', 'PUT'],
            }
        },
    }
}
----
