= Creating a new plugin
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc:
:sectnums:
// Project URLS
:url_architecture: architecture/index.adoc#configuration
:url_guides_modules: guides/app-development/module.adoc
:url_guides_asset: guides/app-development/asset.adoc
:url_guides_config: guides/app-development/configuration.adoc
:url_guides_setup: guides/app-development/setup.adoc
:url_modules_dpos: dpos-module.adoc
:url_rpc_endpoints: rpc-endpoints.adoc
:url_tutorials_hello: tutorials/hello-world.adoc

How to create a new plugin for a blockchain application.

.Prerequisites
[NOTE]
====
To use this guide, it is assumed that the following criteria have been met:

* Lisk Commander is installed, and a basic blockchain application is already initialized, as explained in the guide xref:{url_guides_setup}[].
====

== Generating the plugin skeleton

Use Lisk Commander to generate the skeleton for the new asset:

[source,bash]
----
$ lisk generate:plugin --help
Creates custom plugin.

USAGE
  $ lisk generate:plugin ALIAS

ARGUMENTS
  ALIAS  Alias of the plugin.

OPTIONS
  -o, --output=output      Path to create the plugin.
  -t, --template=template  Template to bootstrap the application. It will read from `.liskrc.json` or use `lisk-ts` if not found.
  --registry=registry      URL of a registry to download dependencies from.
  --standalone             Create a standalone plugin package.

EXAMPLES
  generate:plugin my-plugin
  generate:plugin my-plugin --standalone --output ./myplugin
----

The command `generate:asset` expects 1 argument:

* Plugin alias: The name of the plugin.
Needs to be a string that only consists of small and capital letters [a-z,A-Z].
No numbers, hyphen, etc allowed.

[[generate-plugin]]
[source,bash]
----
lisk generate:plugin nftApi
----

This will generate the following files:

----
Using template "lisk-ts"
Generating plugin skeleton
Registering plugin...
identical .liskrc.json
   create src/app/plugins/nft_api/nft_api_plugin.ts
   create test/unit/plugins/nft_api/nft_api_plugin.spec.ts

No change to package.json was detected. No package manager install will be executed.

Finished creating plugin
----

It will also automatically register the plugin with the application, by adding it to `src/app/plugins.ts`.

.src/app/plugins.ts
[source,typescript]
----
/* eslint-disable @typescript-eslint/no-empty-function */
import { Application } from 'lisk-sdk';
import { NftApiPlugin } from "./plugins/nft_api/nft_api_plugin";

// @ts-expect-error Unused variable error happens here until at least one module is registered
export const registerPlugins = (app: Application): void => {

    app.registerPlugin(NftApiPlugin);
};
----

The file `nft_api_plugin.ts` contains the plugin skeleton and the file `nft_api_plugin.spec.ts` contains the related unit tests for the new plugin.

Take a look at the plugin skeleton in `nft_api_plugin.ts`:

[source,typescript]
----
import { BasePlugin, PluginInfo } from 'lisk-sdk';
import type { BaseChannel, EventsDefinition, ActionsDefinition, SchemaWithDefault } from 'lisk-sdk';

 /* eslint-disable class-methods-use-this */
 /* eslint-disable  @typescript-eslint/no-empty-function */
 export class NftApiPlugin extends BasePlugin {
	// private _channel!: BaseChannel;

	public static get alias(): string {
		return 'nftApi';
	}

	// eslint-disable-next-line @typescript-eslint/class-literal-property-style
	public static get info(): PluginInfo {
		return {
			author: 'mona',
			version: '0.1.0',
			name: 'nftApi',
		};
	}

	// eslint-disable-next-line @typescript-eslint/explicit-member-accessibility
	public get defaults(): SchemaWithDefault {
		return {
			$id: '/plugins/plugin-nftApi/config',
			type: 'object',
			properties: {},
			required: [],
			default: {},
		}
	}

	public get events(): EventsDefinition {
		return [
			// 'block:created',
			// 'block:missed'
		];
	}

	public get actions(): ActionsDefinition {
		return {
		// 	hello: async () => { hello: 'world' },
		};
	}

		public async load(_: BaseChannel): Promise<void> {
		// this._channel = channel;
		// this._channel.once('app:ready', () => {});
	}

	public async unload(): Promise<void> {}
}
----

The command `generate:plugin` already created the plugin `NftApiPlugin` which contains already skeletons of all important components of a plugin.
The only properties which are set at the moment are the auto-generated plugin info, and the plugin alias which we defined when generating the plugin.

The plugin can already be used like this with the application, but it isn't doing anything yet.
To give the plugin a purpose, it is needed to implement certain logic inside of the plugin.

The following sections explain, how the different components of a plugin can be used to implement the desired logic.

== The plugin class

The plugin class always extends from the `BasePlugin`, which is imported from the `lisk-sdk` package.

The properties `alias` and `info` are pre-filled when <<generate-plugin,generating the plugin skeleton>> in the previous step.

[source,typescript]
----
import { BasePlugin, PluginInfo } from 'lisk-sdk';
import type { BaseChannel, EventsDefinition, ActionsDefinition, SchemaWithDefault } from 'lisk-sdk';

 export class NftApiPlugin extends BasePlugin {

	public static get alias(): string {
		return 'nftApi';
	}

	public static get info(): PluginInfo {
		return {
			author: 'mona',
			version: '0.1.0',
			name: 'nftApi',
		};
	}

	// ...

 }
----

== Actions

Similar to modules, plugins expose `actions` and `events`, which are interfaces that allow other plugins or external services to interact with the plugin.

[source,typescript]
----
public get actions(): ActionsDefinition {
    return {
    // 	hello: async () => { hello: 'world' },
    };
}
----

In this example, two actions are added:

* If `getKnownTimestamp` is invoked, it returns the list of timestamps of the blocks that were added to the chain, while the plugin was active.
* If `getLatestDelegate` is invoked, it returns the last delegate name that was registered in the network.

[source,typescript]
----
public get actions(): ActionsDefinition {
    return {
      getKnownTimestamp: () => this._knownTimestamps,
      getLatestDelegate: () => this._latestDelegate
    };
}
----

== Events

[source,typescript]
----
public get events(): EventsDefinition {
    return [
        'newDelegate',
        'timestamp'
    ];
}
----

In this example, two events are added:

* `newDelegate`, which is published in the `load()` function, when a new delegate is registered in the network.
* `timestamp`, which is published in the `load()` function, when a new block is added to the blockchain.

== Defining the plugin logic

The `load()` function of a plugin contains the plugin logic that is executed when the plugin is loaded in the application.

It can be used to retrieve, mutate, store and/or publish data in a specific way, depending on the purpose of the plugin.

The `unload()` method contains the logic that needs to be executed to unload the plugin correctly.
It is executed for example on application shutdown.

The `channel`, which is available inside of the `load()` function, allows access to the xref:{url_rpc_endpoints}[] in order to subscribe to events or to invoke certain actions within the application, to retrieve the desired data.

In this example, we subscribe to the event `app:transaction:new`, which is published every time a new transaction is added to the application.
Next, the transaction is decoded and checked for it's `moduleID` and `assetID`.
If the transaction is a register delegate transaction, the delegate name is saved under `this._latestDelegate` and a new event `nftApi:newDelegate` is published, which is announcing the new delegate to the application.

Additionally, we subscribe to the event `app:block:new`, which is published everytime a new block is added to the blockchain.
Next, the block is decoded and the timestamp of the block is pushed into the `_knownTimestamps` array.
Then a new event `nftApi:timestamp` is published, which returns the updated timestamp array.

[source,typescript]
----
async load(channel) {
  this._api = await apiClient.createIPCClient('~/.lisk/my-app');

  channel.subscribe('app:transaction:new', (data) => {
    const txBuffer = Buffer.from(data.transaction, 'hex');
    const transaction = this._api.transaction.decode(txBuffer);
    if ( transaction.moduleID === 5 && transaction.assetID === 0 ) {
      this._latestDelegate = transaction.username;
      channel.publish('nftApi:newDelegate', {
        name: transaction.username,
      });
    }
  });
  channel.subscribe('app:block:new', ({ data }) => {
    const decodedBlock = this.codec.decodeBlock(data.block);
    this._knownTimestamps.push(decodedBlock.header.timestamp);
    channel.publish('nftApi:timestamp', { timestamp: decodedBlock.header.timestamp });
  });
}

public async unload(): Promise<void> {
  this._latestDelegate = undefined;
  this._knownTimestamps = [];
}
----

== Defining the plugin configuration

A plugin can be configured by setting the related properties in the application configuration.

The `defaults()` getter defines which properties are available in the xref:{}[application configuration] for the plugin.

The below config options are not really required in this example, but they give a good example of how a configuration of a plugin could be structured.

.defaults.js
[source,js]
----
public get defaults(): SchemaWithDefault {
    return {
        $id: '/plugins/plugin-nftApi/config',
        type: 'object',
        properties: {
            enable: {
                type: 'boolean',
            },
            port: {
                type: 'integer',
                minimum: 1,
                maximum: 65535,
            },
            host: {
                type: 'string',
                format: 'ip',
            },
            whiteList: {
                type: 'array',
                items: {
                    type: 'string',
                },
            },
            cors: {
                type: 'object',
                properties: {
                    origin: {
                        anyOf: [{ type: 'string' }, { type: 'boolean' }],
                    },
                    methods: {
                        type: 'array',
                    },
                },
                required: ['origin'],
            },
        },
        required: ['port', 'whiteList', 'cors', 'enable'],
        default: {
            enable: true,
            port: 5000,
            whitelist: ['127.0.0.1'],
            cors: {
                origin: '*',
                methods: ['GET', 'POST', 'PUT'],
            }
        },
    }
}
----
