= Testing the application
// Settings
:toc: preamble
// Project URLs
:url_guides_setup: guides/app-development/setup.adoc
:url_guides_module: guides/app-development/module.adoc
:url_guides_asset: guides/app-development/asset.adoc
:url_reference_test_suite: references/lisk-framework/test-suite.adoc


How to use the test utility of the Lisk SDK to test your application.

.Prerequisites
[NOTE]
====
To use this guide, it is assumed that the following criteria have been met:

* Lisk Commander is installed, and a basic blockchain application is already initialized, as explained in the guide xref:{url_guides_setup}[].
* a new module has been generated like described in the guide xref:{url_guides_module}[].
* a new asset has been generated like described in the guide xref:{url_guides_asset}[].
====

To test the functionality of modules, plugins or assets conveniently, adjust the already generated test skeletons in the `test` folder of your application.

After generating a new module and asset, the corresponding skeletons for their unit tests can bee found under `test/unit/modules/nft`:
----
├── _setup.js
├── commands
│   └── account
│       └── create.spec.ts
├── integration
├── network
├── tsconfig.json
├── unit
│   └── modules
│       └── nft
│           ├── assets
│           │   └── create_n_f_t_asset.spec.ts
│           └── nft_module.spec.ts
└── utils
    └── config.ts
----

== The module test skeleton

.test/unit/modules/nft/nft_module.spec.ts
[source,typescript]
----
// import * as modules from '../../../src/app/modules/nft'

describe('NftModuleModule', () => {
	describe('constructor', () => {
		it.todo('should have valid id');
		it.todo('should have valid name');
	});

	describe('beforeBlockApply', () => {
		it.todo('should execute before block apply');
	});
	describe('afterBlockApply', () => {
		it.todo('should execute after block apply');
	});
	describe('beforeTransactionApply', () => {
		it.todo('should execute before transaction apply');
	});
	describe('afterTransactionApply', () => {
		it.todo('should execute after transaction apply');
	});
	describe('afterGenesisBlockApply', () => {
		it.todo('should execute after genesis apply');
	});
});
----

== The asset test skeleeton

.test/unit/modules/nft/create_n_f_t_asset.spec.ts
[source,typescript]
----
import { CreateNFTAsset } from '../../../../../src/app/modules/nft/assets/create_n_f_t_asset';

describe('CreateNFTAsset', () => {
  let transactionAsset: CreateNFTAsset;

	beforeEach(() => {
		transactionAsset = new CreateNFTAsset();
	});

	describe('constructor', () => {
		it('should have valid id', () => {
			expect(transactionAsset.id).toEqual(0);
		});

		it('should have valid name', () => {
			expect(transactionAsset.name).toEqual('createNFT');
		});

		it('should have valid schema', () => {
			expect(transactionAsset.schema).toMatchSnapshot();
		});
	});

	describe('validate', () => {
		describe('schema validation', () => {
      it.todo('should throw errors for invalid schema');
      it.todo('should be ok for valid schema');
    });
	});

	describe('apply', () => {
    describe('valid cases', () => {
      it.todo('should update the state store');
    });

    describe('invalid cases', () => {
      it.todo('should throw error');
    });
	});
});
----

== Example: Unit test for a transaction asset

In this example, we will use the test suite of the Lisk SDK to write some simple unit tests for a new transaction asset that we created recently.

[TIP]

====
For more information about the different features of the test suite, check out the reference page xref:{url_reference_test_suite}[]
====
