= Lisk API Documentation


[[_overview]]
== Overview
= Welcome!

== Access Restrictions

The API endpoints are by default restricted to a whitelist of IPs that can be found in `config.json` in the section https://github.com/LiskHQ/lisk/blob/1.0.0/config.json#L35[`api.access.whitelist`].
If you want your API to be accessable by the public, you can do this by changing `api.access.public` to `true`.
This will allow anyone to make requests to your Lisk Core node.
However some endpoints stay private, that means only a list of whitelisted IPs can successfully make API calls to that particular endpoint;
This includes all forging related API calls.
By default, only the nodes' local IP is included in the whitelist, you can change the setting in `config.json` in the section https://github.com/LiskHQ/lisk/blob/1.0.0/config.json#L114[`forging.access.whitelist`].
For more details, see the descriptions at the respective endpoint.

== Requests

Chained filter parameters are logically connected with `AND`.
`HTTP` is the supported URL schema by default.
To enable `HTTPS`, please adjust the the https://github.com/LiskHQ/lisk/blob/1.0.0/config.json#L124[`ssl`] section in `config.json`.

== Responses

The general response format is JSON (`application/json`).
The responses for each API request have a common basic structure:

[source,javascript]
----
{
    "data": {}, //Contains the requested data
    "meta": {}, //Contains additional metadata, e.g. the values of `limit` and `offset`
    "links": {} //Will contain links to connected API calls from here, e.g. pagination links
}
----

== Date Formats

Most of the timestamp parameters are in the Lisk Timestamp format, which is similar to the Unix Timestamp format.
The *Lisk Timestamp* is the number of seconds that have elapsed since the Lisk epoch time (2016-05-24T17:00:00.000Z), not counting leap seconds.
The *Lisk Epoch Time* is returned in the https://en.wikipedia.org/wiki/ISO_8601[ISO8601] format, combined date and time: `YYYY-MM-DDThh:mm:ssZ`.
For details, see the descriptions and examples at the respective endpoint.

== Pagination

One can paginate nicely through the results by providing `limit` and `offset` parameters to the requests.
`limit` and `offset` can be found in the `meta`-object of the response of an API request.
If no limit and offset are provided, they are set to 10 and 0 by default, what will display the first 10 results.

== List of Endpoints

All possible API endpoints for Lisk Core are listed below.
Click on an endpoint to show descriptions, details and examples.


=== Version information
[%hardbreaks]
__Version__ : 1.0.32


=== Contact information
[%hardbreaks]
__Contact Email__ : admin@lisk.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0
__Terms of service__ : null


=== URI scheme
[%hardbreaks]
__BasePath__ : /api
__Schemes__ : HTTP, HTTPS


=== Tags

* Accounts : Account related API calls
* Blocks : Block related API calls
* Dapps : Dapps related API calls
* Delegates : Delegates related API calls
* Node : Node related API calls
* Peers : Peers related API Calls
* Signatures : Signatures related API calls
* Transactions : Transactions related API calls
* Voters : Votes related API calls
* Votes : Votes related API calls



