= Lisk Client
Mona Bärenfänger <mona@lightcurve.io>
:toc:

Provides a default set of Elements for use by clients of the Lisk network.

[NOTE]
====
The `+Client+` package is a collection of the following packages:

xref:lisk-elements/packages/api-client.adoc[api-client], xref:constants.adoc[constants],
xref:lisk-elements/packages/cryptography.adoc[cryptography], xref:passphrase.adoc[passphrase],
xref:lisk-elements/packages/transactions.adoc[transactions]
====

Lisk Elements will include a lot of different packages in the future, which can be plugged in to application as desired.

For better usability Lisk Elements provides special wrapper packages like `lisk-client`, which group packages that are often used in the same context.

== Installation

Add Lisk Client as a dependency of your project:

[source,bash]
----
$ npm install --save @liskhq/lisk-client
----

== Upgrade

[source,bash]
----
npm update --save @liskhq/lisk-client
----

== Usage

Import using ES6 modules syntax:

[source,js]
----
import lisk from '@liskhq/lisk-client';
----

Or using Node.js modules:

[source,js]
----
const lisk = require('@liskhq/lisk-client');
----

Or import specific namespaced functionality:

[source,js]
----
import { APIClient, transactions } from '@liskhq/lisk-client';
// or
const { APIClient, transactions } = require('@liskhq/lisk-client');
----
