== Lisk Core Administration

[cols=",",options="header",]
|===
|Subcategories |Description
|link:binary/admin-binary.md[Binary] |Administration using Binary

|link:docker/admin-docker.md[Docker] |Administration using Docker

|link:source/admin-source.md[Source] |Administration for Installation
from Source
|===

In this section you can find a list of the basic commands needed to
manage your Lisk node on the different distributions, e.g.:

* Start / Stop the Lisk Core process
* Get the status of your Lisk Node
* Create snapshots
* Reload / Rebuild Lisk Core

=== Snapshots

A snapshot is a backup of the complete blockchain. It can be used to
speed up the sync process, instead of having to validate all
transactions starting from genesis block to current block height. Lisk
provides official snapshots of the blockchain, see
http://snapshots.lisk.io.

____
link:binary/admin-binary.md#create-snapshot[Creating own snapshots] is
only supported for Lisk Core Binary distributions. Rebuilding from
snapshot is explained for each distribution in the Administration
section.
____
