= Contributing to the documentation
:url_docs_staging: https://liskhq.github.io/lisk-docs

== Issues

=== Creating issues

=== Working on an issue

. To work on an issue, first assign yourself to it.
. Then check out `docs-sdk` and create a new branch named after the issue you are working on:
+
[source,bash]
----
git checkout docs-sdk
git checkout -b 123-issue-title
----
+
where `123` should be the corresponding issue number.
. Now commit the intended changes and push them back to the `lisk-docs` repository on Github:
+
[source,bash]
----
git push origin 123-issue-title
----

== Projects

== Pull requests (PRs)

=== Creating a PR

. On Github, now open a PR with `docs-sdk` as base branch:
.. Link the corresponding issue in the description and request a reviewer.


== Preview on staging

To verify the correct presentation of the changed content, the docs can be previewed on the {url_docs_staging}[lisk-docs staging] page.
It can then be reviewed at

NOTE: The next- and previous links generally don't work on staging.

== Review

== Merge

