= Getting started
:toc:
:url_gh_commitverification: https://docs.github.com/en/authentication/managing-commit-signature-verification
:url_github_docs: git@github.com:LiskHQ/lisk-docs.git
:url_git_worktree: https://git-scm.com/docs/git-worktree
:url_antora_install: https://docs.antora.org/antora/latest/install-and-run-quickstart/

== Clone the `lisk-docs` repository

[subs=attributes+]
 git clone {url_github_docs}

== Add GPG key to your GitHub account

It is required that all commits are signed by the person who commits.

A GPG key can be used to sign commits with git.

How to add a GPG key to GitHub and other information about the topic is explained here: {url_gh_commitverification}[^]

== Add git worktrees

Worktrees allow checking out several branches of a repository simultaneously.

Each branch is stored in a folder with a name analog to the branch name.

[source,bash,subs=attributes+]
```
cd lisk-docs/build
git worktree add docs-sdk docs-sdk #<1>
git worktree add docs-service docs-service #<2>
git worktree add docs-core docs-core #<3>
git worktree add git-pages git-pages #<4>
```

<1> Directory for working on SDK docs
<2> Directory for working on Service docs
<3> Directory for working on Core docs
<4> Output directory for the compiled documentation for GitHub Pages

TIP: More information about `git worktree` can be found in the {url_git_worktree}[Git documentation reference^].

== Install Antora

Install Antora to be able to compile the docs for a local preview.

 npm i -g @antora/cli@3.0.0 @antora/site-generator@3.0.0

TIP: See {url_antora_install}[^] for more information about how to install Antora.
