= Building the Lisk documenation
// Settings:
:hide-uri-scheme:
:idprefix:
// External URLs:
:url_antora: https://antora.org/
:url_docs: https://lisk.io/documentation/lisk-sdk/index.html
:url_gitlab_antora_extensions: https://gitlab.com/antora/antora-asciidoctor-extensions
// Project URLs:
:url_contributing: contributing.adoc
:url_search: search.adoc
:url_staging: staging.adoc

Lisk uses {url_antora}[Antora^] as documentation generator.

Click here to see the live version of the {url_docs}[Lisk Documentation^].

== Content branches

All content branches store the documentation for a specific product and are referring to a specific version of the product.

=== Documentation components

NOTE: These branches store the latest or WIP versions of each component

* `docs-sdk`
* `docs-core`
* `docs-protocol`
* `docs-service`

=== Previous versions

* `docs-COMPONENT-1.2.3`
+
where

** `COMPONENT` can be either `sdk`, `core`, `protocol` or `service`.
** `1.2.3` represents the respective version number of the corresponding product.

== UI branches

The presentation of the documentation is stored completely separate form the actual content.
It's stored on the `antora` branch.

== The build branch
The `build` branch stores...

* ...the `site.yml` file, which is used to generate the Lisk Documentation using Antora.
* ...the `searchdocs-scraper` folder, for creating the search index.
* ...the `lib` folder, which stores the <<Asciidoc extensions>>, that are used in the Lisk documentation.

NOTE: More information under xref:{url_staging}[] and xref:{url_search}[].

=== Asciidoc extensions

The following Asciidoc extension are used currently:

Tabs::
A clone of {url_gitlab_antora_extensions}.
+
.How to create 2 tabs in Asciidoc
[source,asciidoc]
----
[tabs]
=====
Tab1 title::
+
--
Tab1 content
--
Tab2 title::
+
--
Tab2 content
--
=====
----
