= Building the Lisk documentation
// Settings:
:hide-uri-scheme:
:idprefix:
// External URLs:
:url_antora: https://antora.org/
:url_antora_docs: https://docs.antora.org/antora/2.3/standard-directories/#hierarchy-and-reserved-names
:url_docs: https://lisk.io/documentation
:url_docs_staging: https://liskhq.github.io/lisk-docs
:url_github_docs: https://github.com/LiskHQ/lisk-docs
:url_gitlab_antora_extensions: https://gitlab.com/antora/antora-asciidoctor-extensions
// Project URLs:
:url_contributing: contributing.adoc
:url_search: search.adoc
:url_staging: staging.adoc
:url_structure: structure.adoc

Lisk uses {url_antora}[Antora^] as a documentation generator.

All files for the Lisk documentation are stored in the GitHub repository at {url_github_docs}[^].

== Environments

=== Staging

The testing and WIP environment for the Lisk documentation.
Link to the WIP Lisk documentation: {url_docs_staging}.

Stored in the `development` branch.

=== Production

The official and public location of the Lisk documentation.
Link to the production version of the Lisk documentation: {url_docs}.

Stored in the `main` branch.

== Content branches

All content branches store the documentation for a specific product and are referring to a specific version of the product.

TIP: Learn more about the structure of Antora content branches: {url_antora_docs}.

=== Documentation components

NOTE: These branches store the latest or WIP versions of each component

* `docs-sdk`
* `docs-core`
* `docs-protocol`
* `docs-service`

=== Previous versions

* `docs-COMPONENT-1.2.3`
+
where

** `COMPONENT` can be either `sdk`, `core`, `protocol` or `service`.
** `1.2.3` represents the respective version number of the corresponding product.

=== Structure

== UI branches

The presentation of the documentation is stored completely separate from the actual content.

* `dev-antora`: This branch stores the Lisk docs UI used in development.
It's used in the staging environment.
* `antora`: This branch stores the Lisk docs UI used in production.
It's used in the production environment.

== The build branch
The `build` branch stores...

* ...the `site.yml` file, which is used to generate the Lisk Documentation using Antora.
* ...the `searchdocs-scraper` folder, for creating the search index.
* ...the `lib` folder, which stores the <<Asciidoc extensions>>, that are used in the Lisk documentation.

NOTE: More information under xref:{url_structure}[], xref:{url_staging}[] and xref:{url_search}[].

=== Asciidoc extensions

The following Asciidoc extension are used currently:

Tabs::
A clone of {url_gitlab_antora_extensions}.
+
.How to create 2 tabs in Asciidoc
[source,asciidoc]
----
[tabs]
=====
Tab1 title::
+
--
Tab1 content
--
Tab2 title::
+
--
Tab2 content
--
=====
----
