= Building the Lisk documenation

:url_antora: https://antora.org/
:url_docs: https://lisk.io/documentation/lisk-sdk/index.html

:url_contributing: contributing.adoc

Lisk uses {url_antora}[Antora^] as documentation generator.

Click here to see the live version of the {url_docs}[Lisk Documentation^].

xref:{url_contributing}[How to contribute to the Lisk Documentation]

== Content branches

All content branches store the documentation for a specific product and are referring to a specific version of the product.

=== Documentation components

NOTE: These branches store the latest or WIP versions of each component

* `docs-sdk`
* `docs-core`
* `docs-protocol`
* `docs-service`

=== Previous versions

* `docs-COMPONENT-1.2.3`
+
where

** `COMPONENT` can be either `sdk`, `core`, `protocol` or `service`.
** `1.2.3` represents the respective version number of the corresponding product.

== UI branches

The presentation of the documentation is stored completely separate form the actual content.
It's stored on the `antora` branch.

== The build branch
The `build` branch stores

* the `site.yml` file, which is used to generate the Lisk Documentation using Antora.
* The `searchdocs` folder, for creating the search index

