= Previewing the docs locally
:toc: preamble
:url_webstorm_asciidoc: https://plugins.jetbrains.com/plugin/7391-asciidoc
:url_antora_install: https://docs.antora.org/antora/latest/install-and-run-quickstart/

To verify the correct presentation of the changed content, the docs can be previewed locally by compiling them with Antora.

== Previewing content changes

=== In the editor

Many IDEs support preview of AsciiDoc files.

==== WebStorm

Install the AsciiDoc plugin: {url_webstorm_asciidoc}[^]

=== In browser

==== Navigate into the `build/` folder

 cd lisk-docs/build

==== Create a new folder

 mkdir local

==== Install Antora

 npm i -g @antora/cli@3.0.0 @antora/site-generator@3.0.0

TIP: See {url_antora_install}[^] for more information about how to install Antora.

==== Run local playbook

 antora preview-site.yml --fetch

==== Preview in browser

open local/index.html

== Previewing UI changes

. Navigate to the `ui/` folder
 cd lisk-docs/ui
. Start the local preview
 gulp preview

Open http://localhost:5252/ in the browser.

NOTE: Any changes in the UI source code will reflect directly in the browser.

