= Previewing the docs locally
:toc: preamble
// URLs
:url_webstorm_asciidoc: https://plugins.jetbrains.com/plugin/7391-asciidoc
// Project URLs
:url_ui_preview: ui.adoc#ui-preview

To verify the correct presentation of the modified content, the docs can be previewed locally by compiling them with Antora.

== Previewing content changes

=== In the editor

Many IDEs support the preview of AsciiDoc files.

==== WebStorm

Install the AsciiDoc plugin: {url_webstorm_asciidoc}[^]

=== In browser

==== Navigate into the `build/` folder

 cd lisk-docs/build

==== Create a new folder

 mkdir local

==== Run local playbook

 antora preview-site.yml --fetch

==== Preview in browser

 open local/index.html

== Previewing UI changes

. Navigate to the `ui/` folder
+
 cd lisk-docs/ui

. Start the local preview
+
 gulp preview

Open http://localhost:5252/ in the browser.

NOTE: Any changes in the UI source code will be directly reflected in the browser.

TIP: See xref:{url_ui_preview}[UI preview] for more information.

