= Releasing new versions

//(easiest to make an example here, for example 3.x to 4.x release of the sdk docs)


== Preparing the new docs

* Learn about the upcoming changes by reading the changelog, looking at the github repo, the projects and the code.
* Create a new project on lisk-docs for the new version, title: component + version, description: follow the existing examples
* Create issues for all upcoming content changes in the docs and add them to the project.

=== Major release

Create a new branch `docs-PRODUCT-x.y.z`, on the base of `docs_PRODUCT`, where `PRODUCT` can be `sdk`, `service`, `protocol` or `service`, and `x.y.z` is equal to the now outdated product version.
Like the version number indicates, this branch will store the docs that become outdated with the new release.

The branch `docs_PRODUCT` will be used as base for the new documentation.
To do so, bump the `version` in `antora.yml`:

[source,yaml]
----
name: lisk-sdk
title: Lisk SDK
version: '4.0.0' <1>
display_version: '4.0.0' <2>
start_page: ROOT:index.adoc
nav:
- modules/ROOT/nav.adoc
----

<1> Bump to the latest version
<2> Change from `master` to the new version.
This will be updated again as one of the last steps before the new docs release.

=== Minor + Patch releases

Use the same branch, make the content updates, and bump the version in `antora.yml`


