= Deploying the documentation on staging
// External URLs
:url_docs_staging: https://liskhq.github.io/lisk-docs
// Project URLs
:url_structure: structure.adoc

== Setup

=== Prerequisites

- Node.js v12
- Checkout the `build` branch
- Setup the working environment like described in xref:{url_structure}[]

=== Antora installation

 npm install --global @antora/cli@2.3 @antora/site-generator-default@2.3

=== Algolia credentials

How to include the aloglia search box in the UI when building the documentation:

. Create a file with the Algolia API credentials inside of the `antora/` folder.
 touch antora/.env
. Ask for the Algolia credentails and insert them into `antora/.env`

== The playbook file

.Example content of `site.yml`
[source,yaml]
----
site:
  title: Lisk documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://lisk.com/documentation
  start_page: ROOT::index.adoc
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    imagesdir: ~
    idprefix: ''
    idseparator: '-'
    page-pagination: true
  extensions:
  - ./lib/tabs-block/extension.js
content:
  sources:
  - url: https://github.com/LiskHQ/lisk-docs.git
    branches: [1417-overview-pages, 1417-move-apis, docs-core, docs-sdk-4.0.0, docs-sdk-3.0.2, docs-core-v2, docs-manual]
  - url: https://github.com/LiskHQ/lisk-docs.git
    branches: [ 1364-landing-page ]
    start_path: docs
ui:
  bundle:
#    url: https://github.com/LiskHQ/lisk-docs/raw/dev-antora/build/ui-bundle.zip
   url: ../ui/build/ui-bundle.zip
   snapshot: true
output:
  dir: ./git-page


----

<1> All branch names listed under the `branches` key will be used by Antora to build the documentation content.
<2> Defines the UI bundle that will be used by Antora to build the documentation.
<3> Defines the output directory for the generated HTML files of the documentation.

== Building the new staging documentation with Antora

.On the `build` branch
[source,bash]
----
source antora/.env
antora site.yml --fetch
cd master
git status
git add .
git commit -m "Update docs"
git push origin master
----

Once pushed to `master`, the content will be automatically applied under {url_docs_staging}.
