= Repository structure and workflow
// External URLs
:url_github_docs: git@github.com:LiskHQ/lisk-docs.git
:url_git_worktree: https://git-scm.com/docs/git-worktree
// Project URLs

It is highly recommended to use git worktrees when working with the Lisk documentation.

This allows to conveniently work on different content branches and to deploy the docs on the go, without having to switch branches all the time.

== Setting up the working environment for the first time

=== Working with git worktrees

Git `worktree` allows to have checked out multiple branches of one repository.
Each branch is stored in folder with a name analog to the branch name.

[subs=attributes+]
```
git clone {url_github_docs}
cd lisk-docs
git checkout build
git worktree add dev-antora dev-antora
git worktree add antora antora
git worktree add docs-sdk docs-sdk
git worktree add docs-service docs-service
git worktree add docs-core docs-core
```

After setting up the worktree, the build branch should have several new folder and should look similar to this:

----
tree -L 1 -I 'node_modules'
.
├── antora <1>
├── dev-antora <2>
├── docs-core <3>
├── docs-sdk <4>
├── docs-service <5>
├── lib <6>
├── searchdocs-scraper <7>
├── master <8>
├── live <9>
├── live-site.yml <10>
└── site.yml <11>
----

<1> Stores the `antora` branch (UI)
<2> Stores the `dev-antora` branch (UI)
<3> Stores the `docs-core` branch (Content)
<4> Stores the `docs-sdk` branch (Content)
<5> Stores the `docs-service` branch (Content)
<6> Stores the extentions for Antora, which are used in the playbook files.
<7> Contains all files relates to the algolia docs scraper
<8> Stores the `master` branch, which hold the staging documentation (HTML)
<9> Stores the `live` branch, which hold the production documentation (HTML)
<10> The playbook file for the production documentation
<11> The playbook file for the staging documentation

More information about `git worktree` can be found in the {url_git_worktree}[Git documentation reference^].
