= Repository structure and workflow
:hide-uri-scheme:
:idprefix:
:toc:
// External URLs:
:url_github_docs: git@github.com:LiskHQ/lisk-docs.git
:url_git_worktree: https://git-scm.com/docs/git-worktree
:url_antora: https://antora.org/
:url_antora_docs: https://docs.antora.org/antora/2.3/standard-directories/#hierarchy-and-reserved-names
:url_docs: https://lisk.io/documentation
:url_docs_staging: https://liskhq.github.io/lisk-docs
:url_github_docs: https://github.com/LiskHQ/lisk-docs
:url_gitlab_antora_extensions: https://gitlab.com/antora/antora-asciidoctor-extensions
// Project URLs:
:url_contributing: contributing.adoc
:url_search: search.adoc
:url_staging: staging.adoc
:url_structure: structure.adoc

Lisk uses {url_antora}[Antora^] as a documentation generator.

All files for the Lisk documentation are stored in the GitHub repository at {url_github_docs}[^].

== Environments

=== Staging

The testing and WIP environment for the Lisk documentation.
Link to the WIP Lisk documentation: {url_docs_staging}.

Stored in the `development` branch.

=== Production

The official and public location of the Lisk documentation.
Link to the production version of the Lisk documentation: {url_docs}.

Stored in the `main` branch.

== Content branches

All content branches store the documentation for a specific product and are referring to a specific version of the product.

TIP: Learn more about the structure of Antora content branches: {url_antora_docs}.

=== Documentation components

NOTE: These branches store the latest or WIP versions of each component.

* `docs-sdk`
* `docs-core`
* `docs-protocol`
* `docs-service`

=== Previous versions

* `docs-COMPONENT-1.2.3`
+
where

** `COMPONENT` can be either `sdk`, `core`, `protocol` or `service`.
** `1.2.3` represents the respective version number of the corresponding product.

=== Structure

== UI branches

The presentation of the documentation is stored completely separate from the actual content.

* `dev-antora`: This branch stores the Lisk docs UI used in development.
It is used in the staging environment.
* `antora`: This branch stores the Lisk docs UI used in production.
It is used in the production environment.

== The build branch
The `build` branch stores...

* ...the `site.yml` file, which is used to generate the Lisk documentation using Antora.
* ...the `searchdocs-scraper` folder, for creating the search index.
* ...the `lib` folder, which stores the <<Asciidoc extensions>>, that are used in the Lisk documentation.

NOTE: More information under xref:{url_structure}[], xref:{url_staging}[] and xref:{url_search}[].

=== Asciidoc extensions

The following Asciidoc extension is currently used:

Tabs::
A clone of {url_gitlab_antora_extensions}.
+
.How to create 2 tabs in Asciidoc
[source,asciidoc]
----
[tabs]
=====
Tab1 title::
+
--
Tab1 content
--
Tab2 title::
+
--
Tab2 content
--
=====
----


== Working with git worktrees

It is highly recommended to use git worktrees when working with the Lisk documentation.

This provides the option to conveniently work on different content branches and to easily deploy the docs simultaneously, without having to switch branches all the time.

Git `worktree` offers the possibility to check out multiple branches of one repository.
Each branch is stored in a folder with a name analog to the branch name.

[subs=attributes+]
```
git clone {url_github_docs}
cd lisk-docs
git checkout build
git worktree add dev-antora dev-antora
git worktree add antora antora
git worktree add docs-sdk docs-sdk
git worktree add docs-service docs-service
git worktree add docs-core docs-core
```

After setting up the worktree, the `build` branch should have several new folders, and should look similar to the structure shown below:

----
tree -L 1 -I 'node_modules'
.
├── antora <1>
├── dev-antora <2>
├── docs-core <3>
├── docs-sdk <4>
├── docs-service <5>
├── lib <6>
├── searchdocs-scraper <7>
├── master <8>
├── live <9>
├── live-site.yml <10>
└── site.yml <11>
----

<1> Stores the `antora` branch (UI).
<2> Stores the `dev-antora` branch (UI).
<3> Stores the `docs-core` branch (Content).
<4> Stores the `docs-sdk` branch (Content).
<5> Stores the `docs-service` branch (Content).
<6> Stores the extentions for Antora, which are used in the playbook files.
<7> Contains all files relates to the algolia docs scraper.
<8> Stores the `master` branch, which holds the staging documentation (HTML).
<9> Stores the `live` branch, which holds the production documentation (HTML).
<10> The playbook file for the production documentation.
<11> The playbook file for the staging documentation.

More information about `git worktree` can be found in the {url_git_worktree}[Git documentation reference^].
