= Repository structure and workflow
:hide-uri-scheme:
:idprefix:
:toc: preamble
// External URLs:
:url_antora_ui: https://gitlab.com/antora/antora-ui-default
:url_antora_ui_docs: https://docs.antora.org/antora-ui-default/
:url_github_docs: git@github.com:LiskHQ/lisk-docs.git
:url_antora: https://antora.org/
:url_antora_directories: https://docs.antora.org/antora/latest/standard-directories/
:url_docs: https://lisk.com/documentation
:url_docs_staging: https://staginglisk.com/documentation
:url_docs_gitpage: https://liskhq.github.io/lisk-docs
:url_github_docs: https://github.com/LiskHQ/lisk-docs
:url_gitlab_antora_extensions: https://gitlab.com/antora/antora-asciidoctor-extensions
:url_jenkins_build: https://deployment.liskdev.net/job/lisk-docs-build/
:url_jenkins_staging: https://deployment.liskdev.net/job/lisk-docs-deploy-staging/
:url_jenkins_production: https://deployment.liskdev.net/job/lisk-docs-deploy-production/
// Project URLs:
:url_contributing: contributing.adoc
:url_search: search.adoc
:url_staging: git-hub-pages.adoc
:url_structure: structure.adoc
:url_staging_playbook: {url_staging}#the-playbook-file
:url_style_asciidoc: styleguide:asciidoc.adoc

Lisk uses {url_antora}[Antora^] as a documentation generator.

All files for the Lisk documentation are stored in the GitHub repository at {url_github_docs}[^].

== Environments

=== GitHub Pages

The testing and WIP environment for the Lisk documentation.
Link to the WIP Lisk documentation: {url_docs_gitpage}.

* Source content is stored in the `development` branch.
* Compiled files are stored in the `git-page` branch.

=== Staging
The staging environment mirrors the production version of the website.
Link to the production version of the Lisk documentation: {url_docs_staging}.

Documentation is deployed on staging before deploying on <<production>>, to verify the latest updates of the documentation.

* Source content is stored in the `main` branch.
* Compiled files are stored in the `live` branch.

==== Deployment
* Task for compiling a new version of the Lisk documentation: {url_jenkins_build}[^]
* Task for deploying the latest docs on staging.lisk.com: {url_jenkins_staging}[^]

IMPORTANT: For accessing Jenkins, you need to connect to the lightcurve network via VPN, if you are not in the office.

=== Production

The official and public location of the Lisk documentation.
Link to the production version of the Lisk documentation: {url_docs}.

* Source content is stored in the `main` branch.
* Compiled files are stored in the `live` branch.

==== Deployment
* Task for compiling a new version of the Lisk documentation: {url_jenkins_build}[^]
* Task for deploying the latest docs on staging.lisk.com: {url_jenkins_production}[^]

IMPORTANT: For accessing Jenkins, you need to connect to the lightcurve network via VPN, if you are not in the office.

== Structure

The internal structure of `development` and `main` branch.

=== The `docs/` folder

The source content for the general Lisk documentation  is located in the `docs/` folder.

The file structure follows the expected structure for Antora documentation, see: {url_antora_directories}.

All content is written in xref:{url_style_asciidoc}[AsciiDoc].

=== The `ui/` folder

The presentation of the documentation is stored completely separate from the actual content.

The UI is based on the {url_antora_ui}[Antora default UI^] (see also {url_antora_ui_docs}[^]).

It is customized in the following regards:

* Updated the CSS to follow improve UX and follow Lisk brand styleguide.
* Added additional features, like:
** Algolia site search
** Dark theme
** Zoom for images
** Additional layout for swagger UI
** Tab-blocks
** ...

=== The `build/` folder
The `build` folder contains...

* ...the `site.yml` file, which is used to generate the Lisk documentation using Antora.
* ...the `searchdocs-scraper` folder, for creating the search index.
* ...the `lib` folder, which stores the <<Asciidoc extensions>>, that are used in the Lisk documentation.

----
.
├── lib/ <1>
├── searchdocs-scraper/ <2>
├── live-site.yml <3>
└── site.yml <4>
----

<1> The `lib/` folder contains extensions for Antora.
The extensions are specified in the xref:{url_staging_playbook}[playbook] file of Antora.
<2> The `searchdocs-scraper/` folder contains the file required to update the Algolia xref:{url_search}[search index] of the documentation.
<3> The playbook used to compile the live documentation on {url_docs}[^] with Antora.
Results are pushed to the `live` branch.
<4> The playbook used to compile the documentation at {url_docs_gitpage}[^] with Antora.
Results are pushed to the `git-page` branch.

== Product-specific docs

There are additional content sources, which each store the documentation for a specific software product of Lisk.

=== Content sources

NOTE: These branches store the latest or WIP versions of each component.

* `docs-sdk`
* `docs-core`
* `docs-service`

=== Previous versions

* `docs-COMPONENT-v1`
+
where

** `COMPONENT` can be either `sdk`, `core` or `service`.
** `v1` represents the respective version number of the corresponding product.


== Antora & AsciiDoc

=== Asciidoc extensions

The following Asciidoc extension is currently used:

Tabs::
A clone of {url_gitlab_antora_extensions}.
+
.How to create 2 tabs in Asciidoc
[source,asciidoc]
----
[tabs]
=====
Tab1 title::
+
--
Tab1 content
--
Tab2 title::
+
--
Tab2 content
--
=====
----

