= Lisk Commander Documentation Overview
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:imagesdir: ../assets/images

Lisk Commander is a Command Line Interface tool designed to be a low entry point and the most convenient tool for developers who are looking for an efficient way of coding.

*Who is Lisk Commander for?*

* Delegates
* Node operators
* Contributors to the Lisk codebase
* Developers using Lisk’s infrastructure
* Anyone interested in making use of Lisk’s functionality from the command line with ease

Lisk Commander allows communication with a remote or local node and carry out Lisk-related functionality.

*What can I do with Lisk Commander?*

* Create a transaction
* Decrypt/encrypt passphrases or messages
* Install and manage a node
* Create accounts
* Get delegates
* And many more! xref:lisk-commander/user-guide/commands.adoc[View all commands]

== Setup

NOTE: Supported Platforms: Platforms with NodeJS versions 8.3 and above.

=== Pre-Installation

Lisk Commander requires https://nodejs.org/[Node.js] as the underlying engine for code execution.

==== Install Node

Node.js is supported on most operating systems.
Follow the instructions for your operating system on the https://nodejs.org/en/download/[Node.js downloads page].
Lisk-Commander requires Node.js versions 8.3 or above.

NPM is automatically installed along with Node.js.

===== Verify Node installation

Confirm that Node.js and NPM have been successfully installed by running:

[source,bash]
----
node --version
npm --version
----

=== Installation

To install the latest version of Lisk Commander as a global command, install the NPM package like so:

[source,bash]
----
npm install --global --production lisk-commander
----

Upon successful completion, NPM will add the Lisk Commander executable to your PATH.

To see usage examples and configuration options, check the xref:lisk-commander/user-guide.adoc[Lisk Commander User Guide].
For a full reference of all commands and their available options, check the xref:lisk-commander/user-guide/commands.adoc[Command Reference].

== Upgrade

To update your global installation to the latest version of Lisk Commander, simply run the following command:

[source,bash]
----
npm update --global lisk-commander
----

== Contribute to the Codebase

Everyone is invited to contribute to the Lisk Commander codebase.
We welcome and appreciate all contributions.

=== Github

All necessary information can be found on our https://github.com/LiskHQ/lisk-sdk/tree/development/commander[Lisk Commander Github].

=== Contribution Guidelines

Please be sure to read and follow our https://github.com/LiskHQ/lisk-sdk/blob/development/docs/CONTRIBUTING.md[Contribution Guidelines].

=== Discord

If you have any further questions please join our https://lisk.chat/[Lisk Discord] channel.
