= Delegated Proof of Stake (DPoS) in Lisk
Mona Bärenfänger <mona@lightcurve.io>
:description: This section provides an overview of the main guides in chronological order, together with an example using the 'Hello World' App.
:toc:
:imagesdir: ../../../assets/images
:v_protocol: master

:url_bitcoin_wiki_dpos: https://en.bitcoinwiki.org/wiki/DPoS
:url_wiki_pos: https://en.wikipedia.org/wiki/Proof_of_stake

:url_protocol_delegate_selection: {v_protocol}@lisk-protocol::consensus-algorithm.html#delegate_selection

The Lisk SDK bootstraps a blockchain network that is based on the xref:{url_bitcoin_wiki_dpos}[DPoS^] consensus algorithm.

DPoS is related to the {url_wiki_pos}[Proof of Stake (PoS)^] consensus algorithm.
In PoS-based blockchains the creator of the next block is chosen via various combinations of random selection and wealth or age (i.e., the stake).

In DPoS based blockchains, the consensus about who can forge the next block is reached by users who vote with their stake for other users.

In order to receive votes from other users, a user needs to register their account as <<delegates, delgate>>.

== How new blocks are added to the blockchain

The process of adding new blocks to a blockchain that uses the PoS or DPoS consensus algorithm is called forging.

The process of forging hardly consumes any energy and is therefore an extremely energy-friendly consensus algorithm compared to "mining", which is the analog process for blockchains that run with Proof of Work (PoW).

=== Delegate selection

All accounts in the network can use their tokens to vote for one or multiple delegates.
The delegates are ranked after their accumulated vote weight in a descending order.
This ranking list defines the delegates who are allowed to forge new blocks.
Each forging round, the top 101 delegates and 2 randomly selected standby delegates will forge blocks one after another.

More information about the xref:{url_protocol_delegate_selection}[delegate selection mechanism] can be found in the Lisk Protocol.

=== Forging rounds

The forging spots are predefined in forging rounds by the voting mechanism.
This allows a very energy efficient process of adding new blocks, that enables to run forging nodes on very weak machines, like a Raspberry Pi.

....
103(Number of blocks of a forging round) = 101(amount of the forging delegates) + 2(random standby delegates)
....

[NOTE]
====
The ranked list of the delegates with the highest accumulated vote weight and the order in which the delegates forge new blocks is calculated newly each round.
During a forging round, no new calculations need to be done, which makes the process so efficient.
====

== The voting mechanism

Accounts can vote for delegates by locking tokens in their account.

Lets assume a user holds an account with a balance of 100 tokens.

The user can now decide if and how they want to use their balance to vote for one or multiple delegates.

[source,js]
----
votes = [
    { delegateAddress:'11750255083444888021L', amount: '1000000000'}, // locks 10 tokens
    { delegateAddress:'64373847834494888026L', amount: '3000000000'} // locks 30 tokens
]
----

[[delegates]]
=== Delegates

Forging delegates::
top 101
Standby delegates::
xyz

=== Becoming a delegate

=== Voting for a delegate

== BFT

