= Lisk modules
Mona Bärenfänger <mona@lightcurve.io>
//Settings
:toc:
:v_core: 3.0.0
:imagesdir: ../../assets/images
//External URLs
:url_github_dpos: https://github.com/LiskHQ/lisk-sdk/tree/v5.0.0-alpha.3/framework/src/modules/dpos
:url_github_keys: https://github.com/LiskHQ/lisk-sdk/tree/v5.0.0-alpha.3/framework/src/modules/keys
:url_github_sequence: https://github.com/LiskHQ/lisk-sdk/tree/v5.0.0-alpha.3/framework/src/modules/sequence
:url_github_token: https://github.com/LiskHQ/lisk-sdk/tree/v5.0.0-alpha.3/framework/src/modules/token
// Project URLs
:url_references_framework_basemodule: references/lisk-framework/index.adoc#the-basemodule
:url_references_framework_baseasset: references/lisk-framework/index.adoc#the-baseasset

== What is a custom module?

Custom modules bundle block processing logic and transaction processing logic together with a specific account schema.
Each custom module is separated based on the domain and data which the account schema contains.

They are responsible for the state machine part of the blockchain logic.
The state machine validates and updates the information on either account state or chain state.
Those state changes can be introduced through a block header or a transaction.

Each custom module defines its own data.
If a module is required to interact with other data which is managed by another module, it should communicate through the functions exposed by other modules.


=== Custom assets

//TODO

== When to create a module

The module and asset are used to provide features to...

* define data stored in blockchain
* define data sent through transaction asset
* define logic which is executed per block
* define logic which is executed per transaction
* define logic which is executed per asset

Also, all of the logic implemented using a module / asset must be “deterministic” and executable within block time.

== SDK default modules

[cols="30,70",options="header",stripes="hover"]
|===
|Name
|Description

|{url_github_dpos}[DPoS module^]
a|
The DPoS module is responsible for handling all DPoS related logics.
Specifically:

* Snapshotting vote weights
* Calculating productivity
* Handling registerDelegate, voteDelegate, unlockToken and reportDelegateMisbehavior transaction assets
* Setting the next delegates set

|{url_github_keys}[Keys module^]
a|
The Keys module handles all logic related to the signatures.

It should verify the signatures based on the multi-signature rules including non-multi-signature accounts.
It also handles the registration of multi-signature accounts.


|{url_github_sequence}[Sequence module^]
a|
The Sequence module handles all logic related to nonce.

It should verify the nonce for all transactions and increment if valid.

|{url_github_token}[Token module^]
a|
The Token module handles all logic related to balance.
Specifically:

* Validating and subtracting fees for all transactions
* Checking the minimum remaining balance requirement
* Giving block rewards to the block generator
* Transferring account balances
|===

== Life cycle of a block

. Receive block
. Apply fork choice rule
. Validate block
.. Validate transactions
... Validate transaction
... *Validate transaction asset*
. Verify block header
. Before block apply
. *Apply block*
.. Apply transactions
... *beforeTransactionApply*
... *Apply asset*
... *afterTransactionApply*
. *After block apply*
. Save block and updated states

The *bold* steps are the steps exposed via the base module and base asset, see the xref:{url_references_framework_basemodule}[Lisk Framework reference].

== How to create module with an asset

The module and asset must extend the base module and base asset defined in the Lisk SDK.

NOTE: The interfaces for `BaseModule` and `BaseAsset` are described in the xref:{url_references_framework_basemodule}[Lisk Framework reference].

For the asset, the following properties are required:

* `name` is used for UI purpose.
* `id` is used for `AssetID` to send a transaction.
* `schema` defines `asset` schema in a transaction.
* `apply` defines a state change induced by this asset.

.custom_asset.ts
[source,typescript]
----
const {
    BaseAsset,
    ValidationError,
    codec
} = require('lisk-sdk');
const {
    helloCounterSchema,
    CHAIN_STATE_HELLO_COUNTER
} = require('./schemas');

export class HelloAsset extends BaseAsset { <1>
    name = 'helloAsset';
    id = 0;
    schema = {
        $id: '/hello/asset',
        type: 'object',
        required: ["hello"],
        properties: {
            hello: {
                dataType: 'string',
                fieldNumber: 1,
            },
        },
    };

    validate({asset}) { <2>
        if (!asset.hello || typeof asset.hello !== 'string' || asset.hello.length > 64) {
            throw new ValidationError(
                'Invalid "asset.hello" defined on transaction: A string value no longer than 64 characters is expected',
                asset.hello,
            );
        }
    };

    async apply({ asset, stateStore, reducerHandler, transaction }) { <3>
        const senderAddress = transaction.senderAddress;
        const senderAccount = await stateStore.account.get(senderAddress);


        senderAccount.hello = asset.hello;
        stateStore.account.set(senderAccount.address, senderAccount);

        let counter = await stateStore.chain.get(
            CHAIN_STATE_HELLO_COUNTER
        );

        await stateStore.chain.set(
            CHAIN_STATE_HELLO_COUNTER,
            codec.encode(helloCounterSchema, ++counter)
        );
    }
}
----

<1> description
<2> description
<3> description

For a custom module, the following properties are required:

* `name` will be used for a key of the account schema if defined.
* `id` will be used for a fieldNumber for the account schema, and for a `moduleID` to send a transaction with the `CustomAsset`.

.custom_module.ts
[source,typescript]
----
import { CustomAsset } from './custom_asset';
import {
	TransactionApplyContext,
	AfterBlockApplyContext,
	BeforeBlockApplyContext,
	AfterGenesisBlockApplyContext,
} from '../types';

export class CustomModule extends BaseModule {
  name = 'customModule'; <1>
  id = 1001; <2>
  accountSchema = {
    type: 'object',
    properties: {
      latestData: {
        fieldNumber: 1,
        dataType: 'string',
      },
    },
    default: {
      latestData: 'initial data',
    },
  };
  transactionAssets: [new CustomAsset()];
  actions = {
    someAction: async () => {
        return this.id
    },
  };
  events = ['someEvent','anotherEvent'];
  reducers = {};
  beforeTransactionApply(context: TransactionApplyContext): Promise<void> {
    // Code in here is applied before a transaction is applied.
    this._channel.publish();
  };
  afterTransactionApply(context: TransactionApplyContext): Promise<void> {
    // Code in here is applied after a transaction is applied.
  };
  afterGenesisBlockApply(context: AfterGenesisBlockApplyContext): Promise<void> {
    // Code in here is applied after a genesis block is applied.
  };
  beforeBlockApply(context: BeforeBlockApplyContext): Promise<void> {
    // Code in here is applied before a block is applied.
  }
  afterBlockApply(context: AfterBlockApplyContext): Promise<void> {
    // Code in here is applied after a block is applied.
  }
}
----
