= Modules
Mona Bärenfänger <mona@lightcurve.io>
//Settings
:toc: preamble
:v_core: 3.0.0
:imagesdir: ../../assets/images
// Project URLs
:url_references_framework_basemodule: references/framework/index.adoc#the-basemodule
:url_references_framework_baseasset: references/framework/index.adoc#the-baseasset

== Default modules

=== Token module



[cols="30,70",options="header",stripes="hover"]
|===
|Name
|Description

|xref:{}[Token module]
a|
The Token module handles all logic related to balance.
Specifically:

* Validating and subtracting fees for all transactions
* Checking the minimum remaining balance requirement
* Giving block rewards to the block generator
* Transferring account balances

|xref:{}[Sequence module]
a|
The Sequence module handles all logic related to nonce.

It should verify the nonce for all transactions and increment if valid.

|xref:{}[Keys module]
a|
The Keys module handles all logic related to the signatures.

It should verify the signatures based on the multi-signature rules including non-multi-signature accounts.
It also handles the registration of multi-signature accounts.

|xref:{}[DPoS module]
a|
The DPoS module is responsible for handling all DPoS related logics.
Specifically:

* Snapshotting vote weights
* Calculating productivity
* Handling registerDelegate, voteDelegate, unlockToken and reportDelegateMisbehavior transaction assets
* Setting the next delegates set
|===

== When to create a custom module / custom asset

The Custom module and custom asset are used to provide features to...

* define data stored in blockchain
* define data sent through transaction asset
* define logic which is executed per block
* define logic which is executed per transaction
* define logic which is executed per asset

Also, all of the logic implemented using a custom module / asset must be “deterministic” and executable within block time.

== What is a custom module and a custom asset?

Custom modules bundle block processing logic and transaction processing logic together with a specific account schema.
Each custom module is separated based on the domain and data which the account schema contains.

They are responsible for the state machine part of the blockchain logic.
The state machine validates and updates the information on either account state or chain state.
Those state changes can be introduced through a block header or a transaction.

Each custom module defines its own data.
If a module is required to interact with other data which is managed by another module, it should communicate through the functions exposed by other modules.

== How to create custom module with a custom asset

The custom module and asset must extend the `BaseModule` and `BaseAsset` defined in the Lisk SDK.

The interfaces for `BaseModule` and `BaseAsset` are described in the xref:{url_references_framework_basemodule}[Lisk Framework reference].

For a custom asset, the following properties are required:

* `name` is used for UI purpose.
* `Id` is used for `AssetID` to send a transaction.
* `Schema` defines `asset` schema in a transaction.
* `Apply` defines a state change induced by this asset.

.custom_asset.ts
[source,typescript]
----
interface Asset {
  Data: string;
}
export class CustomAsset extends BaseAsset {
  public name = 'executeCustomAsset';
  public id = 0;
  public schema = {
    $id: '/customAsset',
    type: 'object',
    properties: {
      data: {
        dataType: 'string',
        fieldNumber: 1,
      },
    },
  };

  public apply(context: ApplyAssetContext<Asset>): Promise<void> {
    // do something
  }
}
----

For a custom module, the following properties are required:

* `name` will be used for a key for the account schema if defined.
* `id` will be used for a fieldNumber for the account schema, and for a `moduleID` to send a transaction with `CustomAsset`.

.custom_module.ts
[source,typescript]
----
import { CustomAsset } from './custom_asset';

export class CustomModule extends BaseModule {
  public name = 'customModule';
  public id = 1001;
  public accountSchema = {
    type: 'object',
    properties: {
      latestData: {
        fieldNumber: 1,
        dataType: 'string',
      },
    },
    default: {
      latestData: 'initial data',
    },
  };
  public transactionAssets: [new CustomAsset()];
  public afterBlockApply(context: AfterBlockApplyContext): Promise<void> {
    // do something after block is applied
  }
}
----

== Life cycle of a block

. Receive block
. Apply fork choice rule
. Validate block
.. Validate transactions
... Validate transaction
... *Validate transaction asset*
. Verify block header
. Before block apply
. *Apply block*
.. Apply transactions
... *beforeTransactionApply*
... *Apply asset*
... *afterTransactionApply*
. *After block apply*
. Save block and updated states

The *bold* steps are the steps exposed through the base module and base asset.
