= Custom Plugin interface
Mona Bärenfänger <mona@lightcurve.io>
//Settings
:toc: preamble
:v_core: 3.0.0
:imagesdir: ../../assets/images
// Project URLs
:url_references_framework_baseplugin: references/framework/index.adoc#the-baseplugin

== When to create a plugin

The Custom plugin is used to provide features to provide...

* a function to aggregate the blockchain data.
* automation to the blockchain logic, such as automatically seeding transactions.
* search capabilities for the blockchain data.
* proxy to the application interfaces.

== Plugin interface

All custom plugins must extend BasePlugin exposed by SDK.
All plugins and the application can interact with each other by using a channel.
Each plugin is given one channel through the “load” function as shown below.

== How to create a custom plugin

The interface for the `BasePlugin` is described in the xref:{url_references_framework_basemodule}[Lisk Framework reference].


[source,js]
----
export class MyPlugin extends BasePlugin {
    static get alias(){ return 'pluginAlias'; },

    static get info(){
        return {
            author: '',
            version: '',
            name: '',
        };
    },

    private _knownTimestamps: number[] = [];

    async load(channel: Channel): Promise<void> {
      // initialize plugin
      if (this.options.enable) {
        return false;
      }
      channel.subscribe('app:block:new', ({ data }) => {
        const decodedBlock = this.codec.decodeBlock(data.block);
        this.knownTimestamp.push(decodedBlock.header.timestamp);
        channel.publish('timestamp', { timestamp: decodedBlock.header.timestamp });
      });
    }

    get defaults() {
      return {
        type: 'object',
        properties: {
          enable: {
            type: 'boolean',
          }
        },
      }
    }

    get events() {
      return ['timestamp'];
    }

    get actions() {
        return {
           getKnownTimestamp: () => this._knownTimestamps;
        }
    }

    async unload() {
      this._knownTimestamps = [];
    }
};

----
