{empty}[@liskhq/lisk-api-client](../README.md) ›
link:accountsresource.md[AccountsResource]

== Class: AccountsResource

=== Hierarchy

* APIResource
+
↳ *AccountsResource*

=== Index

==== Constructors

* link:accountsresource.md#constructor[constructor]

==== Properties

* link:accountsresource.md#apiclient[apiClient]
* link:accountsresource.md#get[get]
* link:accountsresource.md#getmultisignaturegroups[getMultisignatureGroups]
* link:accountsresource.md#getmultisignaturememberships[getMultisignatureMemberships]
* link:accountsresource.md#path[path]

==== Accessors

* link:accountsresource.md#headers[headers]
* link:accountsresource.md#resourcepath[resourcePath]

==== Methods

* link:accountsresource.md#handleretry[handleRetry]
* link:accountsresource.md#request[request]

=== Constructors

==== constructor

+ *new AccountsResource*(`+apiClient+`: link:apiclient.md[APIClient]):
_link:accountsresource.md[AccountsResource]_

_Overrides void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/accounts.ts#L25[resources/accounts.ts:25]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+apiClient+` |link:apiclient.md[APIClient]
|===

*Returns:* _link:accountsresource.md[AccountsResource]_

=== Properties

==== apiClient

• *apiClient*: _link:apiclient.md[APIClient]_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L26[api_resource.ts:26]_

'''''

==== get

• *get*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/accounts.ts#L22[resources/accounts.ts:22]_

'''''

==== getMultisignatureGroups

• *getMultisignatureGroups*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/accounts.ts#L23[resources/accounts.ts:23]_

'''''

==== getMultisignatureMemberships

• *getMultisignatureMemberships*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/accounts.ts#L24[resources/accounts.ts:24]_

'''''

==== path

• *path*: _string_

_Overrides void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/accounts.ts#L25[resources/accounts.ts:25]_

=== Accessors

==== headers

• *get headers*(): _HashMap_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L34[api_resource.ts:34]_

*Returns:* _HashMap_

'''''

==== resourcePath

• *get resourcePath*(): _string_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L38[api_resource.ts:38]_

*Returns:* _string_

=== Methods

==== handleRetry

▸ *handleRetry*(`+error+`: Error, `+req+`: AxiosRequestConfig,
`+retryCount+`: number): _Promise‹APIResponse›_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L42[api_resource.ts:42]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+error+` |Error
|`+req+` |AxiosRequestConfig
|`+retryCount+` |number
|===

*Returns:* _Promise‹APIResponse›_

'''''

==== request

▸ *request*(`+req+`: AxiosRequestConfig, `+retry+`: boolean,
`+retryCount+`: number): _Promise‹APIResponse›_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L67[api_resource.ts:67]_

*Parameters:*

[cols=",,",options="header",]
|===
|Name |Type |Default
|`+req+` |AxiosRequestConfig |-
|`+retry+` |boolean |-
|`+retryCount+` |number |1
|===

*Returns:* _Promise‹APIResponse›_
