{empty}[@liskhq/lisk-api-client](../README.md) ›
link:apiclient.md[APIClient]

== Class: APIClient

=== Hierarchy

* *APIClient*

=== Index

==== Constructors

* link:apiclient.md#constructor[constructor]

==== Properties

* link:apiclient.md#accounts[accounts]
* link:apiclient.md#bannednodes[bannedNodes]
* link:apiclient.md#blocks[blocks]
* link:apiclient.md#currentnode[currentNode]
* link:apiclient.md#dapps[dapps]
* link:apiclient.md#delegates[delegates]
* link:apiclient.md#headers[headers]
* link:apiclient.md#node[node]
* link:apiclient.md#nodes[nodes]
* link:apiclient.md#peers[peers]
* link:apiclient.md#randomizenodes[randomizeNodes]
* link:apiclient.md#signatures[signatures]
* link:apiclient.md#transactions[transactions]
* link:apiclient.md#voters[voters]
* link:apiclient.md#votes[votes]

==== Accessors

* link:apiclient.md#static-constants[constants]

==== Methods

* link:apiclient.md#banactivenode[banActiveNode]
* link:apiclient.md#banactivenodeandselect[banActiveNodeAndSelect]
* link:apiclient.md#bannode[banNode]
* link:apiclient.md#getnewnode[getNewNode]
* link:apiclient.md#hasavailablenodes[hasAvailableNodes]
* link:apiclient.md#initialize[initialize]
* link:apiclient.md#isbanned[isBanned]
* link:apiclient.md#static-createmainnetapiclient[createMainnetAPIClient]
* link:apiclient.md#static-createtestnetapiclient[createTestnetAPIClient]

=== Constructors

==== constructor

+ *new APIClient*(`+nodes+`: ReadonlyArray‹string›, `+providedOptions+`:
InitOptions): _link:apiclient.md[APIClient]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L98[api_client.ts:98]_

*Parameters:*

[cols=",,",options="header",]
|===
|Name |Type |Default
|`+nodes+` |ReadonlyArray‹string› |-
|`+providedOptions+` |InitOptions |\{}
|===

*Returns:* _link:apiclient.md[APIClient]_

=== Properties

==== accounts

• *accounts*: _link:accountsresource.md[AccountsResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L84[api_client.ts:84]_

'''''

==== bannedNodes

• *bannedNodes*: _ReadonlyArray‹string›_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L85[api_client.ts:85]_

'''''

==== blocks

• *blocks*: _link:blocksresource.md[BlocksResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L86[api_client.ts:86]_

'''''

==== currentNode

• *currentNode*: _string_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L87[api_client.ts:87]_

'''''

==== dapps

• *dapps*: _link:dappsresource.md[DappsResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L88[api_client.ts:88]_

'''''

==== delegates

• *delegates*: _link:delegatesresource.md[DelegatesResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L89[api_client.ts:89]_

'''''

==== headers

• *headers*: _HashMap_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L90[api_client.ts:90]_

'''''

==== node

• *node*: _link:noderesource.md[NodeResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L91[api_client.ts:91]_

'''''

==== nodes

• *nodes*: _ReadonlyArray‹string›_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L92[api_client.ts:92]_

'''''

==== peers

• *peers*: _link:peersresource.md[PeersResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L93[api_client.ts:93]_

'''''

==== randomizeNodes

• *randomizeNodes*: _boolean_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L94[api_client.ts:94]_

'''''

==== signatures

• *signatures*: _link:signaturesresource.md[SignaturesResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L95[api_client.ts:95]_

'''''

==== transactions

• *transactions*: _link:transactionsresource.md[TransactionsResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L96[api_client.ts:96]_

'''''

==== voters

• *voters*: _link:votersresource.md[VotersResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L97[api_client.ts:97]_

'''''

==== votes

• *votes*: _link:votesresource.md[VotesResource]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L98[api_client.ts:98]_

=== Accessors

==== `+Static+` constants

• *get constants*():
_``/Users/mona/git/sdk/elements/lisk-api-client/src/constants''_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L66[api_client.ts:66]_

*Returns:*
_``/Users/mona/git/sdk/elements/lisk-api-client/src/constants''_

=== Methods

==== banActiveNode

▸ *banActiveNode*(): _boolean_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L117[api_client.ts:117]_

*Returns:* _boolean_

'''''

==== banActiveNodeAndSelect

▸ *banActiveNodeAndSelect*(): _boolean_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L121[api_client.ts:121]_

*Returns:* _boolean_

'''''

==== banNode

▸ *banNode*(`+node+`: string): _boolean_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L130[api_client.ts:130]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+node+` |string
|===

*Returns:* _boolean_

'''''

==== getNewNode

▸ *getNewNode*(): _string_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L140[api_client.ts:140]_

*Returns:* _string_

'''''

==== hasAvailableNodes

▸ *hasAvailableNodes*(): _boolean_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L154[api_client.ts:154]_

*Returns:* _boolean_

'''''

==== initialize

▸ *initialize*(`+nodes+`: ReadonlyArray‹string›, `+providedOptions+`:
InitOptions): _void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L158[api_client.ts:158]_

*Parameters:*

[cols=",,",options="header",]
|===
|Name |Type |Default
|`+nodes+` |ReadonlyArray‹string› |-
|`+providedOptions+` |InitOptions |\{}
|===

*Returns:* _void_

'''''

==== isBanned

▸ *isBanned*(`+node+`: string): _boolean_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L186[api_client.ts:186]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+node+` |string
|===

*Returns:* _boolean_

'''''

==== `+Static+` createMainnetAPIClient

▸ *createMainnetAPIClient*(`+options?+`: InitOptions):
_link:apiclient.md[APIClient]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L70[api_client.ts:70]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+options?+` |InitOptions
|===

*Returns:* _link:apiclient.md[APIClient]_

'''''

==== `+Static+` createTestnetAPIClient

▸ *createTestnetAPIClient*(`+options?+`: InitOptions):
_link:apiclient.md[APIClient]_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_client.ts#L77[api_client.ts:77]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+options?+` |InitOptions
|===

*Returns:* _link:apiclient.md[APIClient]_
