{empty}[@liskhq/lisk-api-client](../README.md) ›
link:noderesource.md[NodeResource]

== Class: NodeResource

=== Hierarchy

* APIResource
+
↳ *NodeResource*

=== Index

==== Constructors

* link:noderesource.md#constructor[constructor]

==== Properties

* link:noderesource.md#apiclient[apiClient]
* link:noderesource.md#getconstants[getConstants]
* link:noderesource.md#getforgingstatus[getForgingStatus]
* link:noderesource.md#getstatus[getStatus]
* link:noderesource.md#gettransactions[getTransactions]
* link:noderesource.md#path[path]
* link:noderesource.md#updateforgingstatus[updateForgingStatus]

==== Accessors

* link:noderesource.md#headers[headers]
* link:noderesource.md#resourcepath[resourcePath]

==== Methods

* link:noderesource.md#handleretry[handleRetry]
* link:noderesource.md#request[request]

=== Constructors

==== constructor

+ *new NodeResource*(`+apiClient+`: link:apiclient.md[APIClient]):
_link:noderesource.md[NodeResource]_

_Overrides void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/node.ts#L27[resources/node.ts:27]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+apiClient+` |link:apiclient.md[APIClient]
|===

*Returns:* _link:noderesource.md[NodeResource]_

=== Properties

==== apiClient

• *apiClient*: _link:apiclient.md[APIClient]_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L26[api_resource.ts:26]_

'''''

==== getConstants

• *getConstants*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/node.ts#L22[resources/node.ts:22]_

'''''

==== getForgingStatus

• *getForgingStatus*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/node.ts#L23[resources/node.ts:23]_

'''''

==== getStatus

• *getStatus*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/node.ts#L24[resources/node.ts:24]_

'''''

==== getTransactions

• *getTransactions*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/node.ts#L25[resources/node.ts:25]_

'''''

==== path

• *path*: _string_

_Overrides void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/node.ts#L26[resources/node.ts:26]_

'''''

==== updateForgingStatus

• *updateForgingStatus*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/node.ts#L27[resources/node.ts:27]_

=== Accessors

==== headers

• *get headers*(): _HashMap_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L34[api_resource.ts:34]_

*Returns:* _HashMap_

'''''

==== resourcePath

• *get resourcePath*(): _string_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L38[api_resource.ts:38]_

*Returns:* _string_

=== Methods

==== handleRetry

▸ *handleRetry*(`+error+`: Error, `+req+`: AxiosRequestConfig,
`+retryCount+`: number): _Promise‹APIResponse›_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L42[api_resource.ts:42]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+error+` |Error
|`+req+` |AxiosRequestConfig
|`+retryCount+` |number
|===

*Returns:* _Promise‹APIResponse›_

'''''

==== request

▸ *request*(`+req+`: AxiosRequestConfig, `+retry+`: boolean,
`+retryCount+`: number): _Promise‹APIResponse›_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L67[api_resource.ts:67]_

*Parameters:*

[cols=",,",options="header",]
|===
|Name |Type |Default
|`+req+` |AxiosRequestConfig |-
|`+retry+` |boolean |-
|`+retryCount+` |number |1
|===

*Returns:* _Promise‹APIResponse›_
