{empty}[@liskhq/lisk-api-client](../README.md) ›
link:votesresource.md[VotesResource]

== Class: VotesResource

=== Hierarchy

* APIResource
+
↳ *VotesResource*

=== Index

==== Constructors

* link:votesresource.md#constructor[constructor]

==== Properties

* link:votesresource.md#apiclient[apiClient]
* link:votesresource.md#get[get]
* link:votesresource.md#path[path]

==== Accessors

* link:votesresource.md#headers[headers]
* link:votesresource.md#resourcepath[resourcePath]

==== Methods

* link:votesresource.md#handleretry[handleRetry]
* link:votesresource.md#request[request]

=== Constructors

==== constructor

+ *new VotesResource*(`+apiClient+`: link:apiclient.md[APIClient]):
_link:votesresource.md[VotesResource]_

_Overrides void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/votes.ts#L23[resources/votes.ts:23]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+apiClient+` |link:apiclient.md[APIClient]
|===

*Returns:* _link:votesresource.md[VotesResource]_

=== Properties

==== apiClient

• *apiClient*: _link:apiclient.md[APIClient]_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L26[api_resource.ts:26]_

'''''

==== get

• *get*: _APIHandler_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/votes.ts#L22[resources/votes.ts:22]_

'''''

==== path

• *path*: _string_

_Overrides void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/resources/votes.ts#L23[resources/votes.ts:23]_

=== Accessors

==== headers

• *get headers*(): _HashMap_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L34[api_resource.ts:34]_

*Returns:* _HashMap_

'''''

==== resourcePath

• *get resourcePath*(): _string_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L38[api_resource.ts:38]_

*Returns:* _string_

=== Methods

==== handleRetry

▸ *handleRetry*(`+error+`: Error, `+req+`: AxiosRequestConfig,
`+retryCount+`: number): _Promise‹APIResponse›_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L42[api_resource.ts:42]_

*Parameters:*

[cols=",",options="header",]
|===
|Name |Type
|`+error+` |Error
|`+req+` |AxiosRequestConfig
|`+retryCount+` |number
|===

*Returns:* _Promise‹APIResponse›_

'''''

==== request

▸ *request*(`+req+`: AxiosRequestConfig, `+retry+`: boolean,
`+retryCount+`: number): _Promise‹APIResponse›_

_Inherited from void_

_Defined in
https://github.com/LiskHQ/lisk-sdk/blob/e48ce8907/elements/lisk-api-client/src/api_resource.ts#L67[api_resource.ts:67]_

*Parameters:*

[cols=",,",options="header",]
|===
|Name |Type |Default
|`+req+` |AxiosRequestConfig |-
|`+retry+` |boolean |-
|`+retryCount+` |number |1
|===

*Returns:* _Promise‹APIResponse›_
