= RPC API of Lisk Service
Muhammad Talha <muhammad.talha@lightcurve.io>
:toc:
:toclevels: 4
:page-toclevels: 4


== Introduction to Lisk Service endpoints

=== Endpoint logic
The logic of the endpoints is as follows: The structure is always based on `/<root_entity or module>/<object>/<properties>`.

=== Response format
All responses are in the JSON format: `application/json`.

Each API request has the following structure:
[source,json]
----
{
  "data": {}, // Contains the requested data
  "meta": {}, // Contains additional metadata, e.g. the values of `limit` and `offset`
}
----

[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>", // Contains the error message
}
----

=== API base URL
The base URL for the Lisk Service v3 API is /api/v3. All the RESTful endpoints specified below follow the base URL.

* *Example:* https://service.lisk.com/api/v3/spec

The WS-RPC endpoints however are available to query under the `/rpc-v3` namespace.

* *Example:* {wss://service.lisk.com/rpc-v3/}[]

=== API status and readiness
Lisk Service offers /status and /ready endpoints to check the current deployment and high-level service readiness statuses respectively.
These endpoints must be queried without the API versioning.

* *Example:* https://service.lisk.com/api/status
* *Example:* https://service.lisk.com/api/ready


== Lisk Blockchain-related endpoints

=== Blocks
==== get.blocks
Retrieves blocks from the blockchain based on ID, height, or account.
Supports pagination.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`blockID`
|String
|`/^([1-9]&#124;[A-Fa-f0-9])&#123;1,64&#125;$/`
|(empty)
|

|`height`
|String
|`/([0-9]+&#124;[0-9]+:[0-9]+)/`
|(empty)
|Query by height or a range of height.
Can be expressed as an interval i.e. `1:20` or `1:` or `:20`.
Specified values are inclusive.

|`timestamp`
|String
|`/([0-9]+&#124;[0-9]+:[0-9]+)/`
|(empty)
|Query by timestamp or a timestamp range.
Can be expressed as an interval i.e. `1000000:2000000` or `1000000:` or `:2000000`.
Specified values are inclusive.

|`generatorAddress`
|String
|`/^lsk[a-hjkm-z2-9]&#123;38&#125;$/`
|(empty)
|

|`limit`
|Number
|`[1,100]`
|10
|

|`offset`
|Number
|`[0,Inf]`
|0
|

|`sort`
|Enum
|`["height:asc", "height:desc","timestamp:asc", "timestamp:desc"]`
|`height:desc`
|
|===
--
cURL::
+
--


.HTTP GET block by blockID
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/blocks?blockID=01967dba384998026fe028119bd099ecf073c05c045381500a93d1a7c7307e5b'
----

.HTTP GET blocks by height
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/blocks?height=10'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC get.blocks by blockID
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.blocks",
  "params": {
      "blockID": "01967dba384998026fe028119bd099ecf073c05c045381500a93d1a7c7307e5b"
  }
}
----

.RPC get.blocks by height
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.blocks",
  "params": {
      "height": "10"
  }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": [
      {
          "id": "485ddcec34ffe77942eb8e4ffb90c323d9eec290aa80ff6fc9806c5679ce0bc2",
          "version": 2,
          "timestamp": 1683666343,
          "height": 10,
          "previousBlockID": "72fb960ff7fa7077f4f89e2d6cad844032222794a507d5dba0737e0ddc40d88d",
          "generator": {
              "address": "lsk5omgus3q5w4jn5xscv5ppmq9kp8k7xu6thy4f7",
              "name": "genesis_9",
              "publicKey": null
          },
          "transactionRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "assetRoot": "86ac617cde82f4ecfc4597829f4df34634b9dead231e4a22c96152025ef41e4c",
          "stateRoot": "ab4e6af04f93ea0c5348828eb6af2fe8b0c903fe455956c7a48caec6fab306b1",
          "maxHeightPrevoted": 0,
          "maxHeightGenerated": 0,
          "validatorsHash": "8438b6d8c70e18c79a9215f53b6c4677e2f4bab793479a35c03d8f514f3389b3",
          "aggregateCommit": {
              "height": 0,
              "aggregationBits": "",
              "certificateSignature": ""
          },
          "numberOfTransactions": 0,
          "numberOfAssets": 1,
          "numberOfEvents": 1,
          "totalForged": "0",
          "totalBurnt": "0",
          "networkFee": "0",
          "signature": "69ab16efce598facb355cca7441cdb932345e13b50f1f5256efb7f14f1f52fba0d994bbf607803bb0cbf8d1d58169e3b33e8c46fdb5434994b523df42f0b240d",
          "reward": "0",
          "isFinal": true
      }
  ],
  "meta": {
      "count": 1,
      "offset": 0,
      "total": 1
  }
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====


==== get.blocks.assets
Retrieves block assets based on criteria defined by params.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`blockID`
|String
|`/^([1-9]&#124;[A-Fa-f0-9])&#123;1,64&#125;$/`
|(empty)
|

|`height`
|String
|`/([0-9]+&#124;[0-9]+:[0-9]+)/`
|(empty)
|Query by height or a range of height.
Can be expressed as an interval i.e. `1:20` or `1:` or `:20`.
Specified values are inclusive.

|`timestamp`
|String
|`/([0-9]+&#124;[0-9]+:[0-9]+)/`
|(empty)
|Query by timestamp or a timestamp range.
Can be expressed as an interval i.e. `1000000:2000000` or `1000000:` or `:2000000`.
Specified values are inclusive.

|`module`
|String
|`/^\b(?:[\w!@$&.]{1,32}\|,)+\b$/`
|(empty)
|

|`limit`
|Number
|`[1,100]`
|10
|

|`offset`
|Number
|`[0,Inf]`
|0
|

|`sort`
|Enum
|`["height:asc", "height:desc","timestamp:asc", "timestamp:desc"]`
|`height:desc`
|
|===
--
cURL::
+
--
.HTTP GET block assets by blockID
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/blocks/assets?blockID=485ddcec34ffe77942eb8e4ffb90c323d9eec290aa80ff6fc9806c5679ce0bc2'
----
.HTTP GET block assets by height
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/blocks/assets?height=10'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC GET block assets by blockID
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.blocks.assets",
  "params": {
      "blockID": "485ddcec34ffe77942eb8e4ffb90c323d9eec290aa80ff6fc9806c5679ce0bc2"
  }
}
----


.RPC GET block assets by blockID
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.blocks.assets",
  "params": {
      "height": "10"
  }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": [
      {
          "block": {
              "id": "485ddcec34ffe77942eb8e4ffb90c323d9eec290aa80ff6fc9806c5679ce0bc2",
              "height": 10,
              "timestamp": 1683666343
          },
          "assets": [
              {
                  "module": "random",
                  "data": {
                      "seedReveal": "c6e438bcbfe9e77825cf70e5cafcc2b3"
                  }
              }
          ]
      }
  ],
  "meta": {
      "count": 1,
      "offset": 0,
      "total": 1
  }
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====






=== Transactions

==== get.transactions
Retrieves network transactions by criteria defined by parameters.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`transactionId`
|String
|`/^([1-9]&#124;[A-Fa-f0-9])&#123;1,64&#125;$/`
|(empty)
|

|`moduleCommand`
|String
|`/^[a-zA-Z][\w]{0,31}:[a-zA-Z][\w]{0,31}$/`
|(empty)
|Transfer transaction: moduleID = 2,assetID = 0

|`senderAddress`
|String
|`/^lsk[a-hjkm-z2-9]{38}$/`
|(empty)
|

|`recipientAddress`
|String
|`/^lsk[a-hjkm-z2-9]{38}$/`
|(empty)
|

|`senderPublicKey`
|String
|`/^([A-Fa-f0-9]&#123;2&#125;)&#123;32&#125;$/`
|(empty)
|

|`address`
|String
|`/^lsk[a-hjkm-z2-9]{38}$/` 
|(empty)
|Resolves for both senderAddress and recipientAddress

|`blockID`
|String
|`/^([1-9]\|[A-Fa-f0-9]){1,64}$/`
|(empty)
|

|`height`
|String
|`/([0-9]+\|[0-9]+:[0-9]+)/`
|(empty)
|Query by height or a range of height.
Can be expressed as an interval i.e. `1:20` or `1:` or `:20`.
Specified values are inclusive.

|`timestamp`
|String
|`/([0-9]+&#124;[0-9]+:[0-9]+)/`
|(empty)
|Query by timestamp or a timestamp range.
Can be expressed as an interval i.e. `1000000:2000000` or `1000000:` or `:2000000`.
Specified values are inclusive.

|`executionStatus`
|String
|`/^\b(?:pending\|success\|fail\|,)+\b$/`
|(empty)
|Can be expressed as a CSV

|`nonce`
|Number
|`/^[0-9]+$/`
|(empty)
|

|`limit`
|Number
|`[1,100]` 
|10
|

|`offset`
|Number
|`[0,Inf]`
|0
|

|`sort`
|Enum
|`["height:asc", "height:desc", "timestamp:asc", "timestamp:desc"]`
|`height:desc`
|

|`order`
|Enum
|`['index:asc', 'index:desc']`
|`index:asc`
|The order condition is applied after the sort condition, usually to break ties when the sort condition results in a collision.

|===

--
cURL::
+
--
.HTTP GET transaction by transactionID
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/transactions?transactionID=dcb3840032b0bcabc1a0ae5e89124004e537927cfa8e9061d5984eaff91b5243'
----
.HTTP GET the last 25 transactions for account
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/transactions?address=lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad'
----

--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC-WS get transaction by transactionID
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.transactions",
  "params": {
      "transactionID": "dcb3840032b0bcabc1a0ae5e89124004e537927cfa8e9061d5984eaff91b5243"
  }
}
----

.RPC-WS get the last 25 transactions for account
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.transactions",
  "params": {
      "address": "lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad"
  }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": [
      {
          "id": "dcb3840032b0bcabc1a0ae5e89124004e537927cfa8e9061d5984eaff91b5243",
          "moduleCommand": "token:transfer",
          "nonce": "4",
          "fee": "5174000",
          "minFee": "173000",
          "size": 174,
          "sender": {
              "address": "lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad",
              "publicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
              "name": "genesis_0"
          },
          "params": {
              "tokenID": "0400000000000000",
              "amount": "12000000000",
              "recipientAddress": "lsknhqvv8ou5jpjcn3ezazkjgbjp2kdhwvoyz6hfj",
              "data": "welcome "
          },
          "block": {
              "id": "5d81effdba82a15977935609e4626091ee904f289e5d7074d67a5b26750064b9",
              "height": 880,
              "timestamp": 1684325210,
              "isFinal": false
          },
          "meta": {
              "recipient": {
                  "address": "lsknhqvv8ou5jpjcn3ezazkjgbjp2kdhwvoyz6hfj",
                  "publicKey": null,
                  "name": null
              }
          },
          "executionStatus": "success",
          "index": 0
      }
  ],
  "meta": {
      "count": 1,
      "offset": 0,
      "total": 1
  }
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====



==== post.transactions.dryrun
The endpoints is used to send decoded/encoded transactions to the network node for dry run.

[tabs]
=====
Specification::
+
--
No parameters are required.
The endpoint can be invoked by sending a payload to it.

.Decoded payload of a transaction
[source,json]
----
{
  "skipDecode": false,
  "skipVerify": false,
  "transaction": {
    "module": "token",
    "command": "transfer",
    "fee": "100000000",
    "nonce": "0",
    "senderPublicKey": "a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0",
    "signatures": [
      "48425002226745847e155cf5480478c2336a43bb178439e9058cc2b50e26335cf7c8360b6c6a49793d7ae8d087bc746cab9618655e6a0adba4694cce2015b50f"
    ],
    "params": {
      "recipientAddress": "lskz4upsnrwk75wmfurf6kbxsne2nkjqd3yzwdaup",
      "amount": "10000000000",
      "tokenID": "0000000000000000",
      "data": "Token transfer tx"
    }
  }
}
----

*OR*

.Encoded payload of a transaction
[source,json]
----
{
  "skipDecode": false,
  "skipVerify": false,
  "transaction": "0a040000000212040000000018002080c2d72f2a2044c3cb523c0a069e3f2dcb2d5994b6ba8ff9f73cac9ae746922aac4bc22f95b132310a0800000001000000001080c2d72f1a14632228a3e6a67ac6892de2eb4f60abe2e3bc42a1220a73656e6420746f6b656e3a40964d81e28727e6567b0fcd8a7fcf0a03f401cadbc1c16b9a7f300a52c372022b51a4553865199af34b5f73765f970704fc443d2a6dd510a26748905c306e530b"
}
----

--
cURL::
+
--
[source,json]
----
curl --location 'https://betanet-service.lisk.com/api/v3/transactions/dryrun' \
--header 'Content-Type: application/json' \
--data '{
  "transaction": "0a040000000212040000000018002080c2d72f2a2044c3cb523c0a069e3f2dcb2d5994b6ba8ff9f73cac9ae746922aac4bc22f95b132310a0800000001000000001080c2d72f1a14632228a3e6a67ac6892de2eb4f60abe2e3bc42a1220a73656e6420746f6b656e3a40964d81e28727e6567b0fcd8a7fcf0a03f401cadbc1c16b9a7f300a52c372022b51a4553865199af34b5f73765f970704fc443d2a6dd510a26748905c306e530b"
}'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.
[source,json]
----
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "post.transactions.dryrun",
    "params": {
        "skipDecode": false,
        "skipVerify": false,
        "transaction": "0a040000000212040000000018002080c2d72f2a2044c3cb523c0a069e3f2dcb2d5994b6ba8ff9f73cac9ae746922aac4bc22f95b132310a0800000001000000001080c2d72f1a14632228a3e6a67ac6892de2eb4f60abe2e3bc42a1220a73656e6420746f6b656e3a40964d81e28727e6567b0fcd8a7fcf0a03f401cadbc1c16b9a7f300a52c372022b51a4553865199af34b5f73765f970704fc443d2a6dd510a26748905c306e530b"
    }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
    "result": 1,
    "status": "ok",
    "events": [
      {
        "data": {
          "senderAddress": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
          "tokenID": "0000000000000000",
          "amount": "100003490",
          "recipientAddress": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"
        },
        "index": 0,
        "module": "token",
        "name": "transferEvent",
        "topics": [
          "86afcdd640846bf41525481938653ee942be3fac1ecbcff08e98f9aeda3a9583",
          "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
          "0000000000000000",
          "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"
        ],
        "height": 10
      }
    ]
  },
  "meta": {}
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
500 Internal Server Error::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unable to reach a network node."
}
----
--
=====
====


==== post.transactions.estimate-fees
Estimate transaction fees.

[tabs]
=====
Specification::
+
--
No parameters are required.
The endpoint can be invoked by sending a payload to it.

.Decoded payload of a transaction
[source,json]
----
{
  "transaction":  {
    "module": "token",
    "command": "transfer",
    "fee": "100000000",
    "nonce": "1",
    "senderPublicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
    "signatures": [
      "0f0af2be5a18593f76dbd7a5d43e29cb9cce7a056dc28f818cc2d75e671bde9e5cccaf924b2a86415dc49be14c8b6bbf348a8918521b7a028bea1d9637bec905"
    ],
    "params": {
      "tokenID": "0000000000000000",
      "amount": "100000000000",
      "receivingChainID": "00000001",
      "recipientAddress": "lskyvvam5rxyvbvofxbdfcupxetzmqxu22phm4yuo",
      "data": "",
      "messageFee": "10000000",
      "messageFeeTokenID": "0000000000000000"
    },
    "id": "0f77248481c050fcf4f88ef7b967548452869879137364df3b33da09cc419395"
  }
}
----

*OR*

.Encoded payload of a transaction
[source,json]
----
{
  "transaction": "0a040000000212040000000018002080c2d72f2a2044c3cb523c0a069e3f2dcb2d5994b6ba8ff9f73cac9ae746922aac4bc22f95b132310a0800000001000000001080c2d72f1a14632228a3e6a67ac6892de2eb4f60abe2e3bc42a1220a73656e6420746f6b656e3a40964d81e28727e6567b0fcd8a7fcf0a03f401cadbc1c16b9a7f300a52c372022b51a4553865199af34b5f73765f970704fc443d2a6dd510a26748905c306e530b"
}
----

--
cURL::
+
--
[source,json]
----
curl --location 'https://betanet-service.lisk.com/api/v3/transactions/estimate-fees' \
--header 'Content-Type: application/json' \
--data '{
  "transaction":  {
    "module": "token",
    "command": "transfer",
    "fee": "100000000",
    "nonce": "1",
    "senderPublicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
    "signatures": [
      "0f0af2be5a18593f76dbd7a5d43e29cb9cce7a056dc28f818cc2d75e671bde9e5cccaf924b2a86415dc49be14c8b6bbf348a8918521b7a028bea1d9637bec905"
    ],
    "params": {
      "tokenID": "0000000000000000",
      "amount": "100000000000",
      "receivingChainID": "00000001",
      "recipientAddress": "lskyvvam5rxyvbvofxbdfcupxetzmqxu22phm4yuo",
      "data": "",
      "messageFee": "10000000",
      "messageFeeTokenID": "0000000000000000"
    },
    "id": "0f77248481c050fcf4f88ef7b967548452869879137364df3b33da09cc419395"
  }
}'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "post.transactions.estimate-fees",
  "params": {
      "transaction": {
          "module": "token",
          "command": "transfer",
          "fee": "100000000",
          "nonce": "1",
          "senderPublicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
          "signatures": [
              "0f0af2be5a18593f76dbd7a5d43e29cb9cce7a056dc28f818cc2d75e671bde9e5cccaf924b2a86415dc49be14c8b6bbf348a8918521b7a028bea1d9637bec905"
          ],
          "params": {
              "tokenID": "0000000000000000",
              "amount": "100000000000",
              "receivingChainID": "00000001",
              "recipientAddress": "lskyvvam5rxyvbvofxbdfcupxetzmqxu22phm4yuo",
              "data": "",
              "messageFee": "10000000",
              "messageFeeTokenID": "0000000000000000"
          },
          "id": "0f77248481c050fcf4f88ef7b967548452869879137364df3b33da09cc419395"
      }
  }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
      "transactionFeeEstimates": {
          "minFee": "166000",
          "accountInitializationFee": {
              "tokenID": "0000000000000000",
              "amount": "5000000"
          }
      },
      "dynamicFeeEstimates": {
          "low": "166000",
          "medium": "166000",
          "high": "166000"
      }
  },
  "meta": {}
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
500 Internal Server Error::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unable to reach a network node."
}
----
--
=====
====




==== post.transactions
Sends encoded transactions to the network node.

[tabs]
=====
Specification::
+
--
No parameters are required.
The endpoint can be invoked by sending a payload to it.

.Payload of a transaction
[source,json]
----
{
  "transaction": "0a040000000212040000000018002080c2d72f2a2044c3cb523c0a069e3f2dcb2d5994b6ba8ff9f73cac9ae746922aac4bc22f95b132310a0800000001000000001080c2d72f1a14632228a3e6a67ac6892de2eb4f60abe2e3bc42a1220a73656e6420746f6b656e3a40964d81e28727e6567b0fcd8a7fcf0a03f401cadbc1c16b9a7f300a52c372022b51a4553865199af34b5f73765f970704fc443d2a6dd510a26748905c306e530b"
}
----

--
cURL::
+
--
[source,json]
----
curl --location 'https://betanet-service.lisk.com/api/v3/transactions' \
--header 'Content-Type: application/json' \
--data '{
"transaction": "0a040000000212040000000018002080c2d72f2a2044c3cb523c0a069e3f2dcb2d5994b6ba8ff9f73cac9ae746922aac4bc22f95b132310a0800000001000000001080c2d72f1a14632228a3e6a67ac6892de2eb4f60abe2e3bc42a1220a73656e6420746f6b656e3a40964d81e28727e6567b0fcd8a7fcf0a03f401cadbc1c16b9a7f300a52c372022b51a4553865199af34b5f73765f970704fc443d2a6dd510a26748905c306e530b"
}'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "post.transactions",
  "params": {
      "transaction": "0a040000000212040000000018002080c2d72f2a2044c3cb523c0a069e3f2dcb2d5994b6ba8ff9f73cac9ae746922aac4bc22f95b132310a0800000001000000001080c2d72f1a14632228a3e6a67ac6892de2eb4f60abe2e3bc42a1220a73656e6420746f6b656e3a40964d81e28727e6567b0fcd8a7fcf0a03f401cadbc1c16b9a7f300a52c372022b51a4553865199af34b5f73765f970704fc443d2a6dd510a26748905c306e530b"
  }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "message": "Transaction payload was successfully passed to the network node.",
  "transactionID": "bfd3521aeddd586f43931b6972b5771e9919e18f2cc91e940a15eacb588ecc6c"
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Transaction payload was rejected by the network node."
}
----
--
500 Internal Server Error::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unable to reach a network node."
}
----
--
=====
====















==== post.transactions.estimate-fees
Estimate transaction fees.

[tabs]
=====
Specification::
+
--
No parameters are required.
The endpoint can be invoked by sending a payload to it.

.Decoded payload of a transaction
[source,json]
----
{
  "transaction":  {
    "module": "token",
    "command": "transfer",
    "fee": "100000000",
    "nonce": "1",
    "senderPublicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
    "signatures": [
      "0f0af2be5a18593f76dbd7a5d43e29cb9cce7a056dc28f818cc2d75e671bde9e5cccaf924b2a86415dc49be14c8b6bbf348a8918521b7a028bea1d9637bec905"
    ],
    "params": {
      "tokenID": "0000000000000000",
      "amount": "100000000000",
      "receivingChainID": "00000001",
      "recipientAddress": "lskyvvam5rxyvbvofxbdfcupxetzmqxu22phm4yuo",
      "data": "",
      "messageFee": "10000000",
      "messageFeeTokenID": "0000000000000000"
    },
    "id": "0f77248481c050fcf4f88ef7b967548452869879137364df3b33da09cc419395"
  }
}
----

*OR*

.Encoded payload of a transaction
[source,json]
----
{
  "transaction": "0a040000000212040000000018002080c2d72f2a2044c3cb523c0a069e3f2dcb2d5994b6ba8ff9f73cac9ae746922aac4bc22f95b132310a0800000001000000001080c2d72f1a14632228a3e6a67ac6892de2eb4f60abe2e3bc42a1220a73656e6420746f6b656e3a40964d81e28727e6567b0fcd8a7fcf0a03f401cadbc1c16b9a7f300a52c372022b51a4553865199af34b5f73765f970704fc443d2a6dd510a26748905c306e530b"
}
----

--
cURL::
+
--
[source,json]
----
curl --location 'https://betanet-service.lisk.com/api/v3/transactions/estimate-fees' \
--header 'Content-Type: application/json' \
--data '{
  "transaction":  {
    "module": "token",
    "command": "transfer",
    "fee": "100000000",
    "nonce": "1",
    "senderPublicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
    "signatures": [
      "0f0af2be5a18593f76dbd7a5d43e29cb9cce7a056dc28f818cc2d75e671bde9e5cccaf924b2a86415dc49be14c8b6bbf348a8918521b7a028bea1d9637bec905"
    ],
    "params": {
      "tokenID": "0000000000000000",
      "amount": "100000000000",
      "receivingChainID": "00000001",
      "recipientAddress": "lskyvvam5rxyvbvofxbdfcupxetzmqxu22phm4yuo",
      "data": "",
      "messageFee": "10000000",
      "messageFeeTokenID": "0000000000000000"
    },
    "id": "0f77248481c050fcf4f88ef7b967548452869879137364df3b33da09cc419395"
  }
}'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "post.transactions.estimate-fees",
  "params": {
      "transaction": {
          "module": "token",
          "command": "transfer",
          "fee": "100000000",
          "nonce": "1",
          "senderPublicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
          "signatures": [
              "0f0af2be5a18593f76dbd7a5d43e29cb9cce7a056dc28f818cc2d75e671bde9e5cccaf924b2a86415dc49be14c8b6bbf348a8918521b7a028bea1d9637bec905"
          ],
          "params": {
              "tokenID": "0000000000000000",
              "amount": "100000000000",
              "receivingChainID": "00000001",
              "recipientAddress": "lskyvvam5rxyvbvofxbdfcupxetzmqxu22phm4yuo",
              "data": "",
              "messageFee": "10000000",
              "messageFeeTokenID": "0000000000000000"
          },
          "id": "0f77248481c050fcf4f88ef7b967548452869879137364df3b33da09cc419395"
      }
  }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
      "transactionFeeEstimates": {
          "minFee": "166000",
          "accountInitializationFee": {
              "tokenID": "0000000000000000",
              "amount": "5000000"
          }
      },
      "dynamicFeeEstimates": {
          "low": "166000",
          "medium": "166000",
          "high": "166000"
      }
  },
  "meta": {}
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
500 Internal Server Error::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unable to reach a network node."
}
----
--
=====
====




==== get.transactions.statistics
Retrieves daily network transaction statistics for periods defined by params.
Supports pagination.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`interval`
|String
|`day` or `month`
|(empty)
|Required field.

|`limit`
|Number
|`[1,100]`
|10
|

|`offset`
|Number
|`[0,Inf]`
|0
|

|===

--
cURL::
+
--
.HTTP GET transaction statistics for the past 7 days.
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/transactions/statistics?interval=day&limit=7'
----

.HTTP GET transaction statistics for the past 12 months.
[source,json]
----
curl --location 'https://service.lisk.com/api/v3/transactions​/statistics​?interval=month&limit=12'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.transactions.statistics",
  "params": {
      "interval": "day",
      "limit": 7
  }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
      "distributionByType": {
          "pos:changeCommission": 1,
          "pos:registerValidator": 2,
          "pos:stake": 8,
          "token:transfer": 9
      },
      "distributionByAmount": {
          "0200000000000000": {
              "0.001_0.01": 9,
              "0.1_1": 2,
              "10_100": 4,
              "100_1000": 3,
              "10000_100000": 2
          }
      },
      "timeline": {
          "0200000000000000": [
              {
                  "date": "2023-05-17",
                  "transactionCount": 20,
                  "volume": 2258455916000,
                  "timestamp": 1684281600
              },
              {
                  "date": "2023-05-16",
                  "transactionCount": 0,
                  "volume": 0,
                  "timestamp": 1684195200
              },
              {
                  "date": "2023-05-15",
                  "transactionCount": 0,
                  "volume": 0,
                  "timestamp": 1684108800
              },
              {
                  "date": "2023-05-14",
                  "transactionCount": 0,
                  "volume": 0,
                  "timestamp": 1684022400
              },
              {
                  "date": "2023-05-13",
                  "transactionCount": 0,
                  "volume": 0,
                  "timestamp": 1683936000
              },
              {
                  "date": "2023-05-12",
                  "transactionCount": 0,
                  "volume": 0,
                  "timestamp": 1683849600
              },
              {
                  "date": "2023-05-11",
                  "transactionCount": 0,
                  "volume": 0,
                  "timestamp": 1683763200
              }
          ]
      }
  },
  "meta": {
      "limit": 7,
      "offset": 0,
      "total": 365,
      "duration": {
          "format": "YYYY-MM-DD",
          "from": "2023-05-11",
          "to": "2023-05-17"
      }
  }
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
503 Service Unavailable::
+
--
[source,json]
----
{
  "error": true,
  "message": "Service is not ready yet."
}
----
--
=====
====




=== Events


==== Events search
Retrieves blockchain events based on criteria defined by params.
Supports pagination.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`transactionID`
|String
|`/^\b([A-Fa-f0-9]){1,64}\b$/`
|(empty)
|

|`senderAddress`
|String
|`/^lsk[a-hjkm-z2-9]{38}$/`
|(empty)
|

|`topic`
|String
|`/^lsk[a-hjkm-z2-9]{38}$/`
|(empty)
|Can be expressed as a CSV

|`blockID`
|String
|`/^([1-9]\|[A-Fa-f0-9]){1,64}$/`
|(empty)
|

|`height`
|String
|`/([0-9]+&#124;[0-9]+:[0-9]+)/`
|(empty)
|Query by height or a range of height.
Can be expressed as an interval i.e. `1:20` or `1:` or `:20`.
Specified values are inclusive.

|`timestamp`
|String
|`/([0-9]+&#124;[0-9]+:[0-9]+)/`
|(empty)
|Query by timestamp or a timestamp range.
Can be expressed as an interval i.e. `1000000:2000000` or `1000000:` or `:2000000`.
Specified values are inclusive.

|`limit`
|Number
|`[1,100]` 
|10
|

|`offset`
|Number
|`[0,Inf]`
|0
|

|`sort`
|Enum
|`["height:asc", "height:desc", "timestamp:asc", "timestamp:desc"]`
|`height:desc`
|

|`order`
|Enum
|`['index:asc', 'index:desc']`
|`index:asc`
|The order condition is applied after the sort condition, usually to break ties when the sort condition results in a collision.

|===

--
cURL::
+
--
.HTTP GET events by blockID.
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/events?blockID=2cede47ca8ae76a4355ad36d8fc5b8a1e8407198e9e1201bf19d8c658c4dae81'
----

.HTTP GET events by topic.
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/events?topic=lskfqjehvg8b86cobzzy72q36s6nyb5d5mxg6ndu3'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC-WS GET events by blockID
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.events",
  "params": {
      "blockID": "2cede47ca8ae76a4355ad36d8fc5b8a1e8407198e9e1201bf19d8c658c4dae81"
  }
}
----

.RPC-WS GET events by topic
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.events",
  "params": {
      "topic": "lskfqjehvg8b86cobzzy72q36s6nyb5d5mxg6ndu3"
  }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": [
      {
          "id": "d6eb4eac33af3645be1c805e15a58b1cb00f09285d9cf1aa18930ce017f078f5",
          "module": "dynamicReward",
          "name": "rewardMinted",
          "data": {
              "amount": "0",
              "reduction": 1
          },
          "topics": [
              "03",
              "lskfqjehvg8b86cobzzy72q36s6nyb5d5mxg6ndu3"
          ],
          "index": 0,
          "block": {
              "id": "2cede47ca8ae76a4355ad36d8fc5b8a1e8407198e9e1201bf19d8c658c4dae81",
              "height": 7140,
              "timestamp": 1684409170
          }
      }
  ],
  "meta": {
      "count": 1,
      "offset": 0,
      "total": 1
  }
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====

=== Generators

==== get.generators
Retrieves the list of block generators.
Supports pagination.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`search`
|Number
|`/^[\w!@$&.]{1,64}$/`
|empty
|Case-insensitive search by name, address or publicKey.
Supports both partial and full text search.

|`limit`
|Number
|`[1,103]`
|10
|

|`offset`
|Number
|`[0,Inf]`
|0
|

|===

--
cURL::
+
--
.HTTP GET the list of generators
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/generators'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC-WS GET the list of generators
[source,json]
----
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get.generators",
    "params": {
    }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "jsonrpc": "2.0",
  "result": {
      "data": [
          {
              "address": "lskafuhtj7rjn5g7u45qjxf5hn6mhc9zja7vyasdw",
              "name": "genesis_2",
              "publicKey": null,
              "nextAllocatedTime": 1684410230,
              "status": "active"
          },
          {
              "address": "lskc94hx5zgu3vbydwj96v64r5pdfj4q3ytfxyw23",
              "name": "genesis_5",
              "publicKey": null,
              "nextAllocatedTime": 1684410240,
              "status": "active"
          },
          {
              "address": "lskm25ey5bcsnu5kh98wavyhy9t6m8yqumq2nhcbw",
              "name": "genesis_0",
              "publicKey": null,
              "nextAllocatedTime": 1684410250,
              "status": "active"
          },
          {
              "address": "lskoary3z6dwdc4g87daqw7dpfetmn2yyanuytztq",
              "name": "genesis_6",
              "publicKey": null,
              "nextAllocatedTime": 1684410260,
              "status": "active"
          },
          {
              "address": "lskhh3qt6yzht3a93ubheoczvro7fch39mm85sk9o",
              "name": "genesis_12",
              "publicKey": null,
              "nextAllocatedTime": 1684410270,
              "status": "active"
          },
          {
              "address": "lskgwn65oosep5tvedmzoww7peroe5h8v4p96p3ht",
              "name": "genesis_9",
              "publicKey": null,
              "nextAllocatedTime": 1684410280,
              "status": "active"
          },
          {
              "address": "lskd5zqbts72odcq5wdfddftnrhvjybx5nk77rxcz",
              "name": "genesis_15",
              "publicKey": null,
              "nextAllocatedTime": 1684410290,
              "status": "active"
          },
          {
              "address": "lskcmvk8ypeye2uqpawwun9u35y5c8kyrgrnygqq4",
              "name": "genesis_3",
              "publicKey": null,
              "nextAllocatedTime": 1684410300,
              "status": "active"
          },
          {
              "address": "lskcdmcxk82hn7krh58u8u2h3whqrtfbjjh267ksk",
              "name": "genesis_10",
              "publicKey": null,
              "nextAllocatedTime": 1684410310,
              "status": "active"
          },
          {
              "address": "lsk6ew29p4dzponwg98ymekg6nbjaynq4hqwetxpm",
              "name": "genesis_1",
              "publicKey": null,
              "nextAllocatedTime": 1684410320,
              "status": "active"
          }
      ],
      "meta": {
          "count": 10,
          "offset": 0,
          "total": 16
      }
  },
  "id": 1
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====




=== Auth

==== get.auth
Retrieves user-specific details from the Auth module.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`address`
|String
|`/^lsk[a-hjkm-z2-9]{38}$/` 
|empty
|Required

|===

--
cURL::
+
--
.HTTP GET auth details for an address
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/auth?address=lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC-WS GET auth details for an address
[source,json]
----
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get.auth",
    "params": {
      "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"
    }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
    "nonce": "1",
    "numberOfReqSignatures": 1,
    "mandatoryKeys": [
      "689b9a40aa11cbc8327d5eeebed9a1052940730f9c34cffb33ae591131141349"
    ],
    "optionalKeys": [
      "478842a844914f18a1c620a6494bf9931d0a862e96212bf5fc6f3ca18658febe"
    ]
  },
  "meta": {
    "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
    "publicKey": "b1d6bc6c7edd0673f5fed0681b73de6eb70539c21278b300f07ade277e1962cd",
    "name": "genesis_84"
  }
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====



=== Validator

==== get.validator
Retrieves user-specific details from the Validator module.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`address`
|String
|`/^lsk[a-hjkm-z2-9]{38}$/` 
|empty
|Required

|===

--
cURL::
+
--
.HTTP GET user-specific details for an address
[source,json]
----
curl --location 'http://betanet-service.lisk.com/api/v3/validator?address=lskc94hx5zgu3vbydwj96v64r5pdfj4q3ytfxyw23'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC-WS GET user-specific details for an address
[source,json]
----
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get.validator",
    "params": {
      "address": "lskc94hx5zgu3vbydwj96v64r5pdfj4q3ytfxyw23"
    }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
    "generatorKey": "59274923432b74133be4def9c9f8e544bf032184a2153b0ca34b1dd5669f5fdf",
    "blsKey": "8aeba1cc038ad2cf1ba6ae1479f293f1e3c074369c3afe623e6921ac4cd6c959647ca85fe197228c38dda1df18812d32",
    "proofOfPossession": "abb6c31f5885022765301fbfcc6c34686ef9a9b0eec34cb487433558071ab57fd28852752f81dda00447e69d61f63f48174c10a0a0a2d34d230b9a75d903a0befdef82708e5f869ff75090c1b5ce85565e8a17e5e06c4cae305c5efb1f37d996"
  },
  "meta": {
    "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
    "publicKey": "b1d6bc6c7edd0673f5fed0681b73de6eb70539c21278b300f07ade277e1962cd",
    "name": "genesis_84"
  }
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====


==== post.validator.validate-bls-key
Sends and validates a BLS key against its corresponding Proof of Possession.

[tabs]
=====
Specification::
+
--
No parameters are required.
The endpoint can be invoked by sending a payload to it.

.Payload containing BLS Key and Proof of Possession.
[source,json]
----
{
  "blsKey": "b301803f8b5ac4a1133581fc676dfedc60d891dd5fa99028805e5ea5b08d3491af75d0707adab3b70c6a6a580217bf81",
  "proofOfPossession": "88bb31b27eae23038e14f9d9d1b628a39f5881b5278c3c6f0249f81ba0deb1f68aa5f8847854d6554051aa810fdf1cdb02df4af7a5647b1aa4afb60ec6d446ee17af24a8a50876ffdaf9bf475038ec5f8ebeda1c1c6a3220293e23b13a9a5d26"
}
----
--
cURL::
+
--
.HTTP POST Validate BLS Key request
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/validator/validate-bls-key' \
--header 'Content-Type: application/json' \
--data '{
  "blsKey": "b301803f8b5ac4a1133581fc676dfedc60d891dd5fa99028805e5ea5b08d3491af75d0707adab3b70c6a6a580217bf81",
  "proofOfPossession": "88bb31b27eae23038e14f9d9d1b628a39f5881b5278c3c6f0249f81ba0deb1f68aa5f8847854d6554051aa810fdf1cdb02df4af7a5647b1aa4afb60ec6d446ee17af24a8a50876ffdaf9bf475038ec5f8ebeda1c1c6a3220293e23b13a9a5d26"
}'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC-WS POST Validate BLS Key request
[source,json]
----
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "post.validator.validate-bls-key",
    "params": {
        "blsKey": "b301803f8b5ac4a1133581fc676dfedc60d891dd5fa99028805e5ea5b08d3491af75d0707adab3b70c6a6a580217bf81",
        "proofOfPossession": "88bb31b27eae23038e14f9d9d1b628a39f5881b5278c3c6f0249f81ba0deb1f68aa5f8847854d6554051aa810fdf1cdb02df4af7a5647b1aa4afb60ec6d446ee17af24a8a50876ffdaf9bf475038ec5f8ebeda1c1c6a3220293e23b13a9a5d26"
    }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
      "isValid": true
  },
  "meta": {}
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====

=== Token
==== get.token.account.exists
Validates if an entry exists in the Token sub-store for the specified address.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`tokenID`
|String
|`/^\b[a-fA-F0-9]{16}\b$/`
|empty
|Required

|`address`
|String
|`/^lsk[a-hjkm-z2-9]{38}$/`
|empty
| One of address, publicKey or name required

|`publicKey`
|String
|`/^([A-Fa-f0-9]{2}){32}$/;`
|empty
|

|`name`
|String
|`/^[\w!@$&.]{3,20}$/`
|empty
|

|===

--
cURL::
+
--

[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/token/account/exists?tokenID=0400000000000000&address=lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

[source,json]
----
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get.token.account.exists",
    "params": {
      "tokenID": "0400000000000000",
      "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"
    }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
    "isExists": true
  },
  "meta": {}
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====


==== get.token.balances
Retrieves the balances from the Token sub-store for the specified address.

[tabs]
=====
Specification::
+
--
[cols="1,1,2,1,2", options="header"]
|===
|Parameter |Type |Validation |Default |Description

|`tokenID`
|String
|`/^\b[a-fA-F0-9]{16}\b$/`
|empty
|

|`address`
|String
|`/^lsk[a-hjkm-z2-9]{38}$/`
|empty
|Required

|`limit`
|Number
|`[1,100]`
|10
|

|`offset`
|Number
|`[0,Inf]`
|0
|

|===

--
cURL::
+
--

[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/token/balances?address=lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

[source,json]
----
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "get.token.balances",
  "params": {
      "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"
  }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
    "tokenID": "0000000000000000",
    "availableBalance": "1000000000",
    "lockedBalances": [
      {
        "module": "token",
        "amount": "10000"
      }
    ]
  },
  "meta": {
    "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
    "count": 10,
    "offset": 10,
    "total": 100
  }
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====

==== get.token.constants
Retrieves module constants from the Token module.

[tabs]
=====
Specification::
+
--
No parameters are required.
--
cURL::
+
--
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/token/constants'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC-WS POST Validate BLS Key request
[source,json]
----
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get.token.constants",
    "params": {
    }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
    "extraCommandFees": {
      "userAccountInitializationFee": "5000000",
      "escrowAccountInitializationFee": "5000000"
    }
  },
  "meta": {}
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====


==== get.token.summary
Retrieves the summary of the Token sub-store state from the Token module.

[tabs]
=====
Specification::
+
--
No parameters are required.
--
cURL::
+
--
[source,json]
----
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/token/summary'
----
--
RPC-WS::
+
--
To request Lisk service endpoints via RPC, set up a socket.io connection and send the following request.

.RPC-WS POST Validate BLS Key request
[source,json]
----
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get.token.summary",
    "params": {
    }
}
----
--

=====

[%collapsible]
.Sample responses
====
[tabs]
=====
200 OK::
+
--
[source,json]
----
{
  "data": {
    "escrowedAmounts": [
      {
        "escrowChainID": "00000000",
        "tokenID": "0000000000000000",
        "amount": "50000000000"
      }
    ],
    "supportedTokens": [
      {
        "isSupportAllTokens": true,
        "patternTokenIDs": [
          "00000000******"
        ],
        "exactTokenIDs": [
          "0000000000000000"
        ]
      }
    ],
    "totalSupply": [
      {
        "tokenID": "0000000000000000",
        "amount": "50000000000"
      }
    ]
  },
  "meta": {}
}
----
--
400 Bad Request::
+
--
[source,json]
----
{
  "error": true,
  "message": "Unknown input parameter(s): <param_name>"
}
----
--
=====
====


























// === Fees
// ==== get.fees
// Requests transaction fee estimates per byte.

// No parameters.

// .Response
// [source,json]
// ----
// {
//   "data": {
//     "feeEstimatePerByte": {
//       "low": 0,
//       "medium": 1000,
//       "high": 2000
//     },
//     "baseFeeById": {
//       "2:0": "1000000000"
//     },
//     "baseFeeByName": {
//       "token:transfer": "1000000000"
//     },
//     "minFeePerByte": 1000,
//   },
//   "meta": {
//     "lastUpdate": 123456789,
//     "lastBlockHeight": 25,
//     "lastBlockId": 1354568
//   },
//   "links": {}
// }
// ----

// .Example: Get fees
// [source,json]
// ----
// {
//     "jsonrpc": "2.0",
//     "method": "get.fees",
// }
// ----
// === Peers
// ==== get.peers
// Retrieves network peers with details based on criteria.

// Supports pagination.

// [cols=",,,,", options="header"]
// .Parameters
// |===
// |Parameter |Type |Validation |Default |Comment

// |`ip`
// |String
// |`/^(?:(?:25[0-5]&#124;2[0-4][0-9]&#124;[01]?[0-9][0-9]?)\.)&#123;3&#125;(?:25[0-5]&#124;2[0-4][0-9]&#124;[01]?[0-9][0-9]?)$/`
// |(empty)
// |

// |`networkVersion`
// |String
// |`/^(0&#124;[1-9]\d*)\.(0&#124;[1-9]\d*)\.(0&#124;[1-9]\d*)(-(0&#124;[1-9]\d*&#124;\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0&#124;[1-9]\d*&#124;\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/`
// |(empty)
// |

// |`state`
// |Array of strings
// |`["connected", "disconnected", "any"]`
// |`connected`
// |

// |`height`
// |Number
// |`<1;+Inf>`
// |(empty)
// |

// |`limit`
// |Number
// |`<1;100>`
// |10
// |

// |`offset`
// |Number
// |`<0;+Inf>`
// |0
// |

// |`sort`
// |Array of strings
// |`["height:asc", "height:desc", "networkVersion:asc", "networkVersion:desc"]`
// |`height:desc`
// |

// |===

// .Response
// [source,json]
// ----
// {
//     "data": [
//       {
//         "ip": "127.0.0.1",
//         "port": 4000,
//         "networkVersion": "2.0",
//         "state": "connected",
//         "height": 8350681,
//         "networkIdentifier": "258974416d58533227c6a3da1b6333f0541b06c65b41e45cf31926847a3db1ea",
//         "location": {
//           "countryCode": "DE",
//           "countryName": "Germany",
//           "hostname": "host.210.239.23.62.rev.coltfrance.com",
//           "ip": "210.239.23.62",
//         }
//       }
//     ],
//     "meta": {
//       "count": 100,
//       "offset": 25,
//       "total": 43749
//     },
//     "links": {}
// }
// ----
// .Example: Get hosts with a specific IP address
// [source,json]
// ----
// {
//     "jsonrpc": "2.0",
//     "method": "get.peers",
//     "params": {
//         "ip": "210.239.23.62"
//     }
// }
// ----
// === Network
// ==== get.network.status
// Retrieves network details and constants such as network height, broadhash, fees, reward amount, etc.

// No parameters.

// .Response
// [source,json]
// ----
// {
//   "data": {
//     "height": 27256,
//     "finalizedHeight": 27112,
//     "milestone": "0",
//     "networkVersion": "2.0",
//     "networkIdentifier": "08ec0e01794b57e5ceaf5203be8c1bda51bcdd39bb6fc516adbe93223f85d630",
//     "reward": "500000000",
//     "supply": "10094237000000000",
//     "registeredModules": ["token", "sequence", "keys", "dpos", "legacyAccount"],
//     "operations": [
//       { "id": "2:0", "name": "token:transfer" }
//       ...
//     ],
//     "blockTime": 10,
//     "communityIdentifier": "Lisk",
//     "maxPayloadLength": 15360,
//   },
//   "meta": {
//     "lastUpdate": 123456789,
//     "lastBlockHeight": 25,
//     "lastBlockId": 1354568
//   },
//   "links": {}
// }
// ----
// .Example
// [source,json]
// ----
// {
//     "jsonrpc": "2.0",
//     "method": "get.network.status"
// }
// ----
// ==== get.network.statistics
// Retrieves network statistics such as the number of peers, node versions, heights, etc.

// No parameters.

// .Response
// [source,json]
// ----
// {
//     "data": {
//       "basic": {
//         "connectedPeers": 134,
//         "disconnectedPeers": 48,
//         "totalPeers": 181
//       },
//       "height": {
//         "7982598": 24
//       },
//       "networkVersion": {
//         "2.0": 12,
//         "2.1": 41
//       }
//     },
//     "meta": {},
//     "links": {}
//   }

// ----
// .Example
// [source,json]
// ----
// {
//     "jsonrpc": "2.0",
//     "method": "get.network.statistics"
// }
// ----

// == Off-chain Features

// === Market Prices

// Retrieves current market prices.

// ==== Endpoints

// - HTTP `/api/v2/market/prices`
// - RPC `get.market.prices`

// ==== Request parameters

// *(no params)*

// ==== Response example

// .200 OK
// [source,json]
// ----
// {
//   "data": [
//     {
//       "code": "BTC_EUR",
//       "from": "BTC",
//       "rate": "53623.7800",
//       "sources": [
//           "binance"
//       ],
//       "to": "EUR",
//       "updateTimestamp": 1634649300
//     },
//   ],
//   "meta": {
//       "count": 7
//   }
// }
// ----

// .503 Service Unavailable
// [source,json]
// ----
// {
//   "error": true,
//   "message": "Service is not ready yet"
// }
// ----

// === News Feed Aggregator

// Retrieves recent blogposts from Lisk Blog and Twitter.

// _Supports pagination._

// ==== Endpoints

// * HTTP: `/api/v2/newsfeed`
// * RPC: `get.newsfeed`

// ==== Request parameters

// [cols="1,1,2", options="header"]
// .The Lisk Service microservices
// |===
// |Parameter |Type |Validation

// |source
// |String
// |`/[A-z]+/`   \| `*`

// Retrieves all sources by default.

// |limit
// |Number
// |`<1;100>`

// |offset
// |Number
// |`<0;+Inf>`

// |===

// ==== Response example

// .200 OK
// [source,json]
// ----
// {
//   "data": [
//     {
//       "author": "Lisk",
//       "content": "On Wednesday, March 3rd, Max Kordek, CEO and Co-founder at Lisk, hosted a live\nmonthly AMA (Ask Max Anything) on Lisk.chat. He answered questions regarding the\nupcoming milestones for Lisk, Lisk.js 2021, marketing plans for this year, and\nmuch more.\n\nThis blog post includes a recap of the live AMA session and features the\nquestions asked by community members, as well as Max’s answers.",
//       "image_url": "https://lisk.com/sites/default/files/styles/blog_main_image_xl_retina/public/images/2021-04/montly-ama-ask-max-anything-recap-MAIN-V1%402x_0.png?itok=_0lipXxp",
//       "imageUrl": "https://lisk.com/sites/default/files/styles/blog_main_image_xl_retina/public/images/2021-04/montly-ama-ask-max-anything-recap-MAIN-V1%402x_0.png?itok=_0lipXxp",
//       "source": "drupal_lisk_general",
//       "sourceId": "1001",
//       "timestamp": 1614854580,
//       "createdAt": 1614854580,
//       "modifiedAt": 1614854580,
//       "title": "AMA Recap: Ask Max Anything in March 2021",
//       "url": "https://lisk.com/blog/events/ama-recap-ask-max-anything-march-2021"
//     }
//   ],
//   "meta": {
//     "count": 1,
//     "limit": 1,
//     "offset": 0
//   }
// }
// ----

// 400 Bad Request

// ._Invalid parameter_
// [source,json]
// ----
// ```
// {
//   "error": true,
//   "message": "Unknown input parameter(s): <param_name>"
// }
// ----

// ._Invalid source name_
// [source,json]
// ----
// {
//     "error": true,
//     "message": "Invalid input: The 'source' field fails to match the required pattern."
// }
// ----

// .503 Service Unavailable
// [source,json]
// ----
// {
//   "error": true,
//   "message": "Service is not ready yet"
// }
// ----






// == Access paths and compatibility
// The RPC WebSocket API can be accessed by the `ws://localhost:9901/rpc-v2`.

// === Access paths and compatibility
// The WebSocket API can be accessed by the `wss://service.lisk.com/rpc-v2`.

// The testnet network can also be accessed by `wss://testnet-service.lisk.com/rpc-v2`.

// The Lisk Service WebSocket API uses the `socket.io` library and is compatible with the JSON-RPC 2.0 standard.
// The specification below contains numerous examples of how to use the API in practice.

// === Endpoint logic
// The logic of the endpoints is derived as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the action is equivalent to the  HTTP standard (GET, POST, PUT, etc.), and `entity` is a part of the application logic, ex. `accounts`, transactions and so on.

// === Requests

// [source,js]
// ----
// import io from 'socket.io-client';

// const request = async (endpoint, method, params) => new Promise(resolve => {
// 	const socket = io(endpoint, { forceNew: true, transports: ['websocket'] });

// 	socket.emit('request', { jsonrpc: '2.0', method, params }, answer => {
// 		socket.close();
// 		resolve(answer);
// 	});
// });

// const wsRequest = async () => {
//   return await request('ws://localhost:9901/rpc', 'get.accounts', { "address": "lskzkfw7ofgp3uusknbetemrey4aeatgf2ntbhcds" });
// };

// wsRequest().then(response => {
//   console.log(response);
// });
// ----

// === Responses
// All responses are returned in the JSON format - application/json.

// Each API response has the following structure:

// [source,js]
// ----
// {
//     "jsonrpc": "2.0",    // standard JSON-RPC envelope
//     "result": {
//         "data": {}, // Contains the requested data
//         "meta": {}, // Contains additional metadata, e.g. the values of `limit` and `offset`
//     },
//     "id": 1    // Number of response in chain
// }
// ----

// == Date Format
// Contrary to the original Lisk Core API, all timestamps used by the Lisk Service are in the UNIX timestamp format.
// The blockchain dates are always expressed as integers and the epoch date is equal to the number of seconds since 1970-01-01 00:00:00.

// == Multi-Requests
// A request can consist of an array of multiple responses.

// [source,js]
// ----
// [
//     { "jsonrpc": "2.0", "id": 1, "method": "get.blocks", "params": {} },
//     { "jsonrpc": "2.0", "id": 2, "method": "get.transactions", "params": { "height": "123" } },
//     { "jsonrpc": "2.0", "id": 3, "method": "get.accounts", "params": { "address": "lskzkfw7ofgp3uusknbetemrey4aeatgf2ntbhcds"} }
// ]
// ----

// Response

// [source,js]
// ----
// [
//     {
//         "jsonrpc": "2.0",
//         "result": {
//             "data": [
//                 ... // List of blocks
//             ],
//             "meta": {},
//         },
//         "id": 1
//     },
//     {
//         "jsonrpc": "2.0",
//         "result": {
//             "data": [
//                 ... // List of transactions
//             ],
//             "meta": {},
//         },
//         "id": 2
//     },
//     {
//         "jsonrpc": "2.0",
//             "data": [
//                 ... // List of accounts
//             ],
//             "meta": {},
//         },
//         "id": 3
//     }
// ]
// ----





//TODO:Remove this

// === Accounts

// ==== get.accounts
// Retrieves account details based on criteria defined by params.

// Supports pagination.

// [cols=",,,,", options="header"]
// .Parameters
// |===
// |Parameter |Type |Validation |Default |Comment

// |`address`
// |String
// |`/^lsk[a-hjkm-z2-9]&#123;38&#125;$//^[1-9]\d&#123;0,19&#125;[L&#124;l]$/`
// |(empty)
// |Resolves new and old address system.

// |`publickey`
// |String
// |`/^([A-Fa-f0-9]&#123;2&#125;)&#123;32&#125;$/`
// |(empty)
// |

// |`username`
// |String
// |`/^[a-z0-9!@$&_.]&#123;1,20&#125;$/`
// |(empty)
// |

// |`isDelegate`
// |Boolean
// |`true` or `false`
// |(empty)
// |

// |`status`
// |String
// |`active`, `standby`, `banned`, `punished`, `non-eligible`
// |(empty)
// |Multiple choice possible i.e. `active,banned`

// |`search`
// |String
// |
// |(empty)
// |

// |`limit`
// |Number
// |`<1;100>`
// |10
// |

// |`offset`
// |Number
// |`<0;+Inf>`
// |0
// |

// |`sort`
// |Array of strings
// |`["balance:asc", "balance:desc", "rank:asc", "rank:desc"]`
// |`balance:desc`
// |Rank is dedicated to delegate accounts
// |===

// .Response example
// [source,json]
// ----
// {
//   "data": {
//     "summary": {
//       "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
//       "legacyAddress": "2841524825665420181L",
//       "balance": "151146419900",
//       "username": "liberspirita",
//       "publicKey": "968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b",
//       "isMigrated": true,
//       "isDelegate": true,
//       "isMultisignature": true,
//     },
//     "knowledge": {
//       "owner": "Genesis Account",
//       "description": ""
//     },
//     "token": {
//       "balance": "151146419900"
//     },
//     "sequence": {
//       "nonce": "11"
//     },
//     "keys": {
//       "numberOfSignatures": 0,
//       "mandatoryKeys": [],
//       "optionalKeys": [],
//       "members": [
//         {
//           "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
//           "publicKey": "968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b",
//           "isMandatory": true,
//         }
//       ],
//       "memberships": [
//         {
//           "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
//           "publicKey": "968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b",
//           "username": "genesis_51",
//         }
//       ],
//     },
//     "dpos": {
//       "delegate": {
//         "username": "liberspirita",
//         "pomHeights": [
//           { "start": 123, "end": 456 },
//           { "start": 789, "end": 1050 }
//         ],
//         "consecutiveMissedBlocks": 0,
//         "lastForgedHeight": 68115,
//         "isBanned": false,
//         "totalVotesReceived": "201000000000",
//       },
//       "sentVotes": [
//         {
//           "delegateAddress": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
//           "amount": "102000000000"
//         },
//         {
//           "delegateAddress": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
//           "amount": "95000000000"
//         }
//       ],
//       "unlocking": [
//         {
//           "delegateAddress": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
//           "amount": "150000000",
//           "height": {
//             "start": "10",
//             "end": "2010"
//           }
//         }
//       ],
//       "legacy": {
//         "address": "2841524825665420181L", // legacyAddress
//         "balance": "234500000" // Reclaimable balance
//       }
//     }
//   },
//   "meta": {
//     "count": 1,
//     "offset": 0
//   },
//   "links": {}
// }
// ----

// .Example: Get account with a specific Lisk account ID
// [source,json]
// ----
// {
//     "jsonrpc": "2.0",
//     "method": "get.accounts",
//     "params": {
//         "address": "lskzkfw7ofgp3uusknbetemrey4aeatgf2ntbhcds"
//     }
// }
// ----

// ==== get.votes_sent
// Retrieves votes of a single account based on address, public key, or delegate name.

// Supports pagination.

// [cols=",,,,", options="header"]
// .Parameters
// |===
// |Parameter |Type |Validation |Default |Comment

// |`address`
// |String
// |`/^lsk[a-hjkm-z2-9]&#123;38&#125;$//^[1-9]\d&#123;0,19&#125;[L&#124;l]$/`
// |(empty)
// |Resolves only new address system

// |`publickey`
// |String
// |`/^([A-Fa-f0-9]&#123;2&#125;)&#123;32&#125;$/`
// |(empty)
// |

// |`username`
// |String
// |`/^[a-z0-9!@$&_.]&#123;1,20&#125;$/`
// |(empty)
// |

// |===

// .Response
// [source,json]
// ----
// {
//   "data": {
//     "account": {
//       "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
//       "username": "genesis_56",
//       "votesUsed": 10
//     },
//     "votes": [
//       {
//         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
//         "amount": 1081560729258, // = voteWeight
//         "username": "liskhq"
//       }
//     ]
//   },
//   "meta": {
//     "count": 10,
//     "offset": 0,
//     "total": 10 // = votesUsed
//   },
//   "links": {}
// }
// ----

// .Example
// [source,json]
// ----
// {
//     "method": "get.votes_sent",
//     "params": {
//         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu"
//     }
// }
// ----

// ==== get.votes_received
// Retrieves voters for a delegate account based on address, public key, or delegate name.

// Supports pagination.

// [cols=",,,,", options="header"]
// .Parameters
// |===
// |Parameter |Type |Validation |Default |Comment

// |`address`
// |String
// |`/^lsk[a-hjkm-z2-9]&#123;38&#125;$//^[1-9]\d&#123;0,19&#125;[L&#124;l]$/`
// |(empty)
// |Resolves only new address system

// |`publickey`
// |String
// |`/^([A-Fa-f0-9]&#123;2&#125;)&#123;32&#125;$/`
// |(empty)
// |

// |`username`
// |String
// |`/^[a-z0-9!@$&_.]&#123;1,20&#125;$/`
// |(empty)
// |

// |`limit`
// |Number
// |`<1;100>`
// |10
// |

// |`offset`
// |Number
// |`<0;+Inf>`
// |0
// |

// |===

// .Response
// [source,json]
// ----
// {
//   "data": {
//     "account": {
//       "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
//       "username": "genesis_56",
//       "votesUsed": 10
//     },
//     "votes": [
//       {
//         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
//         "amount": 1081560729258, // = voteWeight
//         "username": "liskhq"
//       }
//     ]
//   },
//   "meta": {
//     "count": 10,
//     "offset": 0,
//     "total": 10 // = votesUsed
//   },
//   "links": {}
// }
// ----
// .Example
// [source,json]
// ----
// {
//     "jsonrpc": "2.0",
//     "method": "get.votes_received",
//     "params": {
//         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu"
//     }
// }
// ----
