= Application set up
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core application setup describes all necessary steps and requirements to install the Lisk SDK.
:toc:
:v_sdk: master
:page-next: /lisk-core/management/application.html
:page-next-title: Application commands

:url_dev_forum: https://dev.lisk.io/

:url_upgrade_binary: update/application.adoc
:url_admin_binary: management/application.adoc
:url_config_api_access: management/api-access.adoc
:url_config: management/configuration.adoc
:url_config_logrotation: management/logs.adoc#logrotation

This document details how to setup a Lisk Core application on a system.

[[pre_install]]
== Pre-install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, please proceed to the <<install, Installation>> chapter.

=== Determine if your platform can run Lisk Core

==== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64


include::partial$core-ports.adoc[]

=== Install dependencies

If you are running Ubuntu then execute the following command:

[source,bash]
----
sudo apt-get update
sudo apt-get install curl wget tar unzip zip ntp
----

If you are running a Mac then execute the following command:

[source,bash]
----
brew install curl wget tar unzip zip ntp
----

include::partial$create-a-new-user.adoc[]

[[install]]
== Installation

This section details how to install Lisk Core using pre-built application packages.
Once completed, you will have a functioning node on the Lisk network.
If you are looking to upgrade your current Lisk Core installation, please see the xref:{url_upgrade_binary}[Update Application] section.

=== Login to the Lisk user

Creating the user is described in the <<pre_install,Application - prerequisites section>>.

Please note, this is only for Ubuntu. However, if you are already logged in to this user, please skip this step.

[source,bash]
----
sudo -u lisk -i
----

=== Execute the installation script

This will configure the environment, download and install Lisk Core.

Before proceeding, determine whether you wish to connect your node to the Mainnet, (Main Network) or the Testnet, (Test Network).

[tabs]
====
Mainnet::
+
--
Download Lisk Core:

[source,bash]
----
wget https://downloads.lisk.io/lisk/main/installLisk.sh
----

To connect your node to the Mainnet, execute the following command:

[source,bash]
----
bash installLisk.sh install -r main
----
--

Testnet::
+
--
Download Lisk Core:

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/installLisk.sh
----

To connect your node to the Testnet, execute the following command:

[source,bash]
----
bash installLisk.sh install -r test
----
--
====


A prompt will now appear regarding your installation directory, pressing enter will choose the default option.

Next, a following prompt will appear asking if you wish to synchronize from the genesis block.
If you answer `no', which is the default option, the node will download a recent snapshot of the database.
This will be much faster than synchronising from the genesis block.

The installation may take a few minutes.
Check the output of the script to verify that the installation was successful.

If you recognize an error, try to resolve it by analyzing the error output, otherwise please refer to the xref:{url_dev_forum}[Developer's Forum].

=== Verify successful installation

When the installation script has finished, navigate inside of the newly created folder `lisk-main`(for Mainnet) or `lisk-test`(for Testnet).
It is possible to verify that your Lisk node is up and running, by executing the following command:

[source,bash]
----
bash lisk.sh status
----

For further information and how to administer your Lisk node, please see the xref:{url_admin_binary}[Management section].

If you are not running Lisk locally, you will need to follow the xref:{url_config_api_access}[API configuration] document to enable access.

If all of the above steps have been successfully completed, then the next step is to move on to the configuration documentation.

If you wish to enable forging or SSL, please see the xref:{url_config}[General configuration].

== Post-installation (optional)

* It is recommended to set up a xref:{url_config_logrotation}[log rotation].
