= Lisk Core Binary Setup
Mona Bärenfänger <mona@lightcurve.io>
:toc:

This document details how to setup Lisk Core Binary distribution on a system.

== Option A: Lisk Commander

Setup and manage your Lisk node conveniently with Lisk Commander.

[NOTE]
====
This setup option is supported from Lisk Core v2.0.0 upwards.
If you have Lisk Core v1.6 or lower installed, you wont be able to upgrade your node with Lisk Commander.
In this case, use the bash script or remove your old version and make a fresh install with Lisk Commander.
====

include::partial$core-binary-ports.adoc[]

==== Install Lisk Commander

Head to the Lisk Commander docs and follow the xref:2.3.2@lisk-sdk::lisk-commander/index.adoc#_setup[installation instructions].

Once Lisk Commander is set up on your system, you can use the commands below to set up/manage your Lisk Core node.

=== Installation

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:install lisk-mainnet
----

This will install Lisk Core latest version into a directory `lisk-mainnet`.

To verify your node is running correctly, run e.g.

[source,bash]
----
lisk core:status lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:install lisk-testnet
----

This will install Lisk Core latest version into a directory `lisk-testnet`.

To verify your node is running correctly, run e.g.

[source,bash]
----
lisk core:status lisk-testnet
----
--
====

TIP: See for all available options the Lisk Commander xref:2.3.2@lisk-sdk::lisk-commander/user-guide/lisk-core.adoc[Command reference for Lisk Core] as well as the xref:2.3.2@lisk-sdk::lisk-commander/user-guide/commands.adoc[general Command reference].

=== Post-Install

After installation, check which ports Lisk Core is listening by checking the status:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:status lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:status lisk-testnet
----
--
====

Check you network settings to verify, the corresponding ports are open.

It’s also recommended to set up a xref:configuration.adoc#_logrotation[log rotation].

If you are not running Lisk locally, you will need to follow the xref:configuration.adoc#_api_access_control[Configuration - API] document to enable access.

With all of the above steps complete you are ready to move on to the configuration documentation if you wish to enable forging or SSL, please see xref:configuration.adoc[General Configuration].

== Option B: The Bash script

=== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, please proceed to the <<_installation, Installation>> chapter.

==== Determine if your platform can run Lisk Core

===== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64


include::partial$core-ports.adoc[]

==== Install dependencies

[source,bash]
----
sudo apt-get update
sudo apt-get install curl wget tar unzip zip ntp
----

include::partial$create-a-new-user.adoc[]

=== Installation

This section details how to install Lisk Core using pre-built binary packages.
Once completed, you will have a functioning node on the Lisk Network.
If you are looking to upgrade your current Lisk Core installation, please see the xref:upgrade/binary.adoc[Upgrade Binary] section.

==== Login to the Lisk user

The user was created in the <<pre-install,Binary - Prerequisites Section>>.
If you are already logged in to this user, please skip this step.

[source,bash]
----
sudo -u lisk -i
----

==== Execute the installation script

This will configure the environment, download and install Lisk Core.
Before proceeding, determine whether you wish to connect your node to the Testnet (Test Network) or the Mainnet (Main Network).

[tabs]
====
Mainnet::
+
--
Download Lisk Core:

[source,bash]
----
wget https://downloads.lisk.io/lisk/main/installLisk.sh
----

To connect your node to the Mainnet, run:

[source,bash]
----
bash installLisk.sh install -r main
----
--
Testnet::
+
--
Download Lisk Core:

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/installLisk.sh
----

To connect your node to the Testnet, run:

[source,bash]
----
bash installLisk.sh install -r test
----
--
====

You will be prompted for your installation directory, pressing enter will choose the default.

Next, you will be prompted, if you wish to synchronize from the Genesis block.
If you answer `no', which is the default option, the node will download a recent snapshot of the database.
This will be much faster than synching from the genesis block.

The installation may take a few minutes.
Check the output of the script to verify that the installation was successful.

If you recognize an error, try to resolve it by analyzing the error output, otherwise, you can have a look at our xref:troubleshooting.adoc[Troubleshooting Section].

==== Verify successful installation

When the installation script has finished, navigate inside of the newly created folder `lisk-main`(for Mainnet) or `lisk-test`(for Testnet).
You can verify that your Lisk node is up and running, by running the following command:

[source,bash]
----
bash lisk.sh status
----

For further information and how to administer your Lisk node, please have a look at our xref:administration/binary.adoc[Administration Section].

If you are not running Lisk locally, you will need to follow the xref:configuration.adoc#_api_access_control[Configuration - API] document to enable access.

With all of the above steps complete you are ready to move on to the configuration documentation if you wish to enable forging or SSL, please see xref:configuration.adoc[General Configuration].

=== Post-installation (optional)

* Recommended: Set up a xref:configuration.adoc#_logrotation[log rotation]
