== Lisk Core Binary Setup

This document details how to setup Lisk Core Binary distribution on a
system.

* link:#option-a-lisk-commander[Option A: Lisk Commander]
** link:#pre-install[Pre-Install]
[arabic]
. link:#determine-if-your-platform-can-run-lisk-core[Determine if your
platform can run Lisk Core]
. link:#open-the-necessary-ports[Open necessary ports]
. link:#install-lisk-commander[Install Lisk Commander]
** link:#installation[Installation]
* link:#option-b-the-bash-script[Option B: The Bash script]
** link:#pre-install-1[Pre-Install]
[arabic]
. link:#determine-if-your-platform-can-run-lisk-core-1[Determine if your
platform can run Lisk Core]
. link:#install-dependencies[Install dependencies]
. link:#create-a-user-to-run-lisk[Create `+lisk+` user]
** link:#installation-1[Installation]
[arabic]
. link:#login-to-the-lisk-user[Login as lisk user]
. link:#execute-the-installation-script[Execute the installation script]
. link:#verify-successful-installation[Verify successful installation]
* link:#post-installation-optional[Post-Installation (optional)]

== Option A: Lisk Commander

Setup and manage your Lisk node conveniently with Lisk Commander.

____
*Note:* This setup option is supported from Lisk Core v2.0.0 upwards. If
you have Lisk Core v1.6 or lower installed, you wont be able to upgrade
your node with Lisk Commander. In this case, use the bash script or
remove your old version and make a fresh install with Lisk Commander.
____

=== Pre-Install

To complete the installation some prerequisites need to be fulfilled. If
you have already performed these, please proceed to the
link:#installation[Installation] chapter.

==== Determine if your platform can run Lisk Core

===== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64

==== Ports

____
*Mandatory:* Always open the *WebSocket* port of your desired network,
to enable communication with other peer nodes. *Optional:* Open the
corresponding HTTP port for your network, to make your node’s
https://lisk.io/documentation/lisk-core/api[API] reachable. For more
info, see the diagram on the
link:../../start/interact-with-network.md[Interact with network] page.
____

To connect to the desired network with Lisk Core, please ensure that the
corresponding ports are open:

____
Lisk Core installed by lisk Commander currently uses the default ports,
incremented by +2. If you want to change it back to the
link:#open-the-necessary-ports[default ports] ports, just change the
link:../configuration.md[config] of your Lisk Core, once it’s installed.
____

[cols=",,",options="header",]
|===
|Network |HTTP |WebSocket
|Mainnet |8002 |8003
|Testnet |7002 |7003
|Devnet |4002 |5002
|===

These are the default ports for connecting with the network. They can be
link:../configuration.md[altered] later in the
https://github.com/LiskHQ/lisk-core/blob/master/config/mainnet/config.json#L21[`+config.json+`]
file.

==== Install Lisk Commander

Head to the Lisk Commander docs and follow the
link:../lisk-sdk/lisk-commander/introduction.md#setup[installation
instructions].

Once Lisk Commander is set up on your system, you can use the commands
below to set up/manage your Lisk Core node.

=== Installation

[source,bash]
----
lisk core:install lisk-mainnet
----

This will install Lisk Core latest version into a directory
`+lisk-mainnet+`.

To verify your node is running correctly, run e.g.

[source,bash]
----
lisk core:status lisk-mainnet
----

See for all available options the Lisk Commander
link:../lisk-sdk/lisk-commander/user-guide/lisk-core.md[Command
reference for Lisk Core] as well as the
link:../lisk-sdk/lisk-commander/user-guide/commands.md[general Command
reference].

=== Post-Install

After installation, check which ports Lisk Core is listening by checking
the status:

[source,bash]
----
lisk core:status lisk-mainnet
----

Check you network settings to verify, the corresponding ports are open.

It’s also recommended to set up a
link:../configuration.md#logrotation[log rotation].

If you are not running Lisk locally, you will need to follow the
link:../configuration.md#api-access-control[Configuration - API]
document to enable access.

With all of the above steps complete you are ready to move on to the
configuration documentation if you wish to enable forging or SSL, please
see link:../configuration.md[General Configuration].

== Option B: The Bash script

=== Pre-Install

==== Determine if your platform can run Lisk Core

===== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64

To complete the installation some prerequisites need to be fulfilled. If
you have already performed these, please proceed to the
link:#installation[Installation] chapter. Please follow the instructions
below to load the required software to your system.

==== Open the necessary ports

____
*Mandatory:* Always open the *WebSocket* port of your desired network,
to enable communication with other peer nodes. *Optional:* Open the
corresponding HTTP port for your network, to make your node’s
https://lisk.io/documentation/lisk-core/api[API] reachable. For more
info, see the diagram on the
link:../../start/interact-with-network.md[Interact with network] page.
____

To connect to the desired network with Lisk Core, please ensure that the
corresponding ports are open:

[cols=",,",options="header",]
|===
|Network |HTTP |WebSocket
|Mainnet |8000 |8001
|Testnet |7000 |7001
|Devnet |4000 |5000
|===

These are the default ports for connecting with the network. They can be
link:../configuration.md[altered] later in the
https://github.com/LiskHQ/lisk-core/blob/master/config/mainnet/config.json#L21[`+config.json+`]
file.

==== Install dependencies

[source,bash]
----
sudo apt-get update
sudo apt-get install curl wget tar unzip zip ntp
----

==== Create a user to run Lisk

____
The `+lisk+` user itself *does not need* any `+sudo+` rights to run Lisk
Core.
____

[source,bash]
----
sudo adduser lisk
----

=== Installation

This section details how to install Lisk Core using pre-built binary
packages. Once completed, you will have a functioning node on the Lisk
Network. If you are looking to upgrade your current Lisk Core
installation, please see the link:../upgrade/binary.md[Upgrade Binary]
section.

==== Login to the Lisk user

The user was created in the link:#pre-install[Binary - Prerequisites
Section]. If you are already logged in to this user, please skip this
step.

[source,bash]
----
sudo -u lisk -i
----

==== Execute the installation script

This will configure the environment, download and install Lisk Core.
Before proceeding, determine whether you wish to connect your node to
the Testnet (Test Network) or the Mainnet (Main Network).

===== Mainnet

Download Lisk Core:

[source,bash]
----
wget https://downloads.lisk.io/lisk/main/installLisk.sh
----

To connect your node to the Mainnet, run:

[source,bash]
----
bash installLisk.sh install -r main
----

===== Testnet

Download Lisk Core:

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/installLisk.sh
----

To connect your node to the Testnet, run:

[source,bash]
----
bash installLisk.sh install -r test
----

You will be prompted for your installation directory, pressing enter
will choose the default.

Next, you will be prompted, if you wish to synchronize from the Genesis
block. If you answer `no', which is the default option, the node will
download a recent snapshot of the database. This will be much faster
than synching from the genesis block.

The installation may take a few minutes. Check the output of the script
to verify that the installation was successful.

If you recognize an error, try to resolve it by analyzing the error
output, otherwise, you can have a look at our
link:../troubleshooting.md[Troubleshooting Section].

==== Verify successful installation

When the installation script has finished, navigate inside of the newly
created folder `+lisk-main+`(for Mainnet) or `+lisk-test+`(for Testnet).
You can verify that your Lisk node is up and running, by running the
following command:

[source,bash]
----
bash lisk.sh status
----

For further information and how to administer your Lisk node, please
have a look at our link:../administration/binary.md[Administration
Section].

If you are not running Lisk locally, you will need to follow the
link:../configuration.md#api-access-control[Configuration - API]
document to enable access.

With all of the above steps complete you are ready to move on to the
configuration documentation if you wish to enable forging or SSL, please
see link:../configuration.md[General Configuration].

=== Post-installation (optional)

* Recommended: Set up a link:../configuration.md#logrotation[log
rotation]
