= Binary setup
Mona Bärenfänger <mona@lightcurve.io>
:description: How to install and setup a Lisk Core (binary distribution).
:toc:
// External URLs
:url_set_path: https://opensource.com/article/17/6/set-path-linux
// Project URLs
:url_run_logging: lisk-docs::run-blockchain/logging.adoc

The binary installation offers an easy and automated approach to setup Lisk Core.

== Pre-Installation

=== Supported Platforms
* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 20.04 (LTS) x86_64
* MacOS x86_64
* MacOS ARM


// include::partial$create-a-new-user.adoc[]

[[install]]
== Installation

This section details how to install Lisk Core using pre-built application packages.
Once completed, you will have a functioning node on the Lisk Network.
--
NOTE: When using a MAC with Apple Silicon (M1 processor) please adhere to the relevant following setup instructions below:


.Environment Setup requirements
[%collapsible]
====
[source,js]
----
- Clean the old Node.js installations (with arm64 binaries)
rm -rf ~/.nvm

- Add a new session and set iTerm to open Intel mode and set a shortcut key

- Open terminal in the Intel mode

- Install Homebrew and nvm

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
# ARM Homebrew (for Redis)
arch -arm64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- Add the following lines to your ~/.zshrc
if [[ $(arch) = arm64 ]]; then
#   echo 'Detected Apple Silicon, ARM Homebrew has precedence'
   export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
else
#   echo 'Detected Intel CPU architecture, Intel Homebrew has precedence'
   export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"
fi

# Optional
echo "Current architecture: $(arch)"
- Restart the terminal and make sure your running it in the Intel mode
michal@aarmbp ~$ arch
i386

Install - Node.js
arch -x86_64 nvm install 12
Install docker for m1 by google search “docker install m1” and run it.
----

--
.Install Rosseta, Homebrew, and NVM
[%collapsible]
====
[source,js]
----
- Install Rosetta (Intel x86 emulation layer)
softwareupdate --install-rosetta

- Install Homebrew in Apple Silicon (ARM) mode
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

- Install Homebrew in Intel mode
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

- Install nvm
arch -x86_64 /bin/bash -c "wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"

# Now you can add these binaries to your path in .zsh_profile

# The new Macs allow you to mix Intel software with native ARM compilations.

# Some minimal housekeeping is required to ensure the right paths are included in the profile.

# Apple Silicon (ARM) brew writes binaries to /opt/homebrew/bin

# Intel brew binaries are stored (as usual) in /usr/local/Homebrew/bin

Preference should be given to Apple Silicon binaries over Intel where possible

export PATH=/opt/homebrew/bin:/usr/local/Homebrew/bin:$PATH

# Remember to export the nvm path (should be done automatically by the script)
----

====
.Install Node.js
[%collapsible]
====
[source,js]
----

Install - Node.js
arch -x86_64 nvm install 16

Install docker for m1 by google search “docker install m1” and run it

----
====
.Install Python on M1 Mac
[%collapsible]
====
[source,js]
----
brew install pyenv
pyenv install 2.7.18
export PATH="$(pyenv root)/shims:${PATH}"
echo 'PATH=$(pyenv root)/shims:$PATH' >> ~/.zshrc
pyenv global 2.7.18

----
====
// Is python v 2.7.18 still correct as the latest version is 3.11.1?
=== Download and execute the installation script

Download Lisk Core:

[tabs]
====
Mainnet::
+
--
*Linux:*

[source,bash]
----
curl -o lisk-core.tar.gz https://downloads.lisk.com/lisk/mainnet/3.0.4/lisk-core-v3.0.4-linux-x64.tar.gz
----

*MacOS:*

[source,bash]
----
curl -o lisk-core.tar.gz https://downloads.lisk.com/lisk/mainnet/3.0.4/lisk-core-v3.0.4-darwin-x64.tar.gz
----
--
Testnet::
+
--
*Linux:*

[source,bash]
----
curl -o lisk-core.tar.gz https://downloads.lisk.com/lisk/testnet/3.0.4/lisk-core-v3.0.4-linux-x64.tar.gz
----

*MacOS:*

[source,bash]
----
curl -o lisk-core.tar.gz https://downloads.lisk.com/lisk/testnet/3.0.4/lisk-core-v3.0.4-darwin-x64.tar.gz
----
--
====

Unpack it, and add it to the system path, in order to use it in the terminal:

[source,bash]
----
tar -xf ./lisk-core.tar.gz
cd lisk-core
./bin/lisk-core
----

[TIP]

====

You can make the `lisk-core` command available in the PATH, e.g. by executing the following:

[source,bash]
----
export PATH="$PATH:$HOME/lisk-core/bin"
----

See {url_set_path}[^] for more information.

To make `lisk-core` permanently available in the CLI, add the above snippet to `~/.bashrc`.

To reload `.bashrc`, run the following command:

[source,bash]
----
source ~/.bashrc
----
====

=== Verify successful installation

To verify that your Lisk node is up and running, execute the following command:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk-core start --network mainnet
----

[NOTE]
=====
The default log levels for Mainnet are:
// Please check if this is correct..
[source,json]
----
"system": {
    "logLevel": "info",
},
----

When the node is started, the logs will be visible in the console.
You can adjust the level of logging as per your preference. Supported log levels are: `trace`, `debug`, `info`, `warn`, `error`, and `fatal`.
To reduce the number of logs, it is recommended to set the log levels to `warn` or higher.

Alternatively, start the node with the following flag:

[source,bash]
----
lisk-core start --network mainnet --log=info
----

// See the xref:{url_run_logging}[logging] guide for more information about logging.
=====
--
Testnet::
+
--
[source,bash]
----
lisk-core start --network testnet
----
--
====

include::partial$core-post-installation.adoc[]
