= Lisk Core Binary Setup
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Binary Setup describes all necessary steps and requirements to install the Lisk SDK.
:toc:
:v_sdk: master
:url_upgrade_binary: upgrade/binary.adoc
:url_troubleshooting: troubleshooting.adoc
:url_admin_binary: administration/binary.adoc
:url_config_api_access: configuration.adoc#api_access
:url_config: configuration.adoc
:url_config_logrotation: configuration.adoc#logrotation

This document details how to setup Lisk Core Binary distribution on a system.

[[pre_install]]
== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, please proceed to the <<install, Installation>> chapter.

=== Determine if your platform can run Lisk Core

==== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64


include::partial$core-ports.adoc[]

=== Install dependencies

[source,bash]
----
sudo apt-get update
sudo apt-get install curl wget tar unzip zip ntp
----

include::partial$create-a-new-user.adoc[]

[[install]]
== Installation

This section details how to install Lisk Core using pre-built binary packages.
Once completed, you will have a functioning node on the Lisk Network.
If you are looking to upgrade your current Lisk Core installation, please see the xref:{url_upgrade_binary}[Upgrade Binary] section.

=== Login to the Lisk user

The user was created in the <<pre_install,Binary - Prerequisites Section>>.
If you are already logged in to this user, please skip this step.

[source,bash]
----
sudo -u lisk -i
----

=== Execute the installation script

This will configure the environment, download and install Lisk Core.
Before proceeding, determine whether you wish to connect your node to the Testnet (Test Network) or the Mainnet (Main Network).

[tabs]
====
Mainnet::
+
--
Download Lisk Core:

[source,bash]
----
wget https://downloads.lisk.io/lisk/main/installLisk.sh
----

To connect your node to the Mainnet, run:

[source,bash]
----
bash installLisk.sh install -r main
----
--
Testnet::
+
--
Download Lisk Core:

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/installLisk.sh
----

To connect your node to the Testnet, run:

[source,bash]
----
bash installLisk.sh install -r test
----
--
====

You will be prompted for your installation directory, pressing enter will choose the default.

Next, you will be prompted, if you wish to synchronize from the Genesis block.
If you answer `no', which is the default option, the node will download a recent snapshot of the database.
This will be much faster than synching from the genesis block.

The installation may take a few minutes.
Check the output of the script to verify that the installation was successful.

If you recognize an error, try to resolve it by analyzing the error output, otherwise, you can have a look at our xref:{url_troubleshooting}[Troubleshooting Section].

=== Verify successful installation

When the installation script has finished, navigate inside of the newly created folder `lisk-main`(for Mainnet) or `lisk-test`(for Testnet).
You can verify that your Lisk node is up and running, by running the following command:

[source,bash]
----
bash lisk.sh status
----

For further information and how to administer your Lisk node, please have a look at our xref:{url_admin_binary}[Administration Section].

If you are not running Lisk locally, you will need to follow the xref:{url_config_api_access}[Configuration - API] document to enable access.

With all of the above steps complete you are ready to move on to the configuration documentation if you wish to enable forging or SSL, please see xref:{url_config}[General Configuration].

== Post-installation (optional)

* Recommended: Set up a xref:{url_config_logrotation}[log rotation]
