= Binary installation
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Binary Setup describes all necessary steps and requirements to install the Lisk SDK.
:toc:
:v_sdk: master
:page-next: /lisk-core/3.0.0/management/binary.html
:page-next-title: Binary commands

:url_dev_forum: https://dev.lisk.io/

:url_upgrade_binary: update/binary.adoc
:url_admin_binary: management/binary.adoc
:url_config_api_access: management/api-access.adoc
:url_config: management/configuration.adoc
:url_config_logrotation: management/logs.adoc#logrotation
:url_core_2_setup: master@lisk-core::setup/binary.adoc#install

This document details how to setup Lisk Core Binary distribution on a system.

[[pre_install]]
== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, please proceed to the <<install, Installation>> chapter.

=== Determine if your platform can run Lisk Core

==== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64


include::partial$core-ports.adoc[]

=== Install dependencies

[source,bash]
----
sudo apt-get update
brew install curl wget tar unzip zip ntp
----

include::partial$create-a-new-user.adoc[]

[[install]]
== Installation

This section details how to install Lisk Core using pre-built binary packages.
Once completed, you will have a functioning node on the Lisk Network.
If you are looking to upgrade your current Lisk Core installation, please see the xref:{url_upgrade_binary}[Upgrade Binary] section.

=== Login to the Lisk user

Creating the user is described in the <<pre_install,Binary - Prerequisites Section>>.
Please note, this login described here is for ubuntu. However, if you are already logged in to this user, please skip this step.

[source,bash]
----
sudo -u lisk -i
----

=== Execute the installation script

This will configure the environment, download and install Lisk Core.
Before proceeding, determine whether you wish to connect your node to the Testnet, (Test Network) or the Betanet.

[tabs]
====
Betanet::
+
--
Download Lisk Core:

[source,bash]
----
wget https://downloads.lisk.io/lisk/beta/installLisk.sh
----

To connect your node to the Betanet, run the following command:

[source,bash]
----
bash installLisk.sh install -r beta
----
--


Testnet::
+
--
See xref:{url_core_2_setup}[Lisk Core 2.1.5 binary setup]
--
====

A prompt will now appear regarding your installation directory, pressing enter will choose the default.

Next, a following prompt will appear asking if you wish to synchronize from the Genesis block.
If you answer `no', which is the default option, the node will download a recent snapshot of the database.
This will be much faster than synchronizing from the genesis block.

The installation may take a few minutes.
Please check the output of the script to verify that the installation was successful.

If an error appears, try to resolve it by analyzing the error output.
If this is not possible, please refer to the xref:{url_dev_forum}[Developer's Forum].

=== Verify successful installation

When the installation script has finished, navigate inside of the newly created folder `lisk-beta`(for Betanet) or `lisk-test`(for Testnet).
It is possible to verify that your Lisk node is up and running, by running the following command:

[source,bash]
----
bash lisk.sh status
----

For further information and how to administer your Lisk node, please see the xref:{url_admin_binary}[Management Section].

If you are not running Lisk locally, you will need to follow the xref:{url_config_api_access}[Configuration - API] document to enable access.

If all of the above steps have been successfully completed, then the next step is to move on to the configuration documentation.
If you wish to enable forging or SSL, please see xref:{url_config}[General Configuration].

== Post-installation (optional)

* In this case, it is recommended to set up a xref:{url_config_logrotation}[log rotation]
