= Lisk Core Setup with Lisk Commander
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:v_sdk: 2.3.5

Setup and manage your Lisk node conveniently with Lisk Commander.

[NOTE]
====
This setup option is supported from Lisk Core v2.0.0 upwards.
If you have Lisk Core v1.6 or lower installed, you wont be able to upgrade your node with Lisk Commander.
In this case, use the bash script or remove your old version and make a fresh install with Lisk Commander.
====

== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64
* MacOS 10.12 (Sierra)
* MacOS 10.13 (High Sierra)

== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, please proceed to the <<_installation, Installation>> chapter.

=== Install Lisk Commander

Head to the Lisk Commander docs and follow the xref:{v_sdk}@lisk-sdk::lisk-commander/index.adoc#_setup[installation instructions].

Once Lisk Commander is set up on your system, you can use the commands below to set up/manage your Lisk Core node.

== Installation

[IMPORTANT]
====
Don't run this command with a user with `sudo` rights. +
If you do so, the installation will be aborted, as it is not needed and recommended to install Lisk Core for a user with `sudo` rights.
====

[TIP]
====
You can freely choose the name of your Lisk Core instance.

Just be aware that you need to refer to your custom name instead of `lisk-mainnet` or `lisk-testnet` when running the commands.
====

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:install lisk-mainnet
----

This will install Lisk Core latest version into a directory `lisk-mainnet`.

To verify your node is running correctly, run e.g.

[source,bash]
----
lisk core:status lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:install --network=testnet lisk-testnet
----

This will install Lisk Core latest version into a directory `lisk-testnet`.

To verify your node is running correctly, run e.g.

[source,bash]
----
lisk core:status lisk-testnet
----
--
====

TIP: See for all available options the Lisk Commander xref:{v_sdk}@lisk-sdk::lisk-commander/user-guide/lisk-core.adoc[Command reference for Lisk Core] as well as the xref:{v_sdk}@lisk-sdk::lisk-commander/user-guide/commands.adoc[general Command reference].

=== Available options

|===
| Full Name | Short Name | Examples | Description

| `--network` | `-n`
a|
* `--network=testnet`
* `--network=betanet`
* `-n=alphanet`
* `--network=devnet`
| The network, you want to Lisk Core to connect to. If you don't specify this option, it will connect to the default network (Mainnet).

| `--release-url` | `-r`
| `--release-url=https://my-custom.url/testnet/2.1.0-rc.0/lisk-2.1.0-rc.0-Linux-x86_64.tar.gz`
| Define a custom URL for downloading the new Lisk Core binary script.
You also need to have the checksum for the TAR file with the format 2.0.0-Linux-x86_64.tar.gz.SHA256 for the Commander to check the integrity of the binary.
You can refer to our https://downloads.lisk.io/lisk/mainnet/{v_core}/[binary release] for the file naming convention.

| `--lisk-version` | N/A
a|
* `--lisk-version=2.0.0`
* `--lisk-version=2.1.3`
| Define the concrete version, Lisk Core should be upgraded to.
If you don't specify the version, it will install the latest stable version of Lisk Core.

| `--snapshot-url` | `-s`
| `--snapshot-url=http://snapshots.lisk.io.s3-eu-west-1.amazonaws.com/lisk/testnet/lisk_test_backup-9299232.gz`
| Define a custom URL for downloading the xref:index.adoc#_snapshots[snapshot], that should be used during the setup of Lisk Core.

| `--no-snapshot` | N/A
| N/A | Set this option, if you do not want to use any snapshot during the setup of Lisk Core.
In this case, your node will synchronize the whole blockchain, starting from genesis block.
If you choose this option, the setup process will take a significantly longer time.

| `--no-start` | N/A
| N/A | Set this option, if you don't want to start Lisk Core automatically after the installation.
|===


== Post-Install

After installation, check which ports Lisk Core is listening by checking the status:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:status lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:status lisk-testnet
----
--
====

Check you network settings to verify, the corresponding ports are open.

It’s also recommended to set up a xref:configuration.adoc#_logrotation[log rotation].

If you are not running Lisk locally, you will need to follow the xref:configuration.adoc#_api_access_control[Configuration - API] document to enable access.

With all of the above steps complete you are ready to move on to the configuration documentation if you wish to enable forging or SSL, please see xref:configuration.adoc[General Configuration].
