= Commander application set up
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Commander application setup describes all necessary steps and requirements to install the Lisk SDK via Lisk Commander.
:toc:
:v_sdk: master
:v_core: 2.1.5
:page-next: /lisk-core/management/commander.html
:page-previous: /lisk-core/interact-with-network.html
:page-next-title: Commander application commands
:page-previous-title: Interact with the network

:url_sdk_commander_setup: {v_sdk}@lisk-sdk::lisk-commander/index.adoc#setup
:url_sdk_commander_liskcore: {v_sdk}@lisk-sdk::lisk-commander/user-guide/lisk-core.adoc
:url_sdk_commander_commands: {v_sdk}@lisk-sdk::lisk-commander/user-guide/commands.adoc
:url_binary_download: https://downloads.lisk.io/lisk/mainnet/{v_core}/
:url_snapshots: index.adoc#snapshots
:url_config_logrotation: management/logs.adoc#logrotation
:url_config_api_access: management/api-access.adoc#api-access
:url_config: management/configuration.adoc

Setup and manage your Lisk Core conveniently with Lisk Commander.


== Pre-install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, please proceed to the <<install, Installation>> chapter.

=== Install Lisk Commander

Please access the Lisk Commander docs and follow the xref:{url_sdk_commander_setup}[installation instructions].

Once the Lisk Commander is set up on your system, it is possible use the commands below to set up and manage your Lisk Core node.

[[install]]
== Installation

[IMPORTANT]
====
Do not run this command with a user that has `sudo` rights. +
If this is executed then the installation will be aborted, as it is not required and not recommended to install Lisk Core for a user with `sudo` rights.
====

[TIP]
====
You can freely choose the name of your Lisk Core instance.

Please note that it is necessary to refer to your custom name instead of `lisk-mainnet` or `lisk-testnet` when running the commands.
====

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:install lisk-mainnet
----

This will install the latest version of Lisk Core into a directory `~/.lisk/instances/lisk-mainnet`.

To verify your node is running correctly, execute the following command:

[source,bash]
----
lisk core:status lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:install --network=testnet lisk-testnet
----

This will install the latest version of Lisk Core into a directory `~/.lisk/instances/lisk-testnet`.

To verify your node is running correctly, execute the following command:

[source,bash]
----
lisk core:status lisk-testnet
----
--
====

TIP: For all available options, see the Lisk Commander xref:{url_sdk_commander_liskcore}[command reference for Lisk Core] as well as the xref:{url_sdk_commander_commands}[General command reference].

=== Available options

Add one or multiples of the options below to the `core:install` command.
Multiple options are seperated by spaces.

|===
| Full Name | Short Name | Examples | Description

| `--network` | `-n`
a|
* `--network=testnet`
* `--network=betanet`
* `-n=alphanet`
* `--network=devnet`
| The network, you require Lisk Core to connect to. If you don't specify this option, it will connect to the default network, (Mainnet).

| `--release-url` | `-r`
| `--release-url=https://my-custom.url/testnet/2.1.0-rc.0/lisk-2.1.0-rc.0-Linux-x86_64.tar.gz`
| Define a custom URL for downloading the new Lisk Core application script.
It is also required to have the checksum for the TAR file with the format 2.0.0-Linux-x86_64.tar.gz.SHA256 for the Commander to check the integrity of the application.
You can refer to our {url_binary_download}[Lisk Core application releases^] for the file naming convention.

| `--lisk-version` | N/A
a|
* `--lisk-version=2.0.0`
* `--lisk-version=2.1.3`
| Define the concrete version, Lisk Core should be upgraded to.
If you do not specify the version, it will install the latest stable version of Lisk Core.

| `--snapshot-url` | `-s`
| `--snapshot-url=http://snapshots.lisk.io.s3-eu-west-1.amazonaws.com/lisk/testnet/lisk_test_backup-9299232.gz`
| Define a custom URL for downloading the xref:{url_snapshots}[snapshot], that should be used during the setup of Lisk Core.

| `--no-snapshot` | N/A
| N/A | Set this option, if you do not want to use any snapshot during the setup of Lisk Core.
In this case, your node will synchronize to the whole blockchain, starting from the genesis block.
If you choose this option, it will take quite a significant amount of time to complete the the setup process.

| `--no-start` | N/A
| N/A | Set this option, if you do not wish the Lisk Core to start automatically after the installation.
|===


== Post-install

After the installation is completed, check which ports Lisk Core is listening to by checking the status as shown below:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:status lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:status lisk-testnet
----
--
====


Check you network settings to verify the corresponding ports are open.

In addition it is also recommended to set up a xref:{url_config_logrotation}[log rotation].

If you are not running Lisk locally, you will need to follow the xref:{url_config_api_access}[Configuration - API] guide to enable access.

Assuming all of the above steps have been successfully completed, then the next step is to move on to the configuration documentation. If you wish to enable forging or SSL, please see the xref:{url_config}[General configuration].
