= Docker image
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes all necessary steps and requirements to install Lisk Service with Docker.
:toc:
:page-next: /lisk-service/configuration.html
:page-next-title: Configuration

:url_github_service: https://github.com/LiskHQ/lisk-service
:url_docker_install: https://docs.docker.com/engine/installation/#desktop
:url_docker_install_linux: https://docs.docker.com/engine/installation/#server
:url_docker_install_linux_compose: https://docs.docker.com/compose/install/
:url_docker_install_mac: https://docs.docker.com/docker-for-mac/install/
:url_docker_install_windows: https://docs.docker.com/docker-for-windows/install/
:url_docker_linux_post_install: https://docs.docker.com/install/linux/linux-postinstall/

:url_config: configuration.adoc

== Prerequisites

This document covers how to prepare a system in order to run Lisk Core as a Docker-based container.
To run Lisk in Docker a user must first install the Docker Engine.
Additionally, it is recommended to install Docker Compose for convenience.

Firstly, determine if your platform can run Docker as described below.

=== Supported platforms

Please refer to {url_docker_install}[https://docs.docker.com/engine/installation^]

[tabs]
====
Ubuntu::
+
--
Please refer to {url_docker_install_linux}[docker installation for ubuntu^].

To install Docker Compose, please refer to {url_docker_install_linux_compose}[install docker compose^].

IMPORTANT: Configure Docker, so it can be run without `sudo` rights: {url_docker_linux_post_install}[linux post install^].

Install `make` using your package manager.
For example, use `apt-get` if running Ubuntu as shown in the following command below:

[source,bash]
----
sudo apt-get install curl make
----
--
MacOS::
+
--
Please refer to {url_docker_install_mac}[Docker installation for Mac^].
Please note that Docker for Mac already includes Docker Compose.
Install `make` using {url_xcode}[XCode^].
--
Windows::
+
--
Please refer to {url_docker_install_windows}[Docker installation for Windows^].
Please note that Docker for Windows includes Docker Compose.
--
====

=== Open necessary ports

These are the default ports for connecting with the network, and can be altered later in `.env`.

== Installation

Clone the {url_github_service}[lisk-service^] GitHub repository and then navigate into the project folder.

Then `npm run` the script `docker:build`.

[source,bash]
----
git clone https://github.com/LiskHQ/lisk-service.git
cd lisk-service
npm run docker:build <1>
----

<1> The last command will build Lisk Service for you and install all dependencies.

Lisk Service is now ready to use on your machine.

You may now directly start it with:

[source,bash]
----
cd docker/
make -f Makefile.mainnet up
----

This will start Lisk Service with the default configuration, which will connect to a Lisk Core Mainnet node.

In case a different node or network shall be used, you need to xref:{url_config}[configure] Lisk Service accordingly.
