= Docker image
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Docker image setup describes all necessary steps and requirements to install the Lisk SDK with Docker.
:toc:
:page-next: /lisk-core/3.0.0/management/docker.html
:page-previous: /lisk-core/3.0.0/interact-with-network.html
:page-next-title: Docker image commands
:page-previous-title: Interact with the network

:url_docker_install: https://docs.docker.com/engine/installation/#desktop
:url_docker_install_linux: https://docs.docker.com/engine/installation/#server
:url_docker_install_linux_compose: https://docs.docker.com/compose/install/
:url_docker_install_mac: https://docs.docker.com/docker-for-mac/install/
:url_docker_install_windows: https://docs.docker.com/docker-for-windows/install/
:url_docker_linux_post_install: https://docs.docker.com/install/linux/linux-postinstall/
:url_lisk_core_repository: https://github.com/LiskHQ/lisk-core
:url_lisk_explorer_betanet: https://betanet-explorer.lisk.io/
:url_lisk_explorer_testnet: https://testnet-explorer.lisk.io/
:url_lisk_explorer_mainnet: https://explorer.lisk.io/
:url_xcode: https://developer.apple.com/xcode/features/

:url_admin_docker: management/docker.adoc
:url_docker_sync_snapshot: management/docker.adoc#sync_from_a_snaphot

== Pre-install

This document covers how to prepare a system in order to run Lisk Core as a Docker-based container.
To run Lisk in Docker a user must first install the Docker Engine.
Additionally, it is recommended to install Docker Compose for convenience.

Firstly, determine if your platform can run Docker as described below.

=== Supported platforms

Please refer to {url_docker_install}[https://docs.docker.com/engine/installation^]

[tabs]
====
Ubuntu::
+
--
Please refer to {url_docker_install_linux}[docker installation for ubuntu^].

To install Docker Compose, please refer to {url_docker_install_linux_compose}[install docker compose^].

IMPORTANT: Configure Docker, so it can be run without `sudo` rights: {url_docker_linux_post_install}[linux post install^].

Install `make` using your package manager.
For example, use `apt-get` if running Ubuntu as shown in the following command below:

[source,bash]
----
sudo apt-get install curl make
----
--
MacOS::
+
--
Please refer to {url_docker_install_mac}[Docker installation for Mac^].
Please note that Docker for Mac already includes Docker Compose.
Install `make` using {url_xcode}[XCode^].
--
Windows::
+
--
Please refer to {url_docker_install_windows}[Docker installation for Windows^].
Please note that Docker for Windows includes Docker Compose.
--
====

include::partial$core-ports.adoc[]

These are the default ports for connecting with the network, and can be altered later in `.env`.

=== Create a new user

To run and manage a Lisk Core node in the future, please create a separate `lisk` user as described below:

[tabs]
====
Ubuntu::
+
--
[TIP]
=====
The `lisk` user itself *does not need* any `sudo` rights to run the Lisk Core.

It is sufficient to create a group `docker`, and then add the newly created user to that group, in order to enable the user to use Docker, Please see: https://docs.docker.com/install/linux/linux-postinstall/.
=====

[source,bash]
----
sudo adduser lisk              <1>
sudo groupadd docker           <2>
sudo usermod -aG docker lisk   <3>
----

<1> Create a new user.
<2> Create a docker group.
<3> Add the user to the docker group.
--
MacOS::
+
--
It is not necessarily required to set up a `lisk` user, especially when you are running a local instance for development purposes.

However, if it is required then it is recommended to create the user using the macOS GUI: https://support.apple.com/en-gb/guide/mac-help/mtusr001/mac
--
====

[[install]]
== Installation

=== Get configuration and Makefile

Clone the {url_lisk_core_repository}[Lisk Core Repository^].

[source,bash]
----
sudo -u lisk -i                                    <1>
git clone https://github.com/LiskHQ/lisk-core.git  <2>
cd lisk-core/docker                                <3>
git checkout master                                <4>
----

<1> Switch to lisk user.
<2> Clone the repository.
<3> Navigate into the docker directory.
<4> Checkout master branch for last stable version of Lisk Core.

This contains a directory `docker` with the following files:

* `.env.development`
* `.env.betanet`
* `.env.mainnet`
* `.env.testnet`
* `docker-compose.make.yml`: used by `make coldstart`.
* `docker-compose.override.yml`: use this file to overwrite `LISK_` variables, (empty by default).
* `docker-compose.redis.yml`: enable cache, (optional).
* `docker-compose.yml`
* `Makefile`

The `.env`-files are templates with network specific environment variables which are described below:

[[environment-variables]]
=== Set environment variables

To connect to the Lisk network, the environment variables need to be set accordingly.

Before setting the variables, you may wish to edit them in the respective `.env.<network>` file.

It is recommended to change the password for the database, which is stored in `ENV_LISK_DB_PASSWORD`.

To install a specific version of Lisk Core, set the `ENV_LISK_VERSION` to the respective version.

After adjusting them, copy the environment variables to a file called `.env`:

[source,bash]
----
cp .env.<network> .env
----

Where `<network>` refers to the Lisk network that you wish to establish a connection to.

=== Coldstart application

==== Option 1: Makefile

It is recommended to use the Makefile.
Makefile provides a convenient way to xref:{url_docker_sync_snapshot}[sync from a snapshot]:

[source,bash]
----
make coldstart  <1>
----

<1> This will download and restore from a recent blockchain snapshot.

[NOTE]
====
If you wish to synchronize your node starting from the genesis block, it may take a significant amount of time until your local node will be fully synchronized with the blockchain network.
It is recommend to use `make coldstart` in case your node is required to be used without delay.
====

[source,bash]
----
make <1>
----

<1> This will synchronize from the genesis block on the first startup.

==== Option 2: docker-compose

[source,bash]
----
docker-compose up -d <1>
docker-compose ps    <2>
docker-compose logs  <3>
----

<1> Initialize Lisk Core.
<2> Enables the status of Lisk Core to be viewed.
<3> Enables the logs to be viewed.

=== Verify

The final step is to verify that your node is connected and in sync with the network.
For example, by enquiring about your node's status from using the API as shown below:

[source,bash]
----
docker-compose exec lisk curl http://localhost:<PORT>/api/node/status --header "accept: application/json"
----

Where `<PORT>` is the network specific `httpPort` of your node.

The result should appear as shown below:

[source,json,linenums]
----
{
  "meta": {},
  "data": {
    "consensus": 94,
    "currentTime": 1558358294074,
    "secondsSinceEpoch": 94249094,
    "height": 8306047,
    "loaded": true,
    "networkHeight": 8306047,
    "syncing": false,
    "transactions": {
      "confirmed": 928836,
      "unconfirmed": 0,
      "unprocessed": 0,
      "unsigned": 0,
      "total": 928836
    }
  },
  "links": {}
}
----

When your node is synchronized, the values of `networkHeight` and `height` should be either equal or almost equal.

To fully verify that your node is in sync with the network, go to the {url_lisk_explorer_betanet}[Lisk Explorer(Betanet)^] and compare the network height in the explorer with the height of your node.
Again, they should be either equal or almost equal.

If necessary, use the different Explorer tools for further verification, such as comparing the last forged blocks on the chain.

From this point onwards your node should be fully functional.

To proceed to the next step, please see the xref:{url_admin_docker}[Docker image] to learn how to manage your node.

== Post-installation (optional)

=== Ubuntu

You may wish to set up a service for Lisk Core that enables an automatic restart after the server restarts.
This can be performed as shown below:

....
# /etc/systemd/system/docker-compose-lisk.service

[Unit]
Description=Docker Compose Application Service
Requires=docker.service
After=docker.service

[Service]
WorkingDirectory=/home/lisk/lisk-core/docker/testnet/
ExecStart=/usr/local/bin/docker-compose up
TimeoutStartSec=0
Restart=on-failure
StartLimitIntervalSec=60
StartLimitBurst=3

[Install]
WantedBy=multi-user.target
....

[NOTE]
====
*For delegates:* It will still be necessary to enable forging manually after a restart of Lisk Core.
====

To enable this service, execute the following command:

[source,bash]
----
systemctl enable docker-compose-lisk
----

Check the service by executing the following commands:

[source,bash]
----
systemctl status docker-compose-lisk.service <1>
sudo journalctl -u docker-compose-lisk.service <2>
----

<1> Displays the status of the service.
<2> Displays the logs of the service.
