= Installation with Docker
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes all necessary steps and requirements to install Lisk Service with Docker.
:toc:
:experimental:
:page-next: /lisk-service/configuration/docker.html
:page-next-title: Configuration with Docker

:url_github_service: https://github.com/LiskHQ/lisk-service
:url_docker_hub: https://hub.docker.com/
:url_docker_install_linux: https://docs.docker.com/engine/install
:url_docker_install_linux_compose: https://docs.docker.com/compose/install/
:url_docker_install_mac: https://docs.docker.com/docker-for-mac/install/
:url_docker_install_windows: https://docs.docker.com/docker-for-windows/install/
:url_docker_linux_post_install: https://docs.docker.com/install/linux/linux-postinstall/
:url_xcode: https://developer.apple.com/xcode/features/

:url_index_usage: index.adoc#usage
:url_setup: setup/index.adoc
:url_core_setup_npm: v3@lisk-core::setup/npm.adoc
:url_config: configuration/docker.adoc
:url_management: management/docker.adoc
:sectnums:

How to set up Lisk Service and connect it to a local Lisk Core node.

== Setting up Lisk Core

Lisk Service is installed in addition to a Lisk blockchain application such as Lisk Core, in order to provide enriched network data for third-party services.

The first step is therefore to install Lisk Core.

It is recommended to use NPM to conveniently install Lisk Core through the command line:

[source,bash]
----
npm install --global --production lisk-core
----

Check out the xref:{url_core_setup_npm}[Lisk Core NPM setup] guide for more information on how to install Lisk Core on your machine.

== Configuring Lisk Core

Use the Lisk Core CLI to start Lisk Core with the desired configurations.

The `--network` flag defines which blockchain network Lisk Core will connect to.

`--api-ws` enables the WebSocket API of the node.

`--api-ws-port` allows the user to define the port for the WebSocket connection.

[source,bash]
----
lisk-core start --network betanet --api-ws --api-ws-port=8080 --overwrite-config
----

NOTE: To connect to a different network, replace `betanet` with either `mainnet`, `testnet` or `devnet`.

== Setting up Lisk Service

=== Prerequisites

The following dependencies are required to install and run Lisk Service with Docker.

==== Development tools

[tabs]
====
Ubuntu / Debian::
+
--
Install the `build-essential` package alongside with several development tools.

For example, use `apt` if running Ubuntu as shown in the following command below:

[source,bash]
----
apt install build-essential git
----
--
MacOS::
+
--

*Brew*

Install https://brew.sh/[Brew] by following https://brew.sh/[the most recent instruction].

If you already have Brew installed, ensure it is working and is the latest version.

[source,bash]
----
brew update
brew doctor
----

*Xcode*

Install https://developer.apple.com/xcode/[Xcode] essentials coming from Apple.

[source,bash]
----
xcode-select --install
----
--
====

==== Docker

[tabs]
====
Ubuntu / Debian::
+
--
Please refer to {url_docker_install_linux}[docker installation for ubuntu^].

To install Docker Compose, please refer to {url_docker_install_linux_compose}[install docker compose^].

TIP: To configure Docker so it can be run without `sudo` rights, follow: {url_docker_linux_post_install}[linux post install^].
--
MacOS::
+
--
Please refer to {url_docker_install_mac}[Docker installation for Mac^].
Please note that Docker for Mac already includes Docker Compose.
Install `make` using {url_xcode}[XCode^].
--
====


==== Open necessary ports

Ensure the port which allows external services communication with the Lisk Service APIs is open.

- 9901: Default API port (HTTP & WebSocket)

=== Installation of Lisk Service

Clone the {url_github_service}[lisk-service^] GitHub repository and then navigate into the project folder.

.In the directory where you want to store Lisk Service
[source,bash]
----
git clone https://github.com/LiskHQ/lisk-service.git
cd lisk-service
git checkout v0.4.0
----

== Build Lisk Service

Build Lisk Service from local files:

./lisk-service/
[source,bash]
----
make build
----

Lisk Service is now ready to use on your machine.

== Connecting Lisk Service to Lisk Core

To connect Lisk Service to a local Lisk Core node, set the environment variable `LISK_CORE_WS` before starting Lisk Service as shown below:

.Inside of the `lisk-service` root folder
[source,bash]
----
export LISK_CORE_WS=ws://localhost:8080
#export ENABLE_HTTP_API=http-status,http-version2
#export ENABLE_WS_API=blockchain,rpc-v2
# Command to start Lisk Service
make up
----

It's possible to configure Lisk Service by exporting environment variables which override the default option which are located under `docker/network/core3-default.env`.

The three available environment variables are:

* `LISK_CORE_WS`: Path to the Lisk Core WS port.
* `ENABLE_HTTP_API`: List of HTTP APIs that will be enabled in Lisk Service.
* `ENABLE_WS_API`: List of WebSocket APIs that will be enabled in Lisk Service.

////
Alternatively, it is possible to define a file with all the desired environment variables and use it to start Lisk Service as shown below:

./lisk-service/
[source,bash]
----
cd docker/network
vim my-env.env
----

Define key-value pairs of all desired environment variables, for example:

TIP: Press kbd:[i] to enter the insert mode in vim.

./lisk-service/docker/network/my-env.env
[source,bash]
----
# Lisk ecosystem configuration
LISK_CORE_WS=ws://localhost:8080

# Enabled Gateway APIs
ENABLE_HTTP_API=http-status,http-version2
ENABLE_WS_API=blockchain,rpc-v2
----

TIP: Save and quit vim again by first leaving the insert mode with kbd:[Esc] and then by typing kbd:[:wq] and kbd:[Enter].

Now start Lisk Service with the following command:

./lisk-service/
[source,bash]
----
make up-custom-my-env
----

This will start Lisk Service with all the environment variables previously defined in `my-env.env`.
////

== Stopping Lisk Service
You can stop Lisk Service again with the following command:

[source,bash]
----
make down
----

More commands about how to manage Lisk Service are described on the xref:{url_management}[Docker commands] page.

TIP: Check the xref:{url_index_usage}[Usage] section for examples of how to use and interact with Lisk Service.
