= Installation with Docker
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes all necessary steps and requirements to install Lisk Service with Docker.
:toc:
:page-next: /lisk-service/configuration/docker.html
:page-next-title: Configuration with Docker

:url_github_service: https://github.com/LiskHQ/lisk-service
:url_docker_install: https://docs.docker.com/engine/installation/#desktop
:url_docker_install_linux: https://docs.docker.com/engine/installation/#server
:url_docker_install_linux_compose: https://docs.docker.com/compose/install/
:url_docker_install_mac: https://docs.docker.com/docker-for-mac/install/
:url_docker_install_windows: https://docs.docker.com/docker-for-windows/install/
:url_docker_linux_post_install: https://docs.docker.com/install/linux/linux-postinstall/
:url_xcode: https://developer.apple.com/xcode/features/

:url_config: configuration.adoc

A guide about the default installation for Lisk Service.

== Prerequisites

The following dependencies are required to install and run Lisk Service with Docker.

=== Development tools

[tabs]
====
Ubuntu / Debian::
+
--
Install the `build-essential` package alongside with several development tools.

For example, use `apt` if running Ubuntu as shown in the following command below:

[source,bash]
----
apt install build-essential git
----
--
MacOS::
+
--

*Brew*

Install https://brew.sh/[Brew] by following https://brew.sh/[the most recent instruction].

If you already have Brew installed, make sure it is working and up-to-date.

[source,bash]
----
brew update
brew doctor
----

*Xcode*

Install https://developer.apple.com/xcode/[Xcode] essentials coming from Apple.

[source,bash]
----
xcode-select --install
----
--
====

=== Docker

Please refer to {url_docker_install}[https://docs.docker.com/engine/installation^]

[tabs]
====
Ubuntu / Debian::
+
--
Please refer to {url_docker_install_linux}[docker installation for ubuntu^].

To install Docker Compose, please refer to {url_docker_install_linux_compose}[install docker compose^].

TIP: Configure Docker, so it can be run without `sudo` rights: {url_docker_linux_post_install}[linux post install^].
--
MacOS::
+
--
Please refer to {url_docker_install_mac}[Docker installation for Mac^].
Please note that Docker for Mac already includes Docker Compose.
Install `make` using {url_xcode}[XCode^].
--
====

=== Open necessary ports

These are the default ports for connecting with the network, they can be altered later in `.env`.

- 9901: API (HTTP)

== Installation

Clone the {url_github_service}[lisk-service^] GitHub repository and then navigate into the project folder.

.In the directory where you want to store Lisk Service
[source,bash]
----
git clone https://github.com/LiskHQ/lisk-service.git
cd lisk-service
----

Lisk Service is now ready to use on your machine.

You may now directly start it with:

.Inside of the `lisk-service` root folder
[source,bash]
----
make up
----

This will start Lisk Service with the default configuration, which will connect to a Lisk Core Mainnet node.

In case a different node or network shall be used, xref:{url_config}[configure] Lisk Service accordingly.

You can stop Lisk Service again with:

.Inside of the `lisk-service` root folder
[source,bash]
----
make down
----
