= Setup overview
Mona Bärenfänger <mona@lightcurve.io>

:url_binary: binary.adoc
:url_commander: commander.adoc
:url_docker: docker.adoc
:url_source: source.adoc



This section comprises of the setup prerequisites necessary for the xref:{url_binary}[Binary], xref:{url_commander}[Commander], xref:{url_docker}[Docker] and xref:{url_source}[Source] installation distributions.

Once the desired installation is chosen, it is required to fulfill the relevant conditions that pertain to that specific installation described in detail throughout this section.

Firstly, the information required to install Lisk core using pre-built binary packages is covered, followed by the
the requirements to set up and manage Lisk commander on your system for the Lisk core node.
In addition, the preparation necessary to run Lisk core as a docker-based container is described together with the available options.
Finally, the source installation prerequisites are also covered such as the port requirements, toolchain components, postgreSQL, etc., necessary before beginning the the Lisk core installation from source.