= How to maintain a node
Mona Bärenfänger <mona@lightcurve.io>
:description: Learn how to maintain a Lisk node and also when it is recommended to run a specific node.
:page-aliases: getting-started/maintain-a-node.adoc
:toc:
:page-previous: /lisk-core/index.html
:page-previous-title: Overview

:url_core_distributions: index.adoc#distributions
:url_binary_installation: setup/application.adoc
:url_lisk_commander: setup/commander-application.adoc
:url_docker: setup/docker-image.adoc
:url_source: setup/source.adoc

== How to set up a node?

Simply follow the node setup guide for your desired distribution.
This is described on the xref:{url_core_distributions}[Lisk Core overview] page.

There are four available distributions of Lisk Core which are described below:

=== Application

The *default* way to set up Lisk Core.
The xref:{url_binary_installation}[Application installation] is an easy and automated way to set up Lisk Core, which includes almost completed automated update scripts; together with a selection of tools to assist with seamlessly maintaining a Lisk node.

=== Commander application

Use the xref:{url_lisk_commander}[Lisk Commander application] to conveniently install and manage Lisk Core.

=== Docker image

xref:{url_docker}[Docker image] adds support for additional platforms upon which to run a Lisk node.
For example, running a Lisk node inside of a Docker image on Windows and connecting it via a custom node on Lisk Desktop to Lisk Core, without the necessity to rent an additional server.

=== Source code

This is designed for anyone wishing to develop on the Lisk Core codebase.
It also comes with an extensive test-suite, detailed in the following `README.md`.
An installation performed from xref:{url_source}[source code][[installing_lisk_from_source]] enables a developer to work on the latest codebase for Lisk Core, which may not have been tagged for a release yet.
