= Setup
Mona Bärenfänger <mona@lightcurve.io>
:description: How to install and setup up a Lisk Core node.
// Settings
// External URLs
// Project URLs
:url_binary_installation: setup/application.adoc
:url_setup_npm: setup/npm.adoc
:url_docker: setup/docker.adoc
:url_source: setup/source.adoc




[[distributions]]
== How to set up a node?

There are four available distributions of Lisk Core which are described below.
Simply follow the instructions in this setup guide for your desired distribution.

=== Application

The  xref:{url_binary_installation}[application installation] offers an easy and automated approach to set up Lisk Core.
This includes almost completely automated update scripts, together with a selection of tools to assist with seamlessly maintaining a Lisk Core node.

=== NPM setup

An easy way to xref:{url_setup_npm}[set up a Lisk Core node with NPM].

////
=== Docker image

The xref:{url_docker}[Docker image] adds support for additional platforms upon which to run a Lisk node.
 This offers the possibility to containerize the node.
////
=== Source code

The xref:{url_source}[installation from source code] is designed for anyone wishing to develop on the Lisk Core codebase.
It also comes with an extensive test-suite which is described in the `README.md`.
An installation performed from the source code enables a developer to work on the latest codebase of Lisk Core, which may not have been tagged for a release yet.
