= Setup
Mona Bärenfänger <mona@lightcurve.io>


:url_binary_installation: setup/binary.adoc
:url_lisk_commander: setup/commander.adoc
:url_docker: setup/docker.adoc
:url_source: setup/source.adoc




This section comprises of the setup prerequisites necessary for the Binary, Commander, Docker and Source installation distributions.

Once the desired installation is chosen, it is required to fulfill the relevant conditions that pertain to that specific installation described in detail throughout this section.




== How to set up a node?

There are four available distributions of Lisk Core which are described below. Simply follow the instructions in this setup guide for your desired distribution.




=== Binary

This is the *default* procedure to setup Lisk Core.
The xref:{url_binary_installation}[Binary installation] offers an easy and automated approach to set up Lisk Core, which includes almost completely automated update scripts, together with a selection of tools to assist with seamlessly maintaining a Lisk Node. This is the recommended installation for the less experienced user.

=== Commander

Use xref:{url_lisk_commander}[Lisk Commander] to conveniently install and manage Lisk Core. This version offers the possibility to configure various options whxh are described in the link above.

=== Docker

xref:{url_docker}[Docker] adds support for additional platforms upon which to run a Lisk node.
 This offers the possibility to containerize the node.

=== Source

This is designed for anyone wishing to develop on the Lisk Core codebase.
It also comes with an extensive test-suite, detailed in the following `README.md`.
An installation performed from xref:{url_source}[source] enables a developer to work on the latest codebase for Lisk Core, which may not have been tagged for a release yet.
