= Setup
Mona Bärenfänger <mona@lightcurve.io>
:description: The Set up page provides an overview of the prerequisites required for setting up a node.

:url_binary_installation: setup/application.adoc
:url_lisk_commander: setup/commander-application.adoc
:url_docker: setup/docker-image.adoc
:url_source: setup/source-code.adoc


This section comprises of the setup prerequisites necessary for the Application, Commander application, Docker image and Source code installations of Lisk Core.

Once the desired installation is chosen, it is required to fulfill the relevant conditions that pertain to that specific installation described in detail throughout this section.

== How to set up a node?

There are four available distributions of Lisk Core which are described below. Simply follow the instructions in this setup guide for your desired distribution.

=== Application

This is the *default* procedure to setup Lisk Core.
The xref:{url_binary_installation}[Application installation] offers an easy and automated approach to set up Lisk Core, which includes almost completely automated update scripts, together with a selection of tools to assist with seamlessly maintaining a Lisk Node. This is the recommended installation for the less experienced user.

=== Commander application

Use xref:{url_lisk_commander}[Lisk Commander application] to conveniently install and manage Lisk Core. 

=== Docker image

The xref:{url_docker}[Docker image] adds support for additional platforms upon which to run a Lisk node.
 This offers the possibility to containerize the node.

=== Source code

This is designed for anyone wishing to develop on the Lisk Core codebase.
It also comes with an extensive test-suite, detailed in the following `README.md`.
An installation performed from the xref:{url_source}[source code] enables a developer to work on the latest codebase of Lisk Core, which may not have been tagged for a release yet.
