== Lisk Core Setup

=== Table of contents

[cols=",",options="header",]
|===
|link:pre-install/preinstallation.md[Pre-Installation]
|link:install/installation.md[Installation]
|link:pre-install/binary/preinstall-binary.md[Binary]
|link:install/binary/installation-binary.md[Binary]

|link:pre-install/docker[Docker]
|link:pre-install/docker/installation-docker.md[Docker]

|link:pre-install/source[Source]
|link:pre-install/source/installation-source.md[Source]
|===

=== How to set up a Lisk node on the network

Each subcategory offers a specific guide for each distribution of Lisk
Core. The 3 supported distributions for Lisk Core are presented below:

==== Binary

The *default* way to setup Lisk Core. The binary installation is an easy
and automated way to set up Lisk Core, this includes nearly completely
automated update scripts and a selection of tools to help maintain a
Lisk Node in a seamless way.

==== Docker

Docker adds support for additional platforms upon which to run a Lisk
node, e.g. running a Lisk node inside of a Docker on Windows and
connecting it via a custom Node on Lisk Hub to Lisk Core, without the
need to rent an additional server.

==== Source

This is made for anyone wishing to develop on the Lisk Core codebase. It
also comes with an extensive test-suite, detailed in `+README.md+`.
Installation from Source enables a developer to work on the newest
codebase for Lisk Core, which might not have been tagged for a release.
