= Source code
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes all necessary steps and requirements to install Lisk Service from source.
:toc:
:page-previous: /lisk-service/setup/index.html
:page-previous-title: Setup

:url_freegeoip: https://github.com/fiorix/freegeoip
:url_git: https://github.com/git/git
:url_github_service: https://github.com/LiskHQ/lisk-service
:url_nodejs: https://nodejs.org/
:url_nvm: https://github.com/creationix/nvm
:url_nvm_instructions: https://github.com/creationix/nvm#install--update-script
:url_pm2: https://github.com/Unitech/pm2
:url_redis: http://redis.io

A guide about the installation of Lisk Service from Source code.

== Prerequisites

The following dependencies are required to install and run Lisk Service from Source.

=== Node.js

We recommend to use the latest LTS version, but all versions from 10.19.0 or higher are supported.
{url_nodejs}[Node.js^] serves as the underlying engine for code execution.
There are several different methods and version managers used to install Node.js on your system.
It is recommended to use one of the following two options:

[tabs]
====
Option A - Node version manager::
+
--
It is recommended to use a Node version manager such as {url_nvm}[NVM^].
NVM is a bash script that enables the management of multiple active Node.js versions.

. Install nvm following the {url_nvm_instructions}[official instructions^].
. Install the latest LTS version of Node.js using NVM:

[source,bash]
----
nvm install 12.15.0
----
--
Option B - Node.js package::
+
--
If NVM or other package managers are not required, it is possible to install the Node package globally  as shown in the following commands below:

*Ubuntu*

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
----

*MacOS*

For MacOS, please execute the following command below:

[source,bash]
----
brew install node@12.15.0
----
--
====

=== Redis

{url_redis}[Redis] is used for caching parsed exchange data.

[source, bash]
----
sudo apt-get install -y redis-server
----

=== Freegeoip

{url_freegeoip}[Freegeoip] is used by the Network Monitor for IP address geo-location.

[source,bash]
----
wget https://github.com/fiorix/freegeoip/releases/download/v3.4.1/freegeoip-3.4.1-linux-amd64.tar.gz
tar -zxf freegeoip-3.4.1-linux-amd64.tar.gz
ln -s freegeoip-3.4.1-linux-amd64 freegeoip
nohup ./freegeoip/freegeoip > ./freegeoip/freegeoip.log 2>&1 &
----

=== PM2

{url_pm2}[PM2] manages the node process for Lisk Service and handles log rotation (Highly Recommended).

[source,bash]
----
sudo npm install -g pm2
----

=== Git

{url_git}[Git] is used for cloning and updating Lisk Service.

[source,bash]
----
sudo apt-get install -y git
----

=== Tool chain components

Used for compiling dependencies

[source,bash]
----
sudo apt-get install -y python build-essential automake autoconf libtool
----

== Installation

Clone the {url_github_service}[lisk-service^] GitHub repository and then navigate into the project folder.

Then install the dependencies with `npm i`.

[source,bash]
----
git clone https://github.com/LiskHQ/lisk-service.git
cd lisk-service
npm i
----
