= Source code
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes all necessary steps and requirements to install Lisk Service from source.
:toc:
:page-previous: /lisk-service/setup/index.html
:page-previous-title: Setup
:v_core: master

:url_geojs: https://www.geojs.io/
:url_git: https://github.com/git/git
:url_github_service: https://github.com/LiskHQ/lisk-service
:url_nodejs: https://nodejs.org/
:url_nvm: https://github.com/creationix/nvm
:url_nvm_instructions: https://github.com/creationix/nvm#install--update-script
:url_pm2: https://github.com/Unitech/pm2
:url_redis: http://redis.io

:url_config: configuration.adoc
:url_core_docker_setup: {v_core}@lisk-core::setup/docker.adoc

A guide about the installation of Lisk Service from Source code.

== Prerequisites

The following dependencies are required to install and run Lisk Service from Source.

=== Node.js

We recommend to use the latest LTS version, but all versions from 10.19.0 or higher are supported.
{url_nodejs}[Node.js^] serves as the underlying engine for code execution.
There are several different methods and version managers used to install Node.js on your system.
It is recommended to use one of the following two options:

[tabs]
====
Option A - Node version manager::
+
--
It is recommended to use a Node version manager such as {url_nvm}[NVM^].
NVM is a bash script that enables the management of multiple active Node.js versions.

. Install nvm following the {url_nvm_instructions}[official instructions^].
. Install the latest LTS version of Node.js using NVM:

[source,bash]
----
nvm install 12.15.0
----
--
Option B - Node.js package::
+
--
If NVM or other package managers are not required, it is possible to install the Node package globally  as shown in the following commands below:

*Ubuntu*

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
----

*MacOS*

For MacOS, please execute the following command below:

[source,bash]
----
brew install node@12.15.0
----
--
====

=== PostgreSQL

To install Postgres follow the instructions.

[NOTE]
====
During this step it is possible to change your port if you wish to have more Postgres instances in the future.
Remember to adjust the environment variable `POSTGRES_PORT` accordingly in the xref:configuration.adoc[configuration].
====

[tabs]
====
Ubuntu::
+
--

Firstly, install PostgreSQL on your machine as shown in the following commands listed below:

[source,bash]
----
sudo apt-get purge -y postgres* <1>
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt update
sudo apt install postgresql-10
----

<1> Remove all previously installed postgres versions.

After the installation is completed it should be possible to see the Postgres database cluster by running the following commands listed below:

[source,bash]
----
pg_lsclusters
----

Drop the existing database cluster, and replace it with a cluster with the locale `en_US.UTF-8`:

[source,bash]
----
sudo pg_dropcluster --stop 10 main
sudo pg_createcluster --locale en_US.UTF-8 --start 10 main
----

Create a new database user called `lisk` and grant it rights to create databases.
Then create the database `lisk` with the `lisk` user as owner.
Finally, define the password for the `lisk` user:

[source,bash]
----
sudo -u postgres -i createuser --createdb lisk
sudo -u postgres -i createdb lisk --owner lisk
sudo -u postgres psql -d lisk -c "alter user lisk with password 'password';"
----

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:{url_config}[Lisk Service configuration] afterwards.
--
MacOS::
+
--
[[postgres_macos]]
To install the PostgreSQL version 10 execute the following command below:

[source,bash]
----
brew install postgresql@10
----

The next step is to execute the following commands in order to have the PostgreSQL commands (e.g. `psql`), in your PATH:

[source,bash]
----
echo 'export PATH="/usr/local/opt/postgresql@10/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile
----

Start the PostgreSQL, and create the `lisk` user and the database by executing the following commands below:

[source,bash]
----
pg_ctl -D /usr/local/var/postgresql@10 start
createuser lisk
createdb --owner=lisk lisk
psql --dbname=lisk --command="ALTER USER lisk WITH PASSWORD 'password';"
----

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:{url_config}[Lisk Service configuration] afterwards.
--
====

=== Redis

{url_redis}[Redis] is used for caching parsed exchange data.

[NOTE]
====
During this step it is possible to change your port if you wish to have more Redis instances in the future.
Remember to adjust the environment variable `REDIS_PORT` accordingly in the xref:configuration.adoc[configuration].
====

[source, bash]
----
sudo apt-get install -y redis-server
----

Start Redis:

[source,bash]
----
sudo service redis-server start
----

Stop Redis:

[source,bash]
----
sudo service redis-server stop
----

=== GeoJS

{url_geojs}[GeoJS] is used by the Network Monitor for IP address geo-location.

[source,bash]
----
#todo
----

=== PM2

{url_pm2}[PM2] manages the node process for Lisk Service and handles log rotation (Highly Recommended).

[source,bash]
----
sudo npm install -g pm2
----

=== Git

{url_git}[Git] is used for cloning and updating Lisk Service.

[source,bash]
----
sudo apt-get install -y git
----

=== Tool chain components

Used for compiling dependencies

[source,bash]
----
sudo apt-get install -y python build-essential automake autoconf libtool
----

== Installation

Clone the {url_github_service}[lisk-service^] GitHub repository and then navigate into the project folder.

Then install the dependencies with `npm i`.

[source,bash]
----
git clone https://github.com/LiskHQ/lisk-service.git
cd lisk-service
npm i
----

//TODO: that are probably not allr equired steps
