= Source code setup
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes all requirements and dependencies to install Lisk Core from Source.
:toc:
:page-next: /lisk-core/3.0.0/management/source-commands.html
:page-previous: /lisk-core/3.0.0/setup/index.html
:page-next-title: Source code commands
:page-previous-title: Interact with the network
:v_sdk: master

:url_git: https://github.com/git/git
:url_homebrew: https://brew.sh/
:url_nodejs: https://nodejs.org/
:url_nvm: https://github.com/creationix/nvm
:url_nvm_instructions: https://github.com/creationix/nvm#install--update-script
:url_pm2: https://github.com/Unitech/pm2
:url_xcode: https://developer.apple.com/xcode/
:url_core_releases: https://github.com/LiskHQ/lisk-core/releases

:url_binary_pre_install: setup/application.adoc
:url_config_api: {v_sdk}@lisk-sdk::guides/node-management/api-access.adoc
:url_core_config: management/configuration.adoc
:url_docker_setup: setup/docker.adoc
:url_environment_variables: setup/docker.adoc#environment-variables
:url_log_rotation: management/configuration.adoc
:url_upgrade_source: update/source.adoc

[[source-pre-install]]
== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, then please proceed to the <<_installation, Installation>> chapter.

=== Requirements

Supported Platforms::
* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64
* macOS

include::partial$core-ports.adoc[]

=== Git

{url_git}[Git^] is used for cloning and updating Lisk as displayed below:

[tabs]
====
Ubuntu::
+
--
[source,bash]
----
sudo apt install -y git
----
--
MacOS::
+
--
[source,bash]
----
brew install git
----
--
====

=== Node.js

{url_nodejs}[Node.js^] serves as the underlying engine for code execution.
There are several different methods and version managers used to install Node.js on your system. Please ensure the latest LTS version is used.
It is recommended to deploy one of the following two versions shown below:

[tabs]
====
Option A - Node version manager::
+
--
It is recommended to use a Node version manager such as {url_nvm}[NVM^].
NVM is a bash script that enables the management of multiple active Node.js versions.

. Install NVM and follow the {url_nvm_instructions}[official instructions^] here.
. Install the latest LTS version of Node.js using NVM with the following command shown below:

[source,bash]
----
nvm install 12.16.2
----
--
Option B - Node.js package::
+
--
If NVM or other package managers are not required, it is possible to install the Node package globally  as shown in the following commands below:

*Ubuntu*

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
----

*MacOS*

For MacOS, please execute the following command below:

[source,bash]
----
brew install node@12.16.2
----
--
====

=== PM2 (optional)

Install {url_pm2}[PM2^] for managing the start and stop of the application process in the background as shown below:

[source,bash]
----
npm install pm2 -g
----

== Installation

This section details how to install Lisk Core from Source code.
When completed, a functioning node on the Lisk network will exist.
If you wish to update your current Lisk Core installation, please see xref:{url_upgrade_source}[Update Source code].

=== Login as the Lisk user

This user was created in the <<source-pre-install,Pre-Installation steps>>.
If you are already logged in to this user, please skip the following step:

[source,bash]
----
sudo -u lisk -i
----

=== Installing Lisk from Source code

[source,bash]
----
git clone https://github.com/LiskHQ/lisk-core.git <1>
cd lisk-core                  <2>
git checkout v3.0.0-beta.1 -b v3.0.0-beta.1 <3>
npm ci                        <4>
npm run build                 <5>
----

<1> Clone the repository.
<2> Navigate into the lisk-core root folder.
<3> Check out the latest release tag.
<4> Install dependencies.
<5> Compile packages.

NOTE: Please check for the latest release in {url_core_releases}[core releases^].

To test that Lisk Core is built and configured correctly, execute the following command below to connect to the network:

[source,bash]
----
node dist/index.js <1>
LISK_NETWORK=[network] node dist/index.js <2>
node dist/index.js --network [network] <3>
----

<1> Default: connect to Devnet.
<2> Use environment variables to overwrite config values, (recommended).
<3> Use flags to overwrite config values.

Where `[network]` might be either `devnet` (default), `betanet`, `testnet` or `mainnet`.

It is recommended to overwrite the config values with environment variables if required.
Useable variables will always start with the `LISK_` prefix.
Alternatively, the user may define a custom `config.json`, as described in xref:{url_core_config}[Configuration of Lisk Core] .
Please see the xref:{url_environment_variables}[list of available environment variables].

If the process is running correctly, no errors are thrown in the logs.
By default, errors will be logged in `logs/[network]/lisk.log`.
Once the process is verified as running correctly, press `CTRL+C` and start the process with `pm2`.
This will fork the process into the background and automatically recover the process if it fails.

[source,bash]
----
pm2 start --name lisk dist/index.js -- --network [network]
----

Where the `[network]` might be either `devnet` (default), `betanet`, `testnet`, or `mainnet`.

If you are not running Lisk locally, it is required to follow the xref:{url_config_api}[API access guide] document in order to enable access.

In case you wish to configure your node further, e.g. if enabling forging is required, then please see the xref:{url_core_config}[configuration] documentation.

== Post-installation (optional)

* Recommended: Set up a xref:{url_log_rotation}[logrotation]
