= Source code setup
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Source code setup describes all necessary steps and requirements to install the Lisk SDK from source.
:toc:
:page-next: /lisk-core/3.0.0/management/source-commands.html
:page-previous: /lisk-core/3.0.0/interact-with-network.html
:page-next-title: Source code commands
:page-previous-title: Interact with the network

:url_git: https://github.com/git/git
:url_homebrew: https://brew.sh/
:url_nodejs: https://nodejs.org/
:url_nvm: https://github.com/creationix/nvm
:url_nvm_instructions: https://github.com/creationix/nvm#install--update-script
:url_pm2: https://github.com/Unitech/pm2
:url_xcode: https://developer.apple.com/xcode/
:url_core_releases: https://github.com/LiskHQ/lisk-core/releases

:url_admin: management/getting-started.adoc
:url_binary_pre_install: setup/application.adoc
:url_config_api: management/api-access.adoc
:url_core_config: management/configuration.adoc
:url_docker_setup: setup/docker.adoc
:url_environment_variables: setup/docker.adoc#environment-variables
:url_log_rotation: management/configuration.adoc
:url_upgrade_source: update/source.adoc

[[source-pre-install]]
== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, then please proceed to the <<_installation, Installation>> chapter.

include::partial$core-ports.adoc[]

include::partial$create-a-new-user.adoc[]

=== Toolchain components

These are used for compiling dependencies as displayed below:

[tabs]
====
Ubuntu::
+
--
[source,bash]
----
sudo apt update
sudo apt install -y libtool automake autoconf curl build-essential python-minimal
----
--
MacOS::
+
--
Ensure that both {url_xcode}[XCode^] and {url_homebrew}[Homebrew^] are installed.

[source,bash]
----
brew install autoconf automake libtool
----
--
====

=== Git

{url_git}[Git^] is used for cloning and updating Lisk as displayed below:

[tabs]
====
Ubuntu::
+
--
[source,bash]
----
sudo apt install -y git
----
--
MacOS::
+
--
[source,bash]
----
brew install git
----
--
====

=== Node.js

{url_nodejs}[Node.js^] serves as the underlying engine for code execution.
There are several different methods and version managers used to install Node.js on your system. Please ensure the latest LTS version is used.
It is recommended to deploy one of the following two versions shown below:

[tabs]
====
Option A - Node version manager::
+
--
It is recommended to use a Node version manager such as {url_nvm}[NVM^].
NVM is a bash script that enables the management of multiple active Node.js versions.

. Install NVM and follow the {url_nvm_instructions}[official instructions^] here.
. Install the latest LTS version of Node.js using NVM with the following command shown below:

[source,bash]
----
nvm install 12.15.0
----
--
Option B - Node.js package::
+
--
If NVM or other package managers are not required, it is possible to install the Node package globally  as shown in the following commands below:

*Ubuntu*

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
----

*MacOS*

For MacOS, please execute the following command below:

[source,bash]
----
brew install node@12.15.0
----
--
====

=== PostgreSQL

To install PostgresSQL follow the instructions described below, dependent upon the operating system currently being used.
In the case whereby problematic issues occur whilst setting up PostgreSQL on your machine, then it is recommended to try and install it inside of a docker container.

TIP: It is recommended to use PostgresSQL with Docker for a straight forward and fast setup of PostgresSQL.

[tabs]
====
PostgresSQL with Docker::
+
--
Running PostgresSQL inside a Docker container will setup the correct version of PostgresSQL and containerize it away from any existing versions that may exist locally on your machine.
Choose this setup if you are unfamiliar with PostgresSQL, or if other issues occur with a previously installed version of PostgresSQL.
To successfully perform the command shown below, install Docker as described in the Setup page of the xref:{url_docker_setup][Lisk Core Docker image].

WARNING: If other versions of PostgreSQL are currently installed on your machine, please ensure they are stopped before starting the docker container.

[source,bash]
----
docker run --name lisk_core_db -p 5432:5432 -e POSTGRES_USER=lisk -e POSTGRES_PASSWORD=password -e POSTGRES_DB=lisk_<NETWORK> -d postgres:10
----

This will install PostgreSQL version 10 (`postgres:10`) in a container with name `lisk_core_db` and binds the port `5432` of the container with the same port of the machine.
As environment variables `POSTGRES_USER=lisk` is exposed in order to create the Lisk user, and `POSTGRES_PASSWORD=password` is used to set the password for the `lisk` user.
Finally the environment variable `POSTGRES_DB` creates the database `lisk_<NETWORK>` with the `lisk` user as the owner.

The above commands should be enough to set up the database ready to use with Lisk Core.
To manage the Docker container, use the following commands displayed below:

[source,bash]
----
docker stop lisk_core_db <1>
docker start lisk_core_db <2>
docker restart lisk_core_db <3>
docker rm lisk_core_db <4>
----

<1> Stop the container.
<2> Start the container.
<3> Restart the container.
<4> Remove the container.

In order to access PostgresSQL inside the container via CLI, execute the following command displayed below:

[source,bash]
----
docker exec --tty --interactive lisk_core_db psql -h localhost -U lisk -d postgres
----
--
PostgresSQL system wide::
+
--
NOTE: Please see the instructions for MacOS below.

*Ubuntu*

Firstly, install postgreSQL on your machine as shown in the following commands listed below:

[source,bash]
----
sudo apt-get purge -y postgres* <1>
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
sudo apt install wget ca-certificates
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt update
sudo apt install postgresql-10
----

<1> Remove all previously installed postgresSQL versions.

After the installation is completed it should be possible to see the PostgresSQL database cluster by running the following commands listed below:

[source,bash]
----
pg_lsclusters
----

Drop the existing database cluster, and replace it with a cluster with the locale `en_US.UTF-8` as shown below:

[source,bash]
----
sudo pg_dropcluster --stop 10 main
sudo pg_createcluster --locale en_US.UTF-8 --start 10 main
----

Create a new database user called `lisk` and grant it rights to create databases.
Then create the database with the Lisk user as the owner.
In the last step, define the password for the Lisk user:

[source,bash]
----
sudo -u postgres -i createuser --createdb lisk
sudo -u postgres -i createdb lisk_<NETWORK> --owner lisk
sudo -u postgres psql -d lisk_<NETWORK> -c "alter user lisk with password 'password';"
----

`<NETWORK>` may be `main` for Mainnet, `test` for Testnet, or `dev` for Devnet.

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:{url_core_config}[Lisk Core configuration] afterwards.

*MacOS*

Install PostgresSQL version 10 as shown below:

[source,bash]
----
brew install postgresql@10
----

Execute the following code snippet to have PostgreSQL commands, (e.g. `psql`) in your PATH:

[source,bash]
----
echo 'export PATH="/usr/local/opt/postgresql@10/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile
----

Start PostgreSQL, create the `lisk` user and the database as shown using the following commands listed below:

[source,bash]
----
pg_ctl -D /usr/local/var/postgresql@10 start
createuser lisk
createdb --owner=lisk lisk_<NETWORK>
psql --dbname=lisk_<NETWORK> --command="ALTER USER lisk WITH PASSWORD 'password';"
----

`<NETWORK>` may be `main` for Mainnet, `test` for Testnet, or `dev` for Devnet.

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:{url_core_config}[Lisk Core configuration] afterwards.
--
====

=== PM2 (optional)

Install {url_pm2}[PM2^] for managing the start and stop of the application process in the background as shown below:

[source,bash]
----
npm install pm2 -g
----

=== Redis (optional)

[tabs]
====
Ubuntu::
+
--
[source,bash]
----
sudo apt install redis-server
----

To start Redis execute the following command below:

[source,bash]
----
sudo service redis-server start
----

To stop Redis execute the following command below:

[source,bash]
----
sudo service redis-server stop
----
--
MacOS::
+
--
[source,bash]
----
brew install redis
----

To start Redis execute the following command below:

[source,bash]
----
brew services start redis
----

To stop Redis execute the following command below:

[source,bash]
----
brew services stop redis
----
--
====

[IMPORTANT]
====
Please note that Lisk does not run on the Redis default port of `6379`.
Instead it is configured to run on port: `6380`.
Therefore in order to run Lisk, there are two options available which are listed below:
====

[tabs]
====
A - Change the Lisk configuration::
+
--
In the next installation phase, please remember to update the Redis port configuration in `config.json`.
--

B - Change the Redis launch configuration::
+
--
Update the launch configuration file on your system.
Note that there are numerous methods to perform this.

The following is one example:

. Stop the Redis-server
. Edit the file `+redis.conf+` and change: `port 6379` to `port 6380`
* Ubuntu/Debian: `/etc/redis/redis.conf`
* MacOS: `/usr/local/etc/redis.conf`
. Start the Redis-server

Now confirm that Redis is running on `port 6380`:

[source,bash]
----
redis-cli -p 6380
ping
----

The following result should be received: `PONG`.
--
====

If all of the above steps have been successfully completed, your system is now ready for the installation of Lisk Core.

== Installation

This section details how to install Lisk Core from Source code.
When completed, a functioning node on the Lisk network will exist.
If you wish to update your current Lisk Core installation, please see xref:{url_upgrade_source}[Update Source code].

=== Login as the Lisk user

This user was created in the <<source-pre-install,Pre-Installation steps>>.
If you are already logged in to this user, please skip the following step:

[source,bash]
----
sudo -u lisk -i
----

=== Installing Lisk from Source code

[source,bash]
----
git clone https://github.com/LiskHQ/lisk-core.git <1>
cd lisk-core                  <2>
git checkout v3.0.0-beta.0 -b v3.0.0-beta.0 <3>
npm ci                        <4>
npm run build                 <5>
----

<1> Clone the repository.
<2> Navigate into the lisk-core root folder.
<3> Check out the latest release tag.
<4> Install dependencies.
<5> Compile packages.

NOTE: Please check for the latest release in {url_core_releases}[core releases^].

To test that Lisk Core is built and configured correctly, execute the following command below to connect to the network:

[source,bash]
----
node dist/index.js <1>
LISK_NETWORK=[network] node dist/index.js <2>
node dist/index.js --network [network] <3>
----

<1> Default: connect to Devnet.
<2> Use environment variables to overwrite config values, (recommended).
<3> Use flags to overwrite config values.

Where `[network]` might be either `devnet` (default), `betanet`, `testnet` or `mainnet`.

It is recommended to overwrite the config values with environment variables if required.
Useable variables will always start with the `LISK_` prefix.
Alternatively, the user may define a custom `config.json`, as described in xref:{url_core_config}[Configuration of Lisk Core] .
Please see the xref:{url_environment_variables}[list of available environment variables].

If the process is running correctly, no errors are thrown in the logs.
By default, errors will be logged in `logs/[network]/lisk.log`.
Once the process is verified as running correctly, press `CTRL+C` and start the process with `pm2`.
This will fork the process into the background and automatically recover the process if it fails.

[source,bash]
----
pm2 start --name lisk dist/index.js -- --network [network]
----

Where the `[network]` might be either `devnet` (default), `betanet`, `testnet`, or `mainnet`.

If you are not running Lisk locally, it is required to follow the xref:{url_config_api}[API access guide] document in order to enable access.

In case you wish to configure your node further, e.g. if enabling forging is required, then please see the xref:{url_core_config}[configuration] documentation.

== Post-installation (optional)

* Recommended: Set up a xref:{url_log_rotation}[logrotation]
