= Source code setup
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes all requirements and dependencies to install Lisk Core from Source.
:toc:
:v_sdk: master

:url_git: https://github.com/git/git
:url_homebrew: https://brew.sh/
:url_nodejs: https://nodejs.org/
:url_nvm: https://github.com/creationix/nvm
:url_nvm_instructions: https://github.com/creationix/nvm#install--update-script
:url_pm2: https://github.com/Unitech/pm2
:url_xcode: https://developer.apple.com/xcode/
:url_core_releases: https://github.com/LiskHQ/lisk-core/releases

:url_binary_pre_install: setup/application.adoc
:url_config_api: {v_sdk}@lisk-sdk::guides/node-management/api-access.adoc
:url_core_config: management/configuration.adoc
:url_docker_setup: setup/docker.adoc
:url_environment_variables: setup/docker.adoc#environment-variables
:url_log_rotation: management/configuration.adoc
:url_upgrade_source: update/source.adoc

The installation from source code is designed for anyone wishing to develop on the Lisk Core codebase.
It also comes with an extensive test-suite which is described in the `README.md`.
An installation performed from the source code enables a developer to work on the latest codebase of Lisk Core, which may not have been tagged for a release yet.

[[source-pre-install]]
== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, then please proceed to the <<_installation, Installation>> chapter.

=== Requirements

Supported Platforms::
* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 20.04 (LTS) x86_64
* MacOS x86_64

=== Git

{url_git}[Git^] is used for cloning and updating Lisk as displayed below:

[tabs]
====
Ubuntu::
+
--
[source,bash]
----
sudo apt install git
----
--
MacOS::
+
--
[source,bash]
----
brew install git
----
--
====

=== Node.js

{url_nodejs}[Node.js^] serves as the underlying engine for code execution.
There are several different methods and version managers used to install Node.js on your system. Please ensure the latest LTS version is used.
It is recommended to deploy one of the following two versions shown below:

[tabs]
====
Option A - Node version manager::
+
--
It is recommended to use a Node version manager such as {url_nvm}[NVM^].
NVM is a bash script that enables the management of multiple active Node.js versions.

. Install NVM and follow the {url_nvm_instructions}[official instructions^] here.
. Install the latest LTS version of Node.js using NVM with the following command shown below:

[source,bash]
----
nvm install 12.20.1
----
--
Option B - Node.js package::
+
--
If NVM or other package managers are not required, it is possible to install the Node package globally  as shown in the following commands below:

*Ubuntu*

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
----

*MacOS*

For MacOS, please execute the following command below:

[source,bash]
----
brew install node@12.20.1
----
--
====

=== PM2 (optional)

Install {url_pm2}[PM2^] for managing the start and stop of the application process in the background as shown below:

[source,bash]
----
npm install pm2 -g
----

== Installation

This section details how to install Lisk Core from Source code.
When completed, a functioning node on the Lisk network will exist.

=== Installing Lisk from Source code

[source,bash]
----
git clone https://github.com/LiskHQ/lisk-core.git <1>
cd lisk-core                  <2>
git checkout v3.0.0-rc.2 -b v3.0.0-rc.2 <3>
npm install --global <4>
----

<1> Clone the repository.
<2> Navigate into the lisk-core root folder.
<3> Check out the latest release tag.
<4> Install dependencies

NOTE: Please check for the latest release in {url_core_releases}[core releases^].

To test that Lisk Core is built and configured correctly, execute the following command below to connect to the network:

[source,bash]
----
lisk-core start --network devnet
# From other terminal
lisk-core node:info
----

If the process is running correctly, no errors are thrown in the logs.

== Post-installation (optional)

* Recommended: Set up a xref:{url_log_rotation}[logrotation]
