= Installation from source code
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes all necessary steps and requirements to install Lisk Service from source.
:toc:
:page-previous: /lisk-service/setup/index.html
:page-previous-title: Setup
:page-next: /lisk-service/configuration/source.html
:page-next-title: Configuration with PM2

:url_geojs: https://www.geojs.io/
:url_git: https://github.com/git/git
:url_github_service: https://github.com/LiskHQ/lisk-service
:url_nodejs: https://nodejs.org/
:url_nvm: https://github.com/creationix/nvm
:url_nvm_instructions: https://github.com/creationix/nvm#install--update-script
:url_pm2: https://github.com/Unitech/pm2
:url_redis: http://redis.io

:url_index_usage: index.adoc#usage
:url_setup: setup/index.adoc
:url_config: configuration/source.adoc
:url_management_pm2: management/source.adoc

This guide describes, how to setup Lisk Service with PM2.
Alternative ways how to install Lisk Service are described on the xref:{url_setup}[Setup] page.

== Prerequisites

The following dependencies are required to install and run Lisk Service from Source.

=== Update packages

[tabs]
====
Ubuntu::
+
--
In Ubuntu and its derivatives APT is the base package management application. Make sure your local APT registry is up-to-date.

[source,bash]
----
apt update
----
--
macOS::
+
--
Install https://brew.sh/[Brew] by following the https://brew.sh/[latest instructions].

Next, make sure your package sources are up to date:

[source,bash]
----
brew update
brew doctor
----
--
====

=== Tool chain components

[tabs]
====
Ubuntu::
+
--
Install the `build-essential` package alongside with several development tools.

[source,bash]
----
sudo apt-get install -y build-essential git make
----
--
macOS::
+
--
xcode-select --install
--
====

=== Node.js

We recommend to use the latest LTS version
{url_nodejs}[Node.js^] serves as the underlying engine for code execution.
There are several different methods and version managers used to install Node.js on your system.
It is recommended to use one of the following two options:

[tabs]
====
Option A - Node version manager::
+
--
It is recommended to use a Node version manager such as {url_nvm}[NVM^].
NVM is a bash script that enables the management of multiple active Node.js versions.

. Install nvm following the {url_nvm_instructions}[official instructions^].
. Install the latest LTS version of Node.js using NVM:

.Check for the latest LTS version
[source,bash]
----
nvm ls-remote
[...]
v12.17.0   (LTS: Erbium)
v12.18.0   (LTS: Erbium)
v12.18.1   (LTS: Erbium)
v12.18.2   (LTS: Erbium)
v12.18.3   (Latest LTS: Erbium)
v13.0.0
v13.0.1
[...]
----

.Install the latest LTS version
[source,bash]
----
nvm install 12.18.3
----
--
Option B - Node.js package::
+
--
If NVM or other package managers are not required, it is possible to install the Node package globally  as shown in the following commands below:

*Ubuntu*

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
----

*macOS*

For macOS, please execute the following command below:

[source,bash]
----
brew install node@12
----
--
====

=== PostgreSQL

To install Postgres follow the instructions.

[NOTE]
====
During this step it is possible to change your port if you wish to have more Postgres instances in the future.
Remember to adjust the environment variable `POSTGRES_PORT` accordingly in the xref:{url_config}[configuration].
====

[tabs]
====
PostgresSQL with Docker::
+
--
**Docker Setup**

include::partial$docker-setup.adoc[]

**Installation**
CAUTION: If you have other versions of PostgreSQL installed on your machine, ensure they are stopped before starting the Docker container.

[source,bash]
----
cd docker/postgres
make up # to start PostgreSQL
----

The command above will install PostgreSQL version 10 (`postgres:10`) .

The above commands should be enough to set up the database ready to use with Lisk Core.

To stop the Docker container again, execute the following commands below:

[source,bash]
----
make down # to stop PostgreSQL
----
--
PostgresSQL system wide::
+
--
NOTE: See instructions for macOS below.

*Ubuntu*

Firstly, install PostgreSQL on your machine as shown in the following commands listed below:

[source,bash]
----
sudo apt-get purge -y postgres* <1>
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt update
sudo apt install postgresql-10
----

<1> Remove all previously installed postgres versions.

After the installation is completed it should be possible to see the Postgres database cluster by running the following commands listed below:

[source,bash]
----
pg_lsclusters
----

Drop the existing database cluster, and replace it with a cluster with the locale `en_US.UTF-8`:

[source,bash]
----
sudo pg_dropcluster --stop 10 main
sudo pg_createcluster --locale en_US.UTF-8 --start 10 main
----

Create a new database user called `lisk` and grant it rights to create databases.
Then create the database `lisk` with the `lisk` user as owner.
Finally, define the password for the `lisk` user:

[source,bash]
----
sudo -u postgres -i createuser --createdb lisk
sudo -u postgres -i createdb lisk --owner lisk
sudo -u postgres psql -d lisk -c "alter user lisk with password 'password';"
----

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:{url_config}[Lisk Service configuration] afterwards.

*macOS*

[[postgres_macos]]
To install the PostgreSQL version 10 execute the following command below:

[source,bash]
----
brew install postgresql@10
----

The next step is to execute the following commands in order to have the PostgreSQL commands (e.g. `psql`), in your PATH:

[source,bash]
----
echo 'export PATH="/usr/local/opt/postgresql@10/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile
----

Start the PostgreSQL, and create the `lisk` user and the database by executing the following commands below:

[source,bash]
----
pg_ctl -D /usr/local/var/postgresql@10 start
createuser lisk
createdb --owner=lisk lisk
psql --dbname=lisk --command="ALTER USER lisk WITH PASSWORD 'password';"
----

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:{url_config}[Lisk Service configuration] afterwards.
--
====

[tabs]
====
Ubuntu::
+
--

Firstly, install PostgreSQL on your machine as shown in the following commands listed below:

[source,bash]
----
sudo apt-get purge -y postgres* <1>
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt update
sudo apt install postgresql-10
----

<1> Remove all previously installed postgres versions.

After the installation is completed it should be possible to see the Postgres database cluster by running the following commands listed below:

[source,bash]
----
pg_lsclusters
----

Drop the existing database cluster, and replace it with a cluster with the locale `en_US.UTF-8`:

[source,bash]
----
sudo pg_dropcluster --stop 10 main
sudo pg_createcluster --locale en_US.UTF-8 --start 10 main
----

Create a new database user called `lisk` and grant it rights to create databases.
Then create the database `lisk` with the `lisk` user as owner.
Finally, define the password for the `lisk` user:

[source,bash]
----
sudo -u postgres -i createuser --createdb lisk
sudo -u postgres -i createdb lisk --owner lisk
sudo -u postgres psql -d lisk -c "alter user lisk with password 'password';"
----

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:{url_config}[Lisk Service configuration] afterwards.
--
macOS::
+
--
[[postgres_macos]]
To install the PostgreSQL version 10 execute the following command below:

[source,bash]
----
brew install postgresql@10
----

The next step is to execute the following commands in order to have the PostgreSQL commands (e.g. `psql`), in your PATH:

[source,bash]
----
echo 'export PATH="/usr/local/opt/postgresql@10/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile
----

Start the PostgreSQL, and create the `lisk` user and the database by executing the following commands below:

[source,bash]
----
pg_ctl -D /usr/local/var/postgresql@10 start
createuser lisk
createdb --owner=lisk lisk
psql --dbname=lisk --command="ALTER USER lisk WITH PASSWORD 'password';"
----

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:{url_config}[Lisk Service configuration] afterwards.
--
====

=== Redis

{url_redis}[Redis] is used for caching temporary data.

[tabs]
====
Ubuntu::
+
--
[source, bash]
----
sudo apt-get install redis-server
----
--
macOS::
+
--
[source, bash]
----
brew install redis
----
--
====


////
Lisk Service not compatible with this service right now.
we should encourage community to make Lisk Service compatible with this service, then they can use it as alternative GeoIP service.
=== GeoJS

{url_geojs}[GeoJS] is used by the Network Monitor for IP address geo-location.

[source,bash]
----
#todo
----
////


=== PM2

{url_pm2}[PM2] manages the node process for Lisk Service and handles log rotation (Highly Recommended).

[source,bash]
----
npm install -g pm2
----

== Installation

Clone the {url_github_service}[lisk-service^] GitHub repository and then navigate into the project folder and check out the latest release.

[source,bash]
----
# Clone Lisk Service repository
git clone https://github.com/LiskHQ/lisk-service.git

# Change directory to the new repository
cd lisk-service

# Switch to the recent stable as a base
git checkout vx.y.z

# ...or use the development branch
git checkout development
----

Install all npm dependencies from the root directory.

[source,bash]
----
make build-local
----

Now it is possible to start Lisk Service:

.Start Lisk Service from Source code
[source,bash]
----
npm start
----

This will use the default configuration and connect Lisk Service to the Lisk Mainnet.

To change the default configuration, check out the page xref:{url_config}[Configuration with PM2].

More commands about how to manage Lisk Service are described on the xref:{url_management_pm2}[PM2 commands] page.

TIP: Check the xref:{url_index_usage}[Usage] section for examples, how to use and interact with Lisk Service.
