= Source code setup
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Source code setup describes all necessary steps and requirements to install the Lisk SDK from source.
:toc:
:page-next: /lisk-core/management/source.html
:page-previous: /lisk-core/interact-with-network.html
:page-next-title: Source code commands
:page-previous-title: Interact with the network

:url_core_releases: https://github.com/LiskHQ/lisk-core/releases
:url_git: https://github.com/git/git
:url_homebrew: https://brew.sh/
:url_nodejs: https://nodejs.org/
:url_nvm: https://github.com/creationix/nvm
:url_nvm_instructions: https://github.com/creationix/nvm#install--update-script
:url_pm2: https://github.com/Unitech/pm2
:url_xcode: https://developer.apple.com/xcode/

:url_admin: management/getting-started.adoc
:url_binary_pre_install: setup/application.adoc
:url_config_api: management/api-access.adoc
:url_core_config: management/configuration.adoc
:url_docker_setup: setup/docker.adoc
:url_environment_variables: setup/docker.adoc#environment_variables
:url_upgrade_source: update/source.adoc
:url_log_rotation: management/configuration.adoc

[[source_pre_install]]
== Pre-install

To complete the installation it is necessary to fulfill some prerequisites.
If you have already performed these, please proceed to the <<install, Installation>> chapter.

include::partial$core-ports.adoc[]

include::partial$create-a-new-user.adoc[]

=== Toolchain components

Used for compiling dependencies.

[tabs]
====
Ubuntu::
+
--
[source,bash]
----
sudo apt update
sudo apt install -y libtool automake autoconf curl build-essential python-minimal
----
--
MacOS::
+
--
Ensure that both {url_xcode}[XCode] and {url_homebrew}[Homebrew] are installed.

[source,bash]
----
brew install autoconf automake libtool
----
--
====

=== Git

{url_git}[Git] is used for cloning and updating Lisk.

[tabs]
====
Ubuntu::
+
--
[source,bash]
----
sudo apt install -y git
----
--
MacOS::
+
--
[source,bash]
----
brew install git
----
--
====

=== PostgreSQL

To install PostgreSQL please follow the instructions described below:

TIP: It is recommended using PostgreSQL with Docker image for a quick and straight forward setup of PostgreSQL, and PostgreSQL system-wide for production environments.

[tabs]
====
Postgres system wide::
+
--
NOTE: See instructions for MacOS below.

*Ubuntu*

Firstly, install postgreSQL on your machine as shown below:

[source,bash]
----
sudo apt-get purge -y postgres* <1>
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
sudo apt install wget ca-certificates
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt update
sudo apt install postgresql-10
----

<1> Remove all already installed postgres versions.

After installation, it should be possible to see the Postgres database cluster, by executing the following command:

[source,bash]
----
pg_lsclusters
----

Drop the existing database cluster, and replace it with a cluster with the locale `en_US.UTF-8` as shown below:

[source,bash]
----
sudo pg_dropcluster --stop 10 main
sudo pg_createcluster --locale en_US.UTF-8 --start 10 main
----

Create a new database user called `lisk` and grant it rights to create databases.
Then create the database with the Lisk user as the owner.
In the last step, define the password for the Lisk user as shown below:

[source,bash]
----
sudo -u postgres -i createuser --createdb lisk
sudo -u postgres -i createdb lisk_<NETWORK> --owner lisk
sudo -u postgres psql -d lisk_<NETWORK> -c "alter user lisk with password 'password';"
----

`<NETWORK>` may be `main` for Mainnet, `test` for Testnet or `dev` for Devnet.

IMPORTANT: Change `password` to a secure password of your choice.
Do not forget to update this password in the xref:{url_core_config}[Lisk Core configuration] later on.

*MacOS*

Install Postgres version 10 by executing the following command below:

[source,bash]
----
brew install postgresql@10
----

Execute the following to have PostgreSQL commands, (e.g. `psql`) in your PATH as shown below:

[source,bash]
----
echo 'export PATH="/usr/local/opt/postgresql@10/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile
----

Start PostgreSQL, create the `lisk` user and the database by executing the following commands:

[source,bash]
----
pg_ctl -D /usr/local/var/postgresql@10 start
createuser lisk
createdb --owner=lisk lisk_<NETWORK>
psql --dbname=lisk_<NETWORK> --command="ALTER USER lisk WITH PASSWORD 'password';"
----

`<NETWORK>` may be `main` for Mainnet, `test` for Testnet or `dev` for Devnet.

IMPORTANT: Change `password` to a secure password of your choice.
Do not forget to update this password in the xref:{url_core_config}[Lisk Core configuration] later on.
--
Postgres with Docker::
+
--
Running Postgres inside a Docker container will setup the correct version of Postgres and containerize it away from any existing versions you may have locally on your machine.
Chose this setup if you are unfamiliar with Postgres, or if other issues occur with a previously installed version of Postgres.
To perform the command below successfully, install Docker as described in the xref:{url_docker_setup][Lisk Core Docker image set up].

WARNING: If you have other versions of PostgreSQL installed on your machine, ensure they are stopped before starting the Docker container.

[source,bash]
----
docker run --name lisk_core_db -p 5432:5432 -e POSTGRES_USER=lisk -e POSTGRES_PASSWORD=password -e POSTGRES_DB=lisk_<NETWORK> -d postgres:10
----

The command above will install PostgreSQL version 10 (`postgres:10`) in a container with name `lisk_core_db` and binds the port `5432` of the container with the same port of the machine.
As environment variables we expose `POSTGRES_USER=lisk` to create the lisk user and `POSTGRES_PASSWORD=password` to set the password for the lisk user.
Finally, the environment variable `POSTGRES_DB` creates the database `lisk_<NETWORK>` with the `lisk` user as the owner.

The above commands should be enough to set up the database ready to use with Lisk Core.
To manage the Docker container, execute the following commands below:

[source,bash]
----
docker stop lisk_core_db <1>
docker start lisk_core_db <2>
docker restart lisk_core_db <3>
docker rm lisk_core_db <4>
----

<1> Stop the container.
<2> Start the container.
<3> Restart the container.
<4> Remove the container.

In case it is required to access Postgres inside the container via the CLI, execute the following command below:

[source,bash]
----
docker exec --tty --interactive lisk_core_db psql -h localhost -U lisk -d postgres
----
--
====

=== Node.js

{url_nodejs}[Node.js] serves as the underlying engine for code execution.
There are several different methods and version managers to install Node.JS on your system.
It is recommended to utilise one of the following two options shown below:

[tabs]
====
Option A - Node version manager::
+
--
It is recommended to use a node version manager such as {url_nvm}[NVM].
NVM is a bash script that enables the management of multiple active Node.js versions.

. Install nvm following the {url_nvm_instructions}[official instructions].
. Install the correct version of Node.js using NVM by executing the following command below:

[source,bash]
----
nvm install 10.15.3
----
--
Option B - Node.js package::
+
--
If it is not required to use NVM or other package managers, it is possible to install
the node package globally on your system as shown below:

*Ubuntu*

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
----

*MacOS*

[source,bash]
----
brew install node@10.15.3
----
--
====

=== PM2 (optional)

Install {url_pm2}[PM2] for managing the start and stop of the application process in the background by executing the following command:

[source,bash]
----
npm install pm2 -g
----

=== Redis (optional)

[tabs]
====
Ubuntu::
+
--
[source,bash]
----
sudo apt install redis-server
----

Start Redis:

[source,bash]
----
sudo service redis-server start
----

Stop Redis:

[source,bash]
----
sudo service redis-server stop
----
--
MacOS::
+
--
[source,bash]
----
brew install redis
----

Start Redis:

[source,bash]
----
brew services start redis
----

Stop Redis:

[source,bash]
----
brew services stop redis
----
--
====

[IMPORTANT]
====
Lisk does not run on the redis default port of `6379`.
Instead it is configured to run on port: `6380`.
Therefore in order to run Lisk, there are two options available which are shown below:
====

[tabs]
====
A - Change the Lisk configuration::
+
--
In the next installation phase, remember to update the Redis port configuration in `config.json`.
--
B - Change the Redis launch configuration::
+
--
Update the launch configuration file on your system.
Note that there are numerous methods to perform this.

The following is one example:

. Stop redis-server
. Edit the file `+redis.conf+` and change: `port 6379` to `port 6380`
* Ubuntu/Debian: `/etc/redis/redis.conf`
* MacOS: `/usr/local/etc/redis.conf`
. Start redis-server

Now confirm that redis is running on `port 6380`:

[source,bash]
----
redis-cli -p 6380
ping
----

The following result should now be visible: `PONG`.
--
====

If all of the above steps have been successfully completed, then your system is ready for the installation of Lisk Core.

[[install]]
== Installation

This section covers how to install Lisk Core from Source.
When completed, you will have a functioning node on the Lisk Network.
If it is required to upgrade your current Lisk Core installation, please see xref:{url_upgrade_source}[Update from Source code].

=== Login as the Lisk user

This user was created in the <<source_pre_install,pre-installation steps>>.
If you are already logged in to this user, please skip this following step:

[source,bash]
----
sudo -u lisk -i
----

=== Installing Lisk from Source code

[source,bash]
----
git clone https://github.com/LiskHQ/lisk-core.git <1>
cd lisk-core                  <2>
git checkout v2.0.0 -b v2.0.0 <3>
npm ci                        <4>
npm run build                 <5>
----

<1> Clone the repository.
<2> Navigate into the lisk-core root folder.
<3> Check out the latest release tag.
<4> Install dependencies.
<5> Compile packages.

NOTE: Please check for latest release in {url_core_releases}[Core releases].

To test that Lisk Core is built and configured correctly, execute the following commands to connect to the network:

[source,bash]
----
node dist/index.js <1>
LISK_NETWORK=[network] node dist/index.js <2>
node dist/index.js --network [network] <3>
----

<1> Default: connect to Devnet.
<2> Use environment variables to overwrite config values, (recommended).
<3> Use flags to overwrite config values.

Where `[network]` might be either `devnet` (default), `alphanet`, `betanet`, `testnet` or `mainnet`.

It is recommended to overwrite the config values with environment variables if necessary.
Useable variables will always start with `LISK_` prefix.
Alternatively, the user may define a custom `config.json`, as described in xref:{url_core_config}[Configuration of Lisk Core] .
Click here, to see a xref:{url_environment_variables}[list of available environment variables]

If the process is running correctly, no errors are thrown in the logs.
By default, errors will be logged in `logs/[network]/lisk.log`.
Once the process is verified as running correctly, press `CTRL+C` and start the process with `pm2`.
This will fork the process into the background and automatically recover the process if it fails.

[source,bash]
----
pm2 start --name lisk dist/index.js -- --network [network]
----

Where `[network]` might be either `devnet` (default), `alphanet`, `betanet`, `testnet` or `mainnet`.

If you are not running Lisk locally, you will need to follow the xref:{url_config_api}[API access guide] document to enable access.


In case you wish to configure your node further, e.g. if enabling forging is required, then please see the xref:{url_core_config}[Configuration] documentation.

== Post-installation (optional)

* Recommended: Set up a xref:{url_log_rotation}[logrotation]
