= Update Application
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core aApplication update page describes how to upgrade Lisk Core to the latest version.
:page-aliases: upgrade/binary.adoc
:toc:
:experimental:
:v_sdk: master
:page-next: /lisk-core/monitoring.html
:page-previous: /lisk-core/management/application.html
:page-next-title: Monitoring
:page-previous-title: Application commands

:url_sdk_commander_liskcore: {v_sdk}@lisk-sdk::lisk-commander/user-guide/lisk-core.adoc
:url_sdk_commander_commands: {v_sdk}@lisk-sdk::lisk-commander/user-guide/commands.adoc
:url_enable_forging: management/forging.adoc

To update Lisk Core application please follow the instructions below.
Please choose the instructions specific to the network, (Mainnet or Testnet) your node is connected to.

== Update with Lisk Commander application

IMPORTANT: The `core:upgrade` command is only supported for Lisk Core versions > `2.0.0` and will only work, if Lisk Core has been installed with the Lisk Commander application before.

Firstly, open the the directory, where your Lisk Core installation is located.

Then execute the following command to upgrade Lisk Core:

[source,bash]
----
lisk core:upgrade <location>
----

Where `<location>` should be the root folder of your Lisk Core installation.

For all available options see the Lisk Commander application xref:{url_sdk_commander_liskcore}[command reference for Lisk Core] as well as the xref:{url_sdk_commander_commands}[General command reference] .

== Update with bash script

=== Mainnet

[source,bash]
----
cd ~
rm -f installLisk.sh
wget https://downloads.lisk.io/lisk/main/installLisk.sh
bash installLisk.sh upgrade -r main
----

=== Testnet

[source,bash]
----
cd ~
rm -f installLisk.sh
wget https://downloads.lisk.io/lisk/test/installLisk.sh
bash installLisk.sh upgrade -r test
----

After running the above script manually or through `lisk_bridge.sh`, you will be prompted to choose from a few options.
Please read these thoroughly and follow the steps described below:

[NOTE]
====
It is necessary to enable forging manually after the upgrade.
For further details, please follow this guide to xref:{url_enable_forging}[enable forging on your delegate node].
====

== Manual update Lisk Core

To switch to your Lisk folder and stop the Lisk processes, execute the following applicable command below:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cd ~
cd lisk-main
bash lisk.sh stop
----
--
Testnet::
+
--
[source,bash]
----
cd ~
cd lisk-test
bash lisk.sh stop
----
--
====

To backup your SSL folder, (if necessary) execute the following commands below:

[source,bash]
----
mkdir ~/backup
cp -f ./ssl/* ~/backup/
cp -f ./config.json ~/backup/
----

In order to remove your old Lisk folder and install the script, execute the following applicable command below:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cd ~
rm -rf ~/lisk-main
rm -rf installLisk.sh
----
--
Testnet::
+
--
[source,bash]
----
cd ~
rm -rf ~/lisk-test
rm -rf installLisk.sh
----
--
====

To get the latest install script execute the following applicable command below:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
wget https://downloads.lisk.io/lisk/main/installLisk.sh
----
--
Testnet::
+
--
[source,bash]
----
wget https://downloads.lisk.io/lisk/test/installLisk.sh
----
--
====

To install the latest version of Lisk execute the following applicable command below:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
bash installLisk.sh install -r main
----
--
Testnet::
+
--
[source,bash]
----
bash installLisk.sh install -r test
----
--
====

TIP: You will be prompted for your installation directory, pressing kbd:[Enter] will choose the default.
