= Application
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core application update page describes how to upgrade Lisk Core to the latest version.
:toc:
:experimental:
:v_sdk: master
:page-next: /lisk-core/3.0.0/monitoring.html
:page-previous: /lisk-core/3.0.0/management/application.html
:page-next-title: Monitoring
:page-previous-title: Application commands

:url_sdk_commander_liskcore: {v_sdk}@lisk-sdk::reference/lisk-commander/user-guide/lisk-core.adoc
:url_sdk_commander_commands: {v_sdk}@lisk-sdk::reference/lisk-commander/user-guide/commands.adoc
:url_enable_forging: management/forging.adoc



== Update with bash script

To perform the update using the bash script, please follow the instructions below.

=== Betanet

[source,bash]
----
cd ~
rm -f installLisk.sh
wget https://downloads.lisk.io/lisk/beta/installLisk.sh
bash installLisk.sh upgrade -r beta
----

After running the above script manually or through `lisk_bridge.sh`, you will be prompted to select a few options.
Please read these thoroughly and follow the applicable steps.

[NOTE]
====
It is necessary to enable forging manually after the upgrade.
Please follow this guide to xref:{url_enable_forging}[enable forging on your delegate node] for further details.
====

== Manual update Lisk Core

Switch to your Lisk folder and stop Lisk processes as shown below:

[tabs]
====
Betanet::
+
--
[source,bash]
----
cd ~
cd lisk-beta
bash lisk.sh stop
----
--
====

Backup your SSL folder (if necessary) as shown below:

[source,bash]
----
mkdir ~/backup
cp -f ./ssl/* ~/backup/
cp -f ./config.json ~/backup/
----

Remove your old Lisk folder and install the script as shown below:

[tabs]
====
Betanet::
+
--
[source,bash]
----
cd ~
rm -rf ~/lisk-beta
rm -rf installLisk.sh
----
--
====

Get the latest install script as shown below:

[tabs]
====
Betanet::
+
--
[source,bash]
----
wget https://downloads.lisk.io/lisk/beta/installLisk.sh
----
--
====

Install the latest version of Lisk as shown below:

[tabs]
====
Betanet::
+
--
[source,bash]
----
bash installLisk.sh install -r beta
----
--
====

TIP: You will be prompted for your installation directory, pressing kbd:[Enter] will choose the default.
