= Lisk Core Binary Update
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Binary Update page describes how to upgrade Lisk Core to the latest version.
:toc:
:experimental:
:v_sdk: master

:url_sdk_commander_liskcore: {v_sdk}@lisk-sdk::lisk-commander/user-guide/lisk-core.adoc
:url_sdk_commander_commands: {v_sdk}@lisk-sdk::lisk-commander/user-guide/commands.adoc
:url_enable_forging: management/forging.adoc

To update Lisk Core from Binary, please follow the correct instructions below which pertain to the specific network, (Mainnet or Testnet) that your node is currently using.

== Update with Lisk Commander

IMPORTANT: The `core:upgrade` command is only supported for Lisk Core versions `2.0.0` and higher, therefore all previous versions below 2.0.0 are not supported.
In addition, this will only work if Lisk Core has previously been installed with Lisk Commander.

Firstly, open the directory, where your Lisk Core installation is located.

Execute the following command below to upgrade Lisk Core:

[source,bash]
----
lisk core:upgrade <location>
----

Where `<location>` should be the root folder of your Lisk Core installation.

For all available options, please see the Lisk Commander xref:{url_sdk_commander_liskcore}[Command reference for Lisk Core] as well as the xref:{url_sdk_commander_commands}[general Command reference].

== Update with bash script

=== Mainnet

[source,bash]
----
cd ~
rm -f installLisk.sh
wget https://downloads.lisk.io/lisk/main/installLisk.sh
bash installLisk.sh upgrade -r main
----

=== Testnet

[source,bash]
----
cd ~
rm -f installLisk.sh
wget https://downloads.lisk.io/lisk/test/installLisk.sh
bash installLisk.sh upgrade -r test
----

After running the above script manually or through `lisk_bridge.sh` a prompt will appear listing certain options.
Please read the following section below thoroughly and follow the steps.

[NOTE]
====
It is required to enable forging manually after the upgrade.
Please see the following guide on how to xref:{url_enable_forging}[enable forging on your delegate node].
====

== Manual Update Lisk Core

Switch to your Lisk folder and stop the Lisk processes:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cd ~
cd lisk-main
bash lisk.sh stop
----
--
Testnet::
+
--
[source,bash]
----
cd ~
cd lisk-test
bash lisk.sh stop
----
--
====

Backup your SSL folder, (if necessary) as shown below in the following commands:

[source,bash]
----
mkdir ~/backup
cp -f ./ssl/* ~/backup/
cp -f ./config.json ~/backup/
----

Remove your old Lisk folder and install the following script:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cd ~
rm -rf ~/lisk-main
rm -rf installLisk.sh
----
--
Testnet::
+
--
[source,bash]
----
cd ~
rm -rf ~/lisk-test
rm -rf installLisk.sh
----
--
====

Get the latest install script:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
wget https://downloads.lisk.io/lisk/main/installLisk.sh
----
--
Testnet::
+
--
[source,bash]
----
wget https://downloads.lisk.io/lisk/test/installLisk.sh
----
--
====

Install the latest version of Lisk:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
bash installLisk.sh install -r main
----
--

Testnet::
+
--
[source,bash]
----
bash installLisk.sh install -r test
----
--
====

TIP: A prompt will appear asking for your installation directory.
To choose the default directory, press kbd:[Enter].
