= Update Lisk Core (Binary)
Mona Bärenfänger <mona@lightcurve.io>
:description: How to update Lisk Core to the latest version (Binary).
:toc:
:sectnums:
:experimental:
// Project URLs
:url_enable_forging: management/forging.adoc

How to update the Lisk Core binary distribution to a new version.

== Download the new Lisk Core version

Download the new Lisk Core version inside of your user home directory.

[tabs]
====
Mainnet::
+
--
*Linux:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz
wget https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz.SHA256
----

*MacOS:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-darwin-x64.tar.gz
wget https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-darwin-x64.tar.gz.SHA256
----
--
Testnet::
+
--
*Linux:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz
wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz.SHA256
----

*MacOS:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-darwin-x64.tar.gz
wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-darwin-x64.tar.gz.SHA256
----
--
====

== Verify Checksum

[tabs]
====
Linux::
+
--
[source,bash]
----
sha256sum -c lisk-core-v3.0.2-linux-x64.tar.gz.SHA256
# lisk-core-v3.0.2-linux-x64.tar.gz: OK
----
--
MacOS::
+
--
[source,bash]
----
sha256sum -c lisk-core-v3.0.2-darwin-x64.tar.gz.SHA256
----
--
====

== Stop Lisk Core

[source,bash]
----
pm2 stop lisk-core
----

== Backup Lisk Core
=== Backup your custom configs

In case you created custom configurations inside the `lisk-core/` folder, make sure to copy or move them out of the `lisk-core/` folder before removing them in the next step.

* `custom-config.json`: backup the custom configuration for Lisk Core
* `pm2.conf.json`: backup the pm2 config file

=== Backup the application data
[source,bash]
----
tar czf ~/backup_lisk.tar.gz ~/.lisk/
----

== Remove the old version

[source,bash]
----
rm -rf ~/lisk-core/
----

== Extract the new version

[tabs]
====
Linux::
+
--
[source,bash]
----
tar xzf ~/lisk-core-v3.0.2-linux-x64.tar.gz -C ~/
----
--
MacOS::
+
--
[source,bash]
----
tar xzf ~/lisk-core-v3.0.2-darwin-x64.tar.gz -C ~/
----
--
====

== Update the custom config

Update the custom configuration according to the provided default configurations for Lisk Core, located in `lisk-core/config/default/`, if necessary.

For updating to v3.0.2, it is highly important to ensure the new property `unlockFixHeight` is included in the configuration.

== Start Lisk Core

[source,bash]
----
pm2 start lisk-core
----

== Sanity Check

Verify the correct version

[source,bash]
----
lisk-core --version
#lisk-core/3.0.2 linux-x64 node-v12.22.7
----

Check if the new `unlockFixHeight` is correctly set:

* `unlockFixHeight` value for the Mainnet is `16785878`
* `unlockFixHeight` value for the Testnet is `14867989`.

.Example: Checking unlockFixHeight for Testnet
[source,bash]
----
lisk-core node:info --pretty | grep unlockFixHeight
"unlockFixHeight": 14867989
----

.For delegates
NOTE: *For delegates:* Don't forget to xref:{url_enable_forging}[] again after the update.

