= Binary
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Binary update page describes how to upgrade Lisk Core to the latest version.
:toc:
:experimental:
:v_sdk: master
:page-next: /lisk-core/3.0.0/monitoring.html
:page-previous: /lisk-core/3.0.0/management/binary.html
:page-next-title: Monitoring
:page-previous-title: Binary commands

:url_sdk_commander_liskcore: {v_sdk}@lisk-sdk::reference/lisk-commander/user-guide/lisk-core.adoc
:url_sdk_commander_commands: {v_sdk}@lisk-sdk::reference/lisk-commander/user-guide/commands.adoc
:url_enable_forging: management/forging.adoc

To upgrade Lisk Core from Binary please follow the instructions below.
Please choose the instructions specific to the network (Mainnet or Testnet), that your node is connected to.

== Update with Lisk Commander

IMPORTANT: The `core:upgrade` command is only supported for Lisk Core versions > `2.0.0` and will only work, if Lisk Core has been installed with Lisk Commander before.

Firstly, navigate into the directory where your Lisk Core installation is located.

Then, run the following command to upgrade Lisk Core:

[source,bash]
----
lisk core:upgrade <location>
----

Where `<location>` should be the root folder of your Lisk Core installation.

See  the Lisk Commander xref:{url_sdk_commander_liskcore}[Command reference for Lisk Core] for all available options, as well as the xref:{url_sdk_commander_commands}[General command reference].

== Update with bash script

=== Mainnet

[source,bash]
----
cd ~
rm -f installLisk.sh
wget https://downloads.lisk.io/lisk/main/installLisk.sh
bash installLisk.sh upgrade -r main
----

=== Testnet

[source,bash]
----
cd ~
rm -f installLisk.sh
wget https://downloads.lisk.io/lisk/test/installLisk.sh
bash installLisk.sh upgrade -r test
----

After running the above script manually or through `lisk_bridge.sh`, you will be prompted to select a few options.
Please read these thoroughly and follow the applicable steps.

[NOTE]
====
It is necessary to enable forging manually after the upgrade.
Please follow this guide to xref:{url_enable_forging}[enable forging on your delegate node] for further details.
====

== Manual update Lisk Core

Switch to your Lisk folder and stop Lisk processes as shown below:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cd ~
cd lisk-main
bash lisk.sh stop
----
--
Testnet::
+
--
[source,bash]
----
cd ~
cd lisk-test
bash lisk.sh stop
----
--
====

Backup your SSL folder (if needed) as shown below:

[source,bash]
----
mkdir ~/backup
cp -f ./ssl/* ~/backup/
cp -f ./config.json ~/backup/
----

Remove your old Lisk folder and install the script as shown below:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cd ~
rm -rf ~/lisk-main
rm -rf installLisk.sh
----
--
Testnet::
+
--
[source,bash]
----
cd ~
rm -rf ~/lisk-test
rm -rf installLisk.sh
----
--
====

Get the latest install script as shown below:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
wget https://downloads.lisk.io/lisk/main/installLisk.sh
----
--
Testnet::
+
--
[source,bash]
----
wget https://downloads.lisk.io/lisk/test/installLisk.sh
----
--
====

Install the latest version of Lisk as shown below:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
bash installLisk.sh install -r main
----
--
Testnet::
+
--
[source,bash]
----
bash installLisk.sh install -r test
----
--
====

TIP: You will be prompted for your installation directory, pressing kbd:[Enter] will choose the default.
