= Update Lisk Core (Binary)
Mona Bärenfänger <mona@lightcurve.io>
:description: How to update Lisk Core to the latest version (Binary).
:toc:
:sectnums:
:experimental:
// Project URLs
:url_enable_forging: management/forging.adoc

How to update the Lisk Core binary distribution to a new version.

== Download the new Lisk Core version

[tabs]
====
Mainnet::
+
--
*Linux:*

[source,bash]
----
wget -O lisk-core-v3.0.2.tar.gz https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz
wget https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz.SHA256
----

*MacOS:*

[source,bash]
----
wget -O lisk-core-v3.0.2.tar.gz https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-darwin-x64.tar.gz
wget https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-darwin-x64.tar.gz.SHA256
----
--
Testnet::
+
--
*Linux:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz
wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz.SHA256
----

*MacOS:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-darwin-x64.tar.gz
wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-darwin-x64.tar.gz.SHA256
----
--
====

== Verify Checksum

[tabs]
====
Linux::
+
--
[source,bash]
----
sha256sum -c lisk-core-v3.0.2-linux-x64.tar.gz.SHA256
# lisk-core-v3.0.2-linux-x64.tar.gz: OK
----
--
MacOS::
+
--
[source,bash]
----
sha256sum -c lisk-core-v3.0.2-darwin-x64.tar.gz.SHA256
----
--
====

== Stop Lisk Core

[source,bash]
----
pm2 stop lisk-core
----

== Backup Lisk Core

[source,bash]
----
tar cf ~/backup_lisk.tar.gz ~/.lisk/ ~/lisk-core/
----

== Extract the new version

[tabs]
====
Linux::
+
--
[source,bash]
----
tar xf /home/lisk/lisk-core-v3.0.2-linux-x64.tar.gz -C /home/lisk/
----
--
MacOS::
+
--
[source,bash]
----
tar xf /home/lisk/lisk-core-v3.0.2-darwin-x64.tar.gz -C /home/lisk/
----
--
====

IMPORTANT: In case a custom config file is used with Lisk Core, copy one of the default config files of the new Lisk Core version to use it as basis for the new custom config, and adjust it to your needs.

== Start Lisk Core

[source,bash]
----
pm2 start lisk-core
----

== Sanity Check

Verify the correct version

[source,bash]
----
lisk-core --version
#lisk-core/3.0.2 linux-x64 node-v12.22.7
----

Check if the new `unlockFixHeight` is correctly set:

[tabs]
====
Mainnet::
+
--
`unlockFixHeight` value for the Mainnet is `16785878`

[source,bash]
----
grep unlockFixHeight /home/lisk/.lisk/lisk-core/config/testnet/config.json
----
--
Testnet::
+
--
`unlockFixHeight` value for the Testnet is `14867989`.

[source,bash]
----
grep unlockFixHeight /home/lisk/.lisk/lisk-core/config/mainnet/config.json
----
--
====

.For delegates
NOTE: *For delegates:* Don't forget to xref:{url_enable_forging}[] again after the update.

