= Update Lisk Core (Binary)
Mona Bärenfänger <mona@lightcurve.io>
:description: How to update Lisk Core to the latest version (Binary).
:toc:
:sectnums:
:experimental:
// Project URLs
:url_enable_forging: management/forging.adoc

How to update the Lisk Core binary distribution to a new version.

== Download the new Lisk Core version

Download the new Lisk Core version inside of your user home directory.

[tabs]
====
Mainnet::
+
--
*Linux:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/main/3.0.3/lisk-core-v3.0.3-linux-x64.tar.gz
wget https://downloads.lisk.io/lisk/main/3.0.3/lisk-core-v3.0.3-linux-x64.tar.gz.SHA256
----

*MacOS:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/main/3.0.3/lisk-core-v3.0.3-darwin-x64.tar.gz
wget https://downloads.lisk.io/lisk/main/3.0.3/lisk-core-v3.0.3-darwin-x64.tar.gz.SHA256
----
--
Testnet::
+
--
*Linux:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/3.0.3/lisk-core-v3.0.3-linux-x64.tar.gz
wget https://downloads.lisk.io/lisk/test/3.0.3/lisk-core-v3.0.3-linux-x64.tar.gz.SHA256
----

*MacOS:*

[source,bash]
----
wget https://downloads.lisk.io/lisk/test/3.0.3/lisk-core-v3.0.3-darwin-x64.tar.gz
wget https://downloads.lisk.io/lisk/test/3.0.3/lisk-core-v3.0.3-darwin-x64.tar.gz.SHA256
----
--
====

== Verify Checksum

[tabs]
====
Linux::
+
--
[source,bash]
----
sha256sum -c lisk-core-v3.0.3-linux-x64.tar.gz.SHA256
# lisk-core-v3.0.3-linux-x64.tar.gz: OK
----
--
MacOS::
+
--
[source,bash]
----
sha256sum -c lisk-core-v3.0.3-darwin-x64.tar.gz.SHA256
----
--
====

== Stop Lisk Core

[source,bash]
----
pm2 stop lisk-core
----

== Backup Lisk Core
=== Backup your custom configs

In case you created custom configurations inside the `lisk-core/` folder, make sure to copy or move them out of the `lisk-core/` folder before removing them in the next step.

* `custom-config.json`: backup the custom configuration for Lisk Core.
* `pm2.conf.json`: backup the pm2 config file.

=== Backup the application data
[source,bash]
----
tar czf ~/backup_lisk.tar.gz ~/.lisk/
----

== Remove the old version

[source,bash]
----
rm -rf ~/lisk-core/
----

== Extract the new version

[tabs]
====
Linux::
+
--
[source,bash]
----
tar xzf ~/lisk-core-v3.0.3-linux-x64.tar.gz -C ~/
----
--
MacOS::
+
--
[source,bash]
----
tar xzf ~/lisk-core-v3.0.3-darwin-x64.tar.gz -C ~/
----
--
====

== Start Lisk Core

Note: If you have configured your `pm2.config.json`, please use that configuration.

[source,bash]
----
pm2 start lisk-core
----

== Sanity Check

Verify the correct version.

[source,bash]
----
lisk-core --version
#lisk-core/3.0.3 linux-x64 node-v12.22.9
----

Check if the new `transferFixHeight, serializationFixHeight` is correctly set:

* `transferFixHeight, serializationFixHeight` value for the Mainnet is `17557156`.
* `transferFixHeight, serializationFixHeight` value for the Testnet is `15466999`.

.Example: Checking transferFixHeight, serializationFixHeight for Testnet
[source,bash]
----
lisk-core node:info --pretty | grep "serializationFixHeight\|transferFixHeight"
"transferFixHeight, serializationFixHeight": 15466999
----

.For delegates
NOTE: *For delegates:* Don't forget that xref:{url_enable_forging}[] again is required after the update.

