= Update Commander application
Mona Bärenfänger <mona@lightcurve.io>
:description:  Describes how to update Lisk Core to the latest version via Lisk Commander.
:page-aliases: upgrade/commander.adoc
:toc:
:v_core: 2.1.5
:page-next: /lisk-core/monitoring.html
:page-previous: /lisk-core/management/commander.html
:page-next-title: Monitoring
:page-previous-title: Commander application commands

:url_binary_release: https://downloads.lisk.io/lisk/mainnet/
:url_setup_commander: setup/commander.adoc#install

NOTE: The `core:upgrade` command is only supported for Lisk Core versions greater than 2.0.0.

== Update

[tabs]
=====
Mainnet::
+
--
To upgrade Lisk Core, execute the following command:

[source,bash]
----
lisk core:upgrade lisk-mainnet <1>
----
<1> Exchange `INSTANCE` with the name of your Lisk Core instance, which you chose during the xref:{url_setup_commander}[Installation of Lisk Core].
--
Testnet::
+
--
To upgrade Lisk Core, execute the following command:

[source,bash]
----
lisk core:upgrade lisk-testnet <1>
----
<1> Exchange `INSTANCE` with the name of your Lisk Core instance, which you chose during the xref:{url_setup_commander}[Installation of Lisk Core].
--
=====

[TIP]
====
If you have forgotton the name of the Lisk instance, this can be found in the `instances` directory by executing the following command below:

[source,bash]
----
ls ~/.lisk/instances/ <1>
----
<1> Lists all available Lisk Core instances
====

== Available options

Add one or more of the multiple options listed below to the `core:upgrade` command. Multiple options are seperated by spaces.

|===
| Full Name | Short Name | Examples | Description

| `--release-url` | `-r`
| `--release-url=https://my-custom.url/testnet/2.1.0-rc.0/lisk-2.1.0-rc.0-Linux-x86_64.tar.gz`
| Define a custom URL for downloading the new Lisk Core application script.
It is also necessary to have the checksum for the TAR file with the format 2.0.0-Linux-x86_64.tar.gz.SHA256, for the Commander application to check the integrity of the application.
For the file naming convention, please refer to the {url_binary_release}[Lisk Core application releases^].

| `--lisk-version`
| N/A
a|
* `--lisk-version=2.0.0`
* `--lisk-version=2.1.3`
| Define the specific version, Lisk Core should be upgraded to.
|===
