= Commander application
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes how to upgrade Lisk Core to the latest version via Lisk Commander.
:toc:
:v_core: 2.1.3
:page-next: /lisk-core/3.0.0/monitoring.html
:page-previous: /lisk-core/3.0.0/management/commander.html
:page-next-title: Monitoring
:page-previous-title: Commander application commands

:url_binary_release: https://downloads.lisk.io/lisk/mainnet/

:url_setup_commander: setup/commander-application.adoc#install


== Update with Lisk Commander application

To update the Lisk Core application please follow the instructions below.

=== Betanet

Firstly, navigate into the directory where your Lisk Core installation is located.

To upgrade Lisk Core, execute the following command:

[source,bash]
----
lisk core:upgrade lisk-betanet <1>
----

[TIP]
====
If you have forgotton the name of the Lisk instance, please open and view the contents of the `instances` directory by executing the following command below:

[source,bash]
----
ls ~/.lisk/instances/ <1>
----
<1> Lists all available Lisk Core instances.
====

Available options::

Add either one or multiple options listed below to the `core:upgrade` command.
Multiple options are seperated by spaces.

|===
| Full Name | Short Name | Examples | Description

| `--release-url` | `-r`
| `--release-url=https://my-custom.url/testnet/2.1.0-rc.0/lisk-2.1.0-rc.0-Linux-x86_64.tar.gz`
| Defines a custom URL for downloading the new Lisk Core application script.
It is also necessary to have the checksum for the TAR file with the format 2.0.0-Linux-x86_64.tar.gz.SHA256, in order for the Commander to check the integrity of the application.
Please refer to the {url_binary_release}[Lisk Core application releases^] for the file naming convention.

| `--lisk-version`
| N/A
a|
* `--lisk-version=2.0.0`
* `--lisk-version=2.1.3`
| Defines the specific version that should be used to update Lisk Core.
|===
