= Docker image
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes how to upgrade Lisk Core to the latest version with Docker.
:toc:
:page-next: /lisk-core/3.0.0/monitoring.html
:page-previous: /lisk-core/3.0.0/management/docker.html
:page-next-title: Monitoring
:page-previous-title: Docker image commands

:url_core_repository: https://github.com/LiskHQ/lisk-core
:url_current_version: https://github.com/LiskHQ/lisk-core/tree/development/docker
:url_version_tag: https://github.com/LiskHQ/lisk-core/tags

[[minor-version]]
== Upgrade minor versions

To update a Lisk installation using Docker Compose it is only required to export the new version number in `ENV_LISK_VERSION`.

Example: Update from Lisk Core 2.1.5 to 3.0.0 by executing the following commands:

[source,bash]
----
export ENV_LISK_VERSION=3.0.0
docker-compose up -d
----

To Update the Lisk installation execute `docker-compose up -d`

== Update major versions

For major version updates there may be additional changes in `docker-compose.yml`

In this case Lisk Core provides an updated version of `docker-compose.yml` in the {url_core_repository}[Lisk Core repository^] on Github, inside the `docker` folder: {url_current_version}[current version^].

(Where `<CURRENT_VERSION>` is the {url_version_tag}[version tag^] of the update version you wish to use.)

Use the following file as a new template for your `docker-compose.yml`

The remainder of the upgrade process is analog to the <<minor-version,minor version upgrade>>.
