= Docker image
Mona Bärenfänger <mona@lightcurve.io>
:description: How to upgrade Lisk Core with Docker.
:toc:

:url_core_repository: https://github.com/LiskHQ/lisk-core
:url_current_version: https://github.com/LiskHQ/lisk-core/tree/development/docker
:url_version_tag: https://github.com/LiskHQ/lisk-core/tags

[[minor-version]]
== Upgrade minor versions

To update a Lisk installation using Docker Compose it is only required to export the new version number in `ENV_LISK_VERSION`.

Example: Update from Lisk Core by executing the following commands:

[source,bash]
----
export ENV_LISK_VERSION=3.0.2
docker-compose up -d
----

== Update major versions

For major version updates there may be additional changes in `docker-compose.yml`

In this case Lisk Core provides an updated version of `docker-compose.yml` in the {url_core_repository}[Lisk Core repository^] on Github, inside the `docker` folder: {url_current_version}[current version^].

(Where the `<CURRENT_VERSION>` is the {url_version_tag}[version tag^] of the update version you wish to use.)

Use this file as a new template for your `docker-compose.yml`

The remainder of the upgrade process is analog to the <<minor-version,minor version upgrade>>.
