= Update Docker image
Mona Bärenfänger <mona@lightcurve.io>
:description: The Docker image update page describes how to upgrade Lisk Core to the latest version with Docker.
:page-aliases: upgrade/docker.adoc
:toc:
:page-next: /lisk-core/monitoring.html
:page-previous: /lisk-core/management/docker.html
:page-next-title: Monitoring
:page-previous-title: Docker image commands

:url_core_repository: https://github.com/LiskHQ/lisk-core
:url_current_version: https://github.com/LiskHQ/lisk-core/tree/development/docker
:url_version_tag: https://github.com/LiskHQ/lisk-core/tags

[[minor_version]]
== Upgrade minor versions

To upgrade a Lisk installation using Docker Compose, the only requirement necessary is to export the new version number in `ENV_LISK_VERSION`.

Example: To perform the update from Lisk Core 2.0.0 to 2.1.1, execute the following command:

[source,bash]
----
export ENV_LISK_VERSION=2.1.1
docker-compose up -d
----

To update the Lisk installation, execute the following command `docker-compose up -d`.

== Update major versions

For major version upgrades, there may be additional changes within `docker-compose.yml`.

In this case, Lisk Core provides an updated version of `docker-compose.yml` which can be found in the {url_core_repository}[Lisk Core repository] on Github, inside the `docker` folder: {url_current_version}[current version].

(Where `<CURRENT_VERSION>` is the {url_version_tag}[version tag] of the version you wish to upgrade to.)

Use this file as a new template for your `docker-compose.yml`.

The remainder of the upgrade process is analog to the <<minor_version,minor version upgrade>>.
