= Docker Update
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Docker Update page describes how to upgrade Lisk Core to the latest version with Docker.
:toc:

:url_core_repository: https://github.com/LiskHQ/lisk-core
:url_current_version: https://github.com/LiskHQ/lisk-core/tree/development/docker
:url_version_tag: https://github.com/LiskHQ/lisk-core/tags

[[minor-version]]
== Upgrade minor versions

To upgrade a Lisk installation using Docker Compose you simply need to export the new version number in `ENV_LISK_VERSION`.

Example: Update from Lisk Core 2.0.0 to 2.1.1 by executing:

[source,bash]
----
export ENV_LISK_VERSION=2.1.1
docker-compose up -d
----

To Update the Lisk installation run `docker-compose up -d`.

== Update major versions

For major version upgrades, there can be additional changes in `docker-compose.yml`.

In this case, Lisk Core provides an updated version of `docker-compose.yml` in the {url_core_repository}[Lisk Core repository] on Github, inside the `docker` folder: {url_current_version}[current version]

(Where `<CURRENT_VERSION>` is the {url_version_tag}[version tag] of the version you want to upgrade to.)

Use this file as a new template for your `docker-compose.yml`.

The rest of the upgrade process is analog to the <<minor-version,minor version upgrade>>.
