= Update
Mona Bärenfänger <mona@lightcurve.io>
:description: The Update page provides a brief overview, together with the associated links for updating all installations.

:url_update_binary: update/binary.adoc
:url_update_commander: update/commander.adoc
:url_update_docker: update/docker.adoc
:url_update_source: update/source.adoc


This section describes how to perform the necessary updates for the  Binary, Commander, Docker and Source  installations.


== Binary

The xref:{url_update_binary}[Binary] update section comprises of how to perform an update with the Lisk Commander, and also via the bash script as well as manually.

== Lisk Commander

The Lisk xref:{url_update_commander}[Commander] update process covers the available options with their descriptions.

== Docker

The xref:{url_update_docker}[Docker] process explains how to upgrade the minor versions and update the major versions.

== Source

The xref:{url_update_source}[Source] update details how to upgrade Lisk Core and also pull the latest tagged releases.

Dependent on the installation performed then the relevant updates can be completed by following the procedures within this section.





