= Update
Mona Bärenfänger <mona@lightcurve.io>
:description: The Update page provides a brief overview, together with the associated links for updating all installations.

:url_update_binary: update/application.adoc
:url_update_commander: update/commander.adoc
:url_update_docker: update/docker.adoc
:url_update_source: update/source.adoc


This section describes how to perform the necessary updates for the Lisk Core application, Lisk Core Commander application, Docker image and Source code installations.


== Application

The xref:{url_update_binary}[Application] update section comprises of how to perform an update with the Lisk Commander, and also via the bash script as well as manually.

== Lisk Commander application

The Lisk xref:{url_update_commander}[Commander application] update process covers the available options with their descriptions.

== Docker image

The xref:{url_update_docker}[Docker image] update explains how to upgrade to minor versions and major versions.

== Source code

The xref:{url_update_source}[Source code] update details how to update Lisk Core and also pull the latest tagged releases.

Dependent on the installation performed then the relevant updates can be completed by following the procedures within this section.


