= Update Lisk Core (NPM)
Mona Bärenfänger <mona@lightcurve.io>
:description: How to update Lisk Core to the latest version (Binary).
:toc:
:sectnums:
:experimental:
// Project URLs
:url_enable_forging: management/forging.adoc

== Check for new versions

[source,bash]
----
npm outdated --global --depth=0
----

[source,bash]
----
Package    Current   Wanted  Latest  Location
lisk-core    3.0.1    3.0.2   3.0.2  global
----

As the output indicates, we currently have v3.0.1 installed, but the latest version of Lisk Core is `v3.0.2`.

== Stop Lisk Core

[source,bash]
----
pm2 stop lisk-core
----

== Backup Lisk Core

[source,bash]
----
tar czf ~/backup_lisk.tar.gz ~/.lisk/lisk-core
----

== Install the new version

IMPORTANT: In case a custom config file is used with Lisk Core, copy one of the default config files of the new Lisk Core version to use it as basis for the new custom config, and adjust it according to your old custom config.

[source,bash]
----
npm update --global lisk-core
----

== Start Lisk Core

[source,bash]
----
pm2 start lisk-core
----

== Sanity Check

Verify the correct version

[source,bash]
----
lisk-core --version
#lisk-core/3.0.2 linux-x64 node-v12.22.7
----

Check if the new `unlockFixHeight` is correctly set:

* `unlockFixHeight` value for the *Mainnet* is `16785878`
* `unlockFixHeight` value for the *Testnet* is `14867989`.

.Example: Checking `unlockFixHeight` for Testnet
[source,bash]
----
lisk-core node:info --pretty | grep unlockFixHeight
"unlockFixHeight": 14867989
----

.For delegates
NOTE: *For delegates:* Don't forget to xref:{url_enable_forging}[] again after the update.

