= Update Lisk Core (source code)
Mona Bärenfänger <mona@lightcurve.io>
:description: How to upgrade Lisk Core from source.
:toc:
:sectnums:

:url_core_releases: https://github.com/LiskHQ/lisk-core/releases

:url_enable_forging: management/forging.adoc

This section describes how to update Lisk Core to a specific version from source code

== Stop the old Lisk Core
Stop the node. If you are using pm2 you can do this by executing the following command:

[source,bash]
----
pm2 stop lisk
----

== Backup Lisk Core

[source,bash]
----
tar czf ~/backup_lisk.tar.gz ~/.lisk/ ~/lisk-core/
----

== Switch to the new version

Pull the latest {url_core_releases}[tagged release^] using Git:

.~/lisk-core/
[source,bash]
----
cd lisk-core/ #<1>
git fetch #<2>
git checkout v3.0.2 -b v3.0.2 #<3>
----

<1> Navigate into the root directory of Lisk Core.
<2> Fetch the latest releases.
<3> To view the latest release tag, please see {url_core_releases}[Lisk Core releases^].

== Install the new version

Install node modules as shown below in the following commands:

[source,bash]
----
npm ci #<1>
npm run build #<2>
----

<1> Install node modules.
<2> Compile packages.

== Start Lisk Core again

Start the node again by executing the following command below:

[source,bash]
----
pm2 start lisk
----

== Sanity Check

Verify the correct version

[source,bash]
----
lisk-core --version
#lisk-core/3.0.2 linux-x64 node-v12.22.7
----

Check if the new `unlockFixHeight` is correctly set:

* `unlockFixHeight` value for the Mainnet is `16785878`
* `unlockFixHeight` value for the Testnet is `14867989`.

.Example: Checking unlockFixHeight for Testnet
[source,bash]
----
lisk-core node:info --pretty | grep unlockFixHeight
"unlockFixHeight": 14867989
----

.For delegates
NOTE: *For delegates:* Don't forget to xref:{url_enable_forging}[] again after the update.
