= Glossary
Chris Braithwaite <christopher.braithwaite@lightcurve.io>
:description: SDK glossary of terms from A to Z.
:toc:
:imagesdir: ../../assets/images
:page-no-next: true
:docs_sdk: lisk-sdk::
:idprefix:
:idseparator: -

:url_aes: https://proprivacy.com/guides/aes-encryption
:url_bch_codes: https://en.wikipedia.org/wiki/BCH_code#:~:text=In%20coding%20theory%2C%20the%20BCH,(also%20called%20Galois%20field).&text=This%20simplifies%20the%20design%20of,small%20low%2Dpower%20electronic%20hardware
:url_rocksdb: https://rocksdb.org/
:url_semver: https://semver.org/
:url_fork: https://lisk.com/blog/research/lisk-mainnet-regenesis

:url_delegate_misbehavior: understand-blockchain/lisk-protocol/transactions.adoc#pom
:url_discover_misbehavior: {docs_sdk}modules/dpos-module.adoc#discover
:url_protocol_transactions_pom: understand-blockchain/lisk-protocol/transactions.adoc#pom
// :url_transaction_properties: understand-blockchain/lisk-protocol/transactions.adoc#transaction-properties
:url_dpos: {docs_sdk}modules/dpos-module.adoc#dpos
:url_delegate_registration: run-blockchain/forging.adoc#registering-a-delegate
:url_delegate_registration_tx: run-blockchain/forging.adoc#create-the-delegate-registraton-transaction

:url_genesis_block: understand-blockchain/lisk-protocol/blocks.adoc#genesis-block
:url_reclaim_lsk: lisk-core::index.adoc#lsk-reclaim
:url_tx_properties: understand-blockchain/lisk-protocol/transactions.adoc#transaction-properties
:url_multisignature: understand-blockchain/lisk-protocol/transactions.adoc#multisignature
:url_token_transfer: understand-blockchain/lisk-protocol/transactions.adoc#transfer
:url_token_unlock: understand-blockchain/lisk-protocol/transactions.adoc#unlock
:url_data_structure: understand-blockchain/codec-schema.adoc#data-types
:url_hash_onion: {docs-sdk}references/lisk-elements/modules/cryptography.adoc#hashOnion
:url_blockchain_app: build-blockchain/index.adoc
:url_mainnet: lisk-core::index.adoc#mainnet
:url_state_store: {docs-sdk}references/lisk-elements/modules/chain.adoc
:url_reducer: understand-blockchain/sdk/modules-assets.adoc#reducers
:url_base_endpoint: understand-blockchain/sdk/modules-commands.adoc#the-baseendpoint-class
:url_github_lip_46: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0046.md


== A

=== Account

An account is an address with an amount of tokens referred to as the balance.
// Furthermore, accounts are serialized and deserialized according to the account schema.
// An account consists of a unique identifier / <<account-address,address>>, an amount of tokens referred to as balance and possibly some additional properties used in other parts of the blockchain application.

=== Account address

The address is a unique identifier which has state information associated with it for accounts in the Lisk blockchain.
They are the 20-byte hash value of the public key that controls the account initially.
In all front-end products, addresses are displayed in a human-readable representation called <<Lisk32 format>>.
An example for an address in Lisk32 presentation is `lskxwnb4ubt93gz49w3of855yy9uzntddyndahm6s`.
When referring to addresses in Lisk, we always assume the Lisk32 format, without explicitly having to mention it.
In the Lisk protocol and SDK only the 20 byte value is stored for efficiency and sometimes the hexadecimal representation of the address is used.
Further details regarding other address formats can be seen here in the xref:{url_data_structure}[table for different data types] on the schema reference page.

=== Active delegate

An active delegate (now classed as a validator), can mostly be considered as an entity, that can generate new blocks for the Lisk blockchain.
A total of 101 validators exist in Lisk blockchain, for this purpose and each validator is ranked from 1-101.

// An active delegate can mostly be considered as a forging delegate, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.

// === Address initialization (Removed as agreed with Research)

// The process of sending the first transaction on the Lisk blockchain.
// With that the public key is permanently stored as part of the users address in the Lisk blockchain and checked every time a transaction is sent.
// Hence, the users account is secure, even in the very rare case of an address collision.

=== AES-256-CBC - Advanced encryption standard

The Advanced Encryption Standard (AES), has a key length of 256 bits and is a block cipher adopted as an encryption standard by the U.S. government for military and government use. CBC (Cipher Blocker Chaining), is an advanced form of block cipher encryption.
A detailed description of how AES functions can be found {url_aes}[here^].

=== Alphanet

A temporary, internal-only testing network of a Lisk Core alpha candidate.

=== API

The API is defined as the interface for module-to-module communication.

//An API is an application programming interface, and is classed as software intermediary that allows applications to communicate with each other.

=== Application hooks

Application hooks are defined as module methods that are only called during the block generation.
These hooks can introduce state changes but are unable to mutate the block.

=== Authorities

A special term for validators in a PoA sidechain.

=== Auth module

The Auth module is responsible for handling and verifying nonces and for transaction signature validation which includes transactions from multisignature accounts.
Furthermore, an updated multisignature registration process is now used, based on the new registration parameters.
Finally, a new storage interface for the Auth module is available, which in turn will become part of the state tree and will be authenticated by the state root.

=== Authority update command

A transaction used to update the active validators in PoA chains.

== B

=== BCH Codes - Bose, Chaudhuri, and Hocquenghem codes

BCH codes are error-correcting codes. The Bose, Chaudhuri and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
large class of powerful random error-correcting cyclic codes.

=== Beddow

A Beddow is the smallest unit of a LSK token. 100 million Beddows is equal to 1 <<LSK>>.

=== Betanet

A temporary, external public testing network for the Lisk Core beta candidate.

=== BFT - Byzantine fault tolerance

In a system whereby components need to come to an agreement to reach a consensus,  byzantine failures will prevent those components from reaching an agreement, (usually caused by errors that are hard to detect).
A Byzantine Fault Tolerant system ensures that measures are taken to manage such failures.

=== BFT module

The BFT module is responsible for maintaining the consensus participants, their BFT weights, and all information related to the consensus votes that have been cast as part of the block headers.

=== BFT weight

The weight of validators that are considered in Lisk-BFT for finalizing blocks and for creating valid certificate signatures.

=== BIP - Bitcoin improvement proposal

A Bitcoin Improvement Proposal (BIP), can be defined as a standard for proposing changes to the Bitcoin protocol.
For example, BIP39 is one of many bitcoin improvement proposals.
This particular proposal describes the mnemonic code or mnemonic sentence implementation,
and how to create a human-readable mnemonic sentence including how to convert that mnemonic into a seed.

=== Blockchain application

A xref:{url_blockchain_app}[blockchain application] is any kind of application which uses its own blockchain as a database layer. For example, this can be an application running on its own blockchain built with the Lisk SDK.

=== Blockchain App

Short form of blockchain application.

=== Block assets

The block assets contain data created by individual modules.
This consists of an array of bytes, whereby each value corresponds to an object serialized according to the `assetSchema` property.
The block assets, together with the transactions, form the block payload.

=== Blockchain client

A blockchain client is defined as the software that runs a blockchain node.

=== Blockchain generation hooks

Block generation hooks can add information to the block assets, but cannot introduce any state changes.
These are module methods which are called during the actual block generation.

=== Block header

A block is composed of a block header and a payload of transactions.
The block header contains all information related to the block as well as a hash of the payload.

=== Block height

The number of blocks in the blockchain between the genesis block and the block of the specified block height.

=== Block ID

A hash of a block header that uniquely identifies a block in the Lisk blockchain.

== C

=== Chain ID

A unique identifier of a chain account.
It is used when sending tokens to a specific chain and also prepended for signing to protect against replay attacks.

=== Chain of trust

The property that is always a 2/3 majority of the previous validators that sign the new validator set.

=== Chain validators substore

The chain validators substore holds information about the validators of other partner chains.

// === Consenter (Removed as agreed with Research)

// Within the mainchain only active delegates are classed as consenters, hence this does not apply to standby delegates.

=== Command

A command is defined as a group of state-transition logics that are triggered by a specific transaction.
This can be identified by the module and command name of the transaction.
The actual command name is unique within the relevant module that it is associated with.

=== Cross-chain

Cross-chain refers to the interoperability between two or more different independent blockchains.

=== Cross-chain certification

The general technique of how the mainchain and sidechains communicate.
Furthermore, the information received from another blockchain is accepted, if the correctness of this information is attested by a certificate.

=== Cross-chain command

Cross-chain messages (CCMs), are responsible for triggering the logic defined by the cross-chain command, that is identified by both the module name and the cross-chain command name.

=== Cross-chain message

A data object used to exchange information between different chains.
It is added the outbox of the sending chain, later to the respective certificates, and eventually to the inbox of the receiving chain.

=== Cross-chain NFT transfer

The name of the transaction that transfers non-fungible tokens from one chain to another (sidechain to sidechain).

=== Cross-chain transaction

The name of the transaction that transfers fungible tokens from one chain to another (e.g., mainchain to sidechain).
Transactions that add cross-chain messages to the outbox as part of the transaction processing.

=== Cross-chain update command

A command for submitting updates about the state of the chain and new cross-chain messages.

=== Custom transaction

A new transaction type with its own logic for a blockchain application.
Typically, there is a state change on the blockchain.

== D

=== Delegate

A special term for validators in a DPoS sidechain.
//An account which performed the delegate registration and is now able to receive votes.
//An active delegate is now known as a <<consenter>>.
// === Delegate misbehaviour report transaction - now called Proof of Misbehavior - PoM

// A xref:{url_delegate_misbehavior}[delegate misbehavior report] refers to a transaction type on the Mainnet which reports a delegates misbehavior. +
// Any misbehavior of a delegate is xref:{url_discover_misbehavior}[indicated] by two contradicting block headers signed by the delegate.

=== Delegate registration transaction

A xref:{url_delegate_registration}[delegate registration] is achieved by sending a xref:{url_delegate_registration_tx}[delegate registration transaction] on the mainnet, which registers a delegate to participate in the Delegated Proof-of-Stake consensus algorithm.

=== Delegate misbehavior report

A transaction type on the mainnet which reports a delegate misbehavior.

=== Delegate vote

A transaction type on the mainnet which submits votes for delegates.
If the votes are positive it adds the voting weight, if they are negative it removes the voting weight again.
If voting weight was added, the corresponding LSK tokens are locked and cannot be used for any other transaction.

=== Delegate weight

The weight of delegates in DPoS determines whether a delegate is active, on standby, or not eligible to generate blocks.
It is computed from the self-votes and the total amount of received votes.
// The delegate weight is an indicator which shows the active support received by a delegate that is present in the network. To maintain a secure and effective setup, the delegate weight is bound to 10 times the self-votes.
// The weight of a delegate is the sum of all votes for a particular delegate that includes self-votes.

=== Devnet

A blockchain network for development purposes.
The Lisk SDK provides a dedicated genesis block and configurations to conveniently set up a local Devnet during the development of a blockchain application.

=== DPoS - Delegated proof of stake

xref:{url_dpos}[DPoS] is the mechanism of determining eligible block creators achieved by voting for registered delegate accounts, which are then able to create blocks depending on their vote weight.
It is part of the consensus algorithm of a blockchain and is used on Lisk Mainnet and in the Lisk SDK.

=== DPoS module

The DPoS module is responsible for handling all aspects of the generator selection, this includes the registration of accounts as delegates, the voting process, and potential misbehavior reports.

== E

=== Ed25519 - High speed high security signature

Ed25519 is a public-key signature system with several attractive features: Fast single-signature verification.
Ed25519 signatures are elliptic-curve signatures, carefully engineered at several levels of design and implementation to achieve very high speeds without compromising security.

=== Endpoint

In general, an endpoint is one end of a communication channel.
In Lisk, an endpoint is defined as an interface between a module and an external system via an RPC endpoint.
The actual endpoints are individually defined for each module, as this will depend on the requirements of the actual module.

=== Events

Events emit on-chain data during the processing of a block which adds additional information regarding the execution of state transitions.

== F

=== Faucet

A Faucet is generally defined in the blockchain world as a tool whereby users can receive a certain amount of tokens for free.
For Lisk blockchain apps, the faucet plugin can be registered with the application to provide a basic faucet, which is useful during the development phase, and also for proof-of-concept blockchain applications.

// === Forging  - Forger is now Generator

// How delegates produce new blocks on the Lisk blockchain.

=== Fee module

The fee module is responsible for handling the transaction fees.
It allows chains to choose the token used to pay the fee, and to define a minimum fee in order for transactions to be valid.

=== Forge

How delegates produce blocks on the Lisk blockchain.

=== Fork

A fork can be defined as an occurrence of a blockchain diverging into two forward paths in the network.
In other words it is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.
For further detailed information regarding forking in the Lisk network, see the following {url_fork}[Lisk Mainnet hard fork process^] description in the Lisk Mainnet Regenesis page

=== Framework plugin

A self-contained, off chain component which extends the standard feature set of the Lisk SDK by a specific use case, e.g. a node monitor plugin or delegate forging plugin.
Typically there is no state change on the blockchain.

== G

=== Generator

A generator can mostly be considered as a forging generator, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.

=== Genesis block

The xref:{url_genesis_block}[genesis block] describes the very first block in the blockchain.
It defines the initial state of the blockchain on start of the network.
A genesis block must be given to the application, and all networks should have a different genesis block.

== H

=== Hash onion

The hash onion stores the random seeds of the validator and is required for each forging round, this can be generated by the Lisk Commander.
More details can be found in the xref:{url_hash_onion}[enable forging] section.

== I

=== Inbox

The inbox is a data structures that contain information relevant to verify and process a certificate.

=== Interoperability

Interoperability can simply be defined as the ability of different blockchain networks being able to freely communicate, and transfer data and digital assets between each other.

=== Interoperability module

The interoperability module provides functionalities that will allow the transmission of information between interoperable chains in the Lisk ecosystem using cross-chain messages.
In order to validate and process the relevant commands, the interoperability module stores the required necessary properties.

== J

== K

=== Key derivation path

Key derivation allows multiple key pairs to be derived from the same secret recovery phrase.
The key derivation path allows an HD (Hierarchical Deterministic), wallet to derive a specific key from within a tree of keys.
The key derivation path in Lisk follows the industry standard, therefore ensuring forward compatibility with any future third-party products.

== L

=== Legacy module

The Legacy module is responsible for maintaining all accounts on the Lisk mainchain that received balance transfers to their address in the old 8-byte format, and for which no public key is associated.
Furthermore, it also implements a command allowing validators without a BLS key to register one.

=== Lisk framework

Lisk Framework is an application framework responsible for establishing and maintaining the interactions between the modules of a blockchain application compatible with the Lisk protocol. It provides an application where off-chain and on-chain logic can be extended with user defined plugins and modules.

=== LIP - Lisk improvement proposal

A LIP is a document usually structured by the research team defining technical changes in the Lisk protocol.
In addition, it can also cover an implementation or a non-technical process surrounding Lisk.
Furthermore, a LIP also describes the requirements, rationale and motivation for the required changes.

=== Lisk ecosystem

The Lisk ecosystem represents the third-party environment of Lisk, e.g. community members, exchanges, and sidechains.

=== Lisk SDK

The Lisk SDK is an open-source software development kit which enables developers to easily build scalable Blockchain applications using JavaScript.

=== Lisk Testnet

The official testing network of Lisk.
It can be thought of as an instance of a blockchain which is used for testing purposes, and consists of a the same version of the mainnnet underlying software.
All testing and experimentation can be performed on the testnet without jeopardizing the actual mainnet.

=== Lisk32 format

The Lisk32 format of an <<Account address>> starts with the letters "lsk" followed by a custom Base32 encoding of the 20 bytes of the address appended with a BCH checksum.
The checksum is used to check for small errors in the address.
Any errors in up to 4 characters are guaranteed to be detected and errors in more than 5 characters are likely to be detected.
The choice of the Lisk32 format of addresses does not modify the address, but is introduced to provide a safer and more pleasant experience to users.

=== LSK

The token used in the Lisk Mainnet.

=== LSK reclaim

A transaction type on Mainnet which converts a previously non-initialized account’s address to the new address system.
This is required because the public key is required to convert from the old address system to the new address system. Non-initialized accounts don’t have a public key associated with them yet.

== M

=== Mainchain

The mainchain can be defined as series of blocks created from the initial genesis block to the latest block.
All transactions or processes that occur on the mainchain are not confirmed until they are finalized on the mainchain.

=== Lisk Mainnet

A xref:{url_mainnet}[mainnet] is a fully developed functional and independent blockchain, running on its own network and using its own protocol and technology.
It is the official main network within Lisk.

// === Module Asset (Now changed to Command)

// A module asset allows a module to execute specific state changes on the blockchain based on transactions. A <<transaction>> with the corresponding module & asset ID needs to be sent to the <<blockchain-application>> in order to trigger the logic defined in a certain module asset. The data provided in the <<transaction-asset>> provides the required input data to execute the desired state changes.

=== Message fee

A property of a cross-chain message that is an amount of LSK that is credited to the relayer in the receiving chain.

=== Message recovery command

A mainchain command to recover a pending message in the inbox of a terminated sidechain.

=== Message recovery initialization command

A command to create the necessary state structures so that message recovery can happen.

=== Method

A method is the interface for the module-to-module communication.

=== Minimum return fee

If the message fee is at least the minimum return fee that the receiving sidechain guarantees, that in case of an error a failure message will be returned.

=== Module

A module enables a blockchain application to have application specific on-chain logic.
Modules are able to perform state changes on the related blockchain.
For example, the Lisk SDK modules can define state machine and block generation hooks.
They can also define commands to add the related logic to the state machine.

=== Module endpoint

Module endpoints enable data to be retrieved from a blockchain application.
// Each module endpoint always extends from the xref:{url_base_endpoint}[BaseEndpoint] class.

=== Module methods

Module methods are hooks, such as application hooks and block generation hooks.
These methods are called during actions such as during the block execution and block generation.

=== Multisignature group registration transaction

A transaction type on all networks based on the Lisk protocol which registers a xref:{url_multisignature}[multisignature group].
This transaction registers the sender account as a multisignature group account.

== N

=== NFT - Non fungible token

NFTs are digital assets in the form of unique cryptographic tokens. Examples can represent real-world objects such as art, music, games, and videos, which due to their uniqueness can result in them becoming collectible items of value.

=== NFT ID

A unique identifier in the Lisk ecoysystem for a specific NFT created by the NFT module.

=== NFT module

Name of the non-fungible token standard module.
// The NFT (non-fungible token), module is responsible for creating, destroying, and transferring NFTs within the Lisk ecosystem.
// Furthermore, the NFT module ensures the NFT unique identifiers are never modified.
// Finally, the NFT module provides the functionality of locking/unlocking the NFTs which restrict the user transferring NFTs within the chain or across chains.

=== NFT transfer

The name of the transaction that transfers non-fungible tokens within one chain.

=== Node

//A blockchain application built with the Lisk SDK, e.g. Lisk Core, which is connected to other nodes.
A server having Lisk Core installed and therefore being part of a Lisk network, e.g. Lisk’s mainnet.
Together, they form a blockchain network.
Nodes fulfill many important roles in the network, like synchronising new events in the network between each other, adding new blocks to the blockchain, and providing APIs for external services in order to communicate with the network.

=== Nonce

A nonce is an abbreviation for "number only used once" and is a random number that can only be used one time.
In the Lisk network it can be defined as an integer that represents for the number of outgoing transactions of an account.
For a transaction to be valid, transaction nonce has to be equal to the nonce stored in the sender account.
If due to network congestion, a transaction was not included in a block because its fee was too low, a user can broadcast a new transaction using the same nonce value but with a higher fee.
Once one of the two transactions is included in the blockchain, the other one becomes invalid as the nonce has already been used.

== O

=== Outbox

The outbox is a data structures that contain information relevant to verify and process a certificate.

== P

=== Package

NPM distribution of a library.

=== Parameters (Params)

A parameter can be defined as a property of a transaction which is passed as an input to the command that is being triggered by the transaction.
Essentially these are input parameters for the aforementioned command.

=== Passphrase

A set of 12 words used to access the Lisk address.

=== PBKDF2 - Password Based Key Derivation Function 2

PBKDF2 can be defined as key derivation functions with a sliding computational cost, in order to reduce vulnerabilities to brute force attacks.

=== Peer

A node interacting with other nodes on a Lisk network, e.g. Lisk’s mainnet.

=== PoS - Proof of stake

Proof of Stake is a type of consensus mechanism used to achieve agreement over a distributed network.
With PoS the consensus is determined based upon the stake of each user in the network. +
With PoS users are required to stake their tokens in order to become a validator in the network.
Validators are responsible for ordering transactions and creating new blocks so that all nodes can agree on the current state of the network.

=== PoA - Proof of Authority

Proof-of-authority (PoA) is a consensus mechanism that is dependent on a reputable and trustworthy pre-defined authority to produce blocks.
By using a <<BFT - Byzantine fault tolerance>> algorithm with identity as a stake, PoA is an efficient mechanism as it enables relatively faster transaction completion.

=== PoA module

The SDK module that implements a PoA chain.

=== Proof of misbehavior - PoM

This transaction contains the information necessary to prove that a delegate has breached the BFT protocol.
A block cannot contain two PoMs with the same forging delegate.
In practice, this means that a delegate cannot be punished twice in one block.
Finally, a reward is added to the account sending the PoM.

=== PoW - Proof of work

Proof of Work is a type of consensus mechanism used to achieve agreement over a distributed network.
With PoW in order to complete the transactions on a given network, the miners have to solve complex mathematical problems in order to be rewarded with the tokens.
In a nutshell, the PoW consensus algorithm is used to confirm transactions and produce new blocks to the chain. The miners have to compete against each other to complete transactions on the network to receive their rewards.
Hence, the PoW mechanism allows consensus to be reached whilst simultaneously maintaining network security.

=== P2P - Peer to peer

A peer-to-peer network is a group of nodes (devices), that make up a decentralized network that can collectively share and store data, whereby each node acts as an individual peer.

== Q

== R

=== Random module

The Random module handles the validation of the inputs and computation of outputs for the commit and reveal process for a Lisk blockchain, and in addition, defines a random substore whose value contains the validator reveals array.
More detailed information can be found in {url_github_lip_46}[LIP 0046].

=== Receiving chain ID

The property in a cross-chain message determining to which chain the message is sent to.

=== Recover message

A mainchain command to recover a pending message from the inbox in a terminated sidechain.

=== Reclaim LSK transaction

This transaction is only part of Lisk Core and not the Lisk SDK.
A xref:{url_reclaim_lsk}[reclaim LSK transaction] type on the Mainnet converts a previously non-initialized legacy account’s address to the new address system.
Initialization was originally only required for the v2 chain as legacy addresses, generated from the first eight bytes of the public key, were used in older versions of the protocol.
However, this is required because the public key is required to convert from the old address system to the new address system.
Non-initialized accounts don’t have a public key associated with them yet.

=== Reducer

A reducer is a function that derives a new state from an input, and can change the state.

// Reducers are functions which can be invoked via Remote-Procedure-Calls (RPC) by other modules.
// Reducers are able to perform state changes on the blockchain.
// Modules and module assets can invoke reducers through the `reducerHandler`.
// See xref:{url_reducer}[Modules > Reducers] for more information.

=== Relayer

Relayers in simple terms can be defined as the actors that submit cross-chain update transactions (CCUs), between sidechains when necessary.
They are completely symmetric with regard to all information being relayed from a sidechain to the mainchain.

=== Reward module

The reward module provides the base reward system for the validators and the voters of the Lisk ecosystem.
The reward can be reduced which depends on the rules of the <<Random module>> and the <<BFT module>>.

== S

=== Second passphrase

An additional passphrase used as a voluntary, second level of security.

=== Self vote

A self vote is a vote that a delegate casts for themselves. Self votes are always at least 10% of the delegate weight.

=== Sending chain ID

The property in a cross-chain message identifying from which chain the message was sent.

=== Sidechain

A sidechain consists of a separate blockchain network that is connected to the mainchain network via a two-way peg.

=== Standby delegate

A standby delegate is classed as a delegate that is not able to forge new blocks for the Lisk blockchain, as each delegate is not an <<active-delegate>>.
Rank 102-∞.

=== State Store

The xref:{url_state_store}[state store] is used to mutate the state of the blockchain data, or to retrieve data from the blockchain, and can also be thought of as a temporary data structure that holds a temporary state while processing a block.

=== State recovery initialization command

A command to create the necessary state structures so that state recovery can happen.

=== State recovery command

A command to recover a specific part of the state in a terminated sidechain.

== T

=== Token

A token refers to LSK or any sidechain token.
A  digital token is designated to a cryptocurrency that is built on top of an existing blockchain, and represents a particular tradable and fungible asset.

=== Token module

Name of the fungible token standard module.
// The token module is used for minting, burning, and transferring tokens.
// It allows any chain in the ecosystem to handle and transfer tokens in a coherent, secure, and controlled manner.
// Furthermore, the token module is composed of a state store definition that is used to store tokens in the state.

=== Transaction

An interaction with the Lisk blockchain which permanently writes data to it.
A transaction can have multiple purposes, e.g. a balance transfer or delegate registration.
// Each transaction contains a module ID and an asset ID, defining the transaction type.
// All properties of a transaction object are described on the xref:{url_transaction_properties}[Transactions] page.
// The input data for the different <<module-asset, module assets>> is stored inside the <<transaction-asset>> of a transaction.

//=== Transaction asset  -Now renamed to 'Params'

// The asset of a transaction contains the custom data which serves as input parameters for the corresponding <<module-asset>>.
// The transaction asset is part of every <<transaction>> object.

=== Token ID

A unique identifier in the Lisk ecosystem for a token type (e.g., LSK) created by the token module.

=== Token transfer

A transaction type on all networks based on the Lisk protocol which transfers fungible tokens (e.g. LSK), within one chain.

=== Token transfer transaction

A transaction type which transfers tokens from one account to another one.
A xref:{url_token_transfer}[Token transfer] transaction will transfer the amount of tokens specified in the amount property, from the sender of the transaction to the specified recipient.

=== Token unlock

A transaction type on all networks based on the Lisk protocol which unlocks the token used for votes.

=== Total votes received

The total votes received is the sum of all vote amounts (including self-votes), for that specific delegate.
The self-votes are always at least 10% of the delegate weight, in order to ensure each delegate is able to maintain an adequate amount of votes.
The votes are aggregated and used to compute the delegate weight, which in turn is used to assign blocks to delegates. However, it should be noted that as the delegate vote will be capped by the self-vote, the total votes might not be equal to the delegate weight.

=== Transaction fee

An amount of LSK needed to send a transaction on the Lisk blockchain.

=== Transaction ID

A hash of a transaction that uniquely identifies a transaction.

=== Transaction message

A custom message you can attach to a balance transfer.

== U

=== Unlock token transaction

The xref:{url_token_unlock}[unlock token] transaction unlocks the tokens which have been locked previously by voting for a specific delegate.
The delegate needs to be unvoted before unlocking the tokens by sending a <<vote-delegate-transaction>>.

=== UTXO - Unspent transaction output

UTXO is an unspent output.
In other words, it can be thought of as an indivisible chunk of a token, which is under the control of the private keys belonging to the owners.

== V

=== Validator

Participants which are in charge of generating and finalizing blocks in a sidechain.
Validators in Lisk <<DPoS - Delegated proof of stake>> and Lisk <<PoA - Proof of authority>> chains share many common properties, for example, such as the BLS and generator keys.
Therefore, these properties and their associated logic are now handled in a single module, namely the <<Validators module>> described below.
//An account eligible to add a new block to the chain.

=== Validators module

The Validators module is responsible for validating the eligibility of a validator for generating a block and the block signature.
// In addition, information about the registered validators in its module store is maintained, together with providing the generator list.
In particular, it verifies that a validator is eligible for generating a block in a certain block slot and the validity of the block signature.
Furthermore, the Validators module store maintains an account for each validator that is registered in the chain.

=== Vote delegate transaction

Accounts can vote for delegates by sending a vote delegate transaction.
The tokens used to vote for delegates will be locked, although the locked tokens can be unlocked again if required, by unvoting the delegate again.
The weight of a delegate will determine the sum of all votes for this delegate.

=== Voter

A user deploying their LSK to vote for their favourite delegates.

== W

=== Wallet

Wallets can be broken down into three distinct categories: Software, Hardware, and Paper wallets.
Software wallets can be defined as either desktop, mobile or online.
In short, a wallet will store the public and private keys and can interface with various blockchains, enabling the users to monitor their balance, send tokens and conduct other operations.
A Lisk wallet is available on both Lisk Desktop and Lisk Mobile.
They are actively maintained and provide the most secure and easiest way to access the users' LSK tokens.

== X

== Y

== Z
