= Glossary
Chris Braithwaite <christopher.braithwaite@lightcurve.io>
:description: SDK glossary of terms from A to Z.
:toc:
:imagesdir: ../../assets/images
:page-no-next: true
:docs_sdk: lisk-sdk::
:idprefix:
:idseparator: -

:url_aes: https://proprivacy.com/guides/aes-encryption
:url_bch_codes: https://en.wikipedia.org/wiki/BCH_code#:~:text=In%20coding%20theory%2C%20the%20BCH,(also%20called%20Galois%20field).&text=This%20simplifies%20the%20design%20of,small%20low%2Dpower%20electronic%20hardware
:url_rocksdb: https://rocksdb.org/
:url_semver: https://semver.org/
:url_fork: https://lisk.com/blog/research/lisk-mainnet-regenesis

:url_delegate_misbehavior: understand-blockchain/lisk-protocol/transactions.adoc#pom
:url_discover_misbehavior: {docs_sdk}modules/dpos-module.adoc#discover
:url_protocol_transactions_pom: understand-blockchain/lisk-protocol/transactions.adoc#pom
// :url_transaction_properties: understand-blockchain/lisk-protocol/transactions.adoc#transaction-properties
:url_dpos: {docs_sdk}modules/dpos-module.adoc#dpos
:url_delegate_registration: run-blockchain/forging.adoc#registering-a-delegate
:url_delegate_registration_tx: run-blockchain/forging.adoc#create-the-delegate-registration-transaction

:url_genesis_block: understand-blockchain/lisk-protocol/blocks.adoc#genesis-block
:url_tx_properties: understand-blockchain/lisk-protocol/transactions.adoc#transaction-properties
:url_multisignature: understand-blockchain/lisk-protocol/transactions.adoc#multisignature
:url_token_transfer: understand-blockchain/lisk-protocol/transactions.adoc#transfer
:url_token_unlock: understand-blockchain/lisk-protocol/transactions.adoc#unlock

//:url_data_structure: understand-blockchain/codec-schema.adoc#data-types
:url_blockchain_app: build-blockchain/index.adoc
:url_reducer: understand-blockchain/sdk/reducers.adoc
:url_base_endpoint: understand-blockchain/sdk/modules-commands.adoc#the-baseendpoint-class
:url_sdk_docs: {docs_sdk}index.adoc

:url_github_lip_46: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0046.md



// TODO: Update the page by uncommenting the hyperlinks once the updated pages are available. 

== A

=== Account

An account is an address with a number of tokens referred to as the balance.
//  Furthermore, accounts are serialized and deserialized according to the account schema.
// An account consists of a unique identifier / <<account-address,address>>, an amount of tokens referred to as balance and possibly some additional properties used in other parts of the blockchain application.

=== Account address

The address is a unique identifier that has state information associated with it for accounts in the sidechain.
They are the 20-byte hash value of the public key that controls the account initially.
In all front-end products, addresses are displayed in a human-readable representation called <<Lisk32 format>>.
An example of an address in the Lisk32 format is `lskxwnb4ubt93gz49w3of855yy9uzntddyndahm6s`.
When referring to addresses in Lisk, we always assume the Lisk32 format, without explicitly having to mention it.
In the Lisk protocol and SDK, only the 20-byte value is stored for efficiency and sometimes the hexadecimal representation of the address is used.
//TODO: Add link back, once the codec-schema page is updated
//Further details regarding other address formats can be seen here in the xref:{url_data_structure}[table for different data types] on the schema reference page.

=== Active validator

An active validator is an account registered as a validator. It can generate new blocks in the next block generation round for the Lisk mainchain, or for a sidechain with PoS as a validator selection algorithm.
A registered validator turns from inactive to active, if they accumulated more <<validator-weight>> than one of the currently active validators.
A total of 101 active validators exist on the Lisk Mainchain for this purpose, and each validator is ranked from 1-101.
Additionally, two random validators are selected for each round of block generation, resulting in 103 active validators per round on the Lisk Mainnet.

// An active delegate can mostly be considered as a forging delegate, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.

// === Address initialization (Removed as agreed with Research)

// The process of sending the first transaction on the Lisk blockchain.
// With that the public key is permanently stored as part of the users address in the Lisk blockchain and checked every time a transaction is sent.
// Hence, the users account is secure, even in the very rare case of an address collision.

=== AES-256-CBC - Advanced encryption standard

The Advanced Encryption Standard (AES), has a key length of 256 bits and is a block cipher adopted as an encryption standard by the U.S. government for military and government use. CBC (Cipher Blocker Chaining), is an advanced form of block cipher encryption.
For detailed description of how AES functions, see {url_aes}[How does AES encryption work^].

=== Alphanet

A temporary, internal-only testing network of a Lisk Core alpha candidate.

=== API

The API is defined as the interface for module-to-module communication.

//An API is an application programming interface, and is classed as software intermediary that allows applications to communicate with each other.

=== Application hooks

Application hooks are defined as module methods that are only called during block generation.
These hooks can introduce state changes but are unable to mutate the block.

=== Authorities

A special term for validators in a PoA sidechain.

=== Auth module

The Auth module is responsible for handling and verifying nonces and for transaction signature validation which includes transactions from multisignature accounts.
Furthermore, an updated multisignature registration process is now used, based on the new registration parameters.
Finally, a new storage interface for the Auth module is available, which in turn will become part of the state tree and will be authenticated by the state root.

=== Authority update command

A transaction used to update the active validators in PoA chains.

== B

=== BCH Codes - Bose, Chaudhuri, and Hocquenghem codes

BCH codes are error-correcting codes. The Bose, Chaudhuri, and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
large class of powerful random error-correcting cyclic codes.

=== Beddow

A Beddow is the smallest unit of a LSK token. 100 million Beddows is equal to 1 <<LSK>>.

=== Betanet

A temporary, external public testing network for the Lisk Core beta candidate.

=== BFT - Byzantine fault tolerance

In a system whereby components need to agree to reach a consensus,  byzantine failures will prevent those components from reaching an agreement, (usually caused by errors that are hard to detect).
A Byzantine Fault Tolerant system ensures that measures are taken to manage such failures.

=== BFT module

The BFT module is responsible for maintaining the consensus participants, their BFT weights, and all information related to the consensus stakes that have been cast as part of the block headers.

=== BFT weight

The weight of validators that are considered in Lisk-BFT for finalizing blocks and for creating valid certificate signatures.

=== BIP - Bitcoin improvement proposal

A Bitcoin Improvement Proposal (BIP), can be defined as a standard for proposing changes to the Bitcoin protocol.
For example, BIP39 is one of many bitcoin improvement proposals.
This particular proposal describes the mnemonic code or mnemonic sentence implementation,
and how to create a human-readable mnemonic sentence including how to convert that mnemonic into a seed.

=== Block assets
The block assets contain data created by individual modules.
This consists of an array of bytes, whereby each value corresponds to an object serialized according to the `assetSchema` property.
The block assets, together with the transactions, form the block payload.

=== Blockchain application
Refers to software that has a blockchain client, a middleware, and a UI.

=== Blockchain client
Refers to software that runs a blockchain node (ex: Ethereum client, bitcoin client, light client, etc).

=== Blockchain generation hooks

Block generation hooks can add information to the block assets, but cannot introduce any state changes.
These are module methods that are called during the actual block generation.

=== Blockchain node
Refers to an instance of a blockchain client that is connected to other nodes in a decentralized network.

=== Block header

A block is composed of a block header and a payload of transactions.
The block header contains all information related to the block as well as a hash of the payload.

=== Block height

The number of blocks in the blockchain between the genesis block and the block of the specified block height.

=== Block ID

A hash of a block header that uniquely identifies a block in a Lisk blockchain.

== C

=== Chain ID

A unique identifier of a chain account.
It is used when sending tokens to a specific chain and is also prepended for signing to protect against replay attacks.

=== Chain of trust

The property that is always a 2/3 majority of the previous validators that sign the new validator set.

=== Chain validators substore

The chain validators substore holds information about the validators of other partner chains.

// === Consenter (Removed as agreed with Research)

// Within the mainchain only active delegates are classed as consenters, hence this does not apply to standby delegates.


=== Command

A command is defined as a group of state-transition logics that are triggered by a specific transaction.
This can be identified by the module and command name of the transaction.
The actual command name is unique within the relevant module that it is associated with.

=== Cross-chain

Cross-chain refers to the interoperability between two or more different independent sidechains.

=== Cross-chain certification

The general technique of how the mainchain and sidechains communicate.
Furthermore, the information received from another sidechain is accepted, if the correctness of this information is attested by a certificate.

=== Cross-chain command

Cross-chain messages (CCMs), are responsible for triggering the logic defined by the cross-chain command, which is identified by both the module name and the cross-chain command name.

=== Cross-chain message

A data object used to exchange information between different chains.
It is added to the outbox of the sending chain, later to the respective certificates, and eventually to the inbox of the receiving chain.

=== Cross-chain NFT transfer

The name of the transaction that transfers non-fungible tokens from one chain to another (sidechain to sidechain).

=== Cross-chain transfer transaction

The name of the transaction that transfers fungible tokens from one chain to another (e.g., mainchain to sidechain).
Transactions that add cross-chain messages to the outbox as part of the transaction processing.

=== Cross-chain update command

A command for submitting updates about the state of the chain and new cross-chain messages.

== D

=== Devnet

A sidechain network for development purposes.
The Lisk SDK provides a dedicated genesis block and configurations to conveniently set up a local Devnet during the development of a sidechain.

== E

=== Ed25519 - High speed high security signature

Ed25519 is a public-key signature system with several attractive features: Fast single-signature verification.
Ed25519 signatures are elliptic-curve signatures, carefully engineered at several levels of design and implementation to achieve very high speeds without compromising security.

=== Endpoint

In general, an endpoint is one end of a communication channel.
In Lisk, an endpoint is defined as an interface between a module and an external system via an RPC endpoint.
The actual endpoints are individually defined for each module, as this will depend on the requirements of the actual module.

=== Events

Events emit on-chain data during the processing of a block which adds additional information regarding the execution of state transitions.

== F

=== Faucet

A Faucet is generally defined in the blockchain world as a tool whereby users can receive a certain amount of tokens for free.
The faucet plugin can be registered with the sidechain client to provide a basic faucet, which is useful during the development phase, and also for proof-of-concept sidechains.

// === Forging  - Forger is now Generator

// How delegates produce new blocks on the Lisk blockchain.

=== Fee module

The fee module is responsible for handling the transaction fees.
It allows chains to choose the token used to pay the fee and to define a minimum fee for transactions to be valid.


=== Fork

A fork can be defined as an occurrence of a blockchain diverging into two forward paths in the network.
In other words, it is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.
For further detailed information regarding forking in the Lisk network, see the following {url_fork}[Lisk Mainnet hard fork process^] description on the Lisk Mainnet Regenesis page.

=== Framework plugin

A self-contained, off-chain component that extends the standard feature set of the Lisk SDK by a specific use case, e.g. a node monitor plugin, etc.
Typically there is no state change on the sidechain.

== G

=== Genesis block

The xref:{url_genesis_block}[genesis block] describes the very first block in the blockchain.
It defines the initial state of the blockchain at the start of the network.
A genesis block must be given to the application, and all networks should have a different genesis block.

== H

=== Hash onion

The hash onion stores the random seeds of the validator and is required for each block generation round, this can be generated by the Lisk Commander.

== I

=== Inbox

The inbox is a data structure that contains information relevant to the verification and processing of a certificate.

=== Interoperability

Interoperability can simply be defined as the ability of different sidechain networks being able to freely communicate, and transfer data and digital assets between each other.

=== Interoperability module

The interoperability module provides functionalities that will allow the transmission of information between interoperable chains in the Lisk ecosystem using cross-chain messages.
To validate and process the relevant commands, the interoperability module stores the required necessary properties.

== J

== K

=== Key derivation path

Key derivation allows multiple key pairs to be derived from the same secret recovery phrase.
The key derivation path allows an HD (Hierarchical Deterministic), wallet to derive a specific key from within a tree of keys.
The key derivation path in Lisk follows the industry standard, therefore ensuring forward compatibility with any future third-party products.

== L

=== Legacy module

The Legacy module is responsible for maintaining all accounts on the Lisk mainchain that received balance transfers to their address in the old 8-byte format, and for which no public key is associated.
Furthermore, it also implements a command allowing validators without a BLS key to register one.

=== LIP - Lisk improvement proposal

A LIP is a document usually structured by the research team defining technical changes in the Lisk protocol.
In addition, it can also cover an implementation or a non-technical process surrounding Lisk.
Furthermore, a LIP also describes the requirements, rationale, and motivation for the required changes.

=== Lisk32 format

The Lisk32 format of an <<Account address>> starts with the letters "lsk" followed by a custom Base32 encoding of the 20 bytes of the address appended with a BCH checksum.
The checksum is used to check for small errors in the address.
Any errors in up to 4 characters are guaranteed to be detected and errors in more than 5 characters are likely to be detected.
The choice of the Lisk32 format of addresses does not modify the address but is introduced to provide a safer and more pleasant experience to users.

=== Lisk ecosystem

The Lisk ecosystem represents the third-party environment of Lisk, e.g. community members, exchanges, and sidechains.

=== Lisk framework

Lisk Framework is an application framework responsible for establishing and maintaining the interactions between the modules of a sidechain compatible with the Lisk protocol. It provides an application where off-chain and on-chain logic can be extended with user-defined plugins and modules.

=== Lisk Mainnet

The Mainnet is a fully developed, functional, and independent blockchain, running on its own network and using its own protocol and technology.
It is the official main network within Lisk.

=== Lisk SDK

The xref:{url_sdk_docs}[Lisk SDK] is an open-source software development kit that enables developers to easily build scalable sidechains using JavaScript & Typescript.

=== Lisk Testnet

The official testing network of Lisk.
It can be thought of as an instance of a blockchain that is used for testing purposes and consists of the same version of the mainnet underlying software.
All testing and experimentation can be performed on the testnet without jeopardizing the actual mainnet.

=== LSK

The token used in the Lisk Mainnet.

=== LSK reclaim

A transaction type on Mainnet which converts a previously non-initialized account’s address to the new address system.
This is required because the public key is required to convert from the old address system to the new address system. Non-initialized accounts don’t have a public key associated with them yet.

== M

=== Mainchain

The mainchain can be defined as a series of blocks created from the initial genesis block to the latest block.
All transactions or processes that occur on the mainchain are not confirmed until they are finalized on the mainchain.


// === Module Asset (Now changed to Command)

// A module asset allows a module to execute specific state changes on the blockchain based on transactions. A <<transaction>> with the corresponding module & asset ID needs to be sent to the <<blockchain-application>> in order to trigger the logic defined in a certain module asset. The data provided in the <<transaction-asset>> provides the required input data to execute the desired state changes.

=== Message fee

It is a property of a cross-chain message that represents the number of LSK tokens that are credited to the relayer in the receiving chain.

=== Message recovery command

A mainchain command to recover a pending message in the inbox of a terminated sidechain.

=== Message recovery initialization command

A command to create the necessary state structures so that message recovery can happen.

=== Method

A method is an interface for module-to-module communication.

=== Minimum fee

All transactions must have a fee greater or equal to a minimum fee (which can be zero).
The minimum fee is computed from the transaction size.
The minimum fee should be burned to make sure that validators can't send transactions in the blocks they generate without a cost.

=== Module

A module enables a sidechain to have client-specific on-chain logic.
Modules can perform state changes on the related sidechain.
For example, the Lisk SDK modules can define state machine and block generation hooks.
They can also define commands to add the related logic to the state machine.

=== Module endpoint

Module endpoints enable external services to retrieve data from a sidechain.
// Each module endpoint always extends from the xref:{url_base_endpoint}[BaseEndpoint] class.

=== Module methods

Module methods are hooks, such as application hooks and block generation hooks.
These methods are called during actions such as during block execution and block generation.


== N

=== NFT - Non-fungible token

NFTs are digital assets in the form of unique cryptographic tokens. Examples can represent real-world objects such as art, music, games, and videos, which due to their uniqueness can result in them becoming collectible items of value.

=== NFT ID

A unique identifier in the Lisk ecosystem for a specific NFT created by the NFT module.

=== NFT module

Name of the non-fungible token standard module.
// The NFT (non-fungible token), module is responsible for creating, destroying, and transferring NFTs within the Lisk ecosystem.
// Furthermore, the NFT module ensures the NFT unique identifiers are never modified.
// Finally, the NFT module provides the functionality of locking/unlocking the NFTs which restrict the user transferring NFTs within the chain or across chains.

=== NFT transfer

The name of the transaction that transfers non-fungible tokens within one chain.

=== Node

//A blockchain application built with the Lisk SDK, e.g. Lisk Core, which is connected to other nodes.
A server having Lisk Core installed and therefore being part of a Lisk network, e.g. Lisk’s mainnet.
Together, they form a blockchain network.
Nodes fulfill many important roles in the network, like synchronizing new events in the network with each other, adding new blocks to the blockchain, and providing APIs for external services to communicate with the network.

=== Nonce

A nonce is an abbreviation for "number only used once" and is a random number that can only be used one time.
In the Lisk protocol, it can be defined as an integer that represents the number of outgoing transactions of an account.
For a transaction to be valid, the transaction nonce has to be equal to the nonce stored in the sender account.
If due to network congestion, a transaction was not included in a block because its fee was too low, a user can broadcast a new transaction using the same nonce value but with a higher fee.
Once one of the two transactions is included in the blockchain, the other one becomes invalid as the nonce has already been used.

== O

=== Outbox

The outbox is a data structure that contains information relevant to the verification and processing of a certificate.

== P

=== P2P - Peer to peer

A peer-to-peer network is a group of nodes (devices), that make up a decentralized network that can collectively share and store data, whereby each node acts as an individual peer.

=== Package

NPM distribution of a library.

=== Parameters (Params)

A parameter can be defined as a property of a transaction that is passed as an input to the command that is being triggered by the transaction.
Essentially these are input parameters for the aforementioned command.

=== Passphrase

A set of 12 words used to access the Lisk address.

=== PBKDF2 - Password-Based Key Derivation Function 2

PBKDF2 can be defined as key derivation functions with a sliding computational cost, to reduce vulnerabilities to brute force attacks.

=== Peer

A node interacting with other nodes on a Lisk network, e.g. Lisk’s mainnet.

=== PoA - Proof of Authority

Proof-of-authority (PoA) is a consensus mechanism that is dependent on a reputable and trustworthy pre-defined authority to produce blocks.
By using a <<BFT - Byzantine fault tolerance>> algorithm with identity as a stake, PoA is an efficient mechanism as it enables relatively faster transaction completion.

=== PoA module

The SDK module that implements a PoA chain.

=== PoS - Proof of stake

The proof of stake mechanism uses an algorithm designed to select users that have the highest stakes as validators. 
The highest stakeholders are expected to have a high motivation to keep the network secure and healthy, as users with the highest amount of tokens or coins have the most to lose if something goes wrong in the network.
The consensus algorithm used by the Lisk mainchain and sidechain is a hybrid version of DPoS and PoS algorithms.

=== PoS module

The PoS module is responsible for handling all aspects of the validator selection, this includes the registration of accounts as validators, the staking process, and potential misbehavior reports.

=== PoW - Proof of work

Proof of Work is a type of consensus mechanism used to achieve agreement over a distributed network.
In PoW, to complete the transactions on a given network, the miners have to solve complex mathematical problems to be rewarded with the tokens.
In a nutshell, the PoW consensus algorithm is used to confirm transactions and produce new blocks to the chain. The miners have to compete against each other to complete transactions on the network to receive their rewards.
Hence, the PoW mechanism allows consensus to be reached whilst simultaneously maintaining network security.

== Q

== R

=== Random module

The Random module handles the validation of the inputs and computation of outputs for the commit and reveal process for a Lisk blockchain, and in addition, defines a random substore whose value contains the validator reveals array.
More detailed information can be found in {url_github_lip_46}[LIP 0046].

=== Receiving chain ID

The property in a cross-chain message determining to which chain the message is sent to.

=== Reclaim LSK transaction

This transaction is only part of Lisk Core and not the Lisk SDK.
A "Reclaim LSK transaction" on the Mainnet converts a previously non-initialized legacy account’s address to the new address system.
Initialization was originally only required for the v2 chain, as legacy addresses generated from the first eight bytes of the public key were used in older versions of the protocol.
However, this is required because the public key is required to convert from the old address system to the new address system.
Non-initialized accounts don’t have a public key associated with them yet.

=== Recover message

A mainchain command to recover a pending message from the inbox in a terminated sidechain.

=== Reducer

A reducer is a function that derives a new state from an input and can change the state.

// Reducers are functions which can be invoked via Remote-Procedure-Calls (RPC) by other modules.
// Reducers are able to perform state changes on the blockchain.
// Modules and module assets can invoke reducers through the `reducerHandler`.
// See xref:{url_reducer}[Modules > Reducers] for more information.

=== RegisterValidator transaction

To be able to participate in the block generation process, an account needs to register as a validator in the network.
//TODO: Add link to related guide how to register a validator, once it is updated.
//TODO: Add link to the PoS module reference
The registration process is performed by posting a RegisterValidator transaction to the network.

=== RegisterMultisignature transaction

A transaction type on all networks based on the Lisk protocol which registers a xref:{url_multisignature}[multisignature group].
This transaction registers the sender account as a multisignature group account.

=== Relayer

Relayers in simple terms can be defined as the actors that submit cross-chain update transactions (CCUs), between sidechains when necessary.
They are completely symmetric with regard to all information being relayed from a sidechain to the mainchain.

=== ReportMisbehavior transaction

This transaction contains the information necessary to prove that a validator has breached the BFT protocol.
A block cannot contain two misbehavior alerts for the same block-generating validator.
In practice, this means that a validator cannot be punished twice in one block.
//TODO: Add link to PoS module reference
Finally, a reward is added to the account sending the reportMisbehavior transaction.

=== Reward module

The reward module provides the base reward system for the validators and the stakers of the Lisk ecosystem.
The reward can be reduced which depends on the rules of the <<Random module>> and the <<BFT module>>.


== S

=== sApp
Abbreviation of sidechain application.

=== Second passphrase

An additional passphrase used as a voluntary, second level of security.

=== Self stake

//TODO: Add footnote here linking to Lisk PoS explanation page
If a validator uses their tokens to increase their <<validator-weight>>, this is called a self-stake.
The percentage of the self-stake needs to be at least 10% of the total validator weight of a particular validator, to be eligible to generate new blocks in the network.

=== Sending chain ID

The property in a cross-chain message identifying from which chain the message was sent.

=== Sidechain

A sidechain is a blockchain that follows the Lisk protocol and is registered on the Lisk mainchain.

=== Sidechain application
Refers to software that contains a lisk based <<sidechain-client>>, a middleware, and a UI.

=== Sidechain client

A xref:{url_blockchain_app}[sidechain client] refers to software that runs a sidechain node, and that follows the Lisk protocol. For example, this can be an application running on its own sidechain built with the Lisk SDK.

=== Stake transaction
Accounts can stake for validators by sending a stake validator transaction.
The tokens used to stake for validators will be locked, although the locked tokens can be unlocked again if required, by unstaking the validator again.
The weight of a validator will determine the sum of all stakes for this validator.

=== Stakers

A user deploying their LSK to <<un-staking, stake>> for their favorite validators.

=== Staking
Staking is the process of using one's tokens to vote for one or multiple validators.
Staking for a delegate will increase the <<validator-weight>> of the validator.
Staked tokens are locked in the account that performed the stake until they are un-staked.
Staking of tokens can be performed by posting a <<stake-transaction>> to the network.

=== Standby validator

A standby validator, or inactive validator, is classed as a validator that does not have sufficient validator weight and therefore is not eligible to generate new blocks. A standby validator can become an <<active-validator>> if their <<validator-weight>> increases.

=== State recovery initialization command

A command to create the necessary state structures so that state recovery can happen.

=== State recovery command

A command to recover a specific part of the state in a terminated sidechain.

=== State Store

The state store is used to mutate the state of the blockchain data, or to retrieve data from the blockchain, and can also be thought of as a temporary data structure that holds a temporary state while processing a block.

== T

=== Token

A token refers to LSK or any sidechain token.
A  digital token is designated to a cryptocurrency that is built on top of an existing sidechain and represents a particular tradable and fungible asset.

=== Token ID

A unique identifier in the Lisk ecosystem for a token type (e.g., LSK) created by the token module.

=== Token module

Name of the fungible token standard module.
// The token module is used for minting, burning, and transferring tokens.
// It allows any chain in the ecosystem to handle and transfer tokens in a coherent, secure, and controlled manner.
// Furthermore, the token module is composed of a state store definition that is used to store tokens in the state.

=== Token transfer

A transaction type on all networks based on the Lisk protocol which transfers fungible tokens (e.g. LSK), within one chain.

=== Token transfer transaction

A transaction type that transfers tokens from one account to another one.
A xref:{url_token_transfer}[Token transfer] transaction will transfer the number of tokens specified in the amount property, from the sender of the transaction to the specified recipient.

=== Token unlock

A transaction type on all networks based on the Lisk protocol which unlocks the token used for staking.

=== Transaction

An interaction with the Lisk blockchain which permanently writes data to it.
A transaction can have multiple purposes, e.g. a balance transfer or validator registration.
// Each transaction contains a module ID and an asset ID, defining the transaction type.
// All properties of a transaction object are described on the xref:{url_transaction_properties}[Transactions] page.
// The input data for the different <<module-asset, module assets>> is stored inside the <<transaction-asset>> of a transaction.

//=== Transaction asset  -Now renamed to 'Params'

// The asset of a transaction contains the custom data which serves as input parameters for the corresponding <<module-asset>>.
// The transaction asset is part of every <<transaction>> object.

=== Transaction fee

A number of LSK tokens needed to send a transaction on the Lisk blockchain.

=== Transaction ID

A hash of a transaction that uniquely identifies a transaction.

=== Transaction message

A custom message you can attach to a balance transfer.

== U

=== Unlock token transaction

The xref:{url_token_unlock}[unlock token] transaction unlocks the tokens which have been locked previously by staking for a specific validator.
The validator needs to be unstaked before unlocking the tokens by sending a <<stake-transaction>>.

=== Unstaking
Unstaking is the process of removing tokens from one or multiple validators.
After the tokens are unstaked, they can be unlocked by posting an <<unlock-token-transaction>>. 
Unstaking of tokens can be performed by posting a <<stake-transaction>> to the network.

=== UTXO - Unspent transaction output

UTXO is an unspent output.
In other words, it can be thought of as an indivisible chunk of a token, which is under the control of the private keys belonging to the owners.

== V

=== Validator

Participants which are in charge of generating and finalizing blocks in a sidechain.
Validators in Lisk <<pos-proof-of-stake>> and Lisk <<poa-proof-of-authority>> chains share many common properties, for example, such as the BLS and generator keys.
Therefore, these properties and their associated logic are now handled in a single module, namely the <<Validators module>> described below.
//An account eligible to add a new block to the chain.

=== Validators module

The Validators module is responsible for validating the eligibility of a validator for generating a block and the block signature.
// In addition, information about the registered validators in its module store is maintained, together with providing the generator list.
In particular, it verifies that a validator is eligible for generating a block in a certain block slot and the validity of the block signature.
Furthermore, the Validators module store maintains an account for each validator that is registered in the chain.

=== Validator weight

The weight of validators in PoS determines whether a validator is active, on standby, or not eligible to generate blocks.
//TODO: Add link to Lisk PoS explanation
It is computed from the <<self-stake, self stakes>> and the total amount of received <<un-staking, stakes>>.
// The delegate weight is an indicator which shows the active support received by a delegate that is present in the network. To maintain a secure and effective setup, the delegate weight is bound to 10 times the self-votes.
// The weight of a delegate is the sum of all votes for a particular delegate that includes self-votes.

== W

=== Wallet

Wallets can be broken down into three distinct categories: Software, Hardware, and Paper wallets.
Software wallets can be defined as either desktop, mobile or online.
In short, a wallet will store the public and private keys and can interface with various blockchains, enabling the users to monitor their balance, send tokens and conduct other operations.
A Lisk wallet is available on both Lisk Desktop and Lisk Mobile.
They are actively maintained and provide the most secure and easiest way to access the users' LSK tokens.

== X

== Y

== Z
