= Inline Text Styles
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

////
When creating a UI theme for Antora, there are certain elements in the UI that require support from the CSS to work correctly.
This list includes elements in the shell (i.e., frame) and in the document content.
This document identifies these UI elements.
////

[#bold]
== Bold text

How xref:antora:asciidoc:bold.adoc[text marked up as bold] appears on your site depends on the fonts loaded by the UI and any CSS styles it applies to the `<strong>` HTML tag.

[source,html]
----
<p>A bold <strong>word</strong>, and a <strong>bold phrase</strong>.</p>
----

In the default UI, the `strong` element, specified in [.path]_css/base.css_, uses the 500 weight fonts loaded by the typeface stylesheets.

[#italics]
== Italic text

How xref:antora:asciidoc:italics.adoc[italicized text] appears on your site depends on the fonts loaded by the UI and any CSS styles it applies to the `<em>` HTML tag.

[source,html]
----
<p>An italic <em>word</em>, and an <em>italic phrase</em>.</p>
----

In the default UI, the italic fonts (`font-style: italic`) loaded by the typeface stylesheets are applied to inline text enclosed in `<em>`.
