= UI Element Style Guide
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings:
:idprefix:
:idseparator: -
:experimental:

When creating a UI theme for Antora, there are certain elements in the UI that require support from the CSS to work correctly.
This list includes elements in the shell (i.e., frame) and in the document content.
This document identifies these UI elements.

//== UI Shell

// TODO

== Document Content

The HTML in the main content area is generated from AsciiDoc using Asciidoctor.
AsciiDoc has numerous content elements that require assistance from CSS to render properly.

=== Admonitions

An admonition block is a table.
The table title element is specified by the block class: tip, note, important, warning, or caution.
Here's an AsciiDoc source example that produces an admonition with the table title warning:

[source,asciidoc]
----
WARNING: Watch out!
----

If font-based icons are enabled (`icons=font`), the table title text is replaced by the associated icon.

[source,html]
----
<div class="admonitionblock warning">
<table>
<tr>
<td class="icon">
<i class="fa icon-warning" title="Warning"></i>
</td>
<td class="content">
<div class="paragraph">
<p>Watch out!</p>
</div>
</td>
</tr>
</table>
</div>
----

Here's how it might appear when the title is displayed as text:

WARNING: Watch out!

=== Task lists

A task list is an unordered list with items that are prefixed with a checkbox marker (checked or unchecked).
Here's an AsciiDoc source example that produces a task list:

[source,asciidoc]
----
* [ ] todo
* [x] done!
----

If font-based icons are enabled (`icons=font`), the checkbox gets inserted as the first element of the paragraph element that contains the list item text.

[source,html]
----
<div class="ulist checklist">
<ul class="checklist">
<li>
<p><i class="fa fa-square-o"> todo</p>
</li>
<li>
<p><i class="fa fa-check-square-o"> done!</p>
</li>
</ul>
</div>
----

The recommended approach is to hide the list markers (`list-style: none`), then add a checkbox glyph on the icon element using either a background image or a `before` pseudo element.

Here's how it might appear:

* [ ] todo
* [*] done!

=== UI Elements

Asciidoctor supports three UI element representations out of the box, which are made from corresponding inline UI macros.

* keybinding (kbd macro)
* button (btn macro)
* menu (menu macro)

The UI elements are output using semantic HTML elements, so they inherit some default styling from the browser.
However, to look proper, they require some additional styling.

==== Keybinding

A keybinding can be a single key (`+kbd:[F11]+`) or a sequence of keys (`+kbd:[Ctrl+F]`).
Here's the HTML that's generated for these two forms.

[source,html]
----
<kbd>F11</kbd>
<span class="keyseq"><kbd>Ctrl</kbd>+<kbd>F</kbd></span>
----

Here's how these might appear:

[%hardbreaks]
kbd:[F11]
kbd:[Ctrl+F]

==== Button

A button is meant to represent an on-screen button (`+btn:[Save]+`).
However, it should not appear like an actual button as that could confuse the reader into thinking it's interactive.
Therefore, a button is rendered as a bold text by default:

[source,html]
----
<b class="button">Save</b>
----

Traditionally, a button reference is styled by surrounding the text with square brackets, as shown here:

btn:[Save]

==== Menu

A menu can be a top-level menu reference (`+menu:File[]+`) or a nested selection (`+menu:File[Save]+`).
Here's the HTML that's generated for these two forms.

[source,html]
----
<b class="menuref">File</b>
<span class="menuseq"><b class="menu">File</b>&#160;<b class="caret">&#8250;</b> <b class="menuitem">Save</b></span>
----

This might be rendered as:

[%hardbreaks]
menu:File[]
menu:File[Save]

The default styling applied to a menu reference is usually sufficient.
