= Work with the Handlebars Templates
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

Antora combines the Handlebars templates with the converted AsciiDoc content to make the pages in the site.
These "`logic-less`" templates are mostly HTML with some special mustache tags sprinkled in where content is to be inserted.

== What do the templates do?

The layout templates, which are stored in [.path]_src/layouts/_, provide the main page structure.
The partial templates, in [.path]_src/partials/_, fill in different regions of a page, such as the navigation and footer.

The templates read from a model that's populated by Antora.
Places in the template where the model is read are enclosed in `{{` and `}}` markers, aka mustaches (e.g., `+{{title}}+`).
When the `{{` is immediately followed by `>`, that's where the result of a partial is inserted (e.g., `+{{> head }}+`.

=== Template variables

*This model is not final.*
*Variable names and purposes may change.*

Here's an overview of the available model:

.Variables available to the Handlebars templates
[#template-variables,cols="1m,3"]
|===
| Name | Description

| site
| Information about the site.
Properties include url, title, buildNumber, domains, aspect, aspectNav, and swiftypeKey.

| title
| The page title (also used as the primary heading).

| contents
| The main article content in HTML format.
Sourced from AsciiDoc and converted to HTML by the Asciidoctor processor.

| description
| The text of the description attribute in the AsciiDoc header, if specified.

| keywords
| A comma-separated list of keywords defined in the AsciiDoc header, if specified.

| domain
| Information about the navigation domain of the current page.
Properties include name, title, type, versioned, version, versions, url, root, and siteAspect.

| versions
| All versions of the current page, including the current page.
Each entry has the properties url, string, and missing.

| breadcrumbs
| An array of breadcrumb items that represent the current selection in the navigation tree.

| uiRootPath
| The path to the root directory of the UI.

| canonicalUrl
| The canonical URL for the current page.
If there are older versions of the page, the canonical URL is the URL of the latest version.
If this is an aspect page, the canonical URL is the URL of the primary (non-aspect) page.

| editUrl
| The URL to edit the current page, typically on GitHub.

| siteRootUrl
| The URL of the site root relative to the current page.
If the site does not have a root component, this value is null.

| home
| Indicates whether the current page is the home page of the site.

| navigation
| A collection of navigation links for the current page.
Each navigation item contains the property `text` as well as the optional properties `href` and (child) `items`.
|===

This model is likely to grow over time.

== Modify a template

Let's consider the case when you want to add a new meta tag inside the HTML head.

First, make sure you have set up the project and created a development branch.
Next, open the file [.path]_templates/partials/head.hbs_ and add your tag.

[source,html]
----
<meta class="swiftype" name="title" data-type="string" content="{{title}}">
----

Each template file has access to the template model, which exposes information about the current page through variable names.
The variables currently available are listed in <<template-variables>>.

Save the file, commit it to git, push the branch, and allow the approval workflow to play out.
