= Calculating the fee for a transaction
:toc: preamble
// URLs
:url_typedoc_transactions: {site-url}/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_transactions.html
// Project URLs
:url_hello_world: build-blockchain/create-sidechain-app.adoc
:url_understand_tx_commandfee: understand-blockchain/blocks-txs.adoc#command-fee

====
On this page, you'll learn how to:

* [x] Define a valid fee for a transaction
* [x] Calculate the minimum fee for a specific transaction
====

== How fees are defined for transactions

Fees can be defined dynamically for every transaction.
A higher fee will create an incentive for validators to include the transaction in a block as quickly as possible, because most validators prioritize transactions with higher fees in the transaction pool, because it means a personal higher rewards for them, if they include these transactions in a block.
So by choosing a higher fee, it can be ensured that the transaction is executed as quickly as possible.

This mechanism can also be used to overwrite existing transactions in the pool, by using the same nonce, but a higher fee than the transaction that should be overwritten.

For every transaction, there is a minimum fee that needs to be paid in order for the transaction to be successfully processed.

WARNING: If the transaction is posted without fee, or with a fee smaller than the required minimum fee, the transaction will *fail*.

It is possible to calculate the minimum fee required by using the short formula listed below:

 minFee = transactionBytes.length * minFeePerByte (+ commandFee)

This means, the minimum fee is directly connected to the size of the transaction object in bytes after it has been encoded, and also to the optional xref:{url_understand_tx_commandfee}[commandFee] of a transaction.

== How to calculate the minimum fee for a transaction

The most convenient way to compute the minimum fee for a transaction is by using the API client as explained in the following sections.

Alternatively, the user can also use directly the {url_typedoc_transactions}[@liskhq/lisk-transactions^] package to compute the minimum fee, by using the function `computeMinFee`.
In this case, the user needs to provide the transaction object and the corresponding transaction schema to the function.

:sectnums:
=== Connect the API client to a node

First, create a function `getClient()`, which will return an instance of the API client.

The API client connects to a local node, having the RPC API enabled via WebSockets at port `7887`.

TIP: Alternatively, the corresponding HTTP or IPC APIs can be used, if the node has enabled those.

To connect to a different node, simply update the API URL defined in `nodeAPIURL`.

.compute-minfee.js
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');

let clientCache;
const nodeAPIURL = 'ws://localhost:7887/ws'

const getClient = async () => {
	if (!clientCache) {
		clientCache = await apiClient.createWSClient(nodeAPIURL);
	}
	return clientCache;
};
----

=== Compute minimumFee

A new transaction is created with the API client in a convenient manner, assuming that the respective transaction type is known to the node.
Generally, a node knows only the commands belonging to the modules registered to the sidechain application.

To calculate the minimum fee of a transaction, first create the respective transaction and sign it.

A value for the transaction fee is already required to create and sign the transaction.
Therefore, just use an arbitrary default value, like 0 LSK.
This value will be replaced with the calculated minimum fee for the transaction in the next step.

.compute-minfee.js
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');

// ...

const calcMinFee = async (client) => {
	const txWithSomeFee = await client.transaction.create({
		module: "token",
		command: "transfer",
		fee: BigInt("0"),
		params: {
			data: "Happy Birthday!"
		}
	});

	return client.transaction.computeMinFee(txWithSomeFee);
}

getClient().then(client => {
	calcMinFee(client).then(minFee => {
		console.log("Minimum fee for the current transaction: ", minFee);
	})
})
----

=== Execute

If the script is now executed in the terminal, it will display the minimum fee for the created transaction.

[source,bash]
----
% node compute-minfee.js
Minimum fee for the current transaction:  127000n
----

:!sectnums:
== Verifying the fee with a dry-run

To verify that the transaction will be accepted by the node, it is possible to dry-run the transaction, before actually sending it to a node.

Invoke the `txpool_dryRunTransaction` endpoint to test the validity of a transaction before acutally sending it:

[tabs]

=====
node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke txpool_dryRunTransaction '{"transaction": "0a040000000212040000000018012080c2d72f2a200fe9a3f1a21b5530f27f87a414b549e79a940bf24fdf2b2f05e7f22aeeecc86a32360a08000000000000000010011a1496c2f3cd9d9a09814d5f5d4182dc84183ea5abfb22124c6174657374205472616e73616374696f6e3a40a77b75083135aa1570e78a64c3f1d40306e3b92498a5fd227a61c40739ba0d1b6f4c7d8e274cc8caa16662906698c215eab08833a8005442862786259613ed02"}'
----
--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "txpool_dryRunTransaction",
    "params": {
        "transaction": "0a040000000212040000000018012080c2d72f2a200fe9a3f1a21b5530f27f87a414b549e79a940bf24fdf2b2f05e7f22aeeecc86a32360a08000000000000000010011a1496c2f3cd9d9a09814d5f5d4182dc84183ea5abfb22124c6174657374205472616e73616374696f6e3a40a77b75083135aa1570e78a64c3f1d40306e3b92498a5fd227a61c40739ba0d1b6f4c7d8e274cc8caa16662906698c215eab08833a8005442862786259613ed02"
    }
}'
----
--
=====

[TIP]
====
To verify that this is in fact the minimum fee, try to send a transaction with a slightly smaller transaction fee:

.Reducing the fee by 1 Beddow
 fee: minFee-BigInt("1"),

Then when dry-running the transaction again, you should see the following error in the terminal:

 (node:14890) UnhandledPromiseRejectionWarning: Error: Error: Insufficient transaction fee. Minimum required fee is: 127000

====