= How to calculate the minimum fee for a transaction
:toc: preamble
// URLs
:url_typedoc_transactions: {site-url}/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_transactions.html
:url_sdkexamples_minfee: https://github.com/LiskHQ/lisk-sdk-examples/blob/300-min-fee/guides/calculate-minfee/index.js
// Project URLs
:url_understand_tx_fee: understand-blockchain/blocks-txs.adoc#transaction-fees

====
On this page, you'll learn how to:

* [x] Define a valid fee for a transaction
* [x] Calculate the minimum fee for a specific transaction
====

== Option 1: Send a transaction with zero fee

If you try to send a transaction with a fee smaller than the minimum fee, the transaction will be rejected by the node with an error.
The error already includes the minimum fee required for the particular transaction.

[source,bash]
----
 % ./bin/run transaction:send 0a05746f6b656e12087472616e73666572180220ef900a2a20ec10255d3e78b2977f04e59ea9afd3e9a2ce9a6b44619ef9f6c47c29695b1df332330a0803000000000000001080c2d72f1a1488c0ee8a4f8fa0e498770c70749584f179938ffa220c48656c6c6f20576f726c64213a40dabb3bb29f133eb49c778091d673c4ed33afe46248bca7765cb12f8768acd0633f87051553d759e339597695eeb629128986b61e6d41e961847e6017c3fde80c
----

 Error: Insufficient transaction fee. Minimum required fee is 176000.

== Option 2: Manually calculate the minimum fee for a transaction

To compute the xref:{url_understand_tx_fee}[minimum fee] for a transaction, use the API client.
Create a small script called `compute-minfee.js` like described in the following sections.

NOTE: See the complete code example of the script in the Lisk SDK examples repository: {url_sdkexamples_minfee}[min-fee.js]

[TIP]
====
To compute the minimum fee for a transaction without a connection to the API client, the user can also use directly the {url_typedoc_transactions}[@liskhq/lisk-transactions^] package.
In this case, the user needs to provide the transaction object and the corresponding transaction schema to the function.
====

:sectnums:
=== Connect the API client to a node

First, create a function `getClient()`, which will return an instance of the API client.

The API client connects to a local node, having the RPC API enabled via WebSockets at port `7887`.

TIP: Alternatively, the corresponding HTTP or IPC APIs can be used, if the node has enabled those.

To connect to a different node, simply update the API URL defined in `nodeAPIURL`.

.compute-minfee.js
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');

let clientCache;
// A URL pointing to a node with open API
const nodeAPIURL = 'ws://localhost:7887/rpc-ws'

// Connects to a node API
const getClient = async () => {
	if (!clientCache) {
		clientCache = await apiClient.createWSClient(nodeAPIURL);
	}
	return clientCache;
};
----

=== Define the transaction to calcuclate the fee for

Adjust the following properties to match the transaction you want to calculate the minimum fee for:

* `module`,
* `command`
* and `params`.

For the following values, it is OK to use dummy values:

* `nonce`,
* `fee`
* and `senderPublicKey`

.compute-minfee.js
[source,js]
----
// Transaction to calculate the minimum fee for
const tx = {
	module: 'token',
	command: 'transfer',
	senderPublicKey: '1234567890123456789012345678901234567890123456789012345678901234',
	nonce: 0,
	fee: 0,
	params: {
		amount:100000000,
		tokenID: "0300000000000000",
		recipientAddress: "lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz",
		data: "Hello World!"
	}
};
----

=== Compute minimumFee

Finally, call the `getClient` function to get the API clint, and use it to calculate the fee with `client.transaction.computeMinFee(tx)`.

.compute-minfee.js
[source,js]
----
const { apiClient, transactions } = require('@liskhq/lisk-client');

let clientCache;
// A URL pointing to a node with open API
const nodeAPIURL = 'ws://localhost:7887/rpc-ws'

// Connects to a node API
const getClient = async () => {
	if (!clientCache) {
		clientCache = await apiClient.createWSClient(nodeAPIURL);
	}
	return clientCache;
};

// Transaction to calculate the minimum fee for
const tx = {
	module: 'token',
	command: 'transfer',
	senderPublicKey: '1234567890123456789012345678901234567890123456789012345678901234',
	nonce: 0,
	fee: 0,
	params: {
		amount:100000000,
		tokenID: "0300000000000000",
		recipientAddress: "lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz",
		data: "Hello World!"
	}
};

// Calculate and return the minimum fee
getClient().then(client => {
	const minFee = client.transaction.computeMinFee(tx);
	console.log("The minimum fee for the given transaction is: ", minFee, " Beddows, i.e. ", transactions.convertBeddowsToLSK(minFee.toString()), " LSK.");
	process.exit(0);
}).catch(error => {
	console.log("Error: " + error);
	process.exit(1);
});


----

=== Execute

If the script is now executed in the terminal, it will display the minimum fee for the defined transaction.

[source,bash]
----
% node compute-minfee.js
The minimum fee for the given transaction is:  139000n  Beddows, i.e.  0.00139  LSK
----

:!sectnums: