= How to calculate the minimum fee for a transaction
:toc: preamble
// URLs
:url_typedoc_transactions: {site-url}/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_transactions.html
:url_sdkexamples_minfee: https://github.com/LiskHQ/lisk-sdk-examples/blob/development/guides/calculate-minfee/index.js
// Project URLs
:url_understand_tx_fee: understand-blockchain/blocks-txs.adoc#transaction-fees

====
On this page, you'll learn how to:

* [x] Dry-run a transaction to retrieve the minimum fee
* [x] Calculate the minimum fee for a given transaction
====

Another option to compute the xref:{url_understand_tx_fee}[minimum fee] for a transaction, use the API client.
Create a small script called `compute-minfee.js` as described in the following sections.

NOTE: See the complete code example of the script in the Lisk SDK examples repository: {url_sdkexamples_minfee}[min-fee.js]

[TIP]
====
To compute the minimum fee for a transaction without a connection to the API client, the user can also use directly the {url_typedoc_transactions}[@liskhq/lisk-transactions^] package.
In this case, the user needs to provide the transaction object and the corresponding transaction schema to the function.
====

== Connect the API client to a node

The Lisk API client is a JS package that allows to connect to a node API through WS and IPC protocols.

It can be used inside of JS or TS script to connect to a blockchain node API in order to calculate the minimum fee for a transaction conveniently.

To use the Lisk API client, install the `lisk-client` package with NPM:

[source,bash]
----
npm install @liskhq/lisk-client
----

[tabs]
=====
WS API client example::
+
--
Create a file `api-client.js` which will export the function `getClient()`.

Adjust `RPC_ENDPOINT` to point to the node you want to post the transaction to.

.api-client.js
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');

const RPC_ENDPOINT = 'ws://localhost:7887/rpc-ws';
let clientCache;

const getClient = async () => {
  if (!clientCache) {
    clientCache = await apiClient.createWSClient(RPC_ENDPOINT);
  }
  return clientCache;
};

module.exports = { getClient };
----
--
IPC API client example::
+
--
Create a file `api-client.js` which will export the function `getClient()`.

Adjust `DATA_PATH` to point to the blockchain client data path.

.api-client.js
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');

const DATA_PATH = '~/.lisk/hello_client';
let clientCache;

const getClient = async () => {
    if (!clientCache) {
        clientCache = await apiClient.createIPCClient(DATA_PATH);
    }
    return clientCache;
};

module.exports = { getClient };
----
--
=====

== Prepare the transaction
Create a new script `compute-minfee.js` to calculate the minimum required transaction fee.
Import the `getClient()` function and execute it to use the API client to calculate the minimum fee, as shown in the snippet below.

Next, prepare the transaction object, for which the minimum required fee shall be calculated.

Adjust the following properties to match the transaction you want to calculate the minimum fee for:

* `module`,
* `command`
* and `params`.

For the following values, it is OK to use dummy values:

* `nonce`,
* `fee`
* and `senderPublicKey`

.compute-minfee.js
[source,js]
----
const { getClient } = require('./api-client');

// Transaction to calculate the minimum fee for
const tx = {
	module: 'token',
	command: 'transfer',
	senderPublicKey: '1234567890123456789012345678901234567890123456789012345678901234',
	nonce: 0,
	fee: 0,
	params: {
		amount:100000000,
		tokenID: "0300000000000000",
		recipientAddress: "lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz",
		data: "Hello World!"
	}
};
----

== Compute minimumFee

Finally, call the `getClient` function to get the API client, and use it to calculate the fee with `client.transaction.computeMinFee(tx)`.

.compute-minfee.js
[source,js]
----
const { getClient } = require('./api-client');

// Transaction to calculate the minimum fee for
const tx = {
	module: 'token',
	command: 'transfer',
	senderPublicKey: '1234567890123456789012345678901234567890123456789012345678901234',
	nonce: 0,
	fee: 0,
	params: {
		amount:100000000,
		tokenID: "0000000000000000",
		recipientAddress: "lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz",
		data: "Hello World!"
	}
};

// Calculate and return the minimum fee
getClient().then(client => {
	const minFee = client.transaction.computeMinFee(tx);
	console.log("The minimum fee for the given transaction is: ", minFee, " Beddows, i.e. ", transactions.convertBeddowsToLSK(minFee.toString()), " LSK.");
	process.exit(0);
}).catch(error => {
	console.log("Error: " + error);
	process.exit(1);
});
----

== Dry-run the transaction

Using the prepared transaction, perform a dry-run like so:

[source,bash]
----
./bin/run endpoint:invoke txpool_dryRunTransaction '{"transaction": "0a05746f6b656e12087472616e73666572180220ef900a2a20ec10255d3e78b2977f04e59ea9afd3e9a2ce9a6b44619ef9f6c47c29695b1df332330a0803000000000000001080c2d72f1a1488c0ee8a4f8fa0e498770c70749584f179938ffa220c48656c6c6f20576f726c64213a40dabb3bb29f133eb49c778091d673c4ed33afe46248bca7765cb12f8768acd0633f87051553d759e339597695eeb629128986b61e6d41e961847e6017c3fde80c"}'
----

If a dry-run is performed on a transaction with a fee smaller than the minimum fee, the dry-run will fail with an error.
The error already includes the minimum fee required for the particular transaction.

[source,json]
----
{
  "result":-1,
  "events":[],
  "errorMessage":"Insufficient transaction fee. Minimum required fee is 176000."
}
----

== Execute

If the script is now executed in the terminal, it will display the minimum fee for the defined transaction.

[source,bash]
----
% node compute-minfee.js
The minimum fee for the given transaction is:  139000n  Beddows, i.e.  0.00139  LSK
----