= Connecting to endpoints
Muhammad Talha <muhammad.talha@lightcurve.io>

//Settings
:toc: preamble
:toclevels: 5
:page-toclevels: 4
:idprefix:
:idseparator: -
:imagesdir: ../../assets/images
:sdk_docs: lisk-sdk::
//External URLs
:url_npm_lisk_sdk: https://www.npmjs.com/package/lisk-sdk
:url_wiki_ipc: https://en.wikipedia.org/wiki/Inter-process_communication
:url_websocket: https://en.wikipedia.org/wiki/WebSocket
:url_wiki_http_protocol: https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol
:url_eda: https://en.wikipedia.org/wiki/Event-driven_architecture
// Project URLs
:url_rpc_config: {sdk_docs}config.adoc#rpc
:url_advanced_rpc: api/lisk-node-rpc.adoc
:url_guides_config_rpc: build-blockchain/configuration.adoc#rpc


:url_endpoints_modules: build-blockchain/module/endpoints-methods.adoc#endpoints
:url_endpoints_plugins: build-blockchain/plugin/plugin-endpoints.adoc#creating-an-endpoint


:url_intro_modules: understand-blockchain/sdk/modules-commands.adoc
:url_intro_plugins: understand-blockchain/sdk/plugins.adoc
:url_intro_plugins_load: understand-blockchain/sdk/plugins.adoc#defining-the-plugin-logic
// :url_references_elements_apiclient: {sdk_docs}references/lisk-elements/api-client.adoc
// :url_references_elements_client: {sdk_docs}references/lisk-elements/client.adoc
:url_advanced_rpc_endpoints: {url_advanced_rpc}#endpoints
:url_advanced_rpc_events: {url_advanced_rpc}#events
:url_guides_asset: build-blockchain/modules/command.adoc
:url_lisk_sdk: glossary.adoc#lisk-sdk
:url_RPC_System_API: {url_advanced_rpc}#system
:url_RPC_Events: {url_advanced_rpc}#events
:JSON_RPC_Specs: https://www.jsonrpc.org/specification
:url_module_endpoints: {sdk_docs}/modules/index.adoc
:url_module_commands: understand-blockchain/sdk/modules-commands.adoc#blockchain-events
:url_sidechain_glossary: glossary.adoc#sidechain-application
:url_sapp: glossary.adoc#sapp
:url_sidechain_client: glossary.adoc#sidechain-client
// footnotes
:fn_sidechain_glossary: footnote:sidechain[See xref:{url_sidechain_glossary}[Sidechain application] for more details.]
:fn_saap_glossary: footnote:saap[See xref:{url_sapp}[sApp] for more details.]
:fn_sidechain_client_glossary: footnote:client[See xref:{url_sidechain_client}[Sidechain client] for more details.]

// TODO: Update the page by uncommenting the hyperlinks once the updated pages are available.

By default, Lisk exposes xref:{url_advanced_rpc_endpoints}[a range of endpoints] to communicate with a node.

Apart from that, sidechain clients{fn_sidechain_client_glossary}, specifically xref:{url_intro_modules}[Modules] and xref:{url_intro_plugins}[Plugins] of a sidechain client can also expose endpoints as described in the guides about xref:{url_endpoints_modules}[implementing endpoints for a module] and xref:{url_endpoints_plugins}[creating an endpoint for a plugin], respectively.

On this page, you'll learn about all the ways with which the aforementioned endpoints can be called within the Lisk ecosystem.

[[the-api-client]]
== The API client

// The xref:{url_references_elements_apiclient}[] simplifies sending API requests to a blockchain application. 
The API client simplifies sending API requests to a blockchain application.

Blockchain applications developed with Lisk SDK communicate to a node via RPCs. RPC-based interfaces i.e. IPC, WS, or HTTP allow applications to *invoke* RPC endpoints. 

An API client can be imported into any JS client application as shown in the following snippets.

// TIP: To conveniently communicate with a blockchain application, use the `apiClient` included in the xref:{url_references_elements_client}[@liskhq/lisk-client] and the {url_npm_lisk_sdk}[lisk-sdk^] packages.
TIP: To conveniently communicate with a blockchain application, use the `apiClient` included in the @liskhq/lisk-client and the lisk-sdk packages.

[tabs]

=====
WS API client example::
+
--
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');
let clientCache;
const nodeAPIURL = 'ws://localhost:7887/rpc-ws';

const getClient = async () => {
    if (!clientCache) {
        clientCache = await apiClient.createWSClient(nodeAPIURL);
    }
    return clientCache;
};


const blockId = "0f4ea1c3cfb61b99d387b26aaadf57936a528e5c713c6e55aa06f4d621b7e6f0";

getClient().then((client) => {
    client.invoke("chain_getBlockByID", {
        id: blockId
    }).then(res => {
        console.log("Result: ", res);
    });
});
----
--
IPC API client example::
+
--
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');
let clientCache;

const getClient = async () => {
    if (!clientCache) {
        clientCache = await apiClient.createIPCClient('~/.lisk/my-app');
    }
    return clientCache;
};

const blockId = "0f4ea1c3cfb61b99d387b26aaadf57936a528e5c713c6e55aa06f4d621b7e6f0";

getClient().then((client) => {
    client.invoke("chain_getBlockByID", {
        id: blockId
    }).then(res => {
        console.log("Result: ", res);
    });
});
----
--
HTTP cURL::
+
--
Apart from the WS and IPC method, Lisk endpoints also support HTTP requests and response mechanisms. With a {JSON_RPC_Specs}[JSON RPC 2.0] based format, any endpoint can be invoked using a cURL request. For example:

[source,json]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chain_getBlockByHeight",
    "params": {
        "height": 2291
    }
}'
----
--
=====