= Connecting to endpoints
Muhammad Talha <muhammad.talha@lightcurve.io> Christopher Braithwaite <christopher.braithwaite@lightcurve.io>
:toc: preamble
:toclevels: 5
:page-toclevels: 4
:idprefix:
:idseparator: -
:imagesdir: ../../assets/images
//External URLs
:url_npm_lisk_sdk: https://www.npmjs.com/package/lisk-sdk
:JSON_RPC_Specs: https://www.jsonrpc.org/specification
:url_socket_io: https://socket.io/
:url_readme: https://github.com/LiskHQ/lisk-core/tree/v4.0.0-beta.3#configuring-lisk-node


// Project URLs
:docs_sdk: v6@lisk-sdk::
:docs_general: ROOT::

:url_advanced_rpc: api/lisk-node-rpc.adoc
:url_endpoints_modules: build-blockchain/module/endpoints-methods.adoc#endpoints
:url_endpoints_plugins: build-blockchain/plugin/plugin-endpoints.adoc#creating-an-endpoint
:url_sync_store: build-blockchain/plugin/plugin-class.adoc#sync-and-store-new-event
:url_cli: {docs_sdk}client-cli.adoc#endpoint
:url_intro_modules: understand-blockchain/sdk/modules-commands.adoc
:url_intro_plugins: understand-blockchain/sdk/plugins.adoc
// :url_references_elements_apiclient: {sdk_docs}references/lisk-elements/api-client.adoc
// :url_references_elements_client: {sdk_docs}references/lisk-elements/client.adoc
// :url_advanced_rpc_endpoints: {url_advanced_rpc}#endpoints
:url_advanced_rpc_endpoints: api/lisk-node-rpc.adoc
:url_rpc_api: api/lisk-service-rpc.adoc#introduction-to-lisk-service-endpoints
:url_api_http:  ROOT::api/lisk-service-http.adoc
:url_api_mainnet: https://service.lisk.com/api/v3
:url_api_testnet: https://testnet-service.lisk.com/api/v3
:url_api_http_testnet:  ROOT::api/lisk-service-http-testnet.adoc

:url_rpc_api_mainnet: wss://service.lisk.com/rpc-v3
:url_api_rpc:  ROOT::api/lisk-service-rpc.adoc
:url_subscribing_to_events: integrate-blockchain/subscribing-to-events.adoc
:url_enable_apis: integrate-blockchain/aggregate-blockchain-data/index.adoc#enable-api-on-the-blockchain-node



// TODO: Update the page by uncommenting the hyperlinks once the updated pages are available.

On this page, connecting via endpoints to both nodes and products such as Lisk Service are covered, and examples are provided on how the relevant endpoints can be invoked within the Lisk ecosystem.

By default, Lisk exposes xref:{url_advanced_rpc_endpoints}[a range of endpoints] to enable communicate with a node or via Lisk Service.

Furthermore, xref:{url_intro_modules}[Modules] and xref:{url_intro_plugins}[Plugins] of a blockchain client can also expose endpoints as described in the guides about xref:{url_endpoints_modules}[implementing endpoints for a module] and xref:{url_endpoints_plugins}[creating an endpoint for a plugin], respectively.


[[the-api-client]]
== Connecting to a node
=== Invoking via API client

// The xref:{url_references_elements_apiclient}[] simplifies sending API requests to a blockchain application. 
The API client simplifies sending API requests to a blockchain node.

External services communicate to a blockchain node via RPCs.

The RPC-based endpoint invocations to the nodes are possible over IPC, WS, or HTTP.

NOTE: To interact with the node APIs through IPC, WS, or HTTP, it is necessary to enable the corresponding APIs. This can be done by configuring them in the xref:{url_enable_apis}[node settings], using command line flags, or setting up the environment when launching the blockchain application.

An API client can be imported into any JS client application as shown in the following snippets.

// TIP: To conveniently communicate with a blockchain application, use the `apiClient` included in the xref:{url_references_elements_client}[@liskhq/lisk-client] and the {url_npm_lisk_sdk}[lisk-sdk^] packages.
TIP: To conveniently communicate with a blockchain node, use the `apiClient` included in the `@liskhq/lisk-client` and the `lisk-sdk` packages.

[tabs]
=====
WS API client example::
+
--
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');
let clientCache;
const nodeAPIURL = 'ws://localhost:7887/rpc-ws';

const getClient = async () => {
    if (!clientCache) {
        clientCache = await apiClient.createWSClient(nodeAPIURL);
    }
    return clientCache;
};


const blockId = "0f4ea1c3cfb61b99d387b26aaadf57936a528e5c713c6e55aa06f4d621b7e6f0";

getClient().then((client) => {
    client.invoke("chain_getBlockByID", {
        id: blockId
    }).then(res => {
        console.log("Result: ", res);
    });
});
----
--
IPC API client example::
+
--
[source,js]
----
const { apiClient } = require('@liskhq/lisk-client');
let clientCache;

const getClient = async () => {
    if (!clientCache) {
        // The data path to the blockchain client should be passed here
        // In our case, we are passing data path for the "hello_client"
        clientCache = await apiClient.createIPCClient('~/.lisk/hello_client');
    }
    return clientCache;
};

const blockId = "0f4ea1c3cfb61b99d387b26aaadf57936a528e5c713c6e55aa06f4d621b7e6f0";

getClient().then((client) => {
    client.invoke("chain_getBlockByID", {
        id: blockId
    }).then(res => {
        console.log("Result: ", res);
    });
});
----
--
HTTP cURL::
+
--
Apart from the WS and IPC method, Lisk endpoints also support HTTP requests and response mechanisms.
With a {JSON_RPC_Specs}[JSON RPC 2.0] based format, any endpoint can be invoked using a cURL request.
For example, as shown below:

[source,json]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chain_getBlockByHeight",
    "params": {
        "height": 2291
    }
}'
----
--
=====

[TIP]
====
Lisk also supports invoking endpoints from within the blockchain client.
For more information, check out the xref:{url_sync_store}[syncing and storing] example for the `HelloInfoPlugin`.
Specifically, the line of code shown in the following example:

[source,typescript]
----
private async _syncChainEvents(): Promise<void> {
    // 1. Get the latest block height from the blockchain
    const res = await this.apiClient.invoke<{ header: { height: number } }>("chain_getLastBlock", {});
    //[...]
}
----
====

=== Invoking via the CLI
Any endpoint within the Lisk ecosystem can be invoked via node CLI as well.
For more information, check out the xref:{url_cli}[Client CLI] page.

NOTE: If you are running *Lisk Core*, you can use mostly the same CLI commands as in the general node CLI.
Just replace `./bin/run` with `lisk-core` in that case.

To invoke an endpoint via the CLI, simply use the `endpoint:invoke` command as shown in the following code snippet.

NOTE: In order to make the endpoints accessible, the configuration setting `rpc.allowedMethods` must either specify `["*"]` to allow all methods.
Alternatively, it can specify the module name, for example, such as `["consensus","token","pos"]`, or the exact method names such as ["chain_getLastBlock", "system_getNodeInfo"] to expose them in the API.
For further details please see the {url_readme}[Configuring Lisk Node] section in the Lisk Core README file.

[source,bash]
----
$./bin/run endpoint:invoke chain_getLastBlock --pretty
{
  "header": {
    "version": 2,
    "timestamp": 1662742534,
    "height": 110,
    "previousBlockID": "4ef1095d3560064dd4a66fb4543680efe65a64020c363571b107be9513628674",
    "stateRoot": "b2507620beb3be5cd7d0cbb7926e4365b5674b682673dc2423400a497636e13e",
    "assetRoot": "2aa695e23b36439b56130a490ef38feaaec57d82859ff64f5ca61cc49993afa3",
    "eventRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "transactionRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "validatorsHash": "84f3ed67cec1eb7bd6dc3ec01b0d0323021c1e86a3dc760b9b92041c28da31ac",
    "aggregateCommit": {
      "height": 0,
      "aggregationBits": "",
      "certificateSignature": ""
    },
    "generatorAddress": "lsk5y2q2tn35xrnpdc4oag8sa3ktdacmdcahvwqot",
    "maxHeightPrevoted": 0,
    "maxHeightGenerated": 110,
    "signature": "6ecd5c6f14d18f84a2125cca4186a6cc493dcd66338f9b13c580cc06be7a33267fe259a074d6f6dc9276aff700a985472fca15cbcf25b2fde1b621fe0810b507",
    "id": "334416bdc1f8a7ff842728ac4e591337a0e7b80f190934694cad7e2a9afdb416"
  },
  "transactions": [],
  "assets": [
    {
      "module": "random",
      "data": "0a10dde856a212ac5af46e26abb5f941cc8b"
    }
  ]
}
----

== Connecting to Lisk Service

=== Invoking via WebSocket

The API base URL is the base URL for the Lisk Service WS-RPC endpoints, that are available to query under the `/rpc-v3` namespace.

* *WS-RPC:* `wss://service.lisk.com/rpc-v3`

For WS, the RPC endpoint name is passed in the `method` property after establishing a WebSocket connection using {url_socket_io}[socket.io].
An example using the WS JSON-RPC API can be seen below.

[tabs]
=====
WS JSON-RPC API::
+
--
[source,js]
----
const io = require('socket.io-client');

const REQUEST_TIMEOUT = 10 * 1000;

const apiEndpoint = 'wss://service.lisk.com/rpc-v3';
const rpcEndpoint = 'get.network.status';
const rpcParams = {};

const socket = io(
	apiEndpoint,
	{
		forceNew: true,
		transports: ['websocket'],
	},
);

socket.emit(
	'request', // channel on which Lisk Service handles the WS-RPC calls
	{
		method: rpcEndpoint,
		params: rpcParams,
	},
	answer => {
		console.log(JSON.stringify(answer, null, 2));
		process.exit(0);
	},
);

setTimeout(
	() => {
		console.log('Request timeout - could not get a response.');
		process.exit(1);
	},
	REQUEST_TIMEOUT,
);
----

--
=====
More detailed information and examples can be found on the xref:{url_rpc_api}[RPC API of Lisk Service page].

=== Invoking the HTTP API

Using the xref:{url_api_http}[HTTP API] offers a RESTful API with various additional endpoints, that for example, could be deployed to build user interfaces and wallets for blockchain applications that are compliant with the Lisk protocol.

There is a public Lisk Service HTTP API, which can be used to query the desired information from the network.

Lisk Mainnet::
* Public API base URL: `{url_api_mainnet}`
* API specification: xref:{url_api_http}[Lisk Service HTTP API reference (Mainnet)]

Lisk Testnet::
* Public API base URL: `{url_api_testnet}`
* API specification: xref:{url_api_http_testnet}[Lisk Service HTTP API reference (Testnet)]

In addition to the WS and IPC method, Lisk endpoints also support HTTP requests and response mechanisms, such as HTTP Axios and cURL.
[tabs]
=====
HTTP Axios::
+
--
[source,js]
----
const axios = require('axios');

const getEndpoint = 'https://service.lisk.com/api/v3/network/status';

axios.get(getEndpoint)
	.then((axiosResponse) => {
		const { data: apiResponse } = axiosResponse;
		console.log(JSON.stringify(apiResponse, null, 2));
	});

----
--
An example of how to execute a POST request to validate a BLS key and Proof of Possession pair is shown below.
+
--

[source,js]

----

const axios = require('axios');

const postEndpoint = 'https://service.lisk.com/api/v3/validator/validate-bls-key';
const postEndpointParams = {
  blsKey: 'b301803f8b5ac4a1133581fc676dfedc60d891dd5fa99028805e5ea5b08d3491af75d0707adab3b70c6a6a580217bf81',
  proofOfPossession: '88bb31b27eae23038e14f9d9d1b628a39f5881b5278c3c6f0249f81ba0deb1f68aa5f8847854d6554051aa810fdf1cdb02df4af7a5647b1aa4afb60ec6d446ee17af24a8a50876ffdaf9bf475038ec5f8ebeda1c1c6a3220293e23b13a9a5d26',
};

axios.post(
	postEndpoint,
	postEndpointParams,
)
	.then((axiosResponse) => {
		const { data: apiResponse } = axiosResponse;
		console.log(JSON.stringify(apiResponse, null, 2));
	});
----
--
HTTP cURL::
To check the network status the following command can be used.
+
--
// With a {JSON_RPC_Specs}[JSON RPC 2.0] based format, any endpoint can be invoked using a cURL request.
[source,bash]
----
curl --location --request GET 'https://service.lisk.com/api/v3/network/status'
----
--
An example of how to execute a POST request to validate a BLS key and Proof of Possession pair is shown below.
+
--
[source,bash]
----
curl --location --request POST 'https://service.lisk.com/api/v3/validator/validate-bls-key' \
--header 'Content-Type: application/json' \
--data-raw '{
  "blsKey": "b301803f8b5ac4a1133581fc676dfedc60d891dd5fa99028805e5ea5b08d3491af75d0707adab3b70c6a6a580217bf81",
  "proofOfPossession": "88bb31b27eae23038e14f9d9d1b628a39f5881b5278c3c6f0249f81ba0deb1f68aa5f8847854d6554051aa810fdf1cdb02df4af7a5647b1aa4afb60ec6d446ee17af24a8a50876ffdaf9bf475038ec5f8ebeda1c1c6a3220293e23b13a9a5d26"
}'
----
=====

=== Subscribe to Events
The Subscribe events feature allows connecting to specific endpoints to receive real-time updates or notifications, as shown in the examples below.
Further information can be found in the xref:{url_subscribing_to_events}[Subscribing to events] page.

[tabs]
=====
Subscribe - Specific Event::
+
--
[source,js]
----
const io = require('socket.io-client');

const subscriptionEndpoint = 'wss://service.lisk.com/blockchain';
const eventName = 'new.block';

const socket = io(
	subscriptionEndpoint,
	{
		forceNew: true,
		transports: ['websocket'],
	},
);

socket.on(
	eventName,
	(eventPayload) => {
		console.log(`Event: ${eventName}`);
		console.log('Payload:', JSON.stringify(eventPayload, null, 2), '\n');
	}
);
----
--
Subscribe - All Events::
+
--
[source,js]
----
const io = require('socket.io-client');

const subscriptionEndpoint = 'wss://service.lisk.com/blockchain';

const socket = io(
	subscriptionEndpoint,
	{
		forceNew: true,
		transports: ['websocket'],
	},
);

const onevent = socket.onevent;
socket.onevent = function (packet) {
    const args = packet.data || [];
    onevent.call (this, packet);
    packet.data = ['*'].concat(args);
    onevent.call(this, packet);
};

socket.on(
	'*',
	(eventName, eventPayload) => {
		console.log(`Event: ${eventName}`);
		console.log('Payload:', JSON.stringify(eventPayload, null, 2), '\n');
	}
);
----
=====

