= How to send a transaction to the network
:url_sdk_client: lisk-sdk::references/lisk-elements/client.adoc
:url_integrate_tx_offline: integrate-blockchain/create-tx-offline.adoc

[NOTE]
====
For convenience, it is recommended to use the API client to communicate to a node for creating and signing transactions.

In case a higher security is desired, it is possible to create the transaction in a complete offline environment.
Please check out the guide xref:{url_integrate_tx_offline}[] for more information.
====


== How to create a transaction

=== Connecting to a node via the API client

On of the most simple ways to create transactions, is via the API client, which is included in the xref:{url_sdk_client}[lisk-client] package.

.Example: Creating a transfer transaction
[source,js]
----
import { apiClient, transactions } from '@liskhq/lisk-client';
let clientCache;
// The node used to create the transaction
const nodeAPIURL = 'ws://localhost:8080/ws';
const address = "lsk123";
const passphrase = "A 12 word mnemonic passphrase";

const getClient = async () => {
	if (!clientCache) {
		clientCache = await apiClient.createWSClient(nodeAPIURL);
	}
	return clientCache;
};

getClient().then(async (client) => {
	const tx = await client.transaction.create({
            moduleID: 2,
            assetID: 0,
            fee: BigInt(transactions.convertLSKToBeddows('0.01')),
            asset: {
                amount: BigInt(transactions.convertLSKToBeddows(state.amount)),
                recipientAddress: address,
                data: '',
            },
        }, passphrase);
        const response = await client.transaction.send(tx);
});
----

== Transaction properties
Explain nonce

== How to sign a transaction
How to sign a transaction

== How to send the transaction
encode it to Buffer
send it via Lisk Service/Core/SDK endpoint POST transactions

Explain how the transaction ID is added to the transaction

