= How to create multi-signature accounts and transactions
:toc: preamble
:idprefix:
:idseparator: -

====
On this page, you'll learn:

* [x] How to create a user account that is managed by multiple users
* [x] How to create and sign multi-signature transactions
====

== Intro
Multi-signature accounts are user accounts which are managed by a group of users.

As the name suggests, multi-signature accounts need multiple signatures of different members of the multi-signature account to send any transaction.

How many and which members exactly need to sign is defined during the registration of the multi-signature account.

NOTE: A multi-signature account can have 2-64 members.

== Use cases for multi-signature accounts

=== Decision Uniformity
A possible use case for multi-signature might be a family account, where family members manage the funds in the account collaboratively, or consider a corporation with four board of directors.
Each board member gains access to one private key.
No individual member can misuse the funds.
Thus, only the decisions agreed upon by majority members can be executed.

=== Escrow Transactions
In case two users get into a dispute, a multi-signature account could be created to solve it.

For example, Alice makes the payment but Bob does not provide the services or goods as promised.
In such a scenario, to resolve the dispute between users, a mutually trusted third party/arbiter steps in.

Considering the wallet is configured to be 2-of-3 multi-sig wallet, the third key in above case is given to the arbiter.
Based on arbiter’s judgment the funds can be given either to Alice or to Bob.

=== Two-Factor Authentication
If John creates a multi-sig wallet that requires two keys, John creates a two factor authentication mechanism to access the funds.
John can store the private keys on two different devices and the funds stored in John’s multisig wallet can be accessed only if both the keys are provided.

However, using multisig technology as two-factor authentication can be risky, especially if it is a set of 2-of-2 multisig address.
If one of the keys is lost, you will not be able to access your funds.
Thus, it is safer to use a 2-of-3 setup.


== How to create a multi-signature account

//TODO: Add link to typedocs Register multisig command once available
//A multi-signature account is created by sending a {}[Register Multisignature] transaction.
A multi-signature account is created by sending a Register Multisignature transaction.
This can be performed by any user account.

The account sending the transaction will be transformed into a multi-signature account, once the transaction is included in a block.

The following parameters are required to send a Register Multisignature transaction:

. `numberOfSignatures`: The number of private keys that must sign a transaction.
. `mandatoryKeys`: An array of public keys in lexicographical order.
Once the account is registered as a multi-signature account, every outgoing transaction requires a signature for every public key in `mandatoryKeys`.
. `optionalKeys`: An array of public keys in lexicographical order.
Once the account is registered as a multi-signature account, every outgoing transaction requires some signatures for some public keys in `optionalKeys` (the number of needed signatures depends on the `numberOfSignatures` property and may also be zero).
. `signatures`: An array of signatures, corresponding to the public keys contained in `mandatoryKeys` and `optionalKeys`.
All public keys must have a corresponding signature.
The signatures corresponding to `mandatoryKeys` are appended first, followed by those corresponding to optionalKeys, where the order of signatures is the same as the order of public keys in the respective array.

Considering the use case example <<escrow-transactions>> from above, the multi-signature registration parameters would look like this:

. `numberOfSignatures`: 2
. `mandatoryKeys`: []
. `optionalKeys`: [AliceKey, BobKey, ArbiterKey]
. `signatures`: [AliceSignature, BobSignature, ArbiterSignature]

=== Option 1: Lisk Desktop

=== Option 2: Node CLI

=== Option 3: Lisk Elements

== How to create and sign a transaction for a multisignature account

=== Option 1: Lisk Desktop

=== Option 2: Node CLI

=== Option 3: Lisk Elements