= How to overwrite a transaction in the transaction pool
Mona Bärenfänger <mona@lightcurve.io>
:toc: preamble
// URLs
// Project URLs
:url_network_txpool: understand-blockchain/network.adoc#transaction-pool

====
On this page, you'll learn:

* [x] How to overwrite a transaction in the transaction pool
====

== Intro

When a transaction is sent to a node, it is first included in the xref:{url_network_txpool}[transaction pool].
Transactions in the transaction pool wait to be included in a block on the blockchain.

It may be the case, that the transaction sender intends to update the transaction before it is included in a block.
For example, to update specific parameters of the transaction, to replace the transaction entirely, or to speed up the inclusion of the transaction into a block by providing a higher fee.

This can be achieved by resending the updated transaction with a higher fee while using the same nonce, as explained in the following steps.

.This only works for transactions in the transaction pool
IMPORTANT: Overwriting a transaction is only possible for transactions, which haven't been included in a block, yet.

== Example: Original transaction

[source,json]
----
{
   "module":"token",
   "command":"transfer",
   "fee":"10000000",
   "nonce":"4",
   "senderPublicKey":"3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
   "signatures":[
      "c06cd0ef375911528d491971296532dbd58725f0fccc0f23e6c0656c43e75ecd12635616117e64d005f1c9f2a55de7cf2d8f5cb961927d839d141a18faa80e08"
   ],
   "params":{
      "tokenID":"0400000000000000",
      "amount":"800000000",
      "recipientAddress":"lskt8ovj2shbxrtno8xqqt7cnmzzygdkbt6brnvmj",
      "data":"Happy birthday!"
   },
   "id":"f3f537bbd52464d2f97c02f5ef0f9a805d19ad4f8ef1c7efa1da17cef0e5036a"
}
----


== Create a new transaction with the same nonce and a higher fee

[source,bash]
----
lisk-core transaction:create token transfer 25000000 --nonce 4 --json ---pretty
----

[source,json]
----
{
  "transaction": {
    "module": "token",
    "command": "transfer",
    "fee": "25000000",
    "nonce": "4",
    "senderPublicKey": "61d320f822fcc163489499200ae6c99a66296513b1ca1066e49a37a026434ac0",
    "signatures": [
      "fca7710c74b9d13ef954be1128a1069bc8b50dbb9f410ddfe62d7d580920e685cb6efbf1b801e86b11839eb5e286ef70d3b6ab725e6d521a6377b6bf5f079203"
    ],
    "params": {
      "tokenID": "0200000000000000",
      "amount": "1",
      "recipientAddress": "lskt8ovj2shbxrtno8xqqt7cnmzzygdkbt6brnvmj",
      "data": "Happy birthday!"
    },
    "id": "78d041e4e9c55fb0c232fcefcb712cb2abb09101dc27281a88e6180a726486d2"
  }
}
----
