= Chain Connector plugin: Endpoint reference
Muhammad Talha <muhammad.talha@lightcurve.io>
// Settings
:toc: preamble
//URLs
:url_typedoc_chainConnector: {site-url}/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_framework_chain_connector_plugin.html

//Project URLs
:url_integrate_endpoints: integrate-blockchain/connecting-endpoints.adoc
// :url_command_fee: understand-blockchain/blocks-txs.adoc#command-fee

//TODO: Add a hyperlink for Dynamic Rewards
This page summarizes all API endpoints specific to the {url_typedoc_chainConnector}[Chain Connector Plugin^].

All the aforementioned endpoints are invoked using the `chainConnector` prefix.

TIP: Endpoints can be invoked as explained in the xref:{url_integrate_endpoints}[] guide.


== `chainConnector_getSentCCUs`
Returns the CCUs sent on chain.

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke chainConnector_getSentCCUs --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://127.0.0.1:7886/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chainConnector_getSentCCUs",
    "params": {}
}'
----
--
=====


.Response
[%collapsible]
====
.Example output
[source,json]
----
{

}
----
====

== `chainConnector_getAggregateCommits`

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke chainConnector_getAggregateCommits --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://127.0.0.1:7886/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chainConnector_getAggregateCommits",
    "params": {}
}'
----
--
=====


.Response
[%collapsible]
====
.Example output
[source,json]
----
[
    {
        "height": 2271,
        "aggregationBits": "01",
        "certificateSignature": "aa472620459ba955152f221a6f639a7e677515c71e390cf1a17a71fb74ebc199301656e27afed8042f6f313536789143042c1c1c7dcbf955dc161e69175c8bc4a564bc84873df1a909397ec82c3c4d1df287036783bbe41cd8e4f44ca8084557"
    },
    {
        "height": 2272,
        "aggregationBits": "01",
        "certificateSignature": "8260018b44d2627bee54fc73fbf8e9d904e94dad27a7580154c395a3690a1f0e82f796df6f65d510c8dcd40e2aae0f0e0cd83558c8940f2bb2cd8a075b2d5ea56cdeb8d3c898c1c96c5904ab579be223f36d8587ef669e4c04be7a0661d7cee4"
    }
]
----
====


== `chainConnector_getBlockHeaders`

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke chainConnector_getBlockHeaders --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://127.0.0.1:7886/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chainConnector_getBlockHeaders",
    "params": {}
}'
----
--
=====


.Response
[%collapsible]
====
.Example output
[source,json]
----
[
    {
        "version": 2,
        "timestamp": 1700738787,
        "height": 2273,
        "previousBlockID": "e5ebf490cc8ff30e968934f2f5771b3077606f11356c0ab23236419bdf94c712",
        "stateRoot": "cc4120e13bb119751bbaae057490bb1580b365e1f21490b1dbdb307d4d0559e2",
        "assetRoot": "594935cbdb78c60dadc1f27abc2bfa7a2bdc486b40ee540a2a963944566202ab",
        "eventRoot": "211811b2fd56bb0694e30e4e954c74faf0d209dddcba5086a375f412112bb730",
        "transactionRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "validatorsHash": "f626be7093592d81cde5bbae150a67db52619e0fd193ee61aebe847c45dd557e",
        "aggregateCommit": {
            "height": 2271,
            "aggregationBits": "01",
            "certificateSignature": "aa472620459ba955152f221a6f639a7e677515c71e390cf1a17a71fb74ebc199301656e27afed8042f6f313536789143042c1c1c7dcbf955dc161e69175c8bc4a564bc84873df1a909397ec82c3c4d1df287036783bbe41cd8e4f44ca8084557"
        },
        "generatorAddress": "lskz98oaohxaw6jcfvtgdxm9sprcqzstddoqusrns",
        "maxHeightPrevoted": 2272,
        "maxHeightGenerated": 2272,
        "impliesMaxPrevotes": true,
        "signature": "8f28b8cc7fceecb15c97d0986826fc2155c4cd705a8f1c83aad91d66c2fa4a61294ed4a31c222e3180cbdf4147407eea79a934b09d9a3bea4b55a719f3b9620f",
        "id": "696b866bcdfae7a37326f383eee29cabe65a7cab6c33b79cae4aa461a4043327"
    }
]
----
====


== `chainConnector_getCrossChainMessages`

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke chainConnector_getCrossChainMessages --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://127.0.0.1:7886/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chainConnector_getCrossChainMessages",
    "params": {}
}'
----
--
=====


.Response
[%collapsible]
====
.Example output
[source,json]
----
[
    {
        "ccms": [],
        "height": 2273,
        "inclusionProof": {
            "bitmap": "01",
            "siblingHashes": [
                "00390d6e7403f26db8fd3507057b8264b944fc767491b7d5525089f711e32355"
            ]
        },
        "outboxSize": 0
    },
    {
        "ccms": [],
        "height": 2274,
        "inclusionProof": {
            "bitmap": "01",
            "siblingHashes": [
                "f00fdae202809b43d4a6d466ffe90ac8b0d9202caef26fcfb8234d3eba504c86"
            ]
        },
        "outboxSize": 0
    },
    {
        "ccms": [],
        "height": 2275,
        "inclusionProof": {
            "bitmap": "01",
            "siblingHashes": [
                "f05f43f7c2703b34c96789d32c0fffdd19b87a21062f605f8a02de48f9e7787b"
            ]
        },
        "outboxSize": 0
    },
    {
        "ccms": [],
        "height": 2276,
        "inclusionProof": {
            "bitmap": "01",
            "siblingHashes": [
                "32f2a4a5a1a7d45fd43acbe344c70b9ebee99471b535fa86195b9eb7c812a8db"
            ]
        },
        "outboxSize": 0
    },
    {
        "ccms": [],
        "height": 2277,
        "inclusionProof": {
            "bitmap": "01",
            "siblingHashes": [
                "db2629c8587deb600dca12813787784304d307c19aa7470be99074ffd66f6292"
            ]
        },
        "outboxSize": 0
    },
    {
        "ccms": [],
        "height": 2278,
        "inclusionProof": {
            "bitmap": "01",
            "siblingHashes": [
                "c13ea6207b51aae9dfb1350a5401ca3c16ed28af87f5e061e17008d1769b8a46"
            ]
        },
        "outboxSize": 0
    },
    {
        "ccms": [],
        "height": 2279,
        "inclusionProof": {
            "bitmap": "01",
            "siblingHashes": [
                "4ed221fb9893b9f27721bef3fea59d996039a9971b6c71409141f12b2f0da712"
            ]
        },
        "outboxSize": 0
    },
    {
        "ccms": [],
        "height": 2280,
        "inclusionProof": {
            "bitmap": "01",
            "siblingHashes": [
                "998e9d0f8135be92528ca0ceebe4a95eb12816a60aede9f6bfa350370f3c1203"
            ]
        },
        "outboxSize": 0
    }
]
----
====


== `chainConnector_getLastSentCCM`

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke chainConnector_getLastSentCCM --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://127.0.0.1:7886/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chainConnector_getLastSentCCM",
    "params": {}
}'
----
--
=====


.Response
[%collapsible]
====
.Example output
[source,json]
----
{
    "error": {
        "message": "No CCM was sent so far."
    }
}
----
====


== `chainConnector_getValidatorsInfoFromPreimage`

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke chainConnector_getValidatorsInfoFromPreimage --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://127.0.0.1:7886/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chainConnector_getValidatorsInfoFromPreimage",
    "params": {}
}'
----
--
=====


.Response
[%collapsible]
====
.Example output
[source,json]
----
[
    {
        "certificateThreshold": "1",
        "validators": [
            {
                "address": "",
                "bftWeight": "1",
                "blsKey": "811e8df1a063f94ad7746350f50956f89397a60c070b80d8c12337c0fc4f40e34635ad55c552324911b0b14c9b07c725"
            }
        ],
        "validatorsHash": "f626be7093592d81cde5bbae150a67db52619e0fd193ee61aebe847c45dd557e"
    }
]
----
====


== `chainConnector_authorize`

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`password`
|string
|Password used to create the encryptedPrivateKey.
|CorrectPassword

|`enable`
|boolean
|Boolean flag that tells whether or not to authorize the Chain Connector plugin.
|true
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke chainConnector_authorize '{"password": "CorrectPassword", "enable":true}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://127.0.0.1:7886/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chainConnector_authorize",
    "params": {
        "password": "CorrectPassword",
        "enable": true
    }
}'
----
--
=====


.Response
[%collapsible]
====
.Example output
[source,json]
----
[

]
----
====