= How to create a module configuration
Mona Bärenfänger <mona@lightcurve.io>
:toc: preamble
:idprefix:
:idseparator: -
:docs_sdk: lisk-sdk::
// URLs
// Project URLS
:url_build_plugin: build-blockchain/create-plugin.adoc

====
On this page, you'll learn how to:

* [x] Define a config schema for a module
* [x] Set a default module config
* [x] Set custom configurations for a module
* [x] Make module configurations accessible inside the command of a module
====

To allow the developer to configure a module in the `config.json` file, create the corresponding configuration schema and pass the values to the module in the `init()` method of the module.

This allows to overwrite the default configurations of a module conveniently by updating the `config.json` file of the Hello client.

== Define a module schema

At first, define a default configuration inside of `module.ts`.
This configuration values will be used, if no custom values are set by the developer in `config.json`.

For the Hello module, we want to provide configuration options for the following values:

. maximum Hello message length
. minimum Hello message length
. List of blacklisted words

Therefore, we define the module default config as follows:

./hello/module.ts
[source,typescript]
----
export const defaultConfig = {
    maxMessageLength: 256,
    minMessageLength: 3,
    blacklist: ["illegalWord1"]
};
----

In our example, we define the following default config:

.Default config values
. maximum Hello message length: 256
. minimum Hello message length: 3
. List of blacklisted words: "illegalWord1"

Once the default config is created, define the corresponding module config interface in `types.ts`:

.hello/types.ts
[source,typescript]
----
import { JSONObject } from 'lisk-sdk';

export interface ModuleConfig {
    maxMessageLength: number;
    minMessageLength: number;
    blacklist: string[];
}

export type ModuleConfigJSON = JSONObject<ModuleConfig>;
----

The config schema is required to validate the module config defined in `config.json`, so add the respective config schema to `schema.ts` as well:

./hello/schema.ts
[source,typescript]
----
export const configSchema = {
    $id: '/hello/config',
    type: 'object',
    properties: {
        maxMessageLength: {
            dataType: 'uint32',
            fieldNumber: 1,
        },
        minMessageLength: {
            dataType: 'uint32',
            fieldNumber: 2,
        },
        blacklist: {
            type: 'array',
            fieldNumber: 3,
            items: {
                dataType: 'string',
                minLength: 1,
                maxLength: 40,
            },
        },
    },
    required: [
        'maxMessageLength',
        'minMessageLength',
        'blacklist'
    ],
};
----

== Use a custom module configuration

Now, open the configuration file and add the config option for the Hello module like this:

.custom_config.json
[source,json]
----
{
  // [...]
  "modules": {
    "hello": {
      "maxMessageLength": 300,
      "minMessageLength": 5,
      "blacklist": ["illegalWord1", "badWord2", "censoredWord3"]
    }
  },
  "plugins": {}
}
----

In the example, we increase the max message length to `300`, the min message length to `5`, and we add two additional words to the blacklist: `badWord2` and `censoredWord3`

== Initialize the module config

To make the custom config that we defined in the previous step <<use-a-custom-module-configuration>> accessible in the module, retieve the config option in the `init()` method like so:

./hello/module.ts
[source,typescript]
----
import {
    BaseModule, BlockAfterExecuteContext, BlockExecuteContext, BlockVerifyContext,
    GenesisBlockExecuteContext, InsertAssetContext, ModuleInitArgs,
    ModuleMetadata, TransactionExecuteContext, TransactionVerifyContext,
    VerificationResult, codec, utils
} from 'lisk-sdk';
import { validator } from '@liskhq/lisk-validator';
import { createHelloSchema, CreateHelloParams, configSchema } from './schema';
import { ModuleConfigJSON } from './types';
// [...]
export const defaultConfig = {
	blacklist: ["illegalWord1"],
	maxMessageLength: 256,
	minMessageLength: 3
};

export class HelloModule extends BaseModule {
    // [...]

    public async init(args: ModuleInitArgs): Promise<void> {
        // Get the module config defined in the config.json file
        const { moduleConfig } = args;
        // Overwrite the default module config with values from config.json, if set
        const config = utils.objects.mergeDeep({}, defaultConfig, moduleConfig) as ModuleConfigJSON;
        // Validate the provided config with the config schema
        validator.validate(configSchema, config);
        // Call the command init() method with config as parameter
        this.commands[0].init(config).catch(err => {
            console.log("Error: ", err);
        });
    }
    // [...]
}
----

The custom config is merged with the default config.
This will overwrite every value of the default config with the value of the custom config, if it is set.
If no value is set in the custom config, it will use the value of the default config.

Once the configs are merged, the module config is validated against the config schema defined in step <<define-a-module-schema>>.

As a last step, the config values are passed to the command by calling the commands' `init()` method, with the config as parameter.

== Use the config values in the command

In the command, create a new method `init()` to update the command blacklist and schema wih the values from the module config.

./hello/command/create_hello_command.ts
[source,typescript]
----
// [...]
export class CreateHelloCommand extends BaseCommand {
    public schema = createHelloSchema;
    // Create private attribute _blacklist
    private _blacklist!: string[];

    // Create init() method for command
    public async init(config: ModuleConfig): Promise<void> {
		// Set _blacklist to the value of the blacklist defined in the module config
		this._blacklist = config.blacklist;
		// Set the max message length to the value defined in the module config
		this.schema.properties.message.maxLength = config.maxMessageLength;
		// Set the min message length to the value defined in the module config
		this.schema.properties.message.minLength = config.minMessageLength;
		console.log("this.schema: ", this.schema);
	}
    // [...]
}
----

== Try the new config out