= How to create a module
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:idprefix:
:idseparator: -
:docs_sdk: lisk-sdk::
// URLs
:url_github_guides_module: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/

// Project URLS
:url_build_blockchain_event: build-blockchain/module/blockchain-event.adoc
:url_build_endpoints_methods: build-blockchain/module/endpoints-methods.adoc
:url_build_init: build-blockchain/create-blockchain-app.adoc
:url_build_config: build-blockchain/module/configuration.adoc
:url_build_stores: build-blockchain/module/stores.adoc
:url_build_setup: build-blockchain/create-blockchain-app.adoc
:url_build_index_helloapp: build-blockchain/index.adoc#the-hello-world-application
:url_build_command: build-blockchain/module/command.adoc
:url_guides_genesis: build-blockchain/create-genesis-block.adoc
:url_guides_testing: build-blockchain/test-app.adoc
:url_intro_modules: understand-blockchain/sdk/modules-commands.adoc
:url_intro_modules_name: {url_intro_modules}#module-name
:url_intro_modules_commands: {url_intro_modules}#commands
:url_intro_modules_endpoints: {url_intro_modules}#endpoints
:url_intro_modules_stores: {url_intro_modules}#stores
:url_intro_modules_methods: {url_intro_modules}#methods
:url_intro_modules_event: {url_intro_modules}#blockchain-events
:url_references_commander: {docs_sdk}references/lisk-commander

How to create a new xref:{url_intro_modules}[module] for a sidechain client.

.Complete application code
[TIP]
====
View the complete sample code of the complete "Hello World" sidechain application on GitHub in the {url_github_guides_module}[Lisk SDK examples repository^].
====

****
As defined on page xref:{url_guides_index_helloapp}[Building blockchain applications with the Lisk SDK], the Hello module shall provide the following functionalities:

. A "Create Hello" command that stores the Hello message for the sender.
** The Hello message has to be of type `string`.
** The Hello message shall have a minimum and maximum length.
** A blacklist of excluded words should exist.
The hello message should be rejected, if it includes one of the words in the blacklist.
. A module config, where the node operator can define:
** maximum message length
** minimum message length
** word blacklist
. A counter, counting the total number of sent Hello messages.
Anyone can request the current value of the Hello counter.
. Emit blockchain event immediately when a new Hello message was sent.
The event includes information about the sender address and the Hello message.
. Two RPC endpoints:
** `hello_getHello`: Returns the Hello message of an account.
Expects account `address` as parameter
** `hello_getHelloCounter`: Returns the counter of total Hello messages sent in the network.
Doesn't expect any parameters.
. One module method:
** `hello_getHello`: Works equally to the corresponding endpoint, but can be used by other modules.
****

== Generating the module file- & folder structure

.Prerequisites
[NOTE]
====
To use this guide, the following criteria is assumed:

* Lisk Commander is installed, and a basic blockchain application is already initialized, as explained in the previous guide xref:{url_build_init}[].
====

While in the root folder of the sidechain client, generate a skeleton for the new module with Lisk Commander.

The command `lisk generate:module` expects one argument:

. The xref:{url_intro_modules_name}[module name].
Needs to be unique within the application.

For a complete overview of all available options of the `generate:module` command, visit the xref:{url_references_commander}[Lisk Commander command reference] or type `generate:module --help`.

As an example, we use the module name `hello`:

[[generate-module]]
[source,bash]
----
lisk generate:module hello
----

This will generate the following file- & folder structure:

.hello/hello_client/src/app/
----
├── bin/
├── config/
├── src/
│    ├── app/
│    │    ├── app.ts
│    │    ├── index.ts
│    │    ├── modules/
│    │    │   └──  hello/ <1>
│    │    │      ├── commands/ <2>
│    │    │      ├── endpoint.ts <3>
│    │    │      ├── events/ <4>
│    │    │      ├── method.ts <5>
│    │    │      ├── module.ts <6>
│    │    │      └── stores/ <7>
│    │    ├── modules.ts
│    │    ├── plugins/
│    │    └── plugins.ts
│    └── commands/
└── test/
    ├── integration/
    ├── network/
    └── unit/
        ├── modules/
        │    └── hello/
        │        └── modules.spec.ts <8>
        └── plugins/
----

<1> The root folder `hello/` for the module is created under `src/app/modules/`.
<2> The `commands/` folder contains the xref:{url_intro_modules_commands}[commands] of the module.
This folder is empty at first.
For more information how to create a command, check out the guide xref:{url_build_command}[].
<3> `endpoint.ts`: Contains the xref:{url_intro_modules_endpoints}[module endpoints].
For more information how to create endpoints for a module, check out the guide xref:{url_build_endpoints_methods}[].
<4> `events/`: Contains the xref:{url_intro_modules_event}[blockchain events] of the module.
This folder is empty at first.
For more information how to create a blockchain event, check out the guide xref:{url_build_blockchain_event}[].
<5> `method.ts`: Contains the xref:{url_intro_modules_methods}[module methods].
For more information how to create module methods, check out the guide xref:{url_build_endpoints_methods}[].
<6> `module.ts`: Registers modules with the sidechain client.
<7> `stores/`: Contains on-chain and off-chain xref:{url_intro_modules_stores}[stores] of the module.
This folder is empty at first.
For more information how to create a module store, check out the guide xref:{url_build_stores}[].
<8> `modules.spec.ts`: Will contain unit tests for the module.
For more information on how to write a unit test for a module, check out the xref:{url_guides_testing}[] guide.

Lisk Commander will also automatically register the module with the application, by adding it to the file `src/app/modules.ts`:

.src/app/modules.ts
[source,typescript]
----
import { Application } from 'lisk-sdk';
import { HelloModule } from "./modules/hello/module";

export const registerModules = (app: Application): void => {
    app.registerModule(new HelloModule());
};
----

Now, let's open the file `hello/module.ts` to take a look at the module skeleton:

== Module class & skeleton

The command `generate:module` already created the class `HelloModule` which contains skeletons for the most important components of the module.

The module class always extends from the `BaseModule`, which is imported from the `lisk-sdk` package.

However, this module is not performing any functions yet.
To give the module a purpose, it is necessary to implement certain logic inside of the module.

The following guides explain how the different components of a module can be used to implement the desired logic for the module.

. xref:{url_build_config}[]
. xref:{url_build_stores}[]
. xref:{url_build_command}[]
. xref:{url_build_endpoints_methods}[]
. xref:{url_build_blockchain_event}[]

.Module skeleton of the Hello module
[%collapsible]
====
.src/app/modules/hello/module.ts
[source,typescript]
----
import {
    BaseModule,
    ModuleInitArgs,
    InsertAssetContext,
	BlockVerifyContext,
	TransactionVerifyContext,
	VerificationResult,
	TransactionExecuteContext,
	GenesisBlockExecuteContext,
	ModuleMetadata,
	BlockExecuteContext,
	BlockAfterExecuteContext,
} from 'lisk-sdk';
import { HelloEndpoint } from './endpoint';
import { HelloMethod } from './method';

export class HelloModule extends BaseModule {
    public endpoint = new HelloEndpoint(this.stores, this.offchainStores);
    public method = new HelloMethod(this.stores, this.events);
    public commands = [];

	public constructor() {
		super();
		// registration of stores and events
	}

	public metadata(): ModuleMetadata {
		return {
			name: '',
			endpoints: [],
			commands: this.commands.map(command => ({
				name: command.name,
				params: command.schema,
			})),
			events: this.events.values().map(v => ({
				name: v.name,
				data: v.schema,
			})),
			assets: [],
		};
	}

    // Lifecycle hooks
    public async init(_args: ModuleInitArgs): Promise<void> {
		// initialize this module when starting a node
	}

	public async insertAssets(_context: InsertAssetContext) {
		// initialize block generation, add asset
	}

	public async verifyAssets(_context: BlockVerifyContext): Promise<void> {
		// verify block
	}

    // Lifecycle hooks
	public async verifyTransaction(_context: TransactionVerifyContext): Promise<VerificationResult> {
		// verify transaction will be called multiple times in the transaction pool
	}

	public async beforeCommandExecute(_context: TransactionExecuteContext): Promise<void> {
	}

	public async afterCommandExecute(_context: TransactionExecuteContext): Promise<void> {

	}
	public async initGenesisState(_context: GenesisBlockExecuteContext): Promise<void> {

	}

	public async finalizeGenesisState(_context: GenesisBlockExecuteContext): Promise<void> {

	}

	public async beforeTransactionsExecute(_context: BlockExecuteContext): Promise<void> {

	}

	public async afterTransactionsExecute(_context: BlockAfterExecuteContext): Promise<void> {

	}
}
----
====