= Lisk client
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references regarding the Clients packages of Lisk Elements. This consists of references to all included sub-packages and general usage instructions.
:toc:
:url_elements_api: reference/lisk-elements/packages/api-client.adoc
:url_elements_constants: reference/lisk-elements/packages/constants.adoc
:url_elements_cryptography: reference/lisk-elements/packages/cryptography.adoc
:url_elements_passphrase: reference/lisk-elements/packages/passphrase.adoc
:url_elements_transactions: reference/lisk-elements/packages/transactions.adoc

This provides a default set of Elements for use by clients of the Lisk network.

[NOTE]
====
The `Client` package is a collection of the following packages:

xref:{url_elements_api}[api-client], xref:{url_elements_constants}[constants],
xref:{url_elements_cryptography}[cryptography], xref:{url_elements_passphrase}[passphrase],
xref:{url_elements_transactions}[transactions]
====

Lisk Elements will include numerous different packages in the future which can be plugged in to applications as desired.

For enhanced usability Lisk Elements provides special wrapper packages such as `lisk-client`, whose group packages are often used in the same context.

== Installation

To add Lisk Client as a dependency of your project execute the following command:

[source,bash]
----
$ npm install @liskhq/lisk-client
----

== Upgrade

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @liskhq/lisk-client
----

== Usage

Import using ES6 modules syntax:

[source,js]
----
import lisk from '@liskhq/lisk-client';
----

Or using Node.js modules:

[source,js]
----
const lisk = require('@liskhq/lisk-client');
----

Or import specific namespaced functionality:

[source,js]
----
import { APIClient, transactions } from '@liskhq/lisk-client';
// or
const { APIClient, transactions } = require('@liskhq/lisk-client');
----
