= Transactions
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references regarding the Transactions packages of Lisk Elements. This consists of usage examples, available options and example responses.
:toc:

The Lisk Elements transactions module provides functions for creating transactions of every type, including a set of utility functions.

== Installation

[source,bash]
----
$ npm install @liskhq/lisk-transactions
----

== Upgrade

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @liskhq/lisk-transactions
----

== Constants

Transactions-specific constants are available via the `transaction` key, and include relevant fees and byte allocations for transaction components.

=== Usage

[source,js]
----
import * as transactions from '@liskhq/lisk-transactions';

transactions.constants.FIXED_POINT; <1>

transactions.constants.TRANSFER_FEE; <2>
transactions.constants.SIGNATURE_FEE; <3>
transactions.constants.DELEGATE_FEE; <4>
transactions.constants.VOTE_FEE; <5>
transactions.constants.MULTISIGNATURE_FEE; <6>

transactions.constants.MULTISIGNATURE_MAX_LIFETIME; <7>
transactions.constants.MULTISIGNATURE_MIN_LIFETIME; <8>
transactions.constants.MULTISIGNATURE_MAX_KEYSGROUP; <9>
transactions.constants.MULTISIGNATURE_MIN_KEYSGROUP; <10>

transactions.constants.USERNAME_MAX_LENGTH; <11>
transactions.constants.BYTESIZES; <12>

transactions.constants.EPOCH_TIME; <13>
transactions.constants.EPOCH_TIME_MILLISECONDS; <14>
transactions.constants.EPOCH_TIME_SECONDS; <15>

transactions.constants.MAX_ADDRESS_NUMBER; <16>
transactions.constants.MAX_TRANSACTION_AMOUNT; <17>
transactions.constants.MAX_TRANSACTION_ID; <18>
----

<1> Number to use when converting between the smallest possible denomination and 1 LSK.
<2> Fee required for a transfer (type 0) transaction.
<3> Fee required for a register second passphrase (type 1) transaction.
<4> Fee required for a register delegate (type 2) transaction.
<5> Fee required for a cast votes (type 3) transaction.
<6> Fee required per group member (plus one) for a register multisignature account (type 4) transaction.
<7> Maximum lifetime in transaction pool of a multi-signature transaction in hours.
<8> Minimum lifetime in transaction pool of a multi-signature transaction in hours.
<9> Maximum number of public keys that can be part of a multi-signature group.
<10> Minimum number of public keys that can be part of a multi-signature group.
<11> Maximum number of characters allowed for a username.
<12> Object containing the number of bytes to allocate for each component of a transaction.
<13> Date from which timestamps are calculated.
<14> EPOCH_TIME in milliseconds since Unix Epoch.
<15> EPOCH_TIME in seconds since Unix Epoch.
<16> Maximum valid number which can form an address when suffixed with an 'L'.
<17> Maximum valid amount for a transaction.
Maximum value for PostgreSQL bigint.
<18> Maximum valid number for transaction IDs.

== Methods for creating transactions

=== Type 0: `transfer`

This creates a transfer (type 0) transaction.

==== Syntax

[source,js]
----
transfer(options)
----

==== Parameters

`options`: Options to be used when creating the transaction:

* `amount`: The amount to transfer, (as a `string` in Beddows, the lowest denomination possible).
* `networkIdentifier`: The ID of the network where the transaction will be broadcasted to.
* `recipientId`: The address of the recipient.
* `data`: Optional data to include in the transaction asset.
(Must be a UTF8-encoded string of maximum 64 characters.)
* `passphrase`: Optional passphrase to use to sign the transaction.
If not provided at creation the transaction can be signed later.
* `secondPassphrase`: Optional second passphrase to use to sign the transaction if the account has registered a second passphrase.
If not provided at the creation, the transaction can be signed with the second passphrase later.

==== Return value

`object`: The created transaction object.

=== Type 1: `registerSecondPassphrase`

This creates a register second passphrase, (type 1) transaction.

==== Syntax

[source,js]
----
registerSecondPassphrase(options)
----

==== Parameters

`options`: Options to be used when creating the transaction:
* `secondPassphrase`: The second passphrase to register.
* `passphrase`: Optional passphrase used to sign the transaction.
* `networkIdentifier`: The ID of the network where the transaction will be broadcasted to.
If not provided at the creation, the transaction can be signed later.

==== Return value

`object`: The created transaction object.

=== Type 2: `registerDelegate`

This creates a register delegate (type 2) transaction.

==== Syntax

[source,js]
----
registerDelegate(options)
----

==== Parameters

`options`: Options to be used when creating the transaction:

* `username`: The delegate username to register.
* `networkIdentifier`: The ID of the network where the transaction will be broadcasted to.
* `passphrase`: Optional passphrase to use to sign the transaction.
If not provided at the creation, the transaction can be signed later.
* `secondPassphrase`: Optional second passphrase used to sign the transaction if the account has registered a second passphrase.
If not provided at the creation, the transaction can be signed with the second passphrase later.

==== Return value

`object`: The created transaction object.

=== Type 3: `castVotes`

This creates a cast votes (type 3) transaction.

==== Syntax

[source,js]
----
castVotes(options)
----

==== Parameters

`options`: Options to be used when creating the transaction:

* `votes`: The public keys of the delegates to vote for.
* `unvotes`: The public keys of the delegates from whom you want to remove your vote.
* `networkIdentifier`: The ID of the network where the transaction will be broadcasted to.
* `passphrase`: Optional passphrase used to sign the transaction.
If not provided at the creation, the transaction can be signed later.
* `secondPassphrase`: Optional second passphrase used to sign the transaction if the account has registered a second passphrase.
If not provided at the creation, the transaction can be signed with the second passphrase later.

==== Return value

`object`: The created transaction object.

=== Type 4: `registerMultisignature`

This creates a register multisignature account (type 4) transaction.

==== Syntax

[source,js]
----
registerMultisignature(options)
----

==== Parameters

`options`: Options to be used when creating the transaction:

* `keysgroup`: An array of public keys which should form part of the multisignature group.
* `lifetime`: The time to wait for enough signatures before a transaction becomes invalid.
* `minimum`: The minimum number of signatures required to authorise a transaction.
* `networkIdentifier`: The ID of the network where the transaction will be broadcasted to.
* `passphrase`: Optional passphrase used to sign the transaction.
If not provided at the creation, the transaction can be signed later.
* `secondPassphrase`: Optional second passphrase used to sign the transaction if the account has registered a second passphrase.
If not provided at the creation, the transaction can be signed with the second passphrase later.

==== Return value

`object`: The created transaction object.

== Methods for creating signature objects

=== createSignatureObject

This creates a signature object for a transaction from a multisignature account.

==== Syntax

[source,js]
----
createSignatureObject(transaction, passphrase)
----

==== Parameters

* `transaction`: The multisignature transaction to sign.
* `passphrase`: Passphrase used to sign the transaction.
* `networkIdentifier`: The ID of the network where the transaction will be broadcasted to.

==== Return value

`object`: The signature object which can be broadcast to the network.
Contains `transactionId`, `publicKey` and `signature` hex ``string``s.

== Utility methods

=== convertBeddowsToLSK

This converts amounts in Beddows, (the smallest denomination) to the amounts in one LSK.

==== Syntax

[source,js]
----
convertBeddowsToLSK(amount)
----

==== Parameters

`amount`: `string` decimal representation of amount to be converted.

==== Return value

`string`: Amount in LSK.

==== Examples

[source,js]
----
transactions.utils.convertBeddowsToLSK('100000'); // '0.001'
----

=== convertLSKToBeddows

This converts the amounts in LSK to the amounts in Beddows, (the smallest denomination).

==== Syntax

[source,js]
----
convertLSKToBeddows(amount)
----

==== Parameters

`amount`: `string` decimal representation of amount to be converted.

==== Return value

`string`: Amount in Beddows.

==== Examples

[source,js]
----
transactions.utils.convertLSKToBeddows('0.001'); // '100000'
----

=== getTransactionBytes

This returns a byte array representation of a transaction object.

==== Syntax

[source,js]
----
getTransactionBytes(transaction)
----

==== Parameters

`transaction`: `object` representation of a transaction.

==== Return value

`buffer`: Byte array representation of the transaction

=== getTransactionId

Returns a transaction ID for a transaction.

==== Syntax

[source,js]
----
getTransactionId(transaction)
----

==== Parameters

`transaction`: The transaction whose ID is required.

==== Return value

`string`: The transaction ID.

=== multiSignTransaction

This signs a transaction from a multisignature account using a passphrase.

==== Syntax

[source,js]
----
multiSignTransaction(transaction, passphrase)
----

==== Parameters

* `transaction`: The multisignature transaction to sign.
* `passphrase`: The passphrase to use to sign the transaction.
* `networkIdentifier`: The ID of the network where the transaction will be broadcasted to.

==== Return value

`string`: The signature.

=== signTransaction

Signs a transaction using a passphrase.

==== Syntax

[source,js]
----
signTransaction(transaction, passphrase)
----

==== Parameters

* `transaction`: The transaction to sign.
* `passphrase`: The passphrase used to sign the transaction.

==== Return value

`string`: The signature.

=== validateAddress

Validates a Lisk address.

==== Syntax

[source,js]
----
validateAddress(address)
----

==== Parameters

`address`: The Lisk address to validate.

==== Return value

`boolean`: `true` if the address is valid, otherwise an error will
be thrown.

==== Examples

[source,js]
----
transactions.utils.validateAddress('12981844261447786907L'); // true
----

=== validateKeysgroup

Validates a keysgroup for a multisignature account.

==== Syntax

[source,js]
----
validateKeysgroup(keysgroup)
----

==== Parameters

`keysgroup`: The keysgroup to validate.

==== Return value

`boolean`: `true` if the keysgroup is an array of public keys whereby are all valid, contain no duplicates, and that are of a valid length.
Otherwise an error will be thrown.

==== Examples

[source,js]
----
transactions.utils.validateKeysgroup([]); // Throws 'Expected between 1 and 16 public keys in the keysgroup.'
----

=== validatePublicKey

Validates a public key.

==== Syntax

[source,js]
----
validatePublicKey(publicKey)
----

==== Parameters

`publicKey`: The public key to validate.

==== Return value

`boolean`: `true` if the public key is valid, otherwise an error will be thrown.

==== Examples

[source,js]
----
transactions.utils.validatePublicKey('0b68c5d745d47998768a14b92b221ded2292e21b62846f8f968fdbcd9b52ae4d'); // true
----

=== validatePublicKeys

Validates an array of public keys.

==== Syntax

[source,js]
----
validatePublicKeys(publicKeys)
----

==== Parameters

`publicKeys`: The public keys to validate.

==== Return value

`boolean`: `true` if the public keys are all valid and there are no duplicates, otherwise an error will be thrown.

==== Examples

[source,js]
----
transactions.utils.validatePublicKeys([
    '0b68c5d745d47998768a14b92b221ded2292e21b62846f8f968fdbcd9b52ae4d',
    '0b68c5d745d47998768a14b92b221ded2292e21b62846f8f968fdbcd9b52ae4d'
]); // Throws 'Error: Duplicated public key: 0b68c5d745d47998768a14b92b221ded2292e21b62846f8f968fdbcd9b52ae4d.'
----

=== `validateTransaction`

Checks whether the input transaction object has valid schema or not.

==== Syntax

[source,js]
----
validateTransaction(transaction)
----

==== Parameters

`transaction`: The transaction to validate.

==== Return value

....
{
  valid: boolean,
  errors: [{
    dataPath: string,
    message: string
  }]
}
....

where `boolean`: `true` if the transaction object, (without signature) is valid, `false` if not.

=== verifyTransaction

Verifies the signature, (and optionally the second signature) for a passphrase.

==== Syntax

[source,js]
----
verifyTransaction(transaction, [secondPublicKey])
----

==== Parameters

`transaction`: The transaction to verify.

`secondPublicKey`: The second public key to check if the transaction has a second signature which should be verified.

==== Return value

`boolean`: `true` if the signature is valid, `false` if not.
