= Broadcast a transaction
Mona Bärenfänger <mona@lightcurve.io>
:toc:

This guide explains, how to create a transaction object of a specific transaction type, and how to broadcadt it to the network.

[[create]]
== Create the transaction object

[tabs]
=====
Default transaction::
+
--

Ensure, that Node.JS is the latest LTS (version 12 or higher) and create a Node.JS project by creating a `package.json` file inside of your current folder.

.Install dependencies
[source,bash]
----
node --version
v12.15.0
npm init --yes
npm i @liskhq/lisk-transactions
npm i @liskhq/lisk-constants
npm i @liskhq/lisk-cryptography
----

.Create tx object with Lisk Elements
[source,js]
----
const transactions = require('@liskhq/lisk-transactions');
const {getNetworkIdentifier} = require('@liskhq/lisk-cryptography');

const networkIdentifier = getNetworkIdentifier(
    "23ce0366ef0a14a91e5fd4b1591fc880ffbef9d988ff8bebf8f3666b0c09597d",
    "Lisk",
);

let tx = new transactions.TransferTransaction({
        asset: {
            amount: '1',
            recipientId: '1L',
        },
        networkIdentifier: networkIdentifier,
    });

console.log(tx.stringify());
----

.Example Output
[source,json]
----
{
   "type":8,
   "timestamp":0,
   "senderPublicKey":"",
   "senderId":"",
   "fee":"10000000",
   "signatures":[

   ],
   "asset":{
      "amount":"1",
      "recipientId":"1L"
   }
}
----
--
Custom Transaction::
+
--
.Create custom tx object with Lisk Elements
[source,js]
----
const HelloTransaction = require('../hello_transaction');
const { EPOCH_TIME } = require('@liskhq/lisk-constants');
const {getNetworkIdentifier} = require('@liskhq/lisk-cryptography');

const networkIdentifier = getNetworkIdentifier(
    "23ce0366ef0a14a91e5fd4b1591fc880ffbef9d988ff8bebf8f3666b0c09597d",
    "Lisk",
);

const getTimestamp = () => {
    // check config file or curl localhost:4000/api/node/constants to verify your epoc time
    const millisSinceEpoc = Date.now() - Date.parse(EPOCH_TIME);
    const inSeconds = ((millisSinceEpoc) / 1000).toFixed(0);
    return  parseInt(inSeconds);
}

const tx = new HelloTransaction({ <1>
    asset: {
        hello: 'world', <2>
    },
    networkIdentifier: networkIdentifier, <3>
    timestamp: getTimestamp(),
});

tx.sign('wagon stock borrow episode laundry kitten salute link globe zero feed marble');

console.log(tx.stringify()); <4>
process.exit(0); <5>
----
--
=====

[[sign]]
== Sign the transaction
[tabs]
=====
Default transaction::
+
--
.Sign tx object with Lisk Elements
[source,js]
----
const transactions = require('@liskhq/lisk-transactions');
const {getNetworkIdentifier} = require('@liskhq/lisk-cryptography');

const networkIdentifier = getNetworkIdentifier(
    "23ce0366ef0a14a91e5fd4b1591fc880ffbef9d988ff8bebf8f3666b0c09597d",
    "Lisk",
);

let tx = new transactions.TransferTransaction({
        asset: {
            amount: '1',
            recipientId: '1L',
        },
        networkIdentifier: networkIdentifier,
    });

tx.sign('creek own stem final gate scrub live shallow stage host concert they'); // Genesis account with address: 11237980039345381032L

console.log(tx.stringify());
----

.Example Output
[source,json]
----
{
   "id":"14444765956109766257",
   "type":8,
   "timestamp":0,
   "senderPublicKey":"5c554d43301786aec29a09b13b485176e81d1532347a351aeafe018c199fd7ca",
   "senderId":"11237980039345381032L",
   "fee":"10000000",
   "signature":"49d5824b9008b2005a554d984dedf8986b8bb54328dc5bf4c6a61fcdca6115a5ac0e17b5ec4c24bdaaae4f3be2cf808f514d2b74c506c6df9fcfcfad1caaa702",
   "signatures":[

   ],
   "asset":{
      "amount":"1",
      "recipientId":"1L"
   }
}
----

--
Custom Transaction::
+
--
.Create custom tx object with Lisk Elements
[source,js]
----
const HelloTransaction = require('../hello_transaction');
const { EPOCH_TIME } = require('@liskhq/lisk-constants');
const {getNetworkIdentifier} = require('@liskhq/lisk-cryptography');

const networkIdentifier = getNetworkIdentifier(
    "23ce0366ef0a14a91e5fd4b1591fc880ffbef9d988ff8bebf8f3666b0c09597d",
    "Lisk",
);

const getTimestamp = () => {
    // check config file or curl localhost:4000/api/node/constants to verify your epoc time
    const millisSinceEpoc = Date.now() - Date.parse(EPOCH_TIME);
    const inSeconds = ((millisSinceEpoc) / 1000).toFixed(0);
    return  parseInt(inSeconds);
}

const tx = new HelloTransaction({ <1>
    asset: {
        hello: 'world', <2>
    },
    networkIdentifier: networkIdentifier, <3>
    timestamp: getTimestamp(),
});

tx.sign('wagon stock borrow episode laundry kitten salute link globe zero feed marble');

console.log(tx.stringify()); <4>
process.exit(0); <5>
----
--
=====

[[post]]
== Post the transaction to the network
[tabs]
=====
Default transaction::
+
--
.Create tx object with Lisk Elements
[source,js]
----
const transactions = require('@liskhq/lisk-transactions'); <1>
const { EPOCH_TIME } = require('@liskhq/lisk-constants');
const {getNetworkIdentifier} = require('@liskhq/lisk-cryptography');

const networkIdentifier = getNetworkIdentifier(
    "23ce0366ef0a14a91e5fd4b1591fc880ffbef9d988ff8bebf8f3666b0c09597d", <2>
    "Lisk", <3>
);

const getTimestamp = () => {
    // check config file or curl localhost:4000/api/node/constants to verify your epoc time
    const millisSinceEpoc = Date.now() - Date.parse(EPOCH_TIME);
    const inSeconds = ((millisSinceEpoc) / 1000).toFixed(0);
    return  parseInt(inSeconds);
}

let tx = new transactions.TransferTransaction({
        asset: {
            amount: '1',
            recipientId: packetCredentials.address,
        },
        networkIdentifier: networkIdentifier,
    });

    tx.sign('creek own stem final gate scrub live shallow stage host concert they'); // Genesis account with address: 11237980039345381032L
    res.render('initialize', { packetCredentials });

    api.transactions.broadcast(tx.toJSON()).then(res => {
        console.log("++++++++++++++++ API Response +++++++++++++++++");
        console.log(res.data);
        console.log("++++++++++++++++ Credentials +++++++++++++++++");
        console.dir(packetCredentials);
        console.log("++++++++++++++++ Transaction Payload +++++++++++++++++");
        console.log(tx.stringify());
        console.log("++++++++++++++++ End Script +++++++++++++++++");
    }).catch(err => {
        console.log(JSON.stringify(err.errors, null, 2));
    });

console.log(tx.stringify()); <4>
process.exit(0); <5>
----

--
Custom Transaction::
+
--
.Create custom tx object with Lisk Elements
[source,js]
----
const HelloTransaction = require('../hello_transaction');
const { EPOCH_TIME } = require('@liskhq/lisk-constants');
const {getNetworkIdentifier} = require('@liskhq/lisk-cryptography');

const networkIdentifier = getNetworkIdentifier(
    "23ce0366ef0a14a91e5fd4b1591fc880ffbef9d988ff8bebf8f3666b0c09597d",
    "Lisk",
);

const getTimestamp = () => {
    // check config file or curl localhost:4000/api/node/constants to verify your epoc time
    const millisSinceEpoc = Date.now() - Date.parse(EPOCH_TIME);
    const inSeconds = ((millisSinceEpoc) / 1000).toFixed(0);
    return  parseInt(inSeconds);
}

const tx = new HelloTransaction({ <1>
    asset: {
        hello: 'world', <2>
    },
    networkIdentifier: networkIdentifier, <3>
    timestamp: getTimestamp(),
});

tx.sign('wagon stock borrow episode laundry kitten salute link globe zero feed marble');

console.log(tx.stringify()); <4>
process.exit(0); <5>
----
--
=====

== What happen to the transaction now?

The transaction will be validated by the node, and added to the transaction pool, if valid.
The node will also inform it's peer nodes about the new transaction, so all of them will valide the transaction and add it to their transaction pool.
If the transaction is added to the transaction pool of a forging node, the transaction will be included in one of the next new blocks.
Once the transaction is included into a block, it becomes part of the blockchain.
To be sure, the transaction is final, it is recommended to wait around XXXX blocks.
