= Guides
Mona Bärenfänger <mona@lightcurve.io>
:description:
:toc:
:url_github_hello: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/hello_world

:url_config: guides/configuration.adoc
:url_custom: guides/customize.adoc
:url_frontend: guides/frontend.adoc
:url_launch: guides/launch.adoc


This section consists of concise, goal-oriented how-to guides, that are designed in a manner to help the user to solve specific issues.

The guides are listed in a chronological order, taking you through the basic steps of developing a blockchain application with the Lisk SDK.

As example, the guides use the {url_github_hello}[Hello World] app, which is a very basic blockchain application with one custom transaction type and a simple frontend.

The most important steps are in this regard:

. The xref:{url_config}[configuration guide] covers how to configure a blockchain application and how to modify the default values.
. The xref:{url_custom}[custom transactions guide] provides the necessary criteria for adding and registering a custom transaction.
. In xref:{url_frontend}[connect a frontend] to the blockchain.
. Finally, the xref:{url_launch}[Launch the app] guide describes the steps needed to move from a local Devnet to a public blockchain network.

