= Hello World
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc:
:imagesdir: ../../assets/images
:experimental:
// External URLs
:url_github_hello: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/hello_world

In the Hello World tutorial, you learn how to create a simple blockchain application including a basic frontend.
It describes all important steps that are required to build a blockchain application with the Lisk SDK.
The Hello World app is also a good entry point to start from and extend the app further for your own use case.

TIP: For the *full code example* please see {url_github_hello}[Hello World App on Github^].

== Blockchain application

Showcases a minimal setup of a blockchain application which includes the following:

.lisk-sdk-examples/hello_world/blockchain_app
[source]
----
├── blockchain_app
│   ├── genesis-block.json
│   ├── hello_module
│   │   ├── hello_module.js <1>
│   │   ├── hello_asset.js <2>
│   │   ├── index.js
│   │   └── schemas.js
│   ├── hello_plugin <3>
│   │   └── index.js
│   ├── index.js
│   └── package.json
----

<1> A custom module, which is containing the on-chain logic related to the `hello` property .
<2> A custom asset, which is handling the logic for the hello transaction inside the `hello_module`.
<3> A custom module, which is providing additional API endpoints related to the `hello_module`.

== Client application

A simple react frontend to complement the Hello World blockchain application.
Allows to create and fund new accounts, to transfer tokens, send hello transactions, and shows account details.

.lisk-sdk-examples/hello_world/react-client
[source]
----
└── react-client
    ├── README.md
    ├── package.json
    ├── src
    │   ├── accounts.json
    │   ├── api.js <1>
    │   ├── components <2>
    │   │   ├── Account.js
    │   │   ├── App.js
    │   │   ├── Faucet.js
    │   │   ├── Hello.js
    │   │   ├── NewAccount.js
    │   │   ├── Transfer.js
    │   │   └── home.js
    │   ├── index.html
    │   ├── index.js
    │   ├── transactions <3>
    │   │   ├── create_hello_tx.js
    │   │   └── transfer.js
    │   └── utils.js
    └── webpack.config.js
----

<1> Exports various functions to get data from the API
<2> Contains the different react components for the different pages of the Hello World application.
<3> Exports functions to create the different transactions types that are used in the frontend.

== Setup

=== Setup of the blockchain application

To set up the Hello World app, first install the xref:{url_setup}[prerequisites], then clone the repository and navigate into it as shown below:

.In the terminal
[source,bash]
----
git clone https://github.com/LiskHQ/lisk-sdk-examples.git
cd lisk-sdk-examples/hello_world/blockchain_app
----

Now install all required node modules for the node application by executing the following command below:

.lisk-sdk-examples/hello_world/blockchain_app
[source,bash]
----
npm install
----

The next step is to spin up the devnet node by executing the following command:

[source,bash]
----
node index.js
----

If the setup was successful, it will be possible to view the logs of the node in the terminal.

=== Setup of the client application

Now, navigate into the `react-client` folder and start the frontend application:

[source,bash]
----
cd ../react-client
npm install
----

Now start the client:

[source,bash]
----
npm start
----

This will open the react client in a new browser window.

With the blockchain application and the react client both running on your local machine, it is possible to utilize the frontend to verify the Hello World application was installed successfully and that it works as expected.

== The Hello World app

=== Home page

=== Creating a new account

=== The faucet

=== Get account details

=== Transferring tokens

=== Sending a Hello transaction
