= Tutorials overview
Mona Bärenfänger <mona@lightcurve.io>
:description: The SDK Tutorials overview gives a summary of all available tutorials, including the complexity, estimated time required, and the content.
:toc:
:page-aliases: tutorials/cashback.adoc

:url_hello: tutorials/hello-world.adoc
:url_nft: tutorials/nft.adoc

To become both familiar and fully conversant with the Lisk SDK, a step-by-step walk through guide is provided that simplifies the process of developing a proof of concept blockchain application.

[cols="25,5,10,60",options="header",stripes="hover"]
|===
|Name
|Estimated time required
|Complexity
|Content

| xref:{url_hello}[]
|~1 h
|Beginner
a|
Learn how to:

* ...setup a simple blockchain application
* ...create a custom module
* ...create a custom plugin
* ...create a simple client for the blockchain application

| xref:{url_nft}[]
|~3 h
|Beginner
a|
Learn how to create:

* ...a blockchain application which allows to create, transfer and purchase NFTs.
* ...3 different transaction asset to create, transfer and purchase NFTs.
* ...a custom plugin which adds a new HTTP API that serves NFT-related data to the application.
* ...a frontend application, which allows to use the blockchain application in the browser.
|===
