= Tutorials overview
Mona Bärenfänger <mona@lightcurve.io>
:description: The SDK Tutorials overview gives a summary of all available tutorials, including the complexity, estimated time required, and the content.
:toc:
:page-aliases: tutorials/cashback.adoc

:url_hello: tutorials/hello-world.adoc
:url_nft: tutorials/nft.adoc
:url_srs: tutorials/srs.adoc

To become both familiar and fully conversant with the Lisk SDK, a step-by-step walk through guide is provided that simplifies the process of developing a proof of concept blockchain application.

[cols="15,10,15,60",options="header",stripes="hover"]
|===
|Name
|Estimated time required
|Complexity
|Content

| xref:{url_hello}[]
|~1 h
|Beginner
a|
Learn how to:

* ...setup a simple blockchain application
* ...create a custom module
* ...create a custom plugin
* ...create a simple client for the blockchain application

| xref:{url_nft}[]
|~3 h
|Beginner
a|
Learn how to create:

* ...a blockchain application that allows a user to create, transfer and purchase NFTs.
* ...3 different transaction assets to create, transfer and purchase NFTs.
* ...a custom plugin which adds a new HTTP API that serves NFT-related data to the application.
* ...a frontend application that allows the user to utilize the blockchain application in the browser.

| xref:{url_srs}[]
|~4 h
|Intermediate
a|
Learn how to create:

* ...a blockchain application that offers users the opportunity to recover their accounts if they have lost their credentials through a social recovery system.
* ...6 different transaction assets to manage the recovery process.
* ...2 custom plugins that provide new actions and API endpoints which are helpful in the frontend.
* ...a frontend application that allows the user to utilize the blockchain application in the browser.

|===
