= Auth module: Endpoint reference
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc: preamble

== `auth_getAuthAccount`
This function checks whether the account corresponding to the input address has registered a multisignature.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address to query.
|lsk24cd35u4jdq8szo3pn
sqe5dsxwrnazyqqqg5eu
|===

--
Node CLI::
+
--
[source,bash]
----
lisk-core endoint:invoke auth_getAuthAccount '{ "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "auth_getAuthAccount",
    "params": {
         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "nonce": "0",
  "numberOfSignatures": 0,
  "mandatoryKeys": [],
  "optionalKeys": []
}
----
====


== `auth_isValidSignature`
This function checks whether the account corresponding to the input address has registered a multisignature.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address to query.
|lsk24cd35u4jdq8szo3pn
sqe5dsxwrnazyqqqg5eu
|===

--
Node CLI::
+
--
[source,bash]
----
lisk-core endoint:invoke auth_getAuthAccount '{ "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "auth_getAuthAccount",
    "params": {
         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "nonce": "0",
  "numberOfSignatures": 0,
  "mandatoryKeys": [],
  "optionalKeys": []
}
----
====


== `auth_isValidNonce`
This function checks whether the account corresponding to the input address has registered a multisignature.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address to query.
|lsk24cd35u4jdq8szo3pn
sqe5dsxwrnazyqqqg5eu
|===

--
Node CLI::
+
--
[source,bash]
----
lisk-core endoint:invoke auth_getAuthAccount '{ "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "auth_getAuthAccount",
    "params": {
         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "nonce": "0",
  "numberOfSignatures": 0,
  "mandatoryKeys": [],
  "optionalKeys": []
}
----
====


== `auth_getMultiSigRegMsgSchema`
This function checks whether the account corresponding to the input address has registered a multisignature.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address to query.
|lsk24cd35u4jdq8szo3pn
sqe5dsxwrnazyqqqg5eu
|===

--
Node CLI::
+
--
[source,bash]
----
lisk-core endoint:invoke auth_getAuthAccount '{ "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "auth_getAuthAccount",
    "params": {
         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "nonce": "0",
  "numberOfSignatures": 0,
  "mandatoryKeys": [],
  "optionalKeys": []
}
----
====


== `auth_sortMultisignatureGroup`
This function checks whether the account corresponding to the input address has registered a multisignature.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address to query.
|lsk24cd35u4jdq8szo3pn
sqe5dsxwrnazyqqqg5eu
|===

--
Node CLI::
+
--
[source,bash]
----
lisk-core endoint:invoke auth_getAuthAccount '{ "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "auth_getAuthAccount",
    "params": {
         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "nonce": "0",
  "numberOfSignatures": 0,
  "mandatoryKeys": [],
  "optionalKeys": []
}
----
====


== `auth_getMultiSigRegMsgTag`
This function checks whether the account corresponding to the input address has registered a multisignature.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address to query.
|lsk24cd35u4jdq8szo3pn
sqe5dsxwrnazyqqqg5eu
|===

--
Node CLI::
+
--
[source,bash]
----
lisk-core endoint:invoke auth_getAuthAccount '{ "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "auth_getAuthAccount",
    "params": {
         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "nonce": "0",
  "numberOfSignatures": 0,
  "mandatoryKeys": [],
  "optionalKeys": []
}
----
====

