= Dynamic Reward module: Endpoint reference
Muhammad Talha <muhammad.talha@lightcurve.io>
// Settings
:toc: preamble
//URLs
:url_typedoc_reward: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.RewardModule.html

:url_dynamic_reward: https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/modules/dynamic_rewards/endpoint.ts

//Project URLs
:url_integrate_endpoints: integrate-blockchain/connecting-endpoints.adoc
// :url_command_fee: understand-blockchain/blocks-txs.adoc#command-fee

//TODO: Add a hyperlink for Dynamic Rewards
This page summarizes all API endpoints specific to the {url_dynamic_reward}[Dynamic Reward^] and the {url_typedoc_reward}[Reward module^].

The `DynamicReward` endpoint class inherits all the endpoints from the `Reward` module as well.
All the aforementioned endpoints are invoked using the `dynamicReward` prefix.

TIP: Endpoints can be invoked as explained in the xref:{url_integrate_endpoints}[] guide.


== `dynamicReward_getExpectedValidatorRewards`
Returns expected rewards from the `DynamicReward` module for the given validator.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`validatorAddress`
|string
|The Lisk32 address of a validator.
|lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke dynamicReward_getExpectedValidatorRewards '{"validatorAddress":"lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location '127.0.0.1:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "dynamicReward_getExpectedValidatorRewards",
    "params": {
         "validatorAddress": "lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "blockReward": "513775510",
  "dailyReward": "43097270400",
  "monthlyReward": "1292918112000",
  "yearlyReward": "15730503696000"
}
----
====

== `dynamicReward_getDefaultRewardAtHeight`
Returns default reward from the `Reward` module based on the given height.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`height`
|integer
|Height of a block in the blockchain.
|102
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke dynamicReward_getDefaultRewardAtHeight '{"height":102}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location '127.0.0.1:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "dynamicReward_getDefaultRewardAtHeight",
    "params": {
         "height": 102
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "reward": "0"
}
----
====



== `dynamicReward_getRewardTokenID`

Returns reward token ID from the `Reward` module based on the given height.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`height`
|integer
|Height of a block in the blockchain.
|102
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke dynamicReward_getRewardTokenID '{"height":102}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location '127.0.0.1:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "dynamicReward_getRewardTokenID",
    "params": {
         "height": 102
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "tokenID": "0400000000000000"
}
----
====



== `dynamicReward_getAnnualInflation`

Returns annual inflation details from the `Reward` module based on the given height.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`height`
|integer
|Height of a block in the blockchain.
|102
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke dynamicReward_getAnnualInflation '{"height":102}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location '127.0.0.1:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "dynamicReward_getAnnualInflation",
    "params": {
         "height": 102
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "tokenID": "0400000000000000",
  "rate": "0"
}
----
====