= Interoperability module: Endpoint reference
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc: preamble
//URLs
:url_typedoc_interopmc: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.SidechainInteroperabilityModule.html
//Project URLs
:url_integrate_endpoints: integrate-blockchain/connecting-endpoints.adoc
:url_command_fee: understand-blockchain/blocks-txs.adoc#command-fee

This page summarizes all API endpoints *specific to* the {url_typedoc_interopmc}[Sidechain Interoperability module^].

TIP: Endpoints can be invoked as explained in the xref:{url_integrate_endpoints}[] guide.

== `interoperability_getChainAccount`
Returns the chain account of a specified blockchain.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`chainID`
|string
|The chain ID of a blockchain.
|00000001
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke interoperability_getChainAccount '{ "chainID": "00000001" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getChainAccount",
    "params": {"chainID": "00000001"}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
    "id": "1",
    "jsonrpc": "2.0",
    "result": {
        "lastCertificate": {
            "height": 0,
            "timestamp": 0,
            "stateRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            "validatorsHash": "58fa1be3fca7aef9952a7640397124229837079b14a144907a7e3373685daceb"
        },
        "name": "sidechain1",
        "status": 0
    }
}
----
====

== `interoperability_getAllChainAccounts`
Returns the chain account of a specified blockchain.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`chainID`
|string
|The chain ID of a blockchain.
|00000001
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke interoperability_getAllChainAccounts '{ "chainID": "02000001" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getAllChainAccounts",
    "params": {"chainID": "00000001"}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "chains": [
    {
      "lastCertificate": {
        "height": 0,
        "timestamp": 0,
        "stateRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "validatorsHash": "4db396119b1ef52d664f1ffe6e652fc44efb1d8171eb97316aa2c5535baa6d26"
      },
      "name": "piggybank1",
      "status": 0
    },
    {
      "lastCertificate": {
        "height": 0,
        "timestamp": 0,
        "stateRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "validatorsHash": "4db396119b1ef52d664f1ffe6e652fc44efb1d8171eb97316aa2c5535baa6d26"
      },
      "name": "piggybank",
      "status": 0
    },
    {
      "lastCertificate": {
        "height": 188831,
        "timestamp": 1688646810,
        "stateRoot": "37b9b1c382fc340bd45cf4fe151078e2a138c5fd638b4e2f1cd1896e3be0056b",
        "validatorsHash": "7ef288077993861544e90eb6889c560c12402560fb13d743f6e75bc7f95d1ae1"
      },
      "name": "betahello",
      "status": 0
    },
    {
      "lastCertificate": {
        "height": 0,
        "timestamp": 0,
        "stateRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "validatorsHash": "c941624942cbf1109e292e385885659f6e659ff665aed2857791afb7f80869d6"
      },
      "name": "betadapp",
      "status": 0
    },
    {
      "lastCertificate": {
        "height": 0,
        "timestamp": 0,
        "stateRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "validatorsHash": "9e2cb906384747720fb5693ca3cbb22ff913ce9a94fe60094a98e1ce915f20ef"
      },
      "name": "tiny",
      "status": 0
    }
  ]
}
----
====


== `interoperability_getChannel`
Returns the chain account of a specified blockchain.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`chainID`
|string
|The chain ID of a blockchain.
|00000001
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke interoperability_getChannel '{ "chainID": "02000001" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getChannel",
    "params": {"chainID": "00000001"}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "messageFeeTokenID": "0400000000000000",
  "outbox": {
    "appendPath": [
      "4d48ae83b249d1b409d2d7f1ae18792e7aeb15f647bd8a607c6639723a76a487"
    ],
    "root": "4d48ae83b249d1b409d2d7f1ae18792e7aeb15f647bd8a607c6639723a76a487",
    "size": 1
  },
  "inbox": {
    "appendPath": [],
    "root": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "size": 0
  },
  "partnerChainOutboxRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "minReturnFeePerByte": "1000"
}
----
====

== `interoperability_getOwnChainAccount`
Returns the chain account of a specified blockchain.

.Request
[tabs]
=====
Specification::
+
--
No parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke interoperability_getOwnChainAccount
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getOwnChainAccount",
    "params": {}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "chainID": "01000000",
  "name": "lisk_mainchain",
  "nonce": "5"
}
----
====