= Mainchain Interoperability module: Endpoint reference
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc: preamble
//URLs
:url_typedoc_interopmc: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.MainchainInteroperabilityModule.html
//Project URLs
:url_integrate_endpoints: integrate-blockchain/connecting-endpoints.adoc

This page summarizes all API endpoints specific to the {url_typedoc_interopmc}[Mainchain Interoperability module^].

//TODO:Add link to base interop endpoints
The Mainchain Interoperability modules includes also the base xref:{}[Interoperability endpoints], additional to the endpoints documented on this page.

TIP: Endpoints can be invoked as explained in the xref:{url_integrate_endpoints}[] guide.

== `mainchainInteroperability_getRegistrationFee`
This function checks whether the account corresponding to the input address has registered a multi-signature account.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address to query.
|lsk24cd35u4jdq8szo3pn
sqe5dsxwrnazyqqqg5eu
|===

--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke auth_getAuthAccount '{ "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "auth_getAuthAccount",
    "params": {
         "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "nonce": "0",
  "numberOfSignatures": 0,
  "mandatoryKeys": [],
  "optionalKeys": []
}
----

If there is no entry corresponding to address, it throws an error.
====
