= Mainchain Interoperability module: Endpoint reference
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc: preamble
//URLs
:url_typedoc_interopmc: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.MainchainInteroperabilityModule.html
//Project URLs
:url_integrate_endpoints: integrate-blockchain/connecting-endpoints.adoc
:url_command_fee: understand-blockchain/blocks-txs.adoc#command-fee
:url_api_interop: api/module-rpc-api/interoperability-endpoints.adoc

This page summarizes all API endpoints *specific to* the {url_typedoc_interopmc}[Mainchain Interoperability module^].

The Mainchain Interoperability module includes the base xref:{url_api_interop}[Base Interoperability endpoints], in addition to the endpoints documented on this page.

TIP: Endpoints can be invoked as explained in the xref:{url_integrate_endpoints}[] guide.

== `interoperability_getRegistrationFee`
Returns the required xref:{url_command_fee}[command fee] for sending a Sidechain Registration transaction.

.Request
[tabs]
=====
Specification::
+
--
No parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke interoperability_getRegistrationFee
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getRegistrationFee",
    "params": {}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{"fee":"1000000000"}
----
====

== `interoperability_getMinimumMessageFee`
Returns the minimum fee per byte for CCMs.

.Request
[tabs]
=====
Specification::
+
--
No parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke interoperability_getMinimumMessageFee
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_getMinimumMessageFee",
    "params": {}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{"fee":"1000"}
----
====

== `interoperability_isChainIDAvailable`
Checks if a given chainID for a sidechain is still available to register on the mainchain.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`chainID`
|string
|The chain ID of a sidechain.
|00000001
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke interoperability_isChainIDAvailable '{ "chainID": "00000001" }'
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_isChainIDAvailable",
    "params": { "chainID": "00000001" }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{"result":true}
----
====

== `interoperability_isChainNameAvailable`
Checks if a given chain name for a sidechain is still available to register on the mainchain.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`name`
|string
|Name of the sidechain.
|sidechain_1
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke interoperability_isChainNameAvailable '{ "name": "sidechain_1" }'
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "interoperability_isChainNameAvailable",
    "params": { "name": "sidechain_1" }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{"result":true}
----
====

