= Random module: Endpoint reference
Muhammad Talha <muhammad.talha@lightcurve.io>
// Settings
:toc: preamble
//URLs
:url_typedoc_random: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.RandomModule.html

:url_random: https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/modules/random/endpoint.ts

//Project URLs
:url_integrate_endpoints: integrate-blockchain/connecting-endpoints.adoc

//TODO: Add a hyperlink for Dynamic Rewards
This page summarizes all API endpoints specific to the {url_typedoc_random}[Random^] module.

All the aforementioned endpoints can be invoked using the `random` prefix.

TIP: Endpoints can be invoked as explained in the xref:{url_integrate_endpoints}[] guide.


== `random_isSeedRevealValid`
Checks whether the `seedReveal` of a particular validator is valid.
The response is a boolean value.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`generatorAddress`
|string
|The Lisk32 address of a validator.
|lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99

|`seedReveal`
|string
|The value revealed by the generator of the block for the commit and reveal process.
|c0f96ff4416b6c9ff0f641527dec0a27
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke random_isSeedRevealValid '{"generatorAddress":"lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99", "seedReveal":"c0f96ff4416b6c9ff0f641527dec0a27"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "random_isSeedRevealValid",
    "params": {
        "generatorAddress": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
       "seedReveal":"c0f96ff4416b6c9ff0f641527dec0a27"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "valid": true
}
----
====

== `random_setHashOnion`
Sets the hash onion of a validator.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address of a validator.
|lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99

|`seed`
|string
|Seed hash value for the hash onions.
|c0f96ff4416b6c9ff0f641527dec0a27

|`count`
|string
|The total number of hash onions.
|1000000

|`distance`
|string
|Distance between each hash.
|1000
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke random_setHashOnion '{"address":"lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99", "seed": "e025160dfc93688a01c96ab9f3e0a29e", "count": 1000000, "distance": 1000}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "random_setHashOnion",
    "params": {
        "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
        "seed": "e025160dfc93688a01c96ab9f3e0a29e",
        "count": 1000000,
        "distance": 1000
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{}
----
====

== `random_getHashOnionSeeds`
Retrieves the hash onion seeds of a validator.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address of a validator.
|lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99

|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke random_getHashOnionSeeds '{"address":"lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "random_getHashOnionSeeds",
    "params": {
        "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "seeds": [
    {
      "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
      "seed": "e025160dfc93688a01c96ab9f3e0a29e",
      "count": 1000000,
      "distance": 1000
    }
  ]
}
----
====


== `random_hasHashOnion`
Checks if a validator has a hash onion.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address of a validator.
|lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99

|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke random_hasHashOnion '{"address":"lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "random_hasHashOnion",
    "params": {
        "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "hasSeed": true,
  "remaining": 1000000
}
----
====



== `random_getHashOnionUsage`
Returns the hash onion usage for a validator.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address of a validator.
|lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke random_getHashOnionUsage '{"address":"lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "random_getHashOnionUsage",
    "params": {
        "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "usedHashOnions": [
    {
      "count": 0,
      "height": 0
    }
  ],
  "seed": "e025160dfc93688a01c96ab9f3e0a29e"
}
----
====



== `random_setHashOnionUsage`
Sets the hash onion usage for a validator.

.Request
[tabs]
=====
Specification::
+
--
[cols="1,1,4,4",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address of a validator.
|lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99

|`usedHashOnions`
|Object[]
|Defines the number of times hash onions are used and also the block height of the usage.
a|[source,bash]
----
"usedHashOnions": [
    {
        "count": 10,
        "height": 100
    }
]
----
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke random_setHashOnionUsage '{"address":"lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99", "usedHashOnions": [{"count": 10, "height":100 }]}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "random_setHashOnionUsage",
    "params": {
        "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99",
        "usedHashOnions": [
            {
                "count": 10,
                "height": 100
            }
        ]
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{}
----
====