= Token module: Endpoint reference
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc: preamble
//URLs
:url_typedoc_token: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.TokenModule.html
//Project URLs
:url_integrate_endpoints: integrate-blockchain/connecting-endpoints.adoc

This page summarizes all available API endpoints of the {url_typedoc_token}[Token module^].

TIP: Endpoints can be invoked as explained in the xref:{url_integrate_endpoints}[] guide.

== `token_getBalances`
Returns the balances of all tokens associated with a specific account.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|Account address.
|lsk55e8u4heymzmxgcrg4dc5xpgd5ckkyv53oxftb
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke token_getBalances '{"address":"lsk55e8u4heymzmxgcrg4dc5xpgd5ckkyv53oxftb"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "token_getBalances",
    "params": {"address":"lsk55e8u4heymzmxgcrg4dc5xpgd5ckkyv53oxftb"}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "balances": [
    {
      "tokenID": "0200000000000000",
      "availableBalance": "1000000000",
      "lockedBalances": []
    }
  ]
}
----
====

== `token_getBalance`
Returns the balance of a specific token associated with a specific account.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`tokenID`
|string
|TokenID of the token to query the balance for.
|0200000000000000

|`address`
|string
|Account address.
|lsk55e8u4heymzmxgcrg4dc5xpgd5ckkyv53oxftb
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke token_getBalance '{"tokenID":"0200000000000000","address":"lsk55e8u4heymzmxgcrg4dc5xpgd5ckkyv53oxftb"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "token_getBalance",
    "params": {"tokenID":"0200000000000000","address":"lsk55e8u4heymzmxgcrg4dc5xpgd5ckkyv53oxftb"}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "availableBalance": "1000000000",
  "lockedBalances": []
}
----
====

== `token_getTotalSupply`
Returns the total supply that exists of a specific token.

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke token_getTotalSupply --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "token_getTotalSupply",
    "params": {}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "totalSupply": [
    {
      "tokenID": "0200000000000000",
      "totalSupply": "11121172542991566"
    }
  ]
}
----
====

== `token_getSupportedTokens`
Returns a list of token IDs that are supported in the network.

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke token_getSupportedTokens --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "token_getSupportedTokens",
    "params": {}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "supportedTokens": [
    "0200000000000000",
    "0200000000000000"
  ]
}
----
====

== `token_isSupported`
Checks if a specific token is supported by the network.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`tokenID`
|string
|TokenID of the token to query the balance for.
|0200000000000000
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke token_isSupported '{"tokenID":"0200000000000000"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "token_isSupported",
    "params": {"tokenID":"0200000000000000"}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "supported": true
}
----
====

== `token_getEscrowedAmounts`
Returns all balances of existing sidechain escrow accounts.

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke token_getEscrowedAmounts --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "token_getEscrowedAmounts",
    "params": {}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "escrowedAmounts": [
    {
      "escrowChainID": "02000007",
      "amount": "0",
      "tokenID": "0200000000000000"
    },
    {
      "escrowChainID": "02000070",
      "amount": "0",
      "tokenID": "0200000000000000"
    },
    {
      "escrowChainID": "02001337",
      "amount": "0",
      "tokenID": "0200000000000000"
    },
    {
      "escrowChainID": "02100000",
      "amount": "0",
      "tokenID": "0200000000000000"
    },
    {
      "escrowChainID": "02100001",
      "amount": "0",
      "tokenID": "0200000000000000"
    }
  ]
}
----
====

== `token_getInitializationFees`
Returns the fees for initializing new user and escrow accounts.

.Request
[tabs]
=====
Specification::
+
--
No Parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke token_getInitializationFees --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "token_getInitializationFees",
    "params": {}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "userAccount": "5000000",
  "escrowAccount": "5000000"
}
----
====

== `token_hasUserAccount`
Checks if an account exists for the provided address and token in the network.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`tokenID`
|string
|Token ID.
|0200000000000000

|`address`
|string
|Account address.
|lsk55e8u4heymzmxgcrg4dc5xpgd5ckkyv53oxftb
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke token_hasUserAccount '{"tokenID":"0200000000000000","address":"lsk55e8u4heymzmxgcrg4dc5xpgd5ckkyv53oxftb"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "token_hasUserAccount",
    "params": {"tokenID":"0200000000000000","address":"lsk55e8u4heymzmxgcrg4dc5xpgd5ckkyv53oxftb"}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "exists": true
}
----
====

== `token_hasEscrowAccount`
Checks if an escrow account exists for the provided chain ID and token in the network.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,3,1",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`tokenID`
|string
|Token ID.
|0200000000000000

|`escrowChainID`
|string
|Escrow chain ID.
|02001337
|===
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke token_hasEscrowAccount '{"tokenID":"0200000000000000","escrowChainID":"02001337"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "token_hasEscrowAccount",
    "params": {"tokenID":"0200000000000000","escrowChainID":"02001337"}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "exists": true
}
----
====