= Validators module: Endpoint reference
Mona Bärenfänger <mona@lightcurve.io> Chris Braithwaite <christopher.braithwaite@lightcurve.io>
// Settings
:toc: preamble

//URLs
:url_typedoc_auth: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.ValidatorModule.html
//Project URLs
:url_integrate_endpoints: integrate-blockchain/connecting-endpoints.adoc

This page summarizes all available API endpoints of the {url_typedoc_auth}[Auth module^].

TIP: Endpoints can be invoked as explained in the xref:{url_integrate_endpoints}[] guide.

== `ValidatorBLSKey`
This endpoint checks whether the account corresponding to the input address has registered a multi-signature account.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,2,2",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address to query.
|lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu
|===

--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke validateBLSKey '{ "blsKey": "83d4f8300dda93e62b375264e8e47bc224cbb8f2ecf4c2e848ac9758d6d8fd263c22ef2d9be18b066b8efcab80d6bdaa", "ProofOfPossession": "b92b11d66348e197c62d14af1453620d550c21d59ce572d95a03f0eaa0d0d195efbb2f2fd1577dc1a04ecdb453065d9d168ce7648bc5328e5ea47bb07d3ce6fd75f35ee51064a9903da8b90f7dc8ab4f2549b834cb5911b883097133f" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "validateBLSKey",
    "params": {
         "blsKey":  "83d4f8300dda93e62b375264e8e47bc224cbb8f2ecf4c2e848ac9758d6d8fd263c22ef2d9be18b066b8efcab80d6bdaa", "proofOfpossession": "b92b11d66348e197c62d14af1453620d550c21d59ce572d95a03f0eaa0d0d195efbb2f2fd1577dc1a04ecdb453065d9d168ce7648bc5328e5ea47bb07d3ce6fd75f35ee51064a9903da8b90f7dc8ab4f2549b834cb5911b883097133f" }' --pretty
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "valid"
}
----

If there is no entry corresponding to address, it throws an error.
====

== `auth_getMultiSigRegMsgSchema`
Returns the params schema for the `registerMultisignature` command of the Auth module.

.Request
[tabs]
=====
Specification::
+
--
No parameters.
--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke auth_getMultiSigRegMsgSchema --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "auth_getMultiSigRegMsgSchema",
    "params": {}
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "schema": {
    "$id": "/auth/command/regMultisigMsg",
    "type": "object",
    "required": [
      "address",
      "nonce",
      "numberOfSignatures",
      "mandatoryKeys",
      "optionalKeys"
    ],
    "properties": {
      "address": {
        "dataType": "bytes",
        "fieldNumber": 1,
        "minLength": 20,
        "maxLength": 20
      },
      "nonce": {
        "dataType": "uint64",
        "fieldNumber": 2
      },
      "numberOfSignatures": {
        "dataType": "uint32",
        "fieldNumber": 3
      },
      "mandatoryKeys": {
        "type": "array",
        "items": {
          "dataType": "bytes",
          "minLength": 32,
          "maxLength": 32
        },
        "fieldNumber": 4
      },
      "optionalKeys": {
        "type": "array",
        "items": {
          "dataType": "bytes",
          "minLength": 32,
          "maxLength": 32
        },
        "fieldNumber": 5
      }
    }
  }
}
----
====


