= Validators module: Endpoint reference
Mona Bärenfänger <mona@lightcurve.io> Chris Braithwaite <christopher.braithwaite@lightcurve.io>
// Settings
:toc: preamble

//URLs
:url_typedoc_auth: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.ValidatorModule.html
//Project URLs
:url_integrate_endpoints: integrate-blockchain/connecting-endpoints.adoc

This page summarizes all available API endpoints of the {url_typedoc_auth}[Validators module^].

TIP: Endpoints can be invoked as explained in the xref:{url_integrate_endpoints}[] guide.

== `ValidatorBLSKey`
This endpoint is used to retrieve the BLS public key of a specific validator in the network.
//This endpoint checks whether the account corresponding to the input address has registered a multi-signature account.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,2,2",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`proofOfPossession`
|string
|Validates and verifies ownership of tokens.
|b92b11d66348e197c62d14af1453620d550c21d59ce572d95a03f0eaa0d0d195efbb2f2fd1577dc1a04ecdb453065d9d168ce7648bc5328e5ea47bb07d3ce6fd75f35ee51064a9903da8b90f7dc8ab4f2549b834cb5911b883097133f,

|`blsKey`
|string
|blsKey in hex format.
|83d4f8300dda93e62b375264e8e47bc224cbb8f2ecf4c2e848ac9758d6d8fd263c22ef2d9be18b066b8efcab80d6bdaa
|===

--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke validateBLSKey '{ "blsKey": "83d4f8300dda93e62b375264e8e47bc224cbb8f2ecf4c2e848ac9758d6d8fd263c22ef2d9be18b066b8efcab80d6bdaa", "ProofOfPossession": "b92b11d66348e197c62d14af1453620d550c21d59ce572d95a03f0eaa0d0d195efbb2f2fd1577dc1a04ecdb453065d9d168ce7648bc5328e5ea47bb07d3ce6fd75f35ee51064a9903da8b90f7dc8ab4f2549b834cb5911b883097133f" }' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "validator_validateBLSKey",
    "params": {
         "blsKey":  "83d4f8300dda93e62b375264e8e47bc224cbb8f2ecf4c2e848ac9758d6d8fd263c22ef2d9be18b066b8efcab80d6bdaa", "proofOfpossession": "b92b11d66348e197c62d14af1453620d550c21d59ce572d95a03f0eaa0d0d195efbb2f2fd1577dc1a04ecdb453065d9d168ce7648bc5328e5ea47bb07d3ce6fd75f35ee51064a9903da8b90f7dc8ab4f2549b834cb5911b883097133f" }' --pretty
    }
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
  "valid": true
}
----

If there is no BLS key in the store it would return as `false`.
====

== `getValidator`
Returns the `generatorKey` and the `blsKey` of the validator module.

.Request
[tabs]
=====
Specification::
+
--
.Parameters
[cols="1,1,2,2",options="header",stripes="hover"]
|===
|Name
|Type
|Description
|Sample

|`address`
|string
|The Lisk32 address to query.
|lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday

--
Node CLI::
+
--
[source,bash]
----
lisk-core endpoint:invoke getValidator '{"address":"lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday"}' --pretty
----

--
cURL::
+
--
[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "validator_getValidator",
    "params": {
         "address":  "lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday"
}'
----
--
=====

.Response
[%collapsible]
====
.Example output
[source,json]
----
{
    "generatorKey": "67995503520459acdc44446ea0a57c8c35d4c84c349fca9ecc0f4fe1fa45c06c"
    "blsKey": "b301803f8b5ac4a1133581fc676dfedc60d891dd5fa99028805e5ea5b08d3491af75d0707adab3b70c6a6a580217bf81"
}
----
====


