= ChangeLog 3.x to 4.x
Mona Bärenfänger <mona@lightcurve.io>
:description: This section contains the devloper changelog information from the transaction types and updated genesis block for the devnet, to the database changes including the peers, delegates and nodes.
:toc:
:imagesdir: ../../assets/images
:v_sdk: v4.0.0

:url_bigint: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
:url_github_devnet_genesis_payload: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/sdk/src/samples/genesis_block_devnet.json#L11
:url_github_devnet_genesis_comid: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/sdk/src/samples/genesis_block_devnet.json#L9
:url_github_lip15: https://github.com/LiskHQ/lips/blob/master/proposals/lip-0015.md
:url_github_lip25: https://github.com/LiskHQ/lips/blob/master/proposals/lip-0025.md

:url_config_reference: references/config.adoc
:url_guides_tx_store: guides/app-development/custom-transactions.adoc#store

== BigInt replaces BigNum

In v4.0.0 xref:{url_bigint}[BigInt] is used to handle large numbers, like account balances and transfer amounts.

BigInt is a built-in JavaScript object and replaces the previously used `BigNum` object.

IMPORTANT: The balances of accounts are now saved as **BigInt**(previously `string`) in the Lisk SDK v4.0.0.

== applyAsset() is now asynchronous

The `applyAsset()` function of custom transaction has become asynchronous, so you need to adjust the function in your implementation to something like this:

[tabs]
=====
v4.x::
+
--
[source,js]
----
async applyAsset(store) {
        const sender = await store.account.get(this.senderId);
        // [...]
}
----
--
v3.x::
+
--
[source,js]
----
applyAsset(store) {
        const sender = store.account.get(this.senderId);
        // [...]
}
----
--
=====

== The store returns accounts as classes

The accounts that are returned from the xref:{url_guides_tx_store}[store] in transactions are now returned as classes instead of pure objects.

Because of this, it is recommended to mutate the received account class directly.

[tabs]
=====
v4.x::
+
--
[source,js]
----
async applyAsset(store) {
        const sender = await store.account.get(this.senderId);
        sender.asset = { hello: this.asset.hello };
        store.account.set(sender.address, sender);
        // [...]
}
----
--
v3.x::
+
--
[source,js]
----
applyAsset(store) {
        const sender = store.account.get(this.senderId);
        const newObj = { ...sender, asset: { hello: this.asset.hello } };
        store.account.set(sender.address, newObj);
        // [...]
}
----
--
=====

== Dynamic fees

No static `FEE` property needs to be defined in a custom transaction anymore.

The fee is now a required parameter for every transaction to be accepted by a node.

The specified fee must always be equal or higher to the defined minimum fee per bytes of the corresponding transaction type.



== Nonce replaces the timestamp in transactions

The timestamp that was a required property previousely have been replaced by the nonce.

Every account in the network has a individual nonce, which is a number that increments +1 each time the respective account sends a transaction to the network.

Nonces prevent transaction replays and enable users to invalidate transactions, in case of need.
For more information about the reasoning bbehind this change, check out {url_github_lip15}[LIP 15: Enable transaction invalidation by using nonces instead of timestamps^].

== Accounts must have a minimum balance

{url_github_lip25}[LIP 25: Introduce minimum balance requirement for accounts^] introduces a new constant `minBbalance`, which is defining a minimum balance for all accounts in the network.

If the minimum balance for accounts is set to a reasonable value, it prevents the network from certain spam attacks, like creating a lot of new accounts with basically no balance.

NOTE: This possible attack becomes more relevant with SDK v4.0.0, as the dynamic fees allow much lower fees for nearly all default transactions, and therefore the transaction fees alone are not sufficient anymore to prevent this.

The minimum balance is a constant that is defined in the `BaseTransaction` class and defaults to 0.05 tokens.

.base_transaction.ts
[source,js]
----
//[...]
export abstract class BaseTransaction {
    MIN_REMAINING_BALANCE = BigInt('5000000'); // 0.05
//[...]
----

== Updated genesis block for devnet

Due to the changes that have been introduced for the structure of transaction objects, the genesis block and it's transactions were created new for Lisk SDK version 3.0.

See the new genesis block on Github: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/sdk/src/samples/genesis_block_devnet.json

See the new devnet config: https://github.com/LiskHQ/lisk-sdk/blob/{v_sdk}/sdk/src/samples/config_devnet.json

=== New genesis account

[cols=",,,",options="header"]
|===
| Name
| Address
| Passphrase
| Description

| Genesis account
| 5059876081639179984L
| `peanut hundred pen hawk invite exclude brain chunk gadget wait wrong ready`
| The genesis account holds all the tokens that are created in the devnet genesis block.
It is utilized to vote for the forging genesis delegates in a convenient way during development.

|===

== API changes

[NOTE]
====
The list of API changes only comprises of the parts of the API that changed from Lisk SDK 3.x to 4.x.

To see the complete API specification for Lisk SDK 4.x, please refer to the xref:{url_config_reference}[Config reference].
====

Changes are grouped by the different API endpoints for the Lisk SDK.

=== Color legend
[cols=""]
|===
|{set:cellbgcolor:red}RED = Removed in Lisk SDK 4.x
|{set:cellbgcolor:green}GREEN = Added in Lisk SDK 4.x
|===
{set:cellbgcolor!}

=== Accounts

==== Query
....
GET /accounts
....


===== Description
Search for matching accounts in the system.


===== Parameters

[options="header", cols=",,,,"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**address** +
__optional__|Address of an account.|string (address)|
|**Query**|**limit** +
__optional__|Limit applied to results.|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results.|integer (int32)|`0`
|**Query**|**publicKey** +
__optional__|Public key to query.|string (publicKey)|
|{set:cellbgcolor:red} **Query**|**secondPublicKey** +
__optional__|Second public key to query|string (publicKey)|
|{set:cellbgcolor!}
**Query**|**sort** +
__optional__|Fields to sort results by.|enum (balance:asc, balance:desc)|`"balance:asc"`
|**Query**|**username** +
__optional__|Delegate username to query.|string (username)|
|===

==== Get multisignature groups (Removed)

[options="", cols=""]
|===
|{set:cellbgcolor:red} `GET /accounts/\{address}/multisignature_groups`
|===

==== Get multisignature memberships (Removed)

[options="", cols=""]
|===
|{set:cellbgcolor:red} `GET /accounts/\{address}/multisignature_memberships`
|===
{set:cellbgcolor!}

[[_account]]
==== Account definition

[options="header", cols=",,"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk address is the human readable representation of the accounts owners public key.
It consists of 21 numbers followed by a capital 'L' at the end. +
**Example** : `"12668885769632475474L"`|string (address)
|{set:cellbgcolor:green}**asset** +
__optional__|Any JSON stored in the account's asset field. +
**Example** : `{
  "custom" : true,
  "field" : true
}`|object
|**balance** +
__required__|The current balance of the account in Beddows. +
**Example** : `"1081560729258"`|string
|**delegate** +
__required__||<<_delegate,Delegate>>
|**isDelegate** +
__optional__|The value indicating if the account is a deleage or not.|boolean
|**keys** +
__required__||<<_multisignatureasset,MultisignatureAsset>>
|**missedBlocks** +
__optional__|Total number of blocks that the delegate has missed. +
**Example** : `427`|integer
|**nonce** +
__required__|The current nonce associated to account for transaction processing. +
**Example** : `"154"`|string
|**producedBlocks** +
__optional__|Total number of blocks that the delegate has forged. +
**Example** : `20131`|integer
|**productivity** +
__optional__|Productivity rate.
Percentage of successfully forged blocks (not missed), by the delegate. +
**Example** : `96.41`|number
|{set:cellbgcolor!}
**publicKey** +
__required__|The public key is derived from the private key of the owner of the account.
It can be used to validate that the private key belongs to the owner, but does not provide access to the owners private key. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
| {set:cellbgcolor:red}**secondPublicKey** +
__optional__|The second public key is derived from the second private key of an account, if the owner activated a second passphrase for her/his account. +
It can be used to validate that the private key belongs to the owner, but does not provide access to the owners private key. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|{set:cellbgcolor:green}**rewards** +
__optional__|Total sum of block rewards that the delegate has forged. +
**Example** : `"510000000"`|string
|**totalVotesReceived** +
__optional__|The total votes received by the delegate.
Represents the total amount of Lisk (in Beddows), that the delegates voters voted for this delegate. +
**Example** : `"1081560729258"`|string
|**unlocking** +
__required__||< <<_unlocking,Unlocking>> > array
|**username** +
__optional__|If the account is a delegate, it displays the username for it. +
**Example** : `"onedelegate"`|string
|**votes** +
__required__||< <<_vote,Vote>> > array
|===
{set:cellbgcolor!}

==== AccountWithVotes definition

[options="header", cols=",,"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk address of the queried account. +
**Example** : `"12668885769632475474L"`|string (address)
|{set:cellbgcolor:red}**asset** +
__optional__|Any JSON stored in the account's asset field. +
**Example** : `{
  "custom" : true,
  "field" : true
}`|object
|{set:cellbgcolor!}
**balance** +
__required__|The balance of the queried account. +
**Example** : `"1081560729258"`|string
|{set:cellbgcolor:red}**delegate** +
__optional__||<<_delegate,Delegate>>
|{set:cellbgcolor!}
**publicKey** +
__optional__|Public key of the queried account. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|{set:cellbgcolor:red}**secondPublicKey** +
__optional__|The second public key is derived from the second private key of an account, if the owner activated a second passphrase for her/his account. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|{set:cellbgcolor:green}**username** +
__required__|Username of the account, if the queried account is a delegate. +
**Example** : `"isabella"`|string (username)
|**votes** +
__required__|List of placed votes by the queried account.|< <<_votewithdelegateproperties,VoteWithDelegateProperties>> > array
|**votesAvailable** +
__required__|Number of votes that are available for the queried account.
Derives from 101(max possible votes) - votesUsed(already used votes). +
**Example** : `8`|integer
|===
{set:cellbgcolor!}

=== Delegates

==== Query
....
GET /delegates
....

===== Parameters

[options="header", cols=",,,a,a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**address** +
__optional__|Address of an account|string (address)|
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**publicKey** +
__optional__|Public key to query|string (publicKey)|
|**Query**|**search** +
__optional__|Fuzzy delegate username to query|string|
|{set:cellbgcolor:red}**Query**|**secondPublicKey** +
__optional__|Second public key to query|string (publicKey)|
|{set:cellbgcolor!}
**Query**|**sort** +
__optional__
|Fields to sort results by
|

[cols="",options="header"]
!===
! enum
! username:asc
! username:desc
! productivity:asc
! productivity:desc
! missedBlocks:asc
! missedBlocks:desc
! producedBlocks:asc
! producedBlocks:desc
! {set:cellbgcolor:red}
voteWeight:asc
! voteWeight:desc
! {set:cellbgcolor:green}
totalVotesReceived:asc
! totalVotesReceived:desc
!===

|
[cols=""]
!===
! {set:cellbgcolor:red} `"voteWeight:desc"`
! {set:cellbgcolor:green} `"totalVotesReceived:desc"`
!===
|**Query**|**username** +
__optional__|Delegate username to query|string (username)|
|===

==== Delegate definition
[options="header", cols=",,"]
|===
|Name|Description|Schema
|**approval** +
__optional__|Percentage of the voters weight that the delegate owns in relation to the total supply of Lisk. +
**Example** : `14.22`|number
|{set:cellbgcolor:green}**consecutiveMissedBlocks** +
__optional__|Number of blocks that the delegate missed consecutively. +
**Example** : `10`|integer
|**isBanned** +
__optional__|Whether the delegate is banned or not. +
**Example** : `false`|boolean
|**lastForgedHeight** +
__optional__|Height of the block after the latest forging that was executed by the delegate.  +
**Example** : `100`|integer
|**pomHeights** +
__optional__|Height of blocks where the delegate has been reported for misbehavior.|< integer > array
|===
{set:cellbgcolor!}

[[_delegatewithaccount]]
==== DelegateWithAccount definition (Removed)

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**account** +
__required__||<<_account,Account>>
|**approval** +
__optional__|Percentage of the voters weight, that the delegate owns in relation to the total supply of Lisk. +
**Example** : `14.22`|number
|**missedBlocks** +
__optional__|Total number of blocks the delegate has missed. +
**Example** : `427`|integer
|**producedBlocks** +
__optional__|Total number of blocks the delegate has forged. +
**Example** : `20131`|integer
|**productivity** +
__optional__|Productivity rate.
Percentage of successfully forged blocks (not missed) by the delegate. +
**Example** : `96.41`|number
|**rewards** +
__optional__|Total sum of block rewards that the delegate has forged. +
**Example** : `"510000000"`|string
|**username** +
__required__|The delegates' username.
A delegate chooses the username by registering a delegate on the Lisk network.
It is unique and cannot be changed later. +
**Example** : `"isabella"`|string (username)
|**voteWeight** +
__required__|The voters weight of the delegate.
Represents the total amount of Lisk (in Beddows) that the delegates' voters own.
The voters weight decides which rank the delegate gets in relation to the other delegates and their voters weights. +
**Example** : `"1081560729258"`|string
|===
{set:cellbgcolor!}

==== DelegateWithVoters definition
[options="header", cols=",,"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk address of a delegate. +
**Example** : `"12668885769632475474L"`|string (address)
|**balance** +
__required__|Account balance.
Amount of Lisk the delegate account owns. +
**Example** : `"1081560729258"`|string
|**publicKey** +
__optional__|The public key of the delegate. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**username** +
__required__|The delegates username.
A delegate chooses the username by registering a delegate on the Lisk network.
It is unique and cannot be changed later. +
**Example** : `"isabella"`|string (username)
|**voters** +
__required__|List of accounts that voted for the queried delegate.|< <<_voter,Voter>> > array
|{set:cellbgcolor:red}**votes** +
__required__|The voters weight of the delegate.
Represents the total amount of Lisk (in Beddows) that the delegates' voters own.
The voters weight decides which rank the delegate gets in relation to the other delegates and their voters weights. +
**Example** : `108877`|integer
|{set:cellbgcolor:green}**votes** +
__required__|Accounts which this delegate voted for.|< <<_vote,Vote>> > array
|===
{set:cellbgcolor!}

==== DelegateWithVotes definition (Removed)

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**address** +
__required__|The Lisk address of the queried account. +
**Example** : `"12668885769632475474L"`|string (address)
|**balance** +
__required__|The balance of the queried account. +
**Example** : `"1081560729258"`|string
|**publicKey** +
__optional__|Public key of the queried account. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**username** +
__required__|Username of the account, if the queried account is a delegate +
**Example** : `"isabella"`|string (username)
|**votes** +
__required__|List of placed votes by the queried account.|<<_vote,Vote>> array
|**votesAvailable** +
__required__|Number of votes that are available for the queried account.
Derives from 101 (max possible votes) - votesUsed(alreadu used votes) +
**Example** : `40`|integer
|**votesUsed** +
__required__|Number of votes that are already placed by the queried account. +
**Example** : `2`|integer
|===
{set:cellbgcolor!}

==== DelegatesResponse definition

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**data** +
__required__|List of delegates|<<_delegatewithaccount,DelegateWithAccount>> array
|{set:cellbgcolor:green}**data** +
__required__|List of delegates.|< <<_account,Account>> > array
|{set:cellbgcolor!}
**links** +
__required__||object
|**meta** +
__required__||<<_delegatesresponse_meta,meta>>
|===
[[_delegatesresponse_meta]]
**meta**
[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**limit** +
__required__|**Default** : `10` +
**Minimum value** : `1` +
**Maximum value** : `101`|integer (int32)
|{set:cellbgcolor:green}**limit** +
__required__|**Default** : `10` +
**Minimum value** : `1` +
**Maximum value** : `103`|integer (int32)
|{set:cellbgcolor!}
**offset** +
__required__||<<_offset,Offset>>
|===

=== Node

==== Query node/transactions/state

[options="", cols=""]
|===
|{set:cellbgcolor:red} GET /node/transactions/\{state}
|{set:cellbgcolor:green} `GET /node/transactions`
|===
{set:cellbgcolor!}

===== Parameters

[options="header", cols=",,,a,a"]
|===
|Type|Name|Description|Schema|Default
|{set:cellbgcolor:red}**Path**|**state** +
__required__|State of transactions to query|enum (pending, ready, received, validated, verified)|`"verified"`
|{set:cellbgcolor!}
**Query**|**id** +
__optional__|Transaction ID to query.|string (id)|
|**Query**|**limit** +
__optional__|Limit applied to results.|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results.|integer (int32)|`0`
|{set:cellbgcolor:red}**Query**|**recipientId** +
__optional__|Recipient's Lisk address|string (address)|
|{set:cellbgcolor!}
**Query**|**senderId** +
__optional__|Sender's Lisk address.|string (address)|
|**Query**|**senderPublicKey** +
__optional__|Sender's public key.|string (publicKey)|
|**Query**|**sort** +
__optional__
|Fields to sort results by
|

[cols="",options="header"]
!===
! enum
! {set:cellbgcolor:red}
amount:asc
! amount:desc
! {set:cellbgcolor!}
fee:asc
! fee:desc
! type:asc
! type:desc
! {set:cellbgcolor:red}
timestamp:asc
! timestamp:desc
!===

|
[cols=""]
!===
! {set:cellbgcolor:red} amount:desc
! {set:cellbgcolor:green} fee:desc
!===
|{set:cellbgcolor!}
*Query*| *type* +
__optional__|Transaction type (0-*)|integer|
|===

[[_nodestatus]]
==== NodeStatus definition

[options="header", cols=",,"]
|===
|Name|Description|Schema
|**chainMaxHeightFinalized** +
__required__|The largest height with precommits by at least 68 delegates.
See https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md +
**Example** : `123`|integer
|**currentTime** +
__required__|Current time of the node in miliseconds (Unix Timestamp). +
__required__|Current time of the node in milliseconds (Unix timestamp). +
**Example** : `1533558858128`|integer
|**height** +
__required__|Current block height of the node.
Represents the current number of blocks in the chain on the node. +
**Minimum value** : `1` +
**Example** : `123`|integer
|**secondsSinceEpoch** +
__required__|Number of seconds that have elapsed since the Lisk epoch time (Lisk Timestamp). +
__required__|Number of seconds that have elapsed since the Lisk epoch time (Lisk timestamp). +
**Example** : `1533558858`|integer
|**syncing** +
__required__|True if the node syncing with other peers. +
__required__|True if the node is syncing with other peers. +
**Example** : `false`|boolean
|{set:cellbgcolor:green}**unconfirmedTransactions** +
__required__|Number of unprocessed transactions in the pool. +
**Minimum value** : `0` +
**Example** : `1`|integer
|===
{set:cellbgcolor!}

=== Signatures

==== Post a signature (removed)

[options="", cols=""]
|===
|{set:cellbgcolor:red} POST /signatures
|===
{set:cellbgcolor!}

[[_signature]]
==== Signature definition (removed)

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**publicKey** +
__required__|Public key of the account that intends to sign the multisignature transaction. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|**signature** +
__required__|Signature to sign the transaction.
The signature can be generated locally, either by using Lisk Commander or with Lisk elements. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**transactionId** +
__required__|Unique identifier of the multisignature transaction to sign. +
**Length** : `1 - 20` +
**Example** : `"222675625422353767"`|string (id)
|===


[[_signatureresponse]]
==== SignatureResponse definition (removed)
Signature response.

[options="header", cols=","]
|===
|Name|Schema
|{set:cellbgcolor:red}**data** +
__required__|<<_signatureresponse_data,data>>
|**links** +
__required__|object
|**meta** +
__required__|<<_signatureresponse_meta,meta>>
|===

[[_signatureresponse_data]]
**data**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**message** +
__required__|**Minimum length** : `1`|string
|===

[[_signatureresponse_meta]]
**meta**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**status** +
__required__|Acceptance status for the signature +
**Example** : `true`|boolean
|===

[[_multisignaturegroup]]
==== MultisignatureGroup definition (removed)

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**address** +
__required__|The Lisk address is the human readable representation of the accounts owners' public key.
It consists of 21 numbers followed by a big 'L' at the end. +
**Example** : `"12668885769632475474L"`|string (address)
|**balance** +
__required__|The current balance of the account in Beddows. +
**Example** : `"1081560729258"`|string
|**lifetime** +
__required__|The maximum amount of hours, that a transaction will wait for the minimum amount of signatures to be reached.
If not enough members of a multisignature group sign the transaction in the defined lifespan, the transaction will be invalid. +
**Example** : `72`|integer
|**members** +
__required__||<<_account,Account>> array
|**min** +
__required__|Minimum amount of signatures a transaction needs to be signed successfully by this multisignature account. +
**Example** : `3`|integer
|**publicKey** +
__required__|The public key is derived from the private key of the owner of the account.
It can be used to validate that the private key belongs to the owner, but not provide access to the owners private key. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**secondPublicKey** +
__optional__|The second public key is derived from the second private key of an account, if the owner activated a second passphrase for her/his account. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|===


[[_multisignaturegroupsresponse]]
==== MultisignatureGroupsResponse definition (removed)

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**data** +
__required__|List of multisignature groups|<<_multisignaturegroup,MultisignatureGroup>> array
|**links** +
__required__||object
|**meta** +
__required__||object
|===
{set:cellbgcolor!}

[[_multisignatureasset]]
==== MultisignatureAsset definition (added)

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:green}**mandatoryKeys** +
__optional__|Mandatory multi-signature account members|< string > array
|**numberOfSignatures** +
__optional__|Number of required signatures|number
|**optionalKeys** +
__optional__|Optional multi-signature account members|< string > array
|===
{set:cellbgcolor!}

=== Transactions

==== Query
....
GET /transactions
....

===== Description
Search for a specified transaction in the system.

===== Parameters

[options="header", cols=",,,a,"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**blockId** +
__optional__|Block ID to query.|string (id)|
|**Query**|**data** +
__optional__|Fuzzy additional data field to query.|string (additionalData)|
|{set:cellbgcolor:red}**Query**|**fromTimestamp** +
__optional__|Starting unix timestamp|integer|
|{set:cellbgcolor!}
**Query**|**height** +
__optional__|Current height of the network.|integer (int32)|
|**Query**|**id** +
__optional__|Transaction ID to query.|string (id)|
|**Query**|**limit** +
__optional__|Limit applied to results.|integer (int32)|`10`
|**Query**|**maxAmount** +
__optional__|Maximum transaction amount in Beddows.|integer|
|**Query**|**minAmount** +
__optional__|Minimum transaction amount in Beddows.|integer|
|**Query**|**offset** +
__optional__|Offset value for results.|integer (int32)|`0`
|**Query**|**recipientId** +
__optional__|Recipients Lisk address.|string (address)|
|**Query**|**senderId** +
__optional__|Senders Lisk address.|string (address)|
|**Query**|**senderIdOrRecipientId** +
__optional__|Lisk address.|string (address)|
|**Query**|**senderPublicKey** +
__optional__|Senders public key.|string (publicKey)|
|**Query**|**sort** +
__optional__
|Fields to sort results by
|

[cols="",options="header"]
!===
! enum
! amount:asc
! amount:desc
! fee:asc
! fee:desc
! type:asc
! type:desc
! {set:cellbgcolor:red}
timestamp:asc
! timestamp:desc
!===

| {set:cellbgcolor!}
amount:asc
|**Query**|**type** +
__optional__|Transaction type (0-*)|integer|
|===

==== Fees definition (Removed)

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}**dappDeposit** +
__required__|**Example** : `"10000000"`|string
|**dappRegistration** +
__required__|**Example** : `"2500000000"`|string
|**dappWithdrawal** +
__required__|**Example** : `"10000000"`|string
|**delegate** +
__required__|**Example** : `"2500000000"`|string
|**multisignature** +
__required__|**Example** : `"500000000"`|string
|**secondSignature** +
__required__|**Example** : `"500000000"`|string
|**send** +
__required__|**Example** : `"10000000"`|string
|**vote** +
__required__|**Example** : `"100000000"`|string
|===
{set:cellbgcolor!}

[[_transaction]]
==== Transaction definition

[options="header", cols=",,"]
|===
|Name|Description|Schema
|**asset** +
__required__||object
|**blockId** +
__optional__|The ID of the block which this transaction is included in. +
**Length** : `1 - 20` +
**Example** : `"6258354802676165798"`|string (id)
|**confirmations** +
__optional__|Number of times that this transaction has been confirmed by the network.
By forging a new block on a chain, all former blocks and their contained transactions in the chain get confirmed by the forging delegate. +
**Minimum value** : `0`|integer
|**fee** +
__required__|Transaction fee associated with this transaction. +
**Example** : `"1000000"`|string
|**height** +
__optional__|The height of the network, at the exact point in time when this transaction was included in the blockchain. +
**Minimum value** : `1`|integer
|**id** +
__required__|Unique identifier of the transaction.
Derived from the transaction signature. +
**Length** : `1 - 20` +
**Example** : `"222675625422353767"`|string (id)
|{set:cellbgcolor:green}**nonce** +
__required__|Unique sequence of number per account. +
**Example** : `"1"`|string
|{set:cellbgcolor!}
**ready** +
__optional__|Only present in transactions sent from a multisignature account, or transactions type 4 (multisignature registration).
False, if the minimum amount of signatures to sign this transaction has not been reached yet.
True, if the minimum amount of signatures has been reached. +
**Example** : `false`|boolean
|**receivedAt** +
__optional__|The timestamp of the exact point in time where a node discovered a transaction for the first time.|string (date-time)
|**senderId** +
__optional__|Lisk Address of the Senders account. +
**Example** : `"12668885769632475474L"`|string (address)
|**senderPublicKey** +
__required__|The public key of the Senders account. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|{set:cellbgcolor:red}**senderSecondPublicKey** +
__optional__|The second public key of the senders' account, if it exists. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|**signSignature** +
__optional__|Contains the second signature, if the transaction is sent from an account with second passphrase activated. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**signature** +
__required__|Derived from a SHA-256 hash of the transaction object,
that is signed by the private key of the account who created the transaction. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**signatures** +
__optional__|| string (signature)  array
|**timestamp** +
__required__|Time when the transaction was created.
Unix timestamp. +
**Example** : `28227090`|integer
|{set:cellbgcolor:green}**signatures** +
__required__||< string (signature) > array
|{set:cellbgcolor!}
**type** +
__required__|Describes the Transaction type. +
**Minimum value** : `0`|integer
|===

[[_transactionrequest]]
==== TransactionRequest definition

[options="header", cols=",,"]
|===
|Name|Description|Schema
|**asset** +
__required__|Displays additional transaction data.
For example, this can include the vote data or delegate username.|<<_transactionrequest_asset,asset>>
|{set:cellbgcolor:red}
**id** +
__required__|Unique identifier of the transaction.
Derived from the transaction signature. +
**Length** : `1 - 20` +
**Example** : `"222675625422353767"`|string (id)
|{set:cellbgcolor:green}
**fee** +
__required__|Fee for the transaction. +
**Example** : `"1000000"`|string
|**nonce** +
__required__|Unique sequence of number per account. +
**Example** : `"0"`|string
|{set:cellbgcolor!}
**senderPublicKey** +
__required__|The public key of the senders' account. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|{set:cellbgcolor:red}
**signSignature** +
__optional__|Contains the second signature, if the transaction is sent from an account with second passphrase activated. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**signature** +
__required__|Derived from a SHA-256 hash of the transaction object,
that is signed by the private key of the account who created the transaction. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**signatures** +
__optional__|If the transaction is a multisignature transaction, all signatures of the members of the corresponding multisignature group will be listed here.|< string (signature) > array
|**timestamp** +
__required__|Time when the transaction was created.
Unix timestamp. +
**Example** : `28227090`|integer
|{set:cellbgcolor:green}**signatures** +
__required__|Derived from a SHA-256 hash of the transaction object, that is signed by the private key of the account who created the transaction.|< string (signature) > array
|{set:cellbgcolor!}
**type** +
__required__|Describes the transaction type. +
__required__|Describes the Transaction type. +
**Minimum value** : `0`|integer
|===

[[_unlocking]]
==== Unlocking definition (added)

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:green}**amount** +
__required__|Amount the account voted the delegate for in multiples of 10 Lisk. +
**Example** : `"1000000000000"`|string
|**delegateAddress** +
__required__|Lisk address of the delegate the queried account unvoted. +
**Example** : `"12668885769632475474L"`|string (address)
|**unvoteHeight** +
__required__|Height at which the unvote should be valid. +
**Example** : `50000.0`|number
|===
{set:cellbgcolor!}

=== Voters

==== Query
....
GET /voters
....

===== Description
_Attention: At least *one of the filter parameters must be provided.*_
Returns all votes received by a delegate.

===== Parameters

[options="header", cols=",,,,"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**address** +
__optional__|Address of an account.|string (address)|
|**Query**|**limit** +
__optional__|Limit applied to results.|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results.|integer (int32)|`0`
|**Query**|**publicKey** +
__optional__|Public key to query.|string (publicKey)|
|{set:cellbgcolor:red}**Query**|**secondPublicKey** +
__optional__|Second public key to query|string (publicKey)|
|{set:cellbgcolor!}
**Query**|**sort** +
__optional__|Fields to sort results by.|enum (publicKey:asc, publicKey:desc, balance:asc, balance:desc, username:asc, username:desc)|`"publicKey:asc"`
|**Query**|**username** +
__optional__|Delegate username to query.|string (username)|
|===

[[_voter]]
==== Voter definition

[options="header", cols=",,"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk address of the account that voted for the queried delegate. +
**Example** : `"12668885769632475474L"`|string (address)
|{set:cellbgcolor:red}**balance** +
__required__|Balance of the account that voted for the queried delegate. +
**Example** : `"1081560729258"`|string
|{set:cellbgcolor!}
*publicKey** +
__required__|Public key of the account that voted for the queried delegate. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|{set:cellbgcolor:green}**votes** +
__required__|All votes the voter for the queried delegate voted for.|< <<_vote,Vote>> > array
|===
{set:cellbgcolor!}

=== Votes

==== Query
....
GET /votes
....


===== Description
_Attention: At least *one of the filter parameters must be provided.*_
Returns all votes placed by an account.


===== Parameters

[options="header", cols=",,,,"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**address** +
__optional__|Address of an account.|string (address)|
|**Query**|**limit** +
__optional__|Limit applied to results.|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results.|integer (int32)|`0`
|**Query**|**publicKey** +
__optional__|Public key to query.|string (publicKey)|
|{set:cellbgcolor:red}**Query**|**secondPublicKey** +
__optional__|Second public key to query|string (publicKey)|
|{set:cellbgcolor!}
**Query**|**sort** +
__optional__|Fields to sort results by.|enum (username:asc, username:desc, balance:asc, balance:desc)|`"username:asc"`
|**Query**|**username** +
__optional__|Delegate username to query.|string (username)|
|===

[[_vote]]
==== Vote definition

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:red}
**address** +
__required__|Lisk address of the delegate the queried account voted for. +
**Example** : `"12668885769632475474L"`|string (address)
|{set:cellbgcolor:green}
**amount** +
__required__|Amount the account voted the delegate for in multiples of 10 Lisk. +
**Example** : `"1000000000000"`|string
|**delegateAddress** +
__required__|Lisk address of the delegate the queried account voted for. +
**Example** : `"12668885769632475474L"`|string (address)
|{set:cellbgcolor:red}
**balance** +
__required__|Balance of the delegate the queried account voted for. +
**Example** : `"1081560729258"`|string
|**publicKey** +
__required__|Public key of the delegate the queried account voted for. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**username** +
__required__|Username of the delegate the queried account voted for. +
**Example** : `"liskhq"`|string (username)
|===
{set:cellbgcolor!}

[[_votewithdelegateproperties]]
==== VoteWithDelegateProperties definition (added)

[options="header", cols=",,"]
|===
|Name|Description|Schema
|{set:cellbgcolor:green}**amount** +
__required__|Amount the account voted the delegate for in multiples of 10 Lisk. +
**Example** : `"1000000000000"`|string
|**delegate** +
__required__|Delegate properties of the delegate for this vote.|object
|**delegateAddress** +
__required__|Lisk address of the delegate the queried account voted for. +
**Example** : `"12668885769632475474L"`|string (address)
|===
