= Glossary and Abbreviations
Chris Braithwaite <christopher.braithwaite@lightcurve.io>
:description: SDK glossary of terms from A to Z.
:toc:
:imagesdir: ../../assets/images
:page-no-next: true

:idprefix:
:idseparator: -

:url_aes: https://proprivacy.com/guides/aes-encryption
:url_bch_codes: https://en.wikipedia.org/wiki/BCH_code#:~:text=In%20coding%20theory%2C%20the%20BCH,(also%20called%20Galois%20field).&text=This%20simplifies%20the%20design%20of,small%20low%2Dpower%20electronic%20hardware
:url_rocksdb: https://rocksdb.org/
:url_semver: https://semver.org/

:url_delegate_misbehavior: protocol:transactions.adoc#pom
:url_del_misbehavior: dpos-module.adoc#discover
:url_protocol_transactions_pom: protocol:transactions.adoc#pom
:url_dpos: dpos-module.adoc#dpos
:url_delegate_registration: dpos-module.adoc#delegate_registration
:url_delegate_registration_tx: protocol:transactions.adoc#delegate

:url_genesis_block: protocol:blocks.adoc#genesis-block
:url_reclaim_lsk: protocol:mainnet.adoc#transactions
:url_multisignature: protocol:transactions.adoc#multisignature
:url_token_transfer: protocol:transactions.adoc#transfer
:url_token_unlock: protocol:transactions.adoc#unlock
:url_data_structure: references/schemas.adoc#data-types

== A
=== Account

An account consists of a unique identifier / <<account-address,address>>, an amount of tokens referred to as balance and possibly some additional properties used in other parts of the blockchain application.

=== Account Address

Addresses are unique identifiers for accounts in the Lisk blockchain.
They are the 20-byte hash value of the public key that controls the account initially.
In all front-end products, addresses are displayed in a human-readable representation called <<Lisk32-representation>>.
An example for an address in Lisk32 presentation is `lskxwnb4ubt93gz49w3of855yy9uzntddyndahm6s`.
When referring to addresses in Lisk, we always assume the Lisk32 representation, without explicitly having to mention it.
In the Lisk protocol and SDK only the 20 byte value is stored for efficiency and sometimes the hexadecimal representation of the address is used.
Further details regarding other address representations can be seen here in the xref:{url_data_structure}[table for different data types] on the schema reference page.

=== Active Delegate

An active delegate can mostly be considered as a forging delegate, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.

=== AES-256-CBC - Advanced Encryption Standard

The Advanced Encryption Standard (AES), has a key length of 256 bits and is a block cipher adopted as an encryption standard by the U.S. government for military and government use. CBC (Cipher Blocker Chaining), is an advanced form of block cipher encryption. A detailed description of how AES functions can be found {url_aes}[here^].

=== API - Application Programming Interface

An application programming interface is a software intermediary that allows two applications to talk to each other.

== B

=== BCH Codes - Bose, Chaudhuri and Hocquenghem codes

BCH codes are error-correcting codes. The Bose, Chaudhuri and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
large class of powerful random error-correcting cyclic codes.

=== Beddow

The smallest unit of account. 100 million Beddows make one LSK.

=== Betanet

A temporary, public testing network for the Lisk Core beta candidate.

=== BFT - Byzantine Fault Tolerance

In a system whereby components need to come to an agreement to reach consensus,  byzantine failures will prevent those components from reaching an agreement, (usually caused by errors that are hard to detect).
A Byzantine Fault Tolerant system ensures that measures are taken to manage such failures.

=== BIP - Bitcoin Improvement Proposal

For example, a BIP39 describes the mnemonic code or mnemonic sentence implementation. It is a protocol that describes how to create a human readable mnemonic sentence and how to convert that mnemonic into a seed.

=== Blockchain Application

An application running on its own blockchain built with the Lisk SDK.

=== Blockchain App

Short form of blockchain application.

=== Block Header

A block is composed of a block header and a payload of transactions. The block header contains all information related to the block as well as a hash of the payload.

=== Block Height

The number of blocks in the blockchain between the genesis block and the block of the specified block height.

=== Block ID

A hash of a block header that uniquely identifies a block in the Lisk blockchain.

== C

=== CDN - Content Delivery Network

A content delivery network, or content distribution network, is a geographically distributed network of proxy servers and their data centers.

=== CORS - Cross Origin Resource Sharing

Cross Origin Resource Sharing is a protocol that enables scripts running on a browser client to interact with resources from a different origin.

=== CRUD - Create, Read, Update & Delete

CRUD refers to the four functions that are considered necessary to implement a persistent storage application, namely create, read, update and delete.

=== Custom Transaction

A new transaction type with its own logic for a blockchain application. Typically there is a state change on the blockchain.

== D

=== Delegate

An account which performed the delegate registration and is now able to receive votes.

=== Delegate Misbehaviour Report

A xref:{url_delegate_misbehavior}[delegate misbehavior report] refers to a transaction type on the Mainnet which reports a delegates misbehavior. +
Any misbehavior of a delegate is xref:{url_discover_misbehavior}[indicated] by two contradicting block headers signed by the delegate.

=== Delegate Registration

A xref:{url_delegate_registration}[delegate registration] is achieved by sending a xref:{url_delegate_registration_tx}[delegate registration transaction], which registers a delegate to participate in the Delegated Proof-of-Stake consensus algorithm.

=== Delegate Vote

For a delegate to cast a vote they are required to specify how much Lisk will be voted or unvoted with each vote. Furthermore, the Lisk address of the delegate is used, as opposed to the public key in the previous implementation. +
In addition, the weight of a delegate will determine the sum of all votes for this delegate. Hence, to maintain a secure and effective setup, the delegate weight is bound to 10 times the self-votes.

=== Devnet

A blockchain network for development purposes.
The Lisk SDK provides dedicated genesis block and configurations to conveniently set up a local Devnet during development of a blockchain application.

=== DHCP - Dynamic Host Configuration Protocol

The Dynamic Host Configuration Protocol can be defined as a client/server protocol that automatically provides a host with its IP address. This also includes additional related configuration information such as the default gateway and the subnet mask.

=== DPoS - Delegated Proof of Stake

xref:{url_dpos}[DPoS] is the mechanism of determining eligible block creators achieved by voting for registered delegate accounts, which are then able to create blocks depending on their vote weight.
It is part of the consensus algorithm of a blockchain and used on Lisk Mainnet and in the Lisk SDK.

== E

=== Ed25519 - High Speed High Security Signature

Ed25519 is a public-key signature system with several attractive features: Fast single-signature verification.
Ed25519 signatures are elliptic-curve signatures, carefully engineered at several levels of design and implementation to achieve very high speeds without compromising security.

== F

=== FireHOL

FireHOL is a shell script designed as a wrapper for iptables written in order to ease the customization of the Linux kernel's firewall netfilter.
FireHOL does not have a graphical user interface, but is configured through a user-friendly and easy to understand plain text configuration file.

=== Forging

How delegates produce new blocks on the Lisk blockchain.

=== Fork

A fork in the network is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.

=== Framework Plugin

A self-contained, off chain component which extends the standard feature set of the Lisk SDK by a specific use case, e.g. a node monitor plugin or delegate forging plugin.
Typically there is no state change on the blockchain.


== G

=== Genesis Block

The xref:{url_genesis_block}[genesis block] describes the very first block in the blockchain.
It defines the initial state of the blockchain on start of the network.
A genesis block must be given to the application, and all networks should have a different genesis block.

== H

=== Hash Onion

This is the onion of hashes used by the delegate.

== I

=== IoT - Internet of Things

The Internet of Things refers to a wide variety of physical ''things'' or objects that are embedded with some form of technology, i.e. software and sensors to enable connection possibilities with other systems and devices over the Internet.

=== IPC - Inter Process Communication

Inter process communication is defined as a set of programming interfaces allowing programmers to coordinate activities between various program processes that can run simultaneously.

=== IV - Initialization Vector

An initialization vector (IV) is classed as an arbitrary number that can be used in conjuction with a secret key for data encryption.
This can also be referred to as a nonce.

=== IPv4 - Internet Protocol Version 4

Internet Protocol version 4 is the fourth version of the Internet Protocol.

=== IPv6 - Internet Protocol Version 6

Internet Protocol version 6 is the latest up to date version of the Internet Protocol

== J

=== JSON - JavaScript Object Notation

JSON is a syntax for storing and exchanging data and is text written with JavaScript object notation.

== K

== L

=== LDR - Light Dependent Resistor

A light dependent resistor is a passive component, whereby when it is exposed to light the internal resistance changes according to the light intensity that falls upon it. Hence, they are deployed in light sensing circuits.

=== LIP - Lisk Improvement Proposal

A LIP is a document usually structured by the research team defining technical changes in the Lisk protocol.
In addition, it can also cover an implementation or a non technical process surrounding Lisk.
Furthermore, a LIP also describes the requirements, rationale and motivation for the required changes.
=== Lisk32 representation

The Lisk32 representation of <<account-addresses>> starts with the letters "lsk" followed by a custom Base32 encoding of the 20 bytes of the address appended with a BCH checksum.
The checksum is used to check for small errors in the address.
Any errors in up to 4 characters are guaranteed to be detected and errors in more than 5 characters are likely to be detected.
The choice of the Lisk32 representation of addresses does not modify the address, but is introduced to provide a safer and more pleasant experience to users.

// === Lisk Ecosystem

// The Lisk ecosystem represents the third party environment of Lisk, e.g. community members, exchanges, sidechains.

// === Lisk Foundation

// The non profit entity governing Lisk. This is based in Zug, Switzerland.

// === Lisk for Desktop

// Official Lisk wallet for desktop platforms.

// === Lisk for Mobile

// Official Lisk wallet for mobile platforms.

=== LSK

The token used in the Lisk Mainnet.

=== LSK reclaim

This transaction is only part of Lisk Core and not the Lisk SDK.
A xref:{url_reclaim_lsk}[LSK reclaim] transaction type on the Mainnet converts a previously non-initialized legacy account’s address to the new address system.
This is required because the public key is required to convert from the old address system to the new address system.
Non-initialized accounts don’t have a public key associated with them yet.

=== LTS - Long Term Support

LTS is an acronym for long term support, and is applied to release lines that will be supported and maintained, to ensure any critical bugs will be fixed for an extended period of time.

== M

=== Mainnet

The official main network of Lisk.

=== Multisignature Group Registration

A transaction type on all networks based on the Lisk protocol which registers a xref:{url_multisignature}[multisignature group].
This transaction registers the sender account as a multisignature group account. 

== N

=== Node

A blockchain application built with the Lisk SDK, e.g. Lisk Core, which is connected to other nodes.
Together, they form a blockchain network.
Nodes fulfill many important roles in the network, like synchronising new events in the network between each other, adding new blocks to the blockchain, and providing APIs for external services in order to communicate with the network.

=== Nonce

A nonce is an abbreviation for "number only used once" and is a random number that can only be used one time. Nonces have a multitude of applications in cryptographic processes such as authentication, hashing, identification, electronic signatures, etc. +
This can be a timestamp or a special marker intended to prevent unauthorized reproductions of a file.
Nonces are generated for a specific purpose and are most commonly used to modify the result of a function in a cryptographic communication.

=== NPM - Node Package Manager

NPM is the default package manager for the JavaScript runtime environment Node.js.

== O

== P

=== Package

NPM distribution of a library.

=== Passphrase

A set of 12 words used to access an <<account>>.

=== PBKDF2 - Password Based Key Derivation Function 2

PBKDF2 can be defined as key derivation functions with a sliding computational cost, in order to reduce vulnerabilities to brute force attacks.

=== Peer

A node interacting with other nodes on a Lisk network, e.g. Lisk’s mainnet.

=== PoC - Proof of Concept

Short form of proof of concept blockchain application.

=== PoS - Proof of Stake

Proof of Stake is a type of consensus mechanism used to achieve agreement over a distributed network. With PoS the consensus is determined based upon the stake of each user in the network. +
With PoS users are required to stake their tokens in order to become a validator in the network. Validators are responsible for ordering transactions and creating new blocks, so that all nodes are able to agree on the current state of the network.

=== PoW - Proof of Work

Proof of Work is the original type of consensus mechanism used to achieve agreement over a distributed network. With PoW in order to complete the transactions on a given network, the miners have to solve complex mathematical problems in order to be rewarded with the tokens. +
In a nutshell, the PoW consensus algorithm is used to confirm transactions and produce new blocks to the chain. The miners have to compete against each other to complete transactions on the network to receive their rewards. Hence, the PoW mechanism allows consensus to be reached whilst simultaneously maintaining the network security.

=== P2P - Peer to Peer

A peer to peer network is a group of nodes (devices), that make up a decentralized network that can collectively share and store data, whereby each node acts as an individual peer.

== Q

== R

=== Release Candidate

A proposed new version of Lisk Core for the testnet. +
A release candidate can be described as a SW build released internally for testing purposes and not usually for production deployment. It is also defined as a version of the software, which should be functional but not necessarily ready to be released.

=== REST - Representational State Transfer

REST refers to the Representational State Transfer, which is a client-server, stateless, cacheable communications protocol.
In the majority of cases HTTP is used.

=== RocksDB

{url_rocksdb}[RocksDB^] is a high performance embedded database.
An embedded persistent key value store for fast storage.

=== RPC - Remote Procedure Call

RPC is a request–response protocol.
An RPC is initiated by the client, which sends a request message to a known remote server to execute a specified procedure with supplied parameters.
The remote server sends a response to the client, and the application continues its process.

== S

=== SDK - Software Development Kit

The set of tools that allow you to build blockchain applications replicating Lisk’s technology stack and architecture.

=== SemVer

Semantic versioning (also referred as SemVer), is a versioning system that provides a universal way of versioning software development projects in order to track changes and updates, such as plugins, add-ons, libraries and extensions. +
Further details regarding SemVer can be found {url_semver}[here^].

=== SHA-256 - Secure Hash Algorithm 256

The SHA is a 256 bit algorithm designed for cryptographic security.

=== Standby Delegate

A standby delegate, as each delegate is not an <<active-delegate>>.
Rank 102-∞.

== T

=== Testnet

The official testing network of Lisk.

=== TLS ALPN - Transport Layer Security Application-Layer Protocol Negotiation

TLS is the transport layer security.
The application-layer protocol negotiation is a transport layer security extension that allows the application layer to negotiate over a secure connection which protocol should be performed.
This occurs in a manner that avoids additional round trips and which is independent of the application-layer protocols.

=== Token

A token refers to LSK or any sidechain token. A  digital token is designated to a cryptocurrency that is built on top of an existing blockchain, and represents a particular tradable and fungible asset.

=== Transaction

An interaction with the Lisk blockchain which permanently writes data to it.
A transaction can have multiple purposes, e.g. a balance transfer or a delegate registration.

=== Token transfer

A transaction type which transfers tokens from one account to another one.
A xref:{url_token_transfer}[token transfer] transaction will transfer the amount of tokens specified in the amount property, from the sender of the transaction to the specified recipient.

=== Transaction fee

An amount of LSK needed to send a transaction on the Lisk blockchain.

=== Transaction ID

A hash of a transaction that uniquely identifies a transaction.

=== Transaction Message

A custom message you can attach to a <<token-transfer>>.

=== Token unlock

The xref:{url_token_unlock}[token unlock] transaction unlocks the tokens which have been locked previously by voting for a specific delegate.
The delegate needs to be unvoted before unlocking the tokens by sending a <<delegate-vote>> transaction.

== U

=== UI - User Interface

The space where computer systems and humans interact.

=== UTF-8 - Unicode Transformation Format 8

UTF-8 is a variable width encoding system which enables the translation of any unicode charater to a matching binary string.

=== URL - Uniform Resource Locator

A URL is a reference to a web resource and possesses a mechanism for retrieving the web site specified in the URL.

=== UTXO - Unspent Transaction Output

UTXO is an unspent output.
In other words it can be thought of as an indivisible chunk of a token, which is under the control of the private keys belonging to the owners.

== V

=== Voter

An account deploying their LSK to vote for their favourite delegates.

== W

=== Wallet

Wallets can be broken down into three distinct categories: Software, Hardware, and Paper wallets. Software wallets can be defined as either desktop, mobile or online. +
In short a wallet will store the public and private keys and can interface with various blockchains, enabling the users to monitor their balance, send tokens and conduct other operations. +
A Lisk wallet is available on both Lisk Desktop and Lisk Mobile.
They are actively maintained and provide the most secure and easiest way to access the users LSK tokens.

== X

== Y

== Z
