= Glossary of Abbreviations
Mona Bärenfänger <mona@lightcurve.io>
:description: SDK glossary of terms from A to Z.
:toc: preamble
:imagesdir: ../../assets/images
:page-no-next: true



== A

=== API - Application Programming Interface +

An application programming interface is a software intermediary that allows two applications to talk to each other.

=== AES-256-CBC - Advanced Encryption Standard +

The Advanced Encryption Standard (AES), has a key length of 256 bits and is a block cipher adopted as an encryption standard by the U.S. government for military and government use. CBC (Cipher Blocker Chaining) is an advanced form of block cipher encryption.

== B

=== BCH Codes - Bose, Chaudhuri, and Hocquenghem codes +

BCH are cyclic codes. The Bose, Chaudhuri, and Hocquenghem (BCH) codes form a
large class of powerful random error-correcting cyclic codes.

=== BIP - Bitcoin Improvement Proposal +

For example, a BIP39 describes the mnemonic code or mnemonic sentence implementation. It is a protocol that describes how to create a human readable mnemonic sentence and how to convert that mnemonic into a seed.

=== BFT - Byzantine Fault Tolerance +

In a system whereby components need to come to an agreement to reach consensus,  byzantine failures will prevent those components from reaching an agreement, (usually caused by errors that are hard to detect).
A Byzantine Fault Tolerant system ensures that measures are taken to manage such failures.

== C

=== CDN - Content Delivery Network +

A content delivery network, or content distribution network, is a geographically distributed network of proxy servers and their data centers.

=== CLI - Command Line Interface +

A command line interface is a text-based interface used for inputting commands.

=== CORS - Cross Origin Resource Sharing +

Cross-Origin Resource Sharing is a protocol that enables scripts running on a browser client to interact with resources from a different origin.

=== CRUD - Create, Read, Update & Delete +

CRUD refers to the four functions that are considered necessary to implement a persistent storage application, namely create, read, update and delete.

== D

=== DHCP - Dynamic Host Configuration Protocol +

The Dynamic Host Configuration Protocol can be defined as a client/server protocol that automatically provides a host with its IP address. This also includes additional related configuration information such as the default gateway and the subnet mask.

=== DPoS - Delegated Proof of Stake +

DPoS is a consensus algorithm which ensures reliable approval and verification of transactions in a blockchain.

== E

=== Ed25519 - High Speed High Security Signature +

Ed25519 is a public-key signature system with several attractive features: Fast single-signature verification.
Ed25519 signatures are elliptic-curve signatures, carefully engineered at several levels of design and implementation to achieve very high speeds without compromising security.

== F

=== Fork +

A fork in the network is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.

== G

=== Genesis Block +

The first actual block created in the blockchain.

== H

=== Hash Onion +

This is the onion of hashes used by the delegate.

== I

=== IoT - Internet of Things +

The Internet of Things refers to a wide variety of physical ''things'' or objects that are embedded with some form of technology, i.e. software and sensors to enable connection possibilities with other systems and devices over the Internet.

=== IPC - Inter Process Communication +

Inter process communication is defined as a set of programming interfaces allowing programmers to coordinate activities between various program processes that can run simultaneously.

=== IV - Initialization Vector  +

An initialization vector (IV) is classed as an arbitrary number that can be used in conjuction with a secret key for data encryption. This can also be referred to as a nonce.

=== IPv4 - Internet Protocol Version 4 +

Internet Protocol version 4 is the fourth version of the Internet Protocol.

=== IPv6 - Internet Protocol Version 6 +

Internet Protocol version 6 is the flatest up to date version of the Internet Protocol

== J

=== JSON - JavaScript Object Notation +

JSON is a syntax for storing and exchanging data and is text written with JavaScript object notation.

== K

== L

=== LDR - Light Dependent Resistor +

A light dependent resistor is a passive component, whereby when it is exposed to light the internal resistance changes according to the light intensity that falls upon it. Hence, they are deployed in light sensing circuits.

=== LIP - Lisk Improvement Proposal +

A LIP is a document usually structured by the research team defining technical changes in the Lisk protocol. In addition, it can also cover an implementation or a non-technical process surrounding Lisk. Furthermore, a LIP also describes the requirements, rationale and motivation for the required changes.

=== LSK - The name of our utility token +

The LSK token is used to pay for transaction fees on the Lisk blockchain.

== M

== N

=== NPM - Node Package Manager +

A configurable package manager used for the node JavaScript platform. It can manage dependency conflicts and put modules in place so that node can locate them.

== O

== P

=== PBKDF2 - Password Based Key Deriviation Function 2 +

PBKDF2 can be defined as key deriviation functions with a sliding computational cost, in order to reduce vulnerabilities to brute force attacks.

=== PoM - Proof of Misbehavior +

A 'proof of misbehavior' transaction allows users to reveal to the network any BFT violation.

=== PoS - Proof of Stake +

Proof of Stake is a type of consensus mechanism used to achieve agreement over a distributed network. With PoS the consensus is determined based upon the stake of each user in the network.

=== PoS - Proof of Work +

Proof of Work is is a type of consensus mechanism used to achieve agreement over a distributed network. With PoW in order to complete the transactions on a given network, the miners have to solve complex mathematical problems in order to be rewarded with the tokens.

=== P2P - Peer to Peer +

A peer to peer network is a group of nodes (devices), that make up a decentralized network that can collectively share and store data, whereby each node acts as an individual peer.

== Q

== R

=== REST - Representational State Transfer +

REST refers to the Representational State Transfer, which is a client-server, stateless, cacheable communications protocol. In the majority of cases HTTP is used.

=== RocksDB - A high performance embedded database +

An embedded persistent key value store for fast storage.

=== RPC - Remote Procedure Call +

RPC is a session protocol which enable a host to make a procedure call that appears to be local, however it has the ability to execute remotely on a separate machine connected to the network.

== S

=== SHA-256 - Secure Hash Algorithm 256 +

The SHA is a 256 bit algorithm designed for cryptographic security.

== T

== U

=== UI - User Interface +

The space where computer systems and humans interact.

=== UTF-8 - Unicode Transformation Format 8 +

UTF-8 is a variable width encoding system which enables the translation of any unicode charater to a matching binary string.

=== URL - Uniform Resource Locator +

A URL is a reference to a web resource and possesses a mechanism for retrieving the web site specified in the URL.

=== UTXO - Unspent Transaction Output +

UTXO is an unspent output. In other words it can be thought of as an indivisible chunk of a token which is under the control of the private keys belonging to the owners.

== V

== W

== X

== Y

== Z


