= Glossary

:description: SDK glossary of terms from A to Z.
:toc: preamble
:imagesdir: ../../assets/images
:page-no-next: true



== A

=== API - Application Programming Interface +

An application programming interface is a software intermediary that allows two applications to talk to each other.

=== AES-256-CBC - Advanced Encryption Standard +

The Advanced Encryption Standard (AES), has a key length of 256 bits and is a block cipher adopted as an encryption standard by the U.S. government for military and government use. CBC (Cipher Blocker Chaining) is an advanced form of block cipher encryption.

== B

=== BCH Codes - Bose, Chaudhuri, and Hocquenghem codes +

BCH are cyclic codes. The Bose, Chaudhuri, and Hocquenghem (BCH) codes form a
large class of powerful random error-correcting cyclic codes.

=== BIP - Bitcoin Improvement Proposal +

For example, a BIP39 describes the mnemonic code or mnemonic sentence implementation. It is a protocol that describes how to create a human readable mnemonic sentence and how to convert that mnemonic into a seed.

=== BFT - Byzantine Fault Tolerance +

In a system whereby components need to come to an agreement to reach consensus,  byzantine failures will prevent those components from reaching an agreement, (usually caused by errors that are hard to detect).
A Byzantine Fault Tolerant system ensures that measures are taken to manage such failures.

== C

=== CDN - Content Delivery Network +

A content delivery network, or content distribution network, is a geographically distributed network of proxy servers and their data centers.

=== CLI - Command Line Interface +

A command line interface is a text-based interface used for inputting commands.

=== CORS - Cross Origin Resource Sharing +

Cross-Origin Resource Sharing is a protocol that enables scripts running on a browser client to interact with resources from a different origin.

=== CRUD - Create, Read, Update & Delete +

CRUD refers to the four functions that are considered necessary to implement a persistent storage application, namely create, read, update and delete.

== D

=== DHCP - Dynamic Host Configuration Protocol +

The Dynamic Host Configuration Protocol can be defined as a client/server protocol that automatically provides a host with its IP address. This also includes additional related configuration information such as the default gateway and the subnet mask.

=== DPoS - Delegated Proof of Stake +

DPoS is a consensus algorithm which ensures reliable approval and verification of transactions in a blockchain.

== E

=== Ed25519 - High speed high security signature +

Ed25519 is a public-key signature system with several attractive features: Fast single-signature verification.
Ed25519 signatures are elliptic-curve signatures, carefully engineered at several levels of design and implementation to achieve very high speeds without compromising security.

== F

=== Fork +

A fork in the network is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.

== G

=== Genesis Block +

The first actual block created in the blockchain.

== H

=== Hash Onion +

This is the onion of hashes used by the delegate.

== I

=== IPC - Inter Process Communication +

Inter process communication is defined as a set of programming interfaces allowing programmers to coordinate activities between various program processes that can run simultaneously.

=== IV - Initialization Vector  +

An initialization vector (IV) is classed as an arbitrary number that can be used in conjuction with a secret key for data encryption. This can also be referred to as a nonce.

== J





== K







== L






== M






==== N






==== O





==== P





==== Q





==== R





==== S





==== T






==== U






==== V






==== W




==== X





==== Y




==== Z


