= Glossary and Abbreviations
Mona Bärenfänger <mona@lightcurve.io>
:description: SDK glossary of terms from A to Z.
:toc: preamble
:imagesdir: ../../assets/images
:page-no-next: true



== A

=== Account +

How we describe the overarching account based on an email address.

=== Active Delegate +

Each delegate able to forge new blocks for the Lisk blockchain. Rank 1-101.

=== Address +

A human-readable representation of a public key on the Lisk blockchain, e.g. 8746385184555771012L.

=== Address Initialization +

The process of sending the first transaction on the Lisk blockchain. With that the public key is permanently stored as part of your address in the Lisk blockchain and checked every time you send a transaction. This means no one can access your account, even in the very rare case of an address collision.

=== AES-256-CBC - Advanced Encryption Standard +

The Advanced Encryption Standard (AES), has a key length of 256 bits and is a block cipher adopted as an encryption standard by the U.S. government for military and government use. CBC (Cipher Blocker Chaining) is an advanced form of block cipher encryption.

=== Alphanet +

A temporary, internal-only testing network of a Lisk Core alpha candidate.

=== Alpha Candidate +

A proposed new version of Lisk Core for an Alphanet.

=== Alpha Stage +

The stage the Lisk SDK is in while Security and Reliability, Network Economics, Network Consensus, and Network Longevity is being implemented.

=== API - Application Programming Interface +

An application programming interface is a software intermediary that allows two applications to talk to each other.

=== Avatar +

The default image of an address which is being auto generated.

== B

=== BCH Codes - Bose, Chaudhuri and Hocquenghem codes +

BCH are cyclic codes. The Bose, Chaudhuri and Hocquenghem (BCH) codes form a
large class of powerful random error-correcting cyclic codes.

=== Beddow +

The smallest unit of account. 100 million beddows make one LSK.

=== Betanet +

A temporary, external testing network of a Lisk Core beta candidate.

=== Beta Candidate +

A proposed, new version of Lisk Core for a Betanet.

=== Beta Stage +

The stage the Lisk SDK is in while Blockchain Interoperability is being implemented.

=== BFT - Byzantine Fault Tolerance +

In a system whereby components need to come to an agreement to reach consensus,  byzantine failures will prevent those components from reaching an agreement, (usually caused by errors that are hard to detect).
A Byzantine Fault Tolerant system ensures that measures are taken to manage such failures.

=== BIP - Bitcoin Improvement Proposal +

For example, a BIP39 describes the mnemonic code or mnemonic sentence implementation. It is a protocol that describes how to create a human readable mnemonic sentence and how to convert that mnemonic into a seed.

=== Blockchain Application Platform +

A blockchain application can be launched on the Lisk blockchain application platform.

=== Blockchain Application +

An application running on its own blockchain built with the Lisk SDK.

=== Blockchain App +

Short form of blockchain application.

=== Block Header +

A block is composed of a block header and a payload of transactions. The block header contains all information related to the block as well as a hash of the payload.

=== Block Height +

The number of blocks in the blockchain between the genesis block and the block of the specified block height.

=== Block ID +

A hash of a block header that uniquely identifies a block in the Lisk blockchain.

=== Bug +

An unwanted outcome in a Lisk product.

== C

=== Candidate +

A new version of Lisk Core.

=== CDN - Content Delivery Network +

A content delivery network, or content distribution network, is a geographically distributed network of proxy servers and their data centers.

=== CEO - Chief Executive Officer +

Position title of Max Kordek in relation to the Lisk project.

=== CLI - Command Line Interface +

A command line interface is a text-based interface used for inputting commands.

=== Community +

An international group of followers and enthusiasts of Lisk. They can be found across various channels spanning Twitter, Reddit, Discord and offline meetups.

=== Community Member +

A member of the Lisk community.

=== Contractors +

How the Lisk Foundation refers to third-party companies during a contractual relationship, e.g. Lightcurve GmbH, Wachsman Inc.

=== CORS - Cross Origin Resource Sharing +

Cross Origin Resource Sharing is a protocol that enables scripts running on a browser client to interact with resources from a different origin.

=== CRUD - Create, Read, Update & Delete +

CRUD refers to the four functions that are considered necessary to implement a persistent storage application, namely create, read, update and delete.

=== CTO - Chief Technical Officer +

Position title of Oliver Beddows in relation to the Lisk project.

=== Custom Transaction +

A new transaction type with its own logic for a blockchain application. Typically there is a state change on the blockchain.

== D

=== Delegate +

A Lisk account which performed the delegate registration and is now able to receive votes.

=== Delegate Misbehaviour Report (previously called `Proof-of-Misbehavior` or `PoM`) +

A transaction type on Mainnet which reports a delegate misbehavior.

=== Delegate Pool +

A group of delegates e.g. Elite, GDT.

=== Delegated Proof-of-Stake +

The mechanism of determining eligible block creators via voting for registered delegate accounts, which then can create blocks depending on their vote weight. It is part of the consensus algorithm of a blockchain and used on Lisk Mainnet and in the Lisk SDK.

=== Delegate Registration +

A transaction type on Mainnet which registers a delegate to participate in the Delegated Proof-of-Stake consensus algorithm.

=== Delegate Vote (previously called `vote`) +

A transaction type on Mainnet which submits votes for delegates. If the votes are positive it adds the voting weight, if they are negative it removes the voting weight again. If voting weight was added, the corresponding LSK are locked and cannot be used for any other transaction.

=== Developer +

The target audience who is using Lisk Core and Lisk SDK. This includes all kinds of technical people.

=== Devnet +

A temporary, internal-only testing network running on an individual developer’s machine during development.

=== DHCP - Dynamic Host Configuration Protocol +

The Dynamic Host Configuration Protocol can be defined as a client/server protocol that automatically provides a host with its IP address. This also includes additional related configuration information such as the default gateway and the subnet mask.

=== DPoS - Delegated Proof of Stake +

DPoS is a consensus algorithm which ensures reliable approval and verification of transactions in a blockchain.

== E

=== Ed25519 - High Speed High Security Signature +

Ed25519 is a public-key signature system with several attractive features: Fast single-signature verification.
Ed25519 signatures are elliptic-curve signatures, carefully engineered at several levels of design and implementation to achieve very high speeds without compromising security.

== F

=== Feature +

A new functionality added to a Lisk product.

=== Forge +

How delegates produce blocks on the Lisk blockchain.

=== Fork +

A fork in the network is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.

=== Framework Plugin +

A self-contained, off-chain module which extends the standard feature-set of the Lisk SDK by a specific use-case, e.g. a node monitor plugin or delegate forging plugin. Typically there is no state change on the blockchain.


== G

=== Genesis Block +

The first actual block created in the blockchain.

== H

=== Hash Onion +

This is the onion of hashes used by the delegate.

== I

=== ICO - Initial Coin Offering +

The crowdfunding Max Kordek and Oliver Beddows did in February and March 2016.

=== IoT - Internet of Things +

The Internet of Things refers to a wide variety of physical ''things'' or objects that are embedded with some form of technology, i.e. software and sensors to enable connection possibilities with other systems and devices over the Internet.

=== IPC - Inter Process Communication +

Inter process communication is defined as a set of programming interfaces allowing programmers to coordinate activities between various program processes that can run simultaneously.

=== IV - Initialization Vector  +

An initialization vector (IV) is classed as an arbitrary number that can be used in conjuction with a secret key for data encryption. This can also be referred to as a nonce.

=== IPv4 - Internet Protocol Version 4 +

Internet Protocol version 4 is the fourth version of the Internet Protocol.

=== IPv6 - Internet Protocol Version 6 +

Internet Protocol version 6 is the flatest up to date version of the Internet Protocol

== J

=== JSON - JavaScript Object Notation +

JSON is a syntax for storing and exchanging data and is text written with JavaScript object notation.

== K

== L

=== LDR - Light Dependent Resistor +

A light dependent resistor is a passive component, whereby when it is exposed to light the internal resistance changes according to the light intensity that falls upon it. Hence, they are deployed in light sensing circuits.

=== LIP - Lisk Improvement Proposal +

A LIP is a document usually structured by the research team defining technical changes in the Lisk protocol. In addition, it can also cover an implementation or a non-technical process surrounding Lisk. Furthermore, a LIP also describes the requirements, rationale and motivation for the required changes.

=== Lisk +

Overarching term for the entire project.

=== Lisk Ecosystem +

The Lisk ecosystem represents the third-party environment of Lisk, e.g. community members, exchanges, sidechains.

=== Lisk Foundation +

The non-profit entity governing Lisk. This is based in Zug, Switzerland.

=== Lisk Foundation Council +

How we refer to the Lisk Foundation’s governing body. Consisting of Max, Oliver and Benedikt.

=== Lisk for Desktop +

Our wallet for desktop platforms.

=== Lisk for Mobile +

Our wallet for mobile platforms.

=== LSK +

The token for the Lisk blockchain application platform.

=== LSK holder +

A person in possession of LSK.

=== LSK reclaim (previously called `reclaim`) +

A transaction type on Mainnet which converts a previously non-initialized account’s address to the new address system. This is required because the public key is required to convert from the old address system to the new address system. Non-initialized accounts don’t have a public key associated with them yet.

== M

=== Mainnet +

The official main network of Lisk.

=== multisignature group registration (previously called `multisignature registration`) +

A transaction type on all networks based on the Lisk protocol which registers a multisignature group.

== N

=== Node +

A server having Lisk Core installed and therefore being part of a Lisk network, e.g. Lisk’s mainnet.

=== NPM - Node Package Manager +

A configurable package manager used for the node JavaScript platform. It can manage dependency conflicts and put modules in place so that node can locate them.

== O

=== Objective +

An individual goal on the Lisk Roadmap e.g. "Improve multi-signature solution".

== P

=== Package +

Distribution of a library.

=== Passphrase +

A set of 12 words used to access the Lisk address.

=== PBKDF2 - Password Based Key Derivation Function 2 +

PBKDF2 can be defined as key derivation functions with a sliding computational cost, in order to reduce vulnerabilities to brute force attacks.

=== Peer +

A node interacting with other nodes on a Lisk network, e.g. Lisk’s mainnet.

=== Phase +

How we refer to groups of objectives on the Lisk Roadmap e.g. Network Consensus.

=== Platform Development Team +

Led by Oliver Beddows.

=== PoC - Proof of Concept +

Short form of proof of concept blockchain application.

=== PoM - Proof of Misbehavior +

A 'proof of misbehavior' transaction allows users to reveal to the network any BFT violation.

=== PoS - Proof of Stake +

Proof of Stake is a type of consensus mechanism used to achieve agreement over a distributed network. With PoS the consensus is determined based upon the stake of each user in the network.

=== PoS - Proof of Work +

Proof of Work is is a type of consensus mechanism used to achieve agreement over a distributed network. With PoW in order to complete the transactions on a given network, the miners have to solve complex mathematical problems in order to be rewarded with the tokens.

=== Production Candidate +

A proposed, new version of Lisk Core for the Mainnet.

=== Production Stage +

The stage the Lisk SDK is in after every phase of the Lisk protocol roadmap is implemented and the Lisk blockchain application platform is fully launched.

=== Protocol Roadmap +

A path consisting of the most important milestones to consistently improve the Lisk protocol.

=== P2P - Peer to Peer +

A peer to peer network is a group of nodes (devices), that make up a decentralized network that can collectively share and store data, whereby each node acts as an individual peer.

== Q

== R

=== RC Stage +

The stage the Lisk SDK is in after every phase of the Lisk protocol roadmap is implemented, and also whilst any final refinements are being completed.

=== Release Candidate +

A proposed, new version of Lisk Core for the testnet.

=== Research Team +

Led by Jan Hackfeld.

=== REST - Representational State Transfer +

REST refers to the Representational State Transfer, which is a client-server, stateless, cacheable communications protocol. In the majority of cases HTTP is used.

=== RocksDB - A high performance embedded database +

An embedded persistent key value store for fast storage.

=== RPC - Remote Procedure Call +

RPC is a session protocol which enable a host to make a procedure call that appears to be local, however it has the ability to execute remotely on a separate machine connected to the network.

== S

=== SDK - Software Development Kit +

The set of tools that allow you to build blockchain applications replicating Lisk’s technology stack and architecture.

=== Second Passphrase +

An additional passphrase used as a voluntary, second level of security. To be removed once multi-signatures are implemented in the Network Economics phase.

=== SHA-256 - Secure Hash Algorithm 256 +

The SHA is a 256 bit algorithm designed for cryptographic security.

=== Stage +

A general product status of the Lisk SDK.

=== Standby Delegate +

A standby delegate, as each delegate is not able to forge new blocks for the Lisk blockchain. Rank 102-∞.

== T

=== Testnet +

The official testing network of Lisk.

=== Token +

How we refer to LSK or any sidechain token.

=== Transaction +

An interaction with the Lisk blockchain which permanently writes data to it. A transaction can have multiple purposes, e.g. a balance transfer or a delegate registration.

=== token transfer (previously called `balance transfer`) +

A transaction type on all networks based on the Lisk protocol which transfers LSK from one Lisk address to another one.

=== Transaction fee +

An amount of LSK needed to send a transaction on the Lisk blockchain.

=== Transaction ID +

A hash of a transaction that uniquely identifies a transaction.

=== Transaction Message +

A custom message you can attach to a balance transfer.

=== token unlock (previously called `unlock vote`) +

A transaction type on all networks based on the Lisk protocol which locks the token used for votes.

== U

=== UI - User Interface +

The space where computer systems and humans interact.

=== UTF-8 - Unicode Transformation Format 8 +

UTF-8 is a variable width encoding system which enables the translation of any unicode charater to a matching binary string.

=== URL - Uniform Resource Locator +

A URL is a reference to a web resource and possesses a mechanism for retrieving the web site specified in the URL.

=== UTXO - Unspent Transaction Output +

UTXO is an unspent output. In other words it can be thought of as an indivisible chunk of a token which is under the control of the private keys belonging to the owners.

== V

=== Version +

The number of a Lisk product.

=== Voter +

A user using their LSK to vote for their favourite delegates.

=== Vulnerability +

A bug which can be used to deal damage to a Lisk product, mainly the Lisk network.


== W

=== Wallet +

How we generally describe our desktop and mobile user interfaces.


== X

== Y

== Z


