= SDK Migration Guide
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc:
:docs-general: ROOT::
// URLs
:url_ethereum_events: https://medium.com/mycrypto/understanding-event-logs-on-the-ethereum-blockchain-f4ae7ba50378
:url_wiki_pubsub: https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern
// Project URLs
:url_sdkv5_rpc_events: lisk-sdk::events.adoc
:url_api_rpc_getEvents: {docs-general}api/lisk-node-rpc.adoc
:url_understand_modules_standardevent: {docs-general}understand-blockchain/sdk/modules-commands.adoc#standard-event
:url_understand_rpc_events: {docs-general}understand-blockchain/sdk/rpc.adoc#rpc-events
:url_build_module_event: {docs-general}build-blockchain/module/blockchain-event.adoc

== Terminology changes

[cols="1,1,3",options="header"]
|===
|SDKv5 (old)
|SDKv6 (new)
|Description

|Forging
|Block generation
|Description

|Forging node
|Validator node
|Description

|Non-forging node
|RPC node
|Description

|Network ID
|Chain ID
|Description

|Blockchain application
|Sidechain client
|Description

|Blockchain application
|Sidechain application
|Description

|Module/Plugin action
|Module/Plugin endpoint
|Description

|Application event
|RPC event
|Description

|Application action
|RPC endpoint
|Description

|Module/Plugin event
|X
|Description

|X
|Blockchain event
|Description
|===

== Migration of store from v5 to v6

== Failed transactions are included in blocks

Transaction fee is paid for every transaction included in a block.
So by including failed transactions in blocks, the transaction fee for a transaction is always paid even if it failed and didn't introduce any state changes on the blockchain.

The main benefits for this change are as follows:

Increased rewards for validators:: By doing this, validators will still be rewarded for executing the logic of the transaction until the point where it failed.
Increased security:: Additionally, it mitigates the danger of DDoSing sidechains by spamming transactions that will fail, because the transaction fee has to be paid in any case.

== Addition of blockchain events

**Blockchain events** are newly introduced, and **Module events** are completely removed in Lisk SDK v6.

Although similar in name, **Blockchain events** follow a completely different approach.
To avoid confusion between the two events, please read the summary below, which is comparing the new and old events inside modules.

[cols="1h,4,4",options="header"]
|===
|
|Module events (v5)
|Blockchain events (v6)

|Description
|Analog to the xref:{url_sdkv5_rpc_events}[application events] from v5, module events could be subscribed to via the RPC API of a node.

An event informs services that subscribed to it, if a certain event happened (e.g. a transaction was executed), and often contain additional data, providing more information or context about the event.

*Module events in Lisk SDK v5 follow the {url_wiki_pubsub}[publish-subscribe-pattern^].*
|Blockchain events are introduced newly in Lisk SDK v6.
Blockchain events are still defined and emitted inside the module, but it is not possible to subscribe to them via the RPC API of a node.

Instead, blockchain events are **logged per block**, i.e. directly included in the block header and can be queried through the RPC API of a node by requesting the RPC endpoint `chain_getEvents`.

Blockchain events are defined individually for each module, which one exception: The xref:{url_understand_modules_standardevent}[standard event] is emitted for every transaction included in the particular block, and it informs, if that particular transaction was successful or failed.

*Blockchain events in Lisk SDK v6 are following a concept comparable to the {url_ethereum_events}[Ethereum event log^].*

Beside the newly introduced blockchain events, there are still a couple of xref:{url_understand_rpc_events}[RPC events] included in the Lisk Framework, which can be retrieved via public-subscribe, as in v5.

The sidechain developer can define new blockchain events as desired, but the RPC events are not customizable anymore.
Only new blockchain events can be included in the sidechain client by the developer.

|Purpose
|Events are used to communicate about certain events in real time, and to prevent reoccuring RPC request, just to check if there are any changes.
|Blockchain events are a way for modules to store important information which is not included in the transactions or block assets, directly inside the block header.

They are part of the overall state of the blockchain, as an event root of all events included in a particular block is stored in the block header.

They can include a lot of additional data, if required, as the events themselves can be removed from the stores of the node after a certain time, and therefore don't "pollute" the blockchain itself.

|Definition
a|
[source,js]
----
public events = ['newHello'];
----
a|
[source,js]
----
public constructor() {
    super();
    // registration of stores and events
    this.events.register(NewHelloEvent, new NewHelloEvent(this.name));
}
----

For more information how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]

|Publishing
a|
[source,js]
----
this._channel.publish('hello:newHello', {
    sender: tx.senderAddress.toString('hex'),
    hello: helloAsset.helloString
});
----
a|
[source,js]
----
const newHelloEvent = this.events.get(NewHelloEvent);
newHelloEvent.add(context, {
    senderAddress: context.transaction.senderAddress,
    message: context.params.message
},[context.transaction.senderAddress]);
----
|Retrieving
a|
In Lisk SDK v5, events could be subscribed directly via the API client.

If an event was missed, there was no way of retrieving the event, after it was emitted by a node.

[source,js]
----
client.subscribe('app:block:new', ( data ) => {
  console.log('new block:',data);
});
----
a|
In Lisk SDK v6, events are requested per block height after an event is emitted.

Retrieving events from a node:

[source,bash]
----
curl --location --request POST 'http://localhost:7887/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "chain_getEvents",
    "params": {
        "height": 123
    }
}'
----

Lisk Service now offers additional endpoints to query for events more conveniently.
Retrieving events from a Lisk Service:

[source,bash]
----

----

|===



== Migration of reducer => method

== Migration of action => endpoint

== Addition of metadata

== Removing account schema

== Update of how to register module and dependencies
