= Schemas
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc:
// Project URLs

Schemas are used in various places in the Lisk SDK to define how data is saved to, and retrieved from the database.

== Where schemas are used

=== Data schemas



=== Account schemas


== Format

[source,js]
----
export const myAssetSchema = {
  // Unique identifier of the schema throughout the system
  $id: "/unique-id",
  // Root type must be type object
  type: "object",
  // Required properties
  required: ["key1","key2"],
  // Properties for the object
  properties: {
    key1: {
      dataType: "string",
      fieldNumber: 1,
    },
    key2: {
      dataType: "boolean",
      fieldNumber: 2,
    },
    key3: {
      dataType: "uint64",
      fieldNumber: 3,
    },
    key4: {
      type: "object",
      fieldNumber: 4,
      properties: {
        nestedKey1: {
          dataType: "sint32",
          fieldNumber: 1,
        },
        nestedKey2: {
          dataType: "string",
          fieldNumber: 2,
        },
      },
    },
    key5: {
      type: "array",
      fieldNumber: 5,
      items: {
        type: "object",
        properties: {
          nestedArrayKey1: {
            dataType: "string",
            fieldNumber: 1,
          },
          nestedArrayKey2: {
            dataType: "boolean",
            fieldNumber: 2,
          },
        },
      },
    },
    key6: {
      type: "array",
      fieldNumber: 6,
      items: {
        dataType: "bytes",
      },
    },
  },
  // Default values for the different properties
  default: {
    key1 : "",
    key2 : false,
    key3 : 0,
    key4 : {},
    key5 : [],
    key6 : [],
  }
}
----


== Data types

The application data is stored in specific data types and structures in the database.

A schema always defines the data types that will be used in the database to store specific data.
When the data is retrieved from the database by a module or plugin of the blockchain application, it is returned as JavaScript object or JSON, depending on the context:

Database::
These data types are used to save the respective data in the *database*.
The `dataType` in schemas must be one of `string`, `bytes`, `boolean`, `uint32`, `sint32`, `uint64` or `sint64`.
JavaScript object::
This data types are used *internally* in the blockchain application to handle data from the database.
JSON::
Data that is provided by *actions and events* is always returned in JSON format.

.Table: Data types of the different data structures
[cols=",,",options="header",stripes="hover"]
|===
|Database
|JavaScript object
|JSON

|string
|string
|string

|uint32
|number
|number

|sint32
|number
|number

|uint64
|BigInt
|string

|sint64
|BigInt
|string

|bytes
|Buffer
|string in hex format

|boolean
|boolean
|boolean

|===

== Decoding and encoding data

To conveniently decode and encode the data structures, use the `codec` package, which can be imported from the `lisk-sdk`, `@liskhq/lisk-client` or installed separately with `@liskhq/lisk-codec`.

[source,js]
----
const {
    codec,
} = require('lisk-sdk');

const CHAIN_STATE_KEY = "myContext:myKey";

const schema = {
    $id: "lisk/myContext/moreContext",
    type: "object",
    required: ["myKey"],
    properties: {
        myCounter: {
            dataType: "uint32",
            fieldNumber: 1,
        },
    },
    default: {
      myCounter: 0
    }
};

let counterBuffer = await stateStore.chain.get(
    CHAIN_STATE_KEY
);

let counter = codec.decode(
    schema,
    counterBuffer
);

counter.myCounter++;

await stateStore.chain.set(
    CHAIN_STATE_KEY,
    codec.encode(schema, counter)
);
----

