= Consensus protocols
:toc:

// Project URLs
:url_glossary_validator: glossary.adoc#validator
:url_glossary_fork: glossary.adoc#fork
:url_glossary_cchain: glossary.adoc#cross-chain
:url_understand_dpos: understand-blockchain/consensus/dpos.adoc
:url_understand_poa: understand-blockchain/consensus/poa.adoc
:url_understand_bft: understand-blockchain/bft.adoc
:url_understand_interop: understand-blockchain/interoperability.adoc
:url_intro_consensus: intro/how-blockchain-works.adoc#consensus-mechanisms

A consensus protocol is the protocol for xref:{url_glossary_validator}[validators] to **agree on one chain of blocks**.
In particular, the consensus protocol defines,

* *who* is allowed to add a new block to the blockchain,
* how delegates choose the *chain* to which they add a new block and
* when a block and all included transactions are **final**, i.e., irrevocably deemed part of the blockchain.

TIP: See also xref:{url_intro_consensus}[Intro > How blockchain works > Consensus mechanisms].

== Consensus protocols in Lisk

Blockchain applications built with the Lisk SDK achieve consensus in all important domains via dedicated modules, which each cover a specific aspect of the overall consensus of a blockchain.

TIP: There are multiple available protocols for the consensus domain `Block proposal` that you can choose from, to fit the specific use case.

[cols="1a,1,2a"]
|===
|Consensus domain|Consensus protocol|Responsible for

|Block proposal
|xref:{url_understand_dpos}[Lisk DPoS] or xref:{url_understand_poa}[Lisk PoA]
|* **Choosing validators**: Deciding who can be validator, i.e. who is allowed to add new blocks to the blockchain.

|Agreement on one chain
|xref:{url_understand_bft}[Lisk BFT]
|* **xref:{url_glossary_fork}[Fork] choice rule**: Determining how validators choose the chain to which they add a new block.
* **Block finalization**: Determining when a block (and all included transactions) is irrevocably deemed part of the blockchain.

|xref:{url_glossary_cchain}[Cross-chain] agreement
|xref:{url_understand_interop}[Lisk Interoperability]
|* **Chain of trust for validators **: Attesting updates about the current validator set of a chain in certificates.
* **Verifying cross-chain communication**: Attesting the correctness of cross-chain messages with certificates.
Certificates are automatically generated for finalized blocks.
Generated certificates satisfy chain of trust property, i.e., they can be sequentially submitted to another blockchain via cross-chain update transactions.

|===


