= Consensus protocols
:toc:
// Project URLs
:url_understand_dpos: understand-blockchain/consensus/dpos.adoc
:url_understand_poa: understand-blockchain/consensus/poa.adoc
:url_understand_bft: understand-blockchain/bft.adoc
:url_understand_interop: understand-blockchain/interoperability.adoc

A consensus protocol is the protocol for <<validators,validators>> to **agree on one chain of blocks**.
In particular, the consensus protocol defines when a block and all included transactions are **final**, i.e., irrevocably deemed part of the blockchain.

.Important terminology for consensus protocols
[TIP]
====
[[validators]]
Validators:: Accounts eligible to add new blocks to the chain.
[[fork]]
Fork:: A blockchain has forked, if two or more conflicting states(i.e. chain of blocks) of the blockchain exist in the network, and the network is unable to decide which is the correct state.
====

== Overview of consensus protocols in Lisk

//TODO: Link to consensus definitions from intro
//TODO: Link to Lisk consensus pages dpos, poa & bft

== Block generation & finalization

=== 1. Block proposal

Responsible for::

* **Choosing validators**: deciding who can be validator, i.e. who is allowed to add new blocks to the blockchain.
* **Block frequency**: defining when a block is added to the chain.

Defined in::
=> xref:{url_understand_dpos}[Lisk DPoS] or xref:{url_understand_poa}[PoA]

=== 2. Agreement on one chain

Responsible for::

* **Prevent forks**: determining how validators choose the chain to which they add a new block.
* **Chain finalization**: determining when a block (and all included transactions) is irrevocably deemed part of the blockchain.

Defined in::
=> xref:{url_understand_bft}[Lisk-BFT]

=== 3. Certificate generation

Responsible for::

* **Verifying cross-chain communication**: Attesting the correctness of cross-chain messages.
* **Verifying validators cross-chain **: Attesting updates about the current validator set.

Defined in::
xref:{url_understand_interop}[Lisk interoperability]

