= Consensus protocols
:toc:

A consensus protocol is the protocol for <<validators>> to **agree on one chain of blocks**.
In particular, the consensus protocol defines when a block and all included transactions are **final**, i.e., irrevocably deemed part of the blockchain.

.Important terminology for consensus protocols
[TIP]
====
[[validators]]
Validators:: Accounts eligible to add new blocks to the chain.
[[delegates]]
Delegates:: <<validators,Validators>> in DPoS.
[[authorities]]
Authorities:: <<validators,Validators>> in PoA.
[[authorities]]
Authorities:: Description
====

== Block generation & finalization

=== Block proposal

Responsible for:

* Deciding who can add a block to the chain
* Defining when a block is added to the chain

=> in Lisk DPoS or PoA

=== Agreement on one chain

Responsible for:

* Finalizing sequence of blocks in the chain
* Create consensus among all nodes about the block sequence

=> in Lisk-BFT

=== Certificate generation

Responsible for:

* Finalizing sequence of blocks in the chain
* Create consensus among sidechains about the block sequence of a particular sidechain.

for interoperability

