= Lisk Proof of Stake (PoS) & Proof of Authority (PoA)
:toc: preamble

====
On this page, you'll learn about:

* [x] The main characteristics of Lisk PoS
** [x] How validators are selected
** [x] What is the validator weight
** [x] What are active and standby validators
* [x] The main characteristics of Lisk PoA
** [x] How validators are selected
====

== PoS

=== Validator selection

Blocks in the Lisk PoS protocol are grouped together into batches of 103 consecutive blocks, which are referred to as a *block generation round*.

A *validator* is any account that successfully a xref:{url_sdk_modules_dpos}[Register Validator transaction].
//TODO: link to validator guide

Every block generation round, a new *validator list* is generated, which is an ordered list of 103 validators who are allowed to generate a block in that round.
The order of the validators in the list is completely random.

The first 101 validators in the validator list are also called *active validators*.
To become an active validator, a validator needs to increase their validator weight, until they are among the top 101 validators with the most validator weight.

The remaining 2 validator spots in each block generation round are given to two randomly selected *standby validators*.

Starting with the first validator on the validator list, every validator has a *10 second block slot window* in which they can generate a block and broadcast it to the network.

[NOTE]
====
If every validator on the list manages to generate a block in their block slot building on the block by the previous validator, a round lasts 1030 seconds (around 17 minutes).

It can happen that a validator *misses the block slot*, meaning that there is no block added to the chain by the validator in their designated block slot.
Consequently, the end of the validator list is reached before 103 blocks are added to the chain.
In this case, block slots are assigned again from the beginning of the validator list until 103 blocks are generated.
====

=== Staking
[#locked-tokens]
*Staked tokens are locked* inside the account that is performing the staking.
That means, the tokens used for staking stay in the account of the staker, but while they are used for staking, they cannot be used for any other purposes for example token transfers.
The staked tokens can be un-staked partially or completely again, if the account owner wishes to unlock the tokens.

[#self-stake]
Staking is particularly important for validators because they need to stake a significant number of their own tokens for their validator account.
This is also called *self-staking*.

Apart from self-staking, it is also beneficial to stake tokens for a different validator as well.
Staking for the most trustful and helpful validators in the community increases the decentralization and security of the network.
It also allows stakers to earn rewards as a lot of validators reward stakers with a share of their block rewards.
This creates a financial incentive for users to stake their unused tokens and receive regular payouts as a reward.

=== Validator weight

Every validator has an associated *validator weight*.
A high validator weight will put a validator in an active position to generate new blocks for the blockchain.

IMPORTANT: The *minimum validator weight required* to be selected as a block generator is 1000 LSK in the Lisk Mainnet.

Formally, the validator weight is defined as the following:

.Formula for calculating the validator weight
----
validatorWeight = minimum { 10 * selfStake , totalStakeReceived },
----

* `selfStake` is the number of tokens the validator staked for themselves.
* `totalStakeReceived` is the sum of all staked tokens (including self-stakes) for a specific validator.

NOTE: This definition implies that *at least 10% of the validator weight always consists of self-stakes*{fn_weight}.

==== How to retrieve the current weight of a validator

To verify the concrete weight of your validator account or any other validator, it is possible to directly request the required information via the RPC endpoint.

. xref:{url_run_validator_details}[Check the validator details].
. Use the values `totalStakeReceived` and `selfStake` to calculate the validator weight, following the formula described above.

:sectnums:

=== How the validator list is generated

image::protocol/forgerList.svg[forgerList]
//The top 101 delegates by delegate weight are called *active delegates*, whereas all other delegates with a delegate weight of at least 10^11^ (1000 LSK in Lisk Mainnet) are referred to as *standby delegates*.
Specifically, the validator list for a round is generated as follows:

. Compute two values `randomSeed1` and `randomSeed2` from the values provided by the validators in the `seedReveal` property of the block headers of the previous 3 rounds.
. Add the 101 active validators to the list.
Moreover, add 2 standby validators to the list using a random selection proportional to validator weight.
The random selection utilizes `randomSeed1` and `randomSeed2`, respectively.
The computation of 101 active validators as well as the standby validator selection is based on the validator weights from two rounds before.
. Shuffle the list using `randomSeed1`.

The random selection of two standby validators and the commit-reveal scheme that the `seedReveal` values provided by the validators in the block header must follow are described in detail in {url_github_lip_22}[LIP 0022^].

//TODO: Check context/relevance for below statement
////
During the bootstrap period defined in the xref:{url_blocks_genesis}[genesis block] the number of blocks per round and length of the validator list is still 103.
However, the Lisk PoS validator selection is not used.
Instead, the validator list is directly computed from the initial validators specified in the genesis block, repeating validators if needed, to obtain a list of length 103.
////
=== Staking and validator weight

By registering as validator, it is possible to *receive stakes* from other account for this validator.
//TODO: add link to staking guide
Any account can stake for any validator using a Stake transaction.

NOTE: A stake that a validator account casts for themselves is called a *self-stake*.

Depending on the stakes, every validator has an associated *validator weight*, which is an indicator for the support for this validator in the network.
Formally, the validator weight is defined as the following:

----
minimum { 10 * selfStakes , totalStakes },
----

where `selfStakes` is the amount the validator voted for themselves, and `totalStakes` is the sum of all vote amounts (including self-stakes) for that specific validator.
This definition implies that the self-stakes are always at least 10 % of the validator weight and thus validators always have substantial skin in the game.

=== Active vs stand-by vs inactive delegates

=== Banning of unproductive validators

As a fail-safe mechanism, a validator that does not generate blocks for an extended period of time is banned.
This is to avoid the situation where a validator who is not running a node leads to frequent missed block slots.
More specifically, a validator is banned in case they miss 50 consecutive blocks, and the height of the last block they generated differs by more than 260,000 from the current height of the chain (the block is 30 days old).
As soon as a validator is banned, they are excluded from the validator weight snapshots used for the validator list computation.
The ban is permanent, but the validator account holder can move their funds to a different account and register a new validator.

== PoA

=== Validator selection