= Extending the Indexer service
Muhammad Talha <muhammad.talha@lightcurve.io>
:toc: preamble
:toclevels: 3
:page-toclevels: 3
:sectnums:
:idprefix:
:idseparator: -

:url_token: https://github.com/LiskHQ/lisk-service/tree/development/services/blockchain-indexer/shared/indexer/transactionProcessor/token
:url_transfer: https://github.com/LiskHQ/lisk-service/blob/development/services/blockchain-indexer/shared/indexer/transactionProcessor/token/transfer.js
:url_index: https://github.com/LiskHQ/lisk-service/blob/development/services/blockchain-indexer/shared/indexer/transactionProcessor/token/index.js
:url_sharedIndexer_directory: https://github.com/LiskHQ/lisk-service/tree/development/services/blockchain-indexer/shared/indexer/transactionProcessor


The Blockchain Indexer service, in the indexing mode, is primarily responsible to index all the blockchain information, based on the scheduled jobs by the Blockchain Coordinator. In the data service mode, it serves user request queries made via the RESTful API or WebSocket-based RPC calls. It can run both the indexer and data service modes simultaneously, and is enabled by default.

This microservice encapsulates most of the business logic for the Lisk Service API. By default, it only implements the business logic for all the available commands from the Lisk SDK. The applyTransaction and revertTransaction hooks implement the indexing logic and are specific to each available command. The applyTransaction is triggered when processing an included transaction within a new block while (usually) indexing the chain_newBlock event. The revertTransaction hook is triggered when processing an included transaction within a deleted block while processing the chain_deleteBlock event. All the implemented hooks are grouped here. Command specific hooks are always implemented within a single file and are grouped by the module. When interested in extending Lisk Service and implementing hooks for your custom modules, please check the Extending Indexer section below.

== Extending the Indexer service
The applyTransaction and revertTransaction hooks are arranged per command in a file and are grouped by the module that they belong to.
Existing hooks are located in the shared/indexer/transactionProcessor directory.

When implementing the custom hooks please adhere to the following:

. Create a sub-directory with the module name. For example: {url_token}[token^].

. Add {url_index}[index.js^] under the above directory.

. Export a MODULE_NAME variable. The value must match the module name as registered within the application.
+
.index.js
[source,js]
----
const MODULE_NAME = 'token';

module.exports = {
	MODULE_NAME,
};
----
+

. Create a file specific to the command for which you need to implement the custom hooks. For example: {url_transfer}[transfer^].

. Export a COMMAND_NAME variable. The value must match the command name as registered within the application.
+
.transfer.js
[source,js]
----
const {
	Logger,
	DB: {
		MySQL: { getTableInstance },
	},
} = require('lisk-service-framework');
const config = require('../../../../config');

const { TRANSACTION_STATUS } = require('../../../constants');
const { indexAccountAddress } = require('../../accountIndex');
const { requestConnector } = require('../../../utils/request');

const logger = Logger();

const MYSQL_ENDPOINT = config.endpoints.mysql;

const transactionsTableSchema = require('../../../database/schema/transactions');

const getTransactionsTable = () => getTableInstance(transactionsTableSchema, MYSQL_ENDPOINT);

// Command specific constants
const COMMAND_NAME = 'transfer';

const EVENT_NAME_INITIALIZE_USER_ACCOUNT = 'initializeUserAccount';
----
+


Implement the custom logic for the applyTransaction and revertTransaction hooks.
Export the hooks.
To aid your development, please use the sample templates here.


To

