= Sidechain Registration & Recovery
Chris Braithwaite <christopher.braithwaite@lightcurve.io> Mona Bärenfänger <mona@lightcurve.io>
:description: How to register, terminate, and recover a sidechain.
:toc:
:idprefix:
:idseparator: -
:imagesdir: ../../assets/images

:url_ccm: understand-blockchain/interoperability/communication.adoc

//:url_how_blockchain_works: intro/how-blockchain-works.adoc
//:url_transactions: understand-blockchain/lisk-protocol/transactions.adoc

== Overview - What is a Sidechain?

A sidechain is actually a separate blockchain that is attached to its mainchain using a two-way peg.
Sidechains are aligned in parallel with the main blockchain.
Sidechains can facilitate moving digital assets from their origin, namely the original blockchain to a separate blockchain which is known as a sidechain.
Furthermore, it is possible to move these assets back to the original blockchain if necessary, resulting in being able to securely interchange data and assets.
Simply put, a sidechain will allow nodes containing assets or data from the parent blockchain to be securely used in a separate blockchain (the sidechain), and hence, these assets and data can then be transferred back to the original blockchain.
In turn, the advent of sidechains will further increase the performance of the parent blockchain by taking some of the workload, and furthermore this increases the level of security as all transactions that are executed, are secured by the participants (generators/forgers), of the mainchain.

=== Sidechains in Lisk
Within the Lisk network, the sidechain technique deployed collects a series of cross-chain messages before to executing a transaction.
After these messages reach the receiving platform, they can then be verified and added to the block.

The Cross-chain update transactions can be considered as the carriers of the information transmitted between different chains.
By posting a cross-chain update, the receiving chain receives the information required about the advancement of the sending chain.
This transaction can also include cross-chain messages as described below, and thus serves as an envelope for messages from one chain to another.

The cross-chain messages are responsible for verifing the state transition which ensures that the information is valid, and in turn allows for the simple validation of the state of the chain as well as the acceptance into a separate network.
The sidechains function by the way of using certificates to communicate between chains.
Before a transaction can be performed, it is necessary to receive updates from several blocks first, which are then collected and sent to the receiving chain.
This is where cross chain updates (CCUs) are used, as they contain the cross chain messages, a certificate, and the necessary information regarding the current validator set of the sending chain.

The system functions whereby the CCUs are then validated in conjunction with the most recent message from the receiving chain.
Hence, this enables the transfer of data and assets to be administered via these messages.

These CCUs are then validated by the receiving chain in accordance with the most recent message, therefore confirming that the afore-mentioned messages were sent.
Further more in-depth information regarding CCMs can be found here on the xref:{url_ccm}[Cross-chain communication page].

== Sidechain Registration

// Explain why sidechain registration is needed referencing the introduction
// Explain why sidechain will be terminated and how/what can recover from the sidechain

Firstly sidechain registration is required to ultimately ensure interoperability with a separate chain can be achieved with the Lisk mainchain.
In effect this is managed by a registration command that creates a sidechain account within the Lisk mainchain.
This can be thought of as the initial step, being the creation and initiation of the communication channel that is required for two separate, different chains to interoperate and function seamlessly together.
To bring this to fruition a cross channel chain protocol needs to be established, which is the chain registration process defining the necessary protocol rules and data structures.
At this point it should be noted that there are two registration commands which are utilized dependent on whether it is the Lisk mainchain or the sidechain we are dealing with.
To explain this briefly, for the Lisk mainchain the sidechain registration command is used.
From the sidechain perspective, this is performed by the mainchain registration command, both of these are covered further in this section.

== How to register a sidechain

As mentioned in the previous paragraph to enable a sidechain to operate, it first has to be registered in the Lisk mainchain via a sidechain registration command.
This requires that the sidechain registration command is processed, which will then result in the sidechain account status being set to registered.
However, at this point the cross-channel is not active, so it is not possible for any cross-chain messages (CCMs) to be sent yet.

For the processing of this command, it signifies that as sidechain account in the mainchain state exists, and is associated with a name and a unique network identifier.
Therefore, each new sidechain occupies a certain namespace in the ecosystem.

==== Registration Message

The role of the registration message is to allow for a safe activation of the channel between the sending and receiving chains.
It guarantees that when the CCU activating the channel is executed, a registration transaction has been included on the partner chain.

==== Sidechain Registration Process

A transaction with this command can be sent by any user account in the Lisk Mainchain with enough funds to pay the required fee.
The processing of this command implies the creation of a sidechain account in the mainchain state associated with a unique network identifier and a name.
Therefore that every new sidechain occupies a certain namespace in the ecosystem.
Additionally, every newly registered sidechain can increase the size of every cross-chain update command posted on the mainchain (due to the increasing size of the  `outboxRootWitness` property of the command).
For these two reasons, the minimum fee for this command has an added constant similar to the extra fee in a *delegate registration command*.
The value of this extra registration fee is 10 LSK.




== Sidechain termination



Sidechain Terminated Message
The role of the sidechain terminated message is to inform sidechains that another sidechain has been terminated on the mainchain and is unable to receive messages. The message contains the ID of the terminated chain as well as the last certified state root of the terminated sidechain (as certified on the mainchain). This value is used for the creation of the terminated state account (on the sidechain receiving the CCM), allowing state recoveries.
This message allows to inform sidechains about other terminated sidechains efficiently. Indeed, this message will automatically trigger the creation of the terminated sidechain account as soon as the first message is unable to be delivered. This also prevents further messages to be sent to already terminated sidechains.


== How to recover information from a sidechain
Explain steps to recover information from sidechain


=== Mainchain registration