= Sidechain Registration & Recovery
Chris Braithwaite <christopher.braithwaite@lightcurve.io> Mona Bärenfänger <mona@lightcurve.io>
:description: How to register, terminate, and recover a sidechain.
:toc:
:idprefix:
:idseparator: -
:imagesdir: ../../assets/images

:url_ccm: understand-blockchain/interoperability/communication.adoc
:url_ccm1: understand-blockchain/interoperability/communication.adoc#inducing_state_changes_across_chains_with_ccms


//:url_how_blockchain_works: intro/how-blockchain-works.adoc
//:url_transactions: understand-blockchain/lisk-protocol/transactions.adoc

== Overview - What is a Sidechain?

A sidechain is actually a separate blockchain that is attached to its mainchain using a two-way peg.
Sidechains are aligned in parallel with the main blockchain.
Sidechains can facilitate moving digital assets from their origin, namely the original blockchain to a separate blockchain which is known as a sidechain.
Furthermore, it is possible to move these assets back to the original blockchain if necessary, resulting in being able to securely interchange data and assets.
Simply put, a sidechain will allow nodes containing assets or data from the parent blockchain to be securely used in a separate blockchain (the sidechain), and hence, these assets and data can then be transferred back to the original blockchain.
In turn, the advent of sidechains will further increase the performance of the parent blockchain by taking some of the workload, and furthermore this increases the level of security as all transactions that are executed, are secured by the participants (generators/forgers), of the mainchain.

== Sidechains in Lisk

Within the Lisk network, the sidechain technique deployed collects a series of cross-chain messages (CCM), before to executing a transaction.
After these messages reach the receiving platform, they can then be verified and added to the block.

The Cross-chain update (CCU) transactions can be considered as the carriers of the information transmitted between different chains.
By posting a cross-chain update, the receiving chain receives the information required about the advancement of the sending chain.
This transaction can also include cross-chain messages, as described below, and thus serves as an envelope for messages from one chain to another.

The cross-chain messages are responsible for verifing the state transition which ensures that the information is valid, and in turn allows for the simple validation of the state of the chain as well as the acceptance into a separate network.
The sidechains function by the way of using certificates to communicate between chains.
Before a transaction can be performed, it is necessary to receive updates from several blocks first, which are then collected and sent to the receiving chain.
This is where cross chain updates (CCUs) are used, as they contain the cross chain messages (CCMs), a certificate, and the necessary information regarding the current validator set of the sending chain.

The system functions whereby the CCUs are then validated in conjunction with the most recent message from the receiving chain.
Hence, this enables the transfer of data and assets to be administered via these messages.

These CCUs are then validated by the receiving chain in accordance with the most recent message, therefore confirming that the afore-mentioned messages were sent.
Further more in-depth information regarding the CCUs and CCMs can be found here on the xref:{url_ccm}[Cross-chain communication page].

== Life Cycle of a Sidechain

The life cycle of a sidechain can be broken down into 3 parts, corresponding to the following 3 values of the account status property: ''registered'', ''active'', and ''terminated''.

Firstly, a sidechain registers on the mainchain with a *sidechain registration command*.
This command creates the sidechain account on the mainchain.
Specifically it creates an entry in the chain data substore, with the initial status set to 'registered'; an entry in the channel data substore, with an empty inbox and outbox; coupled with an entry in the validators data substore, holding the initial sidechain validators set.
Thereafter, the mainchain account is similarly created on a sidechain with a *mainchain registration command*.

After a sidechain has been registered on the mainchain, it cannot receive any cross-chain message and does not need to follow the liveness rule, until the first sidechain CCU has been included in the mainchain.
At this point, the status of the sidechain account on the mainchain is updated to ''active'' and the liveness requirement rule is then enforced.
(The liveness rule requires active sidechains to prove their liveness once every 30 days, or the sidechain account is terminated).

Therefore, if no CCU is received within 30 days, the *chain account is terminated* and no more CCMs can be sent to or received from the sidechain.
A sidechain account can also be terminated if the sidechain posts a CCU containing a CCM with an invalid schema or with an invalid sending chain ID.
A message targeting a terminated chain is bounced on the mainchain instead of being forwarded.
When this happens, a ''terminated sidechain'' message is emitted by the mainchain, targeting the original sending chain.
When this message is processed, the chain is also terminated in the sending chain, blocking future messages.

When a chain is terminated, a 'terminated state' account is created, storing the last certified state root of the terminated chain.
Then, users can recover tokens from the terminated sidechain with a state recovery command or proceed with the message recovery initialization command to kick-off the recovery of pending cross-chain messages.





== Sidechain Registration

// Explain why sidechain registration is needed referencing the introduction
// Explain why sidechain will be terminated and how/what can recover from the sidechain

Firstly sidechain registration is required to ultimately ensure interoperability with a separate chain can be achieved with the Lisk mainchain.
In effect this is managed by a registration command that creates a sidechain account within the Lisk mainchain.
This can be thought of as the initial step, being the creation and initiation of the communication channel that is required for two separate, different chains to interoperate and function seamlessly together.
To bring this to fruition a cross channel chain protocol needs to be established, which is the chain registration process defining the necessary protocol rules and data structures.
At this point it should be noted that there are two registration commands which are utilized dependent on whether it is the Lisk mainchain or the sidechain we are dealing with.
To explain this briefly, for the Lisk mainchain the sidechain registration command is used.
From the sidechain perspective, this is performed by the mainchain registration command, both of these are covered further in this section.
