= Dashboard plugin
:toc:

`@liskhq/lisk-framework-dashboard-plugin` is a plugin for the Lisk Framework that provides a UI which allows a developer to conveniently communicate with the blockchain application during the development.

The dashbobard plugin includes the following features:

* Monitor recent blocks and transactions
* Get information about accounts
* Create new accounts
* Call actions
* Listen to events
* Create transactions
* Get node information

[cols=",",stripes="hover"]
|===
|Alias
|`dashboard`

|Actions
|none

|Events
|none

|===

== Registering the plugin

How to register the dashboard plugin with the blockchain application.

[source,js]
----
const { Application, DashboardPlugin, genesisBlockDevnet, configDevnet } = require('lisk-sdk');

const app = Application.defaultApplication(genesisBlockDevnet, configDevnet);

app.registerPlugin(DashboardPlugin);

app
  .run()
  .then(() => app.logger.info('App started...'))
  .catch(error => {
    console.error('Faced error in application', error);
    process.exit(1);
  });
----

== Plugin configuration

The dashboard plugin can be configured in the configuration of the blockchain application under `plugins.dashboard`.

NOTE: The application will use the default values in case no plugin configuration is provdided.

.Dashboard options in the configuration
[source,js]
----
const { Application, DashboardPlugin, genesisBlockDevnet, configDevnet } = require('lisk-sdk');

const appConfig = utils.objects.mergeDeep({}, configDevnet, {
    plugins: {
        dashboard: {
            applicationUrl: 'ws://localhost:8080/ws',
            port: 4005,
            host: '127.0.0.1',
            applicationName: 'Lisk',
        }
    }
});

const app = Application.defaultApplication(genesisBlockDevnet, appConfig);

app.registerPlugin(DashboardPlugin);

app
  .run()
  .then(() => app.logger.info('App started...'))
  .catch(error => {
    console.error('Faced error in application', error);
    process.exit(1);
  });
----

=== Available configuration options


[source,js]
----
{
    applicationName: {
        type: 'string',
        description: 'Application name to be shown near Logo',
    },
    applicationUrl: {
        type: 'string',
        format: 'uri',
        description: 'URL to connect',
    },
    port: {
        type: 'integer',
        minimum: 1,
        maximum: 65535,
    },
    host: {
        type: 'string',
        format: 'ip',
    },
}
----

