= Report misbehavior plugin
// Settings
:toc:
// Project URLs
:url_architecture_registering_plugins: architecture/index.adoc#registering-modules-and-plugins

`@liskhq/lisk-framework-report-misbehavior-plugin` is a plugin for the Lisk Framework that provides automatic detection of delegate misbehavior and sends a `reportDelegateMisbehaviorTransaction` to the running node.

[cols=",",options="header",stripes="hover"]
|===
|Name
|Property

|Alias
|`reportMisbehavior`

|Actions
|`authorize`

|Events
|none

|===

[NOTE]
====
To use the report misbehavior plugin in the application, it is necessary to xref:{url_architecture_registering_plugins}[register] it.
====

== Default configuration

.Forger options in the configuration
[source,js]
----
{
  //[...]
  plugins: {
    reportMisbehavior: {
        dataPath: '~/.lisk/report-misbehavior', <1>
		cleanupFrequency: 3600, <2>
		encryptedPassphrase: '', <3>
		defaultPassword: '', <4>
		fee: 100000000 <5>
	},
  }
}
----

<1> `dataPath`: The data path for storing misbehavior related information captured from application.
<2> `cleanupFrequency`(optional): Frequency of cleaning up the outdated data in seconds.
<3> `encryptedPassphrase`(optional): The encrypted passphrase of the account that will report the misbehavior.
<4> `defaultPassword`(optional): Default password to decrypt the encrypted passphrase.
It is not recommended to set a default password in production environments for security reasons.
<5> `fee`(optional): The fee required to send a report misbehavior transaction.

== Actions

=== authorize
Invoke this action to enable or disable the delegate misbevahior report.

==== Input
[source,js]
----
{
  password: string,
  enable: boolean
}
----

==== Returns
[source,json]
----
"Successfully enabled/disabled the reporting of misbehavior."
----
