= The Lisk SDK test suite
:toc: preamble
// URLs
:url_github_statestor_mock: https://github.com/LiskHQ/lisk-sdk/blob/v5.1.0/elements/lisk-chain/src/testing/mocks/state_store_mock.ts
:url_github_app_env: https://github.com/LiskHQ/lisk-sdk/blob/v5.1.0/framework/src/testing/app_env.ts

A detailed reference of the available test utilities in the Lisk SDK test suite.

== Fixtures

=== defaultFaucetAccount
Returns a default faucet account.

==== Usage

[source,js]
----
const sdk = require('lisk-sdk');

sdk.testing.fixtures.defaultFaucetAccount
----

==== Returns

[source,js]
----
{
  address: <Buffer d0 46 99 e5 7c 4a 38 46 c9 88 f3 c1 53 06 79 6f 8e ae 5c 1c>,
  publicKey: <Buffer 0f e9 a3 f1 a2 1b 55 30 f2 7f 87 a4 14 b5 49 e7 9a 94 0b f2 4f df 2b 2f 05 e7 f2 2a ee ec c8 6a>,
  passphrase: 'peanut hundred pen hawk invite exclude brain chunk gadget wait wrong ready',
  balance: '10000000000000000',
  encryptedPassphrase: 'iterations=10&cipherText=6541c04d7a46eacd666c07fbf030fef32c5db324466e3422e59818317ac5d15cfffb80c5f1e2589eaa6da4f8d611a94cba92eee86722fc0a4015a37cff43a5a699601121fbfec11ea022&iv=141edfe6da3a9917a42004be&salt=f523bba8316c45246c6ffa848b806188&tag=4ffb5c753d4a1dc96364c4a54865521a&version=1',
  password: 'elephant tree paris dragon chair galaxy'
}
----

=== defaultAccounts

Returns a list of all addresses of the 103 genesis delegates.

==== Usage

[source,js]
----
const sdk = require('lisk-sdk');

sdk.testing.fixtures.defaultAccounts()
----

==== Returns

[source,js]
----
[
  {
    address: <Buffer 9c ab ee 3d 27 42 66 76 b8 52 ce 6b 80 4c b2 fd ff 7c d0 b5>
  },
  {
    address: <Buffer 46 3e 7e 87 9b 7b dc 6a 97 ec 02 a2 a6 03 aa 1a 46 a0 4c 80>
  },
  {
    address: <Buffer 32 8d 0f 54 66 95 c5 fa 02 10 5d eb 05 5c f2 80 1d 9b 8b a1>
  },
  // +100 more
]
----

=== createDefaultAccount
Generates account data for a user account.

==== Parameters

. modules(array): List of modules.
The modules account schemas will be included in the returned account.
. data(object): Custom account data.

==== Usage

[source,js]
----
const sdk = require('lisk-sdk');

sdk.testing.fixtures.createDefaultAccount([sdk.TokenModule, sdk.DPoSModule, {customKey:"someData"});
----

==== Returns

[source,js]
----
{
  token: { balance: 0n },
  dpos: {
    delegate: {
      username: '',
      pomHeights: [],
      consecutiveMissedBlocks: 0,
      lastForgedHeight: 0,
      isBanned: false,
      totalVotesReceived: 0n
    },
    sentVotes: [],
    unlocking: []
  },
  customKey: 'someData',
  address: <Buffer 43 04 e6 71 08 7f 40 ff bc 30 29 ad 2e f7 16 ad 5c 00 5e 7f>
}
----

=== defaultPassword
Returns a default password.

==== Usage

[source,js]
----
const sdk = require('lisk-sdk');

sdk.testing.fixtures.defaultPassword
----

==== Returns

[source,js]
----
'elephant tree paris dragon chair galaxy'
----

=== defaultConfig
A default configuration for a blockchain applicaiton.

==== Usage

[source,js]
----
const sdk = require('lisk-sdk');

sdk.testing.fixtures.defaultConfig
----

==== Returns

[source,js]
----
{
  label: 'beta-sdk-app',
  version: '0.0.0',
  networkVersion: '1.0',
  rootPath: '~/.lisk',
  logger: {
    fileLogLevel: 'none',
    consoleLogLevel: 'none',
    logFileName: 'lisk.log'
  },
  genesisConfig: {
    blockTime: 10,
    communityIdentifier: 'sdk',
    maxPayloadLength: 15360,
    bftThreshold: 68,
    minFeePerByte: 1000,
    baseFees: [ [Object] ],
    rewards: { milestones: [Array], offset: 2160, distance: 3000000 },
    minRemainingBalance: '5000000',
    activeDelegates: 101,
    standbyDelegates: 2,
    delegateListRoundOffset: 2
  },
  forging: {
    force: true,
    waitThreshold: 2,
    delegates: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 3 more items
    ],
    defaultPassword: 'elephant tree paris dragon chair galaxy'
  },
  network: { seedPeers: [ [Object] ], port: 5000, maxInboundConnection: 0 },
  transactionPool: {
    maxTransactions: 4096,
    maxTransactionsPerAccount: 64,
    transactionExpiryTime: 10800000,
    minEntranceFeePriority: '0',
    minReplacementFeeDifference: '10'
  },
  plugins: {},
  rpc: { enable: true, port: 8080, mode: 'ipc' }
}
----

=== getPassphraseFromDefaultConfig
Returns the passphrase of a default account.

==== Parameters

* address(Buffer): The address of a default delegate.

==== Usage

[source,js]
----
const sdk = require('lisk-sdk');
const address = sdk.testing.fixtures.defaultAccounts()[0].address;

sdk.testing.fixtures.getPassphraseFromDefaultConfig(address)
----

==== Returns

[source,js]
----
'endless focus guilt bronze hold economy bulk parent soon tower cement venue'
----

=== getHashOnionFromDefaultConfig
Returns the hash onion for a default delegate.

==== Parameters

. address(Buffer): The address of a default delegate.
. count(number)

==== Usage

[source,js]
----
const sdk = require('lisk-sdk');
const address = sdk.testing.fixtures.defaultAccounts()[0].address;

sdk.testing.fixtures.getHashOnionFromDefaultConfig(address, 3);
----

==== Returns

[source,js]
----
<Buffer 54 9f b5 3b 1b 8a 49 d7 62 90 1e 75 4b 5c 10 24>
----

== Mocks

=== StateStoreMock
Returns a mock for the state store.

TIP: View the full implementation of the {url_github_statestor_mock}[StateStoreMock on GitHub^].

==== Parameters

* MockInput(object): Input data for the state store mock. (Optional)

.MockInput
[source, typescript]
----
{
	accounts?: Account<any>[];
	defaultAccount?: AccountDefaultProps;
	chain?: { [key: string]: Buffer };
	consensus?: { [key: string]: Buffer };
	lastBlockHeaders?: Partial<BlockHeader>[];
	networkIdentifier?: Buffer;
	lastBlockReward?: bigint;
}
----

==== Usage

[source,typescript]
----
const sdk = require('lisk-sdk');

const account = sdk.testing.fixtures.createDefaultAccount([sdk.TokenModule, sdk.DPoSModule]);

const stateStore = new sdk.testing.mocks.StateStoreMock({
    accounts: [account],
});
----


=== channelMock
Returns a mock for the channel.

==== Usage

[source,typescript]
----
const sdk = require('lisk-sdk');

sdk.testing.mocks.channelMock;
----

==== Returns

[source,typescript]
----
{
  publish: [Function: publish],
  registerToBus: [AsyncFunction: registerToBus],
  isValidEventName: [Function: isValidEventName],
  isValidActionName: [Function: isValidActionName],
  eventsList: [],
  actionsList: [],
  actions: {},
  moduleAlias: '',
  options: {},
  once: [Function: once],
  subscribe: [Function: subscribe],
  invoke: [AsyncFunction: invoke]
}
----

=== consensusMock
Returns a mock for consensus functions.

==== Usage

[source,typescript]
----
const sdk = require('lisk-sdk');

sdk.testing.mocks.consensusMock;
----

==== Returns

[source,typescript]
----
{
  getDelegates: [AsyncFunction: getDelegates],
  updateDelegates: [AsyncFunction: updateDelegates],
  getFinalizedHeight: [Function: getFinalizedHeight]
}
----
=== DataAccessMock
Returns a mock for the data access.

==== Paramters

* opts(object): Input data for the data access mock. (Optional)

[source,typescript]
----
{
    blockHeaders?: BlockHeader<T2>[];
    accounts?: Account<T1>[];
    chainState?: Record<string, Buffer>;
}
----

==== Usage

[source,typescript]
----
const sdk = require('lisk-sdk');

const dataAccess = new sdk.testing.mocks.DataAccessMock()
----

=== loggerMock
Returns a mock of the logger.

==== Usage
[source,typescript]
----
const sdk = require('lisk-sdk');

sdk.testing.mocks.loggerMock;
----

==== Returns

[source,typescript]
----
{
  trace: [Function: trace],
  debug: [Function: debug],
  info: [Function: info],
  warn: [Function: warn],
  error: [Function: error],
  fatal: [Function: fatal],
  level: [Function: level]
}
----

=== reducerHandlerMock
Returns a mock for the reducer handler.

==== Usage
[source,typescript]
----
const sdk = require('lisk-sdk');

sdk.testing.mocks.reducerHandlerMock;
----

==== Returns

[source,typescript]
----
{ invoke: [AsyncFunction: invoke] }
----

== Functions

=== getBlockProcessingEnv
Used for integration testing.

==== Parameters
[source,typescript]
----
{
	modules?: ModuleClass[];
	options?: Options;
	accounts?: PartialAccount<T>[];
	initDelegates?: Buffer[];
}
----

//TODO
==== Usage
[source,typescript]
----
const sdk = require('lisk-sdk');

sdk.testing.mocks.getBlockProcessingEnv();
----

==== Returns

.BlockProcessingEnv
[source,typescript]
----
{
	createBlock: (payload?: Transaction[], timestamp?: number) => Promise<Block>;
	getProcessor: () => Processor;
	getChain: () => Chain;
	getBlockchainDB: () => KVStore;
	process: (block: Block) => Promise<void>;
	processUntilHeight: (height: number) => Promise<void>;
	getLastBlock: () => Block;
	getValidators: () => Promise<Validator[]>;
	getNextValidatorPassphrase: (blockHeader: BlockHeader) => Promise<string>;
	getDataAccess: () => DataAccess;
	getNetworkId: () => Buffer;
	cleanup: (config: Options) => Promise<void>;
}
----

=== createDefaultApplicationEnv
Used for functional testing.

TIP: View the full implementation of the {url_github_app_env}[ApplicationEnv on GitHub^].

==== Parameters

* `appConfig`(object): Environment variables for the application.

.ApplicationEnvConfig
[source,typescript]
----
{
	modules: ModuleClass[];
	plugins?: InstantiablePlugin[];
	config?: PartialApplicationConfig;
	genesisBlockJSON?: Record<string, unknown>;
}
----

//TODO
==== Usage
[source,typescript]
----
const sdk = require('lisk-sdk');

sdk.testing.createDefaultApplicationEnv(cfg);
----

=== createTransaction
==== Parameters
[source,typescript]
----

----


==== Usage
[source,typescript]
----
//TODO
----

==== Returns
[source,typescript]
----
//TODO
----
=== createGenesisBlock
=== getModuleInstance
=== getAccountSchemaFromModules
=== createBlock
=== encodeBlockHeader
=== createBlockHeaderWithDefaults
=== createFakeBlockHeader
=== createAfterGenesisBlockApplyContext
=== createBeforeBlockApplyContext
=== createAfterBlockApplyContext
=== createTransactionApplyContext
=== createApplyAssetContext
=== createValidateAssetContext

