= Lisk Commander Documentation Overview
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Commander overview provides an introduction to the Lisk Commander CLI tool its setup and usage.
:toc:
:imagesdir: ../assets/images

:url_user_guide_commands: lisk-commander/user-guide/commands.adoc
:url_user_guide: lisk-commander/user-guide.adoc



Lisk Commander is a Command Line Interface tool designed to be a low entry point and the most convenient tool for developers who are looking for an efficient way of coding.

*Who is Lisk Commander for?*

* Delegates.
* Node operators.
* Contributors to the Lisk codebase.
* Developers using Lisk’s infrastructure.
* Anyone interested in making use of Lisk’s functionalities via the command line.

Lisk Commander allows communication with a remote or local node in order to access and utilise Lisk-related functionalities.

*What can be achieved with Lisk Commander?*

* Create a transaction.
* Decrypt/encrypt passphrases or messages.
* Install and manage a node.
* Create accounts.
* Get delegates.
* And many more.. For further details please see the following link: xref:{url_user_guide_commands}[View all commands]

== Setup

NOTE: Supported Platforms: Platforms with NodeJS versions 8.3 and above.

=== Pre-Installation

Lisk Commander requires https://nodejs.org/[Node.js] as the underlying engine for code execution.

==== Install Node

Node.js is supported on most operating systems.
Follow the instructions for your operating system on the https://nodejs.org/en/download/[Node.js downloads page].
Lisk-Commander requires Node.js versions 8.3 or above.

NPM is automatically installed along with Node.js.

===== Verify Node installation

Confirm that Node.js and NPM have been successfully installed by executing the following command:

[source,bash]
----
node --version
npm --version
----

=== Installation

To install the latest version of Lisk Commander as a global command, install the NPM package as shown below:

[source,bash]
----
npm install --global --production lisk-commander
----

Upon successful completion, NPM will add the Lisk Commander executable to your PATH.

To see usage examples and configuration options, check the xref:{url_user_guide}[Lisk Commander User Guide].
For a full reference of all commands and their available options, please see the following link: xref:{user_guide_commands}[Command Reference].

== Upgrade

To update your global installation to the latest version of Lisk Commander, simply execute the following command:

[source,bash]
----
npm update --global lisk-commander
----

