= How to maintain a node
Mona Bärenfänger <mona@lightcurve.io>
:description: Learn how to maintain a Lisk node and also when it is recommended to run a specific node.
:toc:

== What is a node?

The Lisk blockchain is a decentralized network that consists of many different servers, (or nodes).
Node operators are required to set up Lisk Core on a server, and then connect it to the desired network.

There are over 600 nodes around the world that are maintained by individuals, and these nodes communicate with the network.
For example, by broadcasting and receiving blocks or transactions from their peers.
In addition, Lisk nodes are also required to forge/add new blocks to the blockchain.
It is possible to view the live network statistics by accessing the following URL: https://explorer.lisk.io/networkMonitor[Lisk’s Blockchain Explorer].

== Who should operate a node?

If you fall under one of the following categories listed below, then it is recommended to set up your own node:

* *Exchanges* and other services that rely on a stable API interface to the network.
* *Delegates* who have registered a delegate and would like to actively forge.
* *Users* who do not trust external sources and want to be in full control over their node.

== Why operate a node?

There are several advantages why one would wish to set up a node:

- To have your xref:configuration.adoc#_api_access_control[private] entry point to communicate with the network.
This is especially important when running an exchange and implementing LSK tokens.
- To acquire full control in order to xref:configuration.adoc[configure] the node to your specific requirements.
- To create your own xref:index.adoc#_snapshots[snapshots] of the blockchain.
- To have the option to xref:configuration.adoc#_forging[Forge] new blocks (assuming you are an active xref:1.1@lisk-protocol::consensus.adoc#_delegates[delegate]).

== How to set up a node?

Simply follow the node setup guide for your desired distribution.
This is described on the xref:index.adoc#_distributions[Lisk Core Overview] page.

There are three available distributions of Lisk Core which can be seen below:

=== xref:setup/binary.adoc[Binary]

The *default* way to setup Lisk Core.
The binary installation is an easy and automated way to set up Lisk Core, which includes almost completed automated update scripts; together with a selection of tools to assist with seamlessly maintaining a Lisk Node.

=== xref:setup/commander.adoc[Commander]

Use xref:setup/commander.adoc[Lisk Commander] to conveniently install and manage Lisk Core.

=== xref:setup/docker.adoc[Docker]

Docker adds support for additional platforms upon which to run a Lisk node.
For example, running a Lisk node inside of a Docker on Windows and connecting it via a custom Node on Lisk Desktop to Lisk Core, without the necessity to rent an additional server.

=== xref:setup/source.adoc[Source]

This is designed for anyone wishing to develop on the Lisk Core codebase.
It also comes with an extensive test-suite, detailed in the following `README.md`.
An installation performed from Source enables a developer to work on the newest codebase for Lisk Core, which may not have been tagged for a release yet.
