= Commander commands
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Commander administration describes all relevant commands to manage Lisk Core through the command-line with Lisk Commander.
:toc:
:page-next: /lisk-core/3.0.0/management/configuration.html
:page-previous: /lisk-core/3.0.0/setup/commander.html
:page-next-title: Configuration
:page-previous-title: Commander installation

:url_setup_commander: setup/commander.adoc
:url_upgrade_commander: update/commander.adoc

This section covers how to perform the installation of Lisk Core using the Lisk Commander.
Further information can be found by referring to the list of commands described here.

== Basic commands

The available basic commands which can be used to manage your Lisk node are displayed here below:

=== Install

NOTE: For more information, please see the xref:{url_setup_commander}[Setup page of Lisk Core with Lisk Commander].

[tabs]
====


--
[source,bash]
----
lisk core:install lisk-betanet
----
--
====

=== Uninstall

[tabs]
====

--
[source,bash]
----
lisk core:uninstall lisk-betanet
----
--
====

=== Status

Check the status of the Lisk Core Node.

[tabs]
====
--
[source,bash]
----
lisk core:status lisk-betanet
----
--
====

=== Upgrade

NOTE: For more information, please see the xref:{url_upgrade_commander}[Upgrade page of Lisk Core with Lisk Commander].

[tabs]
====
--
[source,bash]
----
lisk core:upgrade lisk-betanet
----
--
====

=== Start

Start Lisk Core and PostgreSQL.

[tabs]
====
--
[source,bash]
----
lisk core:start lisk-betanet
----
--
====

=== Stop

Stop Lisk Core and PostgreSQL.

[tabs]
====
--
[source,bash]
----
lisk core:stop lisk-betanet
----
--
====

=== Restart

Reload Lisk Core and pick up changes to config.json.

[tabs]
====
--
[source,bash]
----
lisk core:restart lisk-betanet
----
--
====

=== Logs

Monitor,(tail) the log file of Lisk.

[tabs]
====
--
[source,bash]
----
lisk core:logs lisk-betanet
----
--
====

=== Help

To access the Help menu please execute the following command listed below:

[source,bash]
----
lisk core
----

== Advanced commands

The advanced commands which can be used to manage your Lisk node can be seen in the commands reference list below:

=== Start database only

This command is used to start database instances apart from the Lisk process.

[tabs]
====
--
[source,bash]
----
lisk core:start:database lisk-betanet
----
--
====

=== Stop database only

This command is used to stop all database instances apart from the Lisk process.

[tabs]
====
--
[source,bash]
----
lisk core:stop:database lisk-betanet
----
--
====

=== Start cache only

This command is used to start caching apart from the Lisk process.

[tabs]
====
--
[source,bash]
----
lisk core:start:cache lisk-betanet
----
--
====

=== Stop cache only

This command is used to stop all caching apart from the Lisk process.

[tabs]
====
--
[source,bash]
----
lisk core:stop:cache lisk-betanet
----
--
====
