= Commander application commands
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core commander application commands describes all relevant commands to manage Lisk Core through the command-line with Lisk Commander.
:toc:
:page-next: /lisk-core/management/configuration.html
:page-previous: /lisk-core/setup/commander.html
:page-next-title: Configuration
:page-previous-title: Commander installation

:url_setup_commander: setup/commander.adoc
:url_upgrade_commander: update/commander.adoc

This section covers how to work with an application installation of Lisk Core.
Further information can be found by referring to the following application commands reference list.

== Basic commands

The available basic commands which can be used to manage your Lisk node are displayed here below:

=== Install

NOTE: For more information, please see the xref:{url_setup_commander}[Setup page of Lisk Core with Lisk Commander].

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:install lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:install --network=testnet lisk-testnet
----
--
====

=== Uninstall

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:uninstall lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:uninstall lisk-testnet
----
--
====

=== Status

Check the status of the Lisk Core node.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:status lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:status lisk-testnet
----
--
====

=== Upgrade

NOTE: For more information, please see the xref:{url_upgrade_commander}[Upgrade page of Lisk Core with Lisk Commander].

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:upgrade lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:upgrade lisk-testnet
----
--
====

=== Start

Start Lisk Core and PostgreSQL.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:start lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:start lisk-testnet
----
--
====

=== Stop

Stop Lisk Core and PostgreSQL.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:stop lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:stop lisk-testnet
----
--
====

=== Restart

Reload Lisk Core and pick up changes to config.json.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:restart lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:restart lisk-testnet
----
--
====

=== Logs

Monitor,(tail) the log file of Lisk.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:logs lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:logs lisk-testnet
----
--
====

=== Help

To access the Help menu please execute the following command listed below:

[source,bash]
----
lisk core
----

== Advanced commands

The advanced commands which can be used to manage your Lisk node, can be seen in the application commands reference list below:

=== Start database only

This command is used to start database instances apart from the Lisk process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:start:database lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:start:database lisk-testnet
----
--
====

=== Stop database only

This command is used to stop all database instances apart from the Lisk process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:stop:database lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:stop:database lisk-testnet
----
--
====

=== Start cache only

This command is used to start caching apart from the Lisk process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:start:cache lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:start:cache lisk-testnet
----
--
====

=== Stop cache only

This command is used to stop all caching apart from the Lisk process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:stop:cache lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:stop:cache lisk-testnet
----
--
====
