= Handle config files
Mona Bärenfänger <mona@lightcurve.io>
:description: How to configure Lisk Core.
// Settings
:toc:
:source-highlighter: coderay
:v_sdk: master
// External URLs
// Project URLs
:url_config: reference/config.adoc
:url_config_clo: reference/config.adoc#clo
:url_config_start: reference/config.adoc#start
:url_config_structure: reference/config.adoc#structure
:url_docker: management/docker.adoc
:url_management_api: {v_sdk}@lisk-sdk::guides/node-management/api-access.adoc
:url_management_forging: management/forging.adoc
:url_management_logging: {v_sdk}@lisk-sdk::guides/node-management/logging.adoc
:url_management_ssl: {v_sdk}@lisk-sdk::guides/node-management/enable-ssl.adoc
:url_sdk_framework: {v_sdk}@lisk-sdk::references/lisk-framework/index.adoc#config
:url_source: management/source.adoc

NOTE: A complete command reference with all available options for starting Lisk Core can be found in the xref:{url_config_start}[configuration reference].

== Connecting to a specific network

To connect to a specific network with Lisk Core, specify the desired network with the `--network` or `-n` flag.

[source,bash]
----
$ lisk-core start --network=NETWORK <1>
----

<1> `NETWORK` may be `devnet` or `betanet`.

== Using a custom config file

Lisk Core uses the network-specific configurations at `~/.lisk/lisk-core/config` by default.

It is possible though, to use Lisk Core with a custom config, by specifying the path to the config file with the `--config` or `-c` flag.

The custom config file needs to follow the JSON config structure of Lisk Core.
A simple way is to copy one of the network-specific defualt configs of Lisk Core, and adjust it to your needs.

[source,bash]
----
$ lisk-core start --config=path/to/custom-config.json
----

== Enabling plugins

Pugins like the httpApi plugin are not enabled by default.
Use the dedicated flags to enable them on application start:

[source,bash]
----
$ lisk-core start --enable-forger-plugin --enable-http-api-plugin
----
[source,bash]
----
USAGE
  $ lisk-core start

OPTIONS
  -c, --config=config                                                        File path to a custom config. Environment variable "LISK_CONFIG_FILE" can also be used.
  -d, --data-path=data-path                                                  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -l, --log=trace|debug|info|warn|error|fatal                                File log level. Environment variable "LISK_FILE_LOG_LEVEL" can also be used.
  -n, --network=network                                                      [default: mainnet] Default network config to use. Environment variable "LISK_NETWORK" can also be used.
  -p, --port=port                                                            Open port for the peer to peer incoming connections. Environment variable "LISK_PORT" can also be used.
  --api-ws                                                                   Enable websocket communication for api-client.
  --api-ws-port=api-ws-port                                                  Port to be used for api-client websocket.
  --console-log=trace|debug|info|warn|error|fatal                            Console log level. Environment variable "LISK_CONSOLE_LOG_LEVEL" can also be used.
  --enable-forger-plugin                                                     Enable Forger Plugin. Environment variable "LISK_ENABLE_FORGER_PLUGIN" can also be used.
  --enable-http-api-plugin                                                   Enable HTTP API Plugin. Environment variable "LISK_ENABLE_HTTP_API_PLUGIN" can also be used.
  --enable-ipc                                                               Enable IPC communication. This will also load up plugins in child process and communicate over IPC.
  --enable-monitor-plugin                                                    Enable Monitor Plugin. Environment variable "LISK_ENABLE_MONITOR_PLUGIN" can also be used.

  --enable-report-misbehavior-plugin                                         Enable ReportMisbehavior Plugin. Environment variable "LISK_ENABLE_REPORT_MISBEHAVIOR_PLUGIN" can also be
                                                                             used.

  --forger-plugin-port=forger-plugin-port                                    Port to be used for Forger Plugin. Environment variable "LISK_FORGER_PLUGIN_PORT" can also be used.

  --forger-plugin-whitelist=forger-plugin-whitelist                          List of IPs in comma separated value to allow the connection. Environment variable
                                                                             "LISK_FORGER_PLUGIN_WHITELIST" can also be used.

  --http-api-plugin-port=http-api-plugin-port                                Port to be used for HTTP API Plugin. Environment variable "LISK_HTTP_API_PLUGIN_PORT" can also be used.

  --http-api-plugin-whitelist=http-api-plugin-whitelist                      List of IPs in comma separated value to allow the connection. Environment variable
                                                                             "LISK_HTTP_API_PLUGIN_WHITELIST" can also be used.

  --monitor-plugin-port=monitor-plugin-port                                  Port to be used for Monitor Plugin. Environment variable "LISK_MONITOR_PLUGIN_PORT" can also be used.

  --monitor-plugin-whitelist=monitor-plugin-whitelist                        List of IPs in comma separated value to allow the connection. Environment variable
                                                                             "LISK_MONITOR_PLUGIN_WHITELIST" can also be used.

  --overwrite-config                                                         Overwrite network configs if they exist already

  --report-misbehavior-plugin-port=report-misbehavior-plugin-port            Port to be used for ReportMisbehavior Plugin. Environment variable "LISK_REPORT_MISBEHAVIOR_PLUGIN_PORT" can
                                                                             also be used.

  --report-misbehavior-plugin-whitelist=report-misbehavior-plugin-whitelist  List of IPs in comma separated value to allow the connection. Environment variable
                                                                             "LISK_REPORT_MISBEHAVIOR_PLUGIN_WHITELIST" can also be used.

  --seed-peers=seed-peers                                                    Seed peers to initially connect to in format of comma separated "ip:port". IP can be DNS name or IPV4 format.
                                                                             Environment variable "LISK_SEED_PEERS" can also be used.

EXAMPLES
  start
  start --network devnet --data-path ./data --log debug
----

////
[IMPORTANT]
====
If you are using the Docker image, Lisk Core is configured in a slightly different manner.
Please go to the xref:{url_docker}[Docker image commands] page to find out more regarding the docker-specific configuration of the Lisk Core.
====

[[network_specific_config]]
== Network-specific config files

The root folder for all configurations is `config/`.
The *default* network is `devnet`.
To connect to another network, specify the `network` when starting the Lisk Core as described in xref:{url_config}[Config reference].
The *network specific configurations* can be found under `config/<network>/config.json`, whereby `<network>` can be any of these values listed below:

* `devnet`
* `betanet`

[IMPORTANT]
====
Do not override any value in the files mentioned above, as the changes will be overwritten everytime the Lisk Core is upgraded.
If a custom configuration is required, use the environment variables or alternatively create your own `.json` file and pass it as xref:{url_config_clo}[command line option].
====


== Custom config file

Only the values required to be overwritten are necessary.
For all other options the pre-defined values will be used as described in the <<order, Config Load Order>> section.

[NOTE]
====
The *Application* and *Commander application* both provide a `config.json`, which can be customized as desired.

For the *Source code*, the config file needs to be created separately and needs to be passed as described below:
====

[tabs]
=====
Application::
+
--
The Lisk Core application provides a custom `config.json` which is stored in the root folder of your Lisk Core installation by default.

For example, if Lisk Core is installed under `~/lisk-beta`, then the config is stored directly in `~/lisk-beta/config.json`.

The updated `config.json` will be used automatically when reloading the node with the following command:

[source,bash]
----
bash lisk.sh reload
----
--
Commander application::
+
--
Lisk Commander provides a custom `config.json` which is stored in the root folder of your Lisk Core instance by default.

For example, if Lisk Core is installed under `~/.lisk/instances/lisk-betanet`, then the config is stored directly in `~/.lisk/instances/lisk-beta/config.json`.

The `config.json` will be used automatically when reloading the node with the following command:

[source,bash]
----
lisk core:restart lisk-betanet
----
--
Source code::
+
--
[source,bash]
----
pm2 stop lisk <1>
LISK_CONFIG_FILE=<CONFIG_PATH> pm2 start lisk <2>
----
<1> Stop Lisk Core in the case whereby it is running.
<2> Replace `<CONFIG_PATH>` with the path to your custom config file.
--
=====
////


