= Handle config files
Mona Bärenfänger <mona@lightcurve.io>
:description: Explains how to configure Lisk Core.
:toc:
:source-highlighter: coderay
:v_sdk: master
:url_config_clo: reference/config.adoc#clo
:url_source: management/source.adoc
:url_config_structure: reference/config.adoc#structure
:url_sdk_framework: {v_sdk}@lisk-sdk::reference/lisk-framework/index.adoc
:url_docker: management/docker.adoc


[IMPORTANT]
====
If you are using the Docker distribution, Lisk Core is configured in a slightly different manner.
Please go to the xref:{url_docker}[Docker commands] page to find out more about the docker-specific configuration of the Lisk Core.
====

[[network_specific_config]]
== Network-specific config files

The root folder for all configurations is `config/`.
The *default* network is `devnet`.
To connect to another network, specify the `network` when starting the Lisk Core, as described in xref:{url_source}[Source commands].
The *network specific configurations* can be found under `config/<network>/config.json`, whereby `<network>` can be any of these values listed below:

* `devnet`
* `betanet`


[IMPORTANT]
====
Do not override any value in the files mentioned above, as the changes will be overwritten everytime the Lisk Core is upgraded.
If a custom configuration is required, use the environment variables or alternatively create your own `.json` file and pass it as xref:{url_config_clo}[command line option].
====

== Custom config file

To use a custom config, firstly create a ``.json``-file.
Further information can be found in the <<_structure, Config Structure>> section.

Only the values required to be updated are needed, as for all other options the pre-defined values will be used as described in the <<order, Config Load Order>> section.

[NOTE]
====
*Binary* and *Commander* distributions both provide a config.json, which can be customized as desired.

For *Source* distributions, the config file needs to be created seperately and needs to be passed as described below:
====

[tabs]
=====
Binary::
+
--
The binary script provides a custom `config.json` which is stored in the root folder of your Lisk Core installation by default.

For example, Lisk Core for Betanet is installed under `~/lisk-beta`, and the config is stored directly in `~/lisk-beta/config.json`

The config.json will be used automatically when reloading the node with the following command:

[source,bash]
----
bash lisk.sh reload
----
--
Commander::
+
--
Lisk Commander provides a custom `config.json` which is stored in the root folder of your Lisk Core instance by default.

For example, Lisk Core for Betanet is installed under `~/.lisk/instances/lisk-betanet`, and the config is stored directly in `~/.lisk/instances/lisk-beta/config.json`

The config.json will be used automatically when reloading the node with the following command:
--
Source::
+
--
[source,bash]
----
pm2 stop lisk <1>
LISK_CONFIG_FILE=<CONFIG_PATH> pm2 start lisk <2>
----
<1> Stop Lisk Core in the case whereby it is running.
<2> Replace `<CONFIG_PATH>` with the path to your custom config file.
--
=====

[[order]]
== Config load order

Configurations will be loaded in the following order listed below.
Each configuration will override the previous one:

. Default configuration values of modules and components of the xref:{url_sdk_framework}[Lisk Framework].
. <<network_specific_config, Network specific configuration file>>.
. A xref:{url_config_clo}[custom configuration file] (if specified by the user).
. xref:{url_config_clo}[Command line configurations], specified as command-line flags or `ENV` variables.

For development purposes, use `devnet` as the network option.
Other networks are specific to public Lisk networks.

The `config.json` file and a description of each configurable parameter.
