= Management overview
Mona Bärenfänger <mona@lightcurve.io>

:url_binary: management/binary.adoc
:url_commander: management/commander.adoc
:url_docker: management/docker.adoc
:url_source: management/source.adoc


The management section includes guides and references regarding the configuration and management of Lisk Core. It provides a command reference specific for each distribution, including many further useful guides. For example,
how to enable forging and also how to control the API access of a node.

1. xref:{url_binary}[*Binary*] -  This is the easiest installation to complete as it is automated and is also the default configuration.
2. xref:{url_commander}[*Commander*] -   The Lisk commander offers an alternative method to install and further manage Lisk core.
3. xref:{url_docker}[*Docker*] -  Docker provides the options to run Lisk nodes on other platforms.
4. xref:{url_source}[*Source*] -  This offers the user the possibility to develop on the Lisk core codebase, and has an extensive test suite which can provide the advanced user and developers the possibility to use the latest codebase.

Furthermore, once the desired installation is completed, then controlling the application access is also covered in this section, together with the network specific configuration possibilities, and   how to check, enable and disable forging.
In addition, how to activate the log levels including their destinations and rotation, coupled with finally describing how to set up a secure ssl connection concludes this management overview description.


After reading this section the node setup guide for the required distribution is covered further in the Setup section.


