= Management overview
Mona Bärenfänger <mona@lightcurve.io>


Initially the management section comprises of the following types of Lisk core installation distribution possibilities listed below:-

1. *Binary* -  This is the easiest installation to complete as it is automated and is also the default configuration.
2. *Commander* -  The Lisk commander offers an alternative method to install and further manage Lisk core.
3. *Docker* - Docker provides the options to run Lisk nodes on other platforms.
4. *Source* - This offers the user the possibility to develop on the Lisk core codebase, and has an extensive test suite which can provide the advanced user and developers the possibility to use the latest codebase.

Furthermore, once the desired installation is completed, then controlling the application access is also covered in this section, together with the network specific configuration possibilities, and   how to check, enable and disable forging.
In addition, how to activate the log levels including their destinations and rotation, coupled with finally describing how to set up a secure ssl connection concludes this management overview description.


After reading this section the node setup guide for the required distribution is covered further in the Setup section.



