= Management
Mona Bärenfänger <mona@lightcurve.io>
:description: How to manage the Lisk Core CLI, node management, and the default setup are covered here.

:url_binary: management/application.adoc
:url_commander: management/commander.adoc
:url_docker: management/docker.adoc
:url_source: management/source.adoc
:url_reference_cli: reference/cli.adoc

////
The management section includes guides and references regarding the configuration and management of Lisk Core. It provides a command reference specific for each distribution, including many further useful guides. For example,
how to enable forging and also how to control the API access of a node.


1. xref:{url_binary}[*Application commands*] -  This is the easiest installation to complete as it is automated and is also the default configuration.
2. xref:{url_commander}[*Commander application commands*] -   The Lisk Commander offers an alternative method to install and further manage Lisk Core.
3. xref:{url_docker}[*Docker image commands*] -  Docker provides the options to run Lisk nodes on other platforms.
4. xref:{url_source}[*Source code commands*] -  This offers the user the possibility to develop on the Lisk Core codebase, and has an extensive test suite which can provide the advanced user and developers the possibility to use the latest codebase.

Furthermore, once the desired installation is completed, then controlling the application access is also covered in this section, together with the network specific configuration possibilities, and   how to check, enable and disable forging.
In addition, how to activate the log levels including their destinations and rotation, coupled with finally describing how to set up a secure ssl connection concludes this management overview description.


After reading this section the node setup guide for the required distribution is covered further in the Setup section.
////

== The command-line interface

How to use the Lisk Core CLI.

[source,bash]
----
lisk-core start
# From other terminal
lisk-core node:info
----

More information about available commands can be found in the xref:{url_reference_cli}[Lisk Core CLI reference].

== Node management

With the new Lisk Core CLI, additional process management is recommended.
Any process management tool can be used to manage the Lisk Core node.
We recommend using PM2 to manage the instance.

=== Quick setup

[source,bash]
----
npm i -g pm2
pm2 start "lisk-core start --network betanet --api-ipc" --name 'lisk-core'
----

=== Default setup

Create a pm2 config as below for example...

.pm2.conf.json
[source,json]
----
{
  "name": "lisk-core",
  "script": "lisk-core start",
  "env": {
    "LISK_NETWORK": "betanet",
    "LISK_PORT": 5001
  }
}
----

...and start the node using the config:

[source,bash]
----
pm2 start pm2.conf.json
----

For more information, please refer to https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/

All available options for `scripts` and `env` can be found in `lisk-core start --help`.
