= Testnet and Mainnet v3 migration guide
:toc:
:experimental:
:idprefix:
:idseparator: -
:sectnums:
:sectnumlevels: 5
// External URLs
:url_wallet: https://lisk.io/wallet
// Project URLs
:url_core_install: setup/binary.adoc
:url_core_2_install: master@lisk-core::setup/application.adoc
:url_core_2_update: master@lisk-core::update/application.adoc
:url_sdk_protocol_voteweight: master@lisk-sdk:protocol:consensus-algorithm.adoc#voting_and_weight

This guide describes how to migrate a Lisk Core 2.1.6 node

== Preparation

=== Preparing Lisk Core 2.1.6 for the update

==== Ensure you are running the binary distribution of Lisk Core
If you are using a different distribution of Lisk Core, like Docker, Commander or Source, you need to xref:{url_core_2_install}[install the binary distribution] to be able to seamlessly migrate to Lisk Core 3.0.0.

==== Ensure you are running version 2.1.6 of Lisk Core
Ensure you are running version 2.1.6 of Lisk Core to be able to seamlessly migrate to Lisk Core 3.0.0.

Open `package.json` to check the `version` of your Lisk Core node.
If your version is lower than 2.1.6 make sure to xref:{url_core_2_update}[update Lisk Core] before you proceed with the migration.

==== Ensure your node is fully synced with the network
Check the current block height of your node directly in the terminal by running:

[tabs]
====
Mainnet::
+
--
./home/lisk/lisk-main
[source,bash]
----
$ bash lisk.sh status
Lisk configured for mainnet
[+] Lisk is running as PID: 24468
Current Block Height:   14992772
----
--
Testnet::
+
--
./home/lisk/lisk-test
[source,bash]
----
$ bash lisk.sh status
Lisk configured for testnet
[+] Lisk is running as PID: 24751
Current Block Height:  13279765
----
--
====

Compare the current height of your node to the network height in {url_wallet}[Lisk Desktop^], which is shown on the kbd:[Network] or kbd:[Blocks] pages.

If both heights are equal, it is verified that your node is fully synched with the network.

NOTE: For seeing the current height of Lisk Testnet, use the network switcher of Lisk Desktop, which can be enabled in the settings.

=== Setting up the lisk migrator

==== Download the lisk-migrator
Download the lisk-migrator by running the following command in the terminal:

[source,bash]
----
curl -o lisk-migrator.tar.gz <file name>
----
==== Download checksum and verify
Download the checksum and verify the successful download of lisk-migrator.

===== Download the checksum.

[source,bash]
----
curl <file name>.SHA256
----
{counter:seq3}) Run the following command in the terminal and ensure the output is `sha256sum: <file name>: OK` (note: command name and output may vary on macOS).

[source,bash]
----
sha256sum -c <file name>.SHA256
----

=== Setting up Lisk Core 3.0.0

Follow the guide how to xref:{url_core_install}[setup Lisk Core 3.0.0] for the binary distribution.

IMPORTANT: Don't start Lisk Core 3.0.0 yet.

=== Create a custom config with your delegate information

First copy the existing config file for the respective network.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cp ~/lisk-core/config/mainnet/config.json ~/lisk-core/custom-config.json <1>
----
--
Testnet::
+
--
[source,bash]
----
cp ~/lisk-core/config/testnet/config.json ~/lisk-core/custom-config.json <1>
----
--
====

Next, use the CLI of Lisk Core 3.0.0 to generate the delegate configruation data.

After running the command, you will be prompted for your delegates passphrase and for the password that will be used to encrypt the passphrase, so it can be stored securely in the delegate configuration data.

[source,bash]
----
lisk-core forging:config --pretty
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
? Please enter password:  [hidden]
? Please re-enter password:  [hidden]
----

After providing the required inputs, the delegate configuration data will be returned in the terminal.

Copy the generated delegate data object and add it to your custom configuration under the `forging.delegates` key:

.custom-config.json
[source,js]
----
{
  //...
  forging: {
    force: false,
    delegates: [ <1>
        {
            address: "86555265f0110b4ed5a8cb95dbc732e77732c474",
            encryptedPassphrase: "iterations=1&salt=476d4299531718af8c88156aab0bb7d6&cipherText=663dde611776d87029ec188dc616d96d813ecabcef62ed0ad05ffe30528f5462c8d499db943ba2ded55c3b7c506815d8db1c2d4c35121e1d27e740dc41f6c405ce8ab8e3120b23f546d8b35823a30639&iv=1a83940b72adc57ec060a648&tag=b5b1e6c6e225c428a4473735bc8f1fc9&version=1",
            hashOnion: {
                "count": 1000000,
                "distance": 1000,
                "hashes": [
                    "ff2156e33c4aefa4a5a790edbe329f4a",
                    "5f86db180d4e63be6412d42d444dfb49",
                    "10fc37bb42d7f77030138e45795fef65",
                    "f04a306a73c5d7d94cc4f262b4d5ebb4",
                    //[...]
                    "ca41d52225f4b76140fc7f277731d326",
                    "fde61109609b74ba16d5ebd72a8b446f",
                    "9752dc2228492466d7c2046354d5fdfd"
                ]
            }
        }
    ],
  },
  //...
}
----

<1>  The list of delegates who are allowed to forge on this node.

== Migration steps

//TODO: Add URL to snapshot height announcement

=== Check the announced snapshot height

Check the announced snapshot height on <WEBSITE>.

The height is needed as parameter of the `lisk-migrator` script in the next step.
A snapshot of the blockchain will be created at this particular height, which then will be used to create the genesis block for the new blockchain.

//TODO: At what particular time should the migrator script be running?
=== Run lisk migrator

[IMPORTANT]
====
.When to start the migrator script?
lisk-migrator can be started any time before the announced snapshot height.
====

If you have added the `lisk-migrator` to the PATH like described in section <<setting-up-the-lisk-migrator>> you can start the migration script by running the following command in the terminal:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk-migrator --snapshot-height ${snapshotHeight} --output ~/.lisk/lisk-core/config/mainnet/genesis_block.json --lisk-core-path path_to_lisk_core_v2
----
--
Testnet::
+
--
[source,bash]
----
lisk-migrator --snapshot-height ${snapshotHeight} --output ~/.lisk/lisk-core/config/testnet/genesis_block.json --lisk-core-path path_to_lisk_core_v2
----
--
====


[NOTE]
====
The snapshot height will be announced seperately.
====

Observe if `lisk-migrator` finishes successfully (takes about 30-60 min from the snapshot height).

=== Wait until the network reaches the snapshot height
After the snapshot height is reached, delegates have approximately 2 hours time to start their Lisk Core 3.0.0 and enable forging on them, to ensure they wont miss any blocks after the hardfork.

Is case the node is started at a later point in time, the node will simply sync to the current network height.
For delegates, this might mean they miss a block, for every one else it has no further effect.

=== Stop Lisk Core 2.1.6

After the announced snapshot height has passed, there is no reason annymore to run Lisk Core 2.1.6 and it is recommended to stop it.

Navigate into the root folder of your Lisk Core 2.1.6 installation and run the following command to stop the old Lisk Core version:

[source,bash]
----
bash lisk.sh stop
----

=== Start Lisk Core 3.0.0
Use the Lisk Core CLI to start Lisk Core 3.0.0.

Run the following command in the terminal:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk-core start --network mainnet --config=custom-config.json
----
--
Testnet::
+
--
[source,bash]
----
lisk-core start --network testnet --config=custom-config.json
----
--
====

=== Check new account address

It is necessary to know your new address to enable forging for your delegate in the new network.

Use the following command to see your new account address.
You will be prompted for your passphrase from which the other account details will be generated.

[source,bash]
----
lisk-core account:show
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
----

This will return an object including `privateKey`, `publicKey`, `address` and `binaryAddress`.

* The value under `binaryAddress` is used to self-vote for the delegate account in the next step.
* The value under the `address` key is used to enable forging in the last step.

=== Self-voting

In the new DPoS rules, delegates need to self-vote with a significant amount of tokens to be able to reach forging positions.

For more information, how self-voting affects the vote weight, see xref:{url_sdk_protocol_voteweight}[Delegates, voting and delegate weight (Lisk Protocol)]

Use the Lisk Core CLI to cast the self-vote with the desired amount of tokens.

[source,bash]
----
$ lisk-core transaction:create 5 1 100000000
? Please enter: votes(delegateAddress, amount):  89aa5fc8861d392f60662f76a379cc348fe97d28, 148000000000
? Want to enter another votes(delegateAddress, amount) No
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
{"transaction":"0805100118012080c2d72f2a2024350a05e078b181fa8f3c273ca9882a8f5ed6efbaf3d1537665f9480635273f321f0a1d0a1489aa5fc8861d392f60662f76a379cc348fe97d281080a0e6d7ce083a403aef0012b05f3d962e3bc4b1ba70d6cc4fea783e24c02c36bc644e283ef2dd7618ec072594505c7ab8ce2a1e22dda5e90c51be79d06ac4871daf8430ff6a330b"}
$ lisk-core transaction:send 0805100118012080c2d72f2a2024350a05e078b181fa8f3c273ca9882a8f5ed6efbaf3d1537665f9480635273f321f0a1d0a1489aa5fc8861d392f60662f76a379cc348fe97d281080a0e6d7ce083a403aef0012b05f3d962e3bc4b1ba70d6cc4fea783e24c02c36bc644e283ef2dd7618ec072594505c7ab8ce2a1e22dda5e90c51be79d06ac4871daf8430ff6a330b
Transaction with id: '6a6121adf6a73a857bef92eaec9c29545f53c9196a16faa1eafdf58012f5a2e5' received by node.
----

=== Enable forging

As last step, enable forging on the node for your delegate.

Again, this can be done by using the Lisk Core CLI.
Just use it with your own delegate address.

The `0 0 0` stand for the three variables `HEIGHT`, `MAXHEIGHTPREVIOUSLYFORGED`, `MAXHEIGHTPREVOTED`, which are zero for every delegate who joins the network for the first time.

[source,bash]
----
lisk-core forging:enable lskybqmgrpbckjrf2cbmhs6bf7obrnfrg433j8n7w 0 0 0 <1>
----

<1> Replace the address with your delegate address.
