= Testnet and Mainnet v3 migration guide
// External URLs
:url_wallet: https://lisk.io/wallet
// Project URLs
:url_core_2_install: master@lisk-core::setup/application.adoc
:url_core_2_update: master@lisk-core::update/application.adoc

This guide describes how to migrate a Lisk Core 2.1.6 node

== Preparation

=== Preparing Lisk Core 2.1.6 for the update
Ensure you are running the binary distribution of Lisk Core::
If you are using a different distribution of Lisk Core, like Docker, Commander or Source, you need to xref:{url_core_2_install}[install the binary distribution] to be able to seamlessly migrate to Lisk Core 3.0.0.

Ensure you are running version 2.1.6 of Lisk Core::
Ensure you are running version 2.1.6 of Lisk Core to be able to seamlessly migrate to Lisk Core 3.0.0.
+
Open `package.json` to check the `version` of your Lisk Core node.
If your version is lower than 2.1.6 make sure to xref:{url_core_2_update}[update Lisk Core] before you proceed with the migration.

Ensure your node is fully synced with the network::
Check the current block height of your node directly in the terminal by running:
+
./home/lisk/lisk-test or for Mainnet /home/lisk/lisk-main
[source,bash]
----
$ bash lisk.sh status
Lisk configured for testnet
[+] Lisk is running as PID: 24751
Current Block Height:  13279765
----

Compare the current height of your node to the network height in {url_wallet}[Lisk Desktop^], which is shown on the kbd:[Network] or kbd:[Blocks] pages.

If both heights are equal, it is verified that your node is fully synched with the network.

NOTE: For seeing the current height of Lisk Testnet, use the network switcher of Lisk Desktop, which can be enabled in the settings.

=== Setting up the lisk migrator

=== Setting up Lisk Core 3.0.0

== Migration steps

=== Run lisk migrator

=== Stop Lisk Core 2.1.6

=== Start Lisk Core 3.0.0

