= Source code commands
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Source code commands describes all relevant commands to manage Lisk Core with pm2.
:toc:
:page-next: /lisk-core/management/configuration.html
:page-previous: /lisk-core/setup/source.html
:page-next-title: Configuration
:page-previous-title: Source code installation

:url_admin_binary: administration/application.adoc#create_snapshot
:url_core_snapshots: index.adoc#snapshots

This section covers how to manage a Source code installation of Lisk Core.

== Basic commands

=== Status

Check the status of the Lisk Core node.

[source,bash]
----
pm2 status lisk
----

=== Start

Start Lisk Core.

[source,bash]
----
pm2 start lisk
----

=== Stop

Stop Lisk Core.

[source,bash]
----
pm2 stop lisk
----

=== Restart

Restart Lisk Core.

[source,bash]
----
pm2 restart lisk
----

=== Delete

Remove Lisk Core process from pm2 list.

[source,bash]
----
pm2 delete lisk
----

=== Add

In case this was not completed during the installation process, add your Lisk Core process to pm2 under the name `lisk`.

[source,bash]
----
pm2 start --name lisk dist/index.js -- --network [network]
----

It is possible to choose the `devnet` (default), `testnet` or `mainnet` for the `[network]` option.

=== Logs

Display Lisk Core logs in streaming.

[source,bash]
----
pm2 logs
----

== Utility scripts

There are some command line scripts available that will assist the Lisk user, by performing certain helpful and convenient operations.

All scripts are located under `./scripts/` directory and can be executed directly by `node scripts/<file_name>`.

=== Generate config

This script shown below will help to generate a unified version of the configuration file for any network:

[source,bash]
----
Usage: node scripts/generate_config.js [options]

Options:

-h, --help               output usage information
-V, --version            output the version number
-c, --config [config]    custom config file
-n, --network [network]  specify the network or use LISK_NETWORK
----

Argument `network` is required, and it may be either `devnet`, `testnet`, `mainnet` or any other network folder available under `./config` directory.

=== Update config

This next script is designed to keep track of all changes introduced in Lisk over time in different versions.
If you have one config file existing in any specific version, and you wish to make it compatible with other versions of the Lisk, then execute this update config script shown below:

[source,bash]
----
Usage: node scripts/update_config.js [options] <input_file> <from_version> [to_version]

Options:

-h, --help               output usage information
-V, --version            output the version number
-n, --network [network]  specify the network or use LISK_NETWORK
-o, --output [output]    output file path
----

As can be seen from the usage guide, `input_file` and `from_version` are required.
If you skip `to_version` argument changes in `config.json` will be applied up to the latest version of Lisk Core.
If you do not specify `--output` path the final `config.json` will be printed to stdout.
If you do not specify `--network` argument, it will have to be loaded from `LISK_NETWORK` env variable.

== Creating snapshots

[TIP]
====
For creating xref:{url_core_snapshots}[snapshots] in the most convenient manner, it is recommended to use Lisk Core from the xref:{url_admin_binary}[Application distribution].
Execute the script `lisk-snapshot.sh`, which will then perform all the necessary steps to create a snapshot of the blockchain.
====

To create a snapshot manually, perform the following steps:

*Example:* Creating a snapshot for Lisk Mainnet.

[TIP]
====
The template database to be used should be the actual database defined in the `components.storage.database` in the `config.json` file of Lisk Core.
Its recommended to document the current block height of the snapshot and to include it in the snapshots’ filename.
====

[source,bash]
----
pm2 stop lisk <1>
createdb --template="lisk_main" lisk_snapshot <2>
pm2 start lisk <3>
psql --dbname=lisk_snapshot --command='TRUNCATE peers, mem_accounts2u_delegates, mem_accounts2u_multisignatures;' <4>
psql --dbname=lisk_snapshot --tuples-only --command='SELECT height FROM blocks ORDER BY height DESC LIMIT 1;' | xargs <5>
pg_dump --no-owner lisk_snapshot |gzip -9 > snapshot-lisk_mainnet-<current-block-height>.gz <6>
dropdb lisk_snapshot <7>
----

<1> Stops the Lisk Core node.
<2> Copies the Lisk Mainnet database to a new database `lisk_snapshot`.
During this process, no open connections are allowed to `lisk_main` or it will fail.
<3> Restarts the Lisk Core node again.
<4> Remove the redundant data.
<5> Executes this SQL query to acquire the last block height of the snapshot.
<6> Dumps the database and compresses it.
Replaces the current-block-height with the height that was returned by the SQL query above.
<7> Deletes the snapshot database.

== Rebuild from a snapshot

In some scenarios, it is recommended to restore the blockchain from a xref:{url_core_snapshots}[snapshot].
The command lines shown below will perform this process.
The URL can be substituted for another `blockchain.db.gz` snapshot file if so desired.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
pm2 stop lisk <1>
dropdb lisk_main <2>
wget https://downloads.lisk.io/lisk/main/blockchain.db.gz <3>
createdb lisk_main <4>
gunzip -fcq blockchain.db.gz | psql -d lisk_main <5>
pm2 start lisk <6>
----

<1> Stops the Lisk Core node.
<2> Deletes the Lisk Mainnet database.
<3> Downloads the Lisk snapshot.
<4> Creates a fresh Lisk Mainnet database.
<5> Imports the downloaded snapshot into the new database.
<6> Restarts the Lisk Core node again.

--
Testnet::
+
--
[source,bash]
----
pm2 stop lisk <1>
dropdb lisk_test <2>
wget https://downloads.lisk.io/lisk/test/blockchain.db.gz <3>
createdb lisk_test <4>
gunzip -fcq blockchain.db.gz | psql -d lisk_test <5>
pm2 start lisk <6>
----

<1> Stops the Lisk Core node.
<2> Deletes the Lisk Testnet database.
<3> Downloads the Lisk snapshot.
<4> Creates a fresh Lisk Testnet database.
<5> Imports the downloaded snapshot into the new database.
<6> Restarts the Lisk Core node again.
--
====
