= BFT
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references regarding the BFT package of Lisk Elements.
:toc:

@liskhq/lisk-bft is byzantine fault tolerance implementation according to the Lisk protocol.

== Installation

[source,bash]
----
npm install @liskhq/lisk-bft
----

== Update

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @liskhq/lisk-bft
----

////
{
  EVENT_BFT_BLOCK_FINALIZED: 'EVENT_BFT_BLOCK_FINALIZED',
  BFTFinalizedHeightCodecSchema: {
    type: 'object',
    '$id': '/BFT/FinalizedHeight',
    title: 'Lisk BFT Finalized Height',
    properties: { finalizedHeight: [Object] },
    required: [ 'finalizedHeight' ]
  },
  BFT: [class BFT extends EventEmitter],
  forgingSlot: [Function],
  isBlockReceivedWithinForgingSlot: [Function],
  isLastAppliedBlockReceivedWithinForgingSlot: [Function],
  isValidBlock: [Function],
  isIdenticalBlock: [Function],
  isDuplicateBlock: [Function],
  isDoubleForging: [Function],
  isTieBreak: [Function],
  isDifferentChain: [Function],
  ForkStatus: {
    '1': 'IDENTICAL_BLOCK',
    '2': 'VALID_BLOCK',
    '3': 'DOUBLE_FORGING',
    '4': 'TIE_BREAK',
    '5': 'DIFFERENT_CHAIN',
    '6': 'DISCARD',
    IDENTICAL_BLOCK: 1,
    VALID_BLOCK: 2,
    DOUBLE_FORGING: 3,
    TIE_BREAK: 4,
    DIFFERENT_CHAIN: 5,
    DISCARD: 6
  },
  BFTError: [class BFTError extends Error],
  BFTInvalidAttributeError: [class BFTInvalidAttributeError extends BFTError],
  areHeadersContradicting: [Function]
}
////
