= Chain
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references regarding the chain package of Lisk Elements.
:toc:

@liskhq/lisk-chain implements blocks and state management that are used for block processing according to the Lisk protocol.

== Installation

[source,bash]
----
npm install @liskhq/lisk-chain
----

== Update

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @liskhq/lisk-chain
----

////
{
  events: {
    EVENT_DELETE_BLOCK: 'EVENT_DELETE_BLOCK',
    EVENT_NEW_BLOCK: 'EVENT_NEW_BLOCK',
    EVENT_VALIDATORS_CHANGED: 'EVENT_VALIDATORS_CHANGED'
  },
  Chain: [class Chain],
  Transaction: [class Transaction],
  transactionSchema: {
    '$id': 'lisk/transaction',
    type: 'object',
    required: [
      'moduleID',
      'assetID',
      'nonce',
      'fee',
      'senderPublicKey',
      'asset'
    ],
    properties: {
      moduleID: [Object],
      assetID: [Object],
      nonce: [Object],
      fee: [Object],
      senderPublicKey: [Object],
      asset: [Object],
      signatures: [Object]
    }
  },
  calculateMinFee: [Function],
  blockHeaderAssetSchema: {
    '$id': '/blockHeader/asset/v2',
    type: 'object',
    properties: {
      maxHeightPreviouslyForged: [Object],
      maxHeightPrevoted: [Object],
      seedReveal: [Object]
    },
    required: [ 'maxHeightPreviouslyForged', 'maxHeightPrevoted', 'seedReveal' ]
  },
  blockHeaderSchema: {
    '$id': '/block/header',
    type: 'object',
    properties: {
      version: [Object],
      timestamp: [Object],
      height: [Object],
      previousBlockID: [Object],
      transactionRoot: [Object],
      generatorPublicKey: [Object],
      reward: [Object],
      asset: [Object],
      signature: [Object]
    },
    required: [
      'version',
      'timestamp',
      'height',
      'previousBlockID',
      'transactionRoot',
      'generatorPublicKey',
      'reward',
      'asset'
    ]
  },
  blockSchema: {
    '$id': '/block',
    type: 'object',
    properties: { header: [Object], payload: [Object] },
    required: [ 'header', 'payload' ]
  },
  signingBlockHeaderSchema: {
    '$id': '/block/header/signing',
    type: 'object',
    properties: {
      version: [Object],
      timestamp: [Object],
      height: [Object],
      previousBlockID: [Object],
      transactionRoot: [Object],
      generatorPublicKey: [Object],
      reward: [Object],
      asset: [Object]
    },
    required: [
      'version',
      'timestamp',
      'height',
      'previousBlockID',
      'transactionRoot',
      'generatorPublicKey',
      'reward',
      'asset'
    ]
  },
  validatorsSchema: {
    '$id': '/state/validators',
    type: 'object',
    required: [ 'validators' ],
    properties: { validators: [Object] }
  },
  getGenesisBlockHeaderAssetSchema: [Function],
  stateDiffSchema: {
    '$id': '/state/diff',
    type: 'object',
    required: [ 'updated', 'created' ],
    properties: { updated: [Object], created: [Object], deleted: [Object] }
  },
  getRegisteredBlockAssetSchema: [Function],
  CONSENSUS_STATE_VALIDATORS_KEY: 'validators',
  CONSENSUS_STATE_FINALIZED_HEIGHT_KEY: 'finalizedHeight',
  Slots: [class Slots],
  readGenesisBlockJSON: [Function],
  getValidators: [AsyncFunction],
  getAccountSchemaWithDefault: [Function],
  testing: { StateStoreMock: [class StateStoreMock] }
}
////
