= Client
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references for the clients packages of Lisk Elements including sub-packages, upgrade & usage instructions.
:page-aliases: lisk-elements/packages/client.adoc, reference/lisk-elements/packages/client.adoc
:toc:
:url_elements_api: references/lisk-elements/api-client.adoc
:url_elements_constants: references/lisk-elements/constants.adoc
:url_elements_cryptography: references/lisk-elements/cryptography.adoc
:url_elements_passphrase: references/lisk-elements/passphrase.adoc
:url_elements_transactions: references/lisk-elements/transactions.adoc

This provides a default set of packages for use by clients of the Lisk network.

[NOTE]
====
The `Client` package is a collection of the following packages:

xref:{url_elements_api}[api-client], xref:{url_elements_constants}[constants],
xref:{url_elements_cryptography}[cryptography], xref:{url_elements_passphrase}[passphrase],
xref:{url_elements_transactions}[transactions].
====

Lisk Elements will include numerous different packages in the future which can be plugged in to applications as desired.

For enhanced usability Lisk Elements provides special wrapper packages such as `lisk-client`, whose group packages are often used in the same context.

== Installation

How to add Lisk client as a dependency of your project:

[source,bash]
----
$ npm install @liskhq/lisk-client
----

== Upgrade

How to perform an upgrade:

[source,bash]
----
npm update @liskhq/lisk-client
----

== Usage

How to import `lisk-client` using the ES6 modules syntax:

[source,js]
----
import lisk from '@liskhq/lisk-client';
----

Alternatively, how to use Node.js modules:

[source,js]
----
const lisk = require('@liskhq/lisk-client');
----

Or if it is required, how to import the specific namespaced functionality is shown below:

[source,js]
----
import { APIClient, transactions } from '@liskhq/lisk-client';
// or
const { APIClient, transactions } = require('@liskhq/lisk-client');
----
