= P2P
:description: This section covers how to install, update, and use the P2P library together with some relevant examples.
:toc:

@liskhq/lisk-p2p is a package for creating unstructured P2P networks.
The package in abstraction enables peer discovery, network security, and reliability.
A developer can leverage all the underlying specifications proposed in https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md[LIP: 0004: Introduce robust peer selection and banning mechanism] and use the package for building p2p use cases.

== Installation

[source,bash]
----
npm install --save @liskhq/lisk-p2p
----

== Update

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @liskhq/lisk-p2p
----

////
{
  constants: {
    DEFAULT_NODE_HOST_IP: '0.0.0.0',
    DEFAULT_LOCALHOST_IP: '127.0.0.1',
    DEFAULT_BAN_TIME: 86400000,
    DEFAULT_POPULATOR_INTERVAL: 10000,
    DEFAULT_FALLBACK_SEED_PEER_DISCOVERY_INTERVAL: 30000,
    DEFAULT_SEND_PEER_LIMIT: 16,
    DEFAULT_CONTROL_MESSAGE_LIMIT: 10,
    DEFAULT_WS_MAX_MESSAGE_RATE: 100,
    DEFAULT_WS_MAX_MESSAGE_RATE_PENALTY: 10,
    DEFAULT_RATE_CALCULATION_INTERVAL: 1000,
    DEFAULT_WS_MAX_PAYLOAD: 3048576,
    DEFAULT_NONCE_LENGTH_BYTES: 8,
    DEFAULT_RANDOM_SECRET: 3758309947,
    DEFAULT_MAX_OUTBOUND_CONNECTIONS: 20,
    DEFAULT_MAX_INBOUND_CONNECTIONS: 100,
    DEFAULT_OUTBOUND_SHUFFLE_INTERVAL: 300000,
    DEFAULT_PEER_PROTECTION_FOR_NETGROUP: 0.034,
    DEFAULT_PEER_PROTECTION_FOR_LATENCY: 0.068,
    DEFAULT_PEER_PROTECTION_FOR_USEFULNESS: 0.068,
    DEFAULT_PEER_PROTECTION_FOR_LONGEVITY: 0.5,
    DEFAULT_MIN_PEER_DISCOVERY_THRESHOLD: 100,
    DEFAULT_MAX_PEER_DISCOVERY_RESPONSE_LENGTH: 200,
    DEFAULT_MAX_PEER_INFO_SIZE: 20480,
    DEFAULT_MIN_TRIED_PEER_COUNT: 100,
    DEFAULT_CONNECT_TIMEOUT: 2000,
    DEFAULT_ACK_TIMEOUT: 2000,
    DEFAULT_REPUTATION_SCORE: 100,
    DEFAULT_PRODUCTIVITY_RESET_INTERVAL: 20000,
    DEFAULT_PEER_STATUS_MESSAGE_RATE: 4,
    DEFAULT_PRODUCTIVITY: {
      requestCounter: 0,
      responseCounter: 0,
      responseRate: 0,
      lastResponded: 0
    },
    DEFAULT_HTTP_PATH: '/rpc/',
    INVALID_PEER_LIST_PENALTY: 100,
    INVALID_PEER_INFO_PENALTY: 100,
    DEFAULT_PING_INTERVAL_MAX: 60000,
    DEFAULT_PING_INTERVAL_MIN: 20000,
    DEFAULT_NEW_BUCKET_COUNT: 128,
    DEFAULT_NEW_BUCKET_SIZE: 32,
    DEFAULT_EVICTION_THRESHOLD_TIME: 86400000,
    DEFAULT_TRIED_BUCKET_COUNT: 64,
    DEFAULT_TRIED_BUCKET_SIZE: 32,
    DEFAULT_MAX_RECONNECT_TRIES: 3,
    INTENTIONAL_DISCONNECT_CODE: 1000,
    SEED_PEER_DISCONNECTION_REASON: 'Disconnect from SeedPeer after discovery',
    INVALID_CONNECTION_URL_CODE: 4501,
    INVALID_CONNECTION_URL_REASON: 'Peer did not provide a valid URL as part of the WebSocket connection',
    INVALID_CONNECTION_QUERY_CODE: 4502,
    INVALID_CONNECTION_QUERY_REASON: 'Peer did not provide valid query parameters as part of the WebSocket connection',
    INVALID_CONNECTION_SELF_CODE: 4101,
    INVALID_CONNECTION_SELF_REASON: 'Peer cannot connect to itself',
    INCOMPATIBLE_NETWORK_CODE: 4102,
    INCOMPATIBLE_NETWORK_REASON: 'Peer networkIdentifier did not match our own',
    INCOMPATIBLE_PROTOCOL_VERSION_CODE: 4103,
    INCOMPATIBLE_PROTOCOL_VERSION_REASON: 'Peer has incompatible protocol version',
    INCOMPATIBLE_PEER_CODE: 4104,
    INCOMPATIBLE_PEER_UNKNOWN_REASON: 'Peer is incompatible with the node for unknown reasons',
    INCOMPATIBLE_PEER_INFO_CODE: 4105,
    INCOMPATIBLE_PEER_INFO_CODE_REASON: 'Peer has invalid PeerInfo',
    FORBIDDEN_CONNECTION: 4403,
    FORBIDDEN_CONNECTION_REASON: 'Peer is not allowed to connect',
    EVICTED_PEER_CODE: 4418,
    DUPLICATE_CONNECTION: 4404,
    DUPLICATE_CONNECTION_REASON: 'Peer has a duplicate connection',
    INVALID_PEER_INFO_LIST_REASON: 'PeerInfo list has invalid value',
    PEER_INFO_LIST_TOO_LONG_REASON: 'PeerInfo list is too long',
    ConnectionKind: { OUTBOUND: 'outbound', INBOUND: 'inbound', NONE: 'none' },
    PeerKind: {
      FIXED_PEER: 'fixedPeer',
      WHITELISTED_PEER: 'whitelistedPeer',
      SEED_PEER: 'seedPeer',
      BLACKLISTED_PEER: 'blacklistedPeer',
      NONE: 'NONE'
    }
  },
  errors: {
    PeerInboundHandshakeError: [class PeerInboundHandshakeError extends Error],
    PeerInboundDuplicateConnectionError: [class PeerInboundDuplicateConnectionError extends Error],
    RPCResponseError: [class RPCResponseError extends Error],
    InvalidRPCResponseError: [class InvalidRPCResponseError extends Error],
    RPCResponseAlreadySentError: [class RPCResponseAlreadySentError extends Error],
    ExistingPeerError: [class ExistingPeerError extends Error],
    InvalidNodeInfoError: [class InvalidNodeInfoError extends Error],
    InvalidPeerInfoError: [class InvalidPeerInfoError extends Error],
    InvalidPeerInfoListError: [class InvalidPeerInfoListError extends Error],
    RequestFailError: [class RequestFailError extends Error],
    SendFailError: [class SendFailError extends Error],
    InvalidRPCRequestError: [class InvalidRPCRequestError extends Error],
    InvalidProtocolMessageError: [class InvalidProtocolMessageError extends Error],
    InvalidPayloadError: [class InvalidPayloadError extends Error],
    InvalidDisconnectEventError: [class InvalidDisconnectEventError extends Error]
  },
  events: {
    EVENT_NEW_INBOUND_PEER: 'EVENT_NEW_INBOUND_PEER',
    EVENT_NEW_INBOUND_PEER_CONNECTION: 'EVENT_NEW_INBOUND_PEER_CONNECTION',
    EVENT_FAILED_TO_ADD_INBOUND_PEER: 'EVENT_FAILED_TO_ADD_INBOUND_PEER',
    EVENT_NETWORK_READY: 'EVENT_NETWORK_READY',
    EVENT_REMOVE_PEER: 'EVENT_REMOVE_PEER',
    EVENT_REQUEST_RECEIVED: 'EVENT_REQUEST_RECEIVED',
    EVENT_INVALID_REQUEST_RECEIVED: 'EVENT_INVALID_REQUEST_RECEIVED',
    EVENT_MESSAGE_RECEIVED: 'EVENT_MESSAGE_RECEIVED',
    EVENT_INVALID_MESSAGE_RECEIVED: 'EVENT_INVALID_MESSAGE_RECEIVED',
    EVENT_BAN_PEER: 'EVENT_BAN_PEER',
    EVENT_DISCOVERED_PEER: 'EVENT_DISCOVERED_PEER',
    EVENT_UPDATED_PEER_INFO: 'EVENT_UPDATED_PEER_INFO',
    EVENT_FAILED_PEER_INFO_UPDATE: 'EVENT_FAILED_PEER_INFO_UPDATE',
    EVENT_FAILED_TO_COLLECT_PEER_DETAILS_ON_CONNECT: 'EVENT_FAILED_TO_COLLECT_PEER_DETAILS_ON_CONNECT',
    EVENT_FAILED_TO_FETCH_PEERS: 'EVENT_FAILED_TO_FETCH_PEERS',
    EVENT_FAILED_TO_FETCH_PEER_INFO: 'EVENT_FAILED_TO_FETCH_PEER_INFO',
    EVENT_FAILED_TO_PUSH_NODE_INFO: 'EVENT_FAILED_TO_PUSH_NODE_INFO',
    EVENT_FAILED_TO_SEND_MESSAGE: 'EVENT_FAILED_TO_SEND_MESSAGE',
    REMOTE_SC_EVENT_RPC_REQUEST: 'rpc-request',
    REMOTE_SC_EVENT_MESSAGE: 'remote-message',
    REMOTE_EVENT_POST_NODE_INFO: 'postNodeInfo',
    REMOTE_EVENT_RPC_GET_NODE_INFO: 'getNodeInfo',
    REMOTE_EVENT_RPC_GET_PEERS_LIST: 'getPeers',
    REMOTE_EVENT_PING: 'ping',
    REMOTE_EVENT_PONG: 'pong',
    PROTOCOL_EVENTS_TO_RATE_LIMIT: Set { 'getNodeInfo', 'getPeers' },
    EVENT_CLOSE_INBOUND: 'EVENT_CLOSE_INBOUND',
    EVENT_INBOUND_SOCKET_ERROR: 'EVENT_INBOUND_SOCKET_ERROR',
    EVENT_CONNECT_OUTBOUND: 'EVENT_CONNECT_OUTBOUND',
    EVENT_CONNECT_ABORT_OUTBOUND: 'EVENT_CONNECT_ABORT_OUTBOUND',
    EVENT_CLOSE_OUTBOUND: 'EVENT_CLOSE_OUTBOUND',
    EVENT_OUTBOUND_SOCKET_ERROR: 'EVENT_OUTBOUND_SOCKET_ERROR'
  },
  P2P: [class P2P extends EventEmitter],
  p2pRequest: { P2PRequest: [class P2PRequest] },
  p2pTypes: {},
  p2pSchemas: {
    nodeInfoSchema: {
      '$id': '/nodeInfo',
      type: 'object',
      properties: [Object],
      required: [Array]
    },
    peerInfoSchema: {
      '$id': '/protocolPeerInfo',
      type: 'object',
      properties: [Object],
      required: [Array]
    },
    defaultRPCSchemas: { peerInfo: [Object], nodeInfo: [Object] },
    mergeCustomSchema: [Function]
  }
}
////

== Usage

To run a P2P node.

[source,typescript]
----
const { P2P } = require('@liskhq/lisk-p2p');

const p2p = new P2P({
	nodeInfo: {
		wsPort: 5001,
		networkId: '123xyz',
		protocolVersion: '1.1',
	},
});

const run = async () => {
	await p2p.start();
};

run()
	.then(() => console.log('P2P node has started!'))
	.catch(err => {
		console.log(`Error occurred while running p2p node: ${err}`);
		p2p.stop();
		process.exit(1);
	});
----

It will start a node that is available on `5001` websocket port.

[source,bash]
----
P2P node has started!
----

=== Actions

It provides a simple interface to send, request, broadcast information and many more functions to interact with the network.

- `p2p.start()`: start a P2P node after creating an instance.
- `p2p.stop()`: stop a P2P node.
- `p2p.config`: get the config of the node.
- `p2p.isActive`: check the status if the node is up and running.
- `p2p.nodeInfo`: check the node status and information.
- `applyNodeInfo(nodeInfo: P2PNodeInfo)`: broadcast updated `nodeInfo` to the network.
- `p2p.getConnectedPeers()`: get all the connected peers that are connected to your node in the network.
- `p2p.getDisconnectedPeers()`: get all the disconnected peers that are part of the network but not connected to you.
- `p2p.request(packet: P2PRequestPacket)`: request information from the network that will run the peer selection and finds an appropriate peer for you to request information.
- `p2p.send(message: P2PMessagePacket)`: sends information to 16 connected peers chosen by the peer selection function.
- `p2p.broadcast(message: P2PMessagePacket)`: broadcast information to all the connected peers.
- `p2p.requestFromPeer(packet: P2PRequestPacket,peerId: string)`: request from a specific peers in the network.
- `p2p.sendToPeer(message: P2PMessagePacket, peerId: string)`: sends information to a specific peer in the connected peers.

=== Events

Listen to various events on the network to observe the network activities more closely and take appropriate actions if needed.

[source,typescript]
----
// When a peer updates its information
p2p.on(EVENT_UPDATED_PEER_INFO, (peerInfo: P2PPeerInfo) => {
	// Take any action based peer update event
});
// When a peer sends any information
p2p.on(EVENT_MESSAGE_RECEIVED, (message: P2PMessagePacket) => {
	// Take any action based on message received
	const { event, data, peerId } = message;
});
// When a peer requests any information
p2p.on(EVENT_REQUEST_RECEIVED, async (request: P2PRequest) => {
	// Take any action based on request received and respond with `end(results)` with results or return an error by `error(new Error('Request was not processed successfully'))`
	const { procedure, data, peerId, end, error } = request;
});
----

==== Available events

- `EVENT_BAN_PEER`
- `EVENT_CLOSE_INBOUND`
- `EVENT_CLOSE_OUTBOUND`
- `EVENT_CONNECT_ABORT_OUTBOUND`
- `EVENT_CONNECT_OUTBOUND`
- `EVENT_DISCOVERED_PEER`
- `EVENT_FAILED_PEER_INFO_UPDATE`
- `EVENT_FAILED_TO_ADD_INBOUND_PEER`
- `EVENT_FAILED_TO_COLLECT_PEER_DETAILS_ON_CONNECT`
- `EVENT_FAILED_TO_FETCH_PEER_INFO`
- `EVENT_FAILED_TO_FETCH_PEERS`
- `EVENT_FAILED_TO_PUSH_NODE_INFO`
- `EVENT_FAILED_TO_SEND_MESSAGE`
- `EVENT_INBOUND_SOCKET_ERROR`
- `EVENT_MESSAGE_RECEIVED`
- `EVENT_NETWORK_READY`
- `EVENT_NEW_INBOUND_PEER`
- `EVENT_OUTBOUND_SOCKET_ERROR`
- `EVENT_REMOVE_PEER`
- `EVENT_REQUEST_RECEIVED`
- `EVENT_UPDATED_PEER_INFO`

=== Examples

Check [examples](examples/) folder for a few examples to demonstrate P2P library usage with some use cases.

- [echo](examples/echo): This example will run 3 nodes that will connect to each other and will say "`hi`" to each other that will be responded by peers when they receive it.
- [find-city-game](examples/find-city-game): It will run 3 nodes that will change their city randomly and also tell the other nodes in which city they are located, if they find out that they are in the same city then they stop changing their city. The app will stop when all 3 nodes are in the same city.
- [Connect to Lisk networks](examples/lisk-networks): Example to create a lightweight p2p client that can connect to lisk networks like [testnet](examples/lisk-networks/connect_to_testnet.ts), [mainnet](examples/lisk-networks/connect_to_mainnet.ts) and [devnet](examples/lisk-networks/connect_to_devnet.ts) and listen to various events and request data on connect event.
