= Utils
Mona Bärenfänger <mona@lightcurve.io>
:toc:

@liskhq/lisk-utils is a library providing various utilities for handling data structures, objects and jobs.

== Installation

The following command will install lisk-utils:

[source,bash]
----
npm install @liskhq/lisk-utils
----

== Update

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @liskhq/lisk-utils
----

== Method reference
=== bufferArrayContains
Checks if a Buffer array (`arr1`) contains another Buffer array (`arr2`).

==== Syntax
[source,js]
----
objects.bufferArrayContains(arr1,arr2)
----

==== Parameters
. `arr1`(Buffer[]): A buffer array.
. `arr2`(Buffer[]): Another buffer array.

==== Return value
`boolean`: `true` if `arr1` contains `arr2`, `false` otherwise.

=== bufferArrayContainsSome
Checks if a Buffer array (`arr1`) contains parts of another Buffer array (`arr2`).

==== Syntax
[source,js]
----
objects.bufferArrayContainsSome(arr1,arr2)
----

==== Parameters
. `arr1`(Buffer[]): A buffer array.
. `arr2`(Buffer[]): Another buffer array.

==== Return value
`boolean`: `true` if `arr1` contains some parts of `arr2`, `false` if otherwise.

=== bufferArrayEqual
Checks if two given Buffer arrays are identical.

==== Syntax
[source,js]
----
objects.bufferArrayEqual(arr1,arr2)
----

==== Parameters
. `arr1`(Buffer[]): A buffer array.
. `arr2`(Buffer[]): Another buffer array.

==== Return value
`boolean`: `true` if `arr1` is equal to `arr2`, `false` if otherwise.

=== bufferArrayIncludes
Checks if a Buffer array includes a certain value.

==== Syntax
[source,js]
----
objects.bufferArrayIncludes(arr,val)
----

==== Parameters
. `arr`(Buffer[]): A buffer array.
. `val`(Buffer): A buffer value.

==== Return value
`boolean`: `true` if `arr` includes `val`, `false` if otherwise.

=== bufferArrayOrderByLex
Checks if a given buffer array is sorted in lexicographical order.

==== Syntax
[source,js]
----
objects.bufferArrayOrderByLex(arr1)
----

==== Parameters
. `arr1`(Buffer[]): A buffer array.

==== Return value
`boolean`: `true` if `arr1` is sorted in lexicographical order, `false` if otherwise.

=== bufferArraySubtract
Subtracts one buffer array from another buffer array.

==== Syntax
[source,js]
----
objects.bufferArraySubtract(arr1,arr2)
----

==== Parameters
. `arr1`(Buffer[]): A buffer array.
. `arr2`(Buffer[]): Another buffer array.

==== Return value
`Buffer[]`: A new buffer array, which contains the values of `arr1` excluding the values of `arr2`, if present in `arr1`.

=== bufferArrayUniqueItems
Checks if all items of a buffer array are unique.

==== Syntax
[source,js]
----
objects.bufferArrayUniqueItems(arr1)
----

==== Parameters
. `arr1`(Buffer[]): A buffer array.

==== Return value
`boolean`: `true` if all items in the buffer array are unique, `false` if otherwise.

=== mergeDeep
Merges two objects into one object.

==== Syntax
[source,js]
----
objects.mergeDeep(dest, ...srcs)
----

==== Parameters
. `dest`(KVPair): A key-value pair.
. `srcs`(KVPair[]): A key-value pair array.

==== Return value
`KVPair`: The merged object.
