= Validator
:description: This section contains the installation and updates for the Lisk validator.
:toc:
:v_protocol: master
:url_lisk_protocol: {v_protocol}@lisk-protocol::lisk-protocol/index.adoc

The @liskhq/lisk-validator package is a wrapper of validation packages.
It includes custom validations utilities related to the xref:{url_lisk_protocol}[Lisk Protocol].

== Installation

[source,bash]
----
npm install @liskhq/lisk-validator
----

== Update

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @liskhq/lisk-validator
----

////
/*{
  validator: LiskValidator {
  _validator: Ajv {
    _opts: [Object],
      logger: [Object],
      _schemas: [Object],
      _refs: [Object],
      _fragments: {},
    _formats: [Object],
      _cache: [Cache],
      _loadingSchemas: {},
    _compilations: [],
      RULES: [Array],
      _getId: [Function: _get$IdOrId],
    _metaOpts: [Object],
      errors: null,
      _validateKeyword: [Function]
  }
},
  liskSchemaIdentifier: 'http://lisk.io/lisk-schema/schema#',
    isNumberString: [Function],
  isValidInteger: [Function],
  isHexString: [Function],
  isEncryptedPassphrase: [Function],
  isSemVer: [Function],
  isRangedSemVer: [Function],
  isLessThanRangedVersion: [Function: ltr],
  isGreaterThanRangedVersion: [Function: gtr],
  isProtocolString: [Function],
    isIPV4: [Function],
  isIPV6: [Function],
  isIP: [Function],
  isPort: [Function],
  isStringEndsWith: [Function],
  isVersionMatch: [Function: gte],
  isCsv: [Function],
    isString: [Function],
  isBoolean: [Function],
  isSInt32: [Function],
  isUInt32: [Function],
  isSInt64: [Function],
  isUInt64: [Function],
  isBytes: [Function],
  LiskValidationError: [class LiskValidationError extends Error],
  MAX_SINT32: 2147483647,
  MIN_SINT32: -2147483647,
  MAX_UINT32: 4294967295,
  MAX_UINT64: 18446744073709551615n,
  MAX_SINT64: 9223372036854775807n,
  MIN_SINT64: -9223372036854775808n
}*/
////
