= Validator
:description: This section contains the installation, updates and usage for the Lisk validator.
:toc:
:v_protocol: master
:url_lisk_protocol: protocol:index.adoc

The @liskhq/lisk-validator package is a wrapper of validation packages.
It includes custom validations utilities related to the xref:{url_lisk_protocol}[Lisk Protocol].

== Installation

[source,bash]
----
npm install @liskhq/lisk-validator
----

== Update

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @liskhq/lisk-validator
----

== Usage

[source,js]
----
const validator = require('@liskhq/lisk-validator');

console.log(validator.MAX_SINT64) //9223372036854775807n
----

== Constants

----
MAX_SINT32: 2147483647,
MIN_SINT32: -2147483647,
MAX_UINT32: 4294967295,
MAX_UINT64: 18446744073709551615n,
MAX_SINT64: 9223372036854775807n,
MIN_SINT64: -9223372036854775808n
----

== Validation methods

=== isBoolean
description

==== Syntax

[source,js]
----
isBoolean(data)
----

==== Parameters

`data`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is of type boolean, `false` otherwise.

=== isBytes
description

==== Syntax

[source,js]
----
isBytes(data)
----

==== Parameters

`data`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is of type Buffer, `false` otherwise.

=== isCsv
description

==== Syntax

[source,js]
----
isCsv(data)
----

==== Parameters

`data`(string): String to be checked.

==== Return value

`boolean`: description

=== isEncryptedPassphrase
description

==== Syntax

[source,js]
----
isEncryptedPassphrase(data)
----

==== Parameters

`data`(string): String to be checked.

==== Return value

`boolean`: `true` if the provided data is an encrypted passphrase, `false` otherwise.

=== isHexString
description

==== Syntax

[source,js]
----
isHexString(data)
----

==== Parameters

`data`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is a hex string, `false` otherwise.

=== isIP
description

==== Syntax

[source,js]
----
isIP(data)
----

==== Parameters

`data`(string): String to be checked.

==== Return value

`boolean`: `true` if the provided data is an IP, `false` otherwise.

=== isIPV4
description

==== Syntax

[source,js]
----
isIPV4(data)
----

==== Parameters

`data`(string): String to be checked.

==== Return value

`boolean`: `true` if the provided data is an IPv4, `false` otherwise.

=== isIPV6
description

==== Syntax

[source,js]
----
isIPV6(data)
----

==== Parameters

`data`(string): String to be checked.

==== Return value

`boolean`: `true` if the provided data is an IPv6, `false` otherwise.

=== isNumberString
description

==== Syntax

[source,js]
----
isNumberString(num)
----

==== Parameters

`num`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is a number string, `false` otherwise.

=== isPort
description

==== Syntax

[source,js]
----
isPort(port)
----

==== Parameters

`port`(string): String to be checked.

==== Return value

`boolean`: `true` if the provided data is a port, `false` otherwise.

=== isProtocolString
description

==== Syntax

[source,js]
----
isProtocolString(data)
----

==== Parameters

`data`(string): String to be checked.

==== Return value

`boolean`: `true` if the provided data is a protocol string, `false` otherwise.

=== isRangedSemVer
description

==== Syntax

[source,js]
----
isRangedSemVer(version)
----

==== Parameters

`version`(string): String to be checked.

==== Return value

`boolean`: `true` if the provided data is a valid SemVer version string, `false` otherwise.

=== isSInt32
description

==== Syntax

[source,js]
----
isSInt32(data)
----

==== Parameters

`data`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is of type sint32, `false` otherwise.

=== isSInt64
description

==== Syntax

[source,js]
----
isSInt64(data)
----

==== Parameters

`data`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is of type sint64, `false` otherwise.

=== isSemVer
description

==== Syntax

[source,js]
----
isSemVer(version)
----

==== Parameters

`version`(string): String to be checked.

==== Return value

`boolean`: `true` if the provided data is a SemVer version, `false` otherwise.

=== isString
description

==== Syntax

[source,js]
----
isString(data)
----

==== Parameters

`data`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is of type `string`, `false` otherwise.

=== isStringEndsWith
description

==== Syntax

[source,js]
----
isStringEndsWith(target,suffixes)
----

==== Parameters

. `target`(string): description
. `suffixes`(string[]): description

==== Return value

`boolean`: `true` if the provided data is of type `string`, `false` otherwise.

=== isUInt32
description

==== Syntax

[source,js]
----
isUInt32(data)
----

==== Parameters

`data`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is of type uint32, `false` otherwise.

=== isUInt64
description

==== Syntax

[source,js]
----
isUInt64(data)
----

==== Parameters

`data`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is of type uint64, `false` otherwise.

=== isValidInteger
description

==== Syntax

[source,js]
----
isValidInteger(num)
----

==== Parameters

`num`: Data to be checked.

==== Return value

`boolean`: `true` if the provided data is of type integer, `false` otherwise.

=== isLessThanRangedVersion
=== isGreaterThanRangedVersion
=== isVersionMatch
