= Blockchain applications
// Settings
:toc:
:idprefix:
:idseparator: -
:imagesdir: ../../assets/images
// External URLs
:url_lisk_apps: https://lisk.com/ecosystem
// Project URLs
:url_tutorials: tutorials/index.adoc
:url_tutorials_hello: tutorials/hello-world.adoc
:url_tutorials_nft: tutorials/nft.adoc
:url_tutorials_srs: tutorials/srs.adoc
:url_protocol: protocol:index.adoc

== What are blockchain applications?

A blockchain application is any kind of application which uses its' own blockchain as database layer.

More specifically, in the Lisk documentation, everytime we talk about blockchain applications, we refer to applications which are runnning on blockchains which are compatible with xref:{url_protocol}[].

.Examples of blockchain applications
****
Examples of blockchain applications can be found in the tutorials, like the xref:{url_tutorials_hello}[], the xref:{url_tutorials_nft}[] or the xref:{url_tutorials_srs}[] application.

Additionally, check out the apps list at {url_lisk_apps}
****

== Blockchain applications vs. dApps

As blockchain applications are also in a sense decentralized applications, you may wonder what is the difference between blockchain applications and dApps, or if there is any difference at all.

In short, the main difference between dApps and blockchain applications is, that blockchain applications each run on their own blockchain/sidechain, while dApps are sharing the blockchain network with other dApps.

For this reason, dApps are often constructed as smart contracts for example on the Ethereum blockchain.
The developmeent of blockchain applications is quite different, as it is much more similar to building a normal web application.
A lot of functionalities of smart contracts can easily be reimplemented in blockchain applications, though it is of course also possible to develop a blockchain application which supports smart contracts if this is desired.

The Lisk documentation is referring to applications built with the Lisk SDK as blockchain applications and not dApps to clarify the difference, that applications are not sharing a common blockchain, but instead are each running on their own chain.
As an effect, blockchain applications have the following advantages:

* No high transaction fees, as high traffic a blockchain application has no effect on other blockchain applications.
* The blockchain can be designed with the optimal characteristics for the specific use case.
* The blockchain is much more scalable, as it only handles the data from one blockchain application.
Therefore it is growing much slower in size, and doesn't suffer so much from possible bottlenecks in the network, which can happen during times of high workload on a lot of different dApps.


== Architecture of blockchain applications



//TODO: Talk about interoperability between blockchain apps
