= Key concepts of the Lisk blockchain
:toc: preamble

== The three domains of a blockchain

//TODO: Include image of the 3 domains of a blockchain

=== Network

=== Consensus

=== State machine

The state tree is the sparse Merkle tree built on top of the state store.
Organizing the state of a blockchain in a Merkle tree allows to cryptographically authenticate the whole state with a single hash, the state root.
The state root property is calculated at the end of the block processing as the Merkle root of the state tree and included in the block header.
Information from the block header is then used to create a certificate and signed by the chain validators.

=== The blockchain state as Sparse Merkel Tree

////
TODO: Explain the structure of the state is structured as a Sparse Merkel Tree
TODO: Explain what is a Sparse Merkel Tree, and its benefits for blockchain
TODO: Include image of a Sparse Merkel Tree of a blockchain app
////

== Blocks

//TODO: Include image of the anatomy of a block

=== Block generation

=== Block processing

=== Block schema

=== Block validation

=== Block header

=== Block transactions

=== Block assets

=== Block Signature Calculation

== Transactions

//TODO: Include image of the anatomy of a transaction

=== Transaction schema

=== Transaction header