= Lisk blockchain networks
:url_observer: https://lisk.observer/
:url_observer_testnet: https://testnet.lisk.observer/
:url_liskscan: https://liskscan.com/
:url_liskscan_testnet: https://testnet.liskscan.com/
:url_faucet_testnet: https://testnet-faucet.lisk.com/
:url_lisk_desktop: https://lisk.com/wallet

Lisk maintains the following two accessible public networks which are entirely independent of each other.

.Lisk network overview
[cols="1,1,1",options="header",stripes="hover"]
|===
|
|Mainnet
|Testnet

|Description
|The Mainnet is where the true Lisk economy exists.
Within this network the Lisk users can transfer LSK tokens from one account to another, register accounts as validators, and vote for other validators.
|The Testnet is an independent replica of the Lisk Mainnet, whose main function is to test the upgrades first before they are run on the Lisk Mainnet.

Subsequently, this is where new/updated versions and fixes of the Lisk Core are tested.

For users, the Testnet provides the possibility to perform their own tests of their Lisk applications in the Testnet, or to test their validator node setup, without spending any real LSK, or risking punishment on the mainnet.

|Validator selection algorithm
|<<proof-of-stake-configurations-for-the-lisk-mainnet,PoS(Mainnet)>>
|<<proof-of-stake-configurations-for-the-lisk-testnet,PoS(Testnet)>>

|Block time
|10 seconds
|10 seconds

|maxTransactionsSize
| 15 kB
| 15 kB

|Chain ID
|00000000
|01000000

|Token ID
|0000000000000000
|0100000000000000

|P2P Port
|8001
|7001

|Keeps blockchain events
|For 300 blocks
|For 300 blocks

|Explorer
a|
* {url_observer}[^]
* {url_liskscan}[^]

a|
* {url_observer_testnet}[^]
* {url_liskscan_testnet}[^]

|Lisk service API base URLs
|https://service.lisk.com/api/v3/
|https://testnet-service.lisk.com/api/v3/

|Faucet
| No faucet available.

|===


== Mainnet

=== Proof of Stake configurations for the Lisk Mainnet

=== Registered modules
=== Registered plugins

== Testnet

=== Proof of Stake configurations for the Lisk Testnet

=== Faucet

Get free Testnet LSK from the {url_faucet_testnet}[Testnet faucet^] to start using the Testnet for your own purposes.

.Testnet LSK are "play money"
IMPORTANT: Testnet LSK have no monetary value themselves, their only purpose is to test things in the Lisk testnet, without the need of spending "real" LSK tokens.
Testnet LSK cannot be swapped to Mainnet LSK or any other currency.

=== Using Lisk Desktop for a Testnet account
To connect to the Testnet via {url_lisk_desktop}[Lisk Desktop^], simply enable the "Network Switcher" in the settings and then use it to switch the network to `Testnet`.

=== Registered modules
=== Registered plugins