== Lisk Core Docker Setup

* link:#pre-install[Pre-Install]
[arabic]
. link:#mac-os-x[Mac OS X]
. link:#windows[Windows]
. link:#linux[Linux]
. link:#open-necessary-ports[Open necessary ports]
. link:#create-a-new-user[Create a new user]
* link:#installation[Installation]
[arabic]
. link:#get-configuration-and-makefile[Get configuration and Makefile]
. link:#set-environment-variables[Set environment variables]
. link:#coldstart-application[Coldstart application]

=== Pre-install

This document will detail how to prepare a system to run Lisk Core as a
Docker based container. In order to run Lisk in Docker a user must first
install the Docker Engine. Additionally it is recommended to install
Docker Compose for convenience.

Determine if your platform can run Docker.

==== Supported Platforms

Please refer to https://docs.docker.com/engine/installation/#desktop

==== Mac OS X

Please refer to https://docs.docker.com/docker-for-mac/install/. Please
note that Docker for Mac already includes Docker Compose. Install
`+make+` using https://developer.apple.com/xcode/features/[XCode]

==== Windows

Please refer to https://docs.docker.com/docker-for-windows/install/
Please note that Docker for Windows includes Docker Compose.

==== Linux

Please refer to https://docs.docker.com/engine/installation/#server

To install Docker Compose, please refer to:
https://docs.docker.com/compose/install/

*Important*: Configure Docker, so it can be run without `+sudo+` rights:
https://docs.docker.com/install/linux/linux-postinstall/

Install `+make+` using your package manager. For example, use
`+apt-get+` if running Ubuntu:

[source,bash]
----
sudo apt-get install make
----

==== Open necessary ports

In order to connect to the desired network with Lisk Core , please
ensure that the corresponding ports are open:

[cols=",,",options="header",]
|===
|Network |httpPort(HTTP) |wsPort(TCP)
|Mainnet |8000 |8001
|Testnet |7000 |7001
|Betanet |5000 |5001
|Devnet |4000 |5000
|===

These are the default ports for connecting with the network, these can
be altered later in `+.env+`.

==== Create a new user

In order to run and manage a Lisk Core node in the future, please create
a separate `lisk' user like so:

===== Ubuntu

The `+lisk+` user itself *does not need* any `+sudo+` rights to run Lisk
Core. It is sufficient to create a group `+docker+` and add the newly
created user to that group, in order to enable the user to use Docker
(see: https://docs.docker.com/install/linux/linux-postinstall/).

[source,bash]
----
sudo adduser lisk              # create a new user
sudo groupadd docker           # create docker group
sudo usermod -aG docker lisk   # add user to docker group
----

=== Installation

==== Get configuration and Makefile

Clone the https://github.com/LiskHQ/lisk[Lisk Repository].

[source,bash]
----
su - lisk                                    # switch to lisk user
git clone https://github.com/LiskHQ/lisk.git # clone the repository
cd lisk/docker                               # navigate into docker directory
----

It contains a directory `+docker+` with the following files: -
`+.env.development+` - `+.env.mainnet+` - `+.env.testnet+` -
`+docker-compose.make.yml+`: used by `+make coldstart+`. -
`+docker-compose.override.yml+`: use this file to overwrite `+LISK_+`
variables (empty by default). - `+docker-compose.redis.yml+`: enable
cache (optional). - `+docker-compose.yml+` - `+Makefile+`

The `+.env+`-files are templates with network specific environment
variables.

==== Set environment variables

In order to connect to the Lisk network, the environment variables need
to be set accordingly.

Before setting the variables, you may want to edit them in the
respective `+.env.{network}+` file.

It is recommended to change the password for the database, which is
stored in `+ENV_LISK_DB_PASSWORD+`.

To install a specific version of Lisk Core, set the `+ENV_LISK_VERSION+`
to the respective version.

After adjusting them, copy the environment variables to a file called
`+.env+`:

[source,bash]
----
cp .env.{network} .env
----

Where `+{network}+` stands for the Lisk network you want to connect to.

==== Coldstart application

===== Option 1: Makefile

We recommend to use the Makefile:

[source,bash]
----
make  # will run `docker-compose up` for you
----

Makefile provides a convenient way to
link:../../user-guide/administration/docker/admin-docker.md#sync-from-snapshot[sync
your node from snapshot]:

[source,bash]
----
make coldstart  # will download and restore a blockchain snapshot for you
----

===== Option 2: docker-compose

[source,bash]
----
docker-compose up -d # initialize Lisk Core
docker-compose ps    # see status of Lisk Core
docker-compose logs  # see logs
----

As next step, check out
link:../../user-guide/administration/docker/admin-docker.md[Docker
Administration] to learn how to manage your Node.
