= Delegates
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references regarding the Delegate endpoints of the API client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
:page-aliases: lisk-elements/packages/api-client/delegates.adoc, reference/lisk-elements/packages/api-client/delegates.adoc
:toc:
:v_core: 3.0.0
:url_lisk_core_api: {v_core}@lisk-core::reference/api.adoc

This is a resource for interacting with the `delegates` endpoint provided by the Lisk public API.
Each of the following methods can be accessed via the `delegates` property of an `APIClient` instance.

== get

This searches for a specified delegate in the system.

=== Syntax

[source,js]
----
get([options])
----

=== Parameters

`options`: Please see the options in the following link: xref:{url_lisk_core_api}[Core API documentation^].

=== Return value

`Promise`: Resolves to an API response object.

=== Examples

[source,js]
----
client.delegates.get({ username: 'oliver' })
    .then(res => {
        console.log(res.data);
    })
----

== getStandby

This calls `get` with the default parameters in order to retrieve the delegates from rank 102 onwards.

=== Syntax

[source,js]
----
getStandby([options])
----

=== Parameters

`options`: Please see the options in the following link: xref:{url_lisk_core_api}[Core API documentation^].

=== Return value

`Promise`: Resolves to an API response object.

=== Examples

[source,js]
----
client.delegates.getStandby()
    .then(res => {
        console.log(res.data);
    })
----

== getForgers

This returns a list of the next forgers in this delegate round.

=== Syntax

[source,js]
----
getForgers([options])
----

=== Parameters

`options`: Please see the options in the following link: xref:{url_lisk_core_api}[Core API documentation^].

=== Return value

`Promise`: Resolves to an API response object.

=== Examples

[source,js]
----
client.delegates.getForgers()
    .then(res => {
        console.log(res.data);
    })
----

== getForgingStatistics

By viewing an existing delegate address and the desired unix timestamps, it is possible to acquire their forging statistics within the specified timespan.
If no timestamps are provided, it will use the timestamps from the Lisk epoch to the current date.

=== Syntax

[source,js]
----
getForgingStatistics(address, [options])
----

=== Parameters

`address`: Address of the delegate to query.

`options`: Please see the options in the following link: xref:{url_lisk_core_api}[Core API documentation^].

=== Return value

`Promise`: Resolves to an API response object.

=== Examples

[source,js]
----
client.delegates.getForgingStatistics('15434119221255134066L')
    .then(res => {
        console.log(res.data);
    })
----
