=== Ports

[NOTE]
====
Lisk Core installed by lisk Commander currently uses the default ports, incremented by +2.
If you want to change it back to the <<_open-the-necessary-ports, default ports>> ports, just change the xref:configuration.adoc[config] of your Lisk Core, once it’s installed.
====

[IMPORTANT]
====
*Mandatory:* Always open the *WebSocket* port of your desired network, to enable communication with other peer nodes.

*Optional:* Open the corresponding HTTP port for your network, to make your node’s https://lisk.io/documentation/lisk-core/api[API] reachable.
For more info, see the diagram on the xref:getting-started/interact-with-network.adoc[Interact with network] page.
====

To connect to the desired network with Lisk Core, please ensure that the corresponding ports are open:

[options="header",]
|===
|Network |HTTP |WebSocket
|Mainnet |8002 |8003
|Testnet |7002 |7003
|Devnet |4002 |5002
|===

These are the default ports for connecting with the network.
They can be xref:configuration.adoc[altered] later in the xref:configuration.adoc#_structure[`config.json`] file.
