== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, please proceed to the <<_installation, Installation>> chapter.

=== Determine if your platform can run Lisk Core

==== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64

=== Ports

[IMPORTANT]
====
*Mandatory:* Always open the *WebSocket* port of your desired network, to enable communication with other peer nodes.
*Optional:* Open the corresponding HTTP port for your network, to make your node’s https://lisk.io/documentation/lisk-core/api[API] reachable.
For more info, see the diagram on the xref:1.2.0@lisk-start::interact-with-network.adoc[Interact with network] page.
====

To connect to the desired network with Lisk Core, please ensure that the corresponding ports are open:

[options="header",]
|===
|Network |HTTP |WebSocket
|Mainnet |8002 |8003
|Testnet |7002 |7003
|Devnet |4002 |5002
|===

These are the default ports for connecting with the network.
They can be xref:configuration.adoc[altered] later in the xref:configuration.adoc#_structure[`config.json`] file.
