=== Ports

[NOTE]
====
Lisk Core installed by the Lisk Commander currently uses the default ports, incremented by +2. In order to change it back to the <<_open-the-necessary-ports, default ports>> ports, just change the xref:configuration.adoc[config] of your Lisk Core after the installation has been completed.
====

[IMPORTANT]
====
*Mandatory:* Always open the *WebSocket* port of your desired network, to enable communication with other peer nodes.

*Optional:* Open the corresponding HTTP port for your network, to make your node’s xref:reference/api.adoc[API] reachable.
For more information, see the diagram on the xref:interact-with-network.adoc[Interact with network] page.
====

To connect to the desired network with Lisk Core, please ensure that the corresponding ports listed below are open:

[options="header",]
|===
|Network |HTTP |WebSocket
|Mainnet |8002 |8003
|Testnet |7002 |7003
|Devnet |4002 |5002
|===

These are the default ports for connecting with the network.
They can be altered later in the xref:management/configuration.adoc[`config.json`] file.
