[[postgresql]]
=== PostgreSQL

To install PostgreSQL please follow the instructions described below.

TIP: It is recommended to use PostgreSQL with Docker for a quick and straight forward setup of PostgreSQL, and also PostgreSQL system-wide for production environments.

[tabs]
====
PostgreSQL system wide::
+
--
NOTE: Please see the instructions for the MacOS listed <<postgres_macos,below>>.

*Ubuntu*

Firstly, install PostgreSQL on your machine by executing the following commands:

[source,bash]
----
sudo apt-get purge -y postgres* <1>
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
sudo apt install wget ca-certificates
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt update
sudo apt install postgresql-10
----

<1> Remove all previously installed postgres versions.

After the installation is completed, it will be possible to see the PostgreSQL database cluster by running the following command:

[source,bash]
----
pg_lsclusters
----

Drop the existing database cluster as shown below, and replace it with a cluster with the locale `en_US.UTF-8`:

[source,bash]
----
sudo pg_dropcluster --stop 10 main
sudo pg_createcluster --locale en_US.UTF-8 --start 10 main
----

Create a new database user called `lisk` and grant it access rights to create databases.
Then create the database with the `lisk` user as the owner.
Finally, define the password for the `lisk` user by executing the following commands below:

[NOTE]
=====
If the following error occurs: `could not change directory to "/root": Permission denied` this can be ignored.
The command will be executed regardless.
=====

[source,bash]
----
sudo -u postgres -i createuser --createdb lisk
sudo -u postgres -i createdb lisk_dev --owner lisk
sudo -u postgres psql -d lisk_dev -c "alter user lisk with password 'password';"
----

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:guides/configuration.adoc[Lisk SDK configuration] later.

[[postgres_macos]]
*MacOS*

To install the PostgreSQL version 10 execute the following command below:

[source,bash]
----
brew install postgresql@10
----

The next step is to execute the following commands in order to have the PostgreSQL commands (e.g. `psql`), in your PATH:

[source,bash]
----
echo 'export PATH="/usr/local/opt/postgresql@10/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile
----

Start the PostgreSQL, and create the `lisk` user and the database by executing the following commands below:

[source,bash]
----
pg_ctl -D /usr/local/var/postgresql@10 start
createuser lisk
createdb --owner=lisk lisk_dev
psql --dbname=lisk_dev --command="ALTER USER lisk WITH PASSWORD 'password';"
----

IMPORTANT: Please change the `password` to a secure password of your choice.
In addition, do not forget to update this password in the xref:guides/configuration.adoc[Lisk SDK configuration] later.
--
PostgreSQL with Docker::
+
--
Running PostgreSQL inside a Docker container will set up the correct version of PostgreSQL and containerize it away from any existing versions that may be present locally on your machine.
Please choose this set up if you are unfamiliar with PostgreSQL, or if problematic issues with a previously installed version of PostgreSQL have occured.

*Supported platforms:* For further information please refer to the following link: https://docs.docker.com/engine/installation/#desktop[Docker installation^]

*Install Docker*

To install Docker please refer to the applicable link listed below for your operating system:

*Mac OS X*

Please refer to https://docs.docker.com/docker-for-mac/install/[Mac installation^].
Please note that Docker for Mac already includes Docker Compose.
Install `make` using https://developer.apple.com/xcode/features/[XCode^]

*Linux*

Please refer to https://docs.docker.com/engine/installation/#server[Linux installation^]

*Start the Docker container*.

IMPORTANT: If you have other versions of PostgreSQL installed on your machine, please ensure to stop them before starting the docker container.

[source,bash]
----
docker run --name lisk_db -p 5432:5432 -e POSTGRES_USER=lisk -e POSTGRES_PASSWORD=password -e POSTGRES_DB=lisk_dev -d postgres:10
----

This will install PostgreSQL version 10 (`postgres:10`) in a container with name `lisk_db` and binds the port `5432` of the container with the same port of the machine.
As environment variables we expose `POSTGRES_USER=lisk` to create the lisk user and `POSTGRES_PASSWORD=password` to set the password for the lisk user.
Finally the environment variable `POSTGRES_DB` creates the database `lisk_dev` with the `lisk` user as owner.

The above should be enough to set up the database ready to use with the Lisk SDK.
To manage the Docker container, use the following commands listed below:

[source,bash]
----
docker stop lisk_db <1>
docker start lisk_db <2>
docker restart lisk_db <3>
docker rm lisk_db <4>
----

<1> Stop the container.
<2> Start the container.
<3> Restart the container.
<4> Remove the container.

In order to access PostgreSQL inside the container via the CLI, please execute the following command:

[source,bash]
----
docker exec --tty --interactive lisk_db psql -h localhost -U lisk -d postgres
----
--
====
