=== Node.js

https://nodejs.org/[Node.js^] serves as the underlying engine for code execution.
There are several different ways and version managers to install Node.js on your system.
Please ensure that the latest version is used.
It is recommended to use one of the following two listed below:

[IMPORTANT]
====
Change to the `lisk` user to install Node.js by executing the following command:

[source,bash]
----
sudo -u lisk -i
----
====

[tabs]
====
Option A - Node version manager::
+
--
It is recommended to use a Node version manager, such as https://github.com/creationix/nvm[NVM^].
NVM is a bash script which enables the management of multiple active Node.js versions.

. To install nvm, please follow these https://github.com/creationix/nvm#installing-and-updating[instructions^].
. Install the **latest LTS** version of Node.js:

[source,bash]
----
nvm install 12.15.0
----
--
Option B - Node.js package::
+
--
Alternatively, instead of using the NVM or other package managers, the node package can be installed globally by executing the following commands listed below:

*Ubuntu*

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
----

*MacOS*

Please install node@12.15.0 with brew. Now in order to complete the installation, execute the following command below:

[source,bash]
----
brew install node@12.15.0
echo 'export PATH="/usr/local/opt/node@10/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
----
--
====
