=== Node.js

https://nodejs.org/[Node.js] serves as the underlying engine for code execution.
There are several different ways and version managers to install Node.JS on your system.
It is recommended to use one of the following two listed below:

[IMPORTANT]
====
Change to the `lisk` to install Node.js:

[source,bash]
----
sudo -u lisk -i
----
====

[tabs]
====
Option A - Node Version Manager::
+
--
It is recommended to use a Node version manager, such as https://github.com/creationix/nvm[NVM].
NVM is a bash script which enables the management of multiple active Node.js versions.

. To install nvm, please follow these https://github.com/creationix/nvm#install--update-script[instructions].
. To install the correct version of Node.js using NVM, execute the command listed below:

[source,bash]
----
nvm install 10.15.3
----
--
Option B - Node.js package::
+
--
Alternatively, instead of using the NVM or other package managers, the Node package can be installed globally by executing the following commands listed below:

*Ubuntu*

[source,bash]
----
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
----

*MacOS*

[source,bash]
----
brew install node@10.15.3
----
--
====
