= Lisk Core with Lisk Commander Administration
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Core Commander Administration describes all relevant commands to manage Lisk Core through the Command-line with Lisk Commander.
:toc:

This section covers how to work with a Binary installation of Lisk Core.
Further information can be found by referring to the following commands reference list.

== Basic Commands

The available basic commands which can be used to manage your Lisk node are displayed here below:

=== Install

NOTE: For more information, please see the xref:setup/commander.adoc[Setup page of Lisk Core with Lisk Commander].

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:install lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:install --network=testnet lisk-testnet
----
--
====

=== Uninstall

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:uninstall lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:uninstall lisk-testnet
----
--
====

=== Status

Check the status of the Lisk Core Node.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:status lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:status lisk-testnet
----
--
====

=== Upgrade

NOTE: For more information, please see the xref:upgrade/commander.adoc[Upgrade page of Lisk Core with Lisk Commander].

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:upgrade lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:upgrade lisk-testnet
----
--
====

=== Start

Start Lisk Core and PostgreSQL.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:start lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:start lisk-testnet
----
--
====

=== Stop

Stop Lisk Core and PostgreSQL.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:stop lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:stop lisk-testnet
----
--
====

=== Restart

Reload Lisk Core and pick up changes to config.json.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:restart lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:restart lisk-testnet
----
--
====

=== Logs

Monitor,(tail) the log file of Lisk.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:logs lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:logs lisk-testnet
----
--
====

=== Help

To access the Help menu please execute the following command listed below:

[source,bash]
----
lisk core
----

== Advanced Commands

The advanced commands which can be used to manage your Lisk node, can be seen in the commands reference list below:

=== Start database only

This command is used to start database instances apart from the Lisk process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:start:database lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:start:database lisk-testnet
----
--
====

=== Stop database only

This command is used to stop all database instances apart from the Lisk process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:stop:database lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:stop:database lisk-testnet
----
--
====

=== Start cache only

This command is used to start caching apart from the Lisk process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:start:cache lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:start:cache lisk-testnet
----
--
====

=== Stop cache only

This command is used to stop all caching apart from the Lisk process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
lisk core:stop:cache lisk-mainnet
----
--
Testnet::
+
--
[source,bash]
----
lisk core:stop:cache lisk-testnet
----
--
====
