= API specification
:toc:
:v_core: master

:url_core_api: {v_core@}lisk-core::reference/api.adoc
:url_core_intro: {v_core@}lisk-core::index.adoc

TIP: Check the xref:{url_core_api}[Lisk Core API] to make live API requests to the Lisk xref:{url_core_intro}[public networks].

[[_overview]]
== Access Restrictions

The API endpoints are by default restricted to a whitelist of IPs that can be found in `config.json` in the section `api.access.whitelist`.
If you want your API to be accessable by the public, you can do this by changing `api.access.public` to `true`.
This will allow anyone to make requests to your Lisk Core node.
However some endpoints stay private, that means only a list of whitelisted IPs can successfully make API calls to that particular endpoint;
This includes all forging related API calls.
By default, only the nodes' local IP is included in the whitelist, it is possible to change the setting in `config.json` in the section `forging.access.whitelist`.
For more details, see the descriptions at the respective endpoint.

== Requests

Chained filter parameters are logically connected with `AND`.
`HTTP` is the supported URL schema by default.
To enable `HTTPS`, please adjust the the `ssl` section in `config.json`.

== Responses

The general response format is JSON (`application/json`).
The responses for each API request have a common basic structure:

[source,javascript]
----
{
    "data": {}, //Contains the requested data
    "meta": {}, //Contains additional metadata, e.g. the values of `limit` and `offset`
    "links": {} //Will contain links to connected API calls from here, e.g. pagination links
}
----

== Date Formats

Most of the timestamp parameters are in the Lisk Timestamp format, which is similar to the Unix Timestamp format.
The *Lisk Timestamp* is the number of seconds that have elapsed since the Lisk epoch time (2016-05-24T17:00:00.000Z), not counting leap seconds.
The *Lisk Epoch Time* is returned in the https://en.wikipedia.org/wiki/ISO_8601[ISO8601] format, combined date and time: `YYYY-MM-DDThh:mm:ssZ`.
For details, see the descriptions and examples at the respective endpoint.

== Pagination

One can paginate nicely through the results by providing `limit` and `offset` parameters to the requests.
`limit` and `offset` can be found in the `meta`-object of the response of an API request.
If no limit and offset are provided, they are set to 10 and 0 by default, what will display the first 10 results.

== List of Endpoints

All possible API endpoints for Lisk Core are listed below.
Click on an endpoint to show descriptions, details and examples.


=== Version information
[%hardbreaks]
__Version__ : 1.0.32


=== Contact information
[%hardbreaks]
__Contact Email__ : admin@lisk.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0
__Terms of service__ : null


=== URI scheme
[%hardbreaks]
__BasePath__ : /api
__Schemes__ : HTTP, HTTPS


=== Tags

* Accounts : Account related API calls
* Blocks : Block related API calls
* Dapps : Dapps related API calls
* Delegates : Delegates related API calls
* Node : Node related API calls
* Peers : Peers related API Calls
* Signatures : Signatures related API calls
* Transactions : Transactions related API calls
* Voters : Votes related API calls
* Votes : Votes related API calls


[[_paths]]
== Paths

[[_getaccounts]]
=== Requests account data
....
GET /accounts
....


==== Description
Search for matching accounts in the system.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**address** +
__optional__|Address of an account|string (address)|
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**publicKey** +
__optional__|Public key to query|string (publicKey)|
|**Query**|**secondPublicKey** +
__optional__|Second public key to query|string (publicKey)|
|**Query**|**sort** +
__optional__|Fields to sort results by|enum (balance:asc, balance:desc)|`"balance:asc"`
|**Query**|**username** +
__optional__|Delegate username to query|string (username)|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|List of accounts|<<_accountsresponse,AccountsResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Accounts


[[_getmultisignaturegroups]]
=== Requests multisignature groups data
....
GET /accounts/{address}/multisignature_groups
....


==== Description
Searches for the specified account in the system and responds with a list of the multisignature groups that this account is member of.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**address** +
__required__|Lisk address of an account|string (address)
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|List of multisignature accounts|<<_multisignaturegroupsresponse,MultisignatureGroupsResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**404**|Multisignature account not found|<<_notfounderror,NotFoundError>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Accounts


[[_getmultisignaturememberships]]
=== Requests multisignature membership data
....
GET /accounts/{address}/multisignature_memberships
....


==== Description
Searches for the specified multisignature group and responds with a list of all members of this particular multisignature group.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**address** +
__required__|Lisk address of a multisignature account|string (address)
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|List of multisignature accounts|<<_multisignaturegroupsresponse,MultisignatureGroupsResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Accounts


[[_getblocks]]
=== Requests blocks data
....
GET /blocks
....


==== Description
Search for a specified block in the system.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**blockId** +
__optional__|Block id to query|string (id)|
|**Query**|**fromTimestamp** +
__optional__|Starting unix timestamp|integer|
|**Query**|**generatorPublicKey** +
__optional__|Public key of the forger of the block|string (publicKey)|
|**Query**|**height** +
__optional__|Current height of the network|integer (int32)|
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**sort** +
__optional__|Fields to sort results by|enum (height:asc, height:desc, totalAmount:asc, totalAmount:desc, totalFee:asc, totalFee:desc, timestamp:asc, timestamp:desc)|`"height:desc"`
|**Query**|**toTimestamp** +
__optional__|Ending unix timestamp|integer|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Search results matching criteria|<<_blocksresponse,BlocksResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Blocks


[[_getdapps]]
=== Requests dapps data
....
GET /dapps
....


==== Description
Search for a specified dapp in the system.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**name** +
__optional__|Name to query - Fuzzy search|string|
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**sort** +
__optional__|Fields to sort results by|enum (name:asc, name:desc)|`"name:asc"`
|**Query**|**transactionId** +
__optional__|Dapp registration transaction ID|string (id)|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Search results matching criteria|<<_dappsresponse,DappsResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Dapps


[[_getdelegates]]
=== Requests delegates data
....
GET /delegates
....


==== Description
Search for a specified delegate in the system.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**address** +
__optional__|Address of an account|string (address)|
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**publicKey** +
__optional__|Public key to query|string (publicKey)|
|**Query**|**search** +
__optional__|Fuzzy delegate username to query|string|
|**Query**|**secondPublicKey** +
__optional__|Second public key to query|string (publicKey)|
|**Query**|**sort** +
__optional__|Fields to sort results by|enum (username:asc, username:desc, productivity:asc, productivity:desc, missedBlocks:asc, missedBlocks:desc, producedBlocks:asc, producedBlocks:desc, voteWeight:asc, voteWeight:desc)|`"voteWeight:desc"`
|**Query**|**username** +
__optional__|Delegate username to query|string (username)|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Search results matching criteria|<<_delegatesresponse,DelegatesResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Delegates


[[_getforgers]]
=== Requests next forgers data
....
GET /delegates/forgers
....


==== Description
Returns a list of the next forgers in this delegate round.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Search results matching criteria|<<_forgersresponse,ForgersResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Delegates


[[_getforgingstatistics]]
=== Requests forging stats by delegate
....
GET /delegates/{address}/forging_statistics
....


==== Description
By passing an existing delegate address and the desired unix timestamps, you can get its forging statistics within the specified timespan.
If no timestamps are provided, it will use the timestamps from Lisk epoch to current date.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**address** +
__required__|Lisk address of a delegate|string (address)
|**Query**|**fromTimestamp** +
__optional__|Starting unix timestamp|integer
|**Query**|**toTimestamp** +
__optional__|Ending unix timestamp|integer
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Results matching specified delegate address|<<_forgingstatsresponse,ForgingStatsResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Delegates


[[_getconstants]]
=== Requests constants data
....
GET /node/constants
....


==== Description
Returns all current constants data on the system, e.g. Lisk epoch time and version.


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Node constants response|<<_nodeconstantsresponse,NodeConstantsResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Node


[[_getstatus]]
=== Requests status data
....
GET /node/status
....


==== Description
Returns all current status data of the node, e.g. height.


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Node status response|<<_nodestatusresponse,NodeStatusResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Node


[[_getforgingstatus]]
=== Requests forging status of a delegate
....
GET /node/status/forging
....


==== Description
_Attention! This is a *private endpoint only authorized to whitelisted IPs.*
To edit the whitelist, please edit the `forging.access.whitelist` section in `config.json`_<br>
Responds with the forging status of a delegate on a node.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Query**|**forging** +
__optional__|Forging status to filter|boolean
|**Query**|**publicKey** +
__optional__|Public key to query|string (publicKey)
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Search results matching criteria|<<_forgingstatusresponse,ForgingStatusResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**403**|Access denied|<<_accessdeniederror,AccessDeniedError>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Node


[[_updateforgingstatus]]
=== Toggles the forging status of a delegate
....
PUT /node/status/forging
....


==== Description
_Attention! This is a *private endpoint only authorized to whitelisted IPs.*
To edit the whitelist, please edit the `forging.access.whitelist` section in `config.json`_<br>
Upon passing the correct password and publicKey, forging will be enabled or disabled for the delegate of this particular node.
The password can be generated locally by encrypting your passphrase, either by using Lisk Commander or with Lisk Elements.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**data** +
__required__|Password for decrypting passphrase of delegate with corresponding public key|<<_updateforgingstatus_data,data>>
|===

[[_updateforgingstatus_data]]
**data**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**forging** +
__required__|Forging status of the delegate +
**Example** : `true`|boolean
|**password** +
__required__|Password for decrypting passphrase of delegate. +
**Minimum length** : `5` +
**Example** : `"happy tree friends"`|string
|**publicKey** +
__required__|Public key of the delegate. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Delegate forging toggled on or off|<<_forgingstatusresponse,ForgingStatusResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**403**|Access denied|<<_accessdeniederror,AccessDeniedError>>
|**404**|Provided public key not found|<<_notfounderror,NotFoundError>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Consumes

* `application/json`


==== Produces

* `application/json`


==== Tags

* Node


[[_getpooledtransactions]]
=== Requests unprocessed transactions data
....
GET /node/transactions/{state}
....


==== Description
By specifying the state of the transactions, you get a list of unprocessed transactions matching this state.
Search for specific transactions by providing the appropriate parameters.
If you post a batch of transactions, they will appear in the unprocessed list after a small delay, depending on server load.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Path**|**state** +
__required__|State of transactions to query|enum (pending, ready, received, validated, verified)|`"verified"`
|**Query**|**id** +
__optional__|Transaction id to query|string (id)|
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**recipientId** +
__optional__|Recipient lisk address|string (address)|
|**Query**|**senderId** +
__optional__|Sender lisk address|string (address)|
|**Query**|**senderPublicKey** +
__optional__|Sender public key|string (publicKey)|
|**Query**|**sort** +
__optional__|Fields to sort results by|enum (amount:asc, amount:desc, fee:asc, fee:desc, type:asc, type:desc, timestamp:asc, timestamp:desc)|`"amount:desc"`
|**Query**|**type** +
__optional__|Transaction type (0-*)|integer|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Transactions list|<<_transactionsresponse,TransactionsResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Node


[[_getpeers]]
=== Requests peers data
....
GET /peers
....


==== Description
Search for specified peers.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**height** +
__optional__|Current height of the network|integer (int32)|
|**Query**|**httpPort** +
__optional__|Http port of the node or delegate|integer (int32)|
|**Query**|**ip** +
__optional__|IP of the node or delegate|string (ip)|
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**os** +
__optional__|OS of the node|string|
|**Query**|**protocolVersion** +
__optional__|Protocol version of the node|string (protocolVersion)|
|**Query**|**sort** +
__optional__|Fields to sort results by|enum (height:asc, height:desc, version:asc, version:desc)|`"height:desc"`
|**Query**|**state** +
__optional__|Current state of the network|enum (connected, disconnected)|
|**Query**|**version** +
__optional__|Lisk version of the node|string (version)|
|**Query**|**wsPort** +
__optional__|Web socket port for the node or delegate|integer (int32)|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|List of peers|<<_peersresponse,PeersResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Peers


[[_postsignature]]
=== Submits a signature object to sign multisignature transactions
....
POST /signatures
....


==== Description
Submits signature to sign a multisignature transaction.
Signature objects can be generated locally either by using Lisk Commander or with Lisk Elements.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**signature** +
__required__|Signature object to submit to the network|<<_signature,Signature>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Signature is accepted by the node for processing|<<_signatureresponse,SignatureResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**409**|Some error related to processing of request|<<_processingerror,ProcessingError>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Consumes

* `application/json`


==== Produces

* `application/json`


==== Tags

* Signatures


[[_posttransaction]]
=== Submits signed transaction for processing
....
POST /transactions
....


==== Description
Submits signed transaction object for processing by the transaction pool.
Transaction objects can be generated locally either by using Lisk Commander or with Lisk Elements.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**transaction** +
__required__|Transaction object to submit to the network|<<_transactionrequest,TransactionRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Transaction accepted by the node for processing|<<_generalstatusresponse,GeneralStatusResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**409**|Some error related to processing of request|<<_processingerror,ProcessingError>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|===


==== Consumes

* `application/json`


==== Produces

* `application/json`


==== Tags

* Transactions


[[_gettransactions]]
=== Requests transactions data
....
GET /transactions
....


==== Description
Search for a specified transaction in the system.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**blockId** +
__optional__|Block id to query|string (id)|
|**Query**|**data** +
__optional__|Fuzzy additional data field to query|string (additionalData)|
|**Query**|**fromTimestamp** +
__optional__|Starting unix timestamp|integer|
|**Query**|**height** +
__optional__|Current height of the network|integer (int32)|
|**Query**|**id** +
__optional__|Transaction id to query|string (id)|
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**maxAmount** +
__optional__|Maximum transaction amount in Beddows|integer|
|**Query**|**minAmount** +
__optional__|Minimum transaction amount in Beddows|integer|
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**recipientId** +
__optional__|Recipient lisk address|string (address)|
|**Query**|**senderId** +
__optional__|Sender lisk address|string (address)|
|**Query**|**senderIdOrRecipientId** +
__optional__|Lisk address|string (address)|
|**Query**|**senderPublicKey** +
__optional__|Sender public key|string (publicKey)|
|**Query**|**sort** +
__optional__|Fields to sort results by|enum (amount:asc, amount:desc, fee:asc, fee:desc, type:asc, type:desc, timestamp:asc, timestamp:desc)|`"amount:asc"`
|**Query**|**toTimestamp** +
__optional__|Ending unix timestamp|integer|
|**Query**|**type** +
__optional__|Transaction type (0-*)|integer|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Transactions list|<<_transactionsresponse,TransactionsResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Transactions


[[_getvoters]]
=== Requests voters data for a delegate
....
GET /voters
....


==== Description
_Attention: At least *one of the filter parameters must be provided.*_
Returns all votes received by a delegate.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**address** +
__optional__|Address of an account|string (address)|
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**publicKey** +
__optional__|Public key to query|string (publicKey)|
|**Query**|**secondPublicKey** +
__optional__|Second public key to query|string (publicKey)|
|**Query**|**sort** +
__optional__|Fields to sort results by|enum (publicKey:asc, publicKey:desc, balance:asc, balance:desc, username:asc, username:desc)|`"publicKey:asc"`
|**Query**|**username** +
__optional__|Delegate username to query|string (username)|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Voters list|<<_votersresponse,VotersResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**404**|Requested resource not found based on provided filters|<<_notfounderror,NotFoundError>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Voters


[[_getvotes]]
=== Requests votes data for an account
....
GET /votes
....


==== Description
_Attention: At least *one of the filter parameters must be provided.*_
Returns all votes placed by an account.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**address** +
__optional__|Address of an account|string (address)|
|**Query**|**limit** +
__optional__|Limit applied to results|integer (int32)|`10`
|**Query**|**offset** +
__optional__|Offset value for results|integer (int32)|`0`
|**Query**|**publicKey** +
__optional__|Public key to query|string (publicKey)|
|**Query**|**secondPublicKey** +
__optional__|Second public key to query|string (publicKey)|
|**Query**|**sort** +
__optional__|Fields to sort results by|enum (username:asc, username:desc, balance:asc, balance:desc)|`"username:asc"`
|**Query**|**username** +
__optional__|Delegate username to query|string (username)|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Votes list|<<_votesresponse,VotesResponse>>
|**400**|Malformed query or parameters|<<_paramerrorresponse,ParamErrorResponse>>
|**404**|Requested resource not found based on provided filters|<<_notfounderror,NotFoundError>>
|**429**|Too many requests, exceeded rate limit|<<_requestlimiterror,RequestLimitError>>
|**500**|Unexpected error|<<_unexpectederror,UnexpectedError>>
|===


==== Produces

* `application/json`


==== Tags

* Votes


[[_definitions]]
== Definitions

[[_accessdeniederror]]
=== AccessDeniedError

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**message** +
__required__|Error message containing details of the error +
**Minimum length** : `1`|string
|===


[[_account]]
=== Account

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk Address is the human readable representation of the accounts owners' public key.
It consists of multiple numbers followed by a big 'L' at the end. +
**Example** : `"12668885769632475474L"`|string (address)
|**publicKey** +
__required__|The public key is derived from the private key of the owner of the account.
It can be used to validate that the private key belongs to the owner, but not provide access to the owners private key. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**secondPublicKey** +
__optional__|The second public key is derived from the second private key of an account, if the owner activated a second passphrase for her/his account. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|===


[[_accountextended]]
=== AccountExtended

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk Address is the human readable representation of the accounts owners' public key.
It consists of 21 numbers followed by a big 'L' at the end. +
**Example** : `"12668885769632475474L"`|string (address)
|**asset** +
__optional__|Any JSON stored in the account's asset field. +
**Example** : `{
  "custom" : true,
  "field" : true
}`|object
|**balance** +
__required__|The current balance of the account in Beddows. +
**Example** : `"1081560729258"`|string
|**delegate** +
__optional__||<<_delegate,Delegate>>
|**publicKey** +
__required__|The public key is derived from the private key of the owner of the account.
It can be used to validate that the private key belongs to the owner, but does not provide access to the owners private key. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**secondPublicKey** +
__optional__|The second public key is derived from the second private key of an account, if the owner activated a second passphrase for her/his account. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|===


[[_accountsresponse]]
=== AccountsResponse

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**data** +
__required__|List of accounts|< <<_accountextended,AccountExtended>> > array
|**links** +
__required__||object
|**meta** +
__required__||<<_meta,Meta>>
|===


[[_block]]
=== Block

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**blockSignature** +
__optional__|Derived from a SHA-256 hash of the block header,
that is signed by the private key of the delegate who forged the block. +
**Example** : `"a3733254aad600fa787d6223002278c3400be5e8ed4763ae27f9a15b80e20c22ac9259dc926f4f4cabdf0e4f8cec49308fa8296d71c288f56b9d1e11dfe81e07"`|string (signature)
|**confirmations** +
__optional__|Number of times that this Block has been confirmed by the network.
By forging a new block on a chain, all former blocks in the chain get confirmed by the forging delegate. +
**Example** : `200`|integer
|**generatorAddress** +
__optional__|Lisk Address of the delegate who forged the block. +
**Example** : `"12668885769632475474L"`|string (address)
|**generatorPublicKey** +
__required__|Public key of th edelagte who forged the block. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**height** +
__required__|Height of the network, when the block got forged.
The height of the networks represents the number of blocks,
that have been forged on the network since Genesis Block. +
**Minimum value** : `1` +
**Example** : `123`|integer
|**id** +
__required__|Unique identifier of the block.
Derived from the block signature. +
**Length** : `1 - 20` +
**Example** : `"6258354802676165798"`|string (id)
|**maxHeightPreviouslyForged** +
__optional__|Largest height of any block previously forged by the generatorPublicKey as defined in the Lisk BFT Protocol.
See https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md +
**Example** : `123`|integer
|**maxHeightPrevoted** +
__optional__|Largest height of an ancestor block with at least 68 prevotes as defined in the Lisk BFT Protocol.
See https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md +
**Example** : `123`|integer
|**numberOfTransactions** +
__required__|The number of transactions processed in the block. +
**Example** : `15`|integer
|**payloadHash** +
__optional__|Hash of the payload of the block.
The payload of a block is comprised of the transactions the block contains.
For each type of transaction exists a different maximum size for the payload. +
**Example** : `"4e4d91be041e09a2e54bb7dd38f1f2a02ee7432ec9f169ba63cd1f193a733dd2"`|string (hex)
|**payloadLength** +
__optional__|Bytesize of the payload hash. +
**Minimum value** : `0` +
**Example** : `117`|integer
|**previousBlockId** +
__optional__|The id of the previous block of the chain. +
**Example** : `"15918760246746894806"`|string (id)
|**reward** +
__required__|The Lisk reward for the delegate. +
**Example** : `"50000000"`|string
|**timestamp** +
__required__|Unix Timestamp +
**Example** : `28227090`|integer
|**totalAmount** +
__required__|The total amount of Lisk transferred. +
**Example** : `"150000000"`|string
|**totalFee** +
__required__|The total amount of fees associated with the block. +
**Example** : `"15000000"`|string
|**totalForged** +
__required__|Total amount of LSK that have been forged in this Block.
Consists of fees and the reward. +
**Example** : `"65000000"`|string
|**version** +
__optional__|Versioning for future upgrades of the lisk protocol. +
**Minimum value** : `0` +
**Example** : `0`|integer
|===


[[_blocksresponse]]
=== BlocksResponse
Blocks response


[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|< <<_block,Block>> > array
|**links** +
__required__|object
|**meta** +
__required__|<<_meta,Meta>>
|===


[[_dapp]]
=== Dapp

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**category** +
__optional__|The category of the Dapp. +
**Example** : `8.0`|number
|**description** +
__optional__|Description of the Dapp. +
**Example** : `"Smart Gun Network"`|string
|**icon** +
__optional__|Dapp icon.
A link to the icon can be provided in the Register Dapp Transaction object. +
**Example** : `"http://www.blocksafefoundation.com/header.jpg"`|string
|**link** +
__optional__|**Example** : `"https://github.com/blocksafe/SDK-notice/archive/master.zip"`|string
|**name** +
__required__|Name of the Dapp. +
**Example** : `"Blocksafe"`|string
|**tags** +
__optional__|Tags of the Dapp. +
**Example** : `"Smartgun"`|string
|**transactionId** +
__required__|Unique Identifier of the Register Dapp Transaction.
Derived from the transaction signature. +
**Length** : `1 - 20` +
**Example** : `"15359945250124697273"`|string (id)
|**type** +
__required__|The type of the Dapp. +
**Example** : `8.0`|number
|===


[[_dappsresponse]]
=== DappsResponse
Dapps endpoint response


[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|< <<_dapp,Dapp>> > array
|**links** +
__required__|object
|**meta** +
__required__|<<_meta,Meta>>
|===


[[_delegate]]
=== Delegate

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**approval** +
__optional__|Percentage of the voters weight, that the delegate owns in relation to the total supply of Lisk. +
**Example** : `14.22`|number
|**missedBlocks** +
__optional__|Total number of blocks the delegate has missed. +
**Example** : `427`|integer
|**producedBlocks** +
__optional__|Total number of blocks the delegate has forged. +
**Example** : `20131`|integer
|**productivity** +
__optional__|Productivity rate.
Percentage of successfully forged blocks (not missed) by the delegate. +
**Example** : `96.41`|number
|**rewards** +
__optional__|Total sum of block rewards that the delegate has forged. +
**Example** : `"510000000"`|string
|**username** +
__required__|The delegates' username.
A delegate chooses the username by registering a delegate on the Lisk network.
It is unique and cannot be changed later. +
**Example** : `"isabella"`|string (username)
|**voteWeight** +
__required__|The voters weight of the delegate.
Represents the total amount of Lisk (in Beddows) that the delegates' voters own.
The voters weight decides which rank the delegate gets in relation to the other delegates and their voters weights. +
**Example** : `"1081560729258"`|string
|===


[[_delegatewithaccount]]
=== DelegateWithAccount

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**account** +
__required__||<<_account,Account>>
|**approval** +
__optional__|Percentage of the voters weight, that the delegate owns in relation to the total supply of Lisk. +
**Example** : `14.22`|number
|**missedBlocks** +
__optional__|Total number of blocks the delegate has missed. +
**Example** : `427`|integer
|**producedBlocks** +
__optional__|Total number of blocks the delegate has forged. +
**Example** : `20131`|integer
|**productivity** +
__optional__|Productivity rate.
Percentage of successfully forged blocks (not missed) by the delegate. +
**Example** : `96.41`|number
|**rewards** +
__optional__|Total sum of block rewards that the delegate has forged. +
**Example** : `"510000000"`|string
|**username** +
__required__|The delegates' username.
A delegate chooses the username by registering a delegate on the Lisk network.
It is unique and cannot be changed later. +
**Example** : `"isabella"`|string (username)
|**voteWeight** +
__required__|The voters weight of the delegate.
Represents the total amount of Lisk (in Beddows) that the delegates' voters own.
The voters weight decides which rank the delegate gets in relation to the other delegates and their voters weights. +
**Example** : `"1081560729258"`|string
|===


[[_delegatewithvoters]]
=== DelegateWithVoters

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk Address of a delegate. +
**Example** : `"12668885769632475474L"`|string (address)
|**balance** +
__required__|Account balance.
Amount of Lisk the delegate account owns. +
**Example** : `"1081560729258"`|string
|**publicKey** +
__optional__|The public key of the delegate. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**username** +
__required__|The delegates' username.
A delegate chooses the username by registering a delegate on the Lisk network.
It is unique and cannot be changed later. +
**Example** : `"isabella"`|string (username)
|**voters** +
__required__|List of accounts that voted for the queried delegate.|< <<_voter,Voter>> > array
|**votes** +
__required__|The voters weight of the delegate.
Represents the total amount of Lisk (in Beddows) that the delegates' voters own.
The voters weight decides which rank the delegate gets in relation to the other delegates and their voters weights. +
**Example** : `108877`|integer
|===


[[_delegatewithvotes]]
=== DelegateWithVotes

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk Address of the queried account. +
**Example** : `"12668885769632475474L"`|string (address)
|**balance** +
__required__|The balance of the queried account. +
**Example** : `"1081560729258"`|string
|**publicKey** +
__optional__|Public key of the queried account. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**username** +
__required__|Username of the account, if the queried account is a delegate +
**Example** : `"isabella"`|string (username)
|**votes** +
__required__|List of placed votes by the queried account.|< <<_vote,Vote>> > array
|**votesAvailable** +
__required__|Number of votes that are available for the queried account.
Derives from 101(max possible votes) - votesUsed(alreadu used votes) +
**Example** : `40`|integer
|**votesUsed** +
__required__|Number of votes that are already placed by the queried account. +
**Example** : `2`|integer
|===


[[_delegatesresponse]]
=== DelegatesResponse

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**data** +
__required__|List of delegates|< <<_delegatewithaccount,DelegateWithAccount>> > array
|**links** +
__required__||object
|**meta** +
__required__||<<_delegatesresponse_meta,meta>>
|===

[[_delegatesresponse_meta]]
**meta**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**limit** +
__required__|**Default** : `10` +
**Minimum value** : `1` +
**Maximum value** : `101`|integer (int32)
|**offset** +
__required__||<<_offset,Offset>>
|===


[[_fees]]
=== Fees

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**dappDeposit** +
__required__|**Example** : `"10000000"`|string
|**dappRegistration** +
__required__|**Example** : `"2500000000"`|string
|**dappWithdrawal** +
__required__|**Example** : `"10000000"`|string
|**delegate** +
__required__|**Example** : `"2500000000"`|string
|**multisignature** +
__required__|**Example** : `"500000000"`|string
|**secondSignature** +
__required__|**Example** : `"500000000"`|string
|**send** +
__required__|**Example** : `"10000000"`|string
|**vote** +
__required__|**Example** : `"100000000"`|string
|===


[[_forger]]
=== Forger

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk Address is the human readable representation of the accounts owners' public key.
It consists of 21 numbers followed by a big 'L' at the end. +
**Example** : `"6251001604903637008L"`|string (address)
|**nextSlot** +
__required__|Returns the slot number in which the forger will be able to forge the next block.
Each slot has a timespan of 10 seconds.
The first slot began directly after the Lisk Epoch Time. +
**Example** : `4368793.0`|number
|**publicKey** +
__required__|The public key is derived from the private key of the owner of the account.
It can be used to validate that the private key belongs to the owner, but not provide access to the owners private key. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|**username** +
__required__|The delegates' username.
A delegate chooses the username by registering a delegate on the Lisk network.
It is unique and cannot be changed later. +
**Example** : `"isabella"`|string (username)
|===


[[_forgersresponse]]
=== ForgersResponse

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**data** +
__required__|List of forgers|< <<_forger,Forger>> > array
|**links** +
__required__||object
|**meta** +
__required__||<<_forgersresponse_meta,meta>>
|===

[[_forgersresponse_meta]]
**meta**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**currentSlot** +
__required__|Currently active slot +
**Example** : `10`|integer
|**lastBlock** +
__required__|ID of the last processed block +
**Example** : `10`|integer
|**lastBlockSlot** +
__required__|Slot of the last processed block +
**Example** : `10`|integer
|**limit** +
__required__|**Default** : `10` +
**Minimum value** : `1` +
**Maximum value** : `101`|integer (int32)
|**offset** +
__required__||<<_offset,Offset>>
|===


[[_forgingstats]]
=== ForgingStats

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**count** +
__required__|Amount of blocks, that the delegate has forged during the timespan. +
**Example** : `"100"`|string
|**fees** +
__required__|Amount of fees, the delegate earned during the timespan. +
**Example** : `"15000000"`|string
|**forged** +
__required__|Amount of Lisk, that have been transferred inside the forged blocks of a delegate, during the timespan. +
**Example** : `"65000000"`|string
|**rewards** +
__required__|Amount of rewards, the delegate earned during the timespan. +
**Example** : `"50000000"`|string
|===


[[_forgingstatsresponse]]
=== ForgingStatsResponse

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|<<_forgingstats,ForgingStats>>
|**links** +
__required__|object
|**meta** +
__required__|<<_forgingstatsresponse_meta,meta>>
|===

[[_forgingstatsresponse_meta]]
**meta**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**fromTimestamp** +
__required__|Starting unix timestamp +
**Example** : `0`|integer
|**toTimestamp** +
__required__|Ending unix timestamp +
**Example** : `1525861914`|integer
|===


[[_forgingstatus]]
=== ForgingStatus

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**forging** +
__required__|True if the delegate enabled forging. +
**Example** : `true`|boolean
|**publicKey** +
__required__|Public key of the queried delegate. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|===


[[_forgingstatusresponse]]
=== ForgingStatusResponse

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|< <<_forgingstatus,ForgingStatus>> > array
|**links** +
__required__|object
|**meta** +
__required__|object
|===


[[_generalstatusresponse]]
=== GeneralStatusResponse

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|<<_generalstatusresponse_data,data>>
|**links** +
__required__|object
|**meta** +
__required__|<<_generalstatusresponse_meta,meta>>
|===

[[_generalstatusresponse_data]]
**data**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**message** +
__required__|**Minimum length** : `1`|string
|===

[[_generalstatusresponse_meta]]
**meta**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**status** +
__required__|Acceptance status for transactions +
**Example** : `true`|boolean
|===


[[_limit]]
=== Limit
Limit applied to results

__Type__ : integer (int32)


[[_meta]]
=== Meta

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**limit** +
__required__|<<_limit,Limit>>
|**offset** +
__required__|<<_offset,Offset>>
|===


[[_multisignaturegroup]]
=== MultisignatureGroup

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk Address is the human readable representation of the accounts owners' public key.
It consists of 21 numbers followed by a big 'L' at the end. +
**Example** : `"12668885769632475474L"`|string (address)
|**balance** +
__required__|The current balance of the account in Beddows. +
**Example** : `"1081560729258"`|string
|**lifetime** +
__required__|The maximum amount of hours, that a transaction will wait for the minimum amount of signatures to be reached.
If not enough members of a multisignature group sign the transaction in the defined lifespan, the transaction will be invalid. +
**Example** : `72`|integer
|**members** +
__required__||< <<_account,Account>> > array
|**min** +
__required__|Minimum amount of signatures a transaction needs to be signed successfully by this multisignature account. +
**Example** : `3`|integer
|**publicKey** +
__required__|The public key is derived from the private key of the owner of the account.
It can be used to validate that the private key belongs to the owner, but not provide access to the owners private key. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**secondPublicKey** +
__optional__|The second public key is derived from the second private key of an account, if the owner activated a second passphrase for her/his account. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|===


[[_multisignaturegroupsresponse]]
=== MultisignatureGroupsResponse

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**data** +
__required__|List of multisignature groups|< <<_multisignaturegroup,MultisignatureGroup>> > array
|**links** +
__required__||object
|**meta** +
__required__||object
|===


[[_nodeconstants]]
=== NodeConstants

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**build** +
__required__|The build number.
Consists of `v` + the date and time of the build of the node. +
**Example** : `"v09:54:35 12/04/2017"`|string
|**commit** +
__required__|The last commit that was added to the codebase. +
**Length** : `40` +
**Example** : `"7199d4b67c3575d5f99d1c29436a02977eeb01a7"`|string
|**epoch** +
__required__|Timestamp of first block on the network. +
**Example** : `"2016-05-24T17:00:00.000Z"`|string (date-time)
|**fees** +
__required__||<<_fees,Fees>>
|**milestone** +
__required__|The Reward, each forger will get for forging a block at the current slot.
After a certain amount of slots, the reward will be reduced. +
**Example** : `"500000000"`|string
|**networkId** +
__required__|Unique identifier for the network.
The networkId that the node is connecting to, see LIP-0009 for more details. +
**Example** : `"ed14889723f24ecc54871d058d98ce91ff2f973192075c0155ba2b7b70ad2511"`|string
|**protocolVersion** +
__optional__|The Lisk Core protocol version, that the node is running on. +
**Example** : `"1.0"`|string (protocolVersion)
|**reward** +
__required__|The reward a delegate will get for forging a block.
Depends on the slot height. +
**Example** : `"500000000"`|string
|**supply** +
__required__|Total supply of LSK in the network. +
**Example** : `"10575384500000000"`|string
|**version** +
__required__|The Lisk Core version, that the node is running on. +
**Example** : `"v0.8.0"`|string (version)
|===


[[_nodeconstantsresponse]]
=== NodeConstantsResponse

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|<<_nodeconstants,NodeConstants>>
|**links** +
__required__|object
|**meta** +
__required__|object
|===


[[_nodestatus]]
=== NodeStatus

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**chainMaxHeightFinalized** +
__required__|The largest height with precommits by at least 68 delegates.
See https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md +
**Example** : `123`|integer
|**currentTime** +
__required__|Current time of the node in miliseconds (Unix Timestamp). +
**Example** : `1533558858128`|integer
|**height** +
__required__|Current block height of the node.
Represents the current number of blocks in the chain on the node. +
**Minimum value** : `1` +
**Example** : `123`|integer
|**secondsSinceEpoch** +
__required__|Number of seconds that have elapsed since the Lisk epoch time (Lisk Timestamp). +
**Example** : `1533558858`|integer
|**syncing** +
__required__|True if the node syncing with other peers. +
**Example** : `false`|boolean
|===


[[_nodestatusresponse]]
=== NodeStatusResponse

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|<<_nodestatus,NodeStatus>>
|**links** +
__required__|object
|**meta** +
__required__|object
|===


[[_notfounderror]]
=== NotFoundError

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**message** +
__required__|Error message containing details of the error +
**Minimum length** : `1`|string
|===


[[_offset]]
=== Offset
Offset value for results

__Type__ : integer (int32)


[[_paramerror]]
=== ParamError
Collection of errors on a particular parameter


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**code** +
__required__|Valid error code explaining error +
**Example** : `"INVALID_REQUEST_PARAMETER"`|string
|**errors** +
__optional__|Array of individual validation error for a particular param|< <<_paramerrormessage,ParamErrorMessage>> > array
|**in** +
__optional__|Where the param was specified, e.g. path, query, form-data +
**Example** : `"query"`|string
|**message** +
__required__|Detailed message explaining the error +
**Example** : `"Invalid parameter (offset) value failed JSON schema validation"`|string
|**name** +
__required__|Parameter name for which error triggered +
**Example** : `"offset"`|string
|===


[[_paramerrormessage]]
=== ParamErrorMessage
Singular error detail for a parameter


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**code** +
__optional__|Valid error code explaining error +
**Example** : `"MINIMUM"`|string
|**description** +
__optional__|Param description specified in schema|string
|**message** +
__required__|Detailed message explaining error +
**Example** : `"Value -1 is less than minimum 0"`|string
|**path** +
__optional__|The array/object paths which identify the param associated with the error|< string > array
|===


[[_paramerrorresponse]]
=== ParamErrorResponse
Response generated in case of parameters validation


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**errors** +
__required__|Array of individual parameter errors|< <<_paramerror,ParamError>> > array
|**message** +
__required__|Message stating some valdiation error occurred +
**Example** : `"Validation errors"`|string
|===


[[_peer]]
=== Peer

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**height** +
__optional__|Network height on the peer node.
Represents the current number of blocks in the chain on the peer node. +
**Example** : `123`|integer
|**httpPort** +
__optional__|The port the peer node uses for HTTP requests, e.g. API calls. +
**Minimum value** : `1` +
**Maximum value** : `65535` +
**Example** : `8000`|integer (int32)
|**ip** +
__optional__|IPv4 address of the peer node. +
**Example** : `"127.0.0.1"`|string (ip)
|**networkId** +
__optional__|The network identifier as per LIP-0009 +
**Example** : `"11a254dc30db5eb1ce4001acde35fd5a14d62584f886d30df161e4e883220eb7"`|string
|**os** +
__optional__|The Operating System, that the peer node runs on. +
**Example** : `"debian"`|string
|**protocolVersion** +
__optional__|The protocol version of Lisk Core that the peer node runs on. +
**Example** : `"1.0"`|string (protocolVersion)
|**state** +
__required__|The state of the Peer. +
**Example** : `"connected"`|enum (connected, disconnected)
|**version** +
__optional__|The version of Lisk Core that the peer node runs on. +
**Example** : `"v0.8.0"`|string (version)
|**wsPort** +
__required__|The port the peer node uses for Websocket Connections, e.g. P2P broadcasts. +
**Minimum value** : `1` +
**Maximum value** : `65535` +
**Example** : `8001`|integer (int32)
|===


[[_peersresponse]]
=== PeersResponse
Peers response


[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|< <<_peer,Peer>> > array
|**links** +
__required__|object
|**meta** +
__required__|<<_peersresponse_meta,meta>>
|===

[[_peersresponse_meta]]
**meta**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**count** +
__required__|Number of peers in the response +
**Example** : `100`|integer
|**limit** +
__required__||<<_limit,Limit>>
|**offset** +
__required__||<<_offset,Offset>>
|===


[[_processingerror]]
=== ProcessingError

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**code** +
__optional__|Error code containing details on status|integer
|**errors** +
__optional__|Array containing TransactionError objects|< <<_transactionerror,TransactionError>> > array
|**message** +
__required__|Error message containing details of the error +
**Minimum length** : `1`|string
|===


[[_requestlimiterror]]
=== RequestLimitError

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**error** +
__optional__|**Example** : `"Request limit exceeded. Please try again later"`|string
|===


[[_signature]]
=== Signature

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**publicKey** +
__required__|Public key of the account that intends to sign the multisignature transaction. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|**signature** +
__required__|Signature to sign the transaction.
The signature can be generated locally, either by using Lisk Commander or with Lisk Elements. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**transactionId** +
__required__|Unique identifier of the multisignature transaction to sign. +
**Length** : `1 - 20` +
**Example** : `"222675625422353767"`|string (id)
|===


[[_signatureresponse]]
=== SignatureResponse
Signature response


[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|<<_signatureresponse_data,data>>
|**links** +
__required__|object
|**meta** +
__required__|<<_signatureresponse_meta,meta>>
|===

[[_signatureresponse_data]]
**data**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**message** +
__required__|**Minimum length** : `1`|string
|===

[[_signatureresponse_meta]]
**meta**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**status** +
__required__|Acceptance status for the signature +
**Example** : `true`|boolean
|===


[[_transaction]]
=== Transaction

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**asset** +
__required__||object
|**blockId** +
__optional__|The Id of the block, this transaction is included in. +
**Length** : `1 - 20` +
**Example** : `"6258354802676165798"`|string (id)
|**confirmations** +
__optional__|Number of times that this transaction has been confirmed by the network.
By forging a new block on a chain, all former blocks and their contained transactions in the chain get confirmed by the forging delegate. +
**Minimum value** : `0`|integer
|**fee** +
__required__|Transaction fee associated with this transaction. +
**Example** : `"1000000"`|string
|**height** +
__optional__|The height of the network, at the moment where this transaction was included in the blockchain. +
**Minimum value** : `1`|integer
|**id** +
__required__|Unique identifier of the transaction.
Derived from the transaction signature. +
**Length** : `1 - 20` +
**Example** : `"222675625422353767"`|string (id)
|**ready** +
__optional__|Only present in transactions sent from a multisignature account, or transactions type 4 (multisignature registration).
False, if the minimum amount of signatures to sign this transaction has not been reached yet.
True, if the minimum amount of signatures has been reached. +
**Example** : `false`|boolean
|**receivedAt** +
__optional__|The timestamp of the moment, where a node discovered a transaction for the first time.|string (date-time)
|**senderId** +
__optional__|Lisk Address of the Senders' account. +
**Example** : `"12668885769632475474L"`|string (address)
|**senderPublicKey** +
__required__|The public key of the Senders' account. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|**senderSecondPublicKey** +
__optional__|The second public key of the Senders' account, if it exists. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|**signSignature** +
__optional__|Contains the second signature, if the transaction is sent from an account with second passphrase activated. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**signature** +
__required__|Derived from a SHA-256 hash of the transaction object,
that is signed by the private key of the account who created the transaction. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**signatures** +
__optional__||< string (signature) > array
|**timestamp** +
__required__|Time when the transaction was created.
Unix Timestamp. +
**Example** : `28227090`|integer
|**type** +
__required__|Describes the Transaction type. +
**Minimum value** : `0`|integer
|===


[[_transactionerror]]
=== TransactionError

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**dataPath** +
__required__|Transaction field with error|string
|**id** +
__required__|Transaction ID +
**Minimum length** : `1`|string
|**message** +
__required__|Error message|string
|**name** +
__optional__|Type of Error|string
|===


[[_transactionrequest]]
=== TransactionRequest

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**asset** +
__required__|Displays additional transaction data.
Can include e.g. vote data or delegate username.|<<_transactionrequest_asset,asset>>
|**id** +
__required__|Unique identifier of the transaction.
Derived from the transaction signature. +
**Length** : `1 - 20` +
**Example** : `"222675625422353767"`|string (id)
|**senderPublicKey** +
__required__|The public key of the Senders' account. +
**Example** : `"2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079"`|string (publicKey)
|**signSignature** +
__optional__|Contains the second signature, if the transaction is sent from an account with second passphrase activated. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**signature** +
__required__|Derived from a SHA-256 hash of the transaction object,
that is signed by the private key of the account who created the transaction. +
**Example** : `"2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205"`|string (signature)
|**signatures** +
__optional__|If the transaction is a multisignature transaction, all signatures of the members of the corresponding multisignature group will be listed here.|< string (signature) > array
|**timestamp** +
__required__|Time when the transaction was created.
Unix Timestamp. +
**Example** : `28227090`|integer
|**type** +
__required__|Describes the Transaction type. +
**Minimum value** : `0`|integer
|===

[[_transactionrequest_asset]]
**asset**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**amount** +
__optional__|Amount of Lisk to be transferred in this transaction. +
**Example** : `"150000000"`|string
|**recipientId** +
__optional__|Lisk Address of the Recipients' account. +
**Example** : `"12668885769632475474L"`|string (address)
|===


[[_transactionsresponse]]
=== TransactionsResponse
Transactions response


[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|< <<_transaction,Transaction>> > array
|**links** +
__required__|object
|**meta** +
__required__|<<_transactionsresponse_meta,meta>>
|===

[[_transactionsresponse_meta]]
**meta**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**count** +
__required__|Number of transactions in the response +
**Example** : `100`|integer
|**limit** +
__required__||<<_limit,Limit>>
|**offset** +
__required__||<<_offset,Offset>>
|===


[[_unexpectederror]]
=== UnexpectedError

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**message** +
__required__|Error message containing details of the error +
**Minimum length** : `1`|string
|===


[[_vote]]
=== Vote

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**address** +
__required__|Lisk Address of the delegate the queried account voted for. +
**Example** : `"12668885769632475474L"`|string (address)
|**balance** +
__required__|Balance of the delegate the queried account voted for. +
**Example** : `"1081560729258"`|string
|**publicKey** +
__required__|Public key of the delegate the queried account voted for. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|**username** +
__required__|Username of the delegate the queried account voted for. +
**Example** : `"liskhq"`|string (username)
|===


[[_voter]]
=== Voter

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**address** +
__required__|The Lisk Address of the account that voted for the queried delegate. +
**Example** : `"12668885769632475474L"`|string (address)
|**balance** +
__required__|Balance of the account that voted for the queried delegate. +
**Example** : `"1081560729258"`|string
|**publicKey** +
__required__|Public key of the account that voted for the queried delegate. +
**Example** : `"968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b"`|string (publicKey)
|===


[[_votersresponse]]
=== VotersResponse
Voters endpoint response


[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|<<_delegatewithvoters,DelegateWithVoters>>
|**links** +
__required__|object
|**meta** +
__required__|<<_meta,Meta>>
|===


[[_votesresponse]]
=== VotesResponse
Votes endpoint response


[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**data** +
__required__|<<_delegatewithvotes,DelegateWithVotes>>
|**links** +
__required__|object
|**meta** +
__required__|<<_votesresponse_meta,meta>>
|===

[[_votesresponse_meta]]
**meta**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**limit** +
__required__|**Default** : `10` +
**Minimum value** : `1` +
**Maximum value** : `101`|integer (int32)
|**offset** +
__required__||<<_offset,Offset>>
|===
