= Configuration
Mona Bärenfänger <mona@lightcurve.io>
:description: This section covers the config object, the default values including a description of each value.
:toc:
:url_guide_config: guides/configuration.adoc

[[config_object]]
== The Config object

The values below are the *default values*.
They will be used automatically when starting the application without specifying a specific configuration.
To change them, override the specific default values with custom values when initializing the application.
For more information, please see the xref:{url_guide_config}[configuration guide].

[source,js]
----
{
    label: 'alpha-sdk-app', //<1>
    version: '0.0.0', //<2>
    protocolVersion: '1.1', //<3>
    tempPath: '/tmp/lisk', //<4>
    ipc: {
        enabled: false, //<5>
    },
    genesisConfig: {
        epochTime: new Date(Date.UTC(2016, 4, 24, 17, 0, 0, 0)).toISOString(), //<6>
        blockTime: 10, //<7>
        maxPayloadLength: 15 * 1024, // Kilo Bytes <8>
        rewards: {
            milestones: [
                '500000000', // Initial Reward //<9>
                '400000000', // Milestone 1 //<10>
                '300000000', // Milestone 2 //<11>
                '200000000', // Milestone 3 //<12>
                '100000000', // Milestone 4 //<13>
            ],
            offset: 2160, // Start rewards at 39th block of 22nd round //<14>
            distance: 3000000, // Distance between each milestone //<15>
        },
    },
    rebuildUpToRound: null, //<16>
    forging: {
        force: false, //<17>
        waitThreshold: 2, //<18>
        delegates: [], //<19>
    },
    network: {
        seedPeers: [], //<20>
        wsPort: 5000, //<21>
    },
    components: {
        logger: {
            fileLogLevel: 'info', //<22>
            consoleLogLevel: 'none', //<23>
            logFileName: 'logs/lisk.log', //<24>
        },
        cache: {
            enabled: false, //<25>
            host: '127.0.0.1', //<26>
            port: 6380, //<27>
            db: 0, //<28>
            password: null, //<29>
        },
        storage: {
            host: 'localhost', //<30>
            port: 5432, //<31>
            database: 'lisk_dev', //<32>
            user: 'lisk', //<33>
            password: 'password', //<34>
            min: 10, //<35>
            max: 25, //<36>
            poolIdleTimeout: 30000, //<37>
            reapIntervalMillis: 1000, //<38>
            logEvents: ['error'], //<39>
            logFileName: 'logs/lisk_db.log', //<40>
        },
    },
    modules: {
        http_api: {
            enabled: true, //<41>
            httpPort: 4000, //<42>
            address: '0.0.0.0', //<43>
            trustProxy: false, //<44>
            access: {
                public: false, //<45>
                whiteList: ['127.0.0.1'], //<46>
            },
            ssl: {
                enabled: false, //<47>
                options: {
                    port: 443, //<48>
                    address: '0.0.0.0', //<49>
                    key: './ssl/lisk.key', //<50>
                    cert: './ssl/lisk.crt', //<51>
                },
            },
            options: {
                limits: {
                    max: 0, //<52>
                    delayMs: 0, //<53>
                    delayAfter: 0, //<54>
                    windowMs: 60000, //<55>
                    headersTimeout: 5000, //<56>
                    serverSetTimeout: 20000, //<57>
                },
                cors: {
                    origin: '*', //<58>
                    methods: ['GET', 'POST', 'PUT'], //<59>
                },
            },
            forging: {
                access: {
                    whiteList: ['127.0.0.1'], //<60>
                },
            },
            apm: {
                enabled: false, //<61>
                options: {
                    name: 'Lisk-APM', //<62>
                    uriPath: '/http-stats', //<63>
                },
            },
        },
    },
}
----

<1> Label of the application.
<2> Version of the application.
//<3> Minimal compatible version.
<3> Protocol Version of the application.
<4> Root path for storing temporary pid and socket file.
<5> If true, it allows modules to communicate over IPCs, (inter-process-channels).
//<7> Network specific constants.
<6> Epoch timestamp indicating the initial network start, (`Date.toISOString()`).
<7> Slot time interval in seconds.
<8> Maximum payload allowed per block.
//<11> Initial 5 LSK, and decreasing until 1 LSK.
<9> Initial block reward.
<10> Block reward after milestone 1.
<11> Block reward after milestone 2.
<12> Block reward after milestone 3.
<13> Block reward after milestone 4.
<14> Offset describing the number of blocks that need to be added to the chain, before paying out the first rewards.
<15> Distance of blocks between each milestone.
<16> Integer.
If this value is defined, the node will start and rebuild up to the defined round, (set to 0 to rebuild until current round).
Otherwise, the application continues normal execution.
<17> Forces forging to be on, only used on local development networks.
//<18> waitThreshold
<19> List of delegates, who are allowed to forge on this node.
To successfully enable forging for a delegate, the publickey and the encrypted passphrase need to be deposited here as a JSON object.
<20> A list of peers to use as seeds when starting the node for the first time.
<21> Websocket port of the node.
<22> Minimum loglevel, that should be logged in the log file.
<23> Minimum loglevel, that should be logged in the console when starting the node.
<24> Define name and path of the log file.
Default: logs/lisk.log
<25> If true, enables cache.
Default: false
<26> Redis host IP. Default: 127.0.0.1
<27> Redis host port.
Default: 6380
<28> Set the number of databases for Redis to use.
Min: 0 (default), Max: 15.
<29> Password
<30> The host address of the database.
<31> The port of the database.
<32> The name of the database to use.
<33> Name of the database user.
<34> Password of the database user.
<35> Specifies the minimum amount of database handles.
<36> Specifies the maximum amount of database handles.
<37> This parameter sets how long to hold connection handles open.
<38> Closes & removes clients which have been idle > 1 second.
<39> Specify the minimal log level for database logs.
<40> Relative path of the database log file.
//<33> Contains options for the cache component.
//<34> Set the number of databases for Redis to use.
//Min: 0 (default), Max: 15.
//<35> If true, enables cache.
//Default: false
//<36> Redis host IP. Default: 127.0.0.1
//<37> Redis host port.
//Default: 6380
<38> Contains configurations related to modules.
<39> Contains options for the API module.
<42> Controls the API's availability.
If disabled, no API access is possible.
<40> HTTP port which the node listens on.
<41> Address of the API of the node.

<43> For nodes that sit behind a proxy.
If true, the client IP addresses are understood as the left-most entry in the X-Forwarded-* header.
<44> Contains the API access options.
<45> If true, the API endpoints of the node are available to public.
<46> This parameter allows connections to the API by IP.
Defaults to only allow local host.
<47> Options for enabling SSL with Lisk HTTP API, (alternative to enabling SSL through a Webserver).
<48> Enables SSL for HTTP requests.
<49> Port to host the Lisk Wallet on, default is 443 but is recommended to use a port above 1024 with IP tables.
<50> Interface to listen on for the Lisk Wallet.
<51> Required private key to decrypt and verify the SSL Certificate.
<52> SSL certificate to use with the Lisk Wallet.
<53> Limits for API connections.
<54> Maximum of API connections.
<55> Minimum delay between API calls in ms.
<56> Minimum delay after an API call in ms.
<57> Minimum delay between API calls from the same window.
<58> Indicating the minimum amount of time an idle connection has to be kept opened, (in seconds).
<59> Time to wait for response from server before timing out.
<60> Options for cross-origin resource sharing.
<61> Defines the domains that the resource can be accessed by in a cross-site manner.
Defaults to all domains.
<62> Defines the allowed methods for CORS.
<63> Defines who can access the forging related API endpoints of the node.
<64> This parameter allows connections to the forging API by IP.
Defaults to allow only local connections.
<65> Contains options for the chain module.
<66> Options for broadcasting events to the network.
<67> If true, enables broadcasts.
<68> Specifies how often the node will broadcast transaction bundles.
<69> Specifies how many parallel threads will be used to broadcast transactions.
<70> Specifies how many transactions can be included in a single bundle.
<71> Specifies how many times a transaction broadcast from the node will be relayed.
<72> Sets the maximum size of each transaction queue.
//<73> Contains forging options for delegates.
//<74> Forces forging to be on, only used on local development networks.
//<75> List of delegates, who are allowed to forge on this node.
//To successfully enable forging for a delegate, the publickey and the encrypted passphrase need to be deposited here as a JSON object.
//<76> Default password for dummy delegates, only used on local development networks.
<77> If true, enables syncing, (fallback for broadcasts).
<78> How many blocks to load from a peer or the database during verification.
//<79> Integer.
//If this value is defined, the node will start and rebuild up to the defined round, (set to 0 to rebuild until current round).
//Otherwise, the application continues normal execution.
<80> Contains network options for the node.
//<81> Websocket port of the node.
<82> The host IP which the P2P server should listen on for inbound connections.
This value is passed directly to the underlying Node.js server.
The listen function is documented here: https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback
//<83> A list of peers to use as seeds when starting the node for the first time.
This should be an array of objects in the following form: [{ip: '123.123.123.123', wsPort: 7000}, {ip: '111.111.111.111', wsPort: 8000}]
<84> IP or address of the seed peer.
<85> Port of the seed peer.
<86> A list of peers to blacklist.
This should be an array of objects in the followingform: [{ip: '123.123.123.123'}, {ip: '111.111.111.111'}]
<87> IP or address of the blacklisted peer.
<88> A list of peers to stay constantly connected to.
This should be an array of objects in the following form: [{ip: '123.123.123.123'}, {ip: '111.111.111.111'}]
<89> IP or address of the blacklisted peer.
<90> A list of peers which should never be banned.
This should be an array of objects in the following form: [{ip: '123.123.123.123'}, {ip: '111.111.111.111'}]
<91> IP or address of the blacklisted peer.
<92> Time interval(ms), the time that it takes the nodes to perform peer discovery.
<93> The maximum number of inbound peers/connections which the node should have.
This should be an integer.
Peers which initiate the connection to the node will be added to the node’s inbound list.
<94> The maximum number of outbound peers/connections which the node should have.
This should be an integer.
The node will keep trying to connect to new peers until it reaches maxOutboundConnections.
<95> The amount of milliseconds a peer can be banned for; in the case whereby it's reputation score falls below 0.
<96> How frequently, (in milliseconds) it takes to check and re-populate the outbound list, (as peers may drop out over time).
<97> When broadcasting a message such as a block or transaction to peers, this number determines how many peers the message will be to sent to at any one time.
<98> This number indicates the amount of peer information which the node will send back to a peer; once that peer requests the node’s peer list.
<99> This number indicates the maximum amount of peer information which can be received from a single peer, in order to populate our peer directory during the discovery.
<100> The maximum size in bytes, (integer) of a single peer information object.
A peer information object has a flexible schema, and can contain custom properties/data about the node.
<101> The maximum size in bytes, (integer) of any kind of message from a peer.
If the peer tries to send a message greater than this value, it will be immediately disconnected.
<102> When a node tries to make an RPC against a peer, (and expects a response), this value determines the maximum amount of time, (in milliseconds) that the node will wait to receive a response from the peer.
If the peer does not respond in time, then the RPC will fail with an error.
<103> When a node tries to connect to a peer, this value determines the maximum amount of time, (in milliseconds) that the node will wait to complete the handshake with the peer.
If the peer does not complete the handshake in time then the connection will be closed.
<104> This represents the low-level WebSocket engine which the node should use, (this is for advanced users).
Possible values are "ws", (default and recommended value),and "uws" (for increased performance, however this is not compatible with all systems).
