= References
Mona Bärenfänger <mona@lightcurve.io>
:description:
:toc:
:page-previous: /lisk-sdk/tutorials.html
:page-previous-title: Tutorials

:url_lisk_elements: reference/lisk-elements/index.adoc
:url_lisk_commander: reference/lisk-commander/commands.adoc
:url_lisk_packages: reference/lisk-elements/index.adoc
:url_lisk_api_client: reference/lisk-elements/api-client.adoc
:url_lisk_client: reference/lisk-elements/client.adoc
:url_lisk_constants: reference/lisk-elements/constants.adoc
:url_lisk_cryptography: reference/lisk-elements/cryptography.adoc
:url_lisk_packages: reference/lisk-elements/index.adoc
:url_lisk_p2p: reference/lisk-elements/p2p.adoc
:url_lisk_passphrase: reference/lisk-elements/passphrase.adoc
:url_lisk_trans-pool: reference/lisk-elements/transaction-pool.adoc
:url_lisk_transactions: reference/lisk-elements/transactions.adoc
:url_lisk_validator: reference/lisk-elements/validator.adoc
:url_lisk_commander_commands: reference/lisk-commander/commands.adoc
:url_lisk_core: reference/lisk-commander/lisk-core.adoc
:url_sens_inputs: reference/lisk-commander/sensitive-inputs.adoc
:url_commander_overview: reference/lisk-commander/index.adoc
:url_user_guide: reference/lisk-commander/user-guide.adoc

The references section is designed to provide the user with a comprehensive description of all the necessary specifications.
A brief description of the contents of the references are listed below, in order to assist the user in locating the relevant reference information required.

*  xref:{url_commander_overview}[Commander]

Lisk Commander is an effective, convenient and user-friendly tool designed for all levels of developers, and further useful information is included within the reference section to assist the user.

*  xref:{url_lisk_commander_commands}[Commands]

A comprehensive list of the Lisk Commander commands are covered and explained in detail together with examples in order to assist the end-user.

*  xref:{url_lisk_core}[Core commands]

The Lisk Core commands enables the user to install and manage an instance of Lisk Core, and furthermore the references provide examples and descriptions of the respective commands.

*  xref:{url_sens_inputs}[Sensitive inputs]

The sensitive inputs covers issues whereby certain sensitive crieria is required such as passphrases, etc. The various options together with examples can be found here.

*  xref:{url_lisk_elements}[Lisk Elements]

Lisk Elements is a JavaScript library containing several installable npm packages. These can be installed separately and encompass pre-dominant components of Lisk related functionalites. The package lists, set up, installation and usage information is covered here.


The references for all the following available packages are also listed below in the following subsections:


    * xref:{url_lisk_api_client}[API client]

The API client references provides the various parameters and examples to install, upgrade, and run the client, in order to interact with the API of nodes on the Lisk network.

    * xref:{url_lisk_client}[Client]

The client provides a default set of elements for users of the Lisk network, the installation, upgrade and usage information can be found here in this subsection.

    * xref:{url_lisk_constants}[Constants]

Some useful general purpose constants are covered here, including installation, upgrade, and usage references.

    * xref:{url_lisk_cryptography}[Cryptography]

Detailed comprehensive reference examples, covering the cryptography functionalities when interacting with the Lisk ecosystem can be found here, together with how to perform format conversions, encryption/decryption, hashing and managing keys.

    * xref:{url_lisk_p2p}[Peer-to-Peer]

The P2P library references which covers examples for building P2P use cases are included here, and complimented by the installation, updates and upgrade examples together with actions and events.

    * xref:{url_lisk_passphrase}[Passphrase]

The passphrase module references cover the tools, installation, upgrades and examples with the validation methods.

    * xref:{url_lisk_trans-pool}[Transactions pool]

The transaction pool library references cover examples regarding the installation,updates, constants and usage.

    * xref:{url_lisk_transactions}[Transactions]

The transactions module provides the functions for creating transactions, of which reference examples are provided here including a set of utility functions, and furthmore validation and verification examples.

    * xref:{url_lisk_validator}[Validator]

The Lisk validator is a wrapper of validation libraries including custom validation utilities, whereby installation and update examples are given.




These references have been constructed in a concise and explanatory manner, covering each specific topic to provide the user with the necessary reference information.



