= References overview
Mona Bärenfänger <mona@lightcurve.io>
:description:
:toc:

:url_lisk_commander: reference/lisk-commander/user-guide/commands.adoc
:url_lisk_core: reference/lisk-commander/user-guide/lisk-core.adoc
:url_sensitive_inputs: reference/lisk-commander/user-guide/sensitive-inputs.adoc
:url_lisk_framework: reference/lisk-framework/index.adoc
:url_lisk_packages: reference/lisk-elements/packages/index.adoc
:url_lisk_config: reference/lisk-framework/config.adoc


The reference section is designed to provide the user with a comprehensive description of all the necessary specifications, including user guides for the xref:{url_lisk_commander}[Lisk Commander], xref:{url_lisk_core}[Lisk Core], and also for xref:{url_sensitive_inputs}[sensitive inputs]. This is followed by covering the elements and xref:{url_lisk_packages}[packages], coupled with a breakdown and architectural overview of the xref:{url_lisk_framework}[Lisk framework].

Finally, the API specifications cover the endpoints, together with a detailed description of all relevant queries, examples, and transactions and much more, together with a descriptive example of the xref:{url_lisk_config}[configuration object] values.

This has been constructed in a concise and explanatory manner, covering each specific topic to provide the user with the necessary reference information.



