= Legacy account module

The legacy account module allows to migrate uninitialized legacy accounts.

[cols=",",options="header",stripes="hover"]
|===
|Name
|Property

|Name
|`legacyAccount`

|ID
|`1000`

|Assets
a|
* `ReclaimAsset`
** Name: `reclaimLSK`
** ID: `0`

|Reducers
| none

|Actions
a|
* `getUnregisteredAccount()`

|Events
| none

|===

== Transactions

The following transaction assets are provided by the legacy account module.

=== ReclaimAsset

A `reclaimLSK` transaction allows to claim tokens from uninitialized legacy accounts.
The required public key is retrieved from the sender of the `reclaimLSK` transaction.
The parameter `amount` specifies the amount of tokens that shall be reclaimed, if an uninitialized legacy account was found for the public key.

.Schema
[source,typescript]
----
const reclaimAssetSchema = {
	$id: 'lisk/legacyAccount/reclaim',
	title: 'Reclaim transaction asset',
	type: 'object',
	required: ['amount'],
	properties: {
		amount: {
			dataType: 'uint64',
			fieldNumber: 1,
		},
	},
};
----

== Actions

The following actions are provided by the legacy account module.

=== getUnregisteredAccount
Invoke this action to check if an uninitialized account exists for a provided public key.
If it exists, it returns address and balance of the account.

==== Input
[source,js]
----
{
  publicKey: string
}
----

==== Returns
Returns the address (hexadecimal representation) and balance of the uninitialized account.
Returns `undefined` if no uninitialized account is found or if the account was reclaimed already for the provided public key.

[source,js]
----
{
  address: string,
  balance: string
}
----
