= Accounts
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references regarding the Account endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
:toc:
:v_core: master

:url_lisk_core_api: {v_core}@lisk-core::reference/api.adoc


This is a resource for interacting with the `accounts` endpoint provided by the Lisk public API. Each of the following methods can be accessed via the `accounts` property of an `APIClient` instance.

== get

Searches for matching accounts in the system.

=== Syntax

[source,js]
----
get([options])
----

=== Parameters

`options`: See the options available by accessing the following link: xref:{url_lisk_core_api}[Core API documentation].

=== Return value

`Promise`: Resolves to an API response object.

=== Examples

[source,js]
----
client.accounts.get({ username: 'oliver' })
    .then(res => {
        console.log(res.data);
    })
----

== getMultisignatureGroups

This searches for the specified account in the system, and responds with a list of the multisignature groups that include the afore-mentioned specified account.

=== Syntax

[source,js]
----
getMultisignatureGroups(address, [options])
----

=== Parameters

`address`: A Lisk address string.

`options`: Please see the options in the following link: xref:{url_lisk_core_api}[Core API documentation].

=== Return value

`Promise`: Resolves to an API response object.

=== Examples

[source,js]
----
client.accounts.getMultisignatureGroups('15434119221255134066L')
    .then(res => {
        console.log(res.data);
    })
----

== getMultisignatureMemberships

This searches for the specified multisignature group and responds with a list of all members of this particular multisignature group.

=== Syntax

[source,js]
----
getMultisignatureMemberships(address, [options])
----

=== Parameters

`address`: A Lisk address string.

`options`: Please see the options in the following link: xref:{url_lisk_core_api}[Core API documentation].

=== Return value

`Promise`: Resolves to an API response object.

=== Examples

[source,js]
----
client.accounts.getMultisignatureMemberships('15434119221255134066L')
    .then(res => {
        console.log(res.data);
    })
----
