== Lisk Elements Documentation

Lisk Elements is a JavaScript library containing several
separately-installable npm packages, each covering a distinct region of
Lisk-related functionality.

* link:#lisk-elements-documentation[Introduction]
** link:#versions[Lisk Elements version reference]
** link:#setup[Setup]
*** link:#pre-installation[Pre-Installation]
*** link:#installation[Installation]
** link:#upgrade[Upgrade]
** link:#contribute-to-the-codebase[Contribute to Codebase]
* link:packages.md[Packages]: Stand-alone packages of Lisk Elements
** link:packages/api-client.md[API Client]: An API client for
interacting with nodes on the Lisk network.
** link:packages/client.md[Client]: A default set of elements for use by
clients of the Lisk network
** link:packages/constants.md[Constants]: A set of Lisk-related
constants.
** link:packages/cryptography.md[Cryptography]: Relevant cryptographic
functions.
** link:packages/passphrase.md[Passphrase]: Mnemonic passphrase helpers.
** link:packages/transactions.md[Transactions]: Functions for creating,
signing and verifying transactions.

=== Versions

Documentation on https://lisk.io/documentation[lisk.io] remains up to
date with version updates. The table below provides an overview about
the former releases and documentation versions of Lisk Elements.

[cols=",,",options="header",]
|===
|Version |Release date (yy/mm/dd) |Documentation reference
|https://www.npmjs.com/package/lisk-elements/v/2.3.0[v2.3.0] |19/08/02
|_Current version, live on lisk.io/documentation_

|https://www.npmjs.com/package/lisk-elements/v/2.2.0[v2.2.0] |19/07/24
|https://github.com/LiskHQ/lisk-docs/tree/dev-elements-2.1.0[Lisk
Elements 2.2 docs]

|https://www.npmjs.com/package/lisk-elements/v/2.1.0[v2.1.0] |19/06/24
|https://github.com/LiskHQ/lisk-docs/tree/dev-elements-2.1.0[Lisk
Elements 2.1 docs]

|https://github.com/LiskHQ/lisk-elements/releases/tag/v2.0.0[v2.0.0]
|19/01/07
|https://github.com/LiskHQ/lisk-docs/blob/elements-2.0.0/introduction.md[Lisk
Elements 2.0 docs]

|https://github.com/LiskHQ/lisk-elements/releases/tag/v1.1.3[v1.1.3]
|18/11/22
|https://github.com/LiskHQ/lisk-docs/blob/elements-1.1.0-1.0.1/introduction.md[Lisk
Elements 1.1 docs]

|https://github.com/LiskHQ/lisk-elements/releases/tag/v1.0.0[v1.0.0]
|18/08/06
|https://github.com/LiskHQ/lisk-docs/blob/elements-1.0.0-1.0.1/introduction.md[Lisk
Elements 1.0 docs]
|===

=== Setup

==== Supported Platforms

* Platforms with Node.js version 8.10 and above.

==== Pre-Installation

Lisk Elements requires https://nodejs.org/[Node.js] as the underlying
engine for code execution. This document describes how to install Node
and NPM for installation via NPM.

===== Install Node

Follow the instructions for your operating system on the
https://nodejs.org/en/download/[Node.js downloads page].

____
NPM is automatically installed along with Node.js.
____

===== Verify Installation

Confirm that Node.JS and NPM have been successfully installed by running

[source,bash]
----
node --version
npm --version
----

==== Installation

This section details how to install Lisk Elements for a given
distribution.

____
As all packages in Lisk Elements are independent from each other, they
can be installed seperately.
____

===== Installation via NPM

To install the latest version of Lisk Elements for use as a dependency
in a Node.js project, please proceed with the following:

*Complete library*

[source,bash]
----
npm install --save lisk-elements
----

*Specific package*

[source,bash]
----
npm install --save @liskhq/<package-name>
----

where `+<package-name>+` can be any of the link:packages.md[sub
packages] in Lisk Elements.

For concrete code examples for each package, check the
link:packages.md[Packages section].

Upon successful completion, NPM will add the Lisk Elements package to
your `+package.json+` file.

===== Load via CDN

Include the following script using the following HTML. The `+lisk+`
variable will be exposed.

*Client library*

[source,html]
----
<script src="https://js.lisk.io/lisk-client-2.1.1.js"></script>
----

Or minified:

[source,html]
----
<script src="https://js.lisk.io/lisk-client-2.1.1.min.js"></script>
----

To include other packages of Lisk Elements, replace `+lisk-client+` with
any of the link:packages.md[packages] of Lisk Elements.

== Upgrade

To update your installation to the latest version of Lisk Elements,
simply run the following command:

[source,bash]
----
npm update --save lisk-elements
----

=== Contribute to the Codebase

Everyone is invited to contribute to the Lisk Elements codebase. We
welcome and appreciate all contributions.

==== Github

All necessary information can be found on our
https://github.com/LiskHQ/lisk-sdk/tree/development/elements/lisk-elements[Lisk
Elements Github].

==== Contribution Guidelines

Please be sure to read and follow our
https://github.com/LiskHQ/lisk-sdk/blob/development/docs/CONTRIBUTING.md[Contribution
Guidelines].

==== Discord

If you have any further questions please join our
https://discord.gg/GA9DZmt[Lisk Discord] channel.
