= Lisk Elements Overview
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:imagesdir: ../..assets/images

Lisk Elements is a JavaScript library containing several separately-installable npm packages, each covering a distinct region of Lisk-related functionality.

== Setup

=== Supported Platforms

* Platforms with Node.js version 8.10 and above.

=== Pre-Installation

Lisk Elements requires https://nodejs.org/[Node.js] as the underlying engine for code execution.
This document describes how to install Node and NPM for installation via NPM.

==== Install Node

Follow the instructions for your operating system on the https://nodejs.org/en/download/[Node.js downloads page].

NOTE: NPM is automatically installed along with Node.js.

==== Verify Installation

Confirm that Node.JS and NPM have been successfully installed by running

[source,bash]
----
node --version
npm --version
----

=== Installation

This section details how to install Lisk Elements for a given distribution.

NOTE: As all packages in Lisk Elements are independent from each other, they can be installed seperately.

==== Installation via NPM

To install the latest version of Lisk Elements for use as a dependency in a Node.js project, please proceed with the following:

*Complete library*

[source,bash]
----
npm install lisk-elements
----

*Specific package*

[source,bash]
----
npm install @liskhq/<package-name> <1>
----

<1> `<package-name>` can be any of the xref:lisk-elements/packages.adoc[packages] in Lisk Elements.

TIP: For concrete code examples for each package, check the xref:lisk-elements/packages.adoc[Packages section].

Upon successful completion, NPM will add the Lisk Elements package to your `package.json` file.

==== Load via CDN

Include the following script using the following HTML. The `lisk` variable will be exposed.

*Client library*

[source,html]
----
<script src="https://js.lisk.io/lisk-client-2.1.1.js"></script>
----

Or minified:

[source,html]
----
<script src="https://js.lisk.io/lisk-client-2.1.1.min.js"></script>
----

To include other packages of Lisk Elements, replace `lisk-client` with any of the xref:lisk-elements/packages.adoc[packages] of Lisk Elements.

== Upgrade

To update your installation to the latest version of Lisk Elements, simply run the following command:

[source,bash]
----
npm update lisk-elements
----

== Contribute to the Codebase

Everyone is invited to contribute to the Lisk Elements codebase.
We welcome and appreciate all contributions.

=== Github

All necessary information can be found on our https://github.com/LiskHQ/lisk-sdk/tree/development/elements/lisk-elements[Lisk Elements Github].

=== Contribution Guidelines

Please be sure to read and follow our https://github.com/LiskHQ/lisk-sdk/blob/development/docs/CONTRIBUTING.md[Contribution Guidelines].

=== Discord

If you have any further questions please join our https://lisk.chat[Lisk Discord] channel.
