= Lisk Elements Documentation
Mona Bärenfänger <mona@lightcurve.io>
:toc:
:imagesdir: ../../assets/images
:v_core: 2.0

Lisk Elements is a JavaScript library containing several
separately-installable npm packages, each covering a distinct region of
Lisk-related functionality.

== Setup

=== Supported Platforms

* Platforms with Node.js version 8.10 and above.

=== Pre-Installation

Lisk Elements requires https://nodejs.org/[Node.js] as the underlying
engine for code execution. This document describes how to install Node
and NPM for installation via NPM.

==== Install Node

Follow the instructions for your operating system on the
https://nodejs.org/en/download/[Node.js downloads page].

____
NPM is automatically installed along with Node.js.
____

==== Verify Installation

Confirm that Node.JS and NPM have been successfully installed by running

[source,bash]
----
node --version
npm --version
----

=== Installation

This section details how to install Lisk Elements for a given
distribution.

____
As all packages in Lisk Elements are independent from each other, they
can be installed seperately.
____

==== Installation via NPM

To install the latest version of Lisk Elements for use as a dependency
in a Node.js project, please proceed with the following:

*Complete library*

[source,bash]
----
npm install --save lisk-elements
----

*Specific package*

[source,bash]
----
npm install --save @liskhq/<package-name>
----

where `+<package-name>+` can be any of the xref:packages.adoc[sub packages] in Lisk Elements.

For concrete code examples for each package, check the
xref:packages.adoc[Packages section].

Upon successful completion, NPM will add the Lisk Elements package to
your `+package.json+` file.

==== Load via CDN

Include the following script using the following HTML. The `+lisk+`
variable will be exposed.

*Client library*

[source,html]
----
<script src="https://js.lisk.io/lisk-client-2.1.0.js"></script>
----

Or minified:

[source,html]
----
<script src="https://js.lisk.io/lisk-client-2.1.0.min.js"></script>
----

To include other packages of Lisk Elements, replace `+lisk-client+` with
any of the xref:packages.adoc[packages] of Lisk Elements.

== Upgrade

If you already have Lisk Elements installed and wish to upgrade your
installation, you can follow the instructions below for your specific
distribution.

=== Upgrade Lisk Elements via NPM

To update your global installation to the latest version of Lisk
Elements, simply run the following command:

[source,bash]
----
npm update --save lisk-elements
----

=== Upgrade Lisk Elements via CDN

When a new release is available, simply update the version number
accordingly. For example, if you want to upgrade from v2.0.0 (minified)
to v2.1.0 (minified), change this line:

[source,html]
----
<script src="https://js.lisk.io/lisk-elements-2.0.0.min.js"></script>
----

to this:

[source,html]
----
<script src="https://js.lisk.io/lisk-elements-2.1.0.min.js"></script>
----

== Contribute to the Codebase

Everyone is invited to contribute to the Lisk Elements codebase. We
welcome and appreciate all contributions.

=== Github

All necessary information can be found on our
https://github.com/LiskHQ/lisk-sdk/tree/development/elements/lisk-elements[Lisk Elements Github].

=== Contribution Guidelines

Please be sure to read and follow our
https://github.com/LiskHQ/lisk-sdk/blob/development/docs/CONTRIBUTING.md[Contribution Guidelines].

=== Discord

If you have any further questions please join our
https://discord.gg/GA9DZmt[Lisk Discord] channel.
