= Lisk Elements Packages
Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk Elements packages page provides an overview regarding all available packages of Lisk Elements and direct links to their associated technical references. In addition, it also comprises of the basic usage of a Lisk Elements package.
:toc:

This section details how to use Lisk Elements after a succesfull installation has been completed.

== Package list

[options=header]
|===
|Name | NPM | Specification

| API Client
| https://www.npmjs.com/package/@liskhq/lisk-api-client[@liskhq/lisk-api-client]
| xref:lisk-elements/packages/api-client.adoc[lisk-api-client docs]

| Client
| https://www.npmjs.com/package/@liskhq/lisk-client[@liskhq/lisk-client]
| xref:lisk-elements/packages/client.adoc[lisk-client docs]

| Constants
| https://www.npmjs.com/package/@liskhq/lisk-constants[@liskhq/lisk-constants]
| xref:lisk-elements/packages/constants.adoc[lisk-constants docs]

| Cryptography
| https://www.npmjs.com/package/@liskhq/lisk-cryptography[@liskhq/lisk-cryptography]
| xref:lisk-elements/packages/cryptography.adoc[lisk-cryptography docs]

| Passphrase
| https://www.npmjs.com/package/@liskhq/lisk-passphrase[@liskhq/lisk-passphrase]
| xref:lisk-elements/packages/passphrase.adoc[lisk-passphrase docs]

| Transactions
| https://www.npmjs.com/package/@liskhq/lisk-transactions[@liskhq/lisk-transactions]
| xref:lisk-elements/packages/transactions.adoc[lisk-transactions docs]
|===

== Usage

=== Node.js

Simply import, (or require) the package and access its functionality according to the relevant namespace.

*Example for client package:*

[source,js]
----
import lisk from '@liskhq/lisk-client';
//or
const lisk = require('@liskhq/lisk-client');
const transaction = lisk.transaction.transfer({
    amount: '100000000',
    recipientId: '15434119221255134066L',
    passphrase: 'robust swift grocery peasant forget share enable convince deputy road keep cheap',
});
----

*Example for sub packages:*

[source,js]
----
import * as transactions from '@liskhq/lisk-transactions';

transactions.transfer({
    amount: '123000000',
    recipientId: '12668885769632475474L',
});
----

=== Browser

Load the Lisk Elements script via the CDN.
For example, to load the minified version 2.3.1 of Lisk Elements, include the following script which will then expose the `lisk` variable:

[source,html]
----
<script src="https://js.lisk.io/lisk-client-2.3.1.min.js"></script>
<script>
    const transaction = lisk.transaction.transfer({
        amount: '100000000',
        recipientId: '15434119221255134066L',
        passphrase: 'robust swift grocery peasant forget share enable convince deputy road keep cheap',
    });
</script>
----
